import type { Day } from '../../types';

/** BLENDER trek, 11–17. nap. */
export const blenderHuC: Day[] = [
  {
    day: 11,
    title: 'Boolean műveletek',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **boolean** két test összevetése: egyesítés, kivonás vagy metszet. Ugyanaz a gondolat, mint CAD-ben, csak itt a háló szintjén történik — és ettől trükkösebb.' },
      { k: 'text', md: 'Használat: a Boolean egy **módosító** (Modifier Properties → Add Modifier → Boolean). Beállítod a műveletet, kiválasztod a másik tárgyat, és az eredmény azonnal látszik.\n\n- **Difference** — kivonás: lyukat vág\n- **Union** — összeolvasztás egy testté\n- **Intersect** — csak a közös rész marad' },
      { k: 'callout', tone: 'key', md: 'A boolean addig **élő**, amíg nem alkalmazod (Apply). Élő állapotban a vágótestet mozgathatod, és a lyuk követi. Ez a boolean legnagyobb ereje: a lyuk helye utólag is változtatható.' },
      { k: 'text', md: 'A vágótestet érdemes elrejteni a nézetből (H), vagy a Object Properties → Viewport Display → Display As: **Wire** beállítással drótvázra tenni. Így látod, hol van, de nem takar.' },
      { k: 'callout', tone: 'warn', md: 'A boolean **rendetlen topológiát** hagy: háromszögeket és n-gonokat a vágás mentén. Sima felületen ez látszik az árnyékban. Két ellenszer: (1) a vágás előtt legyen sűrű és egyenletes a háló, (2) a boolean után kézzel tisztítsd az éleket.' },
      { k: 'callout', tone: 'tip', md: 'A vágótest **lapjai nézzenek kifelé**, és legyen zárt (ne legyen lyukas). Nyitott vagy kifordult normálisú testtel a boolean kiszámíthatatlan eredményt ad. Ellenőrzés: Overlays → Face Orientation, a kék a jó, a piros a kifordult.' },
    ],
    quiz: [
      { k: 'single', q: 'Melyik boolean művelet vág lyukat?', opts: ['Union', 'Difference', 'Intersect'], answer: 1, why: 'A Difference kivonja a második testet az elsőből — ez a lyukvágás.' },
      { k: 'single', q: 'Mi az előnye annak, hogy a boolean módosító marad, nem alkalmazod?', opts: ['Gyorsabb a render', 'A vágótest utólag mozgatható, a lyuk követi', 'Kevesebb helyet foglal'], answer: 1, why: 'Élő módosítóként a vágás paraméteres marad: a lyuk helye, mérete bármikor változtatható.' },
      { k: 'single', q: 'Milyen hibát hagy jellemzően a boolean?', opts: ['Eltűnik a tárgy színe', 'Rendetlen topológiát: háromszögeket és n-gonokat a vágás mentén', 'Megnő a fájlméret tízszeresére'], answer: 1, why: 'A vágásvonal mentén a Blender úgy osztja fel a lapokat, ahogy tudja. Sima felületen ez árnyékhibaként jelenik meg.' },
      { k: 'single', q: 'Milyen legyen a vágótest?', opts: ['Nyitott, hogy átférjen', 'Zárt, kifelé néző lapokkal', 'Mindegy'], answer: 1, why: 'A boolean algoritmusnak tudnia kell, mi van „belül". Ehhez zárt test és helyes normálisok kellenek.' },
      { k: 'order', q: 'Milyen sorrendben vágsz lyukat boolean-nal?', items: ['Difference beállítása és a vágótest kijelölése', 'A vágótest elhelyezése a kívánt helyre', 'A vágótest elrejtése vagy drótvázra tétele', 'Boolean módosító hozzáadása a fő testhez'], correct: [1, 3, 0, 2], why: 'Előbb a vágótest a helyére, aztán módosító a fő testre, művelet beállítása, végül a vágótest eltüntetése a nézetből.' },
    ],
    note: {
      summary: ['A boolean két test összevetése: Union, Difference, Intersect.', 'Módosítóként élő marad: a vágótest utólag mozgatható.', 'Difference = lyukvágás, Union = összeolvasztás, Intersect = közös rész.', 'A vágótest legyen zárt és kifelé néző lapokkal.', 'A boolean rendetlen topológiát hagy; sima felületen ez árnyékhiba.'],
      terms: [{ term: 'boolean', def: 'Két test halmazművelete: egyesítés, kivonás, metszet.' }, { term: 'vágótest', def: 'A segédtárgy, amivel vágsz; rendszerint rejtett.' }, { term: 'normális', def: 'A lap „kifelé" iránya; kifordulva hibás eredményt ad.' }],
    },
  },
  {
    day: 12,
    title: 'Görbék és profilok',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **görbe** (Curve) nem háló: matematikai vonal, néhány vezérlőponttal. Kábel, cső, korlát, felirat vonalvezetése — mind görbével készül a legkönnyebben.' },
      { k: 'text', md: 'Add → Curve → **Bézier** vagy **Path (NURBS)**. A Bézier pontjainak fogantyúi vannak, amikkel a görbület állítható; a Path egyszerűbb, egyenletesebb.\n\nSzerkesztő módban: **E** új pontot húz a végéhez, **F** két pontot összeköt, **X** töröl.' },
      { k: 'callout', tone: 'key', md: 'A görbe akkor lesz látható test, ha **vastagságot** adsz neki. Object Data Properties → Geometry → **Bevel**:\n\n- **Round** + Depth → kerek keresztmetszet, azaz cső vagy kábel\n- **Object** → egy másik görbe lesz a keresztmetszet profilja' },
      { k: 'text', md: 'A **Bevel → Object** a legerősebb: rajzolsz egy kis zárt görbét (például egy L alakot), és azt húzod végig az útvonalon. Így készül a léc, a sín, a díszléc — egyetlen profilból bármilyen hosszon.' },
      { k: 'callout', tone: 'tip', md: 'Ha a profil elfordul az út mentén, a **Tilt** (Ctrl+T szerkesztő módban) vagy az Object Data → Twist Method beállítás igazítja. A „Minimum" módszer a legtöbb esetben jó.' },
      { k: 'text', md: 'Ha végeztél, Object → **Convert → Mesh** hálóvá alakítja. Ezután már szerkesztheted pontonként — de a paraméteres szabadságot elveszted, úgyhogy csak a végén konvertálj.' },
    ],
    quiz: [
      { k: 'single', q: 'Mitől lesz a görbéből látható test?', opts: ['Ha kijelölöd', 'Ha Bevel-lel vastagságot adsz neki', 'Ha átszínezed'], answer: 1, why: 'A görbe önmagában vonal. A Bevel ad neki keresztmetszetet, és ettől lesz cső vagy léc.' },
      { k: 'single', q: 'Mire jó a Bevel → Object beállítás?', opts: ['Egy másik görbe lesz a keresztmetszet profilja', 'Megkettőzi a görbét', 'Lekerekíti a sarkokat'], answer: 0, why: 'Így tetszőleges profilt — L alakot, csősarkot, díszlécet — húzhatsz végig az útvonalon.' },
      { k: 'single', q: 'Mikor érdemes a görbét hálóvá konvertálni?', opts: ['Rögtön a rajzolás után', 'A legvégén, amikor már nem akarod paraméteresen állítani', 'Soha'], answer: 1, why: 'A konverzió egyirányú: utána a vonalvezetés már nem állítható fogantyúkkal.' },
      { k: 'single', q: 'Mit csinál az E billentyű görbe szerkesztő módban?', opts: ['Törli a pontot', 'Új pontot húz a görbe végéhez', 'Bezárja a görbét'], answer: 1, why: 'Ugyanaz az extrude gondolat, mint hálónál: a kijelölt végpontból új szakaszt húz.' },
    ],
    note: {
      summary: ['A görbe matematikai vonal vezérlőpontokkal, nem háló.', 'Bevel ad neki keresztmetszetet: Round = cső, Object = tetszőleges profil.', 'Szerkesztő mód: E új pont, F összekötés, X törlés.', 'A Tilt vagy a Twist Method igazítja az elfordult profilt.', 'Convert → Mesh hálóvá alakít, de elveszik a paraméteres szabadság.'],
      terms: [{ term: 'Bézier-görbe', def: 'Vezérlőpontokkal és fogantyúkkal formált sima vonal.' }, { term: 'bevel', def: 'A görbének adott keresztmetszet, amitől testté válik.' }, { term: 'profil', def: 'A keresztmetszet alakja, amit az útvonalon végighúzol.' }],
    },
  },
  {
    day: 13,
    title: 'Anyagok alapjai',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az **anyag** (Material) mondja meg, hogyan veri vissza a felület a fényt. A Blender alap anyaga a **Principled BSDF** — egyetlen csomópont, ami szinte minden valós anyagot le tud írni.' },
      { k: 'text', md: 'A négy legfontosabb beállítása:\n\n- **Base Color** — az alapszín\n- **Metallic** — fémes-e (0 vagy 1, köztes érték a valóságban ritka)\n- **Roughness** — mennyire szórt a tükröződés (0 = tükör, 1 = matt)\n- **IOR / Transmission** — átlátszóság és fénytörés' },
      { k: 'callout', tone: 'key', md: 'A **Roughness** a legfontosabb. Az emberi szem ebből olvassa ki, mit lát: a 0,1-es roughness lakkozott, a 0,4-es műanyag, a 0,8-as kréta. Ha egy render „műanyagnak" néz ki, rendszerint a roughness egységes és túl alacsony.' },
      { k: 'text', md: 'A Metallic kétállapotú a gyakorlatban. **Fém**: Metallic = 1, és a Base Color adja a tükröződés színét (arany = sárgás, réz = vöröses). **Nem fém**: Metallic = 0, és a tükröződés mindig fehér, függetlenül a színtől.' },
      { k: 'callout', tone: 'warn', md: 'Egy tárgynak **több anyaga** is lehet: a Material Properties listájába veszel fel újat, szerkesztő módban kijelölöd a lapokat, és **Assign**. Így lesz a vezérlőpulton fekete gombsor és szürke ház egyetlen hálón.' },
      { k: 'text', md: 'A **Shading** munkaterületen (felső fülsor) nyílik a csomópontszerkesztő. Itt látod az anyagot grafként: dobozok, amik között kábelek futnak. Egyelőre elég, ha a Principled BSDF csúszkáit érted — a következő napokon kötünk rá textúrát.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit állít a Roughness?', opts: ['A tárgy méretét', 'Mennyire szórt a tükröződés: 0 = tükör, 1 = matt', 'Az átlátszóságot'], answer: 1, why: 'A roughness szórja szét a visszavert fényt. Ez a legerősebb anyagjelzés a szem számára.' },
      { k: 'single', q: 'Mi igaz a Metallic értékre a gyakorlatban?', opts: ['Jellemzően 0 vagy 1, köztes érték ritka', 'Mindig 0,5 körül jó', 'A fényerőt állítja'], answer: 0, why: 'A valóságban egy anyag vagy fém, vagy nem. A köztes értéknek jellemzően nincs fizikai megfelelője.' },
      { k: 'single', q: 'Mi adja a fém tükröződésének színét?', opts: ['A fény színe', 'A Base Color', 'A Roughness'], answer: 1, why: 'Fémnél (Metallic = 1) a Base Color színezi a tükröződést. Nem fémnél a tükröződés mindig fehér.' },
      { k: 'single', q: 'Hogyan adsz egy hálónak két különböző anyagot?', opts: ['Nem lehet', 'Két anyagot veszel fel a listába, szerkesztő módban kijelölöd a lapokat és Assign', 'Két tárgyra kell vágni'], answer: 1, why: 'Az anyaglista tárgyanként több bejegyzést tart, és laponként rendelheted hozzá őket.' },
      { k: 'order', q: 'Milyen sorrendben teszel egy gombsort más anyagúra?', items: ['A gombok lapjainak kijelölése szerkesztő módban', 'Assign gomb', 'Új anyag felvétele a listába'], correct: [2, 0, 1], why: 'Előbb létezzen a második anyag, aztán jelöld ki a lapokat, és rendeld hozzá az Assign gombbal.' },
    ],
    note: {
      summary: ['A Principled BSDF egyetlen csomópontban leír szinte minden anyagot.', 'Base Color, Metallic, Roughness, Transmission — a négy fő csúszka.', 'Roughness: 0 tükör, 0,1 lakk, 0,4 műanyag, 0,8 kréta.', 'Metallic a gyakorlatban 0 vagy 1; fémnél a Base Color színezi a tükröződést.', 'Egy hálóhoz több anyag rendelhető laponként, Assign gombbal.'],
      terms: [{ term: 'Principled BSDF', def: 'A Blender általános anyagcsomópontja.' }, { term: 'roughness', def: 'A felület érdessége; szórja a visszavert fényt.' }, { term: 'metallic', def: 'Fémes-e a felület; gyakorlatban 0 vagy 1.' }],
    },
  },
  {
    day: 14,
    title: 'Fém, műanyag, üveg',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Három recept, amit érdemes fejből tudni. Minden robotalkatrész, burkolat és ablak ebből a háromból épül.' },
      { k: 'text', md: '**Csiszolt alumínium**\n\n- Metallic = 1\n- Base Color = világos semleges szürke (0,8 körül)\n- Roughness = 0,25–0,35\n\nA kulcs a közepes roughness: a tükör-alumínium hamisnak néz ki, mert a valódi fémen mindig van csiszolás.' },
      { k: 'text', md: '**Matt ABS műanyag** (3D-nyomtatott alkatrész)\n\n- Metallic = 0\n- Base Color = a nyomtatószál színe\n- Roughness = 0,45–0,6\n\nEhhez jön majd a rétegvonal textúra — enélkül túl tökéletes.' },
      { k: 'text', md: '**Üveg**\n\n- Metallic = 0\n- Transmission = 1\n- Roughness = 0 (vagy 0,05 matt üveghez)\n- IOR = 1,45–1,52' },
      { k: 'callout', tone: 'key', md: 'Az üveg **csak akkor néz ki jól, ha van mit tükröznie**. Üres, fekete háttér előtt az üveg sötét kocka lesz. Ezért kell HDRI környezet vagy legalább néhány fényforrás és fal.' },
      { k: 'callout', tone: 'warn', md: 'Az üveg az **EEVEE** motorban csak közelítés: a valódi fénytörés **Cycles**-ben számolódik. Ha üveg van a jelenetben, és fontos a pontos kép, válts Cycles-re a Render Properties-ben.' },
      { k: 'callout', tone: 'tip', md: 'Kezdd mindig a roughness-szel, ne a színnel. Állítsd be a roughness-t egy semleges szürkével, és csak akkor adj színt, amikor a felület már helyesen csillog.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a csiszolt alumínium beállítása?', opts: ['Metallic 0, Roughness 0', 'Metallic 1, Roughness 0,25–0,35', 'Transmission 1'], answer: 1, why: 'Fém, de nem tükör: a valódi alumíniumon csiszolás van, ettől szórt a tükröződés.' },
      { k: 'single', q: 'Miért néz ki rosszul az üveg üres fekete háttér előtt?', opts: ['Hibás az anyag', 'Mert az üveg azt mutatja, ami körülötte van — ha nincs semmi, sötét marad', 'Túl kicsi a tárgy'], answer: 1, why: 'Az üveg tükröz és tör. Környezet nélkül nincs mit mutatnia.' },
      { k: 'single', q: 'Melyik render motor számol valódi fénytörést?', opts: ['EEVEE', 'Cycles', 'Workbench'], answer: 1, why: 'A Cycles sugárkövetéssel dolgozik, ezért az üveg és a kausztika is helyes benne. Az EEVEE közelít.' },
      { k: 'single', q: 'Mennyi az üveg IOR értéke jellemzően?', opts: ['1,0', '1,45–1,52', '3,0'], answer: 1, why: 'A közönséges ablaküveg törésmutatója 1,5 körül van. Víz 1,33, gyémánt 2,4.' },
    ],
    note: {
      summary: ['Alumínium: Metallic 1, szürke base color, Roughness 0,25–0,35.', 'ABS műanyag: Metallic 0, Roughness 0,45–0,6.', 'Üveg: Transmission 1, Roughness 0, IOR 1,45–1,52.', 'Az üveghez környezet kell, különben sötét kocka marad.', 'Pontos üveghez Cycles kell; az EEVEE csak közelít.'],
      terms: [{ term: 'IOR', def: 'Törésmutató: mennyire töri meg az anyag a fényt.' }, { term: 'transmission', def: 'Mennyi fény halad át az anyagon.' }, { term: 'Cycles', def: 'A Blender sugárkövetéses, fizikailag pontos render motorja.' }],
    },
  },
  {
    day: 15,
    title: 'UV kibontás',
    minutes: 25,
    lesson: [
      { k: 'text', md: 'A textúra lapos kép. A modell térbeli. Az **UV kibontás** mondja meg, a kép melyik pontja hova kerül a felületen — mint amikor egy kartondobozt szétnyitsz és kiterítesz.' },
      { k: 'callout', tone: 'key', md: 'Az U és a V a textúra két tengelye (az X, Y, Z már foglalt a térre). A háló minden pontjához tartozik egy UV koordináta: ez a megfeleltetés a kibontás.' },
      { k: 'text', md: 'A folyamat két lépés:\n\n1. **Varratok (seam) kijelölése** — szerkesztő módban élkijelölés, majd jobb gomb → **Mark Seam**. A varrat mentén nyílik szét a felület.\n2. **Kibontás** — minden kijelölve (A), majd **U → Unwrap**.' },
      { k: 'text', md: 'Varratot oda tegyél, ahol a valóságban is varrat lenne, vagy ahol nem látszik: a tárgy hátuljára, élek mentén, belső sarkokba. Egy hengeren egy függőleges varrat elég; egy kockán az élek mentén négy-öt.' },
      { k: 'callout', tone: 'tip', md: 'Egyszerű formákra nem kell varrat: **U → Smart UV Project** automatikusan feldarabolja a hálót szög szerint. Robotalkatrészekhez, csavarokhoz, dobozokhoz ez rendszerint elég jó.' },
      { k: 'text', md: 'Az eredményt az **UV Editing** munkaterületen látod: bal oldalt a kiterített lapok, jobb oldalt a modell. Ellenőrzés: tedd fel a Blender beépített **UV Grid** képét (az UV szerkesztőben New → Generated Type: UV Grid). Ha a kockák mindenhol nagyjából azonos méretűek és négyzetesek, a kibontás jó.' },
      { k: 'callout', tone: 'warn', md: 'A **nyújtás** a leggyakoribb hiba: ha a rácskockák valahol megnyúlnak, ott a textúra is nyúlni fog. Ilyenkor több varrat kell, hogy a felület laposabban terüljön ki.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az UV kibontás?', opts: ['A modell lapjainak törlése', 'Megfeleltetés a felület pontjai és a lapos textúra pontjai között', 'A modell kicsinyítése'], answer: 1, why: 'Minden hálópont kap egy U,V koordinátát a textúrán. Ez mondja meg, hova kerül a kép.' },
      { k: 'single', q: 'Mire való a varrat (seam)?', opts: ['Erősíti a hálót', 'Megmondja, hol nyíljon szét a felület a kiterítéskor', 'Törli az éleket'], answer: 1, why: 'Mint a ruhaszabásnál: a varrat mentén lehet a térbeli felületet síkba teríteni.' },
      { k: 'single', q: 'Mivel ellenőrzöd a kibontás minőségét?', opts: ['Az UV Grid tesztképpel: a kockák legyenek egyforma méretűek és négyzetesek', 'Szemre', 'A fájlmérettel'], answer: 0, why: 'A rácsos tesztkép azonnal megmutatja a nyújtást és a méretarány-eltéréseket.' },
      { k: 'single', q: 'Mikor jó a Smart UV Project?', opts: ['Emberi arcnál', 'Egyszerű, szögletes formáknál: alkatrész, doboz, csavar', 'Soha'], answer: 1, why: 'Szög szerint darabol. Szerves formáknál ronda darabokat hagy, de műszaki tárgyaknál rendszerint elég.' },
      { k: 'order', q: 'Milyen sorrendben bontasz ki UV-t kézzel?', items: ['U → Unwrap', 'Mark Seam', 'Ellenőrzés UV Grid tesztképpel', 'Élek kijelölése a varratnak'], correct: [3, 1, 0, 2], why: 'Élkijelölés, varrat jelölése, kibontás, végül ellenőrzés tesztképpel.' },
    ],
    note: {
      summary: ['Az UV kibontás a térbeli felületet lapos textúrakoordinátákra képezi le.', 'U és V a textúra két tengelye.', 'Varrat (Mark Seam) mentén nyílik szét a felület.', 'Varratot rejtett helyre tegyél: hátulra, élek mentén.', 'Smart UV Project automatikusan darabol — műszaki formákra elég.', 'UV Grid tesztképpel ellenőrizd a nyújtást.'],
      terms: [{ term: 'UV', def: 'A textúra két koordinátatengelye.' }, { term: 'varrat (seam)', def: 'Él, ami mentén a felület kiterítéskor szétnyílik.' }, { term: 'nyújtás', def: 'Torzulás, amikor a textúra aránytalanul feszül a felületen.' }],
    },
  },
  {
    day: 16,
    title: 'Textúrák használata',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A textúra kép, ami egy anyagtulajdonságot vezérel pontról pontra. Nem csak színt: érdességet, domborzatot, fémességet is.' },
      { k: 'text', md: 'A Shading munkaterületen **Add → Texture → Image Texture**, majd a kimenetét bekötöd a Principled BSDF megfelelő bemenetére:\n\n- **Base Color** — a szín-, azaz albedo térkép\n- **Roughness** — érdességtérkép (szürkeárnyalatos)\n- **Normal** — domborzat, Normal Map csomóponton keresztül' },
      { k: 'callout', tone: 'key', md: 'A **normal map** nem alakítja át a geometriát: megváltoztatja, merre „néz" a felület a fényszámításnál. Ettől lesz látszólag érdes vagy csavarmenetes a sima lap — nulla extra poligonból.' },
      { k: 'callout', tone: 'warn', md: 'A **színteret** el kell találni. Az albedo (szín) térkép sRGB, minden más — roughness, normal, metallic, displacement — **Non-Color**. Ha ezt elrontod, a render tompa vagy túl kontrasztos lesz, és nehéz rájönni, miért.' },
      { k: 'text', md: 'Ha nincs kész textúrád, a Blender **eljárásos** textúrákat is kínál: Noise, Voronoi, Musgrave, Wave. Ezek képlettel számolódnak, tehát végtelen felbontásúak és nem kell hozzájuk UV. Kopás, rozsda, karc, fafelület mind megépíthető belőlük.' },
      { k: 'callout', tone: 'tip', md: 'A legjobb első lépés egy unalmas anyag életre keltéséhez: kösd egy **Noise Texture**-t a Roughness-re, kis erősséggel (Color Ramp-pel 0,35 és 0,5 közé szorítva). Az egyenetlen érdesség azonnal valóságossá teszi a felületet.' },
      { k: 'text', md: 'A **Mapping** és **Texture Coordinate** csomópontpárral lehet a textúrát mozgatni, forgatni, méretezni. Ez a két doboz szinte minden összetett anyagban ott van.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit csinál a normal map?', opts: ['Elmozdítja a pontokat', 'Megváltoztatja a felület látszólagos irányát a fényszámításnál', 'Átszínezi a tárgyat'], answer: 1, why: 'A geometria sima marad, csak a megvilágítás viselkedik úgy, mintha érdes lenne. Ez nagyon olcsó részletesség.' },
      { k: 'single', q: 'Milyen színtér kell egy roughness térképhez?', opts: ['sRGB', 'Non-Color', 'Filmic'], answer: 1, why: 'Csak az albedo sRGB. Minden adat jellegű térkép Non-Color, különben a Blender gamma-korrekciót alkalmaz rá, és elromlanak az értékek.' },
      { k: 'single', q: 'Mi az eljárásos textúra előnye?', opts: ['Kisebb a fájl és nem kell hozzá UV, mert képlettel számolódik', 'Mindig szebb', 'Gyorsabb a render'], answer: 0, why: 'Végtelen felbontás, nincs ismétlődés, és UV nélkül is működik 3D koordinátákkal.' },
      { k: 'single', q: 'Mi a leggyorsabb mód egy lapos anyag feljavítására?', opts: ['Növeld a fényerőt', 'Köss egy gyenge Noise Texture-t a Roughness-re', 'Tedd át Metallic 1-re'], answer: 1, why: 'A valóságban soha nem egyenletes az érdesség. Már egy kicsi változatosság is eltünteti a „CG műanyag" érzetet.' },
    ],
    note: {
      summary: ['A textúra bármely anyagtulajdonságot vezérelhet, nem csak a színt.', 'Image Texture csomópont → Base Color / Roughness / Normal.', 'A normal map a fényszámítást csapja be, a geometria sima marad.', 'Színtér: albedo = sRGB, minden más = Non-Color.', 'Eljárásos textúrák (Noise, Voronoi) UV nélkül, végtelen felbontással működnek.', 'Gyenge Noise a Roughness-en azonnal valóságosabbá tesz.'],
      terms: [{ term: 'albedo', def: 'A felület saját színe, megvilágítás nélkül.' }, { term: 'normal map', def: 'Textúra, ami a felület látszólagos irányát módosítja.' }, { term: 'Non-Color', def: 'Színtér adat jellegű textúrákhoz, gamma-korrekció nélkül.' }],
    },
  },
  {
    day: 17,
    title: 'Világítás: a hárompontos felállás',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A fény többet dönt a végeredményről, mint a modell. Egy közepes modell jó fényben eladható; egy tökéletes modell rossz fényben lapos.' },
      { k: 'text', md: 'A Blender négy lámpatípusa:\n\n- **Point** — izzó, minden irányba\n- **Sun** — párhuzamos sugarak, a helye mindegy, csak a szöge számít\n- **Spot** — kúp, színpadi reflektor\n- **Area** — téglalap vagy kör, ez a legjobb választás a legtöbb esetben' },
      { k: 'callout', tone: 'key', md: 'A **lámpa mérete szabja meg az árnyék lágyságát**. Nagy area lámpa = lágy, elmosódott árnyék (mint felhős égen). Kis lámpa = éles, kemény árnyék (mint tűző napon). Ez a legfontosabb egyetlen szabály a világításban.' },
      { k: 'text', md: 'A **hárompontos felállás**:\n\n1. **Key** (fő fény) — a legerősebb, 30–45 fokkal oldalra és felfelé a kamerától. Ez rajzolja a formát.\n2. **Fill** (derítő) — a másik oldalról, a key erejének negyede-fele. Felnyitja az árnyékot, de nem töröl.\n3. **Rim / Back** (kontúr) — hátulról, a tárgy mögül. Fénycsíkot húz a kontúr mentén, és elválasztja a tárgyat a háttértől.' },
      { k: 'callout', tone: 'tip', md: 'Építsd **egyesével**. Kapcsold ki mind, tedd be a keyt, és állítsd be egyedül. Aztán a fillt, aztán a rimet. Ha egyszerre rakod be mind a hármat, sosem fogod tudni, melyik mit csinál.' },
      { k: 'text', md: 'A gyors alternatíva a **HDRI**: World Properties → Color → Environment Texture, és betöltesz egy gömbpanoráma képet. Ez egyszerre ad fényt, színt és tükröződést minden irányból. Termékrenderhez és üveghez sokszor ez önmagában elég.' },
      { k: 'callout', tone: 'warn', md: 'A lámpa ereje **wattban** van, és a távolság négyzetével gyengül. Ha kétszer messzebb teszed, négyszer akkora teljesítmény kell. Ne a szemed csald meg a kitettséggel — a lámpát állítsd.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi szabja meg az árnyék lágyságát?', opts: ['A lámpa ereje', 'A lámpa mérete', 'A lámpa színe'], answer: 1, why: 'Nagy fényforrás = lágy árnyék, kicsi = kemény. Az erő a fényességet állítja, nem a lágyságot.' },
      { k: 'single', q: 'Mi a fill fény szerepe?', opts: ['Ez a legerősebb fény', 'Felnyitja az árnyékot a key másik oldaláról, gyengébben', 'Kontúrt rajzol hátulról'], answer: 1, why: 'A fill a key árnyékába világít be, jellemzően negyed-fél erővel. Nem törli az árnyékot, csak olvashatóvá teszi.' },
      { k: 'single', q: 'Melyik lámpatípusnál mindegy a pozíció, csak a szög számít?', opts: ['Point', 'Sun', 'Area'], answer: 1, why: 'A Sun végtelen távoli párhuzamos sugarakat ad. Csak az iránya számít.' },
      { k: 'single', q: 'Mit ad a HDRI környezet?', opts: ['Csak hátteret', 'Fényt, színt és tükröződést minden irányból egyszerre', 'Nagyobb felbontást'], answer: 1, why: 'A gömbpanoráma megvilágítja a jelenetet, és meg is jelenik a tükröződő felületeken — ettől hihető az üveg és a fém.' },
      { k: 'order', q: 'Milyen sorrendben építed a hárompontos világítást?', items: ['Rim (kontúr) hátulról', 'Fill a másik oldalról, gyengébben', 'Key beállítása egyedül'], correct: [2, 1, 0], why: 'Egyesével: key, fill, rim. Így tudod, melyik fény mit okoz.' },
    ],
    note: {
      summary: ['A fény többet dönt a végeredményről, mint a modell.', 'Lámpatípusok: Point, Sun, Spot, Area — rendszerint az Area a jó.', 'A lámpa mérete szabja meg az árnyék lágyságát, nem az ereje.', 'Hárompontos felállás: key (fő), fill (derítő), rim (kontúr).', 'Építsd egyesével, hogy lásd, melyik fény mit csinál.', 'A HDRI egyszerre ad fényt, színt és tükröződést.'],
      terms: [{ term: 'key light', def: 'A fő fény, ami a formát rajzolja.' }, { term: 'fill light', def: 'Derítő fény, ami felnyitja az árnyékot.' }, { term: 'HDRI', def: 'Nagy dinamikatartományú gömbpanoráma, ami megvilágítja a jelenetet.' }],
    },
  },
];
