import type { Track } from '../../types';
import { blenderHuB } from './blender-b';
import { blenderHuC } from './blender-c';
import { blenderHuD } from './blender-d';

export const blenderHu: Track = {
  id: 'blender',
  title: 'Blender 3D',
  blurb: 'Modellezés, anyagok, világítás és renderelés Blenderben.',
  plannedTitles: [
    'A Blender felülete',
    'Navigáció a térben',
    'Objektumok mozgatása',
    'Szerkesztő mód: pont, él, lap',
    'Extrude és inset',
    'Loop cut és felosztás',
    'Módosítók: Mirror és Subdivision',
    'Bevel és élsimítás',
    'Egy egyszerű tárgy megmodellezése',
    'Topológia: miért számít?',
    'Boolean műveletek',
    'Görbék és profilok',
    'Anyagok alapjai',
    'Fém, műanyag, üveg',
    'UV kibontás',
    'Textúrák használata',
    'Világítás: a hárompontos felállás',
    'HDRI és környezeti fény',
    'Kamera és képkivágás',
    'Renderelés: EEVEE és Cycles',
    'Rendersebesség és zaj',
    'Kompozitálás alapok',
    'Armature és csontváz',
    'Hitelesítés és súlyozás',
    'Kulcskockás animáció',
    'Grafikonszerkesztő',
    'Fizikai szimuláció',
    'Exportálás nyomtatásra',
    'A robotod megmodellezése',
    'Kész render a portfólióba',
  ],
  days: [
    {
      day: 1,
      title: 'A Blender felülete',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'A Blender hírhedten ijesztő elsőre. Pedig a felülete néhány területből áll, és ha ezt a néhányat érted, a többi már csak gomb.' },
        { k: 'text', md: '- **3D nézet** — középen, itt dolgozol.\n- **Outliner** — jobbra fent: minden objektum listája.\n- **Properties** — jobbra lent: a kiválasztott dolog beállításai.\n- **Timeline** — alul: az animáció ideje.\n- **Fejléc** — a nézet tetején: mód és eszközök.' },
        { k: 'callout', tone: 'key', md: 'A Blender **módokban** működik. Objektum módban egész tárgyakat mozgatsz, szerkesztő módban a tárgy pontjait. Ugyanaz a billentyű mást csinál a két módban — ez okozza a kezdők zavarának felét. A váltás: **Tab**.' },
        { k: 'text', md: 'A három billentyű, amit a legtöbbet fogsz használni:\n\n- **G** (grab) — mozgatás\n- **R** (rotate) — forgatás\n- **S** (scale) — méretezés\n\nMindegyik után nyomhatsz **X**, **Y** vagy **Z** betűt, hogy egy tengelyre korlátozd, vagy beírhatsz számot. `G` majd `Z` majd `2` majd Enter: két egységgel feljebb.' },
        { k: 'callout', tone: 'tip', md: 'A Blender billentyűközpontú, és ez eleinte lassít, utána viszont sokkal gyorsabb lesz, mint a menüzés. Az első héten elég ez a három betű meg a Tab.' },
      ],
      quiz: [
        { k: 'single', q: 'Mivel váltasz objektum és szerkesztő mód közt?', opts: ['Szóköz', 'Tab', 'Enter'], answer: 1, why: 'A Tab a módváltó. Ugyanaz a billentyű más dolgot csinál a két módban, ezért mindig tudd, melyikben vagy.' },
        { k: 'single', q: 'Mit csinál a `G` billentyű?', opts: ['Forgat', 'Mozgat', 'Méretez'], answer: 1, why: 'A G a „grab" rövidítése: megfogja és mozgatja a kijelölést. A forgatás R, a méretezés S.' },
        { k: 'single', q: 'Mit jelent a `G` után nyomott `Z`?', opts: ['Visszavonás', 'A mozgatást a Z tengelyre korlátozza', 'Nagyítás'], answer: 1, why: 'A tengelybetű leszűkíti a műveletet egy irányra. Így tudsz pontosan függőlegesen mozgatni.' },
        { k: 'single', q: 'Mire való az Outliner?', opts: ['A renderelésre', 'A jelenetben lévő objektumok listájára', 'Az anyagok szerkesztésére'], answer: 1, why: 'Az Outliner a jelenet tartalomjegyzéke. Ha egy objektumot nem találsz a nézetben, itt biztosan megvan.' },
      ],
      note: {
        summary: ['A Blender felülete: 3D nézet, Outliner, Properties, Timeline, fejléc.', 'A Blender módokban működik; a Tab vált objektum és szerkesztő mód közt.', 'Ugyanaz a billentyű mást csinál a két módban — mindig tudd, melyikben vagy.', 'G mozgat, R forgat, S méretez.', 'A művelet után nyomott X/Y/Z tengelyre korlátoz, és szám is beírható.'],
        terms: [{ term: 'objektum mód', def: 'Mód, amiben egész tárgyakat mozgatsz, forgatsz, méretezel.' }, { term: 'szerkesztő mód', def: 'Mód, amiben a tárgy pontjait, éleit és lapjait szerkeszted.' }, { term: 'Outliner', def: 'A jelenet összes objektumát felsoroló panel.' }],
      },
    },
    {
      day: 2,
      title: 'Navigáció a térben',
      minutes: 18,
      lesson: [
        { k: 'text', md: 'Mielőtt bármit megmodelleznél, körbe kell tudnod nézni. A Blenderben ez az egér középső gombján múlik.' },
        { k: 'text', md: '- **Középső gomb húzás** — forgatás a nézet középpontja körül\n- **Shift + középső gomb** — oldalazás (pan)\n- **Görgő** — közelítés és távolítás\n- **Numpad .** — ráközelít a kijelölt objektumra\n- **Numpad 1 / 3 / 7** — elölnézet / oldalnézet / felülnézet\n- **Numpad 5** — váltás perspektivikus és ortografikus közt' },
        { k: 'callout', tone: 'key', md: 'Az **ortografikus** nézetben nincs perspektíva: a párhuzamos élek párhuzamosak maradnak. Modellezéskor szinte mindig ebben dolgozz, mert csak így tudsz pontosan igazítani. A perspektivikus a végső képhez kell.' },
        { k: 'text', md: 'Ez ugyanaz a három alapnézet, amit a CAD trek első napján láttál: elöl-, oldal- és felülnézet. A Blender és a CAD program térbeli gondolkodása azonos, csak a cél más: a CAD gyártani akar, a Blender képet csinálni.' },
        { k: 'callout', tone: 'tip', md: 'Ha nincs numpad billentyűzeted, a Beállításokban kapcsold be az „Emulate Numpad" opciót — ekkor a felső számsor veszi át a szerepét.' },
      ],
      quiz: [
        { k: 'single', q: 'Mivel forgatod a nézetet?', opts: ['Bal gomb húzás', 'Középső gomb húzás', 'Jobb gomb húzás'], answer: 1, why: 'A középső egérgomb (a görgő lenyomva) forgatja a nézetet. Shifttel együtt oldalaz.' },
        { k: 'single', q: 'Mi a különbség az ortografikus és a perspektivikus nézet közt?', opts: ['Az ortografikusban nincs perspektíva, a párhuzamos élek párhuzamosak maradnak', 'Az ortografikus színes', 'Semmi'], answer: 0, why: 'A perspektívában a távoli dolgok kisebbek, és az élek összetartanak. Modellezéskor ez megtéveszt, ezért dolgozunk ortografikusan.' },
        { k: 'single', q: 'Mit csinál a Numpad 1?', opts: ['Felülnézet', 'Elölnézet', 'Renderel'], answer: 1, why: 'Numpad 1 elölnézet, 3 oldalnézet, 7 felülnézet. Ugyanaz a három alapnézet, mint a CAD-ben.' },
        { k: 'single', q: 'Mit tegyél, ha nincs numpad a billentyűzeteden?', opts: ['Nem lehet használni a Blendert', 'Kapcsold be az Emulate Numpad opciót a beállításokban', 'Vegyél új gépet'], answer: 1, why: 'Az Emulate Numpad a felső számsort teszi numpaddá. Laptopon ez az első dolog, amit be kell kapcsolni.' },
      ],
      note: {
        summary: ['Középső gomb forgat, Shift + középső oldalaz, görgő közelít.', 'Numpad 1/3/7: elöl-, oldal- és felülnézet; Numpad 5 vált perspektíva és ortografikus közt.', 'Modellezéskor ortografikus nézetben dolgozz: a perspektíva megtéveszt igazításnál.', 'Numpad . ráközelít a kijelölt objektumra.', 'Numpad nélküli gépen kapcsold be az Emulate Numpad opciót.'],
        terms: [{ term: 'ortografikus nézet', def: 'Perspektíva nélküli vetítés, amiben a párhuzamos élek párhuzamosak maradnak.' }, { term: 'pan', def: 'A nézet oldalazása forgatás nélkül.' }, { term: 'Emulate Numpad', def: 'Beállítás, ami a felső számsort numpadként használja.' }],
      },
    },
    {
      day: 3,
      title: 'Objektumok mozgatása',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'Objektum módban egész tárgyakkal dolgozol. Három művelet, és mindháromnak van egy pontos és egy gyors használata.' },
        { k: 'text', md: '**Gyors:** `G` és húzod az egérrel.\n**Pontos:** `G`, majd `Z`, majd `2`, majd Enter — pontosan két egységgel feljebb.\n\nUgyanez `R`-rel (fok) és `S`-sel (szorzó). `S` majd `0.5` felezi a méretet.' },
        { k: 'callout', tone: 'warn', md: 'Minden objektumnak van **origója** — az a kis narancssárga pont. A forgatás és a méretezés **mindig** e körül történik. Ha egy tárgy furcsán ugrik forgatáskor, az origója nincs ott, ahol gondolod. Javítás: Object → Set Origin → Origin to Geometry.' },
        { k: 'text', md: 'A **transzformációk** külön élnek az adattól. Ha egy tárgyat felméretezel 2-szeresére, a Blender nem a pontokat írja át, hanem megjegyzi: „ez a tárgy kétszeres léptékű". Ez később gondot okoz — módosítóknál, fizikánál, exportnál.' },
        { k: 'callout', tone: 'key', md: 'Ezért van a **Ctrl + A → Apply → All Transforms**. Ez belesüti a méretet és a forgatást az adatba, és a lépték visszaáll 1-re. Mielőtt bármit exportálnál vagy fizikát adnál rá, alkalmazd a transzformációkat.' },
      ],
      quiz: [
        { k: 'single', q: 'Mi körül forog egy objektum?', opts: ['A világ középpontja körül', 'A saját origója körül', 'A kamera körül'], answer: 1, why: 'A narancssárga origópont a forgatás és a méretezés középpontja. Rossz helyen lévő origó a furcsa ugrálás leggyakoribb oka.' },
        { k: 'single', q: 'Mit csinál a `S` majd `0.5` majd Enter?', opts: ['Megduplázza a méretet', 'Felezi a méretet', 'Elforgatja 0,5 fokkal'], answer: 1, why: 'Az S utáni szám szorzó. A 0,5 fele akkorára méretez, a 2 kétszeresére.' },
        { k: 'single', q: 'Miért kell alkalmazni a transzformációkat?', opts: ['Hogy szebb legyen', 'Mert a nem alkalmazott lépték gondot okoz módosítóknál, fizikánál és exportnál', 'Nem kell'], answer: 1, why: 'A Blender külön tárolja az objektum léptékét az adattól. Sok eszköz a nyers adattal dolgozik, és ezért viselkedik váratlanul.' },
        { k: 'single', q: 'Hogyan állítod az origót a tárgy közepére?', opts: ['Object → Set Origin → Origin to Geometry', 'Ctrl + Z', 'Tab'], answer: 0, why: 'Ez a parancs odateszi az origót, ahol a geometria súlypontja van. Importált vagy sokat mozgatott tárgynál gyakran kell.' },
      ],
      note: {
        summary: ['G mozgat, R forgat, S méretez; mindegyik után szám írható pontos értékhez.', 'Az S utáni szám szorzó: 0,5 felez, 2 duplázik.', 'A forgatás és a méretezés mindig az objektum origója körül történik.', 'Rossz helyen lévő origó a furcsa ugrálás leggyakoribb oka.', 'A Blender a léptéket az adattól külön tárolja — ez módosítóknál és exportnál gondot okoz.', 'Ctrl + A → Apply → All Transforms belesüti a transzformációt az adatba.'],
        terms: [{ term: 'origó', def: 'Az objektum narancssárga középpontja, ami körül forog és méreteződik.' }, { term: 'transzformáció', def: 'Az objektum helye, forgatása és léptéke, az adattól külön tárolva.' }, { term: 'Apply Transform', def: 'A transzformáció belesütése az adatba, a lépték visszaállításával.' }],
      },
    },
    ...blenderHuB,
    ...blenderHuC,
    ...blenderHuD,
  ],
};
