import type { Day } from '../../types';

/** BLENDER trek, 18–24. nap. */
export const blenderHuD: Day[] = [
  {
    day: 18,
    title: 'HDRI és környezeti fény',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **HDRI** egy gömbpanoráma kép, ami **nagy dinamikatartományt** tárol: a nap több ezerszer fényesebb benne, mint az árnyék. Ez teszi lehetővé, hogy valódi fényforrásként működjön.' },
      { k: 'callout', tone: 'key', md: 'Egy közönséges JPEG 0 és 255 közti értékeket tárol. Egy HDRI lebegőpontos, és a nap akár 50 000-es értéket is felvehet. Ezért tud egyetlen kép élethű világítást adni — a kontrasztarány benne van.' },
      { k: 'text', md: 'Beállítás: **World Properties → Color → Environment Texture**, és betöltöd a `.hdr` vagy `.exr` fájlt. Innentől a jelenetet minden irányból megvilágítja, és a tükröződő felületeken meg is jelenik.' },
      { k: 'text', md: 'A három csúszka, amit állítani szoktál:\n\n- **Strength** — a fényerő. 1,0 az alap; termékrenderhez gyakran 0,5–2 közt.\n- **Rotation** (Mapping csomóponttal) — elforgatja a környezetet. Ettől változik, honnan jön a fő fény.\n- **Transparent film** (Render Properties → Film) — a HDRI világít, de nem látszik a háttérben.' },
      { k: 'callout', tone: 'tip', md: 'A legtöbb termékrender receptje: **HDRI alapnak** + **egy area lámpa keynek**. A HDRI adja a hihető környezeti tükröződést, az area lámpa pedig a formát rajzoló irányított fényt. Ketten együtt jobbak, mint bármelyik önmagában.' },
      { k: 'callout', tone: 'warn', md: 'A HDRI **felbontása** számít a tükröződéseknél. Egy 1K-s panoráma elég a megvilágításhoz, de ha a képen látszik a háttér vagy egy krómfelület tükrözi, legalább 4K kell, különben elmosódott lesz.' },
    ],
    quiz: [
      { k: 'single', q: 'Mitől különleges egy HDRI?', opts: ['Nagyobb felbontású', 'Nagy dinamikatartományt tárol: a nap több ezerszer fényesebb benne, mint az árnyék', 'Színesebb'], answer: 1, why: 'A lebegőpontos tárolás miatt valódi fényforrásként viselkedik, nem csak háttérképként.' },
      { k: 'single', q: 'Hol állítod be a HDRI-t?', opts: ['Render Properties', 'World Properties → Color → Environment Texture', 'Object Properties'], answer: 1, why: 'A világ (World) adja a környezeti megvilágítást minden irányból.' },
      { k: 'single', q: 'Mit csinál a Transparent film beállítás?', opts: ['Átlátszóvá teszi a tárgyat', 'A HDRI világít, de nem látszik a háttérben', 'Kikapcsolja a HDRI-t'], answer: 1, why: 'Így alfa csatornás képet kapsz, amit utólag bármilyen háttérre tehetsz.' },
      { k: 'single', q: 'Mi a legtöbb termékrender receptje?', opts: ['Csak HDRI', 'HDRI alapnak plusz egy area lámpa keynek', 'Csak három lámpa'], answer: 1, why: 'A HDRI adja a környezeti tükröződést, az area lámpa az irányított, formát rajzoló fényt.' },
      { k: 'single', q: 'Mikor kell nagy felbontású HDRI?', opts: ['Mindig', 'Ha a háttér látszik, vagy krómfelület tükrözi', 'Soha'], answer: 1, why: 'Megvilágításhoz 1K is elég. Látható háttérhez vagy éles tükröződéshez legalább 4K.' },
    ],
    note: {
      summary: ['A HDRI gömbpanoráma nagy dinamikatartománnyal.', 'A lebegőpontos tárolás teszi valódi fényforrássá.', 'Beállítás: World Properties → Color → Environment Texture.', 'Strength a fényerő, Rotation forgatja, Transparent film elrejti a háttérben.', 'Termékrender recept: HDRI + egy area lámpa.', 'Látható háttérhez vagy éles tükröződéshez legalább 4K kell.'],
      terms: [{ term: 'HDRI', def: 'Nagy dinamikatartományú gömbpanoráma megvilágításhoz.' }, { term: 'Environment Texture', def: 'A világot megvilágító képcsomópont.' }, { term: 'transparent film', def: 'Beállítás, amivel a háttér átlátszó marad a renderen.' }],
    },
  },
  {
    day: 19,
    title: 'Kamera és képkivágás',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A kamera beállítása ugyanúgy fotózás, mint a valóságban. Ugyanazok a döntések: hova állsz, milyen objektívet használsz, mit teszel a képbe és mit hagysz ki.' },
      { k: 'callout', tone: 'key', md: 'A **gyújtótávolság** nem a nagyítást állítja, hanem a **perspektívát**:\n\n- **20–35 mm** — széles, erős torzítás. A közeli rész nagynak látszik. Belső terekhez.\n- **50 mm** — semleges, emberi látáshoz közeli.\n- **85–135 mm** — összenyomja a teret, hízelgő arányok. Termékfotóhoz ez a jó.' },
      { k: 'text', md: 'Termékrenderhez tehát **ne** menj közel széles objektívvel: a tárgy eleje felnagyul, a hátulja összezsugorodik, és a kép olcsónak néz ki. Állj távolabb 85 mm-rel — ugyanakkorának látszik a tárgy, de az arányai helyesek lesznek.' },
      { k: 'text', md: 'Képkivágás, három bevált szabály:\n\n- **Harmadolás** — a fontos elemek a harmadoló vonalakra vagy metszéspontjaikra. Overlays → Composition Guides mutatja.\n- **Levegő** — ne érjen a tárgy a kép széléhez. A szűk kivágás nyomasztó.\n- **Enyhén felülről vagy alulról** — a pontosan szemmagasságú kép a legunalmasabb.' },
      { k: 'callout', tone: 'tip', md: 'A **mélységélesség** (Camera Data → Depth of Field) azonnal fotószerűvé tesz. Állítsd a fókuszt a tárgyra, és az `F-Stop`-ot 2,8 és 5,6 közé. Vigyázz: túl kis F-Stop mellett a tárgynak már csak egy vékony szelete lesz éles.' },
      { k: 'callout', tone: 'warn', md: 'A **felbontás és a képarány** a Render Properties-ben van, nem a kameránál. Állítsd be a végleges méretet, **mielőtt** komponálsz — különben a kivágás más lesz, mint amit a nézőben láttál.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit állít a gyújtótávolság?', opts: ['Csak a nagyítást', 'A perspektívát: mennyire torzulnak az arányok', 'A fényerőt'], answer: 1, why: 'Széles objektívvel a közeli rész felnagyul. Hosszabbal a tér összenyomódik.' },
      { k: 'single', q: 'Milyen gyújtótávolság jó termékrenderhez?', opts: ['20 mm', '85-135 mm', 'Mindegy'], answer: 1, why: 'Összenyomja a teret és hízelgő arányokat ad. A széles objektív közelről olcsó hatású.' },
      { k: 'single', q: 'Mi a harmadolás szabálya?', opts: ['A tárgy a kép közepén', 'A fontos elemek a harmadoló vonalakra vagy metszéspontjaikra', 'Három tárgy legyen a képen'], answer: 1, why: 'Az Overlays → Composition Guides bekapcsolja a segédvonalakat.' },
      { k: 'single', q: 'Mit ad a mélységélesség?', opts: ['Nagyobb felbontást', 'Fotószerű hatást: a háttér elmosódik', 'Gyorsabb rendert'], answer: 1, why: 'F-Stop 2,8–5,6 közt jó kiindulás. Túl kicsi értéknél csak egy vékony szelet lesz éles.' },
      { k: 'single', q: 'Mikor állítsd be a felbontást és a képarányt?', opts: ['A komponálás után', 'A komponálás előtt', 'Mindegy'], answer: 1, why: 'A képarány megváltoztatja a kivágást. Utólag állítva más lesz, mint amit láttál.' },
    ],
    note: {
      summary: ['A gyújtótávolság a perspektívát állítja, nem a nagyítást.', '20-35 mm széles és torzít; 50 mm semleges; 85-135 mm termékfotóhoz.', 'Komponálás: harmadolás, levegő a szélek felé, enyhén felül- vagy alulnézet.', 'Mélységélesség: F-Stop 2,8–5,6 fotószerű hatáshoz.', 'A felbontást és képarányt a komponálás előtt állítsd be.'],
      terms: [{ term: 'gyújtótávolság', def: 'A kamera látószögét és a perspektíva torzítását meghatározó érték.' }, { term: 'harmadolás', def: 'Kompozíciós szabály a fontos elemek elhelyezésére.' }, { term: 'mélységélesség', def: 'Az élesen leképezett tartomány mélysége.' }],
    },
  },
  {
    day: 20,
    title: 'Renderelés: EEVEE és Cycles',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A Blendernek két fő render motorja van, és teljesen másképp működnek. Nem az a kérdés, melyik jobb, hanem hogy **mire használod**.' },
      { k: 'text', md: '**EEVEE** — raszterizáló motor, mint a játékoké. Közelítéseket használ, és másodpercek alatt renderel. A nézetben is valós időben mutatja az eredményt.\n\n**Cycles** — sugárkövető. Minden fénysugár útját követi, ezért fizikailag pontos. Percekig vagy órákig tart egy kép.' },
      { k: 'callout', tone: 'key', md: 'Amit **csak a Cycles tud jól**: valódi fénytörés üvegben, kausztika, pontos indirekt fény (színátvitel a falakról), igazi szubfelületi szórás. Ha ezek számítanak, nincs választás.' },
      { k: 'text', md: 'Amit az EEVEE jól csinál: lapos, nem tükröződő felületek, stilizált megjelenítés, animáció előnézete, és minden, ahol a sebesség fontosabb a tökéletes fizikánál. Egy 250 képkockás animáció Cycles-ben egy éjszaka, EEVEE-ben öt perc.' },
      { k: 'callout', tone: 'warn', md: 'Az EEVEE-ben külön be kell kapcsolni, amit a Cycles alapból tud: **Screen Space Reflections**, **Ambient Occlusion**, **Soft Shadows**, és az átlátszó anyagoknál a **Blend Mode** és a **Refraction**. Enélkül az EEVEE kép laposnak tűnik.' },
      { k: 'text', md: 'A gyakorlati munkamenet: **modellezz és világíts EEVEE-ben**, mert azonnal látod az eredményt. A végső képet pedig **Cycles-ben** renderelj. Az anyagok nagy része mindkettőben ugyanúgy néz ki, mert a Principled BSDF közös.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a fő különbség EEVEE és Cycles közt?', opts: ['Az EEVEE raszterizál és közelít, a Cycles sugarat követ és pontos', 'Az EEVEE régebbi', 'Nincs különbség'], answer: 0, why: 'Az EEVEE másodpercek alatt közelít, a Cycles percekig számol fizikailag pontos képet.' },
      { k: 'single', q: 'Mit tud jól csak a Cycles?', opts: ['Gyors előnézetet', 'Valódi fénytörést, kausztikát, pontos indirekt fényt', 'Stilizált megjelenítést'], answer: 1, why: 'Ezek mind a fénysugarak valódi követését igénylik, amit az EEVEE csak közelít.' },
      { k: 'single', q: 'Mikor éri meg EEVEE-t használni?', opts: ['Üveges termékrenderhez', 'Animációhoz és minden esetben, ahol a sebesség fontosabb', 'Soha'], answer: 1, why: 'Egy 250 képkockás animáció Cycles-ben egy éjszaka, EEVEE-ben öt perc.' },
      { k: 'single', q: 'Mit kell külön bekapcsolni EEVEE-ben?', opts: ['Semmit', 'Screen Space Reflections, Ambient Occlusion, Soft Shadows', 'Csak a felbontást'], answer: 1, why: 'Ezek nélkül az EEVEE kép laposnak tűnik. A Cycles alapból tudja mindet.' },
      { k: 'single', q: 'Mi a javasolt munkamenet?', opts: ['Mindent Cycles-ben', 'Modellezés és világítás EEVEE-ben, végső render Cycles-ben', 'Mindent EEVEE-ben'], answer: 1, why: 'A Principled BSDF közös, ezért az anyagok nagy része mindkettőben ugyanúgy néz ki.' },
    ],
    note: {
      summary: ['EEVEE raszterizál és közelít; Cycles sugarat követ és pontos.', 'Csak Cycles: valódi fénytörés, kausztika, pontos indirekt fény.', 'EEVEE jó animációhoz és gyors előnézethez.', 'EEVEE-ben külön kell bekapcsolni a tükröződést és a lágy árnyékot.', 'Munkamenet: modellezés EEVEE-ben, végső render Cycles-ben.'],
      terms: [{ term: 'EEVEE', def: 'Valós idejű raszterizáló render motor.' }, { term: 'Cycles', def: 'Fizikailag pontos sugárkövető render motor.' }, { term: 'kausztika', def: 'Átlátszó tárgy által fókuszált fény mintázata.' }],
    },
  },
  {
    day: 21,
    title: 'Rendersebesség és zaj',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A Cycles képe **zajos**, mert véletlenszerűen mintavételez. Minden további minta csökkenti a zajt — de a javulás egyre lassabb.' },
      { k: 'callout', tone: 'key', md: 'A zaj a minták **négyzetgyökével** csökken. Feleakkora zajhoz **négyszer** annyi minta kell. Ezért nem érdemes 4096 mintáig menni: a 256-ról 1024-re lépés négyszeres időbe kerül, és alig látszik.' },
      { k: 'text', md: 'A legfontosabb beállítás a **Denoise** (Render Properties → Sampling → Denoise). A modern zajszűrő gépi tanulással dolgozik, és egy 128 mintás képet olyanná tesz, mint egy 2000 mintás. Ez a legnagyobb ingyen nyereség a renderelésben.' },
      { k: 'text', md: 'Sebességnövelő beállítások:\n\n- **Noise Threshold** — adaptív mintavétel: ahol már sima a kép, abbahagyja\n- **Max Bounces** csökkentése — 12 helyett 4 elég a legtöbb jelenethez\n- **GPU render** — jellemzően 5–20-szor gyorsabb a processzornál\n- **Persistent Data** — animációnál nem építi újra a jelenetet minden képkockán' },
      { k: 'callout', tone: 'warn', md: 'A **tűzijáték-zaj** (fireflies) külön probléma: egy-egy villogóan fehér pixel. Erős fényforrás és kis fényes felület okozza. Megoldás: a **Clamp Indirect** értékét állítsd 10 köré, vagy növeld a fényforrás méretét.' },
      { k: 'callout', tone: 'tip', md: 'Mielőtt órákat várnál egy renderre, próbáld ki **10 százalékos felbontáson**. A kompozíció, a világítás és a zaj mértéke kis képen is látszik, és három másodperc alatt kész.' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan csökken a zaj a mintaszámmal?', opts: ['Egyenesen arányosan', 'A négyzetgyökével: feleakkora zajhoz négyszer annyi minta kell', 'Exponenciálisan'], answer: 1, why: 'Ezért éri el a magas mintaszám a csökkenő hozadék határát.' },
      { k: 'single', q: 'Mi a legnagyobb ingyen sebességnyereség?', opts: ['Kisebb felbontás', 'A Denoise bekapcsolása', 'Kevesebb tárgy'], answer: 1, why: 'A gépi tanulású zajszűrő 128 mintából 2000 mintás minőséget hoz ki.' },
      { k: 'single', q: 'Mi a tűzijáték-zaj (fireflies)?', opts: ['Egyenletes szemcse', 'Egy-egy villogóan fehér pixel, erős fény és kis fényes felület miatt', 'Színhiba'], answer: 1, why: 'Megoldás a Clamp Indirect 10 körüli értéke, vagy nagyobb fényforrás.' },
      { k: 'single', q: 'Mit csinál a Noise Threshold?', opts: ['Növeli a zajt', 'Adaptív mintavétel: ahol már sima a kép, abbahagyja a mintavételt', 'Elmossa a képet'], answer: 1, why: 'A számítási időt oda teszi, ahol tényleg kell: a zajos részekre.' },
      { k: 'single', q: 'Hogyan ellenőrizd a rendert óra helyett három másodperc alatt?', opts: ['Kevesebb mintával', '10 százalékos felbontáson', 'EEVEE-vel'], answer: 1, why: 'A kompozíció, a világítás és a zaj mértéke kis képen is látszik.' },
    ],
    note: {
      summary: ['A Cycles zaja a minták négyzetgyökével csökken.', 'Feleakkora zajhoz négyszer annyi minta kell.', 'A Denoise a legnagyobb ingyen nyereség: 128 mintából 2000 mintás minőség.', 'Gyorsítás: Noise Threshold, kevesebb Max Bounces, GPU, Persistent Data.', 'Fireflies ellen: Clamp Indirect 10 körül, vagy nagyobb fényforrás.', 'Teszteléshez renderelj 10 százalékos felbontáson.'],
      terms: [{ term: 'minta (sample)', def: 'Egy véletlen fénysugárút, amiből a kép épül.' }, { term: 'denoise', def: 'Gépi tanulású zajszűrés a renderelt képen.' }, { term: 'firefly', def: 'Egyedi, villogóan fényes pixel a renderen.' }],
    },
  },
  {
    day: 22,
    title: 'Kompozitálás alapok',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **kompozitálás** a render utómunkája, csomópontokkal. Nem kell újrarenderelni ahhoz, hogy a kép fényesebb, kontrasztosabb vagy melegebb legyen.' },
      { k: 'text', md: 'A **Compositing** munkaterületen kapcsold be a **Use Nodes** jelölőt. Két csomópont van ott: a `Render Layers` (a nyers kép) és a `Composite` (a kimenet). Közéjük fűzöd a műveleteket.' },
      { k: 'callout', tone: 'key', md: 'A három csomópont, amivel a legtöbbet nyersz:\n\n- **Glare** (Fog Glow vagy Streaks) — fényes részek körüli fényudvar. Ez teszi „fotóssá" a képet.\n- **Color Balance** vagy **RGB Curves** — a színhangulat állítása.\n- **Lens Distortion** (kis Dispersion értékkel) — enyhe színhiba a széleken, mint egy valódi objektívnél.' },
      { k: 'text', md: 'Az **AOV**-k, vagyis render rétegek külön csatornákként adják vissza a kép alkotóelemeit: `Diffuse`, `Glossy`, `Emission`, `Mist`, `Z` (mélység). A View Layer Properties → Passes alatt kapcsolhatók be.\n\nA `Mist` rétegből például köd vagy távolságfüggő elhalványulás készíthető — újrarenderelés nélkül.' },
      { k: 'callout', tone: 'warn', md: 'A **színkezelés** (Render Properties → Color Management) nem kompozitálás, de ugyanúgy a végeredményt szabja. Az alapértelmezett **Filmic** vagy **AgX** nézet összenyomja a nagy fényerőket, és ettől lesz fotószerű a kép. A `Standard` beállítás kiégett, kemény képet ad.' },
      { k: 'callout', tone: 'tip', md: 'Ments **OpenEXR** formátumban, ha utómunkát tervezel. A PNG 8 bites, és a kiégett fényeket már nem lehet visszahozni belőle. Az EXR megtartja a teljes dinamikatartományt.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a kompozitálás?', opts: ['Újrarenderelés', 'A render utómunkája csomópontokkal', 'Modellezés'], answer: 1, why: 'A kép fényereje, kontrasztja és színhangulata újrarenderelés nélkül állítható.' },
      { k: 'single', q: 'Mit csinál a Glare csomópont?', opts: ['Élesít', 'Fényudvart ad a fényes részek köré', 'Zajt szűr'], answer: 1, why: 'Ez az egyik leggyorsabb módja annak, hogy a render fotószerűvé váljon.' },
      { k: 'single', q: 'Mire jó a Mist render réteg?', opts: ['Színkorrekcióra', 'Köd vagy távolságfüggő elhalványulás készítésére utólag', 'Zajszűrésre'], answer: 1, why: 'A rétegek külön csatornaként adják vissza a kép alkotóelemeit, újrarenderelés nélkül szerkeszthetően.' },
      { k: 'single', q: 'Mit csinál a Filmic vagy AgX nézet?', opts: ['Élesít', 'Összenyomja a nagy fényerőket, ettől lesz fotószerű a kép', 'Zajt ad hozzá'], answer: 1, why: 'A `Standard` beállítás kiégett, kemény képet ad, mert nem kezeli a nagy dinamikatartományt.' },
      { k: 'single', q: 'Milyen formátumban ments, ha utómunkát tervezel?', opts: ['PNG', 'OpenEXR', 'JPEG'], answer: 1, why: 'A PNG 8 bites: a kiégett fényeket már nem lehet visszahozni. Az EXR megtartja a dinamikatartományt.' },
    ],
    note: {
      summary: ['A kompozitálás a render utómunkája csomópontokkal.', 'Compositing munkaterület → Use Nodes.', 'Glare fényudvart ad; Color Balance a hangulatot; Lens Distortion objektívhatást.', 'Render rétegek (AOV): Diffuse, Glossy, Mist, Z — külön szerkeszthetők.', 'A Filmic vagy AgX nézet teszi fotószerűvé a képet.', 'Utómunkához OpenEXR formátumban ments.'],
      terms: [{ term: 'kompozitálás', def: 'A renderelt kép csomópont-alapú utómunkája.' }, { term: 'render réteg (AOV)', def: 'A kép egy alkotóeleme külön csatornaként.' }, { term: 'színkezelés', def: 'A dinamikatartomány képernyőre leképezésének módja.' }],
    },
  },
  {
    day: 23,
    title: 'Armature és csontváz',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az **armature** a modell belső csontváza. A csontok mozgatják a hálót, és ettől lesz egy merev modellből animálható szerkezet.' },
      { k: 'text', md: 'Add → **Armature**. Szerkesztő módban a csont két vége a **fej** (head) és a **farok** (tail). A csontok **szülő-gyerek** láncot alkotnak: ha a felkart forgatod, az alkar és a kéz követi.' },
      { k: 'callout', tone: 'key', md: 'A csontok helye a **forgástengelyeket** jelöli ki. Egy robotkarnál ez pontosan a valódi csuklók helye legyen — ha mellé teszed, a modell a mozgás során el fog csúszni önmagától.' },
      { k: 'text', md: 'Kétféle animálási mód:\n\n- **FK (előre kinematika)** — minden csontot külön forgatsz. Pontos vezérlés, de a végpont helyét nehéz eltalálni.\n- **IK (inverz kinematika)** — a végpontot húzod, és a köztes csontok maguktól beállnak. Ez kell, ha a kéznek egy adott ponton kell lennie.' },
      { k: 'callout', tone: 'warn', md: 'Az IK-lánc kétértelmű lehet: ugyanazt a végpontot több könyökállás is adja. Ezért kell a **pole target** — egy segédobjektum, ami megmondja, merre nézzen a könyök. Enélkül az animáció közben hirtelen átpattan.' },
      { k: 'text', md: 'A **csontkorlátok** (Bone Constraints) a valódi mozgástartományt rögzítik: `Limit Rotation` megakadályozza, hogy a csukló visszafelé hajoljon. Robotnál ez nemcsak esztétikai kérdés — a valódi szervó sem fordul 360 fokot.' },
      { k: 'callout', tone: 'tip', md: 'Nevezd el a csontokat értelmesen, és használd a `.L` / `.R` végződést: `felkar.L`, `felkar.R`. A Blender ebből felismeri a párokat, és működik a tükrözött testhelyzet beillesztése.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az armature?', opts: ['Egy anyagtípus', 'A modell belső csontváza, ami a hálót mozgatja', 'Egy módosító'], answer: 1, why: 'A csontok szülő-gyerek láncot alkotnak, és ez teszi animálhatóvá a merev modellt.' },
      { k: 'single', q: 'Hol legyen a csont egy robotkarnál?', opts: ['A szegmens közepén', 'Pontosan a valódi csukló helyén', 'A modell szélén'], answer: 1, why: 'A csontok a forgástengelyeket jelölik ki. Rossz helyen a modell elcsúszik mozgás közben.' },
      { k: 'single', q: 'Mi a különbség FK és IK között?', opts: ['Az FK-nál a csontokat forgatod, az IK-nál a végpontot húzod', 'Az IK gyorsabb', 'Nincs különbség'], answer: 0, why: 'Az IK kell, ha a kéznek egy adott ponton kell lennie; az FK pontosabb csukló-vezérlést ad.' },
      { k: 'single', q: 'Mire való a pole target?', opts: ['A csontot hosszabbítja', 'Megmondja, merre nézzen a könyök az IK-láncban', 'Színezi a csontot'], answer: 1, why: 'Enélkül az IK kétértelmű, és az animáció közben hirtelen átpattan a könyök.' },
      { k: 'single', q: 'Miért érdemes `.L` és `.R` végződést használni?', opts: ['Szebb', 'A Blender felismeri a párokat, és működik a tükrözött testhelyzet beillesztése', 'Gyorsabb'], answer: 1, why: 'Ez a szimmetrikus animáció alapfeltétele.' },
    ],
    note: {
      summary: ['Az armature a modell belső csontváza.', 'A csont két vége a fej és a farok; a csontok szülő-gyerek láncot alkotnak.', 'A csont helye a forgástengelyt jelöli ki — robotkarnál a valódi csuklónál.', 'FK: csontonkénti forgatás. IK: a végpontot húzod.', 'Az IK-hoz pole target kell, különben átpattan a könyök.', 'Csontkorlátokkal rögzítsd a valódi mozgástartományt.', 'Nevezd a csontokat `.L` / `.R` végződéssel.'],
      terms: [{ term: 'armature', def: 'A modellt mozgató csontváz.' }, { term: 'IK (inverz kinematika)', def: 'A végpont helyéből számolt csuklószögek.' }, { term: 'pole target', def: 'Segédobjektum, ami az IK-lánc hajlásirányát rögzíti.' }],
    },
  },
  {
    day: 24,
    title: 'Hitelesítés és súlyozás',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **hitelesítés** (rigging) köti össze a hálót a csontvázzal. A **súlyozás** (weight painting) mondja meg, melyik pont mennyire kövessen melyik csontot.' },
      { k: 'text', md: 'A leggyorsabb kezdés: jelöld ki a hálót, majd shift-tel az armature-t, és **Ctrl+P → With Automatic Weights**. A Blender a csontok közelsége alapján kiszámolja a kezdeti súlyokat. Ez ritkán tökéletes, de jó kiindulás.' },
      { k: 'callout', tone: 'key', md: 'Minden pont súlyai **összege 1** legyen. Ha egy pont 0,7-tel követi a felkart és 0,3-mal az alkart, akkor a kettő közt arányosan mozog. Ha az összeg nem 1, a pont elcsúszik vagy nyúlni kezd.' },
      { k: 'text', md: 'A **Weight Paint** módban a színek a súlyt mutatják: **piros = 1** (teljesen követi), **kék = 0** (egyáltalán nem). Az ecsettel festhetsz, és a `Blur` eszközzel simíthatod az átmeneteket.' },
      { k: 'callout', tone: 'warn', md: 'A **merev robotalkatrészeknél ne legyen átmenet**: minden pont tartozzon pontosan egy csonthoz, 1,0 súllyal. A lágy átmenet szerves testekhez való — egy fémlemez nem hajlik meg a csukló körül, hanem elfordul.' },
      { k: 'text', md: 'Merev alkatrészeknél egyszerűbb út: ne is súlyozz. Tedd az alkatrészt a csont **gyerekévé** (Ctrl+P → Bone). Így mereven követi, és nincs semmilyen deformáció.' },
      { k: 'callout', tone: 'tip', md: 'Ellenőrzés: Pose módban forgasd végig **minden csuklót a határhelyzetig**. A hibás súlyozás ott látszik, ahol a háló beomlik vagy kilyukad. Nyugalmi helyzetben minden rig jónak néz ki.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a súlyozás szerepe?', opts: ['Színezi a modellt', 'Megmondja, melyik pont mennyire kövessen melyik csontot', 'Méretezi a modellt'], answer: 1, why: 'Ebből derül ki, hogyan deformálódik a háló a csontok mozgására.' },
      { k: 'single', q: 'Mennyi legyen egy pont súlyainak összege?', opts: ['0', '1', 'Mindegy'], answer: 1, why: 'Ha nem 1, a pont elcsúszik vagy nyúlni kezd a mozgás során.' },
      { k: 'single', q: 'Mit jelent a piros szín Weight Paint módban?', opts: ['Hibát', 'Teljes súlyt: a pont teljesen követi a csontot', 'Nulla súlyt'], answer: 1, why: 'Piros = 1, kék = 0. A köztes színek részleges követést jelentenek.' },
      { k: 'single', q: 'Milyen legyen a súlyozás merev robotalkatrésznél?', opts: ['Lágy átmenet', 'Minden pont pontosan egy csonthoz, 1,0 súllyal', 'Vegyes'], answer: 1, why: 'A fémlemez nem hajlik meg a csukló körül, hanem elfordul. Átmenet csak szerves testeknél kell.' },
      { k: 'single', q: 'Hogyan ellenőrzöd a rigget?', opts: ['Nyugalmi helyzetben megnézed', 'Pose módban minden csuklót elforgatsz a határhelyzetig', 'Renderelsz egy képet'], answer: 1, why: 'Nyugalmi helyzetben minden rig jónak néz ki. A hibák a szélső helyzetekben derülnek ki.' },
    ],
    note: {
      summary: ['A hitelesítés köti a hálót a csontvázhoz; a súlyozás adja a mértéket.', 'Kezdés: Ctrl+P → With Automatic Weights.', 'Minden pont súlyainak összege 1 legyen.', 'Weight Paint: piros = 1, kék = 0.', 'Merev alkatrésznél nincs átmenet: egy csont, 1,0 súly.', 'Merev részt egyszerűbb a csont gyerekévé tenni (Ctrl+P → Bone).', 'Ellenőrzés: minden csuklót forgass a határhelyzetig.'],
      terms: [{ term: 'rigging', def: 'A háló és a csontváz összekötése.' }, { term: 'súlyfestés', def: 'A pontok csontkövetési arányának beállítása ecsettel.' }, { term: 'automatikus súlyozás', def: 'A Blender kezdeti súlybecslése a csontok közelsége alapján.' }],
    },
  },
];
