import type { Day } from '../../types';

/** C trek, 11–16. nap. */
export const cHuC: Day[] = [
  {
    day: 11,
    title: 'Memóriaszivárgás',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Szivárgás** akkor van, ha lefoglalt memóriára már nincs hivatkozásod, de nem is szabadítottad fel. A program futás közben egyre több memóriát eszik, és végül elfogy.' },
      { k: 'code', lang: 'c', src: '/* Szivárog: korai return a free előtt */\nint feldolgoz(const char *ut) {\n    char *puffer = malloc(1024);\n    FILE *f = fopen(ut, "r");\n    if (f == NULL) {\n        return -1;              /* a puffer itt elveszett! */\n    }\n    /* ... */\n    fclose(f);\n    free(puffer);\n    return 0;\n}', explain: 'A korai `return` a leggyakoribb szivárgásforrás C-ben: minden kilépési ágon fel kell szabadítani mindent, amit addig foglaltál.' },
      { k: 'callout', tone: 'key', md: 'A bevált minta a **„cleanup címke"**: egyetlen kilépési pont a függvény végén, és minden hibaág oda ugrik. Ez az egyik kevés eset, ahol a `goto` a tiszta megoldás C-ben.' },
      { k: 'code', lang: 'c', src: 'int feldolgoz(const char *ut) {\n    int kod = -1;\n    char *puffer = malloc(1024);\n    if (puffer == NULL) goto vege;\n\n    FILE *f = fopen(ut, "r");\n    if (f == NULL) goto takarit;\n\n    /* ... munka ... */\n    kod = 0;\n\n    fclose(f);\ntakarit:\n    free(puffer);\nvege:\n    return kod;\n}', explain: 'Minden ág ugyanazon az úton megy ki, és pontosan azt szabadítja fel, ami addig létrejött. Új erőforrás esetén egy helyen kell bővíteni.' },
      { k: 'text', md: 'Ellenőrzés eszközzel:\n\n```\nvalgrind --leak-check=full ./program\ngcc -fsanitize=address,leak -g program.c\n```\n\nA Valgrind és az AddressSanitizer megmondja, hány bájt szivárgott el, és **melyik sorban** foglaltad.' },
      { k: 'callout', tone: 'warn', md: 'A kis szivárgás is baj: egy szerverben, ami hetekig fut, a kérésenként elszivárgó 100 bájt napok alatt gigabájtokká áll össze. Nem a méret számít, hanem hogy **ismétlődik-e**.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a memóriaszivárgás?', opts: ['Ha a program túl sok memóriát használ', 'Ha lefoglalt memóriára már nincs hivatkozás, de nem is lett felszabadítva', 'Ha NULL-t dereferálsz'], answer: 1, why: 'A terület foglalva marad, de elérhetetlen. Sem a program, sem az operációs rendszer nem tudja visszavenni futás közben.' },
      { k: 'single', q: 'Mi a leggyakoribb szivárgásforrás C-ben?', opts: ['A túl nagy tömbök', 'A korai `return` a `free` előtt', 'A `printf`'], answer: 1, why: 'Hibakezelő ágon könnyű kifelejteni a felszabadítást. Ezért kell egyetlen kilépési pont.' },
      { k: 'single', q: 'Mi a „cleanup címke" minta?', opts: ['Egyetlen kilépési pont a függvény végén, ahova a hibaágak `goto`-val ugranak', 'Egy külön takarító függvény', 'Automatikus szemétgyűjtés'], answer: 0, why: 'Ez a C egyik ritka esete, ahol a `goto` a legtisztább megoldás: minden ág ugyanazt a sorrendet követi.' },
      { k: 'single', q: 'Melyik eszközzel keresel szivárgást?', opts: ['gdb', 'valgrind --leak-check=full', 'make'], answer: 1, why: 'A Valgrind megmondja a szivárgott bájtokat és a foglalás helyét. Az AddressSanitizer ugyanezt fordításba építve adja.' },
      { k: 'single', q: 'Miért baj a kérésenkénti 100 bájtos szivárgás?', opts: ['Nem baj, kicsi', 'Mert ismétlődik: hosszú futásnál gigabájtokká áll össze', 'Mert lassítja a hálózatot'], answer: 1, why: 'Az ismétlődés a lényeg, nem az egyszeri méret.' },
    ],
    note: {
      summary: ['Szivárgás: foglalt, de elérhetetlen és fel nem szabadított memória.', 'A korai `return` a leggyakoribb forrás.', 'Cleanup címke: egyetlen kilépési pont, hibaágak `goto`-val.', 'Valgrind és AddressSanitizer megmutatja a szivárgás helyét.', 'Az ismétlődő kis szivárgás is súlyos hosszú futásnál.'],
      terms: [{ term: 'szivárgás', def: 'Fel nem szabadított, elérhetetlenné vált memória.' }, { term: 'cleanup címke', def: 'Egységes kilépési pont minta `goto`-val.' }, { term: 'Valgrind', def: 'Memóriahiba-kereső eszköz.' }],
    },
  },
  {
    day: 12,
    title: 'Mutató mutatóra',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Ha egy mutató a **változó címét** tárolja, akkor a mutató mutatóra a **mutató címét** tárolja. Két oka van, hogy kell: függvényből mutatót akarsz visszaadni paraméteren át, vagy kétdimenziós, dinamikus tömböt építesz.' },
      { k: 'code', lang: 'c', src: '/* A függvény a hívó mutatóját állítja be */\nint foglal(int **ki, int n) {\n    *ki = malloc(n * sizeof **ki);\n    return (*ki != NULL) ? 0 : -1;\n}\n\nint main(void) {\n    int *adat = NULL;\n    if (foglal(&adat, 10) == 0) {\n        adat[0] = 42;\n        free(adat);\n    }\n}', explain: 'A `&adat` a mutató címe. A függvény a `*ki` dereferálással a hívó `adat` változóját írja át — enélkül csak a másolatot módosítaná.' },
      { k: 'callout', tone: 'key', md: 'Ugyanaz a szabály, mint az `int` esetén: ha a függvénynek **meg kell változtatnia** a hívó változóját, egy szinttel több mutató kell. `int` → `int *`, `int *` → `int **`.' },
      { k: 'code', lang: 'c', src: '/* Kétdimenziós, dinamikus tömb */\nint **matrix = malloc(sorok * sizeof *matrix);\nfor (int i = 0; i < sorok; i++) {\n    matrix[i] = malloc(oszlopok * sizeof **matrix);\n}\n\n/* Felszabadítás fordított sorrendben! */\nfor (int i = 0; i < sorok; i++) {\n    free(matrix[i]);\n}\nfree(matrix);', explain: 'Először a sorokat szabadítsd fel, aztán a sormutatók tömbjét. Fordítva már nem érnéd el a sorokat.' },
      { k: 'callout', tone: 'warn', md: 'A sorokra bontott mátrix **nem összefüggő** a memóriában: minden sor külön `malloc`. Nagy mátrixnál ez lassabb, mint egyetlen `n*m` méretű tömb és `matrix[i*m + j]` indexelés.' },
      { k: 'text', md: 'A klasszikus példa, amit ismerősen látsz: `int main(int argc, char **argv)`. Az `argv` mutatók tömbje, és minden mutató egy sztring első betűjére néz.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit tárol egy `int **` típusú változó?', opts: ['Két int értéket', 'Egy `int *` változó címét', 'Egy tömböt'], answer: 1, why: 'Minden csillag egy szint. Az `int **` egy olyan hely címe, ahol egy `int *` van.' },
      { k: 'single', q: 'Miért kell `int **` paraméter, ha a függvény a hívó mutatóját állítaná be?', opts: ['Így gyorsabb', 'Mert `int *` esetén csak a másolatot módosítaná', 'Mert a C megköveteli'], answer: 1, why: 'A C mindent érték szerint ad át. A hívó változójának megváltoztatásához a címe kell.' },
      { k: 'order', q: 'Milyen sorrendben szabadítasz fel egy `int **` mátrixot?', items: ['free(matrix)', 'free(matrix[i]) minden sorra'], correct: [1, 0], why: 'Előbb a sorok, aztán a sormutatók tömbje. Fordítva már nem érnéd el a sorcímeket.' },
      { k: 'single', q: 'Mi a hátránya a sorokra bontott mátrixnak?', opts: ['Nem összefüggő a memóriában, ezért lassabb', 'Nem lehet indexelni', 'Kevesebb elemet bír'], answer: 0, why: 'A gyorsítótár az összefüggő memóriát szereti. Nagy mátrixhoz egyetlen tömb és `i*m + j` indexelés gyorsabb.' },
      { k: 'single', q: 'Mi az `argv` típusa a `main` függvényben?', opts: ['`char *`', '`char **`', '`int *`'], answer: 1, why: 'Mutatók tömbje: minden elem egy parancssori argumentum sztringjének első betűjére mutat.' },
    ],
    note: {
      summary: ['A mutató mutatóra egy mutató címét tárolja.', 'Ha a függvénynek a hívó mutatóját kell beállítania, `int **` paraméter kell.', 'Dinamikus mátrix: sormutatók tömbje, soronként külön foglalás.', 'Felszabadítás fordított sorrendben: előbb a sorok, aztán a tömb.', 'A sorokra bontott mátrix nem összefüggő, ezért nagy méretnél lassabb.', '`char **argv` a klasszikus példa.'],
      terms: [{ term: 'kettős indirekció', def: 'Mutató, ami egy másik mutatóra mutat.' }, { term: 'kimenő paraméter', def: 'Paraméter, amin keresztül a függvény eredményt ad vissza.' }, { term: 'összefüggő memória', def: 'Egyetlen folytonos területen tárolt adat.' }],
    },
  },
  {
    day: 13,
    title: 'Függvénymutatók',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A függvénynek is van címe a memóriában, tehát mutatóba tehető. Ez adja a C-ben a visszahívást (callback), a rendezési szabály átadását és a parancstáblákat.' },
      { k: 'code', lang: 'c', src: '/* Deklaráció: visszatérési típus (*nev)(paraméterek) */\nint osszead(int a, int b) { return a + b; }\nint kivon(int a, int b)   { return a - b; }\n\nint main(void) {\n    int (*muvelet)(int, int) = osszead;\n    printf("%d\\n", muvelet(3, 4));    /* 7 */\n\n    muvelet = kivon;\n    printf("%d\\n", muvelet(3, 4));    /* -1 */\n}', explain: 'A zárójel a `*muvelet` körül kötelező. Nélküle `int *muvelet(int,int)` lenne, ami egy `int *`-ot visszaadó függvény deklarációja — teljesen más.' },
      { k: 'text', md: 'A leggyakoribb felhasználás a szabványos `qsort`:\n\n```c\nint osszehasonlit(const void *a, const void *b) {\n    int x = *(const int *)a, y = *(const int *)b;\n    return (x > y) - (x < y);\n}\nqsort(tomb, n, sizeof *tomb, osszehasonlit);\n```\n\nA `qsort` nem tudja, mit rendez — te adod meg neki a szabályt egy függvénymutatóval.' },
      { k: 'callout', tone: 'key', md: 'A `(x > y) - (x < y)` kifejezés a biztonságos összehasonlítás: -1, 0 vagy 1. A naiv `return x - y;` **túlcsordulhat** nagy számoknál, és akkor hibás a rendezés.' },
      { k: 'callout', tone: 'tip', md: 'Hosszú függvénymutató-típusokat írj `typedef`-fel:\n\n`typedef int (*Muvelet)(int, int);`\n\nEzután a `Muvelet m = osszead;` sor olvasható. Enélkül a táblázatok deklarációja áttekinthetetlen.' },
      { k: 'text', md: 'Függvénymutatók tömbjével készül a **parancstábla**: egy `struct { const char *nev; void (*fn)(void); }` sorozat, amin végigkeresel. Ez váltja ki a hosszú `if`-láncot a parancsértelmezőkben.' },
    ],
    quiz: [
      { k: 'single', q: 'Miért kell zárójel a `*muvelet` köré?', opts: ['Olvashatóbb', 'Nélküle egy `int *`-ot visszaadó függvény deklarációja lenne', 'Nem kötelező'], answer: 1, why: 'Az operátor-elsőbbség miatt. A zárójel köti a csillagot a névhez, nem a visszatérési típushoz.' },
      { k: 'single', q: 'Mire való a `qsort` negyedik paramétere?', opts: ['A tömb mérete', 'Az összehasonlító függvény mutatója', 'A rendezés iránya'], answer: 1, why: 'A `qsort` általános: nem ismeri az elemek típusát, ezért a hasonlítás szabályát te adod át.' },
      { k: 'single', q: 'Miért rossz az `return x - y;` összehasonlításnál?', opts: ['Lassú', 'Nagy számoknál túlcsordulhat, és hibás rendezést ad', 'Nem fordul le'], answer: 1, why: 'A `(x > y) - (x < y)` alak sosem csordul túl, és ugyanazt a három értéket adja.' },
      { k: 'single', q: 'Mire jó a `typedef int (*Muvelet)(int, int);`?', opts: ['Gyorsabb hívás', 'Olvasható nevet ad a függvénymutató-típusnak', 'Új függvényt hoz létre'], answer: 1, why: 'A függvénymutató szintaxisa nehezen olvasható. A typedef különösen táblázatoknál segít.' },
      { k: 'single', q: 'Mi a parancstábla?', opts: ['Függvénymutatók és nevek tömbje a hosszú `if`-lánc helyett', 'Egy adatbázis', 'A fordító része'], answer: 0, why: 'Név szerint keresel benne, és meghívod a hozzá tartozó függvényt. Új parancs = új sor a táblában.' },
    ],
    note: {
      summary: ['A függvénynek is van címe, tehát mutatóba tehető.', 'Deklaráció: `int (*nev)(int, int)` — a zárójel kötelező.', 'A `qsort` függvénymutatóval kapja meg a rendezési szabályt.', 'Összehasonlításhoz `(x > y) - (x < y)`, mert nem csordul túl.', '`typedef` teszi olvashatóvá a függvénymutató-típust.', 'Parancstábla váltja ki a hosszú `if`-láncot.'],
      terms: [{ term: 'függvénymutató', def: 'Egy függvény címét tároló mutató.' }, { term: 'visszahívás (callback)', def: 'Átadott függvény, amit a hívott kód hív meg.' }, { term: 'parancstábla', def: 'Név–függvénymutató párok tömbje.' }],
    },
  },
  {
    day: 14,
    title: 'Fejlécfájlok és fordítási egységek',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Egy C program több `.c` fájlból áll, és mindegyiket **külön fordítja** a fordító. Ezeket hívjuk fordítási egységnek. Hogy tudjanak egymásról, kellenek a `.h` fejlécfájlok.' },
      { k: 'callout', tone: 'key', md: 'A szabály egy mondatban: a **`.h` fájlba a deklaráció** megy (mi létezik), a **`.c` fájlba a definíció** (mi hogyan működik). A fejlécet mindenki beolvassa, a definíció egyetlen helyen van.' },
      { k: 'code', lang: 'c', src: '/* rover.h */\n#ifndef ROVER_H\n#define ROVER_H\n\ntypedef struct {\n    int x, y;\n    int akku;\n} Rover;\n\nvoid rover_init(Rover *r);\nint  rover_lep(Rover *r, int cm);\n\n#endif /* ROVER_H */', explain: 'Az `#ifndef`/`#define`/`#endif` hármas az **include guard**: ha a fejléc kétszer kerülne be, másodszorra üresen fut le. Enélkül duplán deklarált típusokat kapnál.' },
      { k: 'code', lang: 'c', src: '/* rover.c */\n#include "rover.h"\n\nstatic int ervenyes(int cm) {   /* csak ebben a fájlban látszik */\n    return cm > 0 && cm < 100;\n}\n\nvoid rover_init(Rover *r) {\n    r->x = r->y = 0;\n    r->akku = 100;\n}', explain: 'A fájlszintű `static` függvény vagy változó **nem látszik** más fordítási egységből. Ez a C kapszulázási eszköze: ami nincs a fejlécben és `static`, az belső ügy.' },
      { k: 'callout', tone: 'warn', md: 'Globális változót **soha ne definiálj** fejlécben: minden beolvasó fájlban létrejönne egy példány, és a linkelés „multiple definition" hibával elszáll. A fejlécben `extern int szamlalo;` áll, a definíció pontosan egy `.c` fájlban.' },
      { k: 'callout', tone: 'tip', md: 'A fejléc legyen **önálló**: tartalmazza minden saját függőségét, hogy bárhonnan beolvasható legyen. Próbapróba: fordíts le egy fájlt, ami csak ezt az egy fejlécet olvassa be.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi megy a `.h` fájlba?', opts: ['A definíció', 'A deklaráció: mi létezik', 'Minden'], answer: 1, why: 'A fejléc hirdeti, mi érhető el. A megvalósítás a `.c` fájlban, egyetlen helyen van.' },
      { k: 'single', q: 'Mi az include guard szerepe?', opts: ['Gyorsítja a fordítást', 'Megakadályozza, hogy egy fejléc kétszer kerüljön be', 'Elrejti a kódot'], answer: 1, why: 'Kétszeres beolvasásnál duplán deklarált típusokat kapnál, ami fordítási hiba.' },
      { k: 'single', q: 'Mit jelent a fájlszintű `static` egy függvény előtt?', opts: ['Nem változik', 'Csak abban a fordítási egységben látszik', 'Egy példány van belőle'], answer: 1, why: 'Ez a C kapszulázása: a belső segédfüggvényt nem látja más fájl, és a neve sem ütközhet.' },
      { k: 'single', q: 'Hogyan osztasz meg egy globális változót fájlok közt?', opts: ['Definiálod a fejlécben', 'A fejlécben `extern`, a definíció pontosan egy `.c` fájlban', 'Nem lehet'], answer: 1, why: 'Fejlécbeli definíció esetén minden beolvasó fájlban keletkezne egy példány, és a linker „multiple definition" hibát ad.' },
      { k: 'single', q: 'Mit jelent, hogy egy fejléc önálló?', opts: ['Rövid', 'Tartalmazza minden saját függőségét, ezért bárhonnan beolvasható', 'Nincs benne függvény'], answer: 1, why: 'Enélkül a beolvasás sorrendje számítana, és a hibák nehezen követhetők lennének.' },
    ],
    note: {
      summary: ['A program több fordítási egységből (`.c` fájl) áll, külön fordítva.', '`.h`: deklaráció. `.c`: definíció.', 'Include guard (`#ifndef`/`#define`/`#endif`) akadályozza a kétszeres beolvasást.', 'A fájlszintű `static` elrejti a tagot más fordítási egységektől.', 'Globális változó: fejlécben `extern`, definíció egy `.c` fájlban.', 'A fejléc legyen önálló: hozza a saját függőségeit.'],
      terms: [{ term: 'fordítási egység', def: 'Egy `.c` fájl a beolvasott fejlécekkel együtt.' }, { term: 'include guard', def: 'Makróvédelem a fejléc kétszeres beolvasása ellen.' }, { term: 'extern', def: 'Deklaráció: a változó máshol van definiálva.' }],
    },
  },
  {
    day: 15,
    title: 'A preprocesszor',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A preprocesszor a fordítás **előtt** fut, és szöveget helyettesít. Nem ismeri a C nyelvtanát: csak másol, cserél és kihagy. Ebből fakad minden ereje és minden csapdája.' },
      { k: 'code', lang: 'c', src: '#define MAX_ROVER 8\n#define NEGYZET(x) ((x) * (x))\n\n/* Mi lesz ebből? */\nint a = NEGYZET(3 + 1);\n/* ((3 + 1) * (3 + 1)) = 16  -- a zárójelek miatt helyes */\n\n/* Zárójelek nélkül: #define NEGYZET(x) x * x\n   3 + 1 * 3 + 1 = 7  -- hibás! */', explain: 'A makróparaméterek köré **mindig** tegyél zárójelet, és az egész kifejezés köré is. Ez a makróhibák kilenctizedét megelőzi.' },
      { k: 'callout', tone: 'warn', md: 'A makró **többször is kiértékelheti** a paraméterét. A `NEGYZET(i++)` kétszer növeli az `i`-t — a C szabványa szerint ez meghatározatlan viselkedés. Ezért jobb a rövid `static inline` függvény, ahol lehet: típusbiztos, és egyszer értékel.' },
      { k: 'text', md: 'Feltételes fordítás:\n\n```c\n#ifdef DEBUG\n    printf("akku=%d\\n", r->akku);\n#endif\n\n#if defined(__linux__)\n    /* Linux-specifikus kód */\n#elif defined(_WIN32)\n    /* Windows */\n#endif\n```\n\nAmi a kihagyott ágba esik, azt a fordító **soha nem is látja** — tehát a szintaktikai hibái sem derülnek ki.' },
      { k: 'callout', tone: 'key', md: 'Hasznos beépített makrók: `__FILE__`, `__LINE__`, `__func__`. Ezekből épül a saját naplózó és ellenőrző makró:\n\n`#define ELLENORIZ(f) do { if (!(f)) fprintf(stderr, "%s:%d: %s\\n", __FILE__, __LINE__, #f); } while (0)`' },
      { k: 'text', md: 'A `do { ... } while (0)` burok nem véletlen: ettől viselkedik a többsoros makró egyetlen utasításként, és nem romlik el egy `if`-ágban pontosvessző nélkül. A `#f` operátor pedig a paramétert sztringgé alakítja.' },
    ],
    quiz: [
      { k: 'single', q: 'Mikor fut a preprocesszor?', opts: ['A fordítás után', 'A fordítás előtt, szöveget helyettesítve', 'Futásidőben'], answer: 1, why: 'Csak szöveget cserél, a C nyelvtanát nem ismeri. A fordító már a kész szöveget kapja.' },
      { k: 'single', q: 'Miért kell zárójel a makróparaméterek köré?', opts: ['Olvashatóbb', 'Mert szöveges behelyettesítés történik, és a műveleti sorrend elromlana', 'Nem kell'], answer: 1, why: 'A `NEGYZET(3+1)` zárójel nélkül `3 + 1 * 3 + 1` lesz, ami 7, nem 16.' },
      { k: 'single', q: 'Mi a baj a `NEGYZET(i++)` hívással?', opts: ['Lassú', 'A makró kétszer értékeli ki, így `i` kétszer nő — meghatározatlan viselkedés', 'Nem fordul le'], answer: 1, why: 'Mellékhatásos kifejezést sosem adj makrónak. Erre való a `static inline` függvény.' },
      { k: 'single', q: 'Mit tartalmaz a `__LINE__` makró?', opts: ['A fájl méretét', 'Az aktuális sorszámot', 'A függvény nevét'], answer: 1, why: 'A `__FILE__`, `__LINE__` és `__func__` hármasból épülnek a naplózó és ellenőrző makrók.' },
      { k: 'single', q: 'Miért `do { ... } while (0)` burokban van a többsoros makró?', opts: ['Hogy egyszer fusson le', 'Hogy egyetlen utasításként viselkedjen, például egy `if`-ágban', 'Hogy gyorsabb legyen'], answer: 1, why: 'Enélkül egy pontosvessző nélküli `if`-ágban a makró szétesne, és csak az első sor tartozna az `if`-hez.' },
    ],
    note: {
      summary: ['A preprocesszor fordítás előtt szöveget helyettesít; nem ismeri a C nyelvtanát.', 'Makróparaméterek és a teljes kifejezés köré mindig zárójel.', 'A makró többször értékelheti a paraméterét: mellékhatást ne adj neki.', 'Ahol lehet, `static inline` függvény jobb: típusbiztos, egyszer értékel.', 'Feltételes fordítás: `#ifdef`, `#if defined(...)`.', '`__FILE__`, `__LINE__`, `__func__` a naplózó makrókhoz.', 'Többsoros makró `do { ... } while (0)` burokban.'],
      terms: [{ term: 'makró', def: 'Szöveges helyettesítési szabály a preprocesszornak.' }, { term: 'feltételes fordítás', def: 'Kódrész kihagyása fordítási időben.' }, { term: 'sztringesítés (#)', def: 'Operátor, ami a makróparamétert sztringgé alakítja.' }],
    },
  },
  {
    day: 16,
    title: 'Make és fordítási folyamat',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A `gcc program.c -o program` parancs mögött **négy lépés** fut le. Érdemes tudni, melyik hibát melyik lépés adja — ettől lesz olvasható a hibaüzenet.' },
      { k: 'text', md: '1. **Preprocesszor** — `#include`, `#define` feloldása. Hiba: „No such file or directory".\n2. **Fordító** — C-ből assembly. Hiba: szintaktikai és típushibák.\n3. **Assembler** — assembly-ből tárgykód (`.o`).\n4. **Linker** — a `.o` fájlok és könyvtárak összefűzése. Hiba: „undefined reference".' },
      { k: 'callout', tone: 'key', md: 'Az **„undefined reference"** mindig linker-hiba: a deklaráció megvolt (különben a fordító szólt volna), de a definíció sehol. Tipikus okok: elfelejtett `.c` fájl a fordítási parancsban, vagy hiányzó `-lm`, `-lpthread` kapcsoló.' },
      { k: 'code', lang: 'c', src: '/* Makefile -- a behúzás TABULÁTOR, nem szóköz! */\nCC      = gcc\nCFLAGS  = -Wall -Wextra -std=c17 -g\nOBJS    = main.o rover.o\n\nrover: $(OBJS)\n\t$(CC) $(CFLAGS) -o rover $(OBJS)\n\n%.o: %.c\n\t$(CC) $(CFLAGS) -c $< -o $@\n\nclean:\n\trm -f rover $(OBJS)', explain: 'A `%.o: %.c` minta minden `.c` fájlra érvényes. A `$<` az első függőség, a `$@` a cél neve. A make csak azt fordítja újra, aminek a forrása frissebb a tárgykódnál.' },
      { k: 'callout', tone: 'warn', md: 'A Makefile parancssorai **tabulátorral** kezdődnek. Szóközzel „missing separator" hibát kapsz, és a szerkesztőben semmi nem látszik belőle. Ez a Makefile első számú kezdő csapdája.' },
      { k: 'text', md: 'A fordítási kapcsolók, amiket mindig tegyél be:\n\n- `-Wall -Wextra` — a figyelmeztetések nagy része valódi hibát jelez\n- `-std=c17` — rögzített nyelvi szabvány\n- `-g` — hibakeresési információ a gdb-hez\n- `-O2` — optimalizálás a kiadáshoz (fejlesztés közben inkább `-O0`)' },
      { k: 'callout', tone: 'tip', md: 'Fejlesztés közben fordíts `-fsanitize=address,undefined` kapcsolóval. Ez futásidőben elkapja a tömbtúlcímzést, a felszabadítás utáni használatot és a meghatározatlan viselkedést — pontos sorszámmal.' },
    ],
    quiz: [
      { k: 'order', q: 'Milyen sorrendben fut a négy lépés?', items: ['Linker', 'Fordító', 'Preprocesszor', 'Assembler'], correct: [2, 1, 3, 0], why: 'Preprocesszor, fordító, assembler, linker. A hibaüzenet forrása megmondja, hol akadt el.' },
      { k: 'single', q: 'Melyik lépés adja az „undefined reference" hibát?', opts: ['Preprocesszor', 'Fordító', 'Linker'], answer: 2, why: 'A deklaráció megvolt, a definíció hiányzik. Tipikusan kimaradt egy `.c` fájl vagy egy `-l` kapcsoló.' },
      { k: 'single', q: 'Mivel kell kezdeni a Makefile parancssorait?', opts: ['Szóközzel', 'Tabulátorral', 'Mindegy'], answer: 1, why: 'Szóközzel „missing separator" hibát kapsz, és a szerkesztőben nem látszik a különbség.' },
      { k: 'single', q: 'Mit jelent a `$<` a Makefile-ban?', opts: ['A cél neve', 'Az első függőség', 'Minden függőség'], answer: 1, why: 'A `$@` a cél, a `$<` az első függőség, a `$^` az összes. Mintaszabályokban ez a három kell.' },
      { k: 'single', q: 'Mit ad a `-fsanitize=address,undefined` kapcsoló?', opts: ['Gyorsabb futást', 'Futásidejű ellenőrzést tömbtúlcímzésre és meghatározatlan viselkedésre', 'Kisebb bináris méretet'], answer: 1, why: 'Pontos sorszámmal jelzi a hibát ott, ahol történik — órákat spórol a hibakeresésen.' },
    ],
    note: {
      summary: ['Négy lépés: preprocesszor, fordító, assembler, linker.', 'Az „undefined reference" mindig linker-hiba: hiányzó definíció vagy könyvtár.', 'A Makefile parancssorai tabulátorral kezdődnek.', 'Mintaszabály: `%.o: %.c`, benne `$<` az első függőség, `$@` a cél.', 'Mindig fordíts `-Wall -Wextra -g` kapcsolókkal.', 'Fejlesztéshez `-fsanitize=address,undefined`.'],
      terms: [{ term: 'tárgykód (.o)', def: 'Lefordított, de még nem linkelt gépi kód.' }, { term: 'linker', def: 'A tárgykódokat és könyvtárakat futtatható programmá fűző lépés.' }, { term: 'mintaszabály', def: 'Makefile szabály, ami fájlnévminta alapján működik.' }],
    },
  },
];
