import type { Day } from '../../types';

/** C trek, 17–23. nap. */
export const cHuD: Day[] = [
  {
    day: 17,
    title: 'Fájlkezelés',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A C fájlkezelése a `<stdio.h>` fejlécben van. A központi típus a `FILE *`: egy mutató, amit a rendszertől kapsz, és amit vissza is kell adnod.' },
      { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nFILE *f = fopen("adatok.txt", "r");\nif (f == NULL) {\n    perror("adatok.txt");      /* kiírja, mi a hiba pontosan */\n    return -1;\n}\n\nchar sor[256];\nwhile (fgets(sor, sizeof sor, f) != NULL) {\n    printf("%s", sor);\n}\n\nfclose(f);', explain: 'A `perror` a rendszer hibaüzenetét írja ki — „No such file" vagy „Permission denied". Sokkal többet mond, mint egy saját „Hiba" felirat.' },
      { k: 'callout', tone: 'key', md: 'A megnyitási módok:\n\n- `"r"` — olvasás, a fájlnak léteznie kell\n- `"w"` — írás, **kiüríti** a meglévő fájlt\n- `"a"` — hozzáfűzés a végéhez\n- `"r+"` — olvasás és írás\n- `"b"` utótag (`"rb"`) — bináris mód, Windowson számít' },
      { k: 'callout', tone: 'warn', md: 'A `"w"` mód **azonnal kiüríti** a fájlt a megnyitáskor, még mielőtt bármit írnál. Ha véletlenül `"w"`-t írsz `"r"` helyett, az adat egy pillanat alatt elvész. Ez a C fájlkezelés legköltségesebb elgépelése.' },
      { k: 'text', md: 'Olvasási függvények és mikor melyik:\n\n- `fgets(puffer, meret, f)` — egy sor, **mérethatárral**. Ezt használd.\n- `fread(puffer, meret, db, f)` — nyers bájtok, bináris fájlhoz\n- `fscanf(f, "%d", &n)` — formázott olvasás; kényelmes, de hibás bemenetnél nehezen kezelhető\n- `gets()` — **soha**. Nincs mérethatára, ezért törölték a szabványból.' },
      { k: 'callout', tone: 'tip', md: 'Írás után a `fclose` üríti ki a puffert a lemezre. Ha a program összeomlik `fclose` nélkül, az utolsó néhány kilobájt elveszhet. Hosszan futó naplózásnál hívj időnként `fflush(f)` függvényt.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit ad vissza az `fopen`, ha nem sikerül?', opts: ['0-t', 'NULL-t', 'Kivételt dob'], answer: 1, why: 'Mindig ellenőrizd. A `perror` utána kiírja a rendszer pontos hibaüzenetét.' },
      { k: 'single', q: 'Mi történik `"w"` módú megnyitáskor?', opts: ['Hozzáfűz a végéhez', 'Azonnal kiüríti a meglévő fájlt', 'Hibát ad, ha létezik'], answer: 1, why: 'Még írás előtt kiürül. Elgépelve `"r"` helyett egy pillanat alatt elveszik az adat.' },
      { k: 'single', q: 'Melyik olvasó függvényt használd sorokhoz?', opts: ['`gets`', '`fgets`', '`scanf`'], answer: 1, why: 'Az `fgets` mérethatárt vesz. A `gets` nem, ezért törölték a szabványból.' },
      { k: 'single', q: 'Mire jó a `perror`?', opts: ['Megnyitja a fájlt', 'Kiírja a rendszer pontos hibaüzenetét', 'Bezárja a fájlt'], answer: 1, why: 'A „No such file" és a „Permission denied" két külön probléma; a saját „Hiba" felirat ezt elrejti.' },
      { k: 'single', q: 'Miért hívj időnként `fflush`-t hosszú naplózásnál?', opts: ['Gyorsabb lesz', 'Mert összeomlásnál a pufferben lévő adat elveszne', 'Mert kötelező'], answer: 1, why: 'A `fclose` üríti a puffert. Ha a program előbb omlik össze, az utolsó kilobájtok elvesznek.' },
    ],
    note: {
      summary: ['A fájlkezelés a `<stdio.h>` fejlécben van, a `FILE *` típussal.', 'Az `fopen` NULL-t ad hibánál; `perror` írja ki a pontos okot.', 'Módok: `r` olvas, `w` kiürít, `a` hozzáfűz, `b` bináris.', 'A `"w"` mód megnyitáskor azonnal kiüríti a fájlt.', 'Sorokhoz `fgets`, bájtokhoz `fread`. A `gets` tilos.', '`fclose` üríti a puffert; hosszú futásnál `fflush`.'],
      terms: [{ term: 'FILE *', def: 'A megnyitott fájlt azonosító mutató.' }, { term: 'perror', def: 'A rendszer utolsó hibaüzenetét kiíró függvény.' }, { term: 'pufferelés', def: 'Az írások gyűjtése memóriában a lemezre írás előtt.' }],
    },
  },
  {
    day: 18,
    title: 'Bitműveletek',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A bitműveletek a szám **egyes bitjeit** állítják. Mikrokontrollernél, tömörítésnél és jelzőbitek kezelésénél elkerülhetetlenek.' },
      { k: 'callout', tone: 'key', md: 'Az öt operátor:\n\n- `&` — ÉS: mindkettőben 1 kell\n- `|` — VAGY: elég az egyikben\n- `^` — KIZÁRÓ VAGY: pontosan az egyikben\n- `~` — tagadás: minden bit átfordul\n- `<<` / `>>` — eltolás balra / jobbra' },
      { k: 'code', lang: 'c', src: '#define LED   (1u << 2)      /* 0000 0100 */\n#define MOTOR (1u << 5)      /* 0010 0000 */\n\nunsigned port = 0;\n\nport |=  LED;                /* bekapcsol  */\nport &= ~MOTOR;              /* kikapcsol  */\nport ^=  LED;                /* átbillent  */\n\nif (port & LED) { /* be van kapcsolva? */ }', explain: 'Ez a négy minta — `|=` bekapcsol, `&= ~` kikapcsol, `^=` átbillent, `&` lekérdez — a teljes bitkezelés. Minden mikrokontroller-kód ezekből áll.' },
      { k: 'text', md: 'Az eltolás szorzás és osztás kettő hatványaival:\n\n`x << 3` ugyanaz, mint `x * 8`\n`x >> 1` ugyanaz, mint `x / 2` (nemnegatív számra)\n\nRégen ezt sebességért írták; ma a fordító magától megteszi, ezért **az olvashatóbb alakot írd**, hacsak nem bitmaszkról van szó.' },
      { k: 'callout', tone: 'warn', md: 'Előjeles számot **ne tolj el**: a negatív szám jobbra tolása a szabvány szerint megvalósításfüggő, a balra tolás pedig meghatározatlan viselkedés túlcsordulásnál. Bitműveletekhez mindig `unsigned` típust használj.' },
      { k: 'callout', tone: 'tip', md: 'Az `1u << n` alakban az `u` nem elhanyagolható: `1 << 31` előjeles `int`-en már meghatározatlan viselkedés, `1u << 31` viszont rendben van.' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan kapcsolsz be egy bitet?', opts: ['`port &= maszk`', '`port |= maszk`', '`port ^= maszk`'], answer: 1, why: 'A VAGY beteszi az 1-et, és a többi bitet érintetlenül hagyja.' },
      { k: 'single', q: 'Hogyan kapcsolsz ki egy bitet?', opts: ['`port |= maszk`', '`port &= ~maszk`', '`port = 0`'], answer: 1, why: 'A tagadott maszkkal vett ÉS kinullázza azt az egy bitet, a többit meghagyja.' },
      { k: 'single', q: 'Mit csinál a `^=` egy maszkkal?', opts: ['Bekapcsol', 'Átbillenti a bitet', 'Lekérdez'], answer: 1, why: 'A kizáró vagy minden kijelölt bitet az ellenkezőjére fordít.' },
      { k: 'single', q: 'Miért használj `unsigned` típust bitműveletekhez?', opts: ['Gyorsabb', 'Mert előjeles számnál az eltolás megvalósításfüggő vagy meghatározatlan', 'Kevesebb helyet foglal'], answer: 1, why: 'Negatív szám jobbra tolása megvalósításfüggő, a balra tolás túlcsordulásnál meghatározatlan.' },
      { k: 'single', q: 'Miért `1u << 31` és nem `1 << 31`?', opts: ['Rövidebb', 'Mert előjeles `int`-en ez meghatározatlan viselkedés', 'Nincs különbség'], answer: 1, why: 'A 31. bit az előjelbit egy 32 bites `int`-en. Az `u` utótag előjel nélkülivé teszi.' },
    ],
    note: {
      summary: ['Operátorok: `&` ÉS, `|` VAGY, `^` kizáró vagy, `~` tagadás, `<<`/`>>` eltolás.', 'Bekapcsol: `|=`. Kikapcsol: `&= ~`. Átbillent: `^=`. Lekérdez: `&`.', 'Maszk készítése: `1u << n`.', 'Eltolás = szorzás/osztás kettő hatványaival, de a fordító ezt magától megteszi.', 'Bitműveletekhez mindig `unsigned` típust használj.'],
      terms: [{ term: 'bitmaszk', def: 'Szám, aminek a beállított bitjei jelölik ki a műveletet.' }, { term: 'eltolás', def: 'A bitek balra vagy jobbra mozgatása.' }, { term: 'kizáró vagy', def: 'Művelet, ami akkor ad 1-et, ha pontosan az egyik bemenet 1.' }],
    },
  },
  {
    day: 19,
    title: 'Enum és union',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Két típuskonstrukció, amit sokan kihagynak, pedig olvashatóbbá és biztonságosabbá teszi a kódot.' },
      { k: 'code', lang: 'c', src: '/* enum: nevesített egészek */\ntypedef enum {\n    ALLAPOT_ALL,\n    ALLAPOT_HALAD,\n    ALLAPOT_FORDUL,\n    ALLAPOT_HIBA\n} Allapot;\n\nAllapot a = ALLAPOT_HALAD;\n\nswitch (a) {\n    case ALLAPOT_ALL:    break;\n    case ALLAPOT_HALAD:  break;\n    case ALLAPOT_FORDUL: break;\n    case ALLAPOT_HIBA:   break;\n}', explain: 'Az enum értékei automatikusan 0-tól számozódnak. A `switch`-ben a fordító **figyelmeztet**, ha kifelejtesz egy esetet — ez a legnagyobb haszna a `#define` konstansokkal szemben.' },
      { k: 'callout', tone: 'key', md: 'Az enum nem csak szépség: ha új állapotot veszel fel, a fordító végigvezet minden `switch`-en, ami nem kezeli. Számokkal vagy makrókkal ez a biztonsági háló nincs meg.' },
      { k: 'code', lang: 'c', src: '/* union: ugyanaz a memória, több nézet */\ntypedef union {\n    float f;\n    unsigned u;\n    unsigned char b[4];\n} Szam32;\n\nSzam32 sz;\nsz.f = 1.5f;\nprintf("%08x\\n", sz.u);        /* a float bitmintája */\nprintf("%02x\\n", sz.b[0]);     /* az első bájt */', explain: 'A union minden tagja **ugyanazon a címen** van. A mérete a legnagyobb tag mérete, nem az összegük. Egyszerre csak egy tag érvényes.' },
      { k: 'callout', tone: 'warn', md: 'A union **nem tartja számon**, melyik tagja érvényes. Ha `f`-et írsz és `u`-t olvasol, nem kapsz hibát — csak értelmetlen eredményt. Ezért jár a union mellett rendszerint egy enum: ez a **címkézett union**.' },
      { k: 'code', lang: 'c', src: 'typedef struct {\n    enum { ERTEK_INT, ERTEK_FLOAT, ERTEK_SZOVEG } tipus;\n    union {\n        int   i;\n        float f;\n        char *s;\n    } ertek;\n} Ertek;', explain: 'A címkézett union a biztonságos minta: a `tipus` mező mondja meg, melyik tag érvényes, és a kód ezt ellenőrzi olvasás előtt.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az enum fő előnye a `#define` konstansokkal szemben?', opts: ['Kevesebb memória', 'A fordító figyelmeztet, ha egy `switch` kifelejt egy esetet', 'Gyorsabb'], answer: 1, why: 'Új állapot felvételekor a fordító végigvezet minden hiányos `switch`-en.' },
      { k: 'single', q: 'Hol helyezkednek el egy union tagjai?', opts: ['Egymás után', 'Ugyanazon a címen, egymásra fedve', 'Külön memóriaterületen'], answer: 1, why: 'A union mérete a legnagyobb tag mérete, nem a tagok összege.' },
      { k: 'single', q: 'Mi történik, ha egy union egyik tagját írod és a másikat olvasod?', opts: ['Fordítási hiba', 'Nincs hiba, csak értelmetlen eredmény', 'Futásidejű kivétel'], answer: 1, why: 'A union nem tartja számon, melyik tag érvényes. Ezért kell címkézett union.' },
      { k: 'single', q: 'Mi a címkézett union?', opts: ['Union név nélkül', 'Struktúra, amiben egy enum mondja meg, melyik union-tag érvényes', 'Két union egymásban'], answer: 1, why: 'Ez a biztonságos minta: a típusmező alapján lehet ellenőrizni az olvasást.' },
      { k: 'single', q: 'Honnan számozódnak az enum értékei alapértelmezésben?', opts: ['1-től', '0-tól', 'Véletlenszerűen'], answer: 1, why: 'Nullától, egyesével. Kézzel is adható érték, és onnan folytatódik a számozás.' },
    ],
    note: {
      summary: ['Az enum nevesített egészeket ad, 0-tól számozva.', 'A `switch`-ben a fordító figyelmeztet a hiányzó enum esetre.', 'A union tagjai ugyanazon a címen fekszenek; mérete a legnagyobb tagé.', 'A union nem tartja számon, melyik tag érvényes.', 'Címkézett union: enum mező plusz union, ez a biztonságos minta.'],
      terms: [{ term: 'enum', def: 'Nevesített egész konstansok típusa.' }, { term: 'union', def: 'Több tagot azonos memóriaterületen tároló típus.' }, { term: 'címkézett union', def: 'Union plusz típusmező, ami jelzi az érvényes tagot.' }],
    },
  },
  {
    day: 20,
    title: 'const és volatile',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'Két módosító, ami nem a tárolásról, hanem a **fordítónak adott ígéretről** szól. Mindkettő rossz használata nehezen megtalálható hibákat okoz.' },
      { k: 'callout', tone: 'key', md: 'A `const` azt jelenti: **ezen keresztül nem írok**. Nem azt, hogy az érték nem változhat — csak azt, hogy ez a hivatkozás nem fogja megváltoztatni.' },
      { k: 'code', lang: 'c', src: '/* Olvasd jobbról balra! */\nconst char *p;        /* mutató const char-ra: *p nem írható, p igen */\nchar *const q;        /* const mutató char-ra: q nem írható, *q igen */\nconst char *const r;  /* egyik sem írható */\n\nvoid kiir(const char *szoveg);   /* ígéret: nem módosítom */', explain: 'A jobbról balra olvasás szabálya mindig működik. A függvényfejben a `const` dokumentáció is: a hívó tudja, hogy a sztringje biztonságban van.' },
      { k: 'text', md: 'A `volatile` az ellenkezője: azt mondja a fordítónak, hogy **a változó bármikor megváltozhat** a kódon kívülről. Ezért nem optimalizálhatja ki az olvasásokat.' },
      { k: 'code', lang: 'c', src: 'volatile int megszakitas_tortent = 0;\n\n/* A megszakításkezelő írja: */\nvoid ISR(void) { megszakitas_tortent = 1; }\n\n/* A főciklus olvassa: */\nwhile (!megszakitas_tortent) {\n    /* volatile nélkül a fordító egyszer olvasna,\n       látná hogy 0, és végtelen ciklust csinálna */\n}', explain: 'A `volatile` nélkül a fordító jogosan feltételezné, hogy a változó nem változik a cikluson belül, és kioptimalizálná az újraolvasást.' },
      { k: 'callout', tone: 'warn', md: 'A `volatile` **nem teszi szálbiztossá** a változót. Nem ad atomi műveletet és nem szinkronizál. Szálak közti közös adathoz `_Atomic` típus vagy mutex kell — a `volatile` csak a megszakításoknál és a hardverregisztereknél jó.' },
      { k: 'callout', tone: 'tip', md: 'A `const` nem csak dokumentáció: a fordító ellenőrzi, és a hívó látja a szándékot. Tedd `const`-tá minden mutató paramétert, amin nem módosítasz — ez a legolcsóbb minőségjavítás a C-ben.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent a `const`?', opts: ['Az érték sosem változhat', 'Ezen a hivatkozáson keresztül nem írok', 'Konstans memóriába kerül'], answer: 1, why: 'Más hivatkozáson keresztül az érték még változhat. A `const` egy ígéret a fordítónak.' },
      { k: 'single', q: 'Mi a különbség a `const char *p` és a `char *const q` közt?', opts: ['Semmi', 'Az elsőnél `*p` nem írható, a másodiknál `q` nem írható', 'Az első gyorsabb'], answer: 1, why: 'Olvasd jobbról balra: ami a `const` után áll, az a védett rész.' },
      { k: 'single', q: 'Mit mond a `volatile` a fordítónak?', opts: ['Hogy gyorsan változik', 'Hogy a változó kívülről is megváltozhat, ezért ne optimalizálja ki az olvasást', 'Hogy szálbiztos'], answer: 1, why: 'Enélkül a fordító egyszer olvasná a változót, és a ciklus sosem lépne ki.' },
      { k: 'single', q: 'Szálbiztossá tesz-e a `volatile`?', opts: ['Igen', 'Nem: nem ad atomi műveletet és nem szinkronizál', 'Csak olvasásra'], answer: 1, why: 'Szálak közti közös adathoz `_Atomic` vagy mutex kell. A `volatile` megszakításokhoz és hardverregiszterekhez való.' },
      { k: 'single', q: 'Mikor tegyél `const`-ot egy mutató paraméterre?', opts: ['Soha', 'Mindig, ha nem módosítasz rajta', 'Csak nagy struktúráknál'], answer: 1, why: 'A fordító ellenőrzi, a hívó látja a szándékot. Ez a legolcsóbb minőségjavítás C-ben.' },
    ],
    note: {
      summary: ['A `const` ígéret: ezen a hivatkozáson keresztül nem írok.', 'A deklarációt jobbról balra olvasd: `const char *p` és `char *const q` más.', 'A `volatile` megtiltja az olvasások kioptimalizálását.', 'A `volatile` megszakításokhoz és hardverregiszterekhez való.', 'A `volatile` nem szálbiztos: ahhoz `_Atomic` vagy mutex kell.', 'Minden nem módosított mutató paraméter legyen `const`.'],
      terms: [{ term: 'const', def: 'Módosító, ami megtiltja az írást az adott hivatkozáson át.' }, { term: 'volatile', def: 'Módosító, ami jelzi, hogy a változó kívülről is változhat.' }, { term: '_Atomic', def: 'Szálbiztos, oszthatatlan műveleteket adó típusmódosító.' }],
    },
  },
  {
    day: 21,
    title: 'Hibakeresés gdb-vel',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A `printf`-es hibakeresés egy darabig működik. A **gdb** viszont megállítja a programot, megmutatja a hívási láncot, és engedi végigléptetni a kódot.' },
      { k: 'callout', tone: 'key', md: 'Fordíts `-g` kapcsolóval, különben a gdb nem látja a forráskódot és a változóneveket:\n\n`gcc -g -O0 program.c -o program`\n\nAz `-O0` is fontos: optimalizálva a sorok összekeverednek, és a változók eltűnhetnek a regiszterekbe.' },
      { k: 'text', md: 'A tíz parancs, amivel elboldogulsz:\n\n- `run` (`r`) — indítás\n- `break fajl.c:42` (`b`) — töréspont\n- `next` (`n`) — következő sor, függvényhívás átugrásával\n- `step` (`s`) — belépés a függvénybe\n- `continue` (`c`) — tovább a következő töréspontig\n- `print valtozo` (`p`) — érték kiírása\n- `backtrace` (`bt`) — a teljes hívási lánc\n- `frame 2` (`f`) — váltás egy hívási szintre\n- `watch valtozo` — megáll, ha a változó megváltozik\n- `quit` (`q`)' },
      { k: 'code', lang: 'c', src: '/* Tipikus menet összeomlás után:\n\n$ gcc -g -O0 rover.c -o rover\n$ gdb ./rover\n(gdb) run\nProgram received signal SIGSEGV, Segmentation fault.\n0x... in rover_lep (r=0x0, cm=10) at rover.c:42\n42          r->x += cm;\n\n(gdb) bt\n#0  rover_lep (r=0x0, cm=10) at rover.c:42\n#1  main () at rover.c:88\n\n(gdb) frame 1\n(gdb) print rover\n$1 = (Rover *) 0x0\n*/', explain: 'A `bt` azonnal megmutatja, hogy a `main` NULL mutatót adott át. A hiba nem a 42. sorban van, hanem a 88-asban — a `bt` nélkül ez nem derülne ki.' },
      { k: 'callout', tone: 'tip', md: 'A **core dump** utólagos boncolást tesz lehetővé. Engedélyezd `ulimit -c unlimited` paranccsal, majd összeomlás után: `gdb ./program core`. Így egy éjjel lefutott teszt hibáját reggel is meg tudod nézni.' },
      { k: 'callout', tone: 'warn', md: 'Ha a gdb `<optimized out>` értéket mutat egy változóra, akkor optimalizálva fordítottál. Fordíts újra `-O0` kapcsolóval — máskülönben olyan kódot nézel, ami nem egyezik a forrással.' },
    ],
    quiz: [
      { k: 'single', q: 'Milyen kapcsolóval kell fordítani a gdb-hez?', opts: ['`-O2`', '`-g` és `-O0`', '`-Wall`'], answer: 1, why: 'A `-g` adja a hibakeresési információt, az `-O0` tartja a sorokat és a változókat a forrással egyezőnek.' },
      { k: 'single', q: 'Mit mutat a `backtrace`?', opts: ['A változókat', 'A teljes hívási láncot a hiba pillanatában', 'A memóriahasználatot'], answer: 1, why: 'Ebből derül ki, hogy a hiba gyakran nem ott van, ahol az összeomlás.' },
      { k: 'single', q: 'Mi a különbség a `next` és a `step` közt?', opts: ['A `step` belép a függvénybe, a `next` átugorja', 'A `next` gyorsabb', 'Nincs különbség'], answer: 0, why: 'Ha nem a hívott függvényben keresed a hibát, `next`-tel gyorsabban haladsz.' },
      { k: 'single', q: 'Mire való a `watch` parancs?', opts: ['Kiírja a változót', 'Megállítja a programot, amikor a változó megváltozik', 'Nyomon követi az időt'], answer: 1, why: 'Akkor hasznos, ha nem tudod, hol romlik el egy érték.' },
      { k: 'single', q: 'Mit jelent az `<optimized out>` érték?', opts: ['A változó törlődött', 'Optimalizálva fordítottál, fordíts újra `-O0` kapcsolóval', 'Hibás a gdb'], answer: 1, why: 'Optimalizálva a változó regiszterbe kerülhet vagy eltűnhet, és a forrással sem egyezik a sorszámozás.' },
    ],
    note: {
      summary: ['Fordíts `-g -O0` kapcsolóval, különben a gdb nem látja a forrást.', 'Alapparancsok: run, break, next, step, continue, print, backtrace, frame, watch.', 'A `backtrace` mutatja, hol kezdődött a baj — nem ott, ahol összeomlott.', '`watch` megáll, amikor egy változó megváltozik.', 'Core dump: `ulimit -c unlimited`, majd `gdb ./program core`.', 'Az `<optimized out>` azt jelenti, hogy újra kell fordítani `-O0`-val.'],
      terms: [{ term: 'töréspont', def: 'Sor, ahol a hibakereső megállítja a programot.' }, { term: 'hívási lánc (backtrace)', def: 'A függvényhívások sorozata az aktuális pontig.' }, { term: 'core dump', def: 'Az összeomlás pillanatának memóriaképe fájlban.' }],
    },
  },
  {
    day: 22,
    title: 'Valgrind és memóriahibák',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A C memóriahibái **csendesek**: a program lefut, és csak néha, máshol omlik össze. A Valgrind és az AddressSanitizer ezeket teszi azonnal láthatóvá.' },
      { k: 'text', md: 'A négy leggyakoribb memóriahiba:\n\n- **Tömbtúlcímzés** — a lefoglalt területen kívülre írsz\n- **Felszabadítás utáni használat** — `free` után még hivatkozol rá\n- **Kétszeres felszabadítás** — ugyanazt kétszer `free`-zed\n- **Inicializálatlan olvasás** — olyan memóriát olvasol, amibe még nem írtál' },
      { k: 'code', lang: 'c', src: '/* $ valgrind --leak-check=full --track-origins=yes ./program\n\n==1234== Invalid write of size 4\n==1234==    at 0x1091AE: main (teszt.c:7)\n==1234==  Address 0x4a4b040 is 0 bytes after a block of size 40 alloc\'d\n==1234==    at 0x484...: malloc\n==1234==    by 0x109195: main (teszt.c:5)\n*/', explain: 'A Valgrind megmondja a hiba helyét (7. sor), a fajtáját (érvénytelen írás), és azt is, hol foglaltad a területet (5. sor). Ennél többet egy hibaüzenet nem adhat.' },
      { k: 'callout', tone: 'key', md: 'Az **AddressSanitizer** ugyanezt adja, de fordításba építve és sokkal gyorsabban:\n\n`gcc -fsanitize=address,undefined -g program.c`\n\nA Valgrind 10–50-szeresére lassítja a programot; az ASan csak 2-szeresére. Fejlesztés közben ezért az ASan a jobb választás.' },
      { k: 'text', md: 'A Valgrind szivárgás-kategóriái:\n\n- **definitely lost** — biztosan elveszett, ezt javítsd\n- **indirectly lost** — egy elveszett szerkezet része\n- **possibly lost** — belső mutató maradt rá; rendszerint gyanús\n- **still reachable** — a program végén még volt rá mutató; gyakran ártalmatlan' },
      { k: 'callout', tone: 'warn', md: 'Az eszközök **csak azt a hibát találják meg, ami tényleg lefut**. Ha egy hibás ág csak minden századik bemenetnél aktiválódik, a Valgrind sem látja. Ezért kell az eszközöket a **teszteken** futtatni, ne csak a kézi próbán.' },
    ],
    quiz: [
      { k: 'single', q: 'Miért veszélyesek a C memóriahibái?', opts: ['Mert azonnal megállítják a programot', 'Mert csendesek: a program lefut, és csak néha, máshol omlik össze', 'Mert lassítanak'], answer: 1, why: 'A hiba helye és a tünet helye gyakran több száz sorra van egymástól.' },
      { k: 'single', q: 'Melyik a gyorsabb fejlesztés közben?', opts: ['Valgrind', 'AddressSanitizer', 'Egyforma'], answer: 1, why: 'A Valgrind 10–50-szeresére lassít, az ASan csak körülbelül kétszeresére.' },
      { k: 'single', q: 'Mit jelent a „definitely lost" kategória?', opts: ['Biztosan elveszett memória, ezt javítsd', 'Még van rá mutató', 'Nem hiba'], answer: 0, why: 'Semmilyen mutató nem maradt rá, tehát soha nem lehet felszabadítani.' },
      { k: 'single', q: 'Mire jó a `--track-origins=yes` kapcsoló?', opts: ['Gyorsít', 'Megmutatja, honnan származik az inicializálatlan érték', 'Szivárgást keres'], answer: 1, why: 'Inicializálatlan olvasásnál ez mondja meg, melyik foglalásból jött az érték.' },
      { k: 'single', q: 'Mi a korlátja ezeknek az eszközöknek?', opts: ['Csak Linuxon futnak', 'Csak a ténylegesen lefutó kód hibáit találják meg', 'Csak kis programokon működnek'], answer: 1, why: 'Ezért kell őket a teljes tesztsoron futtatni, nem csak egy kézi próbán.' },
    ],
    note: {
      summary: ['A C memóriahibái csendesek: máshol és később buknak ki.', 'Négy fajta: tömbtúlcímzés, felszabadítás utáni használat, kétszeres free, inicializálatlan olvasás.', 'Valgrind: `--leak-check=full --track-origins=yes`.', 'AddressSanitizer: `-fsanitize=address,undefined`, sokkal gyorsabb.', 'Szivárgás-kategóriák: definitely, indirectly, possibly lost, still reachable.', 'Csak a ténylegesen lefutó kódot nézik, ezért a teszteken futtasd.'],
      terms: [{ term: 'tömbtúlcímzés', def: 'Írás vagy olvasás a lefoglalt területen kívül.' }, { term: 'AddressSanitizer', def: 'Fordításba épített futásidejű memóriahiba-ellenőrző.' }, { term: 'definitely lost', def: 'Memória, amire semmilyen mutató nem maradt.' }],
    },
  },
  {
    day: 23,
    title: 'Statikus és dinamikus könyvtárak',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **könyvtár** újrahasználható lefordított kód. Kétféleképpen kapcsolható a programhoz, és a kettő között valódi különbség van.' },
      { k: 'callout', tone: 'key', md: '**Statikus** (`.a`): a kód **bemásolódik** a futtatható fájlba. Nagyobb bináris, de önálló: nincs futásidejű függőség.\n\n**Dinamikus** (`.so` Linuxon, `.dll` Windowson): a kód futásidőben töltődik be. Kisebb bináris, és a könyvtár frissíthető a program újrafordítása nélkül.' },
      { k: 'code', lang: 'c', src: '/* Statikus könyvtár készítése\n$ gcc -c rover.c motor.c            # .o fájlok\n$ ar rcs librobot.a rover.o motor.o\n$ gcc main.c -L. -lrobot -o program\n\n   Dinamikus könyvtár készítése\n$ gcc -fPIC -c rover.c motor.c      # pozíciófüggetlen kód\n$ gcc -shared -o librobot.so rover.o motor.o\n$ gcc main.c -L. -lrobot -o program\n$ LD_LIBRARY_PATH=. ./program       # futásidőben meg kell találni\n*/', explain: 'A `-lrobot` a `librobot` névre fordul: a `lib` előtagot és a kiterjesztést a linker teszi hozzá. A `-fPIC` a dinamikus könyvtárhoz kell, mert a kód bárhova betölthető a memóriában.' },
      { k: 'text', md: 'Mikor melyiket?\n\n- **Statikus**: beágyazott rendszer, egyetlen fájlként terjesztett eszköz, vagy ha a futtatókörnyezet kiszámíthatatlan.\n- **Dinamikus**: ha több program osztozik a könyvtáron, vagy ha biztonsági frissítést kell adni újrafordítás nélkül.' },
      { k: 'callout', tone: 'warn', md: 'A dinamikus könyvtár klasszikus baja a **függőségi pokol**: a program egy másik változatot vár, mint ami a gépen van. Az `ldd ./program` megmutatja, melyik könyvtárakat tölti be és melyiket nem találja.' },
      { k: 'callout', tone: 'tip', md: 'A `.so` fájlokat verziószámmal szokás ellátni: `librobot.so.1.2.3`, és szimbolikus linkek mutatnak rá. A **soname** (`librobot.so.1`) jelzi, meddig kompatibilis a felület — ha a fő verziószám nő, a régi programok már nem használhatják.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a statikus könyvtár lényege?', opts: ['Futásidőben töltődik be', 'A kód bemásolódik a futtatható fájlba', 'Csak fordításhoz kell'], answer: 1, why: 'Nagyobb bináris, de nincs futásidejű függőség: önállóan futtatható.' },
      { k: 'single', q: 'Mit jelent a `-lrobot` kapcsoló?', opts: ['A `robot.c` fájlt fordítja', 'A `librobot` nevű könyvtárat linkeli', 'Egy könyvtárat hoz létre'], answer: 1, why: 'A `lib` előtagot és a kiterjesztést a linker teszi hozzá.' },
      { k: 'single', q: 'Miért kell `-fPIC` a dinamikus könyvtárhoz?', opts: ['Gyorsabb', 'Mert a kódnak bárhova betölthetőnek kell lennie a memóriában', 'Kisebb lesz'], answer: 1, why: 'Pozíciófüggetlen kód: nem feltételez rögzített betöltési címet.' },
      { k: 'single', q: 'Mikor válassz statikus könyvtárat?', opts: ['Ha több program osztozik rajta', 'Beágyazott rendszerhez vagy egyetlen fájlként terjesztett eszközhöz', 'Mindig'], answer: 1, why: 'Nincs futásidejű függőség, tehát kiszámíthatatlan környezetben is működik.' },
      { k: 'single', q: 'Mit mutat az `ldd ./program`?', opts: ['A forrásfájlokat', 'Melyik dinamikus könyvtárakat tölti be, és melyiket nem találja', 'A memóriahasználatot'], answer: 1, why: 'Ez az első parancs függőségi probléma esetén.' },
    ],
    note: {
      summary: ['Statikus (`.a`): a kód bemásolódik, nincs futásidejű függőség.', 'Dinamikus (`.so`): futásidőben töltődik, frissíthető újrafordítás nélkül.', 'Készítés: `ar rcs` statikushoz, `-fPIC -shared` dinamikushoz.', 'A `-lrobot` a `librobot` könyvtárra hivatkozik.', 'Statikus beágyazott rendszerhez, dinamikus megosztott használathoz.', '`ldd ./program` mutatja a futásidejű függőségeket.'],
      terms: [{ term: 'statikus könyvtár', def: 'A binárisba bemásolódó lefordított kódgyűjtemény.' }, { term: 'PIC', def: 'Pozíciófüggetlen kód, ami bárhova betölthető.' }, { term: 'soname', def: 'A dinamikus könyvtár felületének kompatibilitási verziója.' }],
    },
  },
];
