import type { Track } from '../../types';
import { cHuB } from './c-b';

export const cHu: Track = {
  id: 'c',
  title: 'C',
  blurb: 'Memória, mutatók, hardverközeli programozás.',
  plannedTitles: [
    'Fordítás és futtatás',
    'Típusok és memória',
    'Mutatók',
    'Elágazás és ciklus',
    'Függvények',
    'Tömbök',
    'Mutató és tömb kapcsolata',
    'Sztringek C-ben',
    'Struktúrák',
    'Dinamikus memória: malloc és free',
    'Memóriaszivárgás',
    'Mutató mutatóra',
    'Függvénymutatók',
    'Fejlécfájlok és fordítási egységek',
    'A preprocesszor',
    'Make és fordítási folyamat',
    'Fájlkezelés',
    'Bitműveletek',
    'Enum és union',
    'const és volatile',
    'Hibakeresés gdb-vel',
    'Valgrind és memóriahibák',
    'Statikus és dinamikus könyvtárak',
    'Szabványos könyvtár',
    'Mikrokontroller és C',
    'Regiszterek írása',
    'Megszakítások',
    'Beágyazott programozás stílusa',
    'Egy kis beágyazott program',
    'A teljes projekt',
  ],
  days: [
    {
      day: 1,
      title: 'Fordítás és futtatás',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'A C a legtöbb operációs rendszer, mikrokontroller-firmware és maga a Python értelmező nyelve. Közel van a géphez: amit leírsz, nagyjából az történik.' },
        { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nint main(void) {\n    printf("Szia, C!\\n");\n    return 0;\n}', explain: 'A `#include` behúzza a `printf` deklarációját. A `return 0` azt jelenti: a program hiba nélkül futott le — ezt az operációs rendszer olvassa.' },
        { k: 'text', md: 'Fordítás és futtatás Linuxon:\n\n```\ngcc hello.c -o hello\n./hello\n```\n\nA `-o hello` adja a kimeneti fájl nevét. Nélküle `a.out` lesz.' },
        { k: 'callout', tone: 'key', md: 'A C **fordított** nyelv: a forrásból gépi kód lesz, és az fut. Nincs értelmező, nincs virtuális gép. Ezért gyors, és ezért kell újrafordítani minden gépre külön.' },
        { k: 'callout', tone: 'warn', md: 'Mindig fordíts figyelmeztetésekkel: `gcc -Wall -Wextra hello.c -o hello`. A C sok hibát szó nélkül lefordít, és a figyelmeztetések nagy részéből később futásidejű összeomlás lesz.' },
      ],
      quiz: [
        { k: 'single', q: 'Mit csinál a `#include <stdio.h>`?', opts: ['Futtatja a programot', 'Behúzza a szabványos be- és kimenet deklarációit, például a printf-ét', 'Lefordítja a fájlt'], answer: 1, why: 'A fejlécfájl mondja meg a fordítónak, hogy létezik a `printf` és milyen paramétereket vár. Nélküle figyelmeztetést vagy hibát kapsz.' },
        { k: 'single', q: 'Mit jelent a `return 0` a main végén?', opts: ['Nullát ír ki', 'A program hibátlanul lefutott', 'Újraindítja a programot'], answer: 1, why: 'A main visszatérési értéke a kilépési kód. A nulla a siker, minden más hibát jelez az operációs rendszer felé.' },
        { k: 'single', q: 'Miért érdemes `-Wall -Wextra` kapcsolóval fordítani?', opts: ['Gyorsabb lesz a program', 'Mert a C sok veszélyes hibát szó nélkül lefordítana', 'Kisebb lesz a fájl'], answer: 1, why: 'A C megengedő: sok olyat elfogad, amiből később összeomlás lesz. A figyelmeztetések ezeket jelzik fordításkor.' },
        { k: 'single', q: 'Mi a különbség a C és a Python futtatása közt?', opts: ['Semmi', 'A C-ből gépi kód fordul, a Pythont értelmező futtatja', 'A C lassabb'], answer: 1, why: 'A C forrásból közvetlenül futtatható gépi kód lesz. A Python kódot menet közben értelmezi egy program — ezért lassabb, de hordozhatóbb.' },
      ],
      note: {
        summary: ['A C fordított nyelv: a forrásból gépi kód lesz, nincs értelmező vagy virtuális gép.', '`gcc hello.c -o hello` fordít, `./hello` futtat.', 'A `#include` fejlécfájlt húz be, ami a függvények deklarációját adja.', 'A main `return 0` értéke a kilépési kód: nulla a siker.', 'Mindig fordíts `-Wall -Wextra` kapcsolóval — a figyelmeztetésekből lesznek az összeomlások.'],
        terms: [{ term: 'fordító', def: 'Program, ami a forráskódból futtatható gépi kódot készít.' }, { term: 'fejlécfájl', def: 'Deklarációkat tartalmazó fájl, amit a `#include` húz be.' }, { term: 'kilépési kód', def: 'A main visszatérési értéke, amit az operációs rendszer olvas.' }],
      },
    },
    {
      day: 2,
      title: 'Típusok és memória',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'A C-ben a változó nem absztrakció, hanem **egy hely a memóriában**, adott számú bájttal. Ha ezt érted, a mutatók sem lesznek nehezek.' },
        { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nint main(void) {\n    int a = 42;\n    double d = 3.14;\n    char c = \'X\';\n\n    printf("%d %f %c\\n", a, d, c);\n    printf("%zu %zu %zu\\n", sizeof(a), sizeof(d), sizeof(c));\n    return 0;\n}', explain: 'A `printf` **formátumjelölőkkel** dolgozik: `%d` egész, `%f` tizedes, `%c` karakter. A `sizeof` megmondja, hány bájtot foglal.' },
        { k: 'callout', tone: 'warn', md: 'Ha rossz formátumjelölőt adsz meg (`%d`-t egy `double`-höz), a C **nem szól** — csak szemetet ír ki, vagy összeomlik. Ez a nyelv egyik legélesebb pengéje.' },
        { k: 'text', md: 'Tipikus méretek 64 bites gépen: `char` 1 bájt, `int` 4, `double` 8. De ez **nem garantált** — a szabvány csak minimumokat ír elő. Beágyazott rendszereken az `int` lehet 2 bájt is.' },
        { k: 'callout', tone: 'key', md: 'Az **inicializálatlan** változó értéke C-ben nem nulla, hanem szemét: ami épp a memóriában volt. Egy ilyen hiba néha működik, néha nem — és ettől a legnehezebb megtalálni. Mindig adj kezdőértéket.' },
      ],
      quiz: [
        { k: 'single', q: 'Mi az értéke egy inicializálatlan lokális változónak C-ben?', opts: ['Nulla', 'Meghatározatlan szemét', 'NULL'], answer: 1, why: 'A C nem nullázza a lokális változókat. Ami a memóriában volt, az lesz benne — ezért viselkedik egy ilyen program néha jól, néha rosszul.' },
        { k: 'numeric', q: 'Hány bájt egy `double` tipikusan 64 bites gépen?', answer: 8, tol: 0.5, why: 'A `double` általában 8 bájt (64 bit). Az `int` 4, a `char` pedig definíció szerint mindig 1.' },
        { k: 'single', q: 'Mi történik rossz formátumjelölő esetén?', opts: ['Fordítási hiba', 'A program szemetet ír ki vagy összeomlik', 'Automatikusan javítja'], answer: 1, why: 'A `printf` futásidőben olvassa a jelölőket, és elhiszi, amit mondasz neki. Rossz típusnál rossz bájtokat értelmez.' },
        { k: 'single', q: 'Mit ad a `sizeof(x)`?', opts: ['A változó értékét', 'Hány bájtot foglal a memóriában', 'A változó nevét'], answer: 1, why: 'A `sizeof` a típus méretét adja bájtban. Dinamikus memóriafoglalásnál ez nélkülözhetetlen.' },
      ],
      note: {
        summary: ['A C-ben a változó egy memóriahely, adott számú bájttal.', '`sizeof` megmondja a méretet; `char` 1, `int` tipikusan 4, `double` 8 bájt.', 'A méretek nem garantáltak — beágyazott rendszeren eltérhetnek.', 'A `printf` formátumjelölőkkel dolgozik: %d, %f, %c; rossz jelölő szemetet ír ki.', 'Az inicializálatlan lokális változó értéke szemét, nem nulla.'],
        terms: [{ term: 'sizeof', def: 'Operátor, ami egy típus vagy változó bájtban mért méretét adja.' }, { term: 'formátumjelölő', def: 'A printf-ben az érték típusát megadó jelölés, például %d.' }, { term: 'inicializálatlan változó', def: 'Kezdőérték nélküli változó, aminek a tartalma meghatározatlan.' }],
      },
    },
    {
      day: 3,
      title: 'Mutatók',
      minutes: 24,
      lesson: [
        { k: 'text', md: 'A mutató a C hírhedt témája, pedig egyszerű: a **mutató egy változó, ami egy memóriacímet tárol**. Nem az értéket — azt, hogy hol van az érték.' },
        { k: 'code', lang: 'c', src: 'int a = 42;\nint *p = &a;      // p az a címét tárolja\n\nprintf("%d\\n", a);     // 42  — az érték\nprintf("%p\\n", (void*)p);  // 0x7ffd...  — a cím\nprintf("%d\\n", *p);    // 42  — az érték a címen\n\n*p = 99;\nprintf("%d\\n", a);     // 99  — az a is megváltozott!', explain: 'Az `&` a „címe", a `*` a „mutasd, mi van ott". A kettő egymás ellentéte.' },
        { k: 'callout', tone: 'key', md: 'Miért kell ez? Mert C-ben a függvény **másolatot** kap a paraméterről. Ha a függvénynek módosítania kell a hívó változóját, a címét kell megkapnia — más mód nincs rá.' },
        { k: 'code', lang: 'c', src: 'void novel(int *x) {\n    *x = *x + 1;\n}\n\nint main(void) {\n    int szam = 5;\n    novel(&szam);\n    printf("%d\\n", szam);    // 6\n    return 0;\n}', explain: 'A `&szam` átadja a címet, a függvény pedig a `*x`-en át írja az eredetit. Enélkül a `novel(szam)` csak a másolatot növelné.' },
        { k: 'callout', tone: 'warn', md: 'A **NULL mutató** feloldása (`*p`, ha `p == NULL`) azonnali összeomlás. Mielőtt feloldasz egy mutatót, amiről nem tudod biztosan, hogy érvényes, ellenőrizd: `if (p != NULL)`.' },
      ],
      quiz: [
        { k: 'single', q: 'Mit tárol egy mutató?', opts: ['Az értéket', 'Egy memóriacímet', 'A változó nevét'], answer: 1, why: 'A mutató azt tárolja, **hol** van az érték. Magához az értékhez a `*` operátorral jutsz.' },
        { k: 'single', q: 'Mit csinál az `&a`?', opts: ['Megadja az a értékét', 'Megadja az a memóriacímét', 'Megduplázza az a-t'], answer: 1, why: 'Az `&` a címképző operátor. Ez az, amit egy mutatóba el lehet tenni.' },
        { k: 'output', q: 'Mit ír ki?', code: 'int a = 5;\nint *p = &a;\n*p = 10;\nprintf("%d", a);', lang: 'c', opts: ['5', '10', '0'], answer: 1, why: 'A `*p = 10` azon a címen ír, ahol az `a` van, tehát az `a` értéke változik meg.' },
        { k: 'single', q: 'Miért kell mutató, ha egy függvény módosítani akarja a hívó változóját?', opts: ['Mert gyorsabb', 'Mert a függvény egyébként csak másolatot kap', 'Mert a C megköveteli'], answer: 1, why: 'A paraméter érték szerint adódik át: a függvény a másolatot módosítaná. A címmel viszont az eredetihez fér hozzá.' },
      ],
      note: {
        summary: ['A mutató egy memóriacímet tároló változó, nem magát az értéket.', 'Az `&` a címet adja, a `*` feloldja: megmutatja, mi van azon a címen.', 'A függvény érték szerint kapja a paramétert — módosításhoz a címét kell átadni.', 'A `*p = x` azon a helyen ír, ahova a mutató mutat.', 'NULL mutató feloldása azonnali összeomlás; ellenőrizd feloldás előtt.'],
        terms: [{ term: 'mutató', def: 'Memóriacímet tároló változó.' }, { term: 'címképző operátor (&)', def: 'Egy változó memóriacímét adja vissza.' }, { term: 'feloldás (*)', def: 'A mutató által megadott címen lévő értékhez való hozzáférés.' }],
      },
    },
    ...cHuB,
  ],
};
