import type { Day } from '../../types';

/** CAD trek, 20–26. nap. */
export const cadHuE: Day[] = [
  {
    day: 20,
    title: 'Motorrögzítés tervezése',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A motortartó az első igazi tervezési feladat: adott egy szabványos alkatrész, és neked kell hozzá illeszkedő, merev, szerelhető darabot készíteni.' },
      { k: 'callout', tone: 'key', md: 'A tervezés mindig az **adatlappal** kezdődik. Egy motortartóhoz négy méret kell:\n\n1. A **központosító perem** átmérője és mélysége\n2. A **furatosztókör** átmérője és a furatok száma\n3. A **tengely** átmérője és kiállása\n4. A motor **hossza** és a csatlakozók helye' },
      { k: 'text', md: 'A szabványos NEMA 17 léptetőmotor például: 42,3 mm négyzet, 31 mm furatosztókör négy M3 furattal, 22 mm központosító perem, 5 mm tengely. Ezek a számok mennek a paraméterlistába, nem a vázlatba közvetlenül.' },
      { k: 'callout', tone: 'warn', md: 'A **központosító perem** fontosabb, mint a csavarok. Az tartja a motort pontosan a helyén; a csavarok csak leszorítják. Ha a perem laza, a motor a furatok játékán belül elmozdul, és a fogaskerék elállítódik. A perem hézaga 0,1–0,2 mm legyen, ne több.' },
      { k: 'text', md: 'Merevség: a motortartó a nyomatékot adja át, ezért hajlításra terhelt. Három olcsó megoldás:\n\n- **Bordák** a fal és az alap közt — a legnagyobb nyereség a legkevesebb anyagért\n- **Vastagabb fal** a tő közelében, vékonyabb a széleken\n- **Nagyobb érintkező felület** az alaplemezzel' },
      { k: 'callout', tone: 'tip', md: 'Tervezz **szerelési hozzáférést**: a motor csavarjait rendszerint a tartó felől kell behajtani, és a kulcsnak oda kell férnie. Modellezd be a csavart és a szerszám hengerét is, és forgasd körbe a szerelvényt.' },
      { k: 'text', md: 'Végül hagyj helyet a **kábeleknek**: a motor csatlakozója rendszerint hátul van, és a kivezetésnek útja kell legyen. Egy kábelkivágás a tervezés során két perc; utólag reszelővel fél óra.' },
    ],
    quiz: [
      { k: 'single', q: 'Mivel kezdődik a motortartó tervezése?', opts: ['A vázlattal', 'Az adatlappal: perem, furatosztókör, tengely, hossz', 'A renderrel'], answer: 1, why: 'Ezek a számok mennek a paraméterlistába, és onnan hivatkozik rájuk a vázlat.' },
      { k: 'single', q: 'Mi tartja a motort pontosan a helyén?', opts: ['A csavarok', 'A központosító perem', 'A kábel'], answer: 1, why: 'A csavarok csak leszorítanak. Laza peremnél a motor a furatok játékán belül elmozdul.' },
      { k: 'single', q: 'Mekkora legyen a központosító perem hézaga?', opts: ['0,5-1 mm', '0,1-0,2 mm', 'Nincs hézag'], answer: 1, why: 'Nagyobb hézagnál a fogaskerék elállítódik a motor elmozdulásával.' },
      { k: 'single', q: 'Mi a legolcsóbb merevítés hajlításra terhelt tartónál?', opts: ['Teljesen tömör darab', 'Bordák a fal és az alap közt', 'Nagyobb csavarok'], answer: 1, why: 'A legnagyobb merevségnövekedés a legkevesebb anyagért.' },
      { k: 'single', q: 'Mire kell még helyet hagyni?', opts: ['A kábelkivezetésnek', 'A festésnek', 'A címkének'], answer: 0, why: 'Egy kábelkivágás tervezéskor két perc, utólag reszelővel fél óra.' },
    ],
    note: {
      summary: ['A tervezés az adatlappal kezdődik, nem a vázlattal.', 'Négy méret kell: perem, furatosztókör, tengely, hossz.', 'A központosító perem tart, a csavarok csak szorítanak.', 'A perem hézaga 0,1-0,2 mm legyen.', 'Merevítés bordákkal, vastagabb tővel, nagyobb érintkezéssel.', 'Tervezz szerszám-hozzáférést és kábelkivezetést.'],
      terms: [{ term: 'központosító perem', def: 'A motor helyzetét rögzítő körkörös illeszkedés.' }, { term: 'furatosztókör', def: 'A rögzítőfuratok középpontjain átmenő kör átmérője.' }, { term: 'borda', def: 'Merevítő lemez két felület között.' }],
    },
  },
  {
    day: 21,
    title: 'Kábelvezetés',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A kábelvezetést szinte mindenki a végén, utólag találja ki — és ez az egyik leggyakoribb oka annak, hogy egy szép gép megbízhatatlan lesz.' },
      { k: 'callout', tone: 'key', md: 'A kábel **nem végtelenül hajlítható**. Minden kábelnek van **minimális hajlítási sugara**, jellemzően az átmérő 4–8-szorosa álló helyzetben, és 10–15-szöröse, ha mozgás közben is hajlik. Szűkebb ívben a vezetékszálak idővel elszakadnak.' },
      { k: 'text', md: 'A mozgó kábel a legnehezebb eset. Három megoldás:\n\n- **Energialánc** (drag chain) — lineáris mozgáshoz, megvezeti és korlátozza a hajlást\n- **Szolgahurok** (service loop) — nagy, lusta hurok, ami kinyílik és becsukódik\n- **Csúszógyűrű** (slip ring) — folyamatosan forgó tengelyhez, ahol kábel nem vezethető át' },
      { k: 'callout', tone: 'warn', md: 'A **tehermentesítés** nem elhagyható. A kábelt a csatlakozó előtt rögzítsd a házhoz, hogy a húzóerő a rögzítésre essen, ne a forrasztott érintkezőre. Enélkül a csatlakozó előbb-utóbb leszakad — és a hiba szakaszos lesz, ami a legnehezebben kereshető.' },
      { k: 'text', md: 'Elválasztás: a **motorkábel zajos**, a jelkábel érzékeny. Vezesd őket **külön útvonalon**, és ha keresztezniük kell, akkor derékszögben. A párhuzamosan, hosszan egymás mellett futó motor- és jelkábel a hibás szenzorjelek klasszikus oka.' },
      { k: 'callout', tone: 'tip', md: 'Tervezz **kábelcsatornát vagy -kapcsot** a modellbe. Egy nyomtatott kapocs néhány grammba kerül, és a kábelt ott tartja, ahol tervezted. A ragasztószalag két hét alatt leválik és a kábel bekerül a hajtásba.' },
      { k: 'text', md: 'Utolsó szempont a **szerelhetőség**: a kábelnek legyen útja a beszereléshez. Ha a vezetéket előbb kell behúzni, mint a motort beszerelni, dokumentáld — különben a következő összeszerelésnél mindent szét kell szedni.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a minimális hajlítási sugár nagyságrendje mozgó kábelnél?', opts: ['Az átmérő 1-2-szerese', 'Az átmérő 10-15-szöröse', 'Nincs korlát'], answer: 1, why: 'Álló helyzetben 4-8-szoros is elég, de mozgás közben jóval nagyobb kell.' },
      { k: 'single', q: 'Mire való az energialánc?', opts: ['Áramot vezet', 'Lineáris mozgásnál megvezeti és korlátozza a kábel hajlását', 'Szigetel'], answer: 1, why: 'Forgó tengelyhez csúszógyűrű, kisebb mozgáshoz szolgahurok való.' },
      { k: 'single', q: 'Mire való a tehermentesítés?', opts: ['Szigetel', 'Hogy a húzóerő a rögzítésre essen, ne a forrasztott érintkezőre', 'Hűti a kábelt'], answer: 1, why: 'Enélkül a csatlakozó leszakad, és szakaszos hibát okoz — a legnehezebben kereshetőt.' },
      { k: 'single', q: 'Hogyan vezesd a motor- és a jelkábelt?', opts: ['Egymás mellett', 'Külön útvonalon, keresztezés derékszögben', 'Összekötve'], answer: 1, why: 'A hosszan párhuzamosan futó kábelek a hibás szenzorjelek klasszikus oka.' },
      { k: 'single', q: 'Miért jobb a nyomtatott kábelkapocs a ragasztószalagnál?', opts: ['Szebb', 'Mert a szalag két hét alatt leválik és a kábel a hajtásba kerül', 'Olcsóbb'], answer: 1, why: 'A kapocs néhány grammba kerül, és ott tartja a kábelt, ahol tervezted.' },
    ],
    note: {
      summary: ['A kábelvezetést tervezd, ne utólag találd ki.', 'Minimális hajlítási sugár: álló 4-8×, mozgó 10-15× az átmérő.', 'Mozgó kábelhez energialánc, szolgahurok vagy csúszógyűrű.', 'Tehermentesítés nélkül a csatlakozó leszakad.', 'Motor- és jelkábel külön útvonalon, keresztezés derékszögben.', 'Tervezz kábelcsatornát vagy -kapcsot a modellbe.'],
      terms: [{ term: 'hajlítási sugár', def: 'A legkisebb ív, amiben a kábel sérülés nélkül hajlik.' }, { term: 'tehermentesítés', def: 'A kábelt rögzítő elem, ami leveszi a húzóerőt a csatlakozóról.' }, { term: 'energialánc', def: 'Tagokból álló vezeték, ami megvezeti a mozgó kábelt.' }],
    },
  },
  {
    day: 22,
    title: 'Műszaki rajz',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A 3D modell a tervezéshez kell; a **műszaki rajz** a gyártáshoz. Ez a dokumentum mondja meg a gyártónak, mit kell készítenie, és ez az, ami jogilag is érvényes.' },
      { k: 'callout', tone: 'key', md: 'Európában az **első szögű vetítés** a szabvány (ISO), Amerikában a **harmadik szögű**. A kettő egymás tükörképe. A rajzon mindig szerepeljen a jelzése — egy félreértett vetítési mód tükörképben legyártott alkatrészt eredményez.' },
      { k: 'text', md: 'A szokásos nézetrend:\n\n- **Főnézet** — a legtöbb információt hordozó irány, rendszerint a használati helyzet\n- **Felülnézet** és **oldalnézet** — csak amennyi szükséges\n- **Metszet** — belső szerkezethez; a vágósíkot nyilakkal jelöld\n- **Részletnézet** — kinagyított rész, ha a méret nem fér ki' },
      { k: 'callout', tone: 'warn', md: 'A szabály: **annyi nézet, amennyi feltétlenül kell, és nem több**. Minden felesleges nézet újabb hely, ahol ellentmondás keletkezhet, ha a modell változik. Egy forgásszimmetrikus alkatrészhez gyakran egyetlen nézet és egy metszet elég.' },
      { k: 'text', md: 'A rajz kötelező elemei:\n\n- **Fejléc** (title block): alkatrésznév, rajzszám, **méretarány**, anyag, készítő, dátum, verzió\n- **Általános tűrés** megadása (például ISO 2768-m)\n- **Felületi érdesség**, ahol számít\n- **Darabjegyzék** (BOM) szerelvényrajznál' },
      { k: 'callout', tone: 'tip', md: 'A rajz legyen **társított** a modellhez: ha a modell változik, a rajz méretei maguktól frissülnek. Kézzel beírt méretek esetén előbb-utóbb lesz két egymásnak ellentmondó szám, és a gyártó a rosszat fogja követni.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a műszaki rajz szerepe a 3D modell mellett?', opts: ['Szebb', 'Ez mondja meg a gyártónak, mit kell készítenie, és ez a jogilag érvényes dokumentum', 'Gyorsabb'], answer: 1, why: 'A modell a tervezéshez kell; a rajz a gyártáshoz és az átadáshoz.' },
      { k: 'single', q: 'Mi a különbség az első és a harmadik szögű vetítés közt?', opts: ['Egymás tükörképei', 'Az egyik színes', 'A méretarány'], answer: 0, why: 'Európa az elsőt, Amerika a harmadikat használja. Jelezni kell, különben tükörképben készül az alkatrész.' },
      { k: 'single', q: 'Hány nézet kerüljön a rajzra?', opts: ['Minél több', 'Annyi, amennyi feltétlenül kell', 'Pontosan hat'], answer: 1, why: 'Minden felesleges nézet újabb hely, ahol ellentmondás keletkezhet modellváltozáskor.' },
      { k: 'single', q: 'Mi kerül a fejlécbe (title block)?', opts: ['Csak a név', 'Név, rajzszám, méretarány, anyag, készítő, dátum, verzió', 'A render'], answer: 1, why: 'Enélkül a rajz nem azonosítható, és nem tudni, melyik változat érvényes.' },
      { k: 'single', q: 'Miért legyen a rajz társított a modellhez?', opts: ['Kisebb fájl', 'Hogy a méretek automatikusan frissüljenek, és ne legyen két ellentmondó szám', 'Gyorsabb nyomtatás'], answer: 1, why: 'Kézzel beírt méretnél a gyártó előbb-utóbb a rosszat fogja követni.' },
    ],
    note: {
      summary: ['A modell a tervezéshez, a rajz a gyártáshoz kell.', 'Európa első szögű, Amerika harmadik szögű vetítést használ — jelezni kell.', 'Nézetek: fő-, felül-, oldalnézet, metszet, részletnézet.', 'Annyi nézet, amennyi feltétlenül kell.', 'Kötelező: fejléc, általános tűrés, felületi érdesség, szerelvénynél BOM.', 'A rajz legyen társított a modellhez.'],
      terms: [{ term: 'első szögű vetítés', def: 'Az európai szabvány szerinti nézetelrendezés.' }, { term: 'fejléc (title block)', def: 'A rajz azonosító adatait tartalmazó mező.' }, { term: 'társított rajz', def: 'A modellel összekötött rajz, ami automatikusan frissül.' }],
    },
  },
  {
    day: 23,
    title: 'Méretezés és jelölések',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A méretezés nem a számok rárakása a rajzra: az a kérdés, **mi az, ami a működés szempontjából számít**, és azt kell megadni.' },
      { k: 'callout', tone: 'key', md: 'A legfontosabb szabály: **minden méret pontosan egyszer szerepeljen**. A kétszer megadott méret ellentmondásba kerülhet, és akkor a gyártó választ — rendszerint rosszul. Ami levezethető, azt ne add meg újra.' },
      { k: 'text', md: 'Honnan mérj? A **funkcionális bázistól**. Ha négy furatnak egy motorhoz kell illeszkednie, a furatokat egymáshoz és a központosító peremhez méretezd, ne az alkatrész széléhez. A szél tűrése nem számít; a furatok egymáshoz mért helye igen.' },
      { k: 'text', md: 'Szokásos jelölések:\n\n- **⌀20** — átmérő\n- **R5** — sugár\n- **□15** — négyzet keresztmetszet\n- **4× ⌀3.2** — négy azonos furat, elég egyszer megadni\n- **▽** — felületi érdesség jele\n- **⌴** — süllyesztés' },
      { k: 'callout', tone: 'warn', md: 'A **lánc méretezés** (minden méret az előzőtől mérve) halmozza a tűrést: öt egymás utáni ±0,1 mm méret a végén ±0,5 mm bizonytalanságot ad. Ha a végpont helye számít, **egy közös bázistól** méretezz (párhuzamos méretezés).' },
      { k: 'callout', tone: 'tip', md: 'A **GD&T** (geometriai méret- és tűréstűrés) a következő szint: nem csak a méretet, hanem az **alakot és a helyzetet** is tűrésezi — síklapúság, merőlegesség, pozíciótűrés. Pontos illesztéseknél ez mondja meg azt, amit a sima ±0,1 nem tud.' },
    ],
    quiz: [
      { k: 'single', q: 'Hányszor szerepeljen egy méret a rajzon?', opts: ['Minél többször', 'Pontosan egyszer', 'Kétszer, ellenőrzésképpen'], answer: 1, why: 'A kétszer megadott méret ellentmondásba kerülhet, és a gyártó választ — rendszerint rosszul.' },
      { k: 'single', q: 'Honnan méretezd a motorfuratokat?', opts: ['Az alkatrész szélétől', 'Egymáshoz és a központosító peremhez: a funkcionális bázistól', 'Az origótól'], answer: 1, why: 'A szél tűrése nem számít; a furatok egymáshoz mért helye igen.' },
      { k: 'single', q: 'Mi a baj a lánc méretezéssel?', opts: ['Hosszabb', 'Halmozza a tűrést: öt ±0,1 méret a végén ±0,5-öt ad', 'Nem szabványos'], answer: 1, why: 'Ha a végpont helye számít, egy közös bázistól méretezz.' },
      { k: 'single', q: 'Mit jelent a `4× ⌀3.2` jelölés?', opts: ['3,2 mm-es furat négyszer nagyítva', 'Négy darab azonos, 3,2 mm átmérőjű furat', 'Négy réteg'], answer: 1, why: 'Elég egyszer megadni; nem kell mind a négyet külön méretezni.' },
      { k: 'single', q: 'Mit tűrésez a GD&T a mérethez képest?', opts: ['Semmit', 'Az alakot és a helyzetet is: síklapúság, merőlegesség, pozíció', 'A színt'], answer: 1, why: 'Pontos illesztéseknél ez mondja meg azt, amit a sima ±0,1 nem tud.' },
    ],
    note: {
      summary: ['Minden méret pontosan egyszer szerepeljen.', 'A funkcionális bázistól méretezz, ne az alkatrész szélétől.', 'Jelölések: ⌀ átmérő, R sugár, 4× ismétlés, ▽ érdesség.', 'A lánc méretezés halmozza a tűrést: közös bázistól méretezz.', 'A GD&T az alakot és a helyzetet is tűrésezi.'],
      terms: [{ term: 'funkcionális bázis', def: 'Az a felület vagy elem, amihez a működés szempontjából mérni kell.' }, { term: 'lánc méretezés', def: 'Egymástól mért méretek sorozata, ami halmozza a tűrést.' }, { term: 'GD&T', def: 'Geometriai méret- és alaktűrés-rendszer.' }],
    },
  },
  {
    day: 24,
    title: 'Anyagválasztás',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az anyagválasztás ritkán arról szól, melyik a legjobb. Arról szól, **melyik elég jó** a leggyorsabban és a legolcsóbban.' },
      { k: 'text', md: 'A robotépítés szokásos anyagai:\n\n- **PLA** — nyomtatható, merev, olcsó. 60 fok fölött lágyul; motor közelében kerülendő.\n- **PETG** — szívósabb, hőállóbb (80 fok), kicsit nehezebb nyomtatni. Jó alapértelmezés.\n- **ABS / ASA** — hőálló és UV-álló, de vetemedik és szagos.\n- **Nylon** — nagyon szívós, kopásálló; fogaskerékhez. Nedvszívó, szárítani kell.\n- **Alumínium** — merev, hővezető, megmunkálható. Nehezebb és drágább.\n- **Acél** — ahol a szilárdság és a kopásállóság dönt: tengely, csapágyhely.' },
      { k: 'callout', tone: 'key', md: 'A döntés három kérdésből áll:\n\n1. **Mekkora erő** éri, és meddig hajolhat?\n2. **Milyen hőmérsékleten** üzemel?\n3. **Hogyan készül** — nyomtatás, marás, lézervágás, hajlítás?\n\nA gyártási mód sokszor többet nyom a latban, mint az anyagjellemző.' },
      { k: 'callout', tone: 'warn', md: 'A **PLA a motor mellett** a leggyakoribb kezdő hiba. Egy terhelt motor háza könnyen 60–70 fok, és a PLA ott már lágyul: a tartó lassan megfolyik, a tengely elállítódik, és nem érted, miért romlott el a gép magától. Motor közelébe PETG, ABS vagy fém.' },
      { k: 'text', md: 'A **kopás** külön szempont. Ahol két felület egymáson mozog, legyen a kettő **különböző** anyag — két azonos fém összehegedhet. A műanyag-fém pár rendszerint jól működik, és a lágyabb elem a cserélhető.' },
      { k: 'callout', tone: 'tip', md: 'Prototípushoz mindig a **leggyorsabban elkészíthetőt** válaszd, akkor is, ha nem optimális. Egy nyomtatott PETG darab ma este kész; a mart alumínium jövő héten. A tervezési hibát előbb találd meg, és utána válts anyagot.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a jó alapértelmezés nyomtatott robotalkatrészhez?', opts: ['PLA', 'PETG', 'Nylon'], answer: 1, why: 'Szívósabb és hőállóbb a PLA-nál, és még könnyen nyomtatható.' },
      { k: 'single', q: 'Miért nem jó a PLA a motor mellé?', opts: ['Túl merev', '60 fok fölött lágyul, és a motorház könnyen ennél melegebb', 'Nem nyomtatható'], answer: 1, why: 'A tartó lassan megfolyik, a tengely elállítódik, és a hiba magától jelenik meg.' },
      { k: 'single', q: 'Melyik anyag való fogaskerékhez?', opts: ['PLA', 'Nylon', 'ASA'], answer: 1, why: 'Nagyon szívós és kopásálló. Nedvszívó, ezért nyomtatás előtt szárítani kell.' },
      { k: 'single', q: 'Milyen anyagpárt válassz egymáson mozgó felületekhez?', opts: ['Két azonos fémet', 'Két különböző anyagot, például műanyagot és fémet', 'Mindegy'], answer: 1, why: 'Két azonos fém összehegedhet. A lágyabb elem legyen a cserélhető.' },
      { k: 'single', q: 'Mi a jó szempont prototípusnál?', opts: ['A legerősebb anyag', 'A leggyorsabban elkészíthető', 'A legolcsóbb'], answer: 1, why: 'A tervezési hibát előbb találd meg; anyagot utána is lehet váltani.' },
    ],
    note: {
      summary: ['Nem a legjobb, hanem az elég jó anyagot keresd.', 'PLA olcsó de 60 fok fölött lágyul; PETG a jó alapértelmezés.', 'Nylon fogaskerékhez, alumínium merevséghez, acél tengelyhez.', 'Három kérdés: mekkora erő, milyen hőmérséklet, milyen gyártás.', 'PLA motor mellé nem való — ez a leggyakoribb kezdő hiba.', 'Egymáson mozgó felületekhez különböző anyagpár.', 'Prototípushoz a leggyorsabban elkészíthetőt válaszd.'],
      terms: [{ term: 'PETG', def: 'Szívós, 80 fokig hőálló, jól nyomtatható műanyag.' }, { term: 'üvegesedési hőmérséklet', def: 'Az a hőmérséklet, ahol a műanyag lágyulni kezd.' }, { term: 'összehegedés', def: 'Két azonos fém felület összetapadása súrlódás hatására.' }],
    },
  },
  {
    day: 25,
    title: 'Nyomtatási orientáció',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Ugyanaz a modell, más tájolással kinyomtatva **más alkatrész**: más szilárdságú, más felületű, más időben és más támaszigénnyel készül.' },
      { k: 'callout', tone: 'key', md: 'A legfontosabb: a nyomtatott darab **rétegek közt a leggyengébb**. A rétegtapadás jellemzően a rétegen belüli szilárdság **fele**. Tájold úgy, hogy a terhelés a rétegek **síkjában** hasson, ne válassza szét őket.' },
      { k: 'text', md: 'Példa: egy L alakú konzol, amit lefelé terhelsz.\n\n- **Laposan fektetve** — a rétegek vízszintesek, a terhelés szétválasztja őket. Eltörik.\n- **Élére állítva** — a rétegek függőlegesek, a terhelés a síkjukban hat. Többszörös teherbírás.' },
      { k: 'text', md: 'Amit a tájolás még befolyásol:\n\n- **Furatok** — a függőleges tengelyű furat kör marad; az oldalirányú elliptikussá és szűkebbé válik\n- **Felületminőség** — a felső felület sima, a ferde felületen lépcsők látszanak\n- **Nyomtatási idő** — alacsonyabb darab kevesebb rétegből áll, tehát gyorsabb\n- **Támaszigény** — minden 45 foknál meredekebb túlnyúlás támaszt kér' },
      { k: 'callout', tone: 'warn', md: 'A **tapadófelület** is számít. A kis talpfelületű, magas darab leválhat az asztalról nyomtatás közben. Ilyenkor vagy fektesd el, vagy adj hozzá peremet (brim), vagy tervezz rá egy letörhető talpat.' },
      { k: 'callout', tone: 'tip', md: 'Ha egy alkatrész minden tájolásban rossz valamiben, **vágd ketté**, és ragaszd vagy csavarozd össze. Két egyszerű darab gyakran jobb, mint egy bonyolult, tele támasszal — és az illesztés helyét te választod meg.' },
    ],
    quiz: [
      { k: 'single', q: 'Hol a leggyengébb egy nyomtatott darab?', opts: ['A közepén', 'A rétegek között', 'A felületén'], answer: 1, why: 'A rétegtapadás jellemzően fele a rétegen belüli szilárdságnak.' },
      { k: 'single', q: 'Hogyan tájolj egy lefelé terhelt L konzolt?', opts: ['Laposan fektetve', 'Élére állítva, hogy a terhelés a rétegek síkjában hasson', 'Fejjel lefelé'], answer: 1, why: 'Laposan a terhelés szétválasztja a rétegeket, és a darab eltörik.' },
      { k: 'single', q: 'Mi történik egy oldalirányú furattal?', opts: ['Kör marad', 'Elliptikussá és szűkebbé válik', 'Eltűnik'], answer: 1, why: 'A függőleges tengelyű furat marad kör. Oldalirányban a rétegezés torzítja.' },
      { k: 'single', q: 'Mikor kell támasz?', opts: ['Mindig', '45 foknál meredekebb túlnyúlásnál', 'Soha'], answer: 1, why: 'Ez a szokásos határ; alatta a réteg még megtámaszkodik az előzőn.' },
      { k: 'single', q: 'Mit tegyél, ha egy darab minden tájolásban rossz valamiben?', opts: ['Vágd ketté és illeszd össze', 'Nyomtasd ki mégis', 'Növeld a méretét'], answer: 0, why: 'Két egyszerű darab gyakran jobb, mint egy bonyolult, tele támasszal.' },
    ],
    note: {
      summary: ['A tájolás megváltoztatja a szilárdságot, a felületet, az időt és a támaszigényt.', 'A darab a rétegek közt a leggyengébb: a terhelés a rétegek síkjában hasson.', 'Élére állított konzol többszörösét bírja a laposan fektetettnek.', 'Függőleges furat kör marad, oldalirányú elliptikus lesz.', '45 foknál meredekebb túlnyúlás támaszt kér.', 'Kis talpfelületű magas darab leválhat: perem vagy fektetés kell.', 'Ha minden tájolás rossz, vágd ketté a darabot.'],
      terms: [{ term: 'rétegtapadás', def: 'A szomszédos nyomtatási rétegek közti kötés szilárdsága.' }, { term: 'túlnyúlás', def: 'Alátámasztás nélküli, ferde vagy vízszintes felület.' }, { term: 'perem (brim)', def: 'A darab köré nyomtatott lapos gyűrű a tapadásért.' }],
    },
  },
  {
    day: 26,
    title: 'Támaszok elkerülése',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A támasz plusz anyag, plusz idő, és eltávolítás után csúnya felületet hagy. A jó tervezés nagy része arról szól, hogy **ne legyen rá szükség**.' },
      { k: 'callout', tone: 'key', md: 'A **45 fokos szabály**: minden 45 foknál meredekebb túlnyúlás támaszt kér. Ennél laposabb lejtőnél minden réteg elég nagy részben megtámaszkodik az előzőn. Ez a szám a tervezés közben fejben tartandó határ.' },
      { k: 'text', md: 'Három alakzat, ami támasz nélkül nyomtatható:\n\n- **Letörés (chamfer) 45 fokban** — a vízszintes túlnyúlás helyett\n- **Csepp alakú furat** — a kör felső része helyett egy csúcs; vízszintes tengelyű furatnál ez a megoldás\n- **Hídképzés** — két megtámasztott pont közt a nyomtató át tud hidalni, körülbelül 20-30 mm-ig' },
      { k: 'callout', tone: 'warn', md: 'A **vízszintes tengelyű kör furat** teteje mindig problémás: a felső ív túlnyúlás. Vagy csepp alakúra tervezd (a tetején egy 45 fokos csúccsal), vagy fogadd el, hogy ott kicsit lelóg az anyag, és utólag átfúrod.' },
      { k: 'text', md: 'Ha mégis kell támasz, érdemes tudni:\n\n- A támasz a **ráeső felületet mindig elrontja**; tervezd oda, ahol nem látszik vagy nem számít\n- A **fa típusú (tree) támasz** kevesebb anyag és könnyebben törik le, mint a hagyományos\n- **Oldható támaszanyag** (PVA) kétfejes nyomtatón tökéletes felületet ad, de drága és lassú' },
      { k: 'callout', tone: 'tip', md: 'A legjobb teszt tervezés közben: forgasd el a modellt gondolatban úgy, ahogy nyomtatnád, és nézd meg alulról. Amit onnan látsz a levegőben lógni, az támaszt fog kérni — és rendszerint egy letöréssel vagy egy csepp alakkal megoldható.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a 45 fokos szabály?', opts: ['A réteg vastagsága', '45 foknál meredekebb túlnyúlás támaszt kér', 'A nyomtatási szög'], answer: 1, why: 'Ennél laposabb lejtőnél minden réteg elég nagy részben megtámaszkodik az előzőn.' },
      { k: 'single', q: 'Mivel helyettesíthető a vízszintes túlnyúlás?', opts: ['45 fokos letöréssel', 'Nagyobb falvastagsággal', 'Lassabb nyomtatással'], answer: 0, why: 'A letörés támasz nélkül nyomtatható, és erősebb is.' },
      { k: 'single', q: 'Hogyan tervezz vízszintes tengelyű furatot?', opts: ['Simán körre', 'Csepp alakúra, a tetején 45 fokos csúccsal', 'Négyzetesre'], answer: 1, why: 'A kör felső íve túlnyúlás, ami lelóg. A csepp alak ezt kerüli ki.' },
      { k: 'single', q: 'Meddig tud a nyomtató áthidalni két pont közt?', opts: ['2-3 mm', 'Körülbelül 20-30 mm', 'Korlátlanul'], answer: 1, why: 'A hídképzés jól működik ebben a tartományban, ha a hűtés megfelelő.' },
      { k: 'single', q: 'Hova tervezd a támaszt, ha mégis kell?', opts: ['A látható felületre', 'Oda, ahol nem látszik vagy nem számít', 'Mindegy'], answer: 1, why: 'A támasz a ráeső felületet mindig elrontja.' },
    ],
    note: {
      summary: ['A támasz anyagot, időt és felületminőséget visz el.', '45 fokos szabály: ennél meredekebb túlnyúlás támaszt kér.', 'Letörés 45 fokban a vízszintes túlnyúlás helyett.', 'Vízszintes tengelyű furat legyen csepp alakú.', 'Hídképzés 20-30 mm-ig működik.', 'Ha kell támasz, tedd nem látható felületre; a fa típusú a legkíméletesebb.', 'Teszt: nézd meg a modellt alulról a nyomtatási helyzetben.'],
      terms: [{ term: '45 fokos szabály', def: 'A támasz nélkül nyomtatható legmeredekebb túlnyúlás.' }, { term: 'csepp alakú furat', def: 'Felül csúcsban végződő furat, ami támasz nélkül nyomtatható.' }, { term: 'hídképzés', def: 'Két megtámasztott pont közti áthidalás támasz nélkül.' }],
    },
  },
];
