import type { Day } from '../../types';

/** CAD trek, 13–19. nap. */
export const cadHuD: Day[] = [
  {
    day: 13,
    title: 'Paraméteres tervezés',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A paraméteres tervezés lényege: a modell **számokon és összefüggéseken** áll, nem rögzített geometrián. Ha egy számot megváltoztatsz, az egész modell újraépül.' },
      { k: 'callout', tone: 'key', md: 'A gyakorlati eszköz a **változólista** (Fusion: Modify → Change Parameters; FreeCAD: Spreadsheet). Elnevezett értékek, amikre a vázlatméretek hivatkoznak.' },
      { k: 'code', lang: 'js', src: '// Tipikus paraméterkészlet egy motortartóhoz\nfalvastagsag   = 3        // mm\nmotor_atmero   = 37\nfurat_osztokor = 31\ncsavar_atmero  = 3.2      // M3 átmenő furat\nhezag          = 0.2      // nyomtatási tűrés\n\n// Származtatott értékek:\nbefogo_atmero  = motor_atmero + 2*hezag\nkulso_atmero   = befogo_atmero + 2*falvastagsag', explain: 'A származtatott értékek a lényeg. Ha a motor mérete változik, csak egy számot írsz át, és a külső átmérő, a fal, a furatok mind követik.' },
      { k: 'text', md: 'Mit tegyél paraméterbe?\n\n- Minden, ami **többször előfordul** (falvastagság, hézag)\n- Minden, ami **kívülről adott** (motor átmérője, csavar mérete)\n- Minden, amit **valószínűleg állítani fogsz** (nyomtatási tűrés)\n\nAmi csak egyszer szerepel és sosem változik, maradhat szám.' },
      { k: 'callout', tone: 'tip', md: 'Adj a paramétereknek **beszédes nevet és megjegyzést**. Fél év múlva a `d12 = 3.2` semmit nem mond, a `csavar_atmero = 3.2  // M3 átmenő` viszont azonnal érthető.' },
      { k: 'callout', tone: 'warn', md: 'Ne vidd túlzásba. Ha minden egyes méret paraméter, a lista áttekinthetetlen lesz, és nem találod meg azt az egyet, amit állítani akartál. Jó arány: **10–20 paraméter** egy közepes alkatrészhez.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a paraméteres tervezés lényege?', opts: ['Gyorsabb rajzolás', 'A modell számokon és összefüggéseken áll, és egy szám átírására újraépül', 'Automatikus méretezés'], answer: 1, why: 'A geometria a paraméterekből következik, nem fordítva. Ettől lesz a modell változtatható.' },
      { k: 'single', q: 'Mi a származtatott paraméter?', opts: ['Kézzel beírt szám', 'Más paraméterekből képlettel számolt érték', 'A fájl mérete'], answer: 1, why: 'Például `kulso = befogo + 2*falvastagsag`. Így egy változás automatikusan végigfut a modellen.' },
      { k: 'single', q: 'Mit érdemes paraméterbe tenni?', opts: ['Minden egyes méretet', 'Ami többször előfordul, kívülről adott, vagy valószínűleg állítani fogod', 'Semmit'], answer: 1, why: 'Ami egyszer szerepel és sosem változik, az maradhat szám. Túl sok paraméter átláthatatlan.' },
      { k: 'single', q: 'Hány paraméter jó arány egy közepes alkatrészhez?', opts: ['2-3', '10-20', '100 fölött'], answer: 1, why: 'Ennyi még áttekinthető, és lefedi a lényeges változtatható méreteket.' },
      { k: 'single', q: 'Miért fontos a beszédes paraméternév?', opts: ['Szebb', 'Mert fél év múlva a `d12 = 3.2` semmit nem mond', 'Gyorsabb a számítás'], answer: 1, why: 'A név és a megjegyzés az egyetlen dokumentáció, ami a modellben marad.' },
    ],
    note: {
      summary: ['A paraméteres modell számokon és összefüggéseken áll.', 'A változólistában elnevezett értékek, amikre a vázlatok hivatkoznak.', 'Származtatott paraméter: más paraméterekből képlettel.', 'Paraméterbe való: ami ismétlődik, kívülről adott, vagy változni fog.', 'Beszédes név és megjegyzés kötelező.', 'Jó arány: 10–20 paraméter alkatrészenként.'],
      terms: [{ term: 'paraméter', def: 'Elnevezett érték, amire a modell hivatkozik.' }, { term: 'származtatott érték', def: 'Más paraméterekből képlettel számolt méret.' }, { term: 'változólista', def: 'A modell összes paraméterét tartalmazó táblázat.' }],
    },
  },
  {
    day: 14,
    title: 'Tervezési szándék',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **tervezési szándék** (design intent) azt jelenti: a modell ne csak a mostani alakot írja le, hanem azt is, **mi miből következik**. Ettől marad használható, amikor változtatni kell.' },
      { k: 'callout', tone: 'key', md: 'A kérdés minden kényszernél ugyanaz: *ha ez a méret megváltozik, mi kövesse?* Egy lemez furatának a **széltől** mért távolsága mást jelent, mint a **középvonaltól** mért — és csak az egyik marad helyes, ha a lemez szélesebb lesz.' },
      { k: 'text', md: 'Három szabály, ami a legtöbbet segít:\n\n1. **Szimmetriát szimmetriával** fejezz ki, ne két egyforma mérettel. Ha középvonalra tükrözöl, a szimmetria akkor is megmarad, ha a méret változik.\n2. **Egyenlőséget egyenlőséggel**: négy egyforma furat esetén egy méret és három egyenlőség-kényszer, nem négy méret.\n3. **A funkcióhoz kösd**, ne a kényelemhez: a csavarfurat a peremhez képest van helyén, nem a vázlat origójához képest.' },
      { k: 'callout', tone: 'warn', md: 'A **túlkényszerezett** vázlat hibát ad: ellentmondó méretek. Az **alulkényszerezett** viszont veszélyesebb: szemre jó, de a következő változtatáskor elcsúszik valami, és nem érted, miért. A teljesen meghatározott vázlat színe a legtöbb programban fekete vagy zöld — csak ilyet hagyj magad után.' },
      { k: 'text', md: 'A fakezelőben is számít a sorrend. Ha egy lekerekítést a furat **elé** teszel, és a furat később a lekerekített élre esik, a modell elromlik. A szabály: **előbb a nagy forma, aztán a részletek** — lekerekítés és letörés a végére.' },
      { k: 'callout', tone: 'tip', md: 'Próbáld ki: írj át egy fő méretet a duplájára, és nézd meg, mi történik. Ha a modell szépen követ, jó a szándék. Ha szétesik, most tudod, hol kell kényszert javítani — és nem fél év múlva, határidő előtt.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent a tervezési szándék?', opts: ['A modell szép legyen', 'A modell leírja, mi miből következik, nem csak a jelenlegi alakot', 'Gyors modellezés'], answer: 1, why: 'Ettől marad használható a modell, amikor változtatni kell.' },
      { k: 'single', q: 'Hogyan fejezz ki szimmetriát?', opts: ['Két egyforma mérettel', 'Szimmetria-kényszerrel a középvonalra', 'Nem kell kifejezni'], answer: 1, why: 'Két egyforma méret csak most egyezik. A szimmetria-kényszer változás után is tart.' },
      { k: 'single', q: 'Miért veszélyesebb az alulkényszerezett vázlat a túlkényszerezettnél?', opts: ['Mert hibát ad', 'Mert szemre jó, de a következő változtatáskor észrevétlenül elcsúszik', 'Mert lassabb'], answer: 1, why: 'A túlkényszerezés azonnal hibát jelez. Az alulkényszerezés csendben romlik el később.' },
      { k: 'single', q: 'Hova tedd a lekerekítéseket a fában?', opts: ['Az elejére', 'A végére, a nagy forma után', 'Mindegy'], answer: 1, why: 'Ha egy későbbi furat a lekerekített élre esik, a modell elromlik. Előbb forma, aztán részletek.' },
      { k: 'single', q: 'Hogyan ellenőrzöd a tervezési szándékot?', opts: ['Megnézed a renderképet', 'Átírsz egy fő méretet a duplájára, és nézed, követ-e a modell', 'Megméred a fájlméretet'], answer: 1, why: 'Ha szétesik, most tudod meg, hol a hiba — nem fél év múlva, határidő előtt.' },
    ],
    note: {
      summary: ['A tervezési szándék azt írja le, mi miből következik.', 'Kérdés minden kényszernél: ha ez változik, mi kövesse?', 'Szimmetriát szimmetria-kényszerrel, egyenlőséget egyenlőség-kényszerrel.', 'A funkcióhoz kösd a méretet, ne a kényelemhez.', 'Alulkényszerezett vázlat veszélyesebb a túlkényszerezettnél.', 'Előbb a nagy forma, a lekerekítés a végére.', 'Ellenőrzés: írj át egy fő méretet a duplájára.'],
      terms: [{ term: 'tervezési szándék', def: 'A modellbe épített összefüggések, amik a változtatást túlélik.' }, { term: 'alulkényszerezett', def: 'Vázlat, aminek még van szabad mozgása.' }, { term: 'teljesen meghatározott', def: 'Vázlat, aminek minden eleme rögzített.' }],
    },
  },
  {
    day: 15,
    title: 'Szerelvények',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **szerelvény** (assembly) több alkatrészt fog össze egy egységbe. Nem egyetlen nagy modellt építesz: külön alkatrészeket készítesz, és megmondod, hogyan kapcsolódnak.' },
      { k: 'callout', tone: 'key', md: 'Az alapszabály: **egy alkatrész = egy fájl** (vagy egy komponens). Ha egy csavart tízszer használsz, egyetlen definíció van, és tíz példány. Ha javítod a definíciót, mind a tíz követi.' },
      { k: 'text', md: 'A szerelvény fája tükrözze a **valódi szerelési sorrendet**:\n\n```\nRobot\n├── Alváz\n│   ├── Alaplemez\n│   └── Oldalfal ×2\n├── Hajtás\n│   ├── Motor ×4\n│   └── Motortartó ×4\n└── Felépítmény\n```\n\nEz nem esztétika: aki később összerakja, ebből a fából dolgozik.' },
      { k: 'text', md: 'Az **alrészegység** (sub-assembly) több alkatrészt fog egybe, és egyként mozgatható. Egy négymotoros hajtás alrészegységként egyszer beáll, és utána egy mozdulattal áthelyezhető.' },
      { k: 'callout', tone: 'warn', md: 'A **körkörös hivatkozás** a szerelvények rákfenéje: az A alkatrész a B méretére hivatkozik, a B pedig az A-éra. Az első változtatásnál a program vagy végtelen ciklusba kerül, vagy megtagadja az újraépítést. Hivatkozz inkább egy közös **vázgeometriára** (skeleton), amit mindkettő használ.' },
      { k: 'callout', tone: 'tip', md: 'Nagy szerelvénynél kapcsold ki a nem szükséges részek megjelenítését, vagy használj egyszerűsített ábrázolást. Egy ötszáz alkatrészes modellt teljes részletességgel forgatni még erős gépen is lassú.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az alapszabály az ismétlődő alkatrészekre?', opts: ['Minden példány külön fájl', 'Egy definíció, több példány — a javítás mindet követi', 'Másold be újra'], answer: 1, why: 'Egy csavardefiníció és tíz példány. Javításkor nem kell tíz helyen átírni.' },
      { k: 'single', q: 'Mit tükrözzön a szerelvény fája?', opts: ['Az alkatrészek méretét', 'A valódi szerelési sorrendet', 'Az ábécé sorrendet'], answer: 1, why: 'Aki később összerakja a gépet, ebből a fából dolgozik.' },
      { k: 'single', q: 'Mi az alrészegység haszna?', opts: ['Kisebb fájl', 'Több alkatrész egyként mozgatható és újrahasználható', 'Gyorsabb render'], answer: 1, why: 'Egy négymotoros hajtás egyszer beáll, és utána egyben kezelhető.' },
      { k: 'single', q: 'Mi a körkörös hivatkozás?', opts: ['Két alkatrész egymás méretére hivatkozik', 'Kör alakú alkatrész', 'Ismétlődő minta'], answer: 0, why: 'Az első változtatásnál a program vagy végtelen ciklusba kerül, vagy nem épít újra.' },
      { k: 'single', q: 'Mi a körkörös hivatkozás megoldása?', opts: ['Törölni az egyik alkatrészt', 'Közös vázgeometria (skeleton), amire mindkettő hivatkozik', 'Nem hivatkozni semmire'], answer: 1, why: 'A váz egyirányú függést ad: mindkét alkatrész belőle következik, egymásból nem.' },
    ],
    note: {
      summary: ['A szerelvény külön alkatrészeket kapcsol össze.', 'Egy alkatrész = egy definíció, több példány.', 'A fa tükrözze a valódi szerelési sorrendet.', 'Az alrészegység több alkatrészt fog egybe, egyként mozgathatóan.', 'Körkörös hivatkozás helyett közös vázgeometria.', 'Nagy szerelvénynél egyszerűsített ábrázolás.'],
      terms: [{ term: 'szerelvény', def: 'Alkatrészek kapcsolt együttese.' }, { term: 'alrészegység', def: 'Önálló egységként kezelt alszerelvény.' }, { term: 'vázgeometria (skeleton)', def: 'Közös referenciageometria, amire az alkatrészek hivatkoznak.' }],
    },
  },
  {
    day: 16,
    title: 'Illesztések és kényszerek szerelvényben',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A szerelvényben az alkatrészeket **illesztésekkel** (joint, mate) kötöd össze. Ez megmondja, mi mihez képest hol van, és **mi mozoghat**.' },
      { k: 'callout', tone: 'key', md: 'Egy szabad test hat szabadsági fokú: három eltolás és három forgás. Minden kényszer elvesz ebből. Az illesztés pontosan annyi fokot hagyjon meg, **amennyit a valóság is enged**.' },
      { k: 'text', md: 'A leggyakoribb illesztéstípusok:\n\n- **Rögzített (rigid)** — nulla szabadsági fok. Csavarozott lemez.\n- **Forgó (revolute)** — egy forgás. Csapágy, zsanér.\n- **Csúszó (slider)** — egy eltolás. Lineáris vezeték.\n- **Hengeres (cylindrical)** — forgás és eltolás ugyanazon a tengelyen. Csap a furatban.\n- **Gömbcsukló (ball)** — három forgás.' },
      { k: 'callout', tone: 'warn', md: 'A **túlkényszerezés** itt is hiba: ha ugyanazt a mozgást két illesztés is korlátozza, az egyik felesleges, és az első méretváltozásnál ütközni fognak. A szabály: minden szabadsági fokot **pontosan egyszer** vegyél el.' },
      { k: 'text', md: 'Az illesztéseket **mozgással ellenőrizd**, ne szemre. Fogd meg az alkatrészt és húzd: ha olyan irányba mozog, ahova a valóságban nem tudna, hiányzik egy kényszer. Ha nem mozog oda, ahova kellene, egy kényszer túl szigorú.' },
      { k: 'callout', tone: 'tip', md: 'Az **ütközésvizsgálat** (interference check) megmutatja, hol fednek át az alkatrészek. Futtasd le minden szerelvényen, mielőtt gyártásba adnád — egy 0,2 mm-es átfedés a képernyőn láthatatlan, a valóságban viszont nem megy össze a gép.' },
    ],
    quiz: [
      { k: 'single', q: 'Hány szabadsági foka van egy szabad testnek?', opts: ['3', '6', '12'], answer: 1, why: 'Három eltolás és három forgás. Minden kényszer elvesz ebből.' },
      { k: 'single', q: 'Melyik illesztés enged egy forgást?', opts: ['Rögzített', 'Forgó (revolute)', 'Csúszó'], answer: 1, why: 'Csapágy, zsanér, kerék tengelye — ezek mind egyetlen forgást engednek.' },
      { k: 'single', q: 'Mit enged a hengeres illesztés?', opts: ['Csak forgást', 'Forgást és eltolást ugyanazon a tengelyen', 'Csak eltolást'], answer: 1, why: 'Egy csap egy furatban: forog is és csúszik is a tengelye mentén.' },
      { k: 'single', q: 'Mi a baj a túlkényszerezéssel szerelvényben?', opts: ['Lassú', 'Két illesztés ugyanazt korlátozza, és az első változásnál ütközni fognak', 'Nem látszik a modell'], answer: 1, why: 'Minden szabadsági fokot pontosan egyszer vegyél el.' },
      { k: 'single', q: 'Hogyan ellenőrzöd az illesztéseket?', opts: ['Szemre', 'Megfogod és húzod: mozog-e oda, ahova a valóságban is tudna', 'Megméred a fájlméretet'], answer: 1, why: 'A mozgatás azonnal megmutatja a hiányzó vagy felesleges kényszert.' },
    ],
    note: {
      summary: ['Az illesztés megmondja, mi hol van és mi mozoghat.', 'Szabad test: hat szabadsági fok, három eltolás és három forgás.', 'Típusok: rögzített, forgó, csúszó, hengeres, gömbcsukló.', 'Minden szabadsági fokot pontosan egyszer vegyél el.', 'Az illesztéseket mozgatással ellenőrizd, ne szemre.', 'Gyártás előtt mindig futtass ütközésvizsgálatot.'],
      terms: [{ term: 'illesztés (joint)', def: 'Két alkatrész közti kapcsolat, ami szabadsági fokokat vesz el.' }, { term: 'hengeres illesztés', def: 'Egy tengely menti forgást és eltolást engedő kapcsolat.' }, { term: 'ütközésvizsgálat', def: 'Alkatrészek átfedésének ellenőrzése a szerelvényben.' }],
    },
  },
  {
    day: 17,
    title: 'Tűrés és illeszkedés',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Semmit nem lehet pontosan legyártani. A **tűrés** azt mondja meg, mekkora eltérés megengedett — és ettől lesz a rajzból gyártható alkatrész.' },
      { k: 'callout', tone: 'key', md: 'Három illeszkedési fajta:\n\n- **Laza (clearance)** — a csap mindig kisebb a furatnál. Szabadon mozog.\n- **Átmeneti (transition)** — a mérettől függően lehet szoros vagy laza. Pontos helyzet, kézzel szerelhető.\n- **Szoros (interference)** — a csap mindig nagyobb. Préselni vagy melegíteni kell.' },
      { k: 'code', lang: 'js', src: '// Tipikus hézagok 3D nyomtatáshoz (FDM, 0,4 mm fúvóka)\nlaza_mozgo    = 0.40   // csukló, forgó rész\nlaza_szereles = 0.25   // kézzel összedugható\natmeneti      = 0.15   // szoros, de még összenyomható\nszoros        = 0.00   // préselt, kalapáccsal\n\n// A furatot mindig a névleges + hézag mérettel rajzold:\nfurat = tengely_atmero + laza_szereles', explain: 'Ezek FDM nyomtatáshoz valók. Marásnál és esztergálásnál tizedakkora értékek is elegendők; SLA nyomtatásnál a fele.' },
      { k: 'callout', tone: 'warn', md: 'Az FDM nyomtató **befelé pontatlan**: a furat rendszerint kisebb lesz a tervezettnél, a csap pedig nagyobb. Ezért nem elég a hézagot szétosztani — rajzold a furatot nagyobbra, és hagyd a csapot névlegesen.' },
      { k: 'text', md: 'A rajzon a tűrés formái:\n\n- **Kétoldali**: `20 ±0,1` — 19,9 és 20,1 között\n- **Egyoldali**: `20 +0,2 / −0` — csak felfelé térhet el\n- **ISO illesztés**: `H7/g6` — szabványos jelölés, amiből a gyártó tudja a tűréshatárokat' },
      { k: 'callout', tone: 'tip', md: 'A szoros tűrés **pénzbe kerül**: minden tizedmilliméter szigorítás drágítja a gyártást. Csak oda írj szűk tűrést, ahol tényleg kell — jellemzően a csapágyhelyekre és az illeszkedő felületekre. Minden másra elég az általános tűrés.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a laza (clearance) illeszkedés?', opts: ['A csap mindig nagyobb a furatnál', 'A csap mindig kisebb a furatnál, szabadon mozog', 'Pontosan egyforma'], answer: 1, why: 'Forgó és csúszó kapcsolatokhoz kell, ahol a mozgásnak akadálytalannak kell lennie.' },
      { k: 'single', q: 'Mennyi hézag kell FDM nyomtatásnál kézzel összedugható illesztéshez?', opts: ['0,05 mm', '0,25 mm', '1,0 mm'], answer: 1, why: 'Mozgó résznél 0,4 mm, szereléshez 0,25 mm, szorosnál 0. Marásnál ezek tizedakkorák.' },
      { k: 'single', q: 'Miért kell az FDM furatot nagyobbra rajzolni?', opts: ['Mert szebb', 'Mert a nyomtató befelé pontatlan: a furat kisebb lesz a tervezettnél', 'Hogy kevesebb anyag fogyjon'], answer: 1, why: 'A furat szűkebb, a csap vastagabb lesz. Ezért nem elég a hézagot szétosztani.' },
      { k: 'single', q: 'Mit jelent a `20 +0,2 / −0` jelölés?', opts: ['19,8 és 20,2 között', '20 és 20,2 között: csak felfelé térhet el', 'Pontosan 20'], answer: 1, why: 'Ez egyoldali tűrés. Furatoknál gyakori: inkább legyen nagyobb, mint kisebb.' },
      { k: 'single', q: 'Hova írj szűk tűrést?', opts: ['Mindenhova', 'Csak oda, ahol tényleg kell: csapágyhely, illeszkedő felület', 'Sehova'], answer: 1, why: 'Minden tizedmilliméter szigorítás drágítja a gyártást. Máshol elég az általános tűrés.' },
    ],
    note: {
      summary: ['A tűrés a megengedett gyártási eltérés.', 'Illeszkedés: laza, átmeneti, szoros.', 'FDM hézagok: mozgó 0,4; szerelés 0,25; átmeneti 0,15; szoros 0.', 'Az FDM furat kisebb, a csap nagyobb lesz a tervezettnél.', 'Jelölés: kétoldali `±`, egyoldali, vagy ISO illesztés (H7/g6).', 'Szűk tűrést csak oda, ahol tényleg kell — drága.'],
      terms: [{ term: 'tűrés', def: 'A névleges mérettől megengedett eltérés.' }, { term: 'laza illeszkedés', def: 'A csap mindig kisebb a furatnál, szabad mozgást enged.' }, { term: 'ISO illesztés', def: 'Szabványos jelölés (pl. H7/g6) a tűréshatárokra.' }],
    },
  },
  {
    day: 18,
    title: 'Csavarok és kötőelemek',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A gépek nagy része csavarokkal áll össze. Néhány szabály ismerete megspórol egy halom újratervezést.' },
      { k: 'callout', tone: 'key', md: 'Egy metrikus csavarhoz **kétféle furat** tartozik:\n\n- **Átmenő furat** — a csavar szabadon átfér. M3-hoz 3,2–3,4 mm.\n- **Menetes furat** — a menet belevág. M3-hoz 2,5 mm a magfurat.\n\nA kettő összekeverése a leggyakoribb kezdő hiba: ha mindkét lemezbe menetes furatot teszel, a csavar nem tudja összehúzni őket.' },
      { k: 'text', md: 'A gyakori metrikus méretek robotépítéshez:\n\n| Méret | Átmenő | Magfurat | Kulcsnyílás |\n|---|---|---|---|\n| M2 | 2,2 | 1,6 | 1,5 mm imbusz |\n| M3 | 3,2 | 2,5 | 2,5 mm imbusz |\n| M4 | 4,3 | 3,3 | 3 mm imbusz |\n| M5 | 5,3 | 4,2 | 4 mm imbusz |' },
      { k: 'callout', tone: 'warn', md: 'A **menethossz** legalább a csavar átmérőjének **1,5-szerese** legyen acélban, és **2–2,5-szerese** alumíniumban vagy műanyagban. Rövidebb menet kiszakad. M3-hoz tehát műanyagban legalább 6–8 mm menetes mélység kell.' },
      { k: 'text', md: 'Műanyag alkatrészben ne vágj közvetlenül menetet, ha sokszor szét kell szedni — **menetes betétet** (heat-set insert) használj. Forrasztópákával beolvasztod, és utána száz szerelést is kibír. 3D nyomtatott robotoknál ez a szabvány megoldás.' },
      { k: 'callout', tone: 'tip', md: 'Hagyj **szerszámhozzáférést**. Egy tökéletesen megtervezett csavarkötés használhatatlan, ha nem fér oda az imbuszkulcs. A modellben rajzold be a szerszám hengerét is, és nézd meg, ütközik-e valamibe.' },
    ],
    quiz: [
      { k: 'single', q: 'Mekkora átmenő furat kell egy M3 csavarhoz?', opts: ['2,5 mm', '3,2 mm', '4 mm'], answer: 1, why: 'A magfurat 2,5 mm, de az átmenő furat 3,2 mm, hogy a csavar szabadon átférjen.' },
      { k: 'single', q: 'Mi történik, ha mindkét lemezbe menetes furatot teszel?', opts: ['Erősebb lesz', 'A csavar nem tudja összehúzni őket', 'Semmi'], answer: 1, why: 'Az összehúzáshoz az egyik oldalnak szabadon kell engednie a csavart. Ez a leggyakoribb kezdő hiba.' },
      { k: 'single', q: 'Milyen mély legyen a menet műanyagban M3-hoz?', opts: ['3 mm', 'Legalább 6-8 mm', '1 mm'], answer: 1, why: 'Műanyagban az átmérő 2–2,5-szerese kell. Rövidebb menet kiszakad.' },
      { k: 'single', q: 'Mi a menetes betét (heat-set insert) haszna?', opts: ['Szebb', 'Műanyagban is bír sok szét- és összeszerelést', 'Olcsóbb'], answer: 1, why: 'A nyomtatott menet néhány szerelés után kikopik. A beolvasztott fémbetét százat is kibír.' },
      { k: 'single', q: 'Mire kell figyelni a csavar elhelyezésénél a modellben?', opts: ['A színére', 'A szerszámhozzáférésre: férjen oda az imbuszkulcs', 'A tömegére'], answer: 1, why: 'Rajzold be a szerszám hengerét is, és nézd meg, ütközik-e valamibe.' },
    ],
    note: {
      summary: ['Átmenő furat: a csavar szabadon átfér (M3 → 3,2 mm).', 'Menetes furat: magfurat, amibe a menet vág (M3 → 2,5 mm).', 'Mindkét oldalon menet esetén a csavar nem tud összehúzni.', 'Menethossz: acélban 1,5×, műanyagban 2–2,5× az átmérő.', 'Műanyagban menetes betét, ha sokszor kell szétszedni.', 'Mindig hagyj szerszámhozzáférést; rajzold be a szerszámot.'],
      terms: [{ term: 'átmenő furat', def: 'Furat, amin a csavar szabadon átfér.' }, { term: 'magfurat', def: 'A menetvágáshoz szükséges, kisebb átmérőjű furat.' }, { term: 'menetes betét', def: 'Műanyagba olvasztott fémhüvely menettel.' }],
    },
  },
  {
    day: 19,
    title: 'Csapágyak beépítése',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **csapágy** a forgó tengelyt tartja, és közben minimális súrlódást ad. Rossz beépítéssel viszont szorul, kopog vagy tönkremegy — ezért érdemes a néhány szabályt betartani.' },
      { k: 'text', md: 'A leggyakoribb típus a **mélyhornyú golyóscsapágy**. Jelölése négy számjegy, például **608**: a kezdő 6 a sorozat, a 08 pedig a furat átmérője 5-tel szorozva, azaz 8 mm. A 608-as a gördeszkakerék csapágya — olcsó, mindenhol kapható.' },
      { k: 'callout', tone: 'key', md: 'A csapágyat a **belső gyűrűjén** a tengely tartja, a **külső gyűrűjén** a ház. A terhelés mindig a gyűrűkön keresztül menjen — **soha ne a golyókon át**, mert az azonnal tönkreteszi.' },
      { k: 'text', md: 'A szabványos beépítés:\n\n1. A ház furata **szoros** illeszkedés a külső gyűrűhöz\n2. A tengely **szoros** illeszkedés a belső gyűrűhöz\n3. Egy **váll** (perem) határolja a csapágyat tengelyirányban\n4. A váll magassága **kisebb** legyen a gyűrű vastagságánál, hogy ne érjen a tömítéshez' },
      { k: 'callout', tone: 'warn', md: 'Egy tengelyen **két csapágy** kell, de csak az **egyik** rögzítse tengelyirányban. Ha mindkettőt leszorítod, a hőtágulás vagy a gyártási pontatlanság megfeszíti a tengelyt, és a csapágyak gyorsan tönkremennek. Ez a „fix és szabad csapágyazás" elve.' },
      { k: 'text', md: 'Nyomtatott házhoz a szoros illeszkedés nehéz: ha túl szűk, nem megy be, ha túl bő, kilazul. Két jó megoldás: **nyomtatott bordák** a furatban, amik kissé benyomódnak, vagy **szorítóbilincses** ház, amit csavarral húzol rá.' },
      { k: 'callout', tone: 'tip', md: 'Rajzold be a csapágyat a modellbe egyszerűsített alakként (két gyűrű), és illeszd be a szerelvénybe. Így azonnal látod, elfér-e, van-e szerelési útja, és nem ütközik-e a váll a tömítéssel.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent a 608-as csapágyjelölés?', opts: ['608 mm átmérő', '8 mm furatátmérő, 6-os sorozat', '608 gramm'], answer: 1, why: 'Az utolsó két számjegy ötszöröse a furatátmérő. A 608 a gördeszkakerék csapágya.' },
      { k: 'single', q: 'Hogyan menjen a terhelés a csapágyon át?', opts: ['A golyókon keresztül', 'A gyűrűkön keresztül', 'A tömítésen keresztül'], answer: 1, why: 'A belső gyűrűt a tengely, a külsőt a ház tartja. A golyókra ható közvetlen terhelés azonnal tönkreteszi.' },
      { k: 'single', q: 'Miért nem szabad mindkét csapágyat tengelyirányban rögzíteni?', opts: ['Drágább', 'Mert a hőtágulás vagy a gyártási pontatlanság megfeszíti a tengelyt', 'Mert nehezebb szerelni'], answer: 1, why: 'Ez a fix és szabad csapágyazás elve: az egyik vezet, a másik elcsúszhat.' },
      { k: 'single', q: 'Milyen magas legyen a határoló váll?', opts: ['Magasabb a gyűrűnél', 'Kisebb a gyűrű vastagságánál, hogy ne érjen a tömítéshez', 'Mindegy'], answer: 1, why: 'Ha a váll a tömítésre fekszik, a csapágy szorul, és a tömítés tönkremegy.' },
      { k: 'single', q: 'Hogyan oldható meg a szoros illeszkedés nyomtatott házban?', opts: ['Ragasztóval', 'Nyomtatott bordákkal a furatban vagy szorítóbilincses házzal', 'Sehogy'], answer: 1, why: 'A bordák kissé benyomódnak, és kiegyenlítik a nyomtatási pontatlanságot.' },
    ],
    note: {
      summary: ['A mélyhornyú golyóscsapágy jelölése: 608 → 8 mm furat.', 'A terhelés a gyűrűkön át menjen, soha a golyókon.', 'Ház furata és tengely is szoros illeszkedés a gyűrűkhöz.', 'Egy váll határolja tengelyirányban, a gyűrűnél alacsonyabban.', 'Két csapágyból csak az egyiket rögzítsd tengelyirányban.', 'Nyomtatott házhoz bordák vagy szorítóbilincs.'],
      terms: [{ term: 'mélyhornyú golyóscsapágy', def: 'A legelterjedtebb csapágytípus radiális terhelésre.' }, { term: 'fix és szabad csapágyazás', def: 'Egy csapágy vezet tengelyirányban, a másik elcsúszhat.' }, { term: 'váll', def: 'Perem, ami a csapágyat tengelyirányban határolja.' }],
    },
  },
];
