import type { Day } from '../../types';

/** KÓD trek, 7–15. nap. */
export const codeHuB: Day[] = [
  {
    day: 7,
    title: 'Függvények',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **függvény** egy névvel ellátott kódrészlet, amit bárhonnan meghívhatsz. Két dolgot ad: nem kell kétszer leírnod ugyanazt, és nevet adhatsz egy gondolatnak.' },
      { k: 'code', lang: 'py', src: 'def koszon():\n    print("Szia, Rover!")\n\nkoszon()\nkoszon()', explain: 'A `def` definiál, a `koszon()` **hívja**. A definíció önmagában nem futtat semmit — csak megtanítja a programnak, mit jelent ez a név.' },
      { k: 'code', lang: 'py', src: 'def teruletet_szamol(a, b):\n    return a * b\n\nt = teruletet_szamol(3, 4)\nprint(t)     # 12', explain: 'Az `a` és a `b` **paraméter**. A `return` visszaadja az eredményt a hívónak.' },
      { k: 'callout', tone: 'warn', md: 'A `print` és a `return` nem ugyanaz. A `print` kiírja a képernyőre és elfelejti. A `return` visszaadja az értéket, hogy tovább számolhass vele. Ha egy függvény csak printel, nem tudod felhasználni az eredményét.' },
      { k: 'callout', tone: 'key', md: 'Jó szabály: egy függvény egy dolgot csináljon, és a neve mondja meg, mit. Ha a névbe „és" kerül, valószínűleg két függvény akar lenni.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `kettoszerese(n)` nevű függvényt, ami visszaadja a kapott szám kétszeresét. Hívd meg 21-gyel, és írasd ki az eredményt.',
      starter: 'def kettoszerese(n):\n    pass\n\n',
      checks: [{ k: 'output', contains: '42', label: 'A kettoszerese(21) 42-t ad' }],
      hints: ['A `pass` helyére írd: `return n * 2`.', 'Hívás: `print(kettoszerese(21))`.'],
    },
    quiz: [
      { k: 'single', q: 'Mi a különbség a `print` és a `return` között?', opts: ['Semmi, ugyanaz', 'A print kiír, a return visszaadja az értéket a hívónak', 'A return kiír, a print visszaad'], answer: 1, why: 'A `print` csak megjeleníti. A `return` értéket ad vissza, amit eltárolhatsz vagy tovább számolhatsz vele. Ez a leggyakoribb kezdő félreértés.' },
      { k: 'output', q: 'Mit ír ki?', code: 'def f(x):\n    return x + 1\n\nprint(f(f(1)))', lang: 'py', opts: ['2', '3', '1'], answer: 1, why: 'Belülről kifelé: f(1) = 2, majd f(2) = 3.' },
      { k: 'single', q: 'Mit csinál a `def osszead(a, b):` sor önmagában?', opts: ['Kiszámolja a+b-t', 'Csak definiálja a függvényt, nem futtatja', 'Hibát dob'], answer: 1, why: 'A definíció csak megtanítja a nevet. Semmi nem történik, amíg meg nem hívod: `osszead(2, 3)`.' },
      { k: 'single', q: 'Mit ad vissza egy függvény, amiben nincs `return`?', opts: ['0-t', 'None-t', 'Hibát dob'], answer: 1, why: 'Ha nincs `return`, a Python `None`-t ad vissza. Ezért kapsz `None`-t, ha véletlenül printelsz return helyett.' },
    ],
    note: {
      summary: ['A függvény névvel ellátott, újrahasználható kódrészlet.', 'A `def` definiál, a zárójeles hívás futtatja.', 'A paraméterek a bemenetek, a `return` adja vissza az eredményt.', 'A `print` megjelenít, a `return` értéket ad — nem cserélhetők fel.', 'Return nélküli függvény `None`-t ad vissza.', 'Egy függvény egy dolgot csináljon, és a neve mondja meg, mit.'],
      terms: [{ term: 'függvény', def: 'Névvel ellátott, újrahasználható kódrészlet.' }, { term: 'paraméter', def: 'A függvény bemeneti értéke, amit híváskor adsz át.' }, { term: 'return', def: 'Visszaadja az eredményt a hívónak, és befejezi a függvényt.' }],
    },
  },
  {
    day: 8,
    title: 'Paraméterek és visszatérési érték',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Ma a függvények bemenetét és kimenetét finomítjuk. Ez az a réteg, ahol a kód kényelmessé válik.' },
      { k: 'code', lang: 'py', src: 'def halad(cm, sebesseg=10):\n    print(f"{cm} cm, {sebesseg} cm/s")\n\nhalad(30)              # 30 cm, 10 cm/s\nhalad(30, 25)          # 30 cm, 25 cm/s\nhalad(cm=30, sebesseg=5)', explain: 'A `sebesseg=10` **alapérték**: ha nem adod meg, ez lesz. A `cm=30` forma névvel hivatkozik a paraméterre, így nem kell a sorrendre figyelni.' },
      { k: 'callout', tone: 'warn', md: 'Az alapértékkel rendelkező paraméterek mindig a lista végén állnak. A `def f(a=1, b)` szintaktikai hiba.' },
      { k: 'code', lang: 'py', src: 'def hatarok(lista):\n    return min(lista), max(lista)\n\nkicsi, nagy = hatarok([4, 9, 2])\nprint(kicsi, nagy)     # 2 9', explain: 'Több értéket is visszaadhatsz vesszővel. A hívó oldalon ugyanígy szét lehet szedni őket.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `atlag(szamok)` függvényt, ami visszaadja a lista átlagát. Üres listára adjon 0-t hiba helyett. Próbáld ki `[2, 4, 6]`-tal és `[]`-lel is.',
      starter: 'def atlag(szamok):\n    pass\n\nprint(atlag([2, 4, 6]))\nprint(atlag([]))\n',
      checks: [{ k: 'output', contains: '4', label: 'A [2,4,6] átlaga 4' }, { k: 'output', contains: '0', label: 'Az üres lista átlaga 0' }],
      hints: ['Előbb kezeld a különleges esetet: `if len(szamok) == 0: return 0`.', 'Utána: `return sum(szamok) / len(szamok)`.'],
    },
    quiz: [
      { k: 'single', q: 'Mit jelent a `def f(a, b=5):` fejlécben a `b=5`?', opts: ['A b mindig 5', 'A b alapértéke 5, ha nem adod meg', 'A b legfeljebb 5 lehet'], answer: 1, why: 'Ez alapérték. Ha a hívó megad másikat, az érvényesül; ha nem, marad az 5.' },
      { k: 'output', q: 'Mit ír ki?', code: 'def f(a, b=2):\n    return a * b\n\nprint(f(3), f(3, 4))', lang: 'py', opts: ['6 12', '6 6', '3 12'], answer: 0, why: 'Az első hívásnál b az alapértéket veszi fel (2), tehát 3*2=6. A másodikban 4-et kap, tehát 3*4=12.' },
      { k: 'single', q: 'Miért hasznos a nevesített hívás, pl. `halad(sebesseg=5, cm=30)`?', opts: ['Gyorsabb', 'Nem kell a sorrendre figyelni, és olvashatóbb', 'Kevesebb memóriát használ'], answer: 1, why: 'Nevesítve a hívás önmagát magyarázza, és a paraméterek sorrendje nem számít. Sok paraméternél ez nagy segítség.' },
      { k: 'single', q: 'Mit ad vissza a `return a, b`?', opts: ['Csak az a-t', 'Két értéket, amit szét lehet szedni', 'Hibát'], answer: 1, why: 'Több értéket is visszaadhatsz. A hívó oldalon `x, y = f()` formában szedheted szét őket.' },
    ],
    note: {
      summary: ['Az alapérték (`b=5`) akkor érvényesül, ha a hívó nem ad meg értéket.', 'Az alapértékes paraméterek a paraméterlista végére kerülnek.', 'Nevesített hívásnál (`f(b=2, a=1)`) a sorrend nem számít, és olvashatóbb.', 'Egy függvény több értéket is visszaadhat vesszővel elválasztva.', 'A különleges eseteket (üres lista, nulla) érdemes a függvény elején elkapni.'],
      terms: [{ term: 'alapérték', def: 'Paraméter előre megadott értéke, ami hiányzó argumentum esetén érvényesül.' }, { term: 'nevesített argumentum', def: 'Híváskor névvel megadott érték, ami független a sorrendtől.' }, { term: 'kicsomagolás', def: 'Több visszatérési érték szétosztása külön változókba.' }],
    },
  },
  {
    day: 9,
    title: 'Hatókör és mellékhatás',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **hatókör** azt mondja meg, hol látszik egy változó. A függvényen belül létrehozott változó a függvényen kívül nem létezik.' },
      { k: 'code', lang: 'py', src: 'def f():\n    belso = 10\n    print(belso)     # 10\n\nf()\nprint(belso)         # NameError!', explain: 'A `belso` a függvény **lokális** változója. A függvény lefutása után megszűnik.' },
      { k: 'callout', tone: 'key', md: 'Ez nem korlátozás, hanem védelem. Ha minden változó mindenhol látszana, egy hosszú programban soha nem tudnád, ki írta felül az értéket.' },
      { k: 'code', lang: 'py', src: 'def hozzaad(lista):\n    lista.append(99)     # MEGVÁLTOZTATJA a hívó listáját\n\nadatok = [1, 2]\nhozzaad(adatok)\nprint(adatok)            # [1, 2, 99]', explain: 'Listát és szótárat **referencia szerint** kapsz meg: amit a függvényben módosítasz rajta, azt kívül is látod. Ezt hívjuk mellékhatásnak.' },
      { k: 'callout', tone: 'tip', md: 'Ha egy függvény módosítja, amit kapott, írd bele a nevébe vagy a dokumentációjába. A meglepetésszerű mellékhatás a legnehezebben megtalálható hibafajta.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `duplazva(lista)` függvényt, ami **új** listát ad vissza minden elem kétszeresével, és az eredetit nem bántja. Ellenőrizd, hogy az eredeti tényleg változatlan.',
      starter: 'def duplazva(lista):\n    pass\n\neredeti = [1, 2, 3]\nprint(duplazva(eredeti))\nprint(eredeti)\n',
      checks: [{ k: 'output', contains: '[2, 4, 6]', label: 'Az új lista a duplája' }, { k: 'output', contains: '[1, 2, 3]', label: 'Az eredeti változatlan' }],
      hints: ['Hozz létre egy üres listát a függvényben, és abba gyűjts.', '`uj = []` majd `for x in lista: uj.append(x * 2)` majd `return uj`.'],
    },
    quiz: [
      { k: 'single', q: 'Mi történik, ha a függvényen kívül hivatkozol egy benne létrehozott változóra?', opts: ['Megkapod az értékét', 'NameError hibát kapsz', 'None-t kapsz'], answer: 1, why: 'A lokális változó a függvény lefutásával megszűnik. Kívülről nem létezik, ezért `NameError`.' },
      { k: 'output', q: 'Mit ír ki?', code: 'def f(lst):\n    lst.append(9)\n\na = [1]\nf(a)\nprint(a)', lang: 'py', opts: ['[1]', '[1, 9]', 'Hibát dob'], answer: 1, why: 'A listát referencia szerint kapja meg, így az `append` a hívó listáját módosítja. Ez mellékhatás.' },
      { k: 'single', q: 'Miért hasznos, hogy a lokális változók nem szivárognak ki?', opts: ['Gyorsabb a program', 'Nem írnak felül véletlenül más változókat', 'Kevesebbet kell gépelni'], answer: 1, why: 'Az elszigetelés miatt egy függvényt megérthetsz anélkül, hogy az egész programot fejben tartanád.' },
      { k: 'single', q: 'Mi a mellékhatás?', opts: ['Amikor a függvény hibát dob', 'Amikor a függvény megváltoztat valamit önmagán kívül', 'Amikor a függvény lassú'], answer: 1, why: 'Mellékhatás minden olyan változás, ami a visszatérési értéken túl történik: bemenet módosítása, fájlba írás, globális változó átírása.' },
    ],
    note: {
      summary: ['A függvényben létrehozott változó lokális: kívül nem létezik.', 'A lokalitás védelem, nem korlátozás — enélkül nem lehetne nagy programot írni.', 'A listát és szótárat referencia szerint kapja a függvény, így módosíthatja a hívóét.', 'Mellékhatás minden változás a visszatérési értéken kívül.', 'Ha egy függvény módosít, az derüljön ki a nevéből vagy a leírásából.'],
      terms: [{ term: 'hatókör', def: 'Az a tartomány, ahol egy változó neve létezik.' }, { term: 'lokális változó', def: 'Függvényen belül létrehozott változó, ami a függvénnyel együtt megszűnik.' }, { term: 'mellékhatás', def: 'A függvény által okozott változás a visszatérési értéken kívül.' }],
    },
  },
  {
    day: 10,
    title: 'Szövegek kezelése',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'A szöveg (`str`) karakterek sorozata, és sok mindenben hasonlít a listára: van hossza, indexelhető, szeletelhető.' },
      { k: 'code', lang: 'py', src: 's = "Rover Mk-II"\n\nprint(len(s))        # 11\nprint(s[0])          # R\nprint(s[0:5])        # Rover     — szeletelés\nprint(s.upper())     # ROVER MK-II\nprint(s.lower())' },
      { k: 'code', lang: 'py', src: 'sor = "  12, 8, 30  "\n\nprint(sor.strip())              # levágja a szóközöket\nprint(sor.strip().split(","))   # [\'12\', \' 8\', \' 30\']\nprint("-".join(["a", "b"]))     # a-b\nprint("30" in sor)              # True', explain: 'A `split` feldarabol, a `join` összefűz. Ez a kettő a szövegfeldolgozás gerince.' },
      { k: 'callout', tone: 'warn', md: 'A szöveg **megváltoztathatatlan**. Az `s.upper()` nem írja át az `s`-t, hanem új szöveget ad vissza. Ha kell az eredmény, el kell tenned: `s = s.upper()`.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Adott a `sor = "12,8,30,5"` szöveg. Alakítsd számok listájává, és írasd ki az összegüket.',
      starter: 'sor = "12,8,30,5"\n',
      checks: [{ k: 'output', contains: '55', label: 'Az összeg 55' }],
      hints: ['Darabolás: `reszek = sor.split(",")` — ezek még szövegek.', 'Számmá alakítás: `int(r)`.', 'Gyűjtsd ciklussal, vagy: `sum(int(r) for r in sor.split(","))`.'],
    },
    quiz: [
      { k: 'output', q: 'Mit ír ki?', code: 's = "robot"\nprint(s[1:4])', lang: 'py', opts: ['rob', 'obo', 'obot'], answer: 1, why: 'A szeletelés az 1-es indextől a 4-esig tart, de a 4-est már nem veszi bele: o, b, o.' },
      { k: 'single', q: 'Mit csinál a `"a,b,c".split(",")`?', opts: ['Összefűz egy listát', 'Három elemű listát ad: [a, b, c]', 'Kicseréli a vesszőket'], answer: 1, why: 'A `split` a megadott elválasztó mentén darabol, és listát ad vissza.' },
      { k: 'output', q: 'Mit ír ki?', code: 's = "abc"\ns.upper()\nprint(s)', lang: 'py', opts: ['ABC', 'abc', 'Hibát dob'], answer: 1, why: 'A szöveg megváltoztathatatlan: az `upper()` új szöveget ad vissza, amit itt senki nem tett el. Az `s` maradt az eredeti.' },
      { k: 'single', q: 'Mire jó a `strip()`?', opts: ['Levágja a szöveg elejéről és végéről a szóközöket', 'Kisbetűssé alakít', 'Darabol'], answer: 0, why: 'A `strip` a két végéről takarítja le a szóközöket és sortöréseket. Fájlból olvasott soroknál szinte mindig kell.' },
    ],
    note: {
      summary: ['A szöveg karakterek sorozata: van hossza, indexelhető, szeletelhető (`s[1:4]`).', 'A szeletelés felső határa nincs benne az eredményben.', 'A szöveg megváltoztathatatlan: a metódusok új szöveget adnak vissza.', '`split` darabol, `join` összefűz, `strip` levágja a széleket.', 'Az `in` operátor megmondja, hogy egy részlet szerepel-e a szövegben.'],
      terms: [{ term: 'szeletelés', def: 'Részszöveg kivétele indexhatárokkal, pl. `s[1:4]`.' }, { term: 'split', def: 'Szöveg feldarabolása listává egy elválasztó mentén.' }, { term: 'megváltoztathatatlan', def: 'Olyan érték, amit nem lehet helyben módosítani, csak újat készíteni belőle.' }],
    },
  },
  {
    day: 11,
    title: 'Formázás és beolvasás',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'Az **f-string** a legkényelmesebb módja annak, hogy értékeket illessz szövegbe. A `f` betű az idézőjel előtt, a kapcsos zárójelben pedig bármilyen kifejezés állhat.' },
      { k: 'code', lang: 'py', src: 'nev = "Rover"\nakku = 78.456\n\nprint(f"{nev}: {akku} %")\nprint(f"{nev}: {akku:.1f} %")     # egy tizedes\nprint(f"{akku:6.2f}")             # 6 karakter szélesen, 2 tizedes', explain: 'A kettőspont utáni rész a formátum. A `.1f` egy tizedesre kerekít — mérési adatoknál ez alap.' },
      { k: 'code', lang: 'py', src: 'szam = int("42")\ntizedes = float("3.14")\nszoveg = str(42)\n\nprint(szam + 1, tizedes * 2, szoveg + "!")', explain: 'A típusátalakítás explicit. Ha felhasználói bemenetet kapsz, az mindig szöveg — számolni csak átalakítás után tudsz vele.' },
      { k: 'callout', tone: 'warn', md: 'Az `int("alma")` hibát dob: `ValueError`. Valódi bemenetnél erre fel kell készülni — a 19. napon megtanuljuk, hogyan.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Adott `tav = 12.3456` és `nev = "Rover"`. Írasd ki ebben a formában: `Rover: 12.35 cm` — pontosan két tizedessel.',
      starter: 'tav = 12.3456\nnev = "Rover"\n',
      checks: [{ k: 'output', contains: '12.35', label: 'Két tizedesre kerekít' }, { k: 'output', contains: 'Rover', label: 'A név szerepel' }],
      hints: ['f-string: `print(f"...")`.', 'Két tizedes: `{tav:.2f}`.', 'Teljes megoldás: `print(f"{nev}: {tav:.2f} cm")`.'],
    },
    quiz: [
      { k: 'output', q: 'Mit ír ki?', code: 'x = 3.14159\nprint(f"{x:.2f}")', lang: 'py', opts: ['3.14159', '3.14', '3'], answer: 1, why: 'A `.2f` két tizedesre kerekítve formáz. Az eredeti érték nem változik, csak a megjelenítés.' },
      { k: 'single', q: 'Mit ad vissza az `int("7")`?', opts: ['A "7" szöveget', 'A 7 egész számot', 'Hibát'], answer: 1, why: 'Az `int` szövegből egész számot csinál, ha a szöveg valóban számot tartalmaz.' },
      { k: 'single', q: 'Mi történik az `int("alma")` hívásnál?', opts: ['0-t ad', 'ValueError hibát dob', 'None-t ad'], answer: 1, why: 'Nem alakítható számmá, ezért `ValueError`. Ezt kezelni kell, ha a bemenet a felhasználótól jön.' },
      { k: 'single', q: 'Mi kell az f-string elé?', opts: ['Egy f betű az idézőjel előtt', 'Egy % jel', 'Semmi'], answer: 0, why: 'Az `f` prefix kapcsolja be a kapcsos zárójelek kiértékelését. Nélküle a `{x}` szó szerint jelenik meg.' },
    ],
    note: {
      summary: ['Az f-string: `f"{valtozo}"` — értéket illeszt a szövegbe.', 'Formátum a kettőspont után: `{x:.2f}` két tizedes, `{x:6.2f}` hat karakter széles.', 'Típusátalakítás: `int()`, `float()`, `str()`.', 'A felhasználótól érkező adat mindig szöveg — számolni csak átalakítás után lehet vele.', 'A rossz bemenet `ValueError`-t okoz; ezt kezelni kell.'],
      terms: [{ term: 'f-string', def: 'Szövegforma, ami kiértékeli a kapcsos zárójelbe írt kifejezéseket.' }, { term: 'formátumspecifikáció', def: 'A kettőspont utáni rész, ami a megjelenítést szabja meg.' }, { term: 'ValueError', def: 'Hiba, ha egy érték nem alakítható a kért típusra.' }],
    },
  },
  {
    day: 12,
    title: 'Szövegfeldolgozás a gyakorlatban',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Egy valódi feladat: a robot naplót ír, te pedig ki akarod olvasni belőle a lényeget. Ez a művelet minden programozó mindennapja.' },
      { k: 'code', lang: 'py', src: 'naplo = """12:00 tav 30\n12:01 tav 18\n12:02 hiba motor\n12:03 tav 7"""\n\nfor sor in naplo.split("\\n"):\n    reszek = sor.split()\n    if reszek[1] == "tav":\n        print(reszek[0], int(reszek[2]))', explain: 'A `split()` paraméter nélkül tetszőleges mennyiségű szóköz mentén darabol. Sorokra a `split("\\n")` bont.' },
      { k: 'callout', tone: 'tip', md: 'Feldolgozás előtt mindig nézd meg egy sor tartalmát nyersen: `print(repr(sor))`. A `repr` megmutatja a rejtett szóközöket és sortöréseket is, amiktől a feldolgozásod elhasal.' },
      { k: 'code', lang: 'py', src: 'sor = "hőmérséklet: 23.5 C"\n\nif sor.startswith("hőmérséklet"):\n    ertek = float(sor.split(":")[1].strip().split()[0])\n    print(ertek + 1)', explain: 'Több lépés egymás után: vágás kettőspontnál, szóközök le, első darab, számmá alakítás. Bontsd külön sorokra, ha nehezen olvasható.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Adott a `naplo` szöveg. Számold meg, hány „tav" bejegyzés van benne, és írasd ki a számot.',
      starter: 'naplo = "12:00 tav 30\\n12:01 tav 18\\n12:02 hiba motor\\n12:03 tav 7"\n',
      checks: [{ k: 'output', contains: '3', label: 'Három tav bejegyzés van' }],
      hints: ['Sorokra bontás: `naplo.split("\\n")`.', 'Számláló: `db = 0`, majd `db = db + 1` a találatnál.', 'Ellenőrzés: `if " tav " in sor:` vagy `sor.split()[1] == "tav"`.'],
    },
    quiz: [
      { k: 'single', q: 'Mit csinál a `split()` paraméter nélkül?', opts: ['Karakterenként bont', 'Szóközök mentén bont, tetszőleges mennyiségűt kezelve', 'Hibát dob'], answer: 1, why: 'Paraméter nélkül a `split` a fehér karakterek (szóköz, tab) mentén darabol, és az egymás utáni szóközöket egynek veszi.' },
      { k: 'single', q: 'Mire jó a `repr(sor)` hibakereséskor?', opts: ['Gyorsabban fut', 'Megmutatja a rejtett szóközöket és sortöréseket', 'Számmá alakít'], answer: 1, why: 'A sima `print` nem mutatja a láthatatlan karaktereket. A `repr` igen, és általában ott van a hiba.' },
      { k: 'output', q: 'Mit ír ki?', code: 's = "a b  c"\nprint(len(s.split()))', lang: 'py', opts: ['3', '4', '6'], answer: 0, why: 'A `split()` az egymás utáni szóközöket egynek veszi, tehát három darabot ad: a, b, c.' },
      { k: 'single', q: 'Miért érdemes a bonyolult feldolgozást több sorra bontani?', opts: ['Gyorsabb lesz', 'Könnyebb megtalálni, melyik lépés romlott el', 'Kevesebb memória'], answer: 1, why: 'Egyetlen hosszú sornál nem tudod, melyik lépés hibázott. Több sorra bontva mindegyik közbenső eredményt ki tudod íratni.' },
    ],
    note: {
      summary: ['Sorokra bontás: `szoveg.split("\\n")`, szavakra: `sor.split()`.', 'A paraméter nélküli `split` az egymás utáni szóközöket egynek veszi.', 'A `repr()` megmutatja a rejtett karaktereket — hibakeresés első lépése.', 'A `startswith` és az `in` gyors szűrésre jó.', 'A több lépéses feldolgozást bontsd külön sorokra, hogy látszódjon, hol romlik el.'],
      terms: [{ term: 'parsing', def: 'Nyers szövegből strukturált adat kinyerése.' }, { term: 'repr', def: 'Az érték hű, idézőjeles ábrázolása, a rejtett karakterekkel együtt.' }, { term: 'startswith', def: 'Megmondja, hogy a szöveg egy adott részlettel kezdődik-e.' }],
    },
  },
  {
    day: 13,
    title: 'Fájlok írása és olvasása',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Eddig minden eltűnt a program végén. A **fájl** az első hely, ahol az adat túléli a futást.' },
      { k: 'code', lang: 'py', src: 'with open("naplo.txt", "w") as f:\n    f.write("12:00 tav 30\\n")\n    f.write("12:01 tav 18\\n")\n\nwith open("naplo.txt", "r") as f:\n    tartalom = f.read()\n\nprint(tartalom)', explain: 'A `with` gondoskodik róla, hogy a fájl bezáruljon, akkor is, ha közben hiba történik. Mindig így nyiss fájlt.' },
      { k: 'callout', tone: 'warn', md: 'A `"w"` mód **kitörli** a meglévő fájlt. Ha hozzá akarsz fűzni, `"a"` (append) kell. Ezt a különbséget mindenki megtanulja — általában egyszer, kellemetlenül.' },
      { k: 'code', lang: 'py', src: 'with open("naplo.txt") as f:\n    for sor in f:\n        print(sor.strip())', explain: 'A fájlt soronként is bejárhatod. Nagy fájlnál ez sokkal jobb, mint az egészet memóriába olvasni.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj ki három sort egy `meres.txt` fájlba (tetszőleges számokat), majd olvasd vissza, és írasd ki a sorok számát.',
      starter: '',
      checks: [{ k: 'output', contains: '3', label: 'Három sor van a fájlban' }],
      hints: ['Írás: `with open("meres.txt", "w") as f:` majd `f.write("12\\n")`.', 'Olvasás: `with open("meres.txt") as f: sorok = f.readlines()`.', 'Kiírás: `print(len(sorok))`.'],
    },
    quiz: [
      { k: 'single', q: 'Mit csinál a `"w"` mód egy létező fájllal?', opts: ['Hozzáfűz a végéhez', 'Kitörli a tartalmát', 'Hibát dob'], answer: 1, why: 'A `"w"` nulláról kezdi a fájlt. Hozzáfűzéshez `"a"` kell.' },
      { k: 'single', q: 'Miért a `with open(...)` formát használjuk?', opts: ['Gyorsabb', 'Garantáltan bezárja a fájlt, hiba esetén is', 'Kevesebbet kell gépelni'], answer: 1, why: 'A `with` blokk végén a fájl mindenképp bezárul. Enélkül egy kivétel nyitva hagyhatja, és az adat a pufferben ragadhat.' },
      { k: 'single', q: 'Mit ad a `f.read()`?', opts: ['A fájl teljes tartalmát egy szövegként', 'A sorok listáját', 'Az első sort'], answer: 0, why: 'A `read()` az egészet egy szövegbe olvassa. A sorok listáját a `readlines()` adja.' },
      { k: 'single', q: 'Miért jobb nagy fájlt soronként bejárni?', opts: ['Nem kell az egészet memóriába tölteni', 'Pontosabb', 'Nincs különbség'], answer: 0, why: 'A `for sor in f:` egyszerre csak egy sort tart a memóriában. Egy több gigabájtos naplónál ez a különbség a működés és az összeomlás között.' },
    ],
    note: {
      summary: ['A fájl az első hely, ahol az adat túléli a program futását.', 'Mindig `with open(...) as f:` — a blokk végén garantáltan bezárul.', 'Módok: `"r"` olvasás, `"w"` írás (töröl!), `"a"` hozzáfűzés.', '`read()` az egészet, `readlines()` a sorok listáját adja.', 'Nagy fájlt `for sor in f:` formában járj be, hogy ne töltsd memóriába az egészet.'],
      terms: [{ term: 'with blokk', def: 'Szerkezet, ami a blokk végén automatikusan lezárja az erőforrást.' }, { term: 'fájlmód', def: 'Az `open` második paramétere: olvasás, írás vagy hozzáfűzés.' }, { term: 'readlines', def: 'A fájl sorait listaként adja vissza.' }],
    },
  },
  {
    day: 14,
    title: 'JSON és strukturált adat',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A szöveges fájl jó a naplónak, de rossz a szerkezetnek. A **JSON** olyan szövegformátum, ami megőrzi a listát és a szótárat is.' },
      { k: 'code', lang: 'py', src: 'import json\n\nallapot = {"nev": "Rover", "akku": 78, "pozicio": [12, 4]}\n\nszoveg = json.dumps(allapot)     # szótár → szöveg\nvissza = json.loads(szoveg)      # szöveg → szótár\n\nprint(szoveg)\nprint(vissza["pozicio"][0])      # 12', explain: 'A `dumps` „dump string" — szöveggé alakít. A `loads` „load string" — vissza. A szerkezet megmarad.' },
      { k: 'code', lang: 'py', src: 'with open("allapot.json", "w") as f:\n    json.dump(allapot, f, indent=2)\n\nwith open("allapot.json") as f:\n    betoltve = json.load(f)', explain: 'Az `s` nélküli `dump`/`load` közvetlenül fájllal dolgozik. Az `indent=2` olvashatóvá teszi a fájlt.' },
      { k: 'callout', tone: 'key', md: 'A FORGE is pontosan így menti a haladásodat: egy JSON fájlba a gépeden. Amikor a Beállításokban exportálod a mentésedet, ez a fájl megy ki.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Készíts egy szótárat a robotodról, alakítsd JSON szöveggé, majd olvasd vissza, és írasd ki az egyik értékét a visszaolvasott adatból.',
      starter: 'import json\n\nrobot = {"nev": "Rover", "akku": 80}\n',
      checks: [{ k: 'output', contains: '80', label: 'A visszaolvasott akku érték megjelenik' }],
      hints: ['`szoveg = json.dumps(robot)`', '`vissza = json.loads(szoveg)`', '`print(vissza["akku"])`'],
    },
    quiz: [
      { k: 'single', q: 'Mit csinál a `json.dumps(d)`?', opts: ['Fájlba írja a szótárat', 'JSON-szöveggé alakítja a szótárat', 'Beolvas egy fájlt'], answer: 1, why: 'A `dumps` szöveggé alakít. A fájlba írás az `s` nélküli `dump`.' },
      { k: 'single', q: 'Mi a JSON előnye a sima szöveges fájllal szemben?', opts: ['Kisebb', 'Megőrzi a szerkezetet: listát, szótárat, típusokat', 'Gyorsabban olvasható'], answer: 1, why: 'A sima szövegből neked kell visszafejtened a szerkezetet. A JSON ezt elvégzi helyetted.' },
      { k: 'output', q: 'Mit ír ki?', code: 'import json\nd = json.loads(\'{"a": [1, 2]}\')\nprint(d["a"][1])', lang: 'py', opts: ['1', '2', '[1, 2]'], answer: 1, why: 'A `loads` visszaadja a szótárat a beágyazott listával együtt, így az `["a"][1]` a lista második eleme: 2.' },
      { k: 'single', q: 'Mi a különbség a `dump` és a `dumps` között?', opts: ['A dump fájlba ír, a dumps szöveget ad vissza', 'Semmi', 'A dumps gyorsabb'], answer: 0, why: 'Az `s` a „string" rövidítése. `dumps`/`loads` szöveggel, `dump`/`load` fájllal dolgozik.' },
    ],
    note: {
      summary: ['A JSON olyan szövegformátum, ami megőrzi a listát, szótárat és a típusokat.', '`json.dumps` szótárból szöveget, `json.loads` szövegből szótárat csinál.', 'Az `s` nélküli `json.dump`/`json.load` közvetlenül fájllal dolgozik.', 'Az `indent=2` olvashatóvá teszi a mentett fájlt.', 'A programok adatcseréjének ez a legelterjedtebb formátuma.'],
      terms: [{ term: 'JSON', def: 'Szöveges adatformátum, ami szerkezetet is képes leírni.' }, { term: 'szerializálás', def: 'Memóriabeli adat átalakítása tárolható vagy küldhető formára.' }, { term: 'dumps/loads', def: 'Szótár és JSON-szöveg közti oda-vissza alakítás.' }],
    },
  },
  {
    day: 15,
    title: 'Adatok mentése és visszatöltése',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Most összerakjuk az eddigieket: egy program, ami megjegyzi, mi történt, még akkor is, ha kikapcsolod.' },
      { k: 'code', lang: 'py', src: 'import json, os\n\nFAJL = "allapot.json"\n\ndef betolt():\n    if not os.path.exists(FAJL):\n        return {"futasok": 0}\n    with open(FAJL) as f:\n        return json.load(f)\n\ndef ment(adat):\n    with open(FAJL, "w") as f:\n        json.dump(adat, f, indent=2)', explain: 'A `betolt` a hiányzó fájlt nem hibának, hanem „még nincs mentés" esetnek tekinti. Ez az első futás.' },
      { k: 'code', lang: 'py', src: 'allapot = betolt()\nallapot["futasok"] = allapot["futasok"] + 1\nment(allapot)\n\nprint("Ez a", allapot["futasok"], ". futás")' },
      { k: 'callout', tone: 'key', md: 'Három szabály a mentéshez: (1) a hiányzó fájl ne legyen hiba, (2) a sérült fájl se dobja el az egész programot, (3) írás közben ne írd felül a régit, amíg az új el nem készült. A FORGE is ezt csinálja: ideiglenes fájlba ír, majd átnevezi.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `betolt()` függvényt, ami visszaadja a `{"futasok": 0}` szótárat, ha a fájl nem létezik. Hívd meg, növeld a számlálót, és írasd ki.',
      starter: 'import json, os\n\ndef betolt():\n    pass\n\n',
      checks: [{ k: 'output', contains: '1', label: 'Az első futás után a számláló 1' }],
      hints: ['`if not os.path.exists("a.json"): return {"futasok": 0}`', 'Növelés: `a["futasok"] += 1`.', 'Kiírás: `print(a["futasok"])`.'],
    },
    quiz: [
      { k: 'single', q: 'Miért ne legyen hiba a hiányzó mentésfájl?', opts: ['Mert lassú a hibakezelés', 'Mert az első futáskor természetes, hogy még nincs', 'Mert a Python nem támogatja'], answer: 1, why: 'Az első indításnál nincs mentés. Ha ez hibaként áll meg, a program soha nem tud elindulni.' },
      { k: 'single', q: 'Miért ideiglenes fájlba írunk, majd átnevezünk?', opts: ['Gyorsabb', 'Mert egy megszakadt írás nem csonkítja a régi mentést', 'Mert kisebb fájl lesz'], answer: 1, why: 'Ha írás közben elmegy az áram, a régi fájl sértetlen marad. Az átnevezés a fájlrendszerben oszthatatlan művelet.' },
      { k: 'single', q: 'Mit csinál az `os.path.exists("a.json")`?', opts: ['Létrehozza a fájlt', 'Megmondja, hogy létezik-e', 'Megnyitja'], answer: 1, why: 'Csak megvizsgálja, hogy van-e ilyen elérési út. Nem hoz létre és nem nyit meg semmit.' },
      { k: 'order', q: 'Milyen sorrendben fut egy biztonságos mentés?', items: ['Átnevezés a végleges névre', 'Ideiglenes fájlba írás', 'Adat előkészítése'], correct: [2, 1, 0], why: 'Előbb az adat, aztán a temp fájl, és csak a legvégén az átnevezés — így a régi mentés mindvégig ép marad.' },
    ],
    note: {
      summary: ['A mentés a betöltés és a kiírás párosából áll.', 'A hiányzó fájl nem hiba, hanem „első futás" — adj vissza alapértéket.', 'A sérült fájl se dobja el az egész programot.', 'Biztonságos írás: ideiglenes fájl, majd átnevezés.', 'Az `os.path.exists` csak vizsgál, nem hoz létre semmit.'],
      terms: [{ term: 'perzisztencia', def: 'Az adat megőrzése a program futásán túl.' }, { term: 'atomi írás', def: 'Írási minta, amiben a régi adat sértetlen marad, amíg az új el nem készült.' }, { term: 'alapállapot', def: 'Az az érték, amivel a program indul, ha még nincs mentés.' }],
    },
  },
];
