import type { Day } from '../../types';

/** KÓD trek, 16–23. nap. */
export const codeHuC: Day[] = [
  {
    day: 16,
    title: 'Osztályok és objektumok',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Eddig az adat és a rá vonatkozó műveletek külön éltek: volt egy szótárad, és voltak függvényeid, amik azt piszkálták. Az **osztály** ezt a kettőt fogja össze.' },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self, nev):\n        self.nev = nev\n        self.x = 0\n        self.akku = 100\n\n    def halad(self, cm):\n        self.x = self.x + cm\n        self.akku = self.akku - cm * 0.1\n\nr = Rover("Mk-I")\nr.halad(30)\nprint(r.nev, r.x, r.akku)', explain: 'Az `__init__` a születéskor fut le. A `self` maga az objektum — rajta keresztül éred el a saját adatait.' },
      { k: 'callout', tone: 'warn', md: 'A `self` minden metódus első paramétere, de híváskor **nem** adod meg: `r.halad(30)`, nem `r.halad(r, 30)`. A Python teszi oda helyetted.' },
      { k: 'text', md: 'Az **osztály** a terv, az **objektum** a belőle készült példány. Egy `Rover` osztályból akárhány rovert gyárthatsz, mindegyiknek saját `x`-e és akkuja lesz.' },
      { k: 'callout', tone: 'key', md: 'Akkor éri meg osztályt írni, ha egy adathalmaz és a rá vonatkozó műveletek mindig együtt járnak. Ha csak adatot tárolnál, a szótár is elég.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `Szamlalo` osztályt, aminek van `ertek` adata (0-ról indul) és egy `noveld()` metódusa. Hívd meg háromszor, és írasd ki az értéket.',
      starter: 'class Szamlalo:\n    pass\n\n',
      checks: [{ k: 'output', contains: '3', label: 'Három növelés után 3 az érték' }],
      hints: ['`def __init__(self): self.ertek = 0`', '`def noveld(self): self.ertek += 1`', '`sz = Szamlalo()` majd háromszor `sz.noveld()`, végül `print(sz.ertek)`.'],
    },
    quiz: [
      { k: 'single', q: 'Mikor fut le az `__init__`?', opts: ['Minden metódushíváskor', 'Az objektum létrehozásakor', 'A program végén'], answer: 1, why: 'Az `__init__` a konstruktor: pontosan egyszer fut, amikor a `Rover("Mk-I")` létrehozza a példányt.' },
      { k: 'single', q: 'Mit jelent a `self`?', opts: ['Az osztályt', 'Magát az objektumot, amin a metódust hívtad', 'Egy globális változót'], answer: 1, why: 'A `self` az a konkrét példány, amin a metódus fut. Rajta keresztül éred el annak a példánynak az adatait.' },
      { k: 'output', q: 'Mit ír ki?', code: 'class A:\n    def __init__(self):\n        self.n = 1\n\na = A()\nb = A()\nb.n = 9\nprint(a.n, b.n)', lang: 'py', opts: ['1 9', '9 9', '1 1'], answer: 0, why: 'Két külön példány, két külön `n`. Az egyik módosítása nem érinti a másikat — ez az objektumok lényege.' },
      { k: 'single', q: 'Mikor NEM éri meg osztályt írni?', opts: ['Ha csak adatot tárolnál műveletek nélkül', 'Ha sok adatod van', 'Soha, mindig osztályt kell'], answer: 0, why: 'Ha nincsenek hozzá tartozó műveletek, a szótár egyszerűbb és olvashatóbb. Az osztály az adat és a viselkedés összetartozásáról szól.' },
    ],
    note: {
      summary: ['Az osztály adatot és a rá vonatkozó műveleteket fog össze.', 'Az `__init__` a létrehozáskor fut le egyszer.', 'A `self` maga a példány; híváskor nem adod meg, a Python teszi oda.', 'Az osztály a terv, az objektum a belőle készült példány — mindegyiknek saját adatai vannak.', 'Ha nincs viselkedés, elég a szótár.'],
      terms: [{ term: 'osztály', def: 'Terv, ami leírja egy objektum adatait és műveleteit.' }, { term: 'objektum', def: 'Egy osztályból készült konkrét példány.' }, { term: 'self', def: 'A metóduson belül maga a példány, amin a hívás történt.' }],
    },
  },
  {
    day: 17,
    title: 'Állapot és metódusok',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az objektum **állapota** az, amit magában hordoz. A metódusok ezt az állapotot olvassák és változtatják — és épp ezért érdemes vigyázni rá.' },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self):\n        self.akku = 100\n\n    def halad(self, cm):\n        if self.akku <= 0:\n            return False          # nem megy sehova\n        self.akku -= cm * 0.1\n        return True\n\n    def tolt(self):\n        self.akku = 100', explain: 'A `halad` megvédi az objektumot az érvénytelen állapottól: lemerült akkuval nem indul el, és ezt vissza is jelzi.' },
      { k: 'callout', tone: 'key', md: 'Az osztály legnagyobb haszna nem a szintaxis, hanem az, hogy egy helyen őrzöd az adat épségét. Ha csak az osztály metódusai nyúlhatnak az akkuhoz, nem lehet véletlenül -40 %-ra állítani.' },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self, nev):\n        self.nev = nev\n\n    def __repr__(self):\n        return f"Rover({self.nev})"\n\nprint(Rover("Mk-II"))     # Rover(Mk-II)', explain: 'A `__repr__` mondja meg, hogyan nézzen ki az objektum kiíratáskor. Hibakeresésnél ez sokat segít.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `Akku` osztályt `szint` adattal (100-ról indul) és `fogyaszt(mennyi)` metódussal. A szint soha ne mehessen nulla alá. Fogyassz 120-at, és írasd ki a szintet.',
      starter: 'class Akku:\n    pass\n\n',
      checks: [{ k: 'output', contains: '0', label: 'A szint nem megy nulla alá' }],
      hints: ['`self.szint = 100` az `__init__`-ben.', '`self.szint = max(0, self.szint - mennyi)`', 'Végül: `print(a.szint)`.'],
    },
    quiz: [
      { k: 'single', q: 'Mi az objektum állapota?', opts: ['A metódusainak listája', 'Az adatok, amiket magában hordoz', 'Az osztály neve'], answer: 1, why: 'Az állapot a példány adatainak összessége — ami megkülönbözteti egyik objektumot a másiktól.' },
      { k: 'single', q: 'Miért jó, ha csak a metódusok módosítják az adatot?', opts: ['Gyorsabb', 'Egy helyen tudod őrizni, hogy az adat érvényes maradjon', 'Kevesebbet kell gépelni'], answer: 1, why: 'Ha bárhonnan írható, bárhol elromolhat. Ha csak a metódusokon át, elég azokat helyesen megírni.' },
      { k: 'single', q: 'Mire jó a `__repr__`?', opts: ['Gyorsítja az objektumot', 'Megadja, hogyan jelenjen meg kiíratáskor', 'Törli az objektumot'], answer: 1, why: 'Enélkül a `print(obj)` valami olyat ír ki, mint `<__main__.Rover object at 0x7f...>`, ami semmit nem mond. A `__repr__` ezt teszi olvashatóvá.' },
      { k: 'output', q: 'Mit ír ki?', code: 'class C:\n    def __init__(self):\n        self.n = 5\n    def le(self):\n        self.n = max(0, self.n - 10)\n\nc = C()\nc.le()\nprint(c.n)', lang: 'py', opts: ['-5', '0', '5'], answer: 1, why: 'A `max(0, ...)` megfogja az alsó határt, tehát 5-10 = -5 helyett 0 lesz.' },
    ],
    note: {
      summary: ['Az állapot az objektum saját adatainak összessége.', 'A metódusok olvassák és módosítják az állapotot.', 'Ha csak a metódusokon át módosul, egy helyen őrizheted az adat érvényességét.', 'A `__repr__` szabja meg, hogyan néz ki az objektum kiíratáskor — hibakeresésnél sokat ér.', 'A határok (min/max) érvényesítése a metódus dolga, nem a hívóé.'],
      terms: [{ term: 'állapot', def: 'Az objektum saját adatainak összessége.' }, { term: 'metódus', def: 'Osztályon belüli függvény, ami az objektum állapotán dolgozik.' }, { term: 'invariáns', def: 'Szabály, aminek az objektum élete során mindvégig teljesülnie kell.' }],
    },
  },
  {
    day: 18,
    title: 'Öröklődés, amikor tényleg kell',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az **öröklődés** azt jelenti, hogy egy osztály átvesz mindent egy másiktól, és hozzátesz vagy felülír valamit.' },
      { k: 'code', lang: 'py', src: 'class Robot:\n    def __init__(self, nev):\n        self.nev = nev\n\n    def mozog(self):\n        print(f"{self.nev} mozog")\n\nclass Rover(Robot):\n    def mozog(self):\n        print(f"{self.nev} gurul")\n\nclass Dron(Robot):\n    def mozog(self):\n        print(f"{self.nev} repül")\n\nfor r in [Rover("R1"), Dron("D1")]:\n    r.mozog()', explain: 'Mindkettő `Robot`, de másképp mozog. A ciklus nem tudja, melyik micsoda — mégis mindegyik a magáét csinálja. Ezt hívják polimorfizmusnak.' },
      { k: 'callout', tone: 'warn', md: 'Az öröklődést könnyű túlhasználni. Csak akkor érdemes, ha a származtatott osztály **tényleg** a szülő egy fajtája. A „kutya egy állat" jó. A „motor egy autó" nem — a motor az autó *része*, nem fajtája.' },
      { k: 'callout', tone: 'tip', md: 'Ha bizonytalan vagy, ne örökölj: tedd az egyik objektumot a másik adatává. Ezt hívják kompozíciónak, és a legtöbb esetben egyszerűbb.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `Alakzat` osztályt `terulet()` metódussal, ami 0-t ad. Származtass belőle `Negyzet`-et, ami az oldal négyzetét adja. Írasd ki egy 4 oldalú négyzet területét.',
      starter: 'class Alakzat:\n    def terulet(self):\n        return 0\n\n',
      checks: [{ k: 'output', contains: '16', label: 'A 4 oldalú négyzet területe 16' }],
      hints: ['`class Negyzet(Alakzat):`', '`def __init__(self, oldal): self.oldal = oldal`', '`def terulet(self): return self.oldal ** 2`'],
    },
    quiz: [
      { k: 'single', q: 'Mit jelent a `class Rover(Robot):`?', opts: ['A Rover tartalmaz egy Robotot', 'A Rover örököl a Robottól', 'A Rover törli a Robotot'], answer: 1, why: 'A zárójelben a szülőosztály áll. A Rover megkapja a Robot minden metódusát, és felülírhatja őket.' },
      { k: 'output', q: 'Mit ír ki?', code: 'class A:\n    def f(self):\n        return "A"\nclass B(A):\n    def f(self):\n        return "B"\n\nprint(B().f())', lang: 'py', opts: ['A', 'B', 'AB'], answer: 1, why: 'A B felülírta az `f`-et, és a saját változata érvényesül. Ez a felülírás.' },
      { k: 'single', q: 'Mikor NEM jó az öröklődés?', opts: ['Ha a származtatott osztály nem valódi fajtája a szülőnek', 'Ha sok metódus van', 'Ha a szülő rövid'], answer: 0, why: 'Az öröklődés „ez egy olyan" kapcsolatot jelent. Ha a viszony inkább „ennek van egy olyanja", akkor kompozíció kell.' },
      { k: 'single', q: 'Mi a polimorfizmus?', opts: ['Hogy egy osztálynak több neve van', 'Hogy ugyanarra a hívásra különböző típusok különbözőképp válaszolnak', 'Hogy egy metódus többször fut'], answer: 1, why: 'A hívó ugyanazt írja (`r.mozog()`), de minden típus a saját módján válaszol. Ettől lesz bővíthető a kód.' },
    ],
    note: {
      summary: ['Az öröklődés átveszi a szülő minden metódusát, és felül lehet írni őket.', '`class Gyerek(Szulo):` — a zárójelben a szülő áll.', 'Polimorfizmus: ugyanarra a hívásra minden típus a saját módján válaszol.', 'Csak akkor örökölj, ha a gyerek tényleg a szülő egy fajtája.', 'Bizonytalanság esetén kompozíció: legyen az egyik objektum a másik adata.'],
      terms: [{ term: 'öröklődés', def: 'Osztály származtatása egy másikból, annak minden képességével.' }, { term: 'felülírás', def: 'A szülő metódusának lecserélése a gyerekosztályban.' }, { term: 'kompozíció', def: 'Objektum beépítése egy másik adatává, öröklés helyett.' }],
    },
  },
  {
    day: 19,
    title: 'Hibák és kivételek',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A hiba nem kudarc, hanem információ. A **kivétel** a Python módja arra, hogy szóljon: ezt így nem tudom megcsinálni.' },
      { k: 'code', lang: 'py', src: 'try:\n    szam = int("alma")\nexcept ValueError:\n    print("Ez nem szám.")\n    szam = 0\n\nprint(szam)', explain: 'A `try` blokkban próbálkozol, az `except` ágban kezeled, ha elromlott. A program nem áll meg.' },
      { k: 'callout', tone: 'warn', md: 'Ne írj csupasz `except:`-et. Az mindent elkap, a gépelési hibáidat is, és a program csendben rosszul fog működni. Mindig nevezd meg, mire számítasz: `except ValueError:`.' },
      { k: 'code', lang: 'py', src: 'def oszt(a, b):\n    if b == 0:\n        raise ValueError("Nullával nem osztunk")\n    return a / b\n\ntry:\n    oszt(1, 0)\nexcept ValueError as e:\n    print("Hiba:", e)', explain: 'A `raise` te magad dobsz hibát. Ez jobb, mint csendben rossz értéket visszaadni: a hívó legalább tudja, hogy baj van.' },
      { k: 'text', md: 'A leggyakoribb hibafajták:\n\n- `ValueError` — jó típus, rossz érték (`int("alma")`)\n- `TypeError` — rossz típus (`1 + "a"`)\n- `IndexError` — nem létező index\n- `KeyError` — nem létező kulcs\n- `ZeroDivisionError` — nullával osztás' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Írj egy `biztos_int(szoveg)` függvényt, ami számmá alakít, de hibás bemenetre 0-t ad hiba helyett. Próbáld ki "42"-vel és "alma"-val.',
      starter: 'def biztos_int(szoveg):\n    pass\n\nprint(biztos_int("42"))\nprint(biztos_int("alma"))\n',
      checks: [{ k: 'output', contains: '42', label: 'A "42" számmá alakul' }, { k: 'output', contains: '0', label: 'Az "alma" 0-t ad' }],
      hints: ['`try:` majd `return int(szoveg)`.', '`except ValueError:` majd `return 0`.'],
    },
    quiz: [
      { k: 'single', q: 'Mit csinál a `try` / `except` szerkezet?', opts: ['Megelőzi a hibát', 'Elkapja a hibát, és lehetőséget ad kezelni', 'Kiírja a hibát és leáll'], answer: 1, why: 'A hiba bekövetkezik, de nem állítja meg a programot: az `except` ág fut le helyette.' },
      { k: 'single', q: 'Miért rossz a csupasz `except:`?', opts: ['Lassú', 'Mindent elkap, a saját gépelési hibádat is', 'Nem működik Pythonban'], answer: 1, why: 'Elrejti azokat a hibákat is, amikre nem számítottál — és onnantól a program csendben rosszul működik. Ez a legnehezebben megtalálható hibafajta.' },
      { k: 'single', q: 'Milyen hibát dob az `int("alma")`?', opts: ['TypeError', 'ValueError', 'KeyError'], answer: 1, why: 'A típus jó (szöveg), csak az értéke nem alakítható számmá — ez `ValueError`.' },
      { k: 'single', q: 'Mikor érdemes magad `raise`-elni?', opts: ['Soha', 'Ha a függvényed nem tudja értelmesen elvégezni a dolgát', 'Minden függvény elején'], answer: 1, why: 'Ha az adott bemenetre nincs értelmes eredmény, jobb hangosan hibát dobni, mint csendben rossz értéket visszaadni.' },
    ],
    note: {
      summary: ['A kivétel a Python jelzése arra, hogy egy művelet nem végezhető el.', '`try` / `except` elkapja és kezelhetővé teszi a hibát.', 'Mindig nevezd meg, mire számítasz — csupasz `except:` elrejti a saját hibáidat.', 'A `raise` a te hibajelzésed: jobb, mint csendben rossz értéket adni.', 'Gyakori típusok: ValueError, TypeError, IndexError, KeyError, ZeroDivisionError.'],
      terms: [{ term: 'kivétel', def: 'Futásidejű hibajelzés, ami megszakítja a normál végrehajtást.' }, { term: 'try/except', def: 'Szerkezet a hiba elkapására és kezelésére.' }, { term: 'raise', def: 'Saját hiba kiváltása.' }],
    },
  },
  {
    day: 20,
    title: 'Hibakeresés módszeresen',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A hibakeresés nem tehetség kérdése, hanem módszeré. Négy lépés, ebben a sorrendben.' },
      { k: 'text', md: '**1. Reprodukáld.** Ha nem tudod előhívni a hibát parancsra, nem tudod megjavítani sem — csak reménykedni fogsz. Írd le a legkisebb bemenetet, amivel elromlik.\n\n**2. Szűkítsd.** Feleződj: a hiba a kód első vagy második felében van? Egy `print` a közepén megmondja.\n\n**3. Alkoss hipotézist.** Mondd ki, mit gondolsz: „szerintem a lista üres, amikor idejut". Ez ellenőrizhető állítás.\n\n**4. Ellenőrizd.** Írasd ki, és nézd meg. Ha nem az volt, alkoss új hipotézist — ne javítgass vaktában.' },
      { k: 'code', lang: 'py', src: 'def atlag(szamok):\n    print("BEJÖTT:", repr(szamok))       # 1. mit kapott?\n    osszeg = sum(szamok)\n    print("ÖSSZEG:", osszeg)             # 2. jó a részeredmény?\n    return osszeg / len(szamok)', explain: 'A nyomtatás a legegyszerűbb és legmegbízhatóbb eszköz. Nem kell hozzá semmi, és pontosan azt mutatja, ami történik.' },
      { k: 'callout', tone: 'key', md: 'A leggyakoribb hiba a hibakeresésben: azt hiszed, tudod, mi történik, és nem nézed meg. Az olvasott kód azt mutatja, mit **akartál**. A kiírt érték azt, ami **van**.' },
      { k: 'callout', tone: 'warn', md: 'Ha megjavítottad, értsd meg, miért működik. A „most már jó, nem tudom miért" azt jelenti, hogy a hiba visszajön, csak máshol.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Ez a függvény rosszul számol: mindig eggyel kevesebbet ad. Keresd meg és javítsd ki.',
      starter: 'def osszeg(szamok):\n    s = 0\n    for i in range(len(szamok) - 1):\n        s = s + szamok[i]\n    return s\n\nprint(osszeg([1, 2, 3, 4]))\n',
      checks: [{ k: 'output', contains: '10', label: 'Az [1,2,3,4] összege 10' }],
      hints: ['Írasd ki, hány elemen megy végig a ciklus.', 'A `range(len(szamok) - 1)` eggyel kevesebbet ad, mint kellene.', 'A javítás: `range(len(szamok))`, vagy még egyszerűbben `for x in szamok:`.'],
    },
    quiz: [
      { k: 'order', q: 'Mi a módszeres hibakeresés sorrendje?', items: ['Hipotézis felállítása', 'Reprodukálás', 'Ellenőrzés'], correct: [1, 0, 2], why: 'Előbb elő kell tudni hívni a hibát, utána lehet elmélkedni róla, és a végén ellenőrizni az elméletet.' },
      { k: 'single', q: 'Miért kell először reprodukálni a hibát?', opts: ['Mert szép', 'Mert enélkül nem tudod ellenőrizni, hogy megjavítottad-e', 'Mert gyorsabb'], answer: 1, why: 'Ha nem tudod előhívni, nem tudod bizonyítani sem, hogy eltűnt. Csak azt hiszed majd.' },
      { k: 'single', q: 'Mit jelent a felezés a hibakeresésben?', opts: ['Felezed a kódot, és megnézed, melyik felében van a hiba', 'Kétszer futtatod', 'Felezed a bemenetet'], answer: 0, why: 'Egy ellenőrzés a közepén a keresési teret felezi. Tíz felezés ezerszer kisebb területre szűkít.' },
      { k: 'single', q: 'Mit tegyél, ha „valamitől megjavult", de nem tudod, mitől?', opts: ['Örülj és menj tovább', 'Értsd meg, különben visszajön máshol', 'Írd újra az egészet'], answer: 1, why: 'A nem értett javítás azt jelenti, hogy az okot nem találtad meg, csak a tünetet takartad el.' },
    ],
    note: {
      summary: ['Négy lépés: reprodukálás → szűkítés → hipotézis → ellenőrzés.', 'Ha nem tudod előhívni a hibát, nem tudod bizonyítani a javítást sem.', 'Felezéssel szűkíts: egy `print` a közepén felezi a keresési teret.', 'A hipotézis ellenőrizhető állítás legyen, ne sejtés.', 'A kód azt mutatja, mit akartál; a kiírt érték azt, ami van.', 'Amit nem értesz, miért javult meg, az visszajön.'],
      terms: [{ term: 'reprodukálás', def: 'A hiba parancsra való előhívása egy minimális bemenettel.' }, { term: 'felezés', def: 'A keresési tér felezése egy köztes ellenőrzéssel.' }, { term: 'hipotézis', def: 'Ellenőrizhető állítás arról, mi okozza a hibát.' }],
    },
  },
  {
    day: 21,
    title: 'Egy elromlott program megjavítása',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'Ma nem új anyag jön, hanem gyakorlat. Itt egy program, ami majdnem jó. Három hiba van benne — keresd meg mindhármat a tegnapi módszerrel.' },
      { k: 'code', lang: 'py', src: 'def legnagyobb(szamok):\n    legnagyobb = 0                    # (1)\n    for i in range(1, len(szamok)):   # (2)\n        if szamok[i] > legnagyobb:\n            legnagyobb = szamok[i]\n    return legnagyobb\n\nprint(legnagyobb([-5, -2, -9]))       # várt: -2\nprint(legnagyobb([3]))                # várt: 3', explain: 'Futtasd fejben mindkét hívást, mielőtt olvasnád tovább. Melyik sor okozza melyik rossz eredményt?' },
      { k: 'text', md: '**Az (1) hiba:** a nullától indulás feltételezi, hogy van pozitív szám a listában. Csupa negatívnál rossz választ ad. Helyette az **első elemből** kell indulni.\n\n**A (2) hiba:** az 1-től indított ciklus kihagyja a nulladik elemet. Egyelemű listánál egyszer sem fut le.\n\n**A (3) hiba:** üres listára a `szamok[0]` elszáll. Ezt külön kell kezelni.' },
      { k: 'code', lang: 'py', src: 'def legnagyobb(szamok):\n    if not szamok:\n        return None\n    eddigi = szamok[0]\n    for x in szamok:\n        if x > eddigi:\n            eddigi = x\n    return eddigi', explain: 'A javított változat. Figyeld meg azt is, hogy a változó neve már nem ütközik a függvény nevével — az is zavaró volt.' },
      { k: 'callout', tone: 'key', md: 'Mindhárom hiba **peremeset** volt: csupa negatív, egy elem, nulla elem. A hibák nagy része itt lakik, nem a tipikus bemenetnél. Amikor kész vagy, mindig kérdezd meg: mi van, ha üres? ha egy elem? ha mind negatív?' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Ez a `szamlald` függvény rosszul számolja meg a páros számokat. Keresd meg és javítsd.',
      starter: 'def szamlald(szamok):\n    db = 0\n    for x in szamok:\n        if x % 2 == 1:\n            db = db + 1\n    return db\n\nprint(szamlald([1, 2, 3, 4, 6]))\n',
      checks: [{ k: 'output', contains: '3', label: 'Három páros szám van: 2, 4, 6' }],
      hints: ['Írasd ki, melyik számnál növel.', 'A `% 2 == 1` a páratlanokat találja meg, nem a párosokat.', 'A javítás: `if x % 2 == 0:`.'],
    },
    quiz: [
      { k: 'single', q: 'Miért rossz nullától indítani a maximumkeresést?', opts: ['Lassú', 'Csupa negatív számnál rossz választ ad', 'Nem fordul le'], answer: 1, why: 'A nulla nincs a listában, mégis részt vesz az összehasonlításban. Csupa negatívnál ő „nyer", pedig nem is szerepel az adatok közt.' },
      { k: 'single', q: 'Mit hagy ki a `for i in range(1, len(lista))` ciklus?', opts: ['Az utolsó elemet', 'A nulladik elemet', 'Semmit'], answer: 1, why: 'Az 1-es indextől indul, tehát a legelső elemet átugorja. Egyelemű listánál így egyszer sem fut le.' },
      { k: 'multi', q: 'Melyik két peremesetet érdemes mindig végiggondolni?', opts: ['Üres bemenet', 'Nagyon nagy bemenet', 'Egyelemű bemenet', 'Pont tíz elem'], answers: [0, 2], why: 'Az üres és az egyelemű eset borítja fel a legtöbb ciklust és indexelést. A hibák nagy része itt lakik.' },
      { k: 'single', q: 'Miért zavaró, ha a változó ugyanúgy hívják, mint a függvényt?', opts: ['Hibát dob', 'Összekeveri az olvasót, és elfedi az eredeti nevet', 'Lassabb lesz'], answer: 1, why: 'A Python megengedi, de a függvény neve a függvényen belül elérhetetlenné válik, és az olvasó is összezavarodik.' },
    ],
    note: {
      summary: ['A hibák nagy része peremeseteknél lakik: üres, egyelemű, csupa negatív bemenet.', 'Maximumkeresést az első elemből indíts, ne nullából.', 'A `range(1, n)` kihagyja a nulladik elemet — egyelemű listánál egyszer sem fut.', 'Az üres bemenetet külön kezeld, mielőtt indexelnél.', 'Ne nevezd a változót ugyanúgy, mint a függvényt.', 'Készen lenni annyi, mint a peremeseteket is végiggondolni.'],
      terms: [{ term: 'peremeset', def: 'Szélsőséges bemenet: üres, egyelemű, csupa azonos vagy negatív.' }, { term: 'off-by-one', def: 'Eggyel elcsúszott ciklushatár okozta hiba.' }, { term: 'árnyékolás', def: 'Amikor egy változó neve elfedi egy másik, azonos nevű dolgot.' }],
    },
  },
  {
    day: 22,
    title: 'Modulok és importálás',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'Egy fájlba nem fér bele egy komoly program. A **modul** egyetlen `.py` fájl, amit egy másikból használhatsz.' },
      { k: 'code', lang: 'py', src: '# matek.py\ndef terulet(a, b):\n    return a * b\n\nPI = 3.14159', explain: 'Ez egy modul. Semmi különös nincs benne — egy fájl, függvényekkel és értékekkel.' },
      { k: 'code', lang: 'py', src: '# main.py\nimport matek\nprint(matek.terulet(3, 4))\n\nfrom matek import terulet, PI\nprint(terulet(3, 4), PI)', explain: 'Az `import matek` az egész modult hozza, és `matek.` előtaggal éred el. A `from ... import ...` konkrét neveket emel be.' },
      { k: 'callout', tone: 'tip', md: 'Kerüld a `from matek import *` formát. Behoz mindent névtelenül, és fél év múlva senki nem fogja tudni, honnan jött egy függvény.' },
      { k: 'text', md: 'A Python **beépített moduljai** közül a leghasznosabbak: `math` (gyök, szögfüggvények), `random` (véletlen), `json`, `os`, `datetime`, `time`.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Importáld a `math` modult, és írasd ki a 2 négyzetgyökét három tizedesre, valamint a `math.pi` értékét.',
      starter: 'import math\n',
      checks: [{ k: 'output', contains: '1.414', label: 'A gyök 2 értéke megjelenik' }, { k: 'output', contains: '3.14', label: 'A pi értéke megjelenik' }],
      hints: ['`math.sqrt(2)` a négyzetgyök.', 'Formázás: `f"{math.sqrt(2):.3f}"`.', '`print(math.pi)`'],
    },
    quiz: [
      { k: 'single', q: 'Mi a modul?', opts: ['Egy függvény', 'Egy .py fájl, amit másik fájlból használhatsz', 'Egy osztály'], answer: 1, why: 'Minden `.py` fájl modul. Az `import` teszi elérhetővé a tartalmát egy másik fájlból.' },
      { k: 'single', q: 'Mi a különbség az `import math` és a `from math import sqrt` között?', opts: ['Semmi', 'Az elsőnél math.sqrt(), a másodiknál csak sqrt()', 'A második gyorsabb'], answer: 1, why: 'Az `import` a modult hozza be, így minősített néven éred el. A `from ... import` konkrét neveket emel be közvetlenül.' },
      { k: 'single', q: 'Miért kerüljük a `from modul import *` formát?', opts: ['Lassú', 'Nem derül ki, melyik név honnan jött', 'Nem működik'], answer: 1, why: 'Több csillagos import után lehetetlen megmondani, melyik függvény melyik modulból származik — és névütközést is okozhat.' },
      { k: 'multi', q: 'Melyik kettő beépített Python-modul?', opts: ['math', 'rover', 'json', 'kinematics'], answers: [0, 2], why: 'A `math` és a `json` a standard könyvtár része, telepítés nélkül elérhető. A másik kettő kitalált név.' },
    ],
    note: {
      summary: ['A modul egy `.py` fájl, amit másik fájlból használhatsz.', '`import modul` — minősített néven érsz el mindent (`modul.fuggveny()`).', '`from modul import nev` — közvetlenül hozza be a nevet.', 'Kerüld a csillagos importot: elrejti, honnan jött egy név.', 'Hasznos beépítettek: `math`, `random`, `json`, `os`, `datetime`, `time`.'],
      terms: [{ term: 'modul', def: 'Egyetlen Python-fájl, amit másik fájlból importálhatsz.' }, { term: 'import', def: 'Másik modul tartalmának elérhetővé tétele.' }, { term: 'standard könyvtár', def: 'A Pythonnal együtt érkező modulok gyűjteménye.' }],
    },
  },
  {
    day: 23,
    title: 'Könyvtárak használata',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **könyvtár** mások által megírt kód, amit használhatsz. A robotikában és a fizikában szinte minden, amire szükséged lesz, létezik már.' },
      { k: 'code', lang: 'py', src: 'import math\n\nprint(math.sqrt(16))            # 4.0\nprint(math.degrees(math.pi))    # 180.0\nprint(math.sin(math.radians(30)))  # 0.5\nprint(math.hypot(3, 4))         # 5.0 — távolság az origótól', explain: 'A `hypot` a Pitagorasz-tétel egy hívásban. A robotod pozíciójának távolságát pontosan ezzel számolod.' },
      { k: 'code', lang: 'py', src: 'import random\n\nprint(random.randint(1, 6))      # kockadobás\nprint(random.choice(["bal", "jobb"]))\nrandom.seed(42)                  # ismételhető véletlen', explain: 'A `seed` rögzíti a véletlent: ugyanaz a mag ugyanazt a sorozatot adja. Szimuláció tesztelésénél ez elengedhetetlen.' },
      { k: 'callout', tone: 'key', md: 'A robotikában ezekkel fogsz találkozni: `numpy` (mátrixok), `matplotlib` (grafikon), `pyserial` (kommunikáció a mikrokontrollerrel), `opencv` (kamerakép). Egyiket sem kell most megtanulnod — csak tudd, hogy léteznek.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'A robot a (3, 4) pontban van. Számold ki a `math` modullal az origótól való távolságát, és azt, hány fokos irányban van.',
      starter: 'import math\n\nx, y = 3, 4\n',
      checks: [{ k: 'output', contains: '5', label: 'A távolság 5' }],
      hints: ['Távolság: `math.hypot(x, y)`.', 'Szög radiánban: `math.atan2(y, x)`.', 'Fokká alakítás: `math.degrees(...)`.'],
    },
    quiz: [
      { k: 'numeric', q: 'Mennyi a `math.hypot(3, 4)` értéke?', answer: 5, tol: 0.01, why: 'A Pitagorasz-tétel: gyök(3² + 4²) = gyök(25) = 5. Ez a leggyakoribb távolságszámítás a robotikában.' },
      { k: 'single', q: 'Mit csinál a `random.seed(42)`?', opts: ['Negyvenkét véletlen számot generál', 'Rögzíti a véletlen sorozatot, így ismételhető lesz', 'Töröl minden véletlent'], answer: 1, why: 'Ugyanaz a mag ugyanazt a sorozatot adja. Enélkül egy szimulációt nem tudnál kétszer ugyanúgy lefuttatni.' },
      { k: 'single', q: 'Milyen egységben várja a `math.sin` a szöget?', opts: ['Fokban', 'Radiánban', 'Mindkettőt elfogadja'], answer: 1, why: 'Radiánban. Fokból a `math.radians()` alakít át — ennek elfelejtése klasszikus hibaforrás.' },
      { k: 'single', q: 'Miért érdemes meglévő könyvtárat használni?', opts: ['Mert kevesebbet kell gépelni', 'Mert kipróbált és tesztelt, szemben a sajáttal', 'Mert gyorsabban fut'], answer: 1, why: 'Egy elterjedt könyvtárat több ezren használtak és javítottak. A saját megvalósításodat eddig senki.' },
    ],
    note: {
      summary: ['A könyvtár kész, mások által tesztelt kód.', '`math`: `sqrt`, `hypot`, `sin`/`cos`, `radians`/`degrees`.', 'A szögfüggvények radiánt várnak — fokból `math.radians()` alakít.', '`random.seed(n)` ismételhetővé teszi a véletlent; szimuláció tesztelésénél kötelező.', 'A robotikában: numpy, matplotlib, pyserial, opencv — jó tudni, hogy léteznek.'],
      terms: [{ term: 'könyvtár', def: 'Mások által írt, újrahasznosítható kódcsomag.' }, { term: 'radián', def: 'Szögmérték, amit a matematikai függvények várnak.' }, { term: 'seed', def: 'A véletlengenerátor kiindulópontja, ami ismételhetővé teszi a sorozatot.' }],
    },
  },
];
