import type { Day } from '../../types';

/** C++ trek, 17–23. nap. */
export const cppHuD: Day[] = [
  {
    day: 17,
    title: 'const helyessége',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **const helyesség** (const correctness) azt jelenti: mindent `const`-tá teszel, ami nem változik. A fordító ezt ellenőrzi, és a kód szándéka leolvashatóvá válik.' },
      { k: 'code', lang: 'cpp', src: 'class Rover {\n    int akku_ = 100;\n    std::string nev_;\npublic:\n    int akku() const { return akku_; }          // nem módosít\n    const std::string& nev() const { return nev_; }\n\n    void fogyaszt(int mennyi) { akku_ -= mennyi; }   // módosít\n};\n\nvoid kiir(const Rover& r) {\n    std::cout << r.akku();        // csak const metódus hívható\n    // r.fogyaszt(5);             // nem fordul le -- és ez jó\n}', explain: 'A metódus utáni `const` azt ígéri, hogy az objektum nem változik. Egy `const Rover&` hivatkozáson keresztül csak ilyen metódus hívható.' },
      { k: 'callout', tone: 'key', md: 'A szabály: **tegyél `const`-ot minden metódusra, ami nem módosít**, és adj át minden nem módosított paramétert `const` hivatkozásként. Visszamenőleg bevezetni fájdalmas, mert a `const` végigterjed a hívási láncon.' },
      { k: 'text', md: 'A `const` hivatkozás a másolás elkerülésének eszköze is:\n\n```\nvoid f(std::string s);          // másol\nvoid f(const std::string& s);   // nem másol, nem módosít\n```\n\nNagy objektumnál ez érzékelhető különbség. Kis típusnál (`int`, `double`) viszont az érték szerinti átadás gyorsabb.' },
      { k: 'callout', tone: 'warn', md: 'A `mutable` kulcsszó kivételt enged: az ilyen mező `const` metódusból is írható. Gyorsítótárhoz és mutexhez jogos, de ha máshol látod, rendszerint azt jelenti, hogy a `const` ígéret nem igaz.' },
      { k: 'callout', tone: 'tip', md: 'A `const` nem csak dokumentáció: a fordítónak is információ. Egy `const` objektumról tudja, hogy a hívások között nem változik, és ezért több optimalizálást enged meg magának.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent a metódus utáni `const`?', opts: ['Nem ad vissza semmit', 'Nem módosítja az objektumot', 'Nem hívható'], answer: 1, why: 'Egy `const` hivatkozáson keresztül csak ilyen metódus hívható.' },
      { k: 'single', q: 'Miért érdemes `const` hivatkozással átadni egy nagy objektumot?', opts: ['Rövidebb', 'Nem másol és nem is módosít', 'Gyorsabban fordul'], answer: 1, why: 'Kis típusoknál (`int`, `double`) viszont az érték szerinti átadás gyorsabb.' },
      { k: 'single', q: 'Mit enged a `mutable` kulcsszó?', opts: ['A mező `const` metódusból is írható', 'A mező nem változhat', 'A metódus virtuális lesz'], answer: 0, why: 'Gyorsítótárhoz és mutexhez jogos. Máshol rendszerint azt jelzi, hogy a `const` ígéret hamis.' },
      { k: 'single', q: 'Miért nehéz visszamenőleg bevezetni a const helyességet?', opts: ['Sok gépelés', 'Mert a `const` végigterjed a teljes hívási láncon', 'Mert lassítja a kódot'], answer: 1, why: 'Egy `const` metódus csak `const` metódusokat hívhat, így a változás lavinaszerűen terjed.' },
      { k: 'single', q: 'Mit nyer a fordító a `const`-ból?', opts: ['Semmit', 'Tudja, hogy az objektum nem változik, ezért többet optimalizálhat', 'Kisebb binárist'], answer: 1, why: 'A `const` nem csak dokumentáció: valódi információ az optimalizálónak.' },
    ],
    note: {
      summary: ['A const helyesség: minden legyen `const`, ami nem változik.', 'A metódus utáni `const` ígéret: nem módosítja az objektumot.', '`const` hivatkozáson át csak `const` metódus hívható.', 'Nagy objektumot `const&`-ként adj át; kicsit érték szerint.', 'A `mutable` kivételt enged — gyorsítótárhoz és mutexhez jogos.', 'Visszamenőleg bevezetni nehéz, mert a `const` végigterjed.'],
      terms: [{ term: 'const metódus', def: 'Metódus, ami nem módosítja az objektumot.' }, { term: 'const helyesség', def: 'Következetes `const` használat a teljes felületen.' }, { term: 'mutable', def: 'Mező, ami `const` metódusból is írható.' }],
    },
  },
  {
    day: 18,
    title: 'Kivételkezelés',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A C++ kivételkezelése a RAII-ra épül: amikor a kivétel felfelé halad, a **verem lebontása** minden helyi objektum destruktorát lefuttatja. Ez teszi biztonságossá.' },
      { k: 'code', lang: 'cpp', src: '#include <stdexcept>\n\nint akku_szint(const Rover& r) {\n    if (!r.bekapcsolva())\n        throw std::runtime_error("A rover ki van kapcsolva");\n    return r.akku();\n}\n\ntry {\n    int szint = akku_szint(r);\n} catch (const std::runtime_error& e) {\n    std::cerr << e.what() << "\\n";\n} catch (const std::exception& e) {\n    std::cerr << "Egyéb hiba: " << e.what() << "\\n";\n}', explain: 'Mindig **const hivatkozásként** kapd el (`const std::exception&`), ne érték szerint: érték szerint elvágnád a leszármazott típust, és elveszne az információ.' },
      { k: 'callout', tone: 'key', md: 'A `catch` ágak **sorrendben** próbálkoznak, ezért a **szűkebb típus legyen elöl**. Ha a `std::exception` ág áll elöl, az elnyeli az összes többit, és a specifikus ágak sosem futnak le.' },
      { k: 'text', md: 'A szabványos kivételhierarchia:\n\n```\nstd::exception\n├── std::logic_error\n│   ├── std::invalid_argument\n│   └── std::out_of_range\n└── std::runtime_error\n    ├── std::overflow_error\n    └── std::system_error\n```\n\nSaját kivételt `std::runtime_error`-ból származtass, ha nincs jobb illeszkedés.' },
      { k: 'callout', tone: 'warn', md: 'A **destruktor sosem dobhat** kivételt. Ha egy kivétel kezelése közben a destruktor is dob, a program azonnal `std::terminate`-tel leáll. C++11 óta a destruktor alapból `noexcept` — ha mégis dobna, a program meghal.' },
      { k: 'text', md: 'A `noexcept` kulcsszó ígéret: ez a függvény nem dob. A fordító ezt kihasználja (például a `std::vector` mozgatásnál), de ha mégis dobsz, `std::terminate` következik. Csak akkor írd ki, ha biztos vagy benne.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi történik a helyi objektumokkal, amikor egy kivétel felfelé halad?', opts: ['Elvesznek', 'A verem lebontása lefuttatja a destruktorukat', 'Megmaradnak'], answer: 1, why: 'Ez a RAII és a kivételbiztonság alapja: az erőforrások akkor is felszabadulnak.' },
      { k: 'single', q: 'Hogyan kapj el egy kivételt?', opts: ['Érték szerint', '`const` hivatkozásként', 'Mutatóként'], answer: 1, why: 'Érték szerint elvágnád a leszármazott típust, és elveszne az információ.' },
      { k: 'single', q: 'Milyen sorrendben álljanak a `catch` ágak?', opts: ['A szűkebb típus elöl', 'A tágabb típus elöl', 'Mindegy'], answer: 0, why: 'A `std::exception` ág elöl elnyelné az összes többit.' },
      { k: 'single', q: 'Mi történik, ha egy destruktor kivételt dob?', opts: ['Semmi', 'A program `std::terminate`-tel leáll', 'Elkapható'], answer: 1, why: 'C++11 óta a destruktor alapból `noexcept`. Kivételkezelés közben dobva azonnal meghal a program.' },
      { k: 'single', q: 'Mit jelent a `noexcept`?', opts: ['Nem kap el kivételt', 'Ígéret, hogy ez a függvény nem dob', 'Elnyeli a kivételt'], answer: 1, why: 'A fordító kihasználja, de ha mégis dobsz, `std::terminate` következik.' },
    ],
    note: {
      summary: ['A verem lebontása lefuttatja a helyi objektumok destruktorát — ez a RAII haszna.', 'Mindig `const` hivatkozásként kapd el a kivételt.', 'A szűkebb `catch` típus álljon elöl.', 'Hierarchia: `std::exception` → `logic_error` / `runtime_error`.', 'A destruktor sosem dobhat: `std::terminate` lenne belőle.', 'A `noexcept` ígéret, nem védelem.'],
      terms: [{ term: 'verem lebontása', def: 'A helyi objektumok destruktorainak lefuttatása kivétel közben.' }, { term: 'szeletelés (slicing)', def: 'A leszármazott rész elvesztése érték szerinti másoláskor.' }, { term: 'noexcept', def: 'Ígéret, hogy a függvény nem dob kivételt.' }],
    },
  },
  {
    day: 19,
    title: 'Névterek',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'A **névtér** (namespace) a C++ névütközés elleni eszköze. Két könyvtár nyugodtan tartalmazhat `Logger` osztályt, ha külön névtérben vannak.' },
      { k: 'code', lang: 'cpp', src: 'namespace forge {\nnamespace robot {\n\nclass Rover { /* ... */ };\n\n}  // namespace robot\n}  // namespace forge\n\n// C++17-től rövidebben:\nnamespace forge::robot {\nclass Rover { /* ... */ };\n}\n\nforge::robot::Rover r;\nnamespace fr = forge::robot;    // rövidítés\nfr::Rover r2;', explain: 'A névtér-rövidítés (`namespace fr = ...`) helyi, és csak abban a hatókörben él, ahol kiírtad. Ez a jó középút a teljes név és a `using` között.' },
      { k: 'callout', tone: 'warn', md: 'A `using namespace std;` **fejlécfájlban soha**. Minden fájlra ráterül, ami a fejlécet beolvassa, és olyan ütközéseket okoz, amiket az érintett fájl szerzője nem is lát. Forrásfájlban, függvényen belül megengedhető.' },
      { k: 'text', md: 'A **névtelen névtér** a C fájlszintű `static` kulcsszavának megfelelője:\n\n```cpp\nnamespace {\n    int belso_szamlalo = 0;        // csak ebben a fájlban látszik\n    void segitofuggveny() { }\n}\n```\n\nEz a modern C++ módja annak, hogy valamit a fordítási egységen belül tarts.' },
      { k: 'callout', tone: 'key', md: 'Az **ADL** (argumentumfüggő névfeloldás) miatt a fordító a paraméter névterében is keres függvényt. Ezért működik az `std::cout << v` akkor is, ha az operátort nem minősítetted — a `std` névtérben megtalálja.' },
      { k: 'text', md: 'A gyakorlati szokás: a könyvtár kapjon egy rövid, egyedi gyökérnévteret (`forge`), és azon belül legyen alnévtér funkció szerint. A `detail` nevű alnévtér hagyományosan a belső, nem publikus részt jelöli.' },
    ],
    quiz: [
      { k: 'single', q: 'Mire való a névtér?', opts: ['Gyorsít', 'Névütközés megelőzése', 'Memóriát spórol'], answer: 1, why: 'Két könyvtár nyugodtan tartalmazhat azonos nevű osztályt, ha külön névtérben vannak.' },
      { k: 'single', q: 'Hol tilos a `using namespace std;`?', opts: ['Forrásfájlban', 'Fejlécfájlban', 'Függvényen belül'], answer: 1, why: 'Ráterül minden fájlra, ami a fejlécet beolvassa, és láthatatlan ütközéseket okoz.' },
      { k: 'single', q: 'Mi a névtelen névtér megfelelője C-ben?', opts: ['`extern`', 'A fájlszintű `static`', '`const`'], answer: 1, why: 'Mindkettő a fordítási egységen belülre korlátozza a láthatóságot.' },
      { k: 'single', q: 'Mit jelent az ADL?', opts: ['Automatikus törlés', 'A fordító a paraméter névterében is keres függvényt', 'Egy könyvtár'], answer: 1, why: 'Ezért működik az `std::cout << v` minősítés nélkül is.' },
      { k: 'single', q: 'Mit jelöl hagyományosan a `detail` alnévtér?', opts: ['A dokumentációt', 'A belső, nem publikus részt', 'A teszteket'], answer: 1, why: 'Jelzés az olvasónak: erre ne hivatkozz kívülről, bármikor megváltozhat.' },
    ],
    note: {
      summary: ['A névtér a névütközés elleni eszköz.', 'C++17-től `namespace a::b { }` alakban írható.', 'Névtér-rövidítés: `namespace fr = forge::robot;`.', '`using namespace std;` fejlécben soha.', 'Névtelen névtér = a C fájlszintű `static` megfelelője.', 'ADL: a fordító a paraméter névterében is keres.', 'A `detail` alnévtér a belső részt jelöli.'],
      terms: [{ term: 'névtér', def: 'Nevek csoportosítása ütközés elkerülésére.' }, { term: 'névtelen névtér', def: 'Fordítási egységre korlátozott láthatóság.' }, { term: 'ADL', def: 'Argumentumfüggő névfeloldás a paraméter névterében.' }],
    },
  },
  {
    day: 20,
    title: 'Fejléc és forrás szétválasztása',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A C++ ugyanazt a fejléc–forrás felosztást használja, mint a C, de a sablonok és az inline függvények miatt több a kivétel.' },
      { k: 'callout', tone: 'key', md: 'Az alapszabály: a **`.hpp` a felület**, a **`.cpp` a megvalósítás**. Amit nem kell kívülről látni, az ne kerüljön a fejlécbe — minden ott lévő sor minden beolvasó fájl fordítási idejét növeli.' },
      { k: 'code', lang: 'cpp', src: '// rover.hpp\n#pragma once                     // egyszerűbb, mint az include guard\n#include <string>\n\nclass Terkep;                    // előzetes deklaráció: elég a mutatóhoz\n\nclass Rover {\n    std::string nev_;\n    Terkep* terkep_ = nullptr;\npublic:\n    explicit Rover(std::string nev);\n    void lep(int cm);\n};', explain: 'Az **előzetes deklaráció** (`class Terkep;`) elég, ha csak mutatót vagy hivatkozást tárolsz. Így nem kell beolvasni a `terkep.hpp` fájlt, és nem terjed a fordítási függőség.' },
      { k: 'callout', tone: 'warn', md: 'A **sablonok** nem válaszhatók szét: a fordítónak látnia kell a teljes törzset a kifejtéshez. Ezért marad a sablonkód a fejlécben — és ezért nő meg a sablonnehéz projektek fordítási ideje.' },
      { k: 'text', md: 'Mi kerüljön mégis a fejlécbe?\n\n- **inline függvények** — rövid getterek, egysoros műveletek\n- **sablonok** — kötelezően\n- **constexpr** függvények és konstansok\n- `class` és `struct` definíciók' },
      { k: 'callout', tone: 'tip', md: 'A `#pragma once` ma minden elterjedt fordítón működik, és rövidebb, mint a háromsoros include guard. Csak akkor válaszd az `#ifndef` alakot, ha nagyon régi vagy egzotikus fordítót is támogatnod kell.' },
      { k: 'text', md: 'A **PIMPL** minta a legerősebb eszköz a fordítási függőség elvágására: a privát mezőket egy előre deklarált `Impl` osztályba teszed, és a fejlécben csak egy `std::unique_ptr<Impl>` marad. Ettől a megvalósítás változása nem fordítja újra a fél projektet.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az alapszabály a fejléc és a forrás közt?', opts: ['Mindent a fejlécbe', 'A `.hpp` a felület, a `.cpp` a megvalósítás', 'Mindent a forrásba'], answer: 1, why: 'Minden fejlécbe tett sor minden beolvasó fájl fordítási idejét növeli.' },
      { k: 'single', q: 'Mikor elég az előzetes deklaráció?', opts: ['Mindig', 'Ha csak mutatót vagy hivatkozást tárolsz', 'Soha'], answer: 1, why: 'Értéktag esetén a fordítónak ismernie kell a méretet, tehát kell a teljes definíció.' },
      { k: 'single', q: 'Miért marad a sablonkód a fejlécben?', opts: ['Hagyomány', 'Mert a fordítónak látnia kell a teljes törzset a kifejtéshez', 'Mert gyorsabb'], answer: 1, why: 'Ezért nő meg a sablonnehéz projektek fordítási ideje.' },
      { k: 'single', q: 'Mi a `#pragma once` előnye?', opts: ['Gyorsabb futás', 'Rövidebb, mint a háromsoros include guard, és minden elterjedt fordítón működik', 'Kisebb bináris'], answer: 1, why: 'Csak nagyon régi vagy egzotikus fordítóhoz kell az `#ifndef` alak.' },
      { k: 'single', q: 'Mit old meg a PIMPL minta?', opts: ['Gyorsítja a futást', 'Elvágja a fordítási függőséget: a megvalósítás változása nem fordít újra mindent', 'Csökkenti a memóriát'], answer: 1, why: 'A privát mezők egy előre deklarált `Impl` osztályba kerülnek, a fejlécben csak egy mutató marad.' },
    ],
    note: {
      summary: ['`.hpp` a felület, `.cpp` a megvalósítás.', 'Előzetes deklaráció elég mutatóhoz és hivatkozáshoz.', 'A sablonok kötelezően a fejlécben maradnak.', 'Fejlécbe való még: inline, constexpr, osztálydefiníció.', '`#pragma once` helyettesíti az include guardot.', 'PIMPL: a privát rész egy `Impl` osztályba, hogy ne terjedjen a függőség.'],
      terms: [{ term: 'előzetes deklaráció', def: 'Típus bejelentése a teljes definíció nélkül.' }, { term: '#pragma once', def: 'Fordítói utasítás a fejléc egyszeri beolvasására.' }, { term: 'PIMPL', def: 'Minta, ami a privát megvalósítást külön osztályba rejti.' }],
    },
  },
  {
    day: 21,
    title: 'CMake alapok',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **CMake** nem fordít: *generál*. Egy leírásból készít Makefile-t, Ninja fájlt vagy Visual Studio projektet — ezért tud ugyanaz a projekt minden platformon épülni.' },
      { k: 'code', lang: 'cpp', src: '/* CMakeLists.txt\ncmake_minimum_required(VERSION 3.20)\nproject(robot VERSION 1.0 LANGUAGES CXX)\n\nset(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\nadd_library(robotlib\n    src/rover.cpp\n    src/motor.cpp\n)\ntarget_include_directories(robotlib PUBLIC include)\n\nadd_executable(robot src/main.cpp)\ntarget_link_libraries(robot PRIVATE robotlib)\n*/', explain: 'A modern CMake **célközpontú**: minden beállítás egy célhoz (`target_...`) tartozik, nem globális változókhoz. Ettől öröklődnek helyesen a függőségek.' },
      { k: 'callout', tone: 'key', md: 'A `PUBLIC`, `PRIVATE`, `INTERFACE` kulcsszavak a függőség **terjedését** szabályozzák:\n\n- **PRIVATE** — csak ennek a célnak kell\n- **PUBLIC** — ennek is és mindenkinek, aki ezt használja\n- **INTERFACE** — csak a használóknak, ennek nem' },
      { k: 'text', md: 'A szokásos munkamenet:\n\n```\ncmake -S . -B build -DCMAKE_BUILD_TYPE=Debug\ncmake --build build -j\nctest --test-dir build\n```\n\nA `-S` a forrás, a `-B` a külön építési könyvtár. **Mindig külön könyvtárba építs**, hogy a generált fájlok ne keveredjenek a forrással.' },
      { k: 'callout', tone: 'warn', md: 'Ne használd a `file(GLOB ...)` függvényt forrásfájlok összeszedésére. A CMake csak generáláskor futtatja, ezért egy újonnan hozzáadott fájlt nem vesz észre, amíg nem generálsz újra. Sorold fel a fájlokat kézzel — egyértelmű és megbízható.' },
      { k: 'callout', tone: 'tip', md: 'A `FetchContent` modullal külső könyvtárat húzhatsz be közvetlenül a `CMakeLists.txt` fájlból, telepítés nélkül. Tesztkönyvtárakhoz (GoogleTest, Catch2) ez a legegyszerűbb út.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit csinál a CMake?', opts: ['Fordít', 'Generál: Makefile-t, Ninja fájlt vagy IDE projektet', 'Futtat'], answer: 1, why: 'Ezért tud ugyanaz a projekt minden platformon épülni.' },
      { k: 'single', q: 'Mit jelent a modern, célközpontú CMake?', opts: ['Globális változókat állítasz', 'Minden beállítás egy célhoz tartozik, `target_...` parancsokkal', 'Nincs különbség'], answer: 1, why: 'Így öröklődnek helyesen a függőségek a cél használóira.' },
      { k: 'single', q: 'Mit jelent a `PUBLIC` egy `target_link_libraries` hívásban?', opts: ['Csak ennek a célnak kell', 'Ennek is és mindenkinek, aki ezt a célt használja', 'Csak a használóknak'], answer: 1, why: 'A `PRIVATE` nem terjed tovább, az `INTERFACE` csak a használóknak szól.' },
      { k: 'single', q: 'Miért építs külön könyvtárba?', opts: ['Gyorsabb', 'Hogy a generált fájlok ne keveredjenek a forrással', 'Kötelező'], answer: 1, why: 'A `cmake -S . -B build` alak pontosan ezt teszi, és a `build` könyvtár bármikor törölhető.' },
      { k: 'single', q: 'Miért kerülendő a `file(GLOB ...)`?', opts: ['Lassú', 'Mert csak generáláskor fut, így új fájlt nem vesz észre', 'Nem támogatott'], answer: 1, why: 'A kézi felsorolás egyértelmű és megbízható.' },
    ],
    note: {
      summary: ['A CMake generál: Makefile-t, Ninja fájlt vagy IDE projektet.', 'Modern CMake célközpontú: `target_...` parancsok, nem globális változók.', 'PRIVATE csak ennek, PUBLIC tovább is terjed, INTERFACE csak a használóknak.', 'Munkamenet: `cmake -S . -B build`, `cmake --build build`, `ctest`.', 'Mindig külön építési könyvtárba építs.', 'Ne használj `file(GLOB ...)` forrásfájlokhoz.', '`FetchContent` húz be külső könyvtárat telepítés nélkül.'],
      terms: [{ term: 'cél (target)', def: 'Egy könyvtár vagy futtatható, amihez a beállítások tartoznak.' }, { term: 'külön építési könyvtár', def: 'A generált fájlokat a forrástól elkülönítő mappa.' }, { term: 'FetchContent', def: 'CMake modul külső függőség letöltésére építés közben.' }],
    },
  },
  {
    day: 22,
    title: 'Fordítási hibák olvasása',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A C++ hibaüzenetei hírhedten hosszúak. Néhány szabállyal viszont rendszerint harminc másodperc alatt megtalálható a valódi ok.' },
      { k: 'callout', tone: 'key', md: 'Három szabály:\n\n1. **Mindig a legelső hibát javítsd.** A többi rendszerint annak a következménye. Egy hiányzó pontosvessző húsz hibát szül.\n2. **Sablonhibát alulról olvass.** A felső sorok a kifejtési útvonalat sorolják; a valódi ok a lánc végén van.\n3. **Nézd meg az előző sort is.** Hiányzó pontosvesszőnél és zárójelnél a fordító a következő sorra mutat.' },
      { k: 'text', md: 'A leggyakoribb üzenetek és mit jelentenek:\n\n- **„undefined reference to ..."** — linker-hiba: a deklaráció megvolt, a definíció hiányzik\n- **„no matching function for call to ..."** — a paraméterek típusa nem illik; nézd meg a felsorolt jelölteket\n- **„incomplete type"** — csak előzetes deklaráció van, de a teljes definíció kellene\n- **„invalid use of ... in read-only object"** — `const` objektumon hívtál nem `const` metódust\n- **„expected ; before ..."** — rendszerint az **előző** sor végén hiányzik a pontosvessző' },
      { k: 'callout', tone: 'tip', md: 'A **Clang** hibaüzenetei rendszerint olvashatóbbak a GCC-éinél. Ha egy üzenet érthetetlen, fordítsd le ugyanazt a fájlt Clanggal — gyakran egyetlen mondatban megmondja, mi a baj.' },
      { k: 'text', md: 'Sablonhibánál a hasznos kapcsolók:\n\n- `-fmax-errors=1` (GCC) vagy `-ferror-limit=1` (Clang) — csak az első hiba, a lavina nélkül\n- `-fno-diagnostics-show-template-tree` — rövidebb sablonkiírás\n- `-fdiagnostics-color=always` — színezés, ami sokat segít a hosszú típusnevek olvasásában' },
      { k: 'callout', tone: 'warn', md: 'C++20-tól a **koncepciók** (`concept`) sokkal érthetőbb hibaüzenetet adnak sablonokra: „a T típus nem elégíti ki a Rendezheto követelményt" helyett kapsz háromszáz sor kifejtési nyomvonalat. Ha teheted, használd őket.' },
    ],
    quiz: [
      { k: 'single', q: 'Melyik hibát javítsd először?', opts: ['Az utolsót', 'A legelsőt', 'A legrövidebbet'], answer: 1, why: 'A többi rendszerint annak a következménye. Egy hiányzó pontosvessző húsz hibát szül.' },
      { k: 'single', q: 'Hogyan olvasd a sablonhibát?', opts: ['Felülről', 'Alulról: a valódi ok a lánc végén van', 'Középről'], answer: 1, why: 'A felső sorok a kifejtési útvonalat sorolják.' },
      { k: 'single', q: 'Mit jelent az „undefined reference"?', opts: ['Szintaktikai hiba', 'Linker-hiba: a definíció hiányzik', 'Hiányzó fejléc'], answer: 1, why: 'A deklaráció megvolt, különben a fordító szólt volna korábban.' },
      { k: 'single', q: 'Hol keresd a hibát „expected ; before ..." üzenetnél?', opts: ['A jelzett sorban', 'Rendszerint az előző sor végén', 'A fájl elején'], answer: 1, why: 'A fordító ott veszi észre a hiányt, ahol a következő utasítás kezdődne.' },
      { k: 'single', q: 'Mi a koncepciók (`concept`) haszna?', opts: ['Gyorsabb fordítás', 'Sokkal érthetőbb hibaüzenet sablonoknál', 'Kisebb bináris'], answer: 1, why: 'Háromszáz sor kifejtési nyomvonal helyett egy mondatban megmondja, melyik követelmény sérült.' },
    ],
    note: {
      summary: ['Mindig a legelső hibát javítsd: a többi annak következménye.', 'Sablonhibát alulról olvass.', 'Hiányzó pontosvesszőnél az előző sort nézd.', '„undefined reference" = linker-hiba, hiányzó definíció.', '„incomplete type" = csak előzetes deklaráció van.', 'Clang üzenetei gyakran olvashatóbbak; `-fmax-errors=1` levágja a lavinát.', 'C++20 koncepciók sokkal érthetőbb sablonhibát adnak.'],
      terms: [{ term: 'hibalavina', def: 'Egyetlen hibából keletkező sok követő hibaüzenet.' }, { term: 'incomplete type', def: 'Előre deklarált, de nem teljesen definiált típus.' }, { term: 'koncepció (concept)', def: 'C++20 eszköz sablonkövetelmények megnevezésére.' }],
    },
  },
  {
    day: 23,
    title: 'Egységtesztelés',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az **egységteszt** egy apró, gyors, automatikusan futó ellenőrzés egyetlen viselkedésre. Nem a hibák megtalálásáról szól elsősorban, hanem arról, hogy **változtatni merj**.' },
      { k: 'code', lang: 'cpp', src: '#include <catch2/catch_test_macros.hpp>\n#include "rover.hpp"\n\nTEST_CASE("a rover nem megy át a falon") {\n    Rover r{"Alfa"};\n    r.helyez(0, 0);\n\n    SECTION("szabad úton elmozdul") {\n        REQUIRE(r.lep(10) == 10);\n        REQUIRE(r.x() == 10);\n    }\n\n    SECTION("falnál megáll") {\n        r.falat_tesz(5);\n        REQUIRE(r.lep(10) == 5);\n    }\n}', explain: 'Minden `SECTION` **újra lefuttatja** a `TEST_CASE` elejét, tehát friss `Rover`-rel indul. Ettől nem szivárognak át az állapotok a tesztek között.' },
      { k: 'callout', tone: 'key', md: 'A jó teszt három részből áll (**arrange, act, assert**): felállítod az állapotot, végrehajtod a műveletet, ellenőrzöd az eredményt. Ha egy tesztben több „act" van, rendszerint két tesztnek kellene lennie.' },
      { k: 'text', md: 'Mit tesztelj?\n\n- **Határeseteket**: üres bemenet, nulla, maximum, egyetlen elem\n- **Hibaágakat**: mi történik érvénytelen bemenetre\n- **Minden javított hibát**: előbb írj tesztet, ami megbukik, aztán javíts\n\nMit ne: triviális gettereket és a fordító által garantált dolgokat.' },
      { k: 'callout', tone: 'warn', md: 'A **lassú teszt halott teszt**. Ha a tesztsor több percig fut, senki nem futtatja. Egy egységteszt ezredmásodpercekben mérhető: ne nyúljon hálózathoz, fájlrendszerhez vagy adatbázishoz. Ha mégis kell, az már integrációs teszt.' },
      { k: 'text', md: 'A CMake-ből így kapcsolod be:\n\n```\nenable_testing()\nadd_executable(tesztek test/rover_test.cpp)\ntarget_link_libraries(tesztek PRIVATE robotlib Catch2::Catch2WithMain)\nadd_test(NAME rover COMMAND tesztek)\n```\n\nUtána a `ctest --test-dir build` futtatja mindet.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az egységteszt fő haszna?', opts: ['Hibát talál', 'Bátorságot ad a változtatáshoz', 'Dokumentál'], answer: 1, why: 'Visszajelzést ad arról, hogy a változtatás nem rontott el mást. A hibakeresés csak mellékhaszon.' },
      { k: 'single', q: 'Mi a jó teszt három része?', opts: ['Setup, run, print', 'Arrange, act, assert', 'Open, read, close'], answer: 1, why: 'Állapot felállítása, művelet végrehajtása, eredmény ellenőrzése.' },
      { k: 'single', q: 'Mi történik minden `SECTION` futásakor a Catch2-ben?', opts: ['Folytatja az előző állapotot', 'Újra lefut a `TEST_CASE` eleje, tehát friss állapottal indul', 'Kihagyja a többit'], answer: 1, why: 'Ettől nem szivárognak át az állapotok a tesztek között.' },
      { k: 'single', q: 'Mit ne tesztelj?', opts: ['Határeseteket', 'Triviális gettereket és a fordító által garantált dolgokat', 'Hibaágakat'], answer: 1, why: 'Ezek nem hordoznak kockázatot, csak karbantartási terhet.' },
      { k: 'single', q: 'Miért baj a lassú tesztsor?', opts: ['Sok memóriát használ', 'Mert senki nem futtatja, és ettől elveszti az értelmét', 'Mert hibás'], answer: 1, why: 'Az egységteszt ezredmásodpercekben mérhető: ne nyúljon hálózathoz vagy fájlrendszerhez.' },
    ],
    note: {
      summary: ['Az egységteszt apró, gyors ellenőrzés egyetlen viselkedésre.', 'Fő haszna: bátorság a változtatáshoz.', 'Felépítés: arrange, act, assert.', 'Catch2-ben minden `SECTION` friss állapottal indul.', 'Tesztelj határeseteket, hibaágakat és minden javított hibát.', 'A lassú teszt halott teszt: ne nyúljon hálózathoz vagy lemezhez.', 'CMake-ben `enable_testing()` és `add_test`, futtatás `ctest`-tel.'],
      terms: [{ term: 'egységteszt', def: 'Egyetlen viselkedést ellenőrző gyors, automatikus teszt.' }, { term: 'arrange-act-assert', def: 'A teszt három szakasza: felállítás, művelet, ellenőrzés.' }, { term: 'integrációs teszt', def: 'Több komponens együttműködését vizsgáló, lassabb teszt.' }],
    },
  },
];
