import type { Track } from '../../types';
import { cppHuB } from './cpp-b';
import { cppHuC } from './cpp-c';

export const cppHu: Track = {
  id: 'cpp',
  title: 'C++',
  blurb: 'A C ereje osztályokkal, sablonokkal, STL-lel.',
  plannedTitles: [
    'C++ és C: mi a különbség?',
    'String és vector',
    'Osztályok és RAII',
    'Referencia és érték szerinti átadás',
    'Konstruktor és destruktor',
    'Másoló és mozgató szemantika',
    'Operátor-túlterhelés',
    'Öröklődés és virtuális metódusok',
    'Absztrakt osztály',
    'Okos mutatók',
    'Sablonok (template)',
    'STL konténerek',
    'Iterátorok',
    'Algoritmusok: sort, find, transform',
    'Lambda kifejezések',
    'auto és típuskikövetkeztetés',
    'const helyessége',
    'Kivételkezelés',
    'Névterek',
    'Fejléc és forrás szétválasztása',
    'CMake alapok',
    'Fordítási hibák olvasása',
    'Egységtesztelés',
    'Teljesítmény és optimalizálás',
    'Mozgatás és másolás költsége',
    'Többszálúság alapok',
    'Modern C++ stílus',
    'Beágyazott C++',
    'Egy kisebb program',
    'A teljes projekt',
  ],
  days: [
    {
      day: 1,
      title: 'C++ és C: mi a különbség?',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'A C++ a C-ből nőtt ki, és majdnem minden C program lefordul C++-ként is. De a **stílusa** gyökeresen más: a C-ben te kezeled a memóriát, a C++-ban az objektumok kezelik magukat.' },
        { k: 'code', lang: 'cpp', src: '#include <iostream>\n\nint main() {\n    std::cout << "Szia, C++!" << std::endl;\n    return 0;\n}', explain: 'A `std::cout` a kimeneti folyam, a `<<` a beletöltő operátor. Nincs formátumjelölő, mint a `printf`-nél — a típust a fordító tudja.' },
        { k: 'callout', tone: 'key', md: 'Ez a `printf` legnagyobb baját oldja meg: a `cout`-nál **nem lehet rossz formátumjelölőt** megadni, mert nincs is. A fordító tudja, hogy számot vagy szöveget adtál át.' },
        { k: 'text', md: 'Fordítás:\n\n```\ng++ -std=c++17 -Wall hello.cpp -o hello\n./hello\n```\n\nA `-std=c++17` megadja a nyelvi szabványt. Enélkül régebbi, szegényesebb változatot kapsz.' },
        { k: 'code', lang: 'cpp', src: '#include <iostream>\nusing namespace std;   // kerülendő nagy projektben\n\nint main() {\n    cout << "rövidebb, de kockázatos" << endl;\n}', explain: 'A `using namespace std;` megspórolja a `std::` előtagot, de névütközést okozhat. Tanuláskor rendben, komoly projektben kerüld.' },
      ],
      quiz: [
        { k: 'single', q: 'Miért biztonságosabb a `cout` a `printf`-nél?', opts: ['Gyorsabb', 'Nincs formátumjelölő, amit el lehetne rontani', 'Kevesebbet kell gépelni'], answer: 1, why: 'A `printf` elhiszi, amit a jelölőben mondasz neki. A `cout`-nál a fordító ismeri a típust, ezért nem lehet elrontani.' },
        { k: 'single', q: 'Mit jelent a `std::`?', opts: ['Statikus', 'A szabványos könyvtár névtere', 'Szabványos adat'], answer: 1, why: 'A `std` a standard library névtere. A `std::cout` azt jelenti: a `cout` nevű dolog a `std` névtérből.' },
        { k: 'single', q: 'Miért kerüljük a `using namespace std;`-t nagy projektben?', opts: ['Lassabb', 'Névütközést okozhat a saját neveiddel', 'Nem fordul le'], answer: 1, why: 'Az egész szabványos könyvtárat behozza névtér nélkül. Egy saját `count` vagy `distance` nevű dolog ütközhet vele.' },
        { k: 'output', q: 'Mit ír ki?', code: '#include <iostream>\nint main() {\n    std::cout << 2 + 3 << "x" << std::endl;\n}', lang: 'cpp', opts: ['23x', '5x', '2+3x'], answer: 1, why: 'A `2 + 3` előbb kiértékelődik 5-re, azt tölti a folyamba, majd az "x"-et. Az eredmény: 5x.' },
      ],
      note: {
        summary: ['A C++ a C-ből nőtt ki; a legtöbb C kód lefordul, de a stílus más.', '`std::cout << ... << std::endl` a kimenet; nincs formátumjelölő.', 'Ez biztonságosabb a printf-nél: a fordító ismeri a típust.', 'Fordítás: `g++ -std=c++17 -Wall file.cpp -o file`.', 'A `using namespace std;` kényelmes, de nagy projektben névütközést okoz.'],
        terms: [{ term: 'folyam (stream)', def: 'Be- vagy kimeneti csatorna, amibe a `<<` operátorral töltesz.' }, { term: 'névtér', def: 'Nevek csoportja, ami megakadályozza az ütközést; a szabványosé a `std`.' }, { term: 'nyelvi szabvány', def: 'A C++ verziója, amit a `-std=` kapcsolóval adsz meg.' }],
      },
    },
    {
      day: 2,
      title: 'String és vector',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'C-ben a szöveg karaktertömb, a lista pedig kézzel foglalt memória. C++-ban mindkettőre van kész, biztonságos típus — és ez a nyelv egyik legnagyobb nyeresége.' },
        { k: 'code', lang: 'cpp', src: '#include <string>\n#include <vector>\n#include <iostream>\n\nint main() {\n    std::string nev = "Rover";\n    nev += " Mk-II";\n    std::cout << nev << " " << nev.size() << "\\n";\n\n    std::vector<int> tavok = {12, 8, 30};\n    tavok.push_back(5);\n    std::cout << tavok.size() << " " << tavok[0] << "\\n";\n}', explain: 'A `string` magától nő, a `vector` magától foglal helyet. Nincs `malloc`, nincs `free`, nincs méretszámolgatás.' },
        { k: 'callout', tone: 'key', md: 'A `vector` **saját maga kezeli a memóriáját**: amikor kimegy a hatókörből, felszabadul. Ez a RAII, és ez az, amiért a modern C++-ban ritkán kell kézzel memóriát kezelni.' },
        { k: 'code', lang: 'cpp', src: 'for (int t : tavok) {\n    std::cout << t << " ";\n}\n\nfor (size_t i = 0; i < tavok.size(); i++) {\n    std::cout << tavok[i] << " ";\n}', explain: 'A tartomány alapú `for` olvashatóbb, és nem lehet elrontani az indexet. Használd ezt, ha nem kell maga az index.' },
        { k: 'callout', tone: 'warn', md: 'A `tavok[10]` egy háromelemű vektoron **nem** dob hibát — csak olvas valamit a memóriából. Ha ellenőrzést akarsz, a `tavok.at(10)` kivételt dob. A `[]` gyors, az `at()` biztonságos.' },
      ],
      quiz: [
        { k: 'single', q: 'Mi a `std::vector` legnagyobb előnye a C tömbhöz képest?', opts: ['Gyorsabb', 'Magától kezeli a memóriát és a méretét', 'Kevesebb helyet foglal'], answer: 1, why: 'A vektor nő, ha kell, és felszabadítja magát, amikor kimegy a hatókörből. A C tömbnél ezt neked kellene megoldanod.' },
        { k: 'single', q: 'Mi a különbség a `v[10]` és a `v.at(10)` közt?', opts: ['Semmi', 'Az at() ellenőriz és kivételt dob, a [] nem ellenőriz', 'Az at() gyorsabb'], answer: 1, why: 'A `[]` nem néz határt — érvénytelen indexnél meghatározatlan viselkedést kapsz. Az `at()` kivételt dob, cserébe lassabb egy hajszállal.' },
        { k: 'output', q: 'Mit ír ki?', code: 'std::vector<int> v = {1, 2};\nv.push_back(3);\nstd::cout << v.size();', lang: 'cpp', opts: ['2', '3', '6'], answer: 1, why: 'Két elemmel indult, a `push_back` hozzátett egyet, tehát a méret 3.' },
        { k: 'single', q: 'Mikor használd a tartomány alapú `for`-t?', opts: ['Soha', 'Amikor nincs szükséged magára az indexre', 'Csak stringnél'], answer: 1, why: 'Olvashatóbb és nem lehet elrontani a határokat. Ha viszont kell az index, a klasszikus ciklus a helyes választás.' },
      ],
      note: {
        summary: ['A `std::string` magától nő; nincs karaktertömb-kezelés.', 'A `std::vector` dinamikus tömb, ami maga kezeli a memóriáját.', 'A memória felszabadul, amikor a vektor kimegy a hatókörből — ez a RAII.', 'A tartomány alapú `for (int x : v)` olvashatóbb, ha nem kell az index.', 'A `[]` nem ellenőriz határt, az `at()` kivételt dob.'],
        terms: [{ term: 'std::vector', def: 'Dinamikus tömb, ami maga kezeli a méretét és a memóriáját.' }, { term: 'RAII', def: 'Elv, amiben az erőforrás az objektum élettartamához kötődik.' }, { term: 'tartomány alapú for', def: 'Ciklus, ami index nélkül járja végig a konténert.' }],
      },
    },
    {
      day: 3,
      title: 'Osztályok és RAII',
      minutes: 24,
      lesson: [
        { k: 'text', md: 'A C++ osztálya hasonlít a Javáéra, de van benne valami, ami a Javában nincs: a **destruktor** — és ebből nő ki a nyelv legfontosabb gondolata.' },
        { k: 'code', lang: 'cpp', src: 'class Rover {\npublic:\n    Rover(std::string nev) : nev_(nev) {\n        std::cout << "létrejött\\n";\n    }\n\n    ~Rover() {\n        std::cout << "megszűnt\\n";\n    }\n\n    void halad(int cm) { akku_ -= cm / 10; }\n    int akku() const { return akku_; }\n\nprivate:\n    std::string nev_;\n    int akku_ = 100;\n};', explain: 'A `~Rover()` a destruktor: automatikusan lefut, amikor az objektum megszűnik. A kettőspont utáni rész az inicializáló lista.' },
        { k: 'callout', tone: 'key', md: 'A **RAII** ezt jelenti: az erőforrást a konstruktor szerzi meg, és a destruktor adja vissza. Fájl, memória, hálózati kapcsolat, zár — mind. Mivel a destruktor **garantáltan** lefut, amikor az objektum kimegy a hatókörből, nem lehet elfelejteni felszabadítani.' },
        { k: 'code', lang: 'cpp', src: '{\n    Rover r("Mk-I");    // "létrejött"\n    r.halad(50);\n}                       // "megszűnt" — automatikusan' },
        { k: 'callout', tone: 'tip', md: 'A `const` a metódus után (`int akku() const`) azt ígéri: ez a metódus nem módosítja az objektumot. A fordító betartatja. Tedd oda minden lekérdező metódusnál — ez a „const helyesség", és sok hibát megelőz.' },
      ],
      quiz: [
        { k: 'single', q: 'Mikor fut le a destruktor?', opts: ['Amikor meghívod', 'Amikor az objektum megszűnik vagy kimegy a hatókörből', 'A program végén'], answer: 1, why: 'A destruktor automatikus: a hatókör végén, vagy `delete`-kor fut. Nem kell és nem is szokás kézzel hívni.' },
        { k: 'single', q: 'Mit jelent a RAII?', opts: ['Gyors fordítás', 'Az erőforrást a konstruktor szerzi, a destruktor adja vissza', 'Egy könyvtár neve'], answer: 1, why: 'Resource Acquisition Is Initialization. Mivel a destruktor garantáltan lefut, az erőforrás nem maradhat felszabadítatlanul.' },
        { k: 'single', q: 'Mit ígér a `const` egy metódus után?', opts: ['A metódus gyors', 'A metódus nem módosítja az objektumot', 'A metódus privát'], answer: 1, why: 'A fordító ellenőrzi: ha a metódus mégis írna egy mezőt, fordítási hibát kapsz. Ettől lesz olvasható, mi módosít és mi nem.' },
        { k: 'output', q: 'Hány sort ír ki ez a blokk?', code: '{\n    Rover r("A");\n}', lang: 'cpp', opts: ['1', '2', '0'], answer: 1, why: 'A konstruktor kiírja, hogy „létrejött", a blokk végén pedig a destruktor azt, hogy „megszűnt" — két sor.' },
      ],
      note: {
        summary: ['A C++ osztálynak van destruktora (`~Osztaly()`), ami automatikusan lefut.', 'A destruktor a hatókör végén garantáltan lefut — ezt nem lehet elfelejteni.', 'RAII: az erőforrást a konstruktor szerzi meg, a destruktor adja vissza.', 'Az inicializáló lista (`: tag_(ertek)`) a konstruktor fejlécében adja meg a mezők kezdőértékét.', 'A metódus utáni `const` azt ígéri, hogy nem módosítja az objektumot.'],
        terms: [{ term: 'destruktor', def: 'Metódus, ami az objektum megszűnésekor automatikusan lefut.' }, { term: 'RAII', def: 'Erőforráskezelés az objektum élettartamához kötve.' }, { term: 'const metódus', def: 'Metódus, ami a fordító által ellenőrzötten nem módosítja az objektumot.' }],
      },
    },
    ...cppHuB,
    ...cppHuC,
  ],
};
