import type { Track } from '../../types';
import { javaHuB } from './java-b';

export const javaHu: Track = {
  id: 'java',
  title: 'Java',
  blurb: 'Osztályok, típusok, JVM — a nagy rendszerek nyelve.',
  plannedTitles: [
    'Az első Java program',
    'Típusok és változók',
    'Osztályok és objektumok',
    'Metódusok és paraméterek',
    'Elágazás és ciklus',
    'Tömbök',
    'String kezelése',
    'Konstruktorok',
    'Láthatóság: public és private',
    'Getter, setter, kapszulázás',
    'Statikus tagok',
    'Öröklődés',
    'Absztrakt osztály és interfész',
    'Polimorfizmus a gyakorlatban',
    'Kivételkezelés',
    'Saját kivétel',
    'Collections: List és Map',
    'Iterátor és for-each',
    'Generikusok',
    'Lambda és funkcionális interfész',
    'Stream API',
    'Fájlkezelés',
    'Csomagok és importálás',
    'Build: Maven alapok',
    'Egységtesztelés JUnittal',
    'Szálak alapjai',
    'Memória és szemétgyűjtés',
    'Hibakeresés IDE-ben',
    'Egy kisebb alkalmazás',
    'A teljes projekt',
  ],
  days: [
    {
      day: 1,
      title: 'Az első Java program',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'A Java kód nem közvetlenül a gépen fut. Előbb **bájtkóddá** fordul, és azt a **JVM** (Java Virtual Machine) hajtja végre. Ezért fut ugyanaz a program Windowson, Linuxon és Macen változtatás nélkül.' },
        { k: 'code', lang: 'java', src: 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Szia, Java!");\n    }\n}', explain: 'A fájl neve kötelezően `Hello.java` — meg kell egyeznie a publikus osztály nevével. Ez a Java egyik legszigorúbb szabálya.' },
        { k: 'text', md: 'Fordítás és futtatás:\n\n```\njavac Hello.java    → létrejön a Hello.class\njava Hello          → lefut\n```\n\nÚjabb Java-verziókon egy lépésben is megy: `java Hello.java`.' },
        { k: 'callout', tone: 'key', md: 'A `main` a belépési pont, és a szignatúrája kötelezően ez: `public static void main(String[] args)`. Ha bármit elírsz benne, a program lefordul, de nem indul el — „main method not found" hibát kapsz.' },
        { k: 'callout', tone: 'tip', md: 'A Pythonhoz képest a Java **bőbeszédű**: minden kódnak osztályban kell lennie, minden utasítás pontosvesszővel zárul, és minden változónak van típusa. Ez eleinte teher, nagy rendszerben viszont pont ez tartja kordában a káoszt.' },
      ],
      quiz: [
        { k: 'single', q: 'Mi a JVM?', opts: ['Egy szövegszerkesztő', 'A virtuális gép, ami a bájtkódot futtatja', 'A Java fordító'], answer: 1, why: 'A fordító (`javac`) bájtkódot készít, a JVM pedig ezt hajtja végre. Ez teszi a Java-programot platformfüggetlenné.' },
        { k: 'single', q: 'Hogyan kell elnevezni a fájlt, ha a publikus osztály neve `Robot`?', opts: ['robot.java', 'Robot.java', 'Mindegy'], answer: 1, why: 'A fájlnévnek pontosan egyeznie kell a publikus osztály nevével, kis- és nagybetűre is. Ellenkező esetben a fordító hibát ad.' },
        { k: 'output', q: 'Mit ír ki ez a program?', code: 'public class A {\n    public static void main(String[] args) {\n        System.out.println(2 + 3 + "x");\n    }\n}', lang: 'java', opts: ['23x', '5x', '2 + 3 + x'], answer: 1, why: 'Balról jobbra értékelődik ki: 2+3 = 5 (még szám), majd 5 + "x" szöveggé fűz: "5x".' },
        { k: 'single', q: 'Mi történik, ha elírod a `main` szignatúráját?', opts: ['Lefordul, de nem indul el', 'Nem fordul le', 'Lefut, csak lassabban'], answer: 0, why: 'A fordító nem követeli meg a main jelenlétét, de a JVM pontosan ezt a szignatúrát keresi indításkor. Ha nincs meg, „main method not found".' },
      ],
      note: {
        summary: ['A Java kód bájtkóddá fordul, amit a JVM futtat — ettől platformfüggetlen.', '`javac Hello.java` fordít, `java Hello` futtat.', 'A fájlnévnek egyeznie kell a publikus osztály nevével.', 'A belépési pont kötelező szignatúrája: `public static void main(String[] args)`.', 'Minden kód osztályban van, minden utasítás pontosvesszővel zárul.'],
        terms: [{ term: 'JVM', def: 'A virtuális gép, ami a Java bájtkódot végrehajtja.' }, { term: 'bájtkód', def: 'A forrásból fordított köztes forma, amit a JVM futtat.' }, { term: 'main metódus', def: 'A program belépési pontja, kötött szignatúrával.' }],
      },
    },
    {
      day: 2,
      title: 'Típusok és változók',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'A Java **statikusan típusos**: minden változónak megmondod a típusát, és az soha nem változik. A Pythonban `x = 5` után `x = "szia"` megengedett; Javában fordítási hiba.' },
        { k: 'code', lang: 'java', src: 'int tavolsag = 15;\ndouble suly = 2.45;\nboolean fut = true;\nchar jel = \'A\';\nString nev = "Rover";\n\nfinal int MAX = 100;      // nem módosítható', explain: 'A `String` nagy kezdőbetűs, mert osztály, nem alaptípus. A `final` azt jelenti: egyszer kap értéket, utána konstans.' },
        { k: 'text', md: 'Az **alaptípusok** (primitívek) közvetlenül értéket tárolnak: `int`, `long`, `double`, `float`, `boolean`, `char`, `byte`, `short`. Minden más **objektum**: `String`, `Integer`, a saját osztályaid.' },
        { k: 'callout', tone: 'warn', md: 'Egész osztásnál a Java is levágja a tört részt: `7 / 2` eredménye **3**, nem 3,5. Ha tizedest akarsz, legalább az egyik oldal legyen `double`: `7.0 / 2`.' },
        { k: 'callout', tone: 'key', md: 'A statikus típusosság ára, hogy többet kell gépelni. A haszna, hogy a hibák nagy része **fordításkor** derül ki, nem fél évvel később a felhasználónál. Nagy rendszerben ez az üzlet megéri.' },
      ],
      quiz: [
        { k: 'output', q: 'Mit ír ki?', code: 'int a = 7;\nint b = 2;\nSystem.out.println(a / b);', lang: 'java', opts: ['3.5', '3', '4'], answer: 1, why: 'Két egész osztása egész: a tört rész elveszik. 3,5 helyett 3-at kapsz.' },
        { k: 'single', q: 'Mit jelent a `final` egy változónál?', opts: ['Ez az utolsó változó', 'Egyszer kap értéket, utána nem módosítható', 'Automatikusan törlődik'], answer: 1, why: 'A `final` konstanssá teszi: újraértékadás fordítási hiba. Ezzel jelzed, hogy ez az érték nem fog változni.' },
        { k: 'single', q: 'Miért nagy kezdőbetűs a `String`?', opts: ['Így szép', 'Mert osztály, nem primitív alaptípus', 'Véletlen'], answer: 1, why: 'A primitívek kisbetűsek (`int`, `double`), az osztályok nagy kezdőbetűsek. A `String` objektum, ezért van nagy S-sel.' },
        { k: 'single', q: 'Mi a statikus típusosság legfőbb haszna?', opts: ['Gyorsabb futás', 'A hibák nagy része fordításkor kiderül', 'Kevesebb gépelés'], answer: 1, why: 'A fordító ellenőrzi a típusokat, mielőtt a program egyszer is lefutna. Sok hiba így soha nem jut el a felhasználóhoz.' },
      ],
      note: {
        summary: ['A Java statikusan típusos: a változó típusa rögzített és nem változhat.', 'Primitívek: int, long, double, float, boolean, char, byte, short.', 'Minden más objektum, köztük a `String` — ezért nagy kezdőbetűs.', 'Egész osztása egészet ad: `7 / 2` az 3. Tizedeshez `7.0 / 2` kell.', 'A `final` konstanssá teszi a változót.', 'A típusosság ára a gépelés, a haszna a fordításkor kiderülő hiba.'],
        terms: [{ term: 'statikus típusosság', def: 'A változó típusa fordításkor rögzített és nem változhat.' }, { term: 'primitív típus', def: 'Közvetlenül értéket tároló alaptípus, például int vagy double.' }, { term: 'final', def: 'Kulcsszó, ami a változót egyszer beállítható konstanssá teszi.' }],
      },
    },
    {
      day: 3,
      title: 'Osztályok és objektumok',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'Javában **minden** osztályban él. Nincs „szabadon álló" függvény, mint Pythonban — ezért az osztály nem haladó téma, hanem a harmadik napon jön.' },
        { k: 'code', lang: 'java', src: 'public class Rover {\n    private String nev;\n    private int akku = 100;\n\n    public Rover(String nev) {      // konstruktor\n        this.nev = nev;\n    }\n\n    public void halad(int cm) {\n        akku -= cm / 10;\n    }\n\n    public int getAkku() {\n        return akku;\n    }\n}', explain: 'A konstruktor neve megegyezik az osztályéval, és nincs visszatérési típusa. A `this.nev` a mezőt jelenti, a `nev` a paramétert.' },
        { k: 'code', lang: 'java', src: 'Rover r = new Rover("Mk-I");\nr.halad(50);\nSystem.out.println(r.getAkku());    // 95', explain: 'A `new` hozza létre a példányt, és meghívja a konstruktort. A `Rover r` a típus, az `r` a változó.' },
        { k: 'callout', tone: 'key', md: 'A `private` mezőhöz kívülről nem lehet hozzányúlni — csak a metódusokon át. Ezt hívják **kapszulázásnak**, és nem formaság: így tudod garantálni, hogy az akku sosem lesz negatív, akárki is használja az osztályodat.' },
        { k: 'callout', tone: 'warn', md: 'A `new Rover("A")` és a `new Rover("A")` **két különböző objektum**, akkor is, ha ugyanaz van bennük. Ezért ad `false`-t a `r1 == r2`. Tartalom szerinti összehasonlításhoz `equals()` kell — ez az egyik leggyakoribb Java-buktató.' },
      ],
      quiz: [
        { k: 'single', q: 'Mi jellemzi a konstruktort?', opts: ['A neve main', 'Neve az osztály neve, és nincs visszatérési típusa', 'Mindig private'], answer: 1, why: 'A konstruktor neve kötelezően az osztály neve, és nem ír ki visszatérési típust — még `void`-ot sem.' },
        { k: 'single', q: 'Mit ad `r1 == r2`, ha két külön `new Rover("A")` hívással készültek?', opts: ['true', 'false', 'Fordítási hibát'], answer: 1, why: 'A `==` két objektumnál azt nézi, ugyanaz-e a példány, nem azt, hogy egyforma-e a tartalmuk. Tartalomhoz `equals()` kell.' },
        { k: 'single', q: 'Miért tesszük `private`-ra a mezőket?', opts: ['Hogy gyorsabb legyen', 'Hogy csak a metódusokon át lehessen módosítani, és érvényes maradjon az állapot', 'Mert kötelező'], answer: 1, why: 'Ez a kapszulázás. Ha bárki közvetlenül írhatná az akkut, nem tudnád garantálni, hogy nem lesz negatív.' },
        { k: 'output', q: 'Mit ír ki?', code: 'Rover r = new Rover("X");\nr.halad(50);\nSystem.out.println(r.getAkku());', lang: 'java', opts: ['100', '95', '50'], answer: 1, why: 'A kezdeti 100-ból a `halad(50)` levon 50/10 = 5-öt, tehát 95 marad.' },
      ],
      note: {
        summary: ['Javában minden kód osztályban él; nincs szabadon álló függvény.', 'A konstruktor neve az osztály neve, és nincs visszatérési típusa.', 'A `new` hozza létre a példányt és hívja a konstruktort.', 'A `private` mező csak a metódusokon át érhető el — ez a kapszulázás.', 'A `==` objektumoknál azonosságot néz, nem tartalmat; ahhoz `equals()` kell.'],
        terms: [{ term: 'konstruktor', def: 'Az osztály nevét viselő metódus, ami a példány létrehozásakor fut.' }, { term: 'kapszulázás', def: 'Az adat elrejtése, hogy csak az osztály metódusain át legyen módosítható.' }, { term: 'this', def: 'Hivatkozás magára a példányra, a mező és a paraméter megkülönböztetésére.' }],
      },
    },
    ...javaHuB,
  ],
};
