import type { Day } from '../../types';

/** FIZIKA trek, 20–26. nap. */
export const physicsHuE: Day[] = [
  {
    day: 20,
    title: 'Elektromágnesesség',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az elektromosság és a mágnesesség **ugyanannak a jelenségnek a két oldala**. Ezt Maxwell írta le, és ebből következik minden motor, generátor és transzformátor.' },
      { k: 'callout', tone: 'key', md: 'A két alapösszefüggés:\n\n1. **Mozgó töltés mágneses mezőt kelt.** Ezért mágnes minden áramjárta vezeték.\n2. **Változó mágneses mező áramot indukál.** Ezért működik a generátor és a transzformátor.\n\nA kulcsszó a **változás**: állandó mező nem indukál semmit.' },
      { k: 'text', md: '**Faraday törvénye** szerint az indukált feszültség arányos a mágneses fluxus változási sebességével:\n\n`U = -N · ΔΦ / Δt`\n\nahol `N` a menetszám, `Φ` a fluxus. A mínusz jel **Lenz törvénye**: az indukált áram mindig az őt létrehozó változás ellen hat.' },
      { k: 'callout', tone: 'tip', md: 'Lenz törvénye szemléletesen: ejts egy erős mágnest egy rézcsövön át. Lassan fog esni, mintha mézben zuhanna. A mozgás áramot indukál a csőben, az áram mágneses mezője pedig fékezi a mágnest. Energiamegmaradás: ha gyorsítaná, örökmozgó lenne.' },
      { k: 'text', md: 'Három gyakorlati következmény:\n\n- **Transzformátor** — két tekercs közös vasmagon. A feszültség a menetszámok arányában változik, a teljesítmény (a veszteségtől eltekintve) marad.\n- **Örvényáram** — tömör fémben köröző indukált áram. Fékezéshez hasznos, trafóban veszteség; ezért lemezelt a vasmag.\n- **Indukciós fűtés** — az örvényáram melegít; így működik az indukciós főzőlap.' },
      { k: 'callout', tone: 'warn', md: 'A transzformátor **csak váltakozó árammal működik**, mert állandó mező nem indukál. Egyenáramot nem lehet transzformálni — ezért győzött annak idején a váltakozó áram a hálózati elosztásban.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi indukál feszültséget?', opts: ['Állandó mágneses mező', 'Változó mágneses mező', 'Bármilyen mágnes'], answer: 1, why: 'A kulcsszó a változás. Állandó mező mellett nem folyik indukált áram.' },
      { k: 'single', q: 'Mit mond Lenz törvénye?', opts: ['Az indukált áram erősíti a változást', 'Az indukált áram az őt létrehozó változás ellen hat', 'Nincs összefüggés'], answer: 1, why: 'Ez az energiamegmaradás következménye: ha erősítené, örökmozgó lenne.' },
      { k: 'single', q: 'Miért esik lassan egy mágnes a rézcsőben?', opts: ['A súrlódás miatt', 'Az indukált áram mágneses mezője fékezi', 'A levegő ellenállása miatt'], answer: 1, why: 'A mozgás áramot indukál a csőben, és Lenz törvénye szerint ez a mozgás ellen hat.' },
      { k: 'single', q: 'Miért lemezelt a transzformátor vasmagja?', opts: ['Olcsóbb', 'Hogy csökkentsék az örvényáramú veszteséget', 'Könnyebb'], answer: 1, why: 'Tömör vasban körözve az indukált áram hővé alakul. A lemezek megtörik ezeket a köröket.' },
      { k: 'single', q: 'Miért nem lehet egyenáramot transzformálni?', opts: ['Túl erős', 'Mert állandó mező nem indukál feszültséget', 'Mert elolvadna a tekercs'], answer: 1, why: 'Ezért győzött a váltakozó áram a hálózati elosztásban.' },
    ],
    note: {
      summary: ['Az elektromosság és a mágnesesség ugyanannak a jelenségnek két oldala.', 'Mozgó töltés mezőt kelt; változó mező áramot indukál.', 'Faraday: `U = -N · ΔΦ / Δt`.', 'Lenz: az indukált áram a változás ellen hat (energiamegmaradás).', 'Transzformátor: a feszültség a menetszámok arányában változik.', 'Örvényáram: hasznos fékezéshez, veszteség trafóban — ezért lemezelt a vasmag.', 'Egyenáramot nem lehet transzformálni.'],
      terms: [{ term: 'indukció', def: 'Feszültség keletkezése változó mágneses mező hatására.' }, { term: 'Lenz törvénye', def: 'Az indukált áram mindig az őt létrehozó változás ellen hat.' }, { term: 'örvényáram', def: 'Tömör vezetőben köröző indukált áram.' }],
    },
  },
  {
    day: 21,
    title: 'Egyenáramú motor működése',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az egyenáramú motor a legegyszerűbb elektromechanikus átalakító, és minden robot alapeleme. A működése két ismert dologból áll össze.' },
      { k: 'callout', tone: 'key', md: 'Az áramjárta vezetékre mágneses mezőben erő hat (**Lorentz-erő**), ami merőleges az áramra és a mezőre. Ha a vezeték egy tengely körül forgó hurok, ebből **nyomaték** lesz.' },
      { k: 'text', md: 'A **kommutátor** oldja meg a központi problémát: amikor a hurok félfordulatot tett, az erő iránya megfordulna, és a motor megállna. A kommutátor minden félfordulatnál megcseréli az áram irányát, így a nyomaték mindig ugyanabba az irányba hat.' },
      { k: 'code', lang: 'py', src: '# A motor két alapegyenlete\n# Nyomaték:            M = Kt * I\n# Indukált ellenfesz.: Ue = Ke * omega\n\nKt, Ke, R = 0.05, 0.05, 1.2       # Nm/A, Vs/rad, ohm\nU = 12.0\n\nfor omega in (0, 50, 100, 200):\n    I = (U - Ke*omega) / R\n    M = Kt * I\n    print(f"{omega:3} rad/s -> {I:5.2f} A, {M:5.3f} Nm")\n# 0 -> 10.00 A, 0.500 Nm   (indulási nyomaték, legnagyobb áram)\n# 200 -> 1.67 A, 0.083 Nm  (nagy fordulat, kis nyomaték)', explain: 'A kulcs az **indukált ellenfeszültség**: a forgó motor maga is generátor, és a saját feszültsége csökkenti a felvett áramot. Ezért vesz fel egy álló motor sokszoros áramot.' },
      { k: 'callout', tone: 'warn', md: 'A **blokkolt motor** a leggyakoribb meghibásodási ok. Ha a tengely nem tud forogni, nincs ellenfeszültség, és a motor a teljes `U/R` áramot felveszi — a példában tízszeresét az üzeminek. Másodpercek alatt leéghet a tekercs. Áramkorlátozás vagy hőkioldó kötelező.' },
      { k: 'text', md: 'A fordulatszám szabályozása **PWM**-mel történik: a tápfeszültséget gyorsan kapcsolgatod, és a kitöltési tényező adja az átlagos feszültséget. Azért jobb, mint az ellenállásos szabályozás, mert a kapcsoló vagy teljesen nyit, vagy teljesen zár — így alig veszít teljesítményt.' },
      { k: 'callout', tone: 'tip', md: 'Motor mellé **mindig** kell szabadonfutó dióda és rendszerint egy kondenzátor is. A dióda elvezeti a kikapcsolási feszültséglökést, a kondenzátor pedig a kefék szikrázásából származó nagyfrekvenciás zajt szűri.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi hajtja a motort?', opts: ['A hő', 'A Lorentz-erő az áramjárta vezetéken a mágneses mezőben', 'A súrlódás'], answer: 1, why: 'Az erő merőleges az áramra és a mezőre; forgó hurkon ebből nyomaték lesz.' },
      { k: 'single', q: 'Mire való a kommutátor?', opts: ['Hűt', 'Félfordulatonként megcseréli az áramirányt, hogy a nyomaték egyirányú maradjon', 'Méri a fordulatot'], answer: 1, why: 'Enélkül a motor félfordulat után megállna, mert az erő iránya megfordulna.' },
      { k: 'single', q: 'Miért vesz fel egy álló motor sokkal nagyobb áramot?', opts: ['Mert hideg', 'Mert nincs indukált ellenfeszültség, ami csökkentené', 'Mert nagyobb az ellenállása'], answer: 1, why: 'A forgó motor maga is generátor; álló állapotban a teljes `U/R` áram folyik.' },
      { k: 'single', q: 'Mi történik blokkolt motorral?', opts: ['Megáll és nem vesz fel áramot', 'A teljes `U/R` áramot felveszi, és másodpercek alatt leéghet', 'Lassan forog tovább'], answer: 1, why: 'Áramkorlátozás vagy hőkioldó nélkül ez a leggyakoribb meghibásodási ok.' },
      { k: 'single', q: 'Miért jobb a PWM az ellenállásos szabályozásnál?', opts: ['Egyszerűbb', 'A kapcsoló teljesen nyit vagy zár, ezért alig veszít teljesítményt', 'Halkabb'], answer: 1, why: 'Az ellenállás a felesleget hővé alakítja; a PWM-kapcsoló szinte semmit nem disszipál.' },
    ],
    note: {
      summary: ['A motor a Lorentz-erőn alapul: áram plusz mágneses mező nyomatékot ad.', 'A kommutátor félfordulatonként megcseréli az áramirányt.', 'Nyomaték `M = Kt · I`, ellenfeszültség `Ue = Ke · omega`.', 'A forgó motor generátorként csökkenti a felvett áramot.', 'Blokkolt motor a teljes `U/R` áramot felveszi: áramkorlát kell.', 'Fordulatszám PWM-mel, mert alig veszít teljesítményt.', 'Mindig szabadonfutó dióda és zajszűrő kondenzátor.'],
      terms: [{ term: 'kommutátor', def: 'Az áramirányt félfordulatonként megcserélő szerkezet.' }, { term: 'indukált ellenfeszültség', def: 'A forgó motor saját, az áramot csökkentő feszültsége.' }, { term: 'blokkolt állapot', def: 'A tengely nem forog, ezért maximális áram folyik.' }],
    },
  },
  {
    day: 22,
    title: 'Generátor és indukció',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A generátor **ugyanaz a gép**, mint a motor, csak fordítva használva. Ha forgatod, feszültséget ad; ha feszültséget adsz rá, forog. Ezt hívják megfordíthatóságnak.' },
      { k: 'callout', tone: 'key', md: 'Ebből következik egy nagyon hasznos gyakorlati trükk: **bármelyik egyenáramú motor használható fordulatszám-érzékelőként**. Forgatva a kivezetésein mérhető feszültség arányos a fordulatszámmal (`Ue = Ke · omega`).' },
      { k: 'text', md: 'A **regeneratív fékezés** is innen jön: amikor a robot lassít, a motor generátorrá válik, és az energiát visszatölti az akkuba. Egy elektromos autóban ez a városi menet energiájának húsz-harminc százalékát visszanyeri.' },
      { k: 'code', lang: 'py', src: '# Mennyi feszültséget ad a motor generátorként?\nKe = 0.05            # Vs/rad\n\nfor rpm in (100, 500, 1000, 3000):\n    omega = rpm * 2*3.14159 / 60\n    print(f"{rpm:4} rpm -> {Ke*omega:5.2f} V")\n# 100 -> 0.52 V   500 -> 2.62 V   1000 -> 5.24 V   3000 -> 15.71 V', explain: 'Figyeld meg: 3000 fordulaton a 12 voltos motor 15,7 voltot ad. Ezért tud egy lefelé guruló robot **túlfeszültséget** adni a vezérlőre.' },
      { k: 'callout', tone: 'warn', md: 'A **generátoros túlfeszültség** valódi veszély. Ha a robot lejtőn gurul vagy gyorsan lassítasz, a motorok visszatáplálnak, és a tápfeszültség megemelkedhet a vezérlő tűréshatára fölé. Ellenszer: **fékellenállás** (brake chopper) vagy olyan akkutöltő áramkör, ami elnyeli.' },
      { k: 'text', md: 'A váltakozó áramú generátor ugyanezen az elven működik, csak kommutátor nélkül: a forgó tekercsben szinuszosan váltakozó feszültség keletkezik. A hálózati 50 Hz pontosan ezt jelenti — a turbina másodpercenként ötvenszer fordul el a megfelelő szöggel.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a motor és a generátor viszonya?', opts: ['Két különböző gép', 'Ugyanaz a gép, fordítva használva', 'A generátor bonyolultabb'], answer: 1, why: 'Ez a megfordíthatóság: forgatva feszültséget ad, feszültségre kötve forog.' },
      { k: 'single', q: 'Hogyan használható egy motor fordulatszám-érzékelőként?', opts: ['Az áramát méred', 'A kivezetésein mért feszültség arányos a fordulatszámmal', 'A hőmérsékletét méred'], answer: 1, why: '`Ue = Ke · omega`. Ingyenes érzékelő minden motorban benne van.' },
      { k: 'single', q: 'Mi a regeneratív fékezés?', opts: ['Súrlódásos fékezés', 'A motor generátorként visszatölti az energiát az akkuba', 'Motorfék'], answer: 1, why: 'Elektromos autóban a városi menet energiájának húsz-harminc százalékát visszanyeri.' },
      { k: 'single', q: 'Miért veszélyes a lejtőn guruló robot a vezérlőre?', opts: ['Túlmelegszik', 'A motorok visszatáplálnak, és a tápfeszültség a tűréshatár fölé emelkedhet', 'Lemeríti az akkut'], answer: 1, why: 'Ellenszer a fékellenállás vagy egy elnyelő töltőáramkör.' },
      { k: 'single', q: 'Mit jelent a hálózati 50 Hz?', opts: ['50 volt', 'A generátor másodpercenként ötvenszer ad teljes szinuszperiódust', '50 amper'], answer: 1, why: 'A forgó tekercsben szinuszosan váltakozó feszültség keletkezik.' },
    ],
    note: {
      summary: ['A generátor és a motor ugyanaz a gép, fordítva használva.', 'Minden egyenáramú motor használható fordulatszám-érzékelőként.', 'Regeneratív fékezés: a motor visszatölti az energiát.', 'Nagy fordulaton a motor a névlegesnél nagyobb feszültséget ad.', 'Generátoros túlfeszültség ellen fékellenállás vagy elnyelő töltő kell.', 'A váltakozó áramú generátor ugyanez, kommutátor nélkül.'],
      terms: [{ term: 'megfordíthatóság', def: 'Ugyanaz a gép motorként és generátorként is működik.' }, { term: 'regeneratív fékezés', def: 'Fékezés, ami az energiát visszatölti.' }, { term: 'fékellenállás', def: 'A visszatáplált energiát hővé alakító ellenállás.' }],
    },
  },
  {
    day: 23,
    title: 'Hatásfok',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **hatásfok** a hasznos kimenő és a bevitt teljesítmény aránya. Soha nem 100 százalék, és a különbség mindig **hővé** válik.' },
      { k: 'callout', tone: 'key', md: '`eta = P_hasznos / P_bevitt`\n\nEgy lánc hatásfoka a tagok hatásfokának **szorzata**, nem az átlaga. Ez a legfontosabb gyakorlati következmény: négy darab 90 százalékos tag együtt már csak 66 százalék.' },
      { k: 'code', lang: 'py', src: 'lanc = {\n    "akku kisütés": 0.95,\n    "motorvezérlő": 0.90,\n    "motor":        0.80,\n    "hajtómű":      0.85,\n    "kerék-talaj":  0.90,\n}\n\neta = 1.0\nfor nev, e in lanc.items():\n    eta *= e\n    print(f"{nev:15} {e:.2f} -> összesen {eta:.3f}")\nprint(f"\\nTeljes hatásfok: {eta*100:.1f}%")\n# Teljes hatásfok: 52.3%', explain: 'Öt jónak tűnő tag együtt 52 százalék. A bevitt energia fele hővé válik — ez az, amit a hűtés tervezésénél számolni kell.' },
      { k: 'text', md: 'Tipikus hatásfokok:\n\n- **Egyenáramú motor** — 70–90 százalék a terheléstől függően\n- **Fogaskerekes hajtómű** — fokozatonként 95–98 százalék\n- **Csigahajtás** — 40–70 százalék, de önzáró\n- **Li-ion akku** — 95 százalék fölött\n- **Lineáris feszültségszabályozó** — a feszültségek arányában; 12 V-ról 5 V-ra csak 42 százalék!\n- **Kapcsolóüzemű tápegység** — 85–95 százalék' },
      { k: 'callout', tone: 'warn', md: 'A motor hatásfoka **erősen függ a terheléstől**. A csúcsa a névleges terhelés körül van; üresjáratban és blokkolt állapotban egyaránt nulla. Egy túlméretezett, kis terheléssel futó motor pazarol — nem a nagyobb a jobb.' },
      { k: 'callout', tone: 'tip', md: 'A lineáris szabályozó cseréje kapcsolóüzeműre gyakran a legnagyobb egyszerű nyereség egy robotban. 12 V-ról 5 V-ra alakítva a lineáris a bevitt energia 58 százalékát hővé alakítja — a kapcsolóüzemű csak 10 százalékát.' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan számolódik egy lánc hatásfoka?', opts: ['A tagok átlaga', 'A tagok hatásfokának szorzata', 'A legkisebb tag'], answer: 1, why: 'Négy darab 90 százalékos tag együtt már csak 66 százalék.' },
      { k: 'single', q: 'Hova lesz a hiányzó energia?', opts: ['Eltűnik', 'Hővé válik', 'Visszamegy az akkuba'], answer: 1, why: 'Ezért kell a hatásfokból számolni a hűtés igényét.' },
      { k: 'single', q: 'Mekkora egy lineáris szabályozó hatásfoka 12 V-ról 5 V-ra?', opts: ['90 százalék', 'Körülbelül 42 százalék', '100 százalék'], answer: 1, why: 'A feszültségek arányában: 5/12. A különbség teljes egészében hővé válik.' },
      { k: 'single', q: 'Mikor legjobb egy motor hatásfoka?', opts: ['Üresjáratban', 'A névleges terhelés körül', 'Blokkolt állapotban'], answer: 1, why: 'Üresjáratban és blokkolt állapotban egyaránt nulla.' },
      { k: 'single', q: 'Miért nem jó a túlméretezett motor?', opts: ['Drágább', 'Kis terheléssel rossz hatásfokon fut, tehát pazarol', 'Nehezebb'], answer: 1, why: 'A hatásfok csúcsa a névleges terhelés körül van — nem a nagyobb a jobb.' },
    ],
    note: {
      summary: ['`eta = P_hasznos / P_bevitt`; a különbség mindig hővé válik.', 'Egy lánc hatásfoka a tagok szorzata, nem az átlaga.', 'Öt darab 80-95 százalékos tag együtt már csak 52 százalék.', 'Lineáris szabályozó 12 V-ról 5 V-ra csak 42 százalék.', 'A motor hatásfoka a névleges terhelés körül a legjobb.', 'Kapcsolóüzemű tápegység a legnagyobb egyszerű nyereség.'],
      terms: [{ term: 'hatásfok', def: 'A hasznos és a bevitt teljesítmény aránya.' }, { term: 'lineáris szabályozó', def: 'A feleslegt hővé alakító feszültségszabályozó.' }, { term: 'kapcsolóüzemű tápegység', def: 'Nagy hatásfokú, kapcsolással működő feszültségátalakító.' }],
    },
  },
  {
    day: 24,
    title: 'Hőtan alapjai',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **hőmérséklet** nem ugyanaz, mint a **hő**. A hőmérséklet a részecskék átlagos mozgási energiája; a hő pedig az átadott energia mennyisége.' },
      { k: 'callout', tone: 'key', md: 'A felmelegítéshez szükséges energia:\n\n`Q = m · c · ΔT`\n\nahol `m` a tömeg, `c` a fajhő, `ΔT` a hőmérséklet-változás. A víz fajhője 4186 J/(kg·K) — kirívóan magas, ezért olyan jó hűtőközeg.' },
      { k: 'code', lang: 'py', src: '# Mennyire melegszik fel egy alumínium hűtőborda?\nc_alu = 900          # J/(kg*K)\nm = 0.05             # kg, 50 gramm\nP = 5.0              # W disszipáció\nt = 60               # s\n\ndT = (P * t) / (m * c_alu)\nprint(f"{dT:.1f} K emelkedés egy perc alatt")   # 6.7 K', explain: 'Hűtés nélkül a borda percenként közel 7 fokot melegszik. Tíz perc alatt 67 fok — ezért nem elég a tömeg, áramlás is kell.' },
      { k: 'text', md: 'A hőátadás három módja:\n\n- **Vezetés** — anyagon belül, érintkezéssel. A fém jó, a műanyag rossz vezető.\n- **Áramlás (konvekció)** — folyadék vagy gáz mozgásával. A ventilátor ezt gyorsítja fel.\n- **Sugárzás** — elektromágneses hullámmal, közeg nélkül is. Csak nagy hőmérsékleten jelentős.' },
      { k: 'callout', tone: 'warn', md: 'Egy zárt dobozban a hűtőborda **önmagában nem ér semmit**. A hőt elvezeti a chipről, de a doboz belsejében marad. A hőnek **ki kell jutnia**: szellőzőnyílás, ventilátor, vagy a hő elvezetése a doboz falához, ami kívülről hűl.' },
      { k: 'callout', tone: 'tip', md: 'A legtöbb elektronikai alkatrész **85 fokig** biztonságos, az akkuk viszont már **45 fok fölött** gyorsan öregszenek. A hőtervezésnél az akku a szűk keresztmetszet, nem a processzor — tedd a motoroktól és a vezérlőtől távol.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a különbség a hő és a hőmérséklet között?', opts: ['Nincs', 'A hőmérséklet az átlagos mozgási energia, a hő az átadott energia mennyisége', 'A hő hidegebb'], answer: 1, why: 'Egy bögre forró víz és egy fürdőkád langyos víz: utóbbiban több a hő, előbbiben nagyobb a hőmérséklet.' },
      { k: 'single', q: 'Mit mond a `Q = m · c · ΔT` képlet?', opts: ['A hőmérsékletet', 'A felmelegítéshez szükséges energiát', 'A hatásfokot'], answer: 1, why: 'A víz fajhője kirívóan magas (4186 J/kg·K), ezért olyan jó hűtőközeg.' },
      { k: 'single', q: 'Melyik a hőátadás három módja?', opts: ['Vezetés, áramlás, sugárzás', 'Vezetés, nyomás, szórás', 'Áramlás, fény, hang'], answer: 0, why: 'A sugárzás csak nagy hőmérsékleten jelentős; a robotban a vezetés és az áramlás számít.' },
      { k: 'single', q: 'Miért nem elég a hűtőborda egy zárt dobozban?', opts: ['Túl kicsi', 'Mert a hő a dobozban marad: ki is kell juttatni', 'Mert rossz anyagból van'], answer: 1, why: 'Kell szellőzőnyílás, ventilátor, vagy a hő elvezetése a kívülről hűlő dobozfalhoz.' },
      { k: 'single', q: 'Mi a szűk keresztmetszet a hőtervezésben?', opts: ['A processzor', 'Az akku, ami már 45 fok fölött gyorsan öregszik', 'A motor'], answer: 1, why: 'Az elektronika 85 fokig jellemzően biztonságos. Az akkut tedd a motoroktól távol.' },
    ],
    note: {
      summary: ['A hőmérséklet az átlagos mozgási energia, a hő az átadott energia.', '`Q = m · c · ΔT`; a víz fajhője kirívóan magas.', 'Hőátadás: vezetés, áramlás, sugárzás.', 'Zárt dobozban a hűtőborda önmagában nem elég: a hőnek ki kell jutnia.', 'Az elektronika 85 fokig bírja, az akku már 45 fok fölött öregszik.'],
      terms: [{ term: 'fajhő', def: 'Egy kilogramm anyag egy fokos melegítéséhez kellő energia.' }, { term: 'konvekció', def: 'Hőátadás gáz vagy folyadék áramlásával.' }, { term: 'hűtőborda', def: 'Nagy felületű fém, ami a hőt a környezetnek adja át.' }],
    },
  },
  {
    day: 25,
    title: 'Hővezetés és hűtés',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A hűtés tervezése ugyanolyan számítás, mint egy áramkör — csak itt a **hő** az áram, a **hőmérséklet-különbség** a feszültség, és a **hőellenállás** az ellenállás.' },
      { k: 'callout', tone: 'key', md: 'A hőtani Ohm-törvény:\n\n`ΔT = P · R_th`\n\nahol `P` a disszipált teljesítmény wattban, `R_th` a hőellenállás K/W-ban. A hőellenállások ugyanúgy **sorba adódnak**, mint az elektromosak.' },
      { k: 'code', lang: 'py', src: '# Elfér-e egy 3 wattos chip ezzel a hűtéssel?\nR_lapka_tok  = 1.5      # K/W\nR_tok_borda  = 0.5      # K/W, hővezető pasztával\nR_borda_levegő = 8.0    # K/W, kis passzív borda\n\nR_total = R_lapka_tok + R_tok_borda + R_borda_levegő\nP = 3.0\nT_kornyezet = 25\n\nprint(f"R_total = {R_total} K/W")\nprint(f"Lapkahőmérséklet: {T_kornyezet + P*R_total:.0f} C")\n# R_total = 10.0 K/W -> 55 C. Rendben, de 5 W-nál már 75 C lenne.', explain: 'A legnagyobb tag dönt: a borda-levegő átmenet 8 K/W-ja adja a lánc nagy részét. Ventilátorral ez 2 K/W-ra csökkenthető.' },
      { k: 'text', md: 'Hol lehet a legtöbbet nyerni?\n\n- **Hővezető paszta vagy pad** — a levegőrés szigetel; paszta nélkül a tok-borda átmenet akár tízszerese\n- **Nagyobb borda felület** — bordázott kivitel, nem tömör tömb\n- **Ventilátor** — a borda-levegő ellenállást a negyedére-ötödére csökkenti\n- **Hőhíd a házhoz** — a fém ház maga lesz a hűtőborda' },
      { k: 'callout', tone: 'warn', md: 'A **hővezető paszta nem ragasztó és nem is hűt**: csak a mikroszkopikus levegőréseket tölti ki. Vékonyan kend, egyenletesen. A vastag réteg **rontja** a hővezetést, mert a paszta sokkal rosszabb vezető, mint a fém érintkezés.' },
      { k: 'callout', tone: 'tip', md: 'Mérni egyszerűbb, mint számolni. Ragassz egy olcsó hőmérőt vagy NTC ellenállást a legmelegebb alkatrészre, és futtasd a robotot teljes terhelésen tíz percig. A valóság mindig többet mond a táblázatnál.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a hőtani Ohm-törvény?', opts: ['`ΔT = P · R_th`', '`P = U · I`', '`Q = m · c · ΔT`'], answer: 0, why: 'A hő az áram, a hőmérséklet-különbség a feszültség, a hőellenállás az ellenállás.' },
      { k: 'single', q: 'Hogyan adódnak össze a hőellenállások egy láncban?', opts: ['Szorzódnak', 'Sorba adódnak, mint az elektromosak', 'A legnagyobb számít csak'], answer: 1, why: 'Ezért dönt a legnagyobb tag: rendszerint a borda-levegő átmenet.' },
      { k: 'single', q: 'Mire való a hővezető paszta?', opts: ['Ragaszt', 'Kitölti a mikroszkopikus levegőréseket', 'Hűt'], answer: 1, why: 'A levegő szigetel. A paszta nem hűt, csak a réseket tölti ki.' },
      { k: 'single', q: 'Mi történik túl vastag pasztaréteggel?', opts: ['Jobban hűt', 'Rontja a hővezetést, mert a paszta rosszabb vezető a fémnél', 'Semmi'], answer: 1, why: 'Vékonyan és egyenletesen kell felvinni.' },
      { k: 'single', q: 'Mennyivel csökkenti egy ventilátor a borda-levegő hőellenállást?', opts: ['Alig', 'A negyedére-ötödére', 'Megduplázza'], answer: 1, why: 'Ez a lánc legnagyobb tagja, ezért itt lehet a legtöbbet nyerni.' },
    ],
    note: {
      summary: ['Hőtani Ohm-törvény: `ΔT = P · R_th`.', 'A hőellenállások sorba adódnak; a legnagyobb tag dönt.', 'Hővezető paszta a levegőréseket tölti ki, vékonyan.', 'Ventilátor a borda-levegő ellenállást negyedére-ötödére viszi.', 'A fém ház maga is lehet hűtőborda.', 'Mérj, ne csak számolj: hőmérő a legmelegebb alkatrészre.'],
      terms: [{ term: 'hőellenállás', def: 'K/W egységű jellemző: mennyivel melegszik wattonként.' }, { term: 'hővezető paszta', def: 'A levegőréseket kitöltő, hőt vezető anyag.' }, { term: 'hőhíd', def: 'Szándékos hővezető út a hőforrástól a hűtőfelületig.' }],
    },
  },
  {
    day: 26,
    title: 'Anyagok szilárdsága',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az alkatrész akkor jó, ha **nem törik el** és **nem hajlik el túlságosan**. Ez két külön követelmény, és gyakran a második a szigorúbb.' },
      { k: 'callout', tone: 'key', md: 'A két alapfogalom:\n\n- **Feszültség** (`sigma = F / A`) — az erő a keresztmetszetre osztva, pascalban. Ez dönti el, eltörik-e.\n- **Nyúlás** (`epsilon = ΔL / L`) — a relatív hosszváltozás, mértékegység nélkül.\n\nA kettőt a **rugalmassági modulus** köti össze: `sigma = E · epsilon` (Hooke törvénye).' },
      { k: 'text', md: 'Jellemző értékek:\n\n| Anyag | E (GPa) | Folyáshatár (MPa) |\n|---|---|---|\n| Acél | 200 | 250–900 |\n| Alumínium | 70 | 100–500 |\n| PLA (nyomtatott) | 3,5 | 50 |\n| PETG | 2,0 | 50 |\n| Szénszál kompozit | 70–200 | 600+ |' },
      { k: 'callout', tone: 'warn', md: 'Az alumínium rugalmassági modulusa az acél **harmada**. Azonos alakú alumínium alkatrész háromszor annyit hajlik, még ha nem is törik el. Ezért nem lehet egy acél alkatrészt egy az egyben alumíniumra cserélni — a geometriát is át kell tervezni.' },
      { k: 'text', md: 'A hajlítás **nem a keresztmetszettel** arányos, hanem a **másodrendű nyomatékkal**. Egy téglalap keresztmetszetnél ez `b·h³/12` — a magasság **köbösen** számít. Ezért sokkal merevebb egy élére állított léc, mint a lapjára fektetett.' },
      { k: 'callout', tone: 'tip', md: 'Ebből következik a könnyűszerkezetes tervezés fő trükkje: **vidd az anyagot a középvonaltól távolra**. Egy cső majdnem olyan merev, mint az azonos átmérőjű tömör rúd, de töredék a tömege. Ezért cső a kerékpárváz és az I alakú a tartógerenda.' },
      { k: 'callout', tone: 'warn', md: 'A **3D nyomtatott alkatrész rétegek közt a leggyengébb**: a rétegtapadás gyakran a rétegen belüli szilárdság fele. Mindig úgy tájold a darabot, hogy a terhelés a rétegek **síkjában** hasson, ne válassza szét őket.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a feszültség (sigma)?', opts: ['Az erő és a keresztmetszet hányadosa', 'A hosszváltozás', 'Az energia'], answer: 0, why: 'Pascalban mérve. Ez dönti el, hogy az anyag eltörik-e.' },
      { k: 'single', q: 'Mit mond Hooke törvénye?', opts: ['`sigma = E · epsilon`', '`F = m · a`', '`Q = m · c · ΔT`'], answer: 0, why: 'A feszültség arányos a nyúlással, az arányossági tényező a rugalmassági modulus.' },
      { k: 'single', q: 'Mennyivel hajlik többet egy azonos alakú alumínium alkatrész az acélhoz képest?', opts: ['Ugyanannyit', 'Körülbelül háromszor annyit', 'Felét'], answer: 1, why: 'Az alumínium E modulusa 70 GPa, az acélé 200 GPa.' },
      { k: 'single', q: 'Hogyan függ a hajlítási merevség a magasságtól?', opts: ['Egyenesen arányosan', 'A köbével', 'A négyzetgyökével'], answer: 1, why: 'A másodrendű nyomaték `b·h³/12`. Ezért merevebb az élére állított léc.' },
      { k: 'single', q: 'Hogyan tájold a 3D nyomtatott alkatrészt?', opts: ['Mindegy', 'Úgy, hogy a terhelés a rétegek síkjában hasson', 'Mindig függőlegesen'], answer: 1, why: 'A rétegtapadás gyakran fele a rétegen belüli szilárdságnak.' },
    ],
    note: {
      summary: ['Két követelmény: ne törjön el és ne hajoljon túl sokat.', 'Feszültség `sigma = F/A`, nyúlás `epsilon = ΔL/L`.', 'Hooke: `sigma = E · epsilon`.', 'Alumínium E modulusa az acél harmada: háromszor annyit hajlik.', 'A hajlítási merevség a magasság köbével nő.', 'Vidd az anyagot a középvonaltól távolra: cső, I gerenda.', 'Nyomtatott alkatrésznél a terhelés a rétegek síkjában hasson.'],
      terms: [{ term: 'rugalmassági modulus (E)', def: 'Az anyag merevségét jellemző szám, GPa-ban.' }, { term: 'folyáshatár', def: 'Az a feszültség, ami fölött az anyag maradandóan deformálódik.' }, { term: 'másodrendű nyomaték', def: 'A keresztmetszet alakjából adódó hajlítási merevség.' }],
    },
  },
];
