import type { Track } from '../../types';
import { physicsHuB } from './physics-b';

export const physicsHu: Track = {
  id: 'physics',
  title: 'Fizika',
  blurb: 'Mechanika, energia, elektromosság, mágnesesség — robotos szemmel.',
  plannedTitles: [
    'Mértékegységek és vektorok',
    'Sebesség és gyorsulás',
    'Newton törvényei',
    'Munka és energia',
    'Nyomaték',
    'Forgómozgás',
    'Impulzus és ütközés',
    'Súrlódás',
    'Rugók és rezgés',
    'Csillapítás',
    'Lejtő és gépek',
    'Nyomás és folyadékok',
    'Közegellenállás',
    'Töltés és feszültség',
    'Áram és Ohm törvénye',
    'Soros és párhuzamos kapcsolás',
    'Teljesítmény és hő',
    'Kondenzátor',
    'Mágneses mező',
    'Elektromágnesesség',
    'Egyenáramú motor működése',
    'Generátor és indukció',
    'Hatásfok',
    'Hőtan alapjai',
    'Hővezetés és hűtés',
    'Anyagok szilárdsága',
    'Feszültség és alakváltozás',
    'Hullámok és hang',
    'Fény és optika',
    'A fizika a robotodban',
  ],
  days: [
    {
      day: 1,
      title: 'Mértékegységek és vektorok',
      minutes: 20,
      lesson: [
        {
          k: 'text',
          md: 'A fizikában minden szám mögött ott áll egy **mértékegység**. A "12" önmagában semmit nem jelent. A "12 cm", a "12 kg" és a "12 V" három teljesen különböző állítás.',
        },
        {
          k: 'callout',
          tone: 'key',
          md: 'A NASA 1999-ben elvesztett egy Mars-szondát, mert az egyik csapat fontban, a másik newtonban számolt. A mértékegység nem formaság.',
        },
        {
          k: 'text',
          md: 'Az SI alapegységek, amikre szükséged lesz:\n\n- hossz: **méter** (m)\n- tömeg: **kilogramm** (kg)\n- idő: **másodperc** (s)\n- áram: **amper** (A)\n\nEbből származik minden más: a sebesség m/s, az erő N = kg·m/s², a feszültség V = W/A.',
        },
        {
          k: 'formula',
          tex: 'v = \\frac{s}{t}',
          explain: 'A sebesség a megtett út osztva az eltelt idővel. Ha az út méterben, az idő másodpercben van, a sebesség m/s-ban jön ki. A mértékegységek végigkövetése a legjobb hibaellenőrzés, amit ingyen kapsz.',
        },
        {
          k: 'text',
          md: 'Egyes mennyiségeknek csak nagyságuk van: a tömeg 3 kg, és kész. Ezek a **skalárok**. Másoknak iránya is van: ha a robot 5 cm/s-mal megy, az nem ugyanaz, mintha visszafelé menne. Ezek a **vektorok**.',
        },
        {
          k: 'text',
          md: 'Vektor például: elmozdulás, sebesség, gyorsulás, erő.\nSkalár például: tömeg, idő, hőmérséklet, energia.',
        },
        {
          k: 'callout',
          tone: 'tip',
          md: 'A robotodnál a vektor általában két számot jelent: x és y irányú összetevőt. A rover pozíciója (x, z), a sebessége pedig az az irány, amerre éppen néz.',
        },
        { k: 'sim', sim: 'projectile' },
        {
          k: 'text',
          md: 'Ez a szimuláció a következő napokban lesz igazán érdekes — most csak annyit nézz meg rajta, hogy a kezdősebesség **iránya** (a szög) legalább annyira számít, mint a nagysága. Ez a vektor lényege.',
        },
      ],
      quiz: [
        {
          k: 'single',
          q: 'Melyik mennyiség vektor?',
          opts: ['Tömeg', 'Hőmérséklet', 'Sebesség'],
          answer: 2,
          why: 'A sebességnek nagysága és iránya is van — 5 m/s előre és 5 m/s hátra nem ugyanaz. A tömeg és a hőmérséklet skalár: nincs irányuk.',
        },
        {
          k: 'numeric',
          q: 'A robot 3 másodperc alatt 60 cm-t tesz meg. Mekkora az átlagsebessége cm/s-ban?',
          answer: 20,
          tol: 0.1,
          unit: 'cm/s',
          why: 'v = s / t = 60 cm / 3 s = 20 cm/s. Figyeld meg, hogy a mértékegység is "osztódik": cm / s = cm/s.',
        },
        {
          k: 'single',
          q: 'Mi az erő SI mértékegysége?',
          opts: ['Newton (N)', 'Joule (J)', 'Watt (W)'],
          answer: 0,
          why: 'Az erő newtonban mérjük: 1 N = 1 kg·m/s². A joule energia, a watt teljesítmény — ezek a következő hetekben jönnek.',
        },
        {
          k: 'multi',
          q: 'Melyik kettő skalár mennyiség?',
          opts: ['Elmozdulás', 'Tömeg', 'Erő', 'Energia'],
          answers: [1, 3],
          why: 'A tömegnek és az energiának nincs iránya, csak nagysága. Az elmozdulás és az erő viszont vektor: számít, merre.',
        },
      ],
      note: {
        summary: [
          'Minden fizikai szám mögött mértékegység áll; szám önmagában értelmetlen.',
          'SI alapegységek: méter, kilogramm, másodperc, amper. Minden más ezekből származik.',
          'A sebesség v = s/t, és a mértékegységei is osztódnak: m / s = m/s.',
          'Skalár = csak nagyság (tömeg, idő, energia). Vektor = nagyság és irány (sebesség, erő, elmozdulás).',
          'A mértékegységek végigkövetése ingyenes hibaellenőrzés: ha nem jön ki a helyes egység, elszámoltad.',
        ],
        terms: [
          { term: 'mértékegység', def: 'Az a viszonyítási mennyiség, amihez képest a számot értjük.' },
          { term: 'skalár', def: 'Olyan mennyiség, aminek csak nagysága van.' },
          { term: 'vektor', def: 'Olyan mennyiség, aminek nagysága és iránya is van.' },
          { term: 'newton', def: 'Az erő SI egysége: 1 N = 1 kg·m/s².' },
        ],
        formulas: [{ tex: 'v = s / t', meaning: 'Átlagsebesség: a megtett út osztva az eltelt idővel.' }],
      },
    },
    ...physicsHuB,
  ],
};
