import type { Day } from '../../types';

/** FIZIKA trek, 13–19. nap. */
export const physicsHuD: Day[] = [
  {
    day: 13,
    title: 'Közegellenállás',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A levegő és a víz ellenáll a mozgásnak. Kis sebességnél ez elhanyagolható, nagynál viszont **ez szabja meg a végsebességet** — nem a motor ereje.' },
      { k: 'callout', tone: 'key', md: 'A közegellenállási erő nagyobb sebességnél **a sebesség négyzetével** nő:\n\n`F = ½ · ρ · v² · C · A`\n\nahol `ρ` a közeg sűrűsége, `v` a sebesség, `C` az alaktényező, `A` a homlokfelület.' },
      { k: 'text', md: 'A négyzetes tag a lényeg. **Kétszeres sebességnél négyszeres ellenállás** — és mivel a teljesítmény erő szorozva sebességgel, **nyolcszoros teljesítmény** kell hozzá. Ezért nem lesz egy autó kétszer olyan gyors kétszer akkora motortól.' },
      { k: 'code', lang: 'py', src: 'rho, C, A = 1.225, 0.9, 0.05     # levegő, szögletes robot, 500 cm2\n\ndef ellenallas(v):\n    return 0.5 * rho * v*v * C * A\n\nfor v in (1, 2, 4, 8):\n    print(v, "m/s ->", round(ellenallas(v), 3), "N")\n# 1 -> 0.028   2 -> 0.110   4 -> 0.441   8 -> 1.764', explain: 'Nyolcszoros sebesség, 64-szeres erő. Egy lassú roboton az ellenállás elhanyagolható; egy drónon már minden.' },
      { k: 'callout', tone: 'tip', md: 'A `C` alaktényező nagyon különböző: lapos lemez ≈ 1,2; gömb ≈ 0,47; csepp alak ≈ 0,04. A **hátsó rész** alakja fontosabb az elsőnél: ott válik le az áramlás, és ott keletkezik a szívóhatás.' },
      { k: 'text', md: 'A **végsebesség** akkor áll be, amikor a hajtóerő egyenlő az ellenállással. Innentől nincs gyorsulás. Egy szabadeső tárgynál ugyanez: a súly és a közegellenállás kiegyenlíti egymást, és a sebesség állandó marad.' },
      { k: 'callout', tone: 'warn', md: 'Nagyon kis sebességnél vagy nagyon kis tárgynál az ellenállás **lineáris**, nem négyzetes (Stokes-törvény). Egy porszem vagy egy mikrorobot egészen más világban mozog, mint egy autó.' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan függ a közegellenállás a sebességtől nagy sebességnél?', opts: ['Egyenesen arányos', 'A négyzetével arányos', 'Nem függ tőle'], answer: 1, why: 'Kétszeres sebesség négyszeres ellenállást jelent. Ez a legfontosabb gyakorlati következmény.' },
      { k: 'single', q: 'Hányszoros teljesítmény kell kétszeres sebességhez?', opts: ['Kétszeres', 'Négyszeres', 'Nyolcszoros'], answer: 2, why: 'Négyszeres erő, kétszeres sebesség: a teljesítmény erő szorozva sebességgel, tehát nyolcszoros.' },
      { k: 'single', q: 'Melyik rész alakja fontosabb az áramvonalazásnál?', opts: ['Az eleje', 'A hátulja, ahol az áramlás leválik', 'Mindegy'], answer: 1, why: 'A leválásnál keletkező örvény és szívóhatás adja az ellenállás nagy részét.' },
      { k: 'single', q: 'Mikor áll be a végsebesség?', opts: ['Amikor elfogy az üzemanyag', 'Amikor a hajtóerő egyenlő az ellenállással', 'Soha'], answer: 1, why: 'Ekkor az eredő erő nulla, tehát a gyorsulás is nulla, és a sebesség állandó marad.' },
      { k: 'single', q: 'Mi igaz nagyon kicsi tárgyak nagyon kis sebességére?', opts: ['Az ellenállás lineáris, nem négyzetes', 'Nincs ellenállás', 'Az ellenállás köbös'], answer: 0, why: 'Ez a Stokes-tartomány. Egy porszem vagy mikrorobot egészen más szabályok szerint mozog.' },
    ],
    note: {
      summary: ['`F = ½ · ρ · v² · C · A` — a közegellenállás képlete.', 'Nagy sebességnél az ellenállás a sebesség négyzetével nő.', 'Kétszeres sebességhez nyolcszoros teljesítmény kell.', 'Az alaktényező: lapos lemez 1,2; gömb 0,47; csepp 0,04.', 'A hátsó alak fontosabb az elsőnél: ott válik le az áramlás.', 'Végsebesség: amikor a hajtóerő egyenlő az ellenállással.', 'Nagyon kis tárgyaknál az ellenállás lineáris (Stokes).'],
      terms: [{ term: 'alaktényező (C)', def: 'Dimenziótlan szám, ami a forma áramlástani jóságát méri.' }, { term: 'homlokfelület', def: 'A mozgás irányára merőleges vetített terület.' }, { term: 'végsebesség', def: 'Az a sebesség, ahol a hajtóerő és az ellenállás kiegyenlíti egymást.' }],
    },
  },
  {
    day: 14,
    title: 'Töltés és feszültség',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az elektromosság alapja a **töltés**. Kétféle van, vonzzák az ellentéteseket és taszítják az azonosakat. Mértékegysége a **coulomb (C)**; egy elektron töltése 1,6 × 10⁻¹⁹ C.' },
      { k: 'callout', tone: 'key', md: 'A **feszültség** (volt) nem „elektromosság mennyisége", hanem **energiakülönbség töltésegységenként**:\n\n`1 V = 1 J / 1 C`\n\nAzaz: egy coulomb töltés egy volt feszültségkülönbségen áthaladva egy joule munkát végez.' },
      { k: 'text', md: 'A legjobb kép a magasság. A feszültség olyan, mint a **szintkülönbség**: nem az számít, hol vagy, hanem mekkora a különbség. Ezért van értelme a „föld" fogalmának — valahol fel kell venni a nullát.' },
      { k: 'callout', tone: 'warn', md: 'Ezért mondjuk, hogy „a feszültség mindig **két pont között** van". Egyetlen pont feszültségéről beszélni értelmetlen, ahogy egy pont magasságáról is csak valamihez képest lehet.' },
      { k: 'text', md: 'Gyakori feszültségek a robotikában:\n\n- Logikai áramkörök: **3,3 V** vagy **5 V**\n- Li-ion cella: **3,7 V** névleges (4,2 V telve, 3,0 V üresen)\n- Szervók és kisebb motorok: **6–12 V**\n- Nagyobb hajtások: **24 V** vagy **48 V**' },
      { k: 'callout', tone: 'tip', md: 'A **test számára nem a feszültség veszélyes önmagában, hanem az áram**. Egy 9 V-os elem ártalmatlan, mert a bőr ellenállása mellett alig folyik áram. Ugyanakkor 50 V fölött már vigyázz, és hálózati feszültséggel soha ne kísérletezz.' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent az, hogy 1 volt?', opts: ['1 amper áram', '1 joule energia coulombonként', '1 ohm ellenállás'], answer: 1, why: 'A feszültség energiakülönbség töltésegységenként. Ebből következik minden további összefüggés.' },
      { k: 'single', q: 'Miért beszélünk mindig feszültségkülönbségről?', opts: ['Hagyomány', 'Mert a feszültség két pont viszonya, mint a szintkülönbség', 'Mert nehéz mérni'], answer: 1, why: 'Egyetlen pont feszültsége önmagában értelmetlen, ahogy egy pont magassága is csak valamihez képest van.' },
      { k: 'single', q: 'Mennyi egy Li-ion cella névleges feszültsége?', opts: ['1,5 V', '3,7 V', '12 V'], answer: 1, why: 'Telve 4,2 V, üresen 3,0 V körül. A névleges érték a köztes átlag.' },
      { k: 'single', q: 'Mi veszélyes elsősorban az emberi testre?', opts: ['A feszültség önmagában', 'Az áram', 'A töltés mennyisége'], answer: 1, why: 'Egy 9 V-os elem ártalmatlan, mert a bőr ellenállása mellett alig folyik áram.' },
      { k: 'single', q: 'Mi a töltés mértékegysége?', opts: ['Volt', 'Coulomb', 'Watt'], answer: 1, why: 'Egy elektron töltése 1,6 × 10⁻¹⁹ coulomb.' },
    ],
    note: {
      summary: ['A töltés mértékegysége a coulomb; az elektroné 1,6 × 10⁻¹⁹ C.', '1 V = 1 J / 1 C: energiakülönbség töltésegységenként.', 'A feszültség mindig két pont között értelmezhető, mint a szintkülönbség.', 'Tipikus értékek: logika 3,3/5 V, Li-ion 3,7 V, motorok 6–48 V.', 'A testre az áram veszélyes, nem a feszültség önmagában.'],
      terms: [{ term: 'töltés', def: 'Az elektromos kölcsönhatás alapmennyisége, coulombban.' }, { term: 'feszültség', def: 'Energiakülönbség töltésegységenként, két pont között.' }, { term: 'föld (referencia)', def: 'A nullának választott pont, amihez a feszültséget mérjük.' }],
    },
  },
  {
    day: 15,
    title: 'Áram és Ohm törvénye',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az **áram** a töltés áramlása: hány coulomb halad át egy keresztmetszeten másodpercenként. Mértékegysége az **amper**: 1 A = 1 C/s.' },
      { k: 'callout', tone: 'key', md: '**Ohm törvénye** köti össze a hármat:\n\n`U = I · R`\n\nFeszültség = áram × ellenállás. Ebből bármelyik kettőből kiszámolható a harmadik, és ez a teljes egyenáramú áramkörszámítás alapja.' },
      { k: 'text', md: 'A vízvezetékes kép nagyon jól működik:\n\n- **feszültség** → nyomás\n- **áram** → átfolyó vízmennyiség\n- **ellenállás** → a cső szűkülete\n\nNagyobb nyomás több vizet hajt át; szűkebb cső kevesebbet.' },
      { k: 'code', lang: 'py', src: '# Előtét-ellenállás egy LED-hez\nU_tap = 5.0        # V\nU_led = 2.0        # V, vörös LED nyitófeszültsége\nI_cel = 0.015      # A, 15 mA\n\nR = (U_tap - U_led) / I_cel\nprint(round(R), "ohm")        # 200 ohm -> a legközelebbi szabvány: 220\n\nP = (U_tap - U_led) * I_cel\nprint(round(P, 3), "W")       # 0.045 W -> egy 0,25 W-os ellenállás bőven elég', explain: 'A LED-re eső feszültség adott; a maradékot az ellenállásnak kell elnyelnie. Mindig a nagyobb szabványos értéket válaszd — a kisebb áram biztonságosabb.' },
      { k: 'callout', tone: 'warn', md: 'A LED **nem ohmos** alkatrész: nincs állandó ellenállása, hanem majdnem fix feszültségen nyit. Előtét-ellenállás nélkül az áram korlátlanul nő, és a LED pillanatok alatt kiég. Ez a leggyakoribb kezdő hiba az elektronikában.' },
      { k: 'text', md: 'Nem minden alkatrész követi Ohm törvényét. **Ohmos**: ellenállás, vezeték, fűtőszál. **Nem ohmos**: dióda, LED, tranzisztor, izzó (mert a hőmérséklettel változik az ellenállása).' },
    ],
    quiz: [
      { k: 'single', q: 'Mit jelent 1 amper?', opts: ['1 volt / 1 ohm', '1 coulomb másodpercenként', '1 joule'], answer: 1, why: 'Az áram a töltés áramlási sebessége: coulomb per másodperc.' },
      { k: 'single', q: 'Mi Ohm törvénye?', opts: ['`U = I · R`', '`P = U · I`', '`F = m · a`'], answer: 0, why: 'Feszültség = áram × ellenállás. Ebből a teljes egyenáramú számítás levezethető.' },
      { k: 'single', q: 'Miért kell előtét-ellenállás a LED-hez?', opts: ['Hogy világosabb legyen', 'Mert a LED nem ohmos: korlátozás nélkül az áram elszalad és kiég', 'Hogy ne villogjon'], answer: 1, why: 'A LED majdnem fix feszültségen nyit. Az áramot külön kell korlátozni.' },
      { k: 'single', q: '5 V tápról egy 2 V-os LED-et 15 mA-rel hajtva mekkora ellenállás kell?', opts: ['100 ohm', '200 ohm', '470 ohm'], answer: 1, why: '(5 − 2) / 0,015 = 200 ohm. A gyakorlatban a következő szabványos érték, 220 ohm.' },
      { k: 'single', q: 'Melyik alkatrész NEM ohmos?', opts: ['Ellenállás', 'Dióda', 'Rézvezeték'], answer: 1, why: 'A dióda és a LED nem lineáris: az áram a feszültséggel exponenciálisan nő.' },
    ],
    note: {
      summary: ['Áram: töltés áramlása, 1 A = 1 C/s.', 'Ohm törvénye: `U = I · R`.', 'Vízvezetékes kép: feszültség a nyomás, áram az átfolyás, ellenállás a szűkület.', 'LED-hez mindig kell előtét-ellenállás, mert nem ohmos.', 'Előtét számítása: `R = (U_táp − U_LED) / I_cél`.', 'Nem ohmos: dióda, LED, tranzisztor, izzó.'],
      terms: [{ term: 'amper', def: 'Az áram mértékegysége: coulomb per másodperc.' }, { term: 'Ohm törvénye', def: '`U = I · R`, az egyenáramú számítás alapja.' }, { term: 'előtét-ellenállás', def: 'Áramkorlátozó ellenállás egy nem ohmos alkatrész mellett.' }],
    },
  },
  {
    day: 16,
    title: 'Soros és párhuzamos kapcsolás',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Két alapkapcsolás van, és minden bonyolult áramkör ezekből épül. A különbségük egyetlen kérdés: **mi közös bennük** — az áram vagy a feszültség?' },
      { k: 'callout', tone: 'key', md: '**Soros**: egyetlen út, tehát **az áram közös**. A feszültség megoszlik.\n\n`R_eredő = R₁ + R₂ + ...`\n\n**Párhuzamos**: több út, tehát **a feszültség közös**. Az áram megoszlik.\n\n`1/R_eredő = 1/R₁ + 1/R₂ + ...`' },
      { k: 'text', md: 'Két fontos következmény:\n\n- Sorosan az **eredő mindig nagyobb** a legnagyobb tagnál.\n- Párhuzamosan az **eredő mindig kisebb** a legkisebb tagnál.\n\nHa ezt az eredményed nem teljesíti, elszámoltad.' },
      { k: 'code', lang: 'py', src: 'def soros(*r):\n    return sum(r)\n\ndef parhuzamos(*r):\n    return 1 / sum(1/x for x in r)\n\nprint(soros(100, 220))          # 320 ohm\nprint(parhuzamos(100, 100))     # 50.0 ohm  -- két egyforma: a fele\nprint(parhuzamos(100, 1000))    # 90.9 ohm  -- a kisebbhez közeli', explain: 'Két egyforma ellenállás párhuzamosan a felét adja. Ha az egyik sokkal nagyobb, az eredő szinte pontosan a kisebb.' },
      { k: 'callout', tone: 'warn', md: 'A **feszültségosztó** a soros kapcsolás leggyakoribb alkalmazása:\n\n`U_ki = U_be · R₂ / (R₁ + R₂)`\n\nDe csak akkor pontos, ha **terheletlen**. Amint a kimenetre terhelést kötsz, az párhuzamos lesz `R₂`-vel, és a feszültség leesik. Ezért nem lehet feszültségosztóval tápot csinálni.' },
      { k: 'text', md: 'A gyakorlatban: a **LED-ek sorosan** azonos áramot kapnak (ezért egyforma a fényük), **párhuzamosan** viszont a kis gyártási eltérések miatt nem egyformán világítanak. Ezért kap minden ágban külön előtét-ellenállást.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi közös a soros kapcsolásban?', opts: ['A feszültség', 'Az áram', 'Az ellenállás'], answer: 1, why: 'Egyetlen út van, tehát ugyanaz az áram folyik minden tagon. A feszültség oszlik meg.' },
      { k: 'single', q: 'Mekkora két 100 ohmos ellenállás eredője párhuzamosan?', opts: ['200 ohm', '50 ohm', '100 ohm'], answer: 1, why: 'Két egyforma ellenállás párhuzamosan a felét adja.' },
      { k: 'single', q: 'Mi igaz a párhuzamos eredőre?', opts: ['Mindig nagyobb a legnagyobb tagnál', 'Mindig kisebb a legkisebb tagnál', 'A tagok átlaga'], answer: 1, why: 'Ez jó ellenőrzés: ha nem így jött ki, elszámoltad.' },
      { k: 'single', q: 'Miért nem lehet feszültségosztóval tápot csinálni?', opts: ['Túl drága', 'Mert terhelés hatására a kimeneti feszültség leesik', 'Mert melegszik'], answer: 1, why: 'A terhelés párhuzamos lesz az alsó ellenállással, és megváltoztatja az osztási arányt.' },
      { k: 'single', q: 'Miért kap minden párhuzamos LED külön előtét-ellenállást?', opts: ['Hogy szebb legyen', 'Mert a gyártási eltérések miatt másképp osztoznának az áramon', 'Hogy olcsóbb legyen'], answer: 1, why: 'A kisebb nyitófeszültségű LED többet venne fel, fényesebb lenne, és hamarabb kiégne.' },
    ],
    note: {
      summary: ['Soros: közös áram, az eredő `R₁ + R₂`.', 'Párhuzamos: közös feszültség, `1/R = 1/R₁ + 1/R₂`.', 'Soros eredő nagyobb a legnagyobb tagnál; párhuzamos kisebb a legkisebbnél.', 'Két egyforma párhuzamosan a felét adja.', 'Feszültségosztó: `U_ki = U_be · R₂/(R₁+R₂)`, csak terheletlenül pontos.', 'Párhuzamos LED-ekhez ágankénti előtét kell.'],
      terms: [{ term: 'soros kapcsolás', def: 'Egyetlen út; az áram közös, a feszültség oszlik.' }, { term: 'párhuzamos kapcsolás', def: 'Több út; a feszültség közös, az áram oszlik.' }, { term: 'feszültségosztó', def: 'Soros ellenálláspár, aminek a középpontja arányos feszültséget ad.' }],
    },
  },
  {
    day: 17,
    title: 'Teljesítmény és hő',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Az elektromos **teljesítmény** azt mondja meg, milyen gyorsan alakul át az energia. Ellenálláson ez teljes egészében hővé válik — ezért melegszik minden áramkör.' },
      { k: 'callout', tone: 'key', md: 'A három alak ugyanarra:\n\n`P = U · I`\n`P = I² · R`\n`P = U² / R`\n\nMindig azt használd, amelyikhez megvan a két ismert mennyiséged.' },
      { k: 'text', md: 'Az `I² · R` alak a legtanulságosabb: a hő **az áram négyzetével** nő. Kétszeres áram négyszeres melegedést jelent. Ezért van az, hogy egy vezeték, ami 5 A-nél langyos, 10 A-nél már leolvad.' },
      { k: 'code', lang: 'py', src: '# Mennyit veszít a vezeték?\nR_vezetek = 0.05      # ohm, 2 m vékony kábel\n\nfor I in (1, 5, 10, 20):\n    P = I*I * R_vezetek\n    print(I, "A ->", round(P, 2), "W veszteség")\n# 1 -> 0.05   5 -> 1.25   10 -> 5.0   20 -> 20.0', explain: 'Húsz amperen már 20 watt hő keletkezik két méter kábelben. Ennyi egy forrasztópáka teljesítménye — ezért kell vastagabb vezeték nagy áramhoz.' },
      { k: 'callout', tone: 'warn', md: 'Minden ellenállásnak van **teljesítménykorlátja**: a szokásos kicsi 0,25 W. Ha ennél többet disszipál, előbb megbarnul, aztán kiég. Mindig számold ki a disszipációt, és válassz legalább kétszeres tartalékkal.' },
      { k: 'text', md: 'Nagy áramnál két megoldás van: **vastagabb vezeték** (kisebb R) vagy **nagyobb feszültség** (ugyanaz a teljesítmény kisebb árammal). Ezért megy a nagyfeszültség a távvezetéken, és ezért váltanak a robotok is 24 V-ra vagy 48 V-ra a nagyobb hajtásoknál.' },
      { k: 'callout', tone: 'tip', md: 'Az akku kapacitása **amperórában (Ah)** van, az energiája viszont **wattórában (Wh)**: `Wh = Ah · V`. Két akkut csak wattórában érdemes összehasonlítani — egy 5 Ah-s 3,7 V-os cella (18,5 Wh) jóval kevesebb, mint egy 3 Ah-s 12 V-os (36 Wh).' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan függ a hővé váló teljesítmény az áramtól?', opts: ['Egyenesen arányos', 'A négyzetével', 'Nem függ tőle'], answer: 1, why: '`P = I² · R`. Kétszeres áram négyszeres melegedést jelent.' },
      { k: 'single', q: 'Melyik képlettel számolsz, ha az áramot és az ellenállást ismered?', opts: ['`P = U · I`', '`P = I² · R`', '`P = U² / R`'], answer: 1, why: 'Mindig azt az alakot válaszd, amelyikhez megvan a két ismert mennyiséged.' },
      { k: 'single', q: 'Mi történik egy 0,25 W-os ellenállással, ha 1 W-ot disszipál?', opts: ['Semmi', 'Megbarnul, majd kiég', 'Hatékonyabb lesz'], answer: 1, why: 'A teljesítménykorlát a megengedett hődisszipáció. Mindig legalább kétszeres tartalékkal válassz.' },
      { k: 'single', q: 'Miért viszik a villamos energiát nagyfeszültségen?', opts: ['Olcsóbb a vezeték', 'Mert ugyanaz a teljesítmény kisebb árammal megy, és a veszteség az áram négyzetével nő', 'Mert gyorsabb'], answer: 1, why: 'Tízszeres feszültségnél tizedakkora áram, és így századannyi vezetékveszteség.' },
      { k: 'single', q: 'Melyik akku tárol több energiát: 5 Ah / 3,7 V vagy 3 Ah / 12 V?', opts: ['Az első', 'A második', 'Egyforma'], answer: 1, why: '18,5 Wh szemben 36 Wh-val. Az amperóra önmagában nem összehasonlítható eltérő feszültségnél.' },
    ],
    note: {
      summary: ['`P = U · I = I² · R = U² / R`.', 'A hő az áram négyzetével nő: kétszeres áram, négyszeres melegedés.', 'Minden ellenállásnak van teljesítménykorlátja; a kicsi 0,25 W.', 'Nagy áramnál vastagabb vezeték vagy nagyobb feszültség a megoldás.', 'Az akkukat wattórában hasonlítsd össze: `Wh = Ah · V`.'],
      terms: [{ term: 'disszipáció', def: 'Hővé alakuló elektromos teljesítmény.' }, { term: 'teljesítménykorlát', def: 'Az alkatrész által még elviselt hődisszipáció.' }, { term: 'wattóra', def: 'Energiaegység: a kapacitás és a feszültség szorzata.' }],
    },
  },
  {
    day: 18,
    title: 'Kondenzátor',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **kondenzátor** két vezető lemez szigetelővel elválasztva. Töltést tárol, és ezzel **feszültséget tart** — de csak rövid ideig. Nem akkumulátor: kevesebb energiát tárol, viszont nagyon gyorsan adja és veszi.' },
      { k: 'callout', tone: 'key', md: 'Az alapösszefüggés:\n\n`Q = C · U`\n\nahol `Q` a tárolt töltés (coulomb), `C` a kapacitás (farad), `U` a feszültség. A tárolt energia pedig `E = ½ · C · U²`.' },
      { k: 'text', md: 'Az `U²` tag fontos: **kétszeres feszültségen négyszer annyi energia** fér bele. Ezért éri meg a kondenzátort a lehető legnagyobb biztonságos feszültségen használni.' },
      { k: 'code', lang: 'py', src: 'C = 1000e-6        # 1000 uF\nU = 12.0\n\nQ = C * U\nE = 0.5 * C * U*U\nprint(round(Q, 4), "C")      # 0.012 coulomb\nprint(round(E, 4), "J")      # 0.072 joule\n\n# Feltoltesi idoallando egy ellenallason at\nR = 1000           # ohm\nprint(R * C, "s")            # 1.0 s -> 5 tau mulva ~ teljesen tolt', explain: 'A `tau = R · C` időállandó: ennyi idő alatt tölt fel a végérték 63 százalékára. Öt időállandó után gyakorlatilag teljesen feltöltődött.' },
      { k: 'callout', tone: 'warn', md: 'Az **elektrolit kondenzátor polaritásos**: a hosszabb láb a pozitív. Fordítva bekötve felforrósodik és felrobban. Ez nem túlzás — a műanyag burkolat felszakad és az elektrolit kiszökik.' },
      { k: 'text', md: 'Mire használod a gyakorlatban?\n\n- **Szűrés** — a táp zajának elsimítása. Minden IC mellé 100 nF.\n- **Puffer** — nagy áramlökés elnyelése, például motorinduláskor.\n- **Időzítés** — RC tag késleltetéshez, szűrőhöz.\n- **Csatolás** — egyenszint leválasztása váltakozó jelről.' },
      { k: 'callout', tone: 'tip', md: 'Minden mikrovezérlő tápláb mellé tegyél egy **100 nF-os kerámia kondenzátort**, a lehető legközelebb. Ez a „hidegítő" kondenzátor a legegyszerűbb és leghatásosabb dolog, amit a kapcsolás stabilitásáért tehetsz.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a kondenzátor alapösszefüggése?', opts: ['`U = I · R`', '`Q = C · U`', '`P = U · I`'], answer: 1, why: 'A tárolt töltés a kapacitás és a feszültség szorzata.' },
      { k: 'single', q: 'Hányszor annyi energia fér egy kondenzátorba kétszeres feszültségen?', opts: ['Kétszer', 'Négyszer', 'Ugyanannyi'], answer: 1, why: '`E = ½ · C · U²`, tehát a feszültség négyzetesen számít.' },
      { k: 'single', q: 'Mi az RC időállandó jelentése?', opts: ['A teljes feltöltés ideje', 'Ennyi idő alatt tölt fel a végérték 63 százalékára', 'A kisülés sebessége'], answer: 1, why: 'Öt időállandó után gyakorlatilag teljesen feltöltődött.' },
      { k: 'single', q: 'Mi történik fordítva bekötött elektrolit kondenzátorral?', opts: ['Nem működik', 'Felforrósodik és felrobban', 'Lassabban tölt'], answer: 1, why: 'A hosszabb láb a pozitív. Fordított polaritásnál a burkolat felszakad.' },
      { k: 'single', q: 'Mi a „hidegítő" kondenzátor?', opts: ['Hűti a chipet', 'Egy 100 nF-os kerámia az IC táplába mellett, a tápzaj ellen', 'Egy nagy elektrolit a tápegységben'], answer: 1, why: 'A legegyszerűbb és leghatásosabb stabilitásnövelő lépés. Mindig a lehető legközelebb tedd a lábhoz.' },
    ],
    note: {
      summary: ['A kondenzátor töltést tárol: `Q = C · U`, energia `E = ½ · C · U²`.', 'Kétszeres feszültségen négyszer annyi energia fér bele.', 'RC időállandó: `tau = R · C`, 63 százalékos töltés; öt tau után kész.', 'Az elektrolit kondenzátor polaritásos; fordítva felrobban.', 'Használat: szűrés, puffer, időzítés, csatolás.', 'Minden IC tápláb mellé 100 nF kerámia, a lehető legközelebb.'],
      terms: [{ term: 'kapacitás', def: 'A tárolható töltés feszültségegységenként, faradban.' }, { term: 'időállandó', def: '`R · C`: a töltés sebességét megadó idő.' }, { term: 'hidegítő kondenzátor', def: 'Kis kerámia kondenzátor az IC tápláb mellett a zaj ellen.' }],
    },
  },
  {
    day: 19,
    title: 'Mágneses mező',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A mágneses mező minden mozgó töltés körül kialakul. Ezért van, hogy **minden áramjárta vezeték mágnes**, és ezért forog minden villanymotor.' },
      { k: 'callout', tone: 'key', md: 'A **jobbkéz-szabály**: ha a jobb hüvelykujjad az áram irányába mutat, a többi ujjad görbülete adja a mágneses mező körkörös irányát a vezeték körül.' },
      { k: 'text', md: 'Egy egyenes vezeték mezője gyenge. Ha **tekercsbe** tekered, a menetek mezője összeadódik, és a tekercs belsejében erős, egyenletes mező lesz. Ez a **szolenoid** — minden elektromágnes alapja.' },
      { k: 'text', md: 'A mező erősségét három dolog növeli:\n\n1. **Több menet** — arányosan\n2. **Nagyobb áram** — arányosan\n3. **Vasmag** — akár ezerszeresére, mert a vas összegyűjti és vezeti a mezőt' },
      { k: 'callout', tone: 'warn', md: 'A **vasmag telítődik**. Egy ponton túl hiába növeled az áramot, a mező már alig nő — a vas összes tartománya beállt. Ezért nem lehet egy elektromágnest tetszőlegesen erősíteni, és ezért van minden motornak maximális nyomatéka.' },
      { k: 'text', md: 'Az áramjárta vezetékre a mágneses mezőben **erő hat** (Lorentz-erő), és ez merőleges mind az áramra, mind a mezőre. Ez forgatja a motort: a tekercsben folyó áram és az állandó mágnes mezője közti erő adja a nyomatékot.' },
      { k: 'callout', tone: 'tip', md: 'Amikor egy tekercs áramát hirtelen megszakítod, a mező összeomlása **nagy feszültséglökést** indukál — akár több száz voltot. Ezért kell minden relé és motor mellé **szabadonfutó dióda**, különben a kapcsoló tranzisztor tönkremegy.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi kelt mágneses mezőt?', opts: ['Minden töltés', 'Minden mozgó töltés, tehát minden áram', 'Csak az állandó mágnes'], answer: 1, why: 'Ezért mágnes minden áramjárta vezeték, és ezért működik az elektromágnes.' },
      { k: 'single', q: 'Mit mond a jobbkéz-szabály?', opts: ['A hüvelykujj az áram iránya, az ujjak görbülete a mező iránya', 'A tenyér a mező iránya', 'Az erő irányát adja meg'], answer: 0, why: 'Így lehet fejből megmondani, merre fut a mező egy vezeték körül.' },
      { k: 'single', q: 'Mivel lehet a legnagyobb mértékben erősíteni egy elektromágnest?', opts: ['Vastagabb vezetékkel', 'Vasmaggal', 'Hosszabb vezetékkel'], answer: 1, why: 'A vas akár ezerszeresére növeli a mezőt, mert összegyűjti és vezeti.' },
      { k: 'single', q: 'Mit jelent, hogy a vasmag telítődik?', opts: ['Felmelegszik', 'Egy ponton túl az áram növelése már alig növeli a mezőt', 'Elveszti a mágnesességét'], answer: 1, why: 'A vas összes tartománya beállt. Ezért van minden motornak maximális nyomatéka.' },
      { k: 'single', q: 'Miért kell szabadonfutó dióda egy relé mellé?', opts: ['Hogy gyorsabban kapcsoljon', 'Mert a mező összeomlása nagy feszültséglökést indukál, ami tönkretenné a tranzisztort', 'Hogy kevesebb áramot vegyen fel'], answer: 1, why: 'A hirtelen megszakított tekercsáram akár több száz voltot indukálhat.' },
    ],
    note: {
      summary: ['Minden mozgó töltés körül mágneses mező alakul ki.', 'Jobbkéz-szabály: hüvelykujj az áram, ujjak görbülete a mező.', 'A tekercs (szolenoid) belsejében erős, egyenletes mező van.', 'Erősítés: több menet, nagyobb áram, vasmag (akár ezerszeres).', 'A vasmag telítődik: egy ponton túl az áram már nem segít.', 'A Lorentz-erő merőleges az áramra és a mezőre — ez forgatja a motort.', 'Tekercs mellé mindig szabadonfutó dióda.'],
      terms: [{ term: 'szolenoid', def: 'Tekercs, aminek a belsejében egyenletes mágneses mező van.' }, { term: 'telítés', def: 'A vasmag állapota, ahol a mező már nem nő tovább.' }, { term: 'szabadonfutó dióda', def: 'Tekercs mellé kötött dióda, ami elvezeti a kikapcsolási lökést.' }],
    },
  },
];
