import type { Day } from '../../types';

/** ROBOTIKA trek, 13–19. nap. */
export const roboticsHuD: Day[] = [
  {
    day: 13,
    title: 'Robotkar felépítése',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A robotkar **csuklókból** és az őket összekötő **szegmensekből** áll. A csuklók száma adja a szabadsági fokot: hányféleképpen tud mozogni a kar.' },
      { k: 'callout', tone: 'key', md: 'A térben egy tárgy teljes elhelyezéséhez **hat** szabadsági fok kell: három a pozícióhoz (x, y, z) és három az irányhoz (dőlés, bólintás, forgás). Ezért hatcsuklós a legtöbb ipari kar.' },
      { k: 'text', md: 'Kétféle csukló:\n\n- **Forgó (revolute)** — szöget változtat. Ez a gyakoribb; olcsó, strapabíró, nagy mozgástartomány.\n- **Lineáris (prismatic)** — hosszt változtat, mint egy teleszkóp. Pontosabb, de drágább és érzékenyebb a szennyeződésre.' },
      { k: 'text', md: 'Három tipikus elrendezés:\n\n- **Kartéziánus** — három lineáris tengely, mint egy 3D nyomtató. Egyszerű számolás, de nagy helyet foglal.\n- **SCARA** — két függőleges tengelyű forgócsukló plusz egy emelés. Gyors a vízszintes síkban; szerelősorok kedvence.\n- **Csuklós (articulated)** — minden csukló forgó, mint az emberi kar. A legrugalmasabb, a legbonyolultabb számolni.' },
      { k: 'callout', tone: 'warn', md: 'Minden csukló **felszorozza az előző hibáját**. Ha az első csukló fél fokot téved, a kar végén egy méter hosszon ez közel egy centiméter eltérés. Ezért kell a tőhöz közeli csuklókba a legpontosabb érzékelő.' },
      { k: 'text', md: 'A **munkatér** (workspace) az a térrész, amit a kar elér. Nem gömb: belül van egy elérhetetlen hólyag a tő körül, és a szélén a kar kinyújtva alig bír terhet. A gyakorlati munkatér ennél jóval kisebb, mint a papíron megadott.' },
    ],
    quiz: [
      { k: 'single', q: 'Hány szabadsági fok kell egy tárgy teljes térbeli elhelyezéséhez?', opts: ['3', '6', '12'], answer: 1, why: 'Három a pozícióhoz és három az irányhoz. Ezért hatcsuklós a legtöbb ipari kar.' },
      { k: 'single', q: 'Mi a különbség a forgó és a lineáris csukló között?', opts: ['A forgó szöget változtat, a lineáris hosszt', 'A forgó gyorsabb', 'Nincs különbség'], answer: 0, why: 'A forgó csukló olcsóbb és nagyobb a mozgástartománya; a lineáris pontosabb, de drágább.' },
      { k: 'single', q: 'Melyik elrendezés a leggyorsabb vízszintes síkban végzett szerelésnél?', opts: ['Kartéziánus', 'SCARA', 'Csuklós'], answer: 1, why: 'A SCARA merev függőlegesen, és gyors a síkban. Ezért használják szerelősorokon.' },
      { k: 'single', q: 'Miért kell a tőhöz közeli csuklóba a legpontosabb érzékelő?', opts: ['Mert ott nagyobb a terhelés', 'Mert a hibája a kar teljes hosszán felnagyítódik', 'Mert ott melegebb van'], answer: 1, why: 'Fél fok hiba egy méter karhosszon közel egy centiméter eltérés a végponton.' },
      { k: 'single', q: 'Miért kisebb a gyakorlati munkatér a papíron megadottnál?', opts: ['Mert a tő körül van egy elérhetetlen rész, és a szélén alig bír terhet', 'Mert rosszul mérik', 'Nem kisebb'], answer: 0, why: 'A belső hólyag és a széleken a kinyújtott kar gyenge terhelhetősége is kivesz a használható térből.' },
    ],
    note: {
      summary: ['A kar csuklókból és szegmensekből áll; a csuklók száma a szabadsági fok.', 'Teljes térbeli elhelyezéshez hat szabadsági fok kell.', 'Forgó csukló: olcsó, nagy tartomány. Lineáris: pontos, drága.', 'Elrendezések: kartéziánus, SCARA, csuklós.', 'Minden csukló felszorozza az előző hibáját.', 'A gyakorlati munkatér kisebb a névlegesnél.'],
      terms: [{ term: 'szabadsági fok', def: 'Egymástól független mozgásirányok száma.' }, { term: 'SCARA', def: 'Két függőleges forgótengelyű, síkban gyors karelrendezés.' }, { term: 'munkatér', def: 'A kar által elérhető térrész.' }],
    },
  },
  {
    day: 14,
    title: 'Megfogók és végberendezések',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A kar végére szerelt eszköz a **végberendezés** (end effector). Ez dönti el, mire használható a robot: fogó, szívókorong, hegesztőpisztoly, kamera vagy csavarozó.' },
      { k: 'text', md: 'A három leggyakoribb megfogótípus:\n\n- **Párhuzamos ujjas** — két ujj közeledik egymáshoz. Egyszerű, erős, jól pozícionál. Merev tárgyakhoz.\n- **Vákuumos** — szívókorong. Sima, lapos felülethez tökéletes: üveg, lemez, doboz. Porban és érdes felületen nem fog.\n- **Lágy (soft) megfogó** — rugalmas, levegővel felfújt ujjak. Törékeny és szabálytalan tárgyakhoz: gyümölcs, tojás.' },
      { k: 'callout', tone: 'key', md: 'A megfogó **erővezérlése** fontosabb, mint a pozícióvezérlése. Egy tojást pozícióra fogva vagy összetörsz, vagy elejtesz. Erőre fogva viszont minden méretű tojás egyformán jól tartható.' },
      { k: 'text', md: 'A fogáshoz három dolgot kell tudni:\n\n1. **Hol** van a tárgy (kamera vagy rögzített pozíció)\n2. **Honnan** közelítsd (fogási pont és irány)\n3. **Mekkora erővel** szorítsd' },
      { k: 'callout', tone: 'warn', md: 'A megfogó súlya **beleszámít a kar terhelésébe**. Egy 3 kg-os karra szerelt 1,5 kg-os megfogó után csak 1,5 kg hasznos teher marad. Ezt a kezdők rendszeresen elfelejtik, és aztán a kar remeg vagy leáll hibával.' },
      { k: 'callout', tone: 'tip', md: 'A legtöbb ipari feladatban nem a megfogó a nehéz rész, hanem a **tárgy megtalálása és beállása**. Egy jól megtervezett adagolótálca, ami mindig ugyanúgy tartja a darabot, többet ér, mint egy drága kamerarendszer.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a végberendezés?', opts: ['A kar töve', 'A kar végére szerelt eszköz, ami a munkát végzi', 'A vezérlő'], answer: 1, why: 'Fogó, szívókorong, hegesztőpisztoly, kamera — ez dönti el, mire használható a robot.' },
      { k: 'single', q: 'Mikor nem működik a vákuumos megfogó?', opts: ['Sima üvegen', 'Poros vagy érdes felületen', 'Lapos dobozon'], answer: 1, why: 'A szívókorongnak légmentes tapadás kell. Pór és érdesség mellett szivárog.' },
      { k: 'single', q: 'Miért jobb egy tojást erőre fogni, mint pozícióra?', opts: ['Gyorsabb', 'Mert pozícióra fogva vagy összetöröd, vagy elejted', 'Mert kevesebb energiát fogyaszt'], answer: 1, why: 'Az erővezérlés minden tojásméretre ugyanazt a szorítást adja. A pozícióvezérlés a tárgy méretére érzékeny.' },
      { k: 'single', q: 'Hogyan hat a megfogó súlya a kar terhelhetőségére?', opts: ['Sehogy', 'Levonódik a hasznos teherből', 'Megnöveli'], answer: 1, why: 'Egy 3 kg-os karon egy 1,5 kg-os megfogó után 1,5 kg hasznos teher marad.' },
      { k: 'single', q: 'Mi a legtöbb ipari fogási feladat nehéz része?', opts: ['A megfogó megépítése', 'A tárgy megtalálása és ismételhető beállása', 'A kar programozása'], answer: 1, why: 'Egy jó adagolótálca, ami mindig ugyanúgy tartja a darabot, sokszor kiváltja a drága kamerarendszert.' },
    ],
    note: {
      summary: ['A végberendezés dönti el, mire használható a robot.', 'Párhuzamos ujjas: merev tárgyakhoz. Vákuumos: sima felülethez. Lágy: törékenyhez.', 'A megfogó erővezérlése fontosabb a pozícióvezérlésnél.', 'Fogáshoz kell: hol van, honnan közelíts, mekkora erővel.', 'A megfogó súlya levonódik a hasznos teherből.', 'A nehéz rész a tárgy ismételhető beállása, nem a megfogó.'],
      terms: [{ term: 'végberendezés', def: 'A kar végére szerelt munkaeszköz.' }, { term: 'erővezérlés', def: 'A szorítóerő szabályozása pozíció helyett.' }, { term: 'hasznos teher', def: 'A megfogó súlyán felül emelhető tömeg.' }],
    },
  },
  {
    day: 15,
    title: 'Szabályozás: nyílt és zárt hurok',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **nyílt hurkú** vezérlés kiad egy parancsot, és reménykedik. A **zárt hurkú** szabályozás megméri az eredményt, és a különbség alapján korrigál. Ez a különbség adja a robotika egész szabályozástechnikáját.' },
      { k: 'text', md: '**Nyílt hurok**: „menj előre 2 másodpercig". Ha a szőnyeg puhább, vagy az akku merülőben van, más távolságra jut. Nincs visszajelzés, nincs korrekció.\n\n**Zárt hurok**: „menj 50 cm-t". Az enkóder méri a megtett utat, és a szabályozó addig hajt, amíg a különbség nulla nem lesz.' },
      { k: 'callout', tone: 'key', md: 'A zárt hurok négy eleme: **alapjel** (amit akarsz), **mért érték** (ami van), **hibajel** (a kettő különbsége) és **beavatkozás** (amit a hiba alapján teszel). Minden szabályozó ennek a négynek a kapcsolata.' },
      { k: 'code', lang: 'py', src: 'alapjel = 50.0        # cm\nmert = 0.0\n\nwhile True:\n    mert = enkoder_tav()\n    hiba = alapjel - mert\n    if abs(hiba) < 0.5:\n        motor(0)\n        break\n    motor(0.4 if hiba > 0 else -0.4)', explain: 'Ez a legegyszerűbb zárt hurok: ki-be kapcsoló (bang-bang) szabályozó. Működik, de a cél körül ingadozik, mert nem lassít a közeledéskor.' },
      { k: 'callout', tone: 'warn', md: 'A **holtsáv** (itt a 0,5 cm) nem luxus, hanem szükséglet. Nélküle a robot a cél körül örökké oda-vissza kapcsolgat, és a motor hamar tönkremegy.' },
      { k: 'text', md: 'Mikor elég a nyílt hurok? Ha a zavar kicsi és a pontosság nem kritikus: egy lámpa felkapcsolása, egy szelep nyitása. A mozgáshoz szinte mindig zárt hurok kell, mert a tapadás, a terhelés és az akkufeszültség folyamatosan változik.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a különbség a nyílt és a zárt hurok között?', opts: ['A zárt hurok megméri az eredményt és korrigál', 'A nyílt hurok gyorsabb mindig', 'Nincs különbség'], answer: 0, why: 'A nyílt hurok parancsot ad és nem ellenőriz. A zárt hurok a mért hiba alapján avatkozik be.' },
      { k: 'single', q: 'Mi a hibajel?', opts: ['A szenzor zaja', 'Az alapjel és a mért érték különbsége', 'A motor árama'], answer: 1, why: 'Ez a szabályozás bemenete: ebből számol a szabályozó beavatkozást.' },
      { k: 'single', q: 'Mi a baj a ki-be kapcsoló szabályozóval?', opts: ['Túl lassú', 'A cél körül ingadozik, mert nem lassít a közeledéskor', 'Nem éri el a célt'], answer: 1, why: 'Teljes erővel hajt, amíg át nem lépi a célt, aztán visszafordul. Ettől oszcillál.' },
      { k: 'single', q: 'Mire való a holtsáv?', opts: ['Gyorsít', 'Megakadályozza az örökös oda-vissza kapcsolgatást a cél körül', 'Méri a távolságot'], answer: 1, why: 'Enélkül a motor folyamatosan kapcsolgat, és hamar tönkremegy.' },
      { k: 'order', q: 'Milyen sorrendben fut le egy szabályozási ciklus?', items: ['Beavatkozás a motorra', 'Hibajel számítása', 'Mérés'], correct: [2, 1, 0], why: 'Mérés, hibaszámítás, beavatkozás — és kezdődik elölről.' },
    ],
    note: {
      summary: ['Nyílt hurok: parancs visszajelzés nélkül. Zárt hurok: mér és korrigál.', 'A zárt hurok négy eleme: alapjel, mért érték, hibajel, beavatkozás.', 'A ki-be szabályozó működik, de a cél körül oszcillál.', 'A holtsáv megakadályozza a folyamatos kapcsolgatást.', 'Mozgáshoz szinte mindig zárt hurok kell.'],
      terms: [{ term: 'alapjel', def: 'A kívánt érték, amit el akarsz érni.' }, { term: 'hibajel', def: 'Az alapjel és a mért érték különbsége.' }, { term: 'holtsáv', def: 'Tűréstartomány, amin belül nem avatkozunk be.' }],
    },
  },
  {
    day: 16,
    title: 'P szabályozó',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **P (arányos) szabályozó** a legegyszerűbb értelmes megoldás: a beavatkozás **arányos a hibával**. Nagy hiba, nagy teljesítmény; kis hiba, óvatos közelítés.' },
      { k: 'code', lang: 'py', src: 'Kp = 0.02             # arányos erősítés\n\nwhile True:\n    hiba = alapjel - enkoder_tav()\n    u = Kp * hiba\n    u = max(-1.0, min(1.0, u))     # korlátozás a motor tartományára\n    motor(u)\n    if abs(hiba) < 0.5:\n        motor(0); break', explain: 'A `Kp` az egyetlen hangolható szám. A korlátozás kötelező: a motor nem tud 1,0-nál többet adni, és enélkül a számítás értelmetlen értékeket produkálna.' },
      { k: 'callout', tone: 'key', md: 'A `Kp` hangolása:\n\n- **túl kicsi** — lassan ér célba, és megállhat a cél előtt\n- **jó** — gyorsan közelít, alig lendül túl\n- **túl nagy** — túllendül, oszcillál, végül instabil' },
      { k: 'text', md: 'A gyakorlati módszer: indulj kicsiből, és **duplázd**, amíg a rendszer éppen elkezd túllendülni. Aztán vedd vissza a felére. Ez a hangolás első lépése minden szabályozónál.' },
      { k: 'callout', tone: 'warn', md: 'A tiszta P szabályozó **maradó hibát** hagy. Ha a hiba kicsi, a beavatkozás is kicsi — és egy ponton már nem elég, hogy legyőzze a súrlódást vagy a gravitációt. A robot megáll 2 cm-rel a cél előtt, és ott marad örökre.' },
      { k: 'text', md: 'A maradó hiba a P szabályozó alapvető korlátja, nem hangolási hiba. Nagyobb `Kp` csökkenti, de instabilitást hoz. A megoldás az **I tag**, amiről a következő nap szól.' },
    ],
    quiz: [
      { k: 'single', q: 'Mitől arányos a P szabályozó?', opts: ['Az időtől', 'A beavatkozás arányos a hibával', 'A sebességtől'], answer: 1, why: 'Nagy hiba nagy beavatkozást ad, kis hiba kicsit. Ettől lassít a cél közelében.' },
      { k: 'single', q: 'Mi történik túl nagy `Kp` esetén?', opts: ['Lassan ér célba', 'Túllendül, oszcillál, végül instabil lesz', 'Semmi'], answer: 1, why: 'A nagy erősítés túlreagálja a hibát, és a rendszer átlendül a másik irányba.' },
      { k: 'single', q: 'Mi a maradó hiba?', opts: ['Szenzorzaj', 'Az a kis hiba, amit a P szabályozó már nem tud legyőzni, mert a beavatkozás túl kicsi', 'Programhiba'], answer: 1, why: 'Kis hibánál a beavatkozás sem elég a súrlódás legyőzéséhez. A robot megáll a cél előtt.' },
      { k: 'single', q: 'Mi a `Kp` hangolásának gyakorlati módszere?', opts: ['Véletlenszerű próbálgatás', 'Indulj kicsiből, duplázd a túllendülésig, majd vedd vissza a felére', 'Mindig 1.0'], answer: 1, why: 'Ez a szabályozóhangolás bevett első lépése, és minden rendszerre működik.' },
      { k: 'single', q: 'Miért kell korlátozni a beavatkozást?', opts: ['Hogy szép legyen', 'Mert a motor nem tud a tartományán túl teljesíteni', 'Nem kell'], answer: 1, why: 'Korlátozás nélkül a számítás értelmetlen értékeket adna, és az integráló tag később fel is tekeredne.' },
    ],
    note: {
      summary: ['A P szabályozó beavatkozása arányos a hibával.', 'Egyetlen hangolható szám: `Kp`.', 'Túl kicsi `Kp`: lassú. Túl nagy: oszcillál, instabil.', 'Hangolás: duplázd a túllendülésig, majd felezd.', 'A beavatkozást korlátozni kell a motor tartományára.', 'A tiszta P maradó hibát hagy — ez a módszer alapvető korlátja.'],
      terms: [{ term: 'arányos erősítés (Kp)', def: 'A hiba és a beavatkozás közti szorzó.' }, { term: 'maradó hiba', def: 'Az a hiba, amit a P tag már nem tud legyőzni.' }, { term: 'túllendülés', def: 'Amikor a rendszer átlép a célon, mielőtt visszaállna.' }],
    },
  },
  {
    day: 17,
    title: 'PID hangolása',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'A PID három tagból áll, és mindegyik a hiba más oldalát nézi: a **jelent**, a **múltat** és a **jövőt**.' },
      { k: 'text', md: '- **P (arányos)** — a mostani hibára reagál. Ez végzi a munka nagy részét.\n- **I (integráló)** — a felhalmozott múltbeli hibát nézi. Ez tünteti el a maradó hibát.\n- **D (differenciáló)** — a hiba változási sebességét nézi. Ez fékez a cél előtt, csökkenti a túllendülést.' },
      { k: 'code', lang: 'py', src: 'Kp, Ki, Kd = 0.02, 0.001, 0.005\nintegral = 0.0\nelozo_hiba = 0.0\ndt = 0.02             # 50 Hz\n\nwhile True:\n    hiba = alapjel - enkoder_tav()\n    integral += hiba * dt\n    integral = max(-500, min(500, integral))     # feltekeredés ellen\n    derivalt = (hiba - elozo_hiba) / dt\n    u = Kp*hiba + Ki*integral + Kd*derivalt\n    motor(max(-1.0, min(1.0, u)))\n    elozo_hiba = hiba', explain: 'A `dt` rögzített és ismert — ez fontos, mert változó ciklusidőnél az I és a D tag kiszámíthatatlanul viselkedik.' },
      { k: 'callout', tone: 'warn', md: 'Az **integrátor feltekeredése** (windup) a leggyakoribb PID-hiba. Ha a motor telítésben van és a hiba fennmarad, az integrál korlátlanul nő. Amikor végre eléred a célt, a felgyűlt integrál még sokáig hajt tovább, és nagy túllendülést okoz. A korlátozás kötelező.' },
      { k: 'callout', tone: 'key', md: 'A hangolás sorrendje:\n\n1. `Ki = 0`, `Kd = 0`. Hangold a `Kp`-t a túllendülés határáig, majd vedd vissza.\n2. Emeld a `Kd`-t, amíg a túllendülés eltűnik. Óvatosan: a D tag felerősíti a szenzorzajt.\n3. Emeld a `Ki`-t, amíg a maradó hiba eltűnik. A `Ki` mindig a legkisebb a három közül.' },
      { k: 'text', md: 'A D tag zajra érzékeny, mert különbséget képez. Ha a szenzor zajos, a derivált ugrál, és a motor remegni kezd. Ellenszer: szűrd a mért értéket, vagy hagyd el a D tagot — rengeteg rendszer tökéletesen működik **PI** szabályozóval.' },
    ],
    quiz: [
      { k: 'single', q: 'Melyik tag tünteti el a maradó hibát?', opts: ['P', 'I', 'D'], answer: 1, why: 'Az integráló tag a felhalmozott hibát nézi, és addig növeli a beavatkozást, amíg a hiba el nem tűnik.' },
      { k: 'single', q: 'Mit csinál a D tag?', opts: ['Felhalmoz', 'A hiba változási sebességét nézi és fékez a cél előtt', 'Megszorozza a hibát'], answer: 1, why: 'Ha a hiba gyorsan csökken, a D tag ellentart, és ezzel csökkenti a túllendülést.' },
      { k: 'single', q: 'Mi az integrátor feltekeredése?', opts: ['Szenzorhiba', 'Telítésben az integrál korlátlanul nő, és később nagy túllendülést okoz', 'A motor túlmelegedése'], answer: 1, why: 'Ezért kell az integrált korlátozni. Ez a leggyakoribb PID-hiba a gyakorlatban.' },
      { k: 'order', q: 'Milyen sorrendben hangolod a PID-et?', items: ['Kd a túllendülés ellen', 'Ki a maradó hiba ellen', 'Kp a túllendülés határáig'], correct: [2, 0, 1], why: 'Előbb Kp, aztán Kd, végül Ki. A Ki mindig a legkisebb a három közül.' },
      { k: 'single', q: 'Miért érzékeny a D tag a zajra?', opts: ['Mert összeadja a hibákat', 'Mert különbséget képez, és a zaj ugrálása felerősödik', 'Mert lassú'], answer: 1, why: 'A kicsi, gyors zajugrás nagy deriváltat ad. Ellenszer a szűrés, vagy a tisztán PI szabályozó.' },
    ],
    note: {
      summary: ['P a jelent, I a múltat, D a jövőt nézi.', 'P végzi a munka nagy részét; I tünteti el a maradó hibát; D fékez a cél előtt.', 'A `dt` legyen rögzített és ismert.', 'Az integrátort korlátozni kell a feltekeredés ellen.', 'Hangolási sorrend: Kp, Kd, Ki. A Ki a legkisebb.', 'A D tag zajra érzékeny; sok rendszer PI-vel is jól működik.'],
      terms: [{ term: 'PID', def: 'Arányos, integráló és differenciáló tagból álló szabályozó.' }, { term: 'feltekeredés (windup)', def: 'Telítésben korlátlanul növő integráltag.' }, { term: 'PI szabályozó', def: 'D tag nélküli PID; zajos rendszerekben gyakori.' }],
    },
  },
  {
    day: 18,
    title: 'Vonalkövetés',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A vonalkövetés a szabályozás tankönyvi feladata: egyszerű szenzor, egyszerű cél, és minden hangolási hiba azonnal látszik a robot viselkedésén.' },
      { k: 'text', md: 'A szenzor jellemzően **infravörös fénysor**: 5–8 LED–fotodióda pár a robot alján. A fekete vonal elnyeli a fényt, a fehér padló visszaveri. Minden érzékelő egy számot ad 0 és 1 közt.' },
      { k: 'code', lang: 'py', src: '# Súlyozott átlag: hol van a vonal a sorhoz képest?\nsulyok = [-3, -2, -1, 0, 1, 2, 3]\n\ndef vonal_pozicio(ertekek):\n    osszeg = sum(ertekek)\n    if osszeg < 0.1:\n        return None                  # elveszett a vonal\n    return sum(w*v for w, v in zip(sulyok, ertekek)) / osszeg', explain: 'A súlyozott átlag **folytonos** pozíciót ad, nem csak azt, melyik érzékelő látja a vonalat. Ettől lesz sima a szabályozás a lépcsőzetes helyett.' },
      { k: 'callout', tone: 'key', md: 'A pozíció a hibajel, az alapjel pedig nulla (a vonal a közepén). Innen a megszokott PID:\n\n`u = Kp*hiba + Kd*(hiba - elozo)`\n\n`bal = alap - u`, `jobb = alap + u`' },
      { k: 'callout', tone: 'warn', md: 'A **kalibrálás** nem elhagyható. A szenzorok eltérnek, a fény változik, és a padló fényessége is más minden teremben. Indításkor húzd át a robotot a vonalon, jegyezd fel az érzékelőnkénti minimumot és maximumot, és erre normalizálj.' },
      { k: 'text', md: 'Mit tegyél, ha elveszett a vonal? A bevált megoldás: **emlékezz az utolsó ismert irányra**, és fordulj arrafelé, amíg újra megtalálod. Ha egyenesen továbbmész, végleg elveszíted.' },
      { k: 'callout', tone: 'tip', md: 'A sebesség és a `Kp` összefügg: ami jól működik lassan, az gyorsan oszcillálni fog. A versenyrobotok ezért **kanyarban lassítanak** — a sebességet a hiba nagyságából számolják.' },
    ],
    quiz: [
      { k: 'single', q: 'Miért jobb a súlyozott átlag, mint a „melyik érzékelő látja" megközelítés?', opts: ['Gyorsabb', 'Folytonos pozíciót ad, ettől sima lesz a szabályozás', 'Kevesebb érzékelő kell'], answer: 1, why: 'A lépcsőzetes jel lépcsőzetes kormányzást ad. A folytonos érték sima vonalkövetést eredményez.' },
      { k: 'single', q: 'Mi az alapjel vonalkövetésnél?', opts: ['A robot sebessége', 'Nulla: a vonal a szenzorsor közepén', 'A vonal szélessége'], answer: 1, why: 'A hibajel a vonal eltérése a középtől, és a szabályozó ezt nullázza.' },
      { k: 'single', q: 'Miért kell kalibrálni?', opts: ['Mert a szenzorok eltérnek, és a fény termenként más', 'Mert gyorsabb lesz', 'Nem kell'], answer: 0, why: 'Kalibrálás nélkül a nyers értékek nem összehasonlíthatók, és a súlyozott átlag félrevisz.' },
      { k: 'single', q: 'Mit tegyél, ha elveszett a vonal?', opts: ['Menj egyenesen tovább', 'Fordulj az utoljára ismert irányba, amíg újra megtalálod', 'Állj meg'], answer: 1, why: 'Egyenesen továbbmenve csak távolodsz. Az utolsó irány a legjobb tipp.' },
      { k: 'single', q: 'Miért lassítanak a versenyrobotok kanyarban?', opts: ['Hogy kíméljék a motort', 'Mert ami lassan jól működő Kp, az gyorsan oszcillál', 'A szabály előírja'], answer: 1, why: 'A sebességet a hiba nagyságából számolják: nagy hiba, lassabb haladás.' },
    ],
    note: {
      summary: ['Infravörös fénysor: a fekete vonal elnyel, a fehér padló visszaver.', 'Súlyozott átlag ad folytonos pozíciót, ettől sima a szabályozás.', 'Az alapjel nulla; a hibajel a vonal eltérése a középtől.', 'Kalibrálás nélkül a nyers értékek félrevisznek.', 'Elveszett vonalnál fordulj az utolsó ismert irányba.', 'Kanyarban lassíts: a hibából számold a sebességet.'],
      terms: [{ term: 'súlyozott átlag', def: 'Folytonos pozícióbecslés több érzékelő értékéből.' }, { term: 'kalibrálás', def: 'Az érzékelők minimum–maximum tartományának felvétele.' }, { term: 'vonalvesztés', def: 'Az az állapot, amikor egy érzékelő sem látja a vonalat.' }],
    },
  },
  {
    day: 19,
    title: 'Akadálykerülés',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az akadálykerülés két részből áll: **észlelni**, hogy van valami, és **eldönteni**, merre kerüld. A második a nehezebb.' },
      { k: 'text', md: 'Érzékelők és korlátaik:\n\n- **Ultrahang** — olcsó, 2 cm–4 m. Puha vagy ferde felületen a hang elszökik, és nem jön vissza visszhang.\n- **Infravörös távolság** — gyors, de a felület színe befolyásolja: a fekete tárgyat közelebbről látja meg.\n- **LiDAR** — pontos, 360 fokos, drága. Átlátszó üveget nem lát.\n- **Ütközéskapcsoló** — a végső biztonsági háló. Mindig legyen rajta a roboton.' },
      { k: 'callout', tone: 'key', md: 'Egyetlen érzékelőben se bízz. A megbízható robot **több, eltérő elvű** érzékelőt használ: amit az ultrahang elvét, azt a LiDAR látja, és fordítva. Ezt hívják szenzorfúziónak.' },
      { k: 'code', lang: 'py', src: '# Egyszerű reaktív kerülés\nBIZTONSAG = 30.0      # cm\n\nwhile True:\n    b, k, j = tav_bal(), tav_kozep(), tav_jobb()\n    if k > BIZTONSAG:\n        hajt(0.5, 0.5)                  # szabad az út\n    elif b > j:\n        hajt(-0.3, 0.3)                 # balra fordul\n    else:\n        hajt(0.3, -0.3)                 # jobbra fordul', explain: 'Ez **reaktív** vezérlés: nincs térkép és nincs terv, csak az aktuális mérésre reagál. Egyszerű, gyors, és beszorul a sarkokba.' },
      { k: 'callout', tone: 'warn', md: 'A reaktív kerülés tipikus kudarca a **csapda**: egy U alakú akadályban a robot örökké oda-vissza jár. Nincs memóriája, tehát minden fordulás után ugyanazt a döntést hozza. Ebből csak térképezéssel lehet kijönni — ez a következő nap témája.' },
      { k: 'text', md: 'A **potenciálmező** módszer finomabb: a cél vonz, az akadályok taszítanak, és a robot a két erő összegének irányába megy. Sima pályát ad, de ennek is van helyi minimuma, ahol megragad.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az ultrahangos érzékelő fő gyengéje?', opts: ['Lassú', 'Puha vagy ferde felületről nem jön vissza visszhang', 'Drága'], answer: 1, why: 'A hang elszökik a ferde felületről, a puha anyag pedig elnyeli. A robot ilyenkor „szabad utat" lát.' },
      { k: 'single', q: 'Miért kell többféle érzékelő?', opts: ['Hogy gyorsabb legyen', 'Mert az egyes elvek más-más helyzetben hibáznak', 'Hogy drágább legyen'], answer: 1, why: 'Amit az ultrahang elvét, azt a LiDAR látja. Az eltérő elvű érzékelők hibái nem esnek egybe.' },
      { k: 'single', q: 'Mi a reaktív vezérlés?', opts: ['Térkép alapján tervez', 'Csak az aktuális mérésre reagál, terv és memória nélkül', 'Előre felvett útvonalat játszik vissza'], answer: 1, why: 'Egyszerű és gyors, de nincs memóriája, ezért csapdába eshet.' },
      { k: 'single', q: 'Miért ragad be a reaktív robot egy U alakú akadályba?', opts: ['Elromlik az érzékelő', 'Nincs memóriája, ezért minden fordulás után ugyanazt a döntést hozza', 'Lemerül az akku'], answer: 1, why: 'Ebből csak térképezéssel lehet kijönni, ami emlékszik a már bejárt helyekre.' },
      { k: 'single', q: 'Mi a potenciálmező módszer lényege?', opts: ['A cél vonz, az akadályok taszítanak, a robot az eredő irányába megy', 'Véletlenszerű bolyongás', 'Előre tervezett útvonal'], answer: 0, why: 'Sima pályát ad, de helyi minimuma van, ahol a robot szintén megragadhat.' },
    ],
    note: {
      summary: ['Két rész: észlelni az akadályt és eldönteni, merre kerüld.', 'Ultrahang: olcsó, de ferde és puha felületen hibázik.', 'LiDAR: pontos és 360 fokos, de üveget nem lát.', 'Mindig legyen ütközéskapcsoló mint végső biztonsági háló.', 'Több, eltérő elvű érzékelő kell: ez a szenzorfúzió.', 'A reaktív kerülés egyszerű, de U alakú csapdában beragad.', 'Potenciálmező: a cél vonz, az akadály taszít.'],
      terms: [{ term: 'reaktív vezérlés', def: 'Pillanatnyi mérésre reagáló vezérlés terv nélkül.' }, { term: 'szenzorfúzió', def: 'Több, eltérő elvű érzékelő adatainak összevonása.' }, { term: 'potenciálmező', def: 'Vonzó cél és taszító akadályok eredőjén alapuló navigáció.' }],
    },
  },
];
