import type { Day } from '../../types';

/** ROBOTIKA trek, 20–26. nap. */
export const roboticsHuE: Day[] = [
  {
    day: 20,
    title: 'Térképezés alapjai',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A reaktív robot beragad a sarokba, mert nincs memóriája. A **térkép** adja meg neki: eltárolja, mit látott, és ebből tervezhet.' },
      { k: 'callout', tone: 'key', md: 'A legelterjedtebb ábrázolás a **foglaltsági rács** (occupancy grid): a teret cellákra osztod, és minden cella egy valószínűséget tárol arra, hogy ott akadály van. 0 = biztosan szabad, 1 = biztosan foglalt, 0,5 = nem tudom.' },
      { k: 'code', lang: 'py', src: 'CELLA = 5.0          # cm, egy cella mérete\nSZELES, MAGAS = 100, 100\nracs = [[0.5]*SZELES for _ in range(MAGAS)]   # kezdetben minden ismeretlen\n\ndef frissit(cx, cy, foglalt):\n    p = racs[cy][cx]\n    racs[cy][cx] = min(0.95, p + 0.2) if foglalt else max(0.05, p - 0.1)', explain: 'A fokozatos frissítés kezeli a szenzorzajt: egyetlen téves mérés nem billenti át a cellát. A 0,05 és 0,95 korlát hagy esélyt a későbbi javításra.' },
      { k: 'text', md: 'A cellaméret a kulcsdöntés. **Kicsi cella**: pontos, de sok memória és lassú tervezés. **Nagy cella**: gyors, de a robot nem fér át a szűk résen, mert a rács szerint foglalt. Gyakorlati szabály: a cella legyen körülbelül a robot szélességének fele.' },
      { k: 'callout', tone: 'warn', md: 'Az **odometria csúszik**: a kerék megpördül, a szőnyeg puha, és a robot száz lépés után már nem ott hiszi magát, ahol van. A hibás pozícióból felvett térkép pedig használhatatlan: ugyanaz a fal kétszer, elcsúszva kerül bele.' },
      { k: 'text', md: 'Ezért jár együtt a térképezés és a helymeghatározás. A **SLAM** (Simultaneous Localization and Mapping) a kettőt egyszerre oldja meg: a térképből pontosítja a pozíciót, a pozícióból a térképet. Ez a robotika egyik központi problémája.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi a foglaltsági rács?', opts: ['A robot útvonala', 'Cellákra osztott tér, celláján az akadály valószínűségével', 'Egy fénykép'], answer: 1, why: '0 = szabad, 1 = foglalt, 0,5 = ismeretlen. Ez az elterjedt térképábrázolás.' },
      { k: 'single', q: 'Miért fokozatos a cellák frissítése?', opts: ['Gyorsabb', 'Hogy egyetlen téves mérés ne billentse át a cellát', 'Kevesebb memória'], answer: 1, why: 'A szenzorzaj így kiátlagolódik több mérés alatt.' },
      { k: 'single', q: 'Mi a baj a túl nagy cellamérettel?', opts: ['Sok memória', 'A robot nem fér át a szűk résen, mert a rács szerint foglalt', 'Lassú'], answer: 1, why: 'A cella legyen körülbelül a robot szélességének fele.' },
      { k: 'single', q: 'Miért használhatatlan a hibás pozícióból felvett térkép?', opts: ['Túl nagy', 'Ugyanaz a fal kétszer, elcsúszva kerül bele', 'Nincs benne elég cella'], answer: 1, why: 'Az odometria csúszása miatt a robot nem ott hiszi magát, ahol van.' },
      { k: 'single', q: 'Mit old meg a SLAM?', opts: ['Csak a térképezést', 'A térképezést és a helymeghatározást egyszerre', 'Csak az útvonaltervezést'], answer: 1, why: 'A térképből pontosítja a pozíciót, a pozícióból a térképet.' },
    ],
    note: {
      summary: ['A térkép adja meg a robotnak a memóriát a reaktív viselkedés fölé.', 'Foglaltsági rács: cellánként az akadály valószínűsége.', 'A frissítés fokozatos, hogy a szenzorzaj kiátlagolódjon.', 'A cella legyen körülbelül a robot szélességének fele.', 'Az odometria csúszik; hibás pozícióból a térkép használhatatlan.', 'A SLAM a térképezést és a helymeghatározást együtt oldja meg.'],
      terms: [{ term: 'foglaltsági rács', def: 'Cellákra bontott térkép az akadály valószínűségével.' }, { term: 'odometria', def: 'A megtett út becslése a kerékfordulatokból.' }, { term: 'SLAM', def: 'Egyidejű helymeghatározás és térképezés.' }],
    },
  },
  {
    day: 21,
    title: 'Lokalizáció',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **lokalizáció** kérdése: hol vagyok a térképen? Nem triviális, mert minden érzékelő pontatlan, és a hibák összeadódnak.' },
      { k: 'text', md: 'Három információforrás, mindegyik más hibával:\n\n- **Odometria** — kerékfordulatok. Rövid távon pontos, de **halmozódik** a hibája.\n- **IMU** (gyorsulásmérő és giroszkóp) — gyors, de **elsodródik** percek alatt.\n- **Távolságérzékelő vagy kamera** — abszolút, de zajos és lassú.' },
      { k: 'callout', tone: 'key', md: 'A megoldás a **szenzorfúzió**: az odometria adja a folyamatos becslést, a távolságmérés pedig időnként **korrigálja**. Egyik önmagában nem elég; együtt viszont pontosak.' },
      { k: 'text', md: 'A **részecskeszűrő** (particle filter) a szemléletes módszer:\n\n1. Szórj szét több száz „tippet" (részecskét) a térképen, mindegyik egy lehetséges pozíció.\n2. Mozgáskor mindet told el az odometria szerint, kis véletlen zajjal.\n3. Méréskor adj **súlyt** mindegyiknek: mennyire illik a mérés ahhoz, amit onnan látni kellene.\n4. **Mintavételezz újra**: a nagy súlyú részecskék sokszorozódnak, a kicsik eltűnnek.' },
      { k: 'callout', tone: 'tip', md: 'A részecskeszűrő szépsége, hogy **több hipotézist tart életben**. Egy szimmetrikus folyosón először két részecskefelhő marad, és csak akkor dől el, melyik a jó, amikor a robot elér egy megkülönböztető pontot.' },
      { k: 'callout', tone: 'warn', md: 'A **rablott robot** probléma: ha valaki felemeli és áthelyezi a robotot, minden részecske rossz helyen van, és a szűrő nem talál vissza. Ellenszer: tarts fenn néhány százalék **véletlenszerűen szétszórt** részecskét, ami újra fel tudja venni a nyomot.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az odometria fő hibája?', opts: ['Zajos', 'A hibája halmozódik', 'Lassú'], answer: 1, why: 'Rövid távon pontos, de a csúszás és a kerékpörgés hibái összeadódnak.' },
      { k: 'single', q: 'Mi a szenzorfúzió lényege a lokalizációban?', opts: ['Több azonos érzékelő', 'Az odometria ad folyamatos becslést, a távolságmérés időnként korrigál', 'Átlagolás'], answer: 1, why: 'Egyik forrás sem elég önmagában; a hibáik viszont különbözőek.' },
      { k: 'single', q: 'Mit csinál a részecskeszűrő újramintavételezéskor?', opts: ['Töröl mindent', 'A nagy súlyú részecskék sokszorozódnak, a kicsik eltűnnek', 'Új térképet rajzol'], answer: 1, why: 'Így a felhő a valószínű pozíciók köré sűrűsödik.' },
      { k: 'single', q: 'Mi a részecskeszűrő előnye a sima átlagoláshoz képest?', opts: ['Gyorsabb', 'Több hipotézist tart életben egyszerre', 'Kevesebb memória'], answer: 1, why: 'Szimmetrikus folyosón két felhő marad, amíg egy megkülönböztető pont el nem dönti.' },
      { k: 'single', q: 'Mi a rablott robot probléma ellenszere?', opts: ['Több érzékelő', 'Néhány százalék véletlenszerűen szétszórt részecske', 'Lassabb mozgás'], answer: 1, why: 'Ezek újra fel tudják venni a nyomot, ha minden régi részecske rossz helyen van.' },
    ],
    note: {
      summary: ['Lokalizáció: hol vagyok a térképen?', 'Odometria halmozódó hibával, IMU elsodródással, távolságmérés zajjal.', 'Szenzorfúzió: folyamatos becslés plusz időnkénti korrekció.', 'Részecskeszűrő: sok tipp, súlyozás a mérés alapján, újramintavételezés.', 'Több hipotézist tart életben — ez a fő előnye.', 'Rablott robot ellen tarts véletlen részecskéket.'],
      terms: [{ term: 'lokalizáció', def: 'A robot helyzetének meghatározása egy ismert térképen.' }, { term: 'részecskeszűrő', def: 'Sok lehetséges pozíciót súlyozó becslő eljárás.' }, { term: 'elsodródás', def: 'Az IMU becslésének lassú elromlása idővel.' }],
    },
  },
  {
    day: 22,
    title: 'Útvonaltervezés rácson',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Ha megvan a térkép és tudod, hol vagy, jöhet a kérdés: **hogyan jutok el A-ból B-be**? A rácsos térképen ez gráfkeresési feladat.' },
      { k: 'callout', tone: 'key', md: 'A rács **gráf**: minden szabad cella egy csúcs, a szomszédos cellák közt él. Négy szomszéd (fel, le, balra, jobbra) vagy nyolc (az átlósakkal is). Nyolc szomszédnál az átló költsége 1,41, nem 1.' },
      { k: 'text', md: 'A **szélességi keresés** (BFS) a legegyszerűbb: a kezdőponttól gyűrűnként terjed kifelé, és az első megtalált út a legrövidebb — ha minden lépés ugyanannyiba kerül.' },
      { k: 'code', lang: 'py', src: 'from collections import deque\n\ndef bfs(racs, start, cel):\n    sor = deque([start])\n    honnan = {start: None}\n    while sor:\n        p = sor.popleft()\n        if p == cel:\n            break\n        for sz in szomszedok(racs, p):\n            if sz not in honnan:\n                honnan[sz] = p\n                sor.append(sz)\n    return utvonal(honnan, cel)', explain: 'A `honnan` szótár kettős szerepű: megjegyzi az útvonalat **és** jelzi, hogy egy cellát már meglátogattunk. Enélkül a keresés körbe-körbe járna.' },
      { k: 'callout', tone: 'warn', md: 'Ha a cellák költsége **különböző** (fű lassabb az aszfaltnál), a BFS már nem ad legrövidebbet. Akkor **Dijkstra** kell: prioritási sor, és mindig a legolcsóbb elérésű csúcsot bontjuk ki.' },
      { k: 'text', md: 'Egy gyakorlati lépés, amit sokan kihagynak: **duzzaszd fel az akadályokat** a robot sugarával (ezt hívják konfigurációs térnek). Így pontszerű robottal tervezhetsz, és a megtalált út biztosan befér.' },
      { k: 'callout', tone: 'tip', md: 'A nyers rácsútvonal lépcsőzetes. **Simítsd**: ha két távolabbi pont közt egyenes vonalon nincs akadály, hagyd ki a köztes pontokat. Ettől a robot folyamatosan halad, nem cikcakkban.' },
    ],
    quiz: [
      { k: 'single', q: 'Hogyan lesz a rácsból gráf?', opts: ['Minden szabad cella csúcs, a szomszédok közt él', 'Minden fal csúcs', 'A sarkok a csúcsok'], answer: 0, why: 'Négy vagy nyolc szomszéd; nyolcnál az átló költsége 1,41.' },
      { k: 'single', q: 'Mikor ad a BFS legrövidebb utat?', opts: ['Mindig', 'Ha minden lépés költsége azonos', 'Soha'], answer: 1, why: 'Különböző költségeknél Dijkstra kell prioritási sorral.' },
      { k: 'single', q: 'Mi a `honnan` szótár kettős szerepe?', opts: ['Tárolja az útvonalat és jelzi a meglátogatottságot', 'Számolja a lépéseket', 'Tárolja a költséget'], answer: 0, why: 'Enélkül a keresés körbe-körbe járna ugyanazokon a cellákon.' },
      { k: 'single', q: 'Miért duzzaszd fel az akadályokat?', opts: ['Hogy szebb legyen', 'Hogy pontszerű robottal tervezhess, és az út biztosan beférjen', 'Hogy gyorsabb legyen'], answer: 1, why: 'Ez a konfigurációs tér: az akadályokat a robot sugarával növeled.' },
      { k: 'single', q: 'Miért kell simítani a rácsútvonalat?', opts: ['Rövidebb lesz a kód', 'Mert a nyers út lépcsőzetes, és a robot cikcakkban menne', 'Kevesebb memória'], answer: 1, why: 'Ha két távolabbi pont közt egyenesen nincs akadály, a köztes pontok elhagyhatók.' },
    ],
    note: {
      summary: ['A rács gráf: szabad cellák a csúcsok, szomszédság az élek.', 'Nyolc szomszédnál az átló költsége 1,41.', 'BFS legrövidebb utat ad, ha minden lépés azonos költségű.', 'Különböző költségnél Dijkstra kell prioritási sorral.', 'Duzzaszd fel az akadályokat a robot sugarával (konfigurációs tér).', 'Simítsd az útvonalat, különben a robot cikcakkban megy.'],
      terms: [{ term: 'BFS', def: 'Szélességi keresés: gyűrűnként terjedő gráfbejárás.' }, { term: 'Dijkstra', def: 'Legolcsóbb utat kereső algoritmus eltérő élköltségekre.' }, { term: 'konfigurációs tér', def: 'A robot sugarával felduzzasztott akadálytérkép.' }],
    },
  },
  {
    day: 23,
    title: 'A* algoritmus',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'A Dijkstra minden irányba egyformán terjed — akkor is, ha a cél egyértelműen jobbra van. Az **A*** ezt javítja: megsejti, merre érdemes keresni.' },
      { k: 'callout', tone: 'key', md: 'Az A* minden csúcsot a következő érték szerint rangsorol:\n\n`f(n) = g(n) + h(n)`\n\n- **g(n)** — a start óta megtett **valódi** költség\n- **h(n)** — a célig **becsült** hátralévő költség (a heurisztika)\n\nMindig a legkisebb `f` értékű csúcsot bontja ki.' },
      { k: 'code', lang: 'py', src: 'import heapq\n\ndef heur(a, b):            # Manhattan-távolság négy szomszédhoz\n    return abs(a[0]-b[0]) + abs(a[1]-b[1])\n\ndef astar(racs, start, cel):\n    nyitott = [(heur(start, cel), 0, start)]\n    g = {start: 0}\n    honnan = {start: None}\n    while nyitott:\n        _, gp, p = heapq.heappop(nyitott)\n        if p == cel:\n            return utvonal(honnan, cel)\n        for sz in szomszedok(racs, p):\n            uj = gp + 1\n            if uj < g.get(sz, float("inf")):\n                g[sz] = uj\n                honnan[sz] = p\n                heapq.heappush(nyitott, (uj + heur(sz, cel), uj, sz))\n    return None', explain: 'A kupac (`heapq`) mindig a legkisebb `f` értékűt adja vissza. Az `uj < g.get(...)` feltétel engedi, hogy egy csúcsot olcsóbb úton újra felfedezzünk.' },
      { k: 'callout', tone: 'warn', md: 'A heurisztika legyen **megengedhető** (admissible): soha ne becsülje **túl** a hátralévő költséget. Ha túlbecsül, az A* gyorsabb lesz, de már nem garantálja a legrövidebb utat. Négy szomszédhoz a Manhattan-távolság, nyolchoz az átlós (Chebyshev) távolság a helyes választás.' },
      { k: 'text', md: 'A két szélső eset megvilágítja a működést:\n\n- Ha `h(n) = 0`, az A* **pontosan Dijkstra** lesz.\n- Ha `h(n)` tökéletes, az A* egyenesen a célhoz megy, kerülő nélkül.\n\nA gyakorlatban valahol a kettő közt van: jóval kevesebb cellát vizsgál, mint a Dijkstra, és ugyanazt az optimális utat adja.' },
      { k: 'callout', tone: 'tip', md: 'Ha a térkép menet közben változik (új akadály tűnik fel), ne tervezz újra a nulláról. A **D* Lite** algoritmus csak az érintett részt számolja újra — mozgó robotnál ez nagyságrendi különbség.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az A* rangsoroló képlete?', opts: ['`f = g`', '`f = g + h`', '`f = h`'], answer: 1, why: 'A megtett valódi költség plusz a hátralévő becsült költség.' },
      { k: 'single', q: 'Mit jelent, hogy a heurisztika megengedhető?', opts: ['Gyors', 'Soha nem becsüli túl a hátralévő költséget', 'Mindig pontos'], answer: 1, why: 'Túlbecslésnél az A* gyorsabb, de már nem garantálja a legrövidebb utat.' },
      { k: 'single', q: 'Mi történik, ha `h(n) = 0`?', opts: ['Nem talál utat', 'Az A* pontosan Dijkstra lesz', 'Végtelen ciklusba kerül'], answer: 1, why: 'Heurisztika nélkül minden irányba egyformán terjed.' },
      { k: 'single', q: 'Melyik heurisztika jó négy szomszéd esetén?', opts: ['Euklideszi távolság', 'Manhattan-távolság', 'Nulla'], answer: 1, why: 'Átló nélkül a Manhattan-távolság pontos és soha nem becsül túl.' },
      { k: 'single', q: 'Mit ad a D* Lite az A*-hoz képest?', opts: ['Rövidebb utat', 'Változó térképnél csak az érintett részt számolja újra', 'Kevesebb memóriát'], answer: 1, why: 'Mozgó robotnál, ahol új akadály tűnhet fel, ez nagyságrendi gyorsulás.' },
    ],
    note: {
      summary: ['A* rangsorolás: `f(n) = g(n) + h(n)`.', 'g a megtett valódi, h a hátralévő becsült költség.', 'A heurisztika legyen megengedhető: ne becsüljön túl.', 'Négy szomszédhoz Manhattan, nyolchoz Chebyshev távolság.', '`h = 0` esetén az A* Dijkstrává válik.', 'Változó térképhez D* Lite, ami csak az érintett részt számolja újra.'],
      terms: [{ term: 'heurisztika', def: 'A hátralévő költség becslése.' }, { term: 'megengedhető heurisztika', def: 'Olyan becslés, ami sosem nagyobb a valódi költségnél.' }, { term: 'D* Lite', def: 'Változó térképen újratervező útvonalalgoritmus.' }],
    },
  },
  {
    day: 24,
    title: 'Állapotgépek',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Egy robot viselkedése hamar elágazások szövevényévé válik. Az **állapotgép** ezt rendezi: a robot mindig pontosan **egy** állapotban van, és világos szabályok szerint vált.' },
      { k: 'code', lang: 'py', src: 'KERES, MEGKOZELIT, FOG, SZALLIT, TOLT = range(5)\nallapot = KERES\n\nwhile True:\n    if allapot == KERES:\n        forog()\n        if targy_lathato(): allapot = MEGKOZELIT\n    elif allapot == MEGKOZELIT:\n        halad_celhoz()\n        if elertuk():      allapot = FOG\n        if not targy_lathato(): allapot = KERES\n    elif allapot == FOG:\n        if megfogo_zar():  allapot = SZALLIT\n\n    if akku() < 15:        allapot = TOLT      # mindenhonnan', explain: 'Az akkuellenőrzés az állapotgépen **kívül** van, ezért minden állapotból érvényes. Ez a gyakori minta a biztonsági és vészátmenetekre.' },
      { k: 'callout', tone: 'key', md: 'Három kérdést kell minden állapotnál megválaszolni:\n\n1. **Mit csinál** a robot ebben az állapotban?\n2. **Mikor lép ki** belőle, és hova?\n3. **Mi történik belépéskor és kilépéskor** (például megfogó nyitása)?' },
      { k: 'callout', tone: 'warn', md: 'A leggyakoribb hiba a **beragadt állapot**: van olyan helyzet, amiből nincs kivezető átmenet. Rajzold fel az állapotgépet, és minden állapotnál kérdezd meg: *mi történik, ha a várt esemény sosem jön el?* Rendszerint időtúllépés a válasz.' },
      { k: 'text', md: 'A **hierarchikus állapotgép** nagyobb rendszerre való: az állapotok állapotokat tartalmaznak. A `SZALLIT` főállapoton belül lehet `HALAD`, `KERULGET` és `LERAK` alállapot — és a főállapot megszakítása mindet lezárja.' },
      { k: 'callout', tone: 'tip', md: 'Naplózd **minden átmenetet** az okával együtt: „MEGKOZELIT → KERES (tárgy eltűnt)". Amikor a robot furcsán viselkedik, ez a napló mondja meg, mit gondolt magáról.' },
    ],
    quiz: [
      { k: 'single', q: 'Mi az állapotgép lényege?', opts: ['Több dolgot csinál egyszerre', 'A robot mindig pontosan egy állapotban van, és szabályok szerint vált', 'Véletlenszerű viselkedés'], answer: 1, why: 'Ez rendezi a viselkedést, ami különben elágazások szövevénye lenne.' },
      { k: 'single', q: 'Miért van az akkuellenőrzés az állapotgépen kívül?', opts: ['Gyorsabb', 'Hogy minden állapotból érvényes legyen', 'Hogy ne fusson gyakran'], answer: 1, why: 'Ez a szokásos minta a biztonsági és vészátmenetekre.' },
      { k: 'single', q: 'Mi a beragadt állapot?', opts: ['Lassú állapot', 'Olyan állapot, amiből nincs kivezető átmenet', 'A kezdőállapot'], answer: 1, why: 'Minden állapotnál kérdezd meg: mi van, ha a várt esemény sosem jön el? Rendszerint időtúllépés a válasz.' },
      { k: 'single', q: 'Mi a hierarchikus állapotgép?', opts: ['Két párhuzamos gép', 'Állapotok, amik állapotokat tartalmaznak', 'Gyorsabb állapotgép'], answer: 1, why: 'A főállapot megszakítása az összes alállapotot lezárja.' },
      { k: 'single', q: 'Miért naplózd az átmeneteket az okukkal?', opts: ['Kötelező', 'Mert furcsa viselkedésnél ez mondja meg, mit gondolt magáról a robot', 'Gyorsít'], answer: 1, why: 'A „MEGKOZELIT → KERES (tárgy eltűnt)" sor azonnal megmutatja a döntés okát.' },
    ],
    note: {
      summary: ['Az állapotgép rendezi a viselkedést: egyszerre egy állapot.', 'Minden állapothoz: mit csinál, mikor lép ki, mi történik be- és kilépéskor.', 'Biztonsági átmenet (akku) az állapotgépen kívül, minden állapotból.', 'Beragadt állapot ellen: minden várt eseményhez időtúllépés.', 'Hierarchikus állapotgép: állapotok állapotokon belül.', 'Naplózd minden átmenetet az okával.'],
      terms: [{ term: 'állapotgép', def: 'Véges állapotok és átmeneteik rendszere.' }, { term: 'beragadt állapot', def: 'Állapot, amiből nincs kivezető átmenet.' }, { term: 'hierarchikus állapotgép', def: 'Állapotokat tartalmazó állapotokból álló gép.' }],
    },
  },
  {
    day: 25,
    title: 'Viselkedésfák',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Az állapotgép szépen működik tíz állapotig. Utána az átmenetek száma négyzetesen nő, és áttekinthetetlen lesz. A **viselkedésfa** erre a válasz.' },
      { k: 'callout', tone: 'key', md: 'A fa csomópontjai minden lépésben **futnak egyet**, és három érték egyikét adják: **SIKER**, **KUDARC** vagy **FUT** (még dolgozik). A szülő ebből dönt, mi következik.' },
      { k: 'text', md: 'A négy csomóponttípus:\n\n- **Sorozat (→)** — balról jobbra. Megáll az első KUDARC-nál. „Ezt **és** ezt **és** ezt."\n- **Választó (?)** — balról jobbra. Megáll az első SIKER-nél. „Ezt **vagy** ezt **vagy** ezt."\n- **Dekorátor** — egy gyereket módosít: ismétlés, tagadás, időkorlát.\n- **Levél** — a tényleges művelet vagy feltétel.' },
      { k: 'code', lang: 'py', src: '# Egy szállító robot fája (bal oldali ág a legfontosabb):\n#\n# ? Választó\n# ├── → Sorozat: vészhelyzet\n# │    ├── akku < 15?\n# │    └── menj tölteni\n# ├── → Sorozat: szállítás\n# │    ├── van nálam tárgy?\n# │    ├── menj a lerakóhoz\n# │    └── rakd le\n# └── → Sorozat: keresés\n#      ├── keress tárgyat\n#      └── menj oda és fogd meg', explain: 'A legfelső választó a **prioritást** adja: a vészhelyzet mindig előbb fut. Ha az akku rendben van, az első ág KUDARC-ot ad, és a választó továbblép a szállításra.' },
      { k: 'callout', tone: 'tip', md: 'A viselkedésfa fő előnye a **moduláris bővíthetőség**: egy új viselkedés egy új ág beszúrása a megfelelő prioritási helyre. Állapotgépben ugyanez minden meglévő állapot átmeneteinek átírását jelentené.' },
      { k: 'callout', tone: 'warn', md: 'A fa minden lépésben **a gyökértől indul újra**. Ez adja a prioritást (a vészhelyzet mindig előbb jut szóhoz), de azt is jelenti, hogy egy hosszú művelet FUT értéket kell adjon vissza, nem blokkolhatja a ciklust. Blokkoló levél megöli a reagálóképességet.' },
    ],
    quiz: [
      { k: 'single', q: 'Milyen három értéket adhat egy csomópont?', opts: ['Igaz, hamis, null', 'SIKER, KUDARC, FUT', 'Start, stop, szünet'], answer: 1, why: 'A FUT jelzi, hogy a művelet még dolgozik, és a következő lépésben folytatódik.' },
      { k: 'single', q: 'Mit csinál a sorozat (→) csomópont?', opts: ['Megáll az első SIKER-nél', 'Megáll az első KUDARC-nál: „ezt és ezt és ezt"', 'Véletlenszerűen választ'], answer: 1, why: 'Minden gyereknek sikerülnie kell ahhoz, hogy a sorozat sikeres legyen.' },
      { k: 'single', q: 'Mit csinál a választó (?) csomópont?', opts: ['Megáll az első SIKER-nél: „ezt vagy ezt vagy ezt"', 'Mindet lefuttatja', 'Megáll az első KUDARC-nál'], answer: 0, why: 'Ezzel adható prioritási sorrend: a bal oldali ág a legfontosabb.' },
      { k: 'single', q: 'Mi a viselkedésfa fő előnye az állapotgéppel szemben?', opts: ['Gyorsabb', 'Új viselkedés egy ág beszúrása, nem az összes átmenet átírása', 'Kevesebb memória'], answer: 1, why: 'Állapotgépben az átmenetek száma négyzetesen nő az állapotokkal.' },
      { k: 'single', q: 'Miért nem blokkolhat egy levél?', opts: ['Mert lassú', 'Mert a fa minden lépésben a gyökértől indul, és a blokkolás megöli a reagálóképességet', 'Mert hibát ad'], answer: 1, why: 'Hosszú műveletnek FUT értéket kell visszaadnia, hogy a vészhelyzeti ág szóhoz juthasson.' },
    ],
    note: {
      summary: ['A viselkedésfa az állapotgép skálázódási problémájára válasz.', 'Csomópont-eredmény: SIKER, KUDARC vagy FUT.', 'Sorozat (→): „és". Választó (?): „vagy". Dekorátor módosít, levél cselekszik.', 'A legfelső választó adja a prioritási sorrendet.', 'Új viselkedés egyetlen ág beszúrása.', 'A fa minden lépésben a gyökértől indul: levél nem blokkolhat.'],
      terms: [{ term: 'viselkedésfa', def: 'Fa alakú, prioritásos viselkedésvezérlő szerkezet.' }, { term: 'sorozat csomópont', def: 'Minden gyereknek sikerülnie kell.' }, { term: 'választó csomópont', def: 'Az első sikeres gyereknél megáll.' }],
    },
  },
  {
    day: 26,
    title: 'Biztonság és vészleállítás',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Egy robot, ami mozog, veszélyes lehet. A biztonság nem a végén hozzáadott funkció: a **felépítés része**, és rendszerint a szoftvertől független.' },
      { k: 'callout', tone: 'key', md: 'A **vészleállító** (E-stop) a legfontosabb szabály: a szoftvertől **függetlenül** kell működnie. Egy relé vagy kontaktor, ami fizikailag megszakítja a motorok tápját. Ha a szoftverre bízod, akkor pontosan az nem fog működni, ami lefagyott.' },
      { k: 'text', md: 'A vészleállító követelményei:\n\n- **Normálisan zárt** érintkező: ha a kábel elszakad, a kör megszakad és a robot leáll\n- **Reteszelő** gomb: lenyomva marad, amíg el nem forgatják\n- **Elérhető** helyen, jól láthatóan (piros gomb, sárga alap)\n- Újraindítás után **ne induljon magától** a mozgás' },
      { k: 'callout', tone: 'warn', md: 'A **normálisan zárt** logika nem apróság. Normálisan nyitott érintkezőnél egy elszakadt kábel azt jelenti, hogy a vészleállító soha többé nem működik — és ezt senki nem veszi észre, amíg szükség nem lesz rá. A hibának **biztonságos irányba** kell buknia.' },
      { k: 'text', md: 'A szoftveres rétegek a hardveres E-stop **fölé** épülnek, nem helyette:\n\n- **Watchdog időzítő** — ha a főciklus nem jelentkezik időben, a motorok leállnak\n- **Sebességkorlát** — ember közelében lassabban\n- **Nyomatékkorlát** — ütközésnél ne nyomjon tovább\n- **Munkatér-korlátozás** — ne menjen ki a kijelölt területről' },
      { k: 'callout', tone: 'tip', md: 'A **watchdog** a legolcsóbb szoftveres biztonsági háló. A főciklus rendszeresen „megsimogatja"; ha lefagy vagy végtelen ciklusba kerül, a watchdog időtúllépéskor leállítja a motorokat és újraindítja a vezérlőt.' },
      { k: 'text', md: 'Tesztelés: a vészleállítót **minden használat előtt** próbáld ki, és rendszeresen tesztelj kirívó eseteket is — mi történik áramszünetkor, kábelszakadáskor, lemerült akkunál. Egy biztonsági rendszer, amit nem tesztelsz, nem biztonsági rendszer.' },
    ],
    quiz: [
      { k: 'single', q: 'Miért kell a vészleállítónak a szoftvertől függetlenül működnie?', opts: ['Gyorsabb', 'Mert ha a szoftver lefagyott, pontosan az nem fog működni', 'Olcsóbb'], answer: 1, why: 'Egy relé vagy kontaktor fizikailag szakítja meg a motorok tápját.' },
      { k: 'single', q: 'Miért normálisan zárt a vészleállító érintkezője?', opts: ['Kevesebb áram', 'Mert elszakadt kábelnél is leáll a robot: a hiba biztonságos irányba bukik', 'Gyorsabb kapcsolás'], answer: 1, why: 'Normálisan nyitottnál egy szakadt kábel észrevétlenül hatástalanítaná a gombot.' },
      { k: 'single', q: 'Mit csinál a watchdog időzítő?', opts: ['Naplóz', 'Leállítja a motorokat, ha a főciklus nem jelentkezik időben', 'Méri a sebességet'], answer: 1, why: 'Lefagyás vagy végtelen ciklus esetén ez a szoftveres biztonsági háló.' },
      { k: 'single', q: 'Mi történjen a vészleállítás feloldása után?', opts: ['Azonnal folytassa', 'Ne induljon magától a mozgás', 'Újrainduljon a program'], answer: 1, why: 'A váratlan újraindulás önmagában is baleset forrása.' },
      { k: 'single', q: 'Mikor kell tesztelni a vészleállítót?', opts: ['Évente', 'Minden használat előtt, és rendszeresen kirívó esetekkel is', 'Soha'], answer: 1, why: 'Egy biztonsági rendszer, amit nem tesztelsz, nem biztonsági rendszer.' },
    ],
    note: {
      summary: ['A biztonság a felépítés része, nem utólagos funkció.', 'A vészleállító a szoftvertől függetlenül, hardveresen szakítsa meg a tápot.', 'Normálisan zárt érintkező: kábelszakadásnál is leáll.', 'Reteszelő, jól látható gomb; feloldás után ne induljon magától.', 'Szoftveres rétegek a hardver fölé: watchdog, sebesség-, nyomaték-, munkatérkorlát.', 'A vészleállítót minden használat előtt tesztelni kell.'],
      terms: [{ term: 'vészleállító (E-stop)', def: 'Hardveres kapcsoló, ami megszakítja a hajtások tápját.' }, { term: 'normálisan zárt', def: 'Érintkező, ami nyugalmi állapotban zárt, így szakadásnál leállít.' }, { term: 'watchdog', def: 'Időzítő, ami lefagyás esetén leállítja a rendszert.' }],
    },
  },
];
