import type { Day } from '../../types';

/** BLENDER track, days 11-17. */
export const blenderEnC: Day[] = [
  {
    day: 11,
    title: 'Boolean operations',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **boolean** combines two solids: union, difference or intersection. Same idea as in CAD, except here it happens at the mesh level — which makes it trickier.' },
      { k: 'text', md: 'Boolean is a **modifier** (Modifier Properties → Add Modifier → Boolean). Pick the operation, pick the other object, and the result appears live.\n\n- **Difference** — subtract: cuts a hole\n- **Union** — fuse into one solid\n- **Intersect** — keep only the shared volume' },
      { k: 'callout', tone: 'key', md: 'A boolean stays **live** until you Apply it. While live, you can move the cutter and the hole follows. That is the real power: the hole position stays editable.' },
      { k: 'text', md: 'Hide the cutter from the viewport (H), or set Object Properties → Viewport Display → Display As: **Wire**. You still see where it is, but it does not block the view.' },
      { k: 'callout', tone: 'warn', md: 'Booleans leave **messy topology**: triangles and n-gons along the cut. On a smooth surface this shows up as shading artifacts. Two remedies: (1) make the mesh dense and even before cutting, (2) clean the edges by hand afterwards.' },
      { k: 'callout', tone: 'tip', md: 'The cutter must be **closed with outward-facing faces**. An open or inverted solid gives unpredictable results. Check with Overlays → Face Orientation: blue is correct, red is flipped.' },
    ],
    quiz: [
      { k: 'single', q: 'Which boolean operation cuts a hole?', opts: ['Union', 'Difference', 'Intersect'], answer: 1, why: 'Difference subtracts the second solid from the first — that is hole cutting.' },
      { k: 'single', q: 'Why keep the boolean as a modifier instead of applying it?', opts: ['Renders faster', 'The cutter stays movable and the hole follows', 'Smaller file'], answer: 1, why: 'As a live modifier the cut stays parametric: position and size can change at any time.' },
      { k: 'single', q: 'What defect do booleans typically leave?', opts: ['The object loses its colour', 'Messy topology: triangles and n-gons along the cut', 'The file grows tenfold'], answer: 1, why: 'Blender splits faces along the cut line however it can. On smooth surfaces that shows as shading errors.' },
      { k: 'single', q: 'What should the cutter solid be like?', opts: ['Open, so it can pass through', 'Closed, with outward-facing faces', 'It does not matter'], answer: 1, why: 'The algorithm has to know what counts as "inside". That needs a closed solid and correct normals.' },
      { k: 'order', q: 'In what order do you cut a hole with a boolean?', items: ['Set Difference and pick the cutter', 'Position the cutter where the hole goes', 'Hide the cutter or set it to wireframe', 'Add a Boolean modifier to the main body'], correct: [1, 3, 0, 2], why: 'Cutter into place, modifier on the main body, set the operation, then get the cutter out of the way.' },
    ],
    note: {
      summary: ['A boolean combines two solids: Union, Difference, Intersect.', 'As a modifier it stays live and the cutter can be moved later.', 'Difference cuts holes, Union fuses, Intersect keeps the shared volume.', 'The cutter must be closed with outward-facing faces.', 'Booleans leave messy topology, which shows as shading errors on smooth surfaces.'],
      terms: [{ term: 'boolean', def: 'Set operation between two solids: union, difference, intersection.' }, { term: 'cutter', def: 'The helper object you cut with; usually hidden.' }, { term: 'normal', def: 'The outward direction of a face; flipped normals break the result.' }],
    },
  },
  {
    day: 12,
    title: 'Curves and profiles',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **curve** is not a mesh: it is a mathematical line with a few control points. Cables, pipes, railings, the path of a sign — all easiest with curves.' },
      { k: 'text', md: 'Add → Curve → **Bezier** or **Path (NURBS)**. Bezier points have handles that shape the curvature; a Path is simpler and more even.\n\nIn edit mode: **E** extends with a new point, **F** joins two points, **X** deletes.' },
      { k: 'callout', tone: 'key', md: 'A curve becomes a visible solid only when you give it **thickness**. Object Data Properties → Geometry → **Bevel**:\n\n- **Round** + Depth → circular cross-section, i.e. a pipe or cable\n- **Object** → another curve becomes the cross-section profile' },
      { k: 'text', md: '**Bevel → Object** is the powerful one: draw a small closed curve (an L shape, say) and sweep it along the path. That is how you get trim, rails and mouldings — one profile, any length.' },
      { k: 'callout', tone: 'tip', md: 'If the profile twists along the path, fix it with **Tilt** (Ctrl+T in edit mode) or Object Data → Twist Method. The "Minimum" method works in most cases.' },
      { k: 'text', md: 'When done, Object → **Convert → Mesh** turns it into geometry. After that you can edit it point by point — but you lose the parametric freedom, so convert only at the end.' },
    ],
    quiz: [
      { k: 'single', q: 'What turns a curve into a visible solid?', opts: ['Selecting it', 'Giving it thickness with Bevel', 'Colouring it'], answer: 1, why: 'A curve on its own is a line. Bevel gives it a cross-section, making it a pipe or a strip.' },
      { k: 'single', q: 'What is Bevel → Object for?', opts: ['Another curve becomes the cross-section profile', 'It duplicates the curve', 'It rounds the corners'], answer: 0, why: 'It lets you sweep any profile — an L, a pipe elbow, a moulding — along the path.' },
      { k: 'single', q: 'When should you convert a curve to a mesh?', opts: ['Right after drawing it', 'At the very end, once you no longer need parametric control', 'Never'], answer: 1, why: 'Conversion is one-way: afterwards the path can no longer be shaped with handles.' },
      { k: 'single', q: 'What does E do in curve edit mode?', opts: ['Deletes the point', 'Extends the curve with a new point', 'Closes the curve'], answer: 1, why: 'Same extrude idea as with meshes: it pulls a new segment from the selected endpoint.' },
    ],
    note: {
      summary: ['A curve is a mathematical line with control points, not a mesh.', 'Bevel gives it a cross-section: Round = pipe, Object = any profile.', 'Edit mode: E new point, F join, X delete.', 'Tilt or Twist Method fixes a twisted profile.', 'Convert → Mesh makes it geometry but loses parametric control.'],
      terms: [{ term: 'Bezier curve', def: 'A smooth line shaped by control points and handles.' }, { term: 'bevel', def: 'The cross-section given to a curve, turning it into a solid.' }, { term: 'profile', def: 'The shape of the cross-section swept along the path.' }],
    },
  },
  {
    day: 13,
    title: 'Materials basics',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **material** tells Blender how a surface bounces light. The default is the **Principled BSDF** — a single node that can describe almost any real material.' },
      { k: 'text', md: 'Its four most important settings:\n\n- **Base Color** — the surface colour\n- **Metallic** — is it metal (0 or 1; in-between values are rare in reality)\n- **Roughness** — how scattered the reflection is (0 = mirror, 1 = matte)\n- **IOR / Transmission** — transparency and refraction' },
      { k: 'callout', tone: 'key', md: '**Roughness** matters most. The eye reads material from it: 0.1 is lacquered, 0.4 is plastic, 0.8 is chalk. When a render looks "plastic", roughness is usually uniform and too low.' },
      { k: 'text', md: 'Metallic is effectively binary. **Metal**: Metallic = 1, and Base Color tints the reflection (gold is yellowish, copper reddish). **Non-metal**: Metallic = 0, and the reflection is always white regardless of colour.' },
      { k: 'callout', tone: 'warn', md: 'One object can hold **several materials**: add another slot in Material Properties, select the faces in edit mode, and hit **Assign**. That is how a control panel gets black buttons and a grey housing on one mesh.' },
      { k: 'text', md: 'The **Shading** workspace (top tab bar) opens the node editor. There you see the material as a graph: boxes with cables between them. For now the Principled sliders are enough — we wire textures into them over the next days.' },
    ],
    quiz: [
      { k: 'single', q: 'What does Roughness control?', opts: ['Object size', 'How scattered the reflection is: 0 = mirror, 1 = matte', 'Transparency'], answer: 1, why: 'Roughness scatters reflected light. It is the strongest material cue the eye has.' },
      { k: 'single', q: 'What is true about Metallic in practice?', opts: ['Typically 0 or 1; in-between is rare', 'Around 0.5 is usually right', 'It sets brightness'], answer: 0, why: 'In reality a material is either metal or it is not. In-between values have no physical counterpart.' },
      { k: 'single', q: 'What tints a metal reflection?', opts: ['The light colour', 'The Base Color', 'The Roughness'], answer: 1, why: 'For metal (Metallic = 1) Base Color tints the reflection. For non-metals the reflection is always white.' },
      { k: 'single', q: 'How do you give one mesh two different materials?', opts: ['You cannot', 'Add two slots, select faces in edit mode, press Assign', 'Split it into two objects'], answer: 1, why: 'The material list holds several slots per object and you assign them per face.' },
      { k: 'order', q: 'In what order do you give a row of buttons a different material?', items: ['Select the button faces in edit mode', 'Press Assign', 'Add a new material slot'], correct: [2, 0, 1], why: 'The second material has to exist first, then select the faces, then assign.' },
    ],
    note: {
      summary: ['The Principled BSDF describes nearly any material in one node.', 'Base Color, Metallic, Roughness, Transmission are the four main sliders.', 'Roughness: 0 mirror, 0.1 lacquer, 0.4 plastic, 0.8 chalk.', 'Metallic is effectively 0 or 1; metal reflections are tinted by Base Color.', 'A mesh can hold several materials, assigned per face.'],
      terms: [{ term: 'Principled BSDF', def: 'Blender general-purpose material node.' }, { term: 'roughness', def: 'Surface microtexture; scatters reflected light.' }, { term: 'metallic', def: 'Whether the surface is metal; in practice 0 or 1.' }],
    },
  },
  {
    day: 14,
    title: 'Metal, plastic, glass',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Three recipes worth knowing by heart. Every robot part, housing and window is built from these.' },
      { k: 'text', md: '**Brushed aluminium**\n\n- Metallic = 1\n- Base Color = light neutral grey (around 0.8)\n- Roughness = 0.25–0.35\n\nThe mid roughness is the key: mirror-perfect aluminium looks fake, because real metal always carries some brushing.' },
      { k: 'text', md: '**Matte ABS plastic** (a 3D-printed part)\n\n- Metallic = 0\n- Base Color = the filament colour\n- Roughness = 0.45–0.6\n\nA layer-line texture comes on top later — without it the surface is too perfect.' },
      { k: 'text', md: '**Glass**\n\n- Metallic = 0\n- Transmission = 1\n- Roughness = 0 (or 0.05 for frosted)\n- IOR = 1.45–1.52' },
      { k: 'callout', tone: 'key', md: 'Glass **only looks right when there is something to reflect**. Against an empty black background glass renders as a dark block. That is why you need an HDRI environment, or at least a few lights and a wall.' },
      { k: 'callout', tone: 'warn', md: 'Glass in **EEVEE** is an approximation: real refraction is computed in **Cycles**. If glass matters to the image, switch renderers in Render Properties.' },
      { k: 'callout', tone: 'tip', md: 'Always start with roughness, not colour. Dial in roughness on a neutral grey, and add colour only once the surface catches light correctly.' },
    ],
    quiz: [
      { k: 'single', q: 'What are the settings for brushed aluminium?', opts: ['Metallic 0, Roughness 0', 'Metallic 1, Roughness 0.25–0.35', 'Transmission 1'], answer: 1, why: 'Metal, but not a mirror: real aluminium is brushed, which scatters the reflection.' },
      { k: 'single', q: 'Why does glass look wrong against an empty black background?', opts: ['The material is broken', 'Glass shows what is around it — with nothing there, it stays dark', 'The object is too small'], answer: 1, why: 'Glass reflects and refracts. With no environment there is nothing for it to show.' },
      { k: 'single', q: 'Which renderer computes true refraction?', opts: ['EEVEE', 'Cycles', 'Workbench'], answer: 1, why: 'Cycles is a ray tracer, so glass and caustics come out correct. EEVEE approximates.' },
      { k: 'single', q: 'What is the IOR of ordinary glass?', opts: ['1.0', '1.45–1.52', '3.0'], answer: 1, why: 'Window glass sits around 1.5. Water is 1.33, diamond 2.4.' },
    ],
    note: {
      summary: ['Aluminium: Metallic 1, grey base colour, Roughness 0.25–0.35.', 'ABS plastic: Metallic 0, Roughness 0.45–0.6.', 'Glass: Transmission 1, Roughness 0, IOR 1.45–1.52.', 'Glass needs an environment or it renders as a dark block.', 'Accurate glass needs Cycles; EEVEE only approximates.'],
      terms: [{ term: 'IOR', def: 'Index of refraction: how strongly the material bends light.' }, { term: 'transmission', def: 'How much light passes through the material.' }, { term: 'Cycles', def: 'Blender physically based ray-tracing renderer.' }],
    },
  },
  {
    day: 15,
    title: 'UV unwrapping',
    minutes: 25,
    lesson: [
      { k: 'text', md: 'A texture is a flat image. A model is three-dimensional. **UV unwrapping** decides which point of the image lands where on the surface — like cutting a cardboard box open and flattening it.' },
      { k: 'callout', tone: 'key', md: 'U and V are the texture axes (X, Y, Z are already taken by space). Every mesh vertex gets a UV coordinate: that mapping is the unwrap.' },
      { k: 'text', md: 'Two steps:\n\n1. **Mark seams** — select edges in edit mode, right click → **Mark Seam**. The surface splits open along seams.\n2. **Unwrap** — select everything (A), then **U → Unwrap**.' },
      { k: 'text', md: 'Put seams where a real seam would be, or where nobody looks: the back of the object, along hard edges, inside corners. A cylinder needs one vertical seam; a cube four or five along the edges.' },
      { k: 'callout', tone: 'tip', md: 'Simple shapes need no manual seams: **U → Smart UV Project** splits the mesh automatically by angle. For robot parts, bolts and boxes that is usually good enough.' },
      { k: 'text', md: 'The **UV Editing** workspace shows the result: flattened islands on the left, the model on the right. To check, apply Blender built-in **UV Grid** image (New → Generated Type: UV Grid in the UV editor). If the squares are roughly the same size and square everywhere, the unwrap is good.' },
      { k: 'callout', tone: 'warn', md: '**Stretching** is the usual failure: wherever the grid squares elongate, the texture will stretch too. Fix it with more seams so the surface flattens more easily.' },
    ],
    quiz: [
      { k: 'single', q: 'What is UV unwrapping?', opts: ['Deleting faces', 'A mapping between surface points and flat texture points', 'Scaling the model down'], answer: 1, why: 'Every mesh vertex gets a U,V coordinate on the texture. That is what places the image.' },
      { k: 'single', q: 'What is a seam for?', opts: ['It strengthens the mesh', 'It tells Blender where the surface splits open when flattened', 'It deletes edges'], answer: 1, why: 'Like in tailoring: the seam is where a 3D surface can be laid flat.' },
      { k: 'single', q: 'How do you check unwrap quality?', opts: ['With the UV Grid test image: squares should be even and square', 'By eye', 'By file size'], answer: 0, why: 'The checker image immediately reveals stretching and scale differences.' },
      { k: 'single', q: 'When is Smart UV Project a good choice?', opts: ['On a human face', 'On simple angular shapes: parts, boxes, bolts', 'Never'], answer: 1, why: 'It splits by angle. It leaves ugly islands on organic forms, but is usually fine for technical objects.' },
      { k: 'order', q: 'In what order do you unwrap by hand?', items: ['U → Unwrap', 'Mark Seam', 'Check with the UV Grid image', 'Select the edges for the seam'], correct: [3, 1, 0, 2], why: 'Select edges, mark the seam, unwrap, then verify with a checker texture.' },
    ],
    note: {
      summary: ['UV unwrapping maps a 3D surface onto flat texture coordinates.', 'U and V are the two texture axes.', 'The surface splits open along seams (Mark Seam).', 'Hide seams on the back or along hard edges.', 'Smart UV Project splits automatically — fine for technical shapes.', 'Check stretching with the UV Grid test image.'],
      terms: [{ term: 'UV', def: 'The two coordinate axes of a texture.' }, { term: 'seam', def: 'An edge along which the surface splits open when flattened.' }, { term: 'stretching', def: 'Distortion where the texture is pulled unevenly across the surface.' }],
    },
  },
  {
    day: 16,
    title: 'Using textures',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A texture is an image that drives a material property point by point. Not only colour: roughness, surface detail and metalness too.' },
      { k: 'text', md: 'In the Shading workspace, **Add → Texture → Image Texture**, then wire its output into the matching Principled input:\n\n- **Base Color** — the colour, or albedo, map\n- **Roughness** — a greyscale roughness map\n- **Normal** — surface detail, through a Normal Map node' },
      { k: 'callout', tone: 'key', md: 'A **normal map** does not change geometry: it changes which way the surface appears to face during lighting. A flat face can look rough or threaded — at zero extra polygons.' },
      { k: 'callout', tone: 'warn', md: 'Get the **colour space** right. The albedo map is sRGB; everything else — roughness, normal, metallic, displacement — is **Non-Color**. Get it wrong and the render looks flat or over-contrasted, and it is hard to see why.' },
      { k: 'text', md: 'With no texture files at hand, Blender offers **procedural** textures: Noise, Voronoi, Musgrave, Wave. They are computed from formulas, so they have infinite resolution and need no UVs. Wear, rust, scratches and wood grain can all be built from them.' },
      { k: 'callout', tone: 'tip', md: 'The fastest way to rescue a dull material: wire a **Noise Texture** into Roughness at low strength (squeezed into 0.35–0.5 with a Color Ramp). Uneven roughness makes a surface read as real immediately.' },
      { k: 'text', md: 'The **Mapping** and **Texture Coordinate** node pair moves, rotates and scales a texture. Those two boxes appear in almost every non-trivial material.' },
    ],
    quiz: [
      { k: 'single', q: 'What does a normal map do?', opts: ['Moves vertices', 'Changes the apparent facing of the surface during lighting', 'Recolours the object'], answer: 1, why: 'The geometry stays smooth; only the shading behaves as if it were bumpy. Very cheap detail.' },
      { k: 'single', q: 'What colour space does a roughness map need?', opts: ['sRGB', 'Non-Color', 'Filmic'], answer: 1, why: 'Only albedo is sRGB. Every data map is Non-Color, otherwise Blender gamma-corrects it and the values go wrong.' },
      { k: 'single', q: 'What is the advantage of a procedural texture?', opts: ['Small file, no UVs needed, because it is computed from a formula', 'It always looks better', 'It renders faster'], answer: 0, why: 'Infinite resolution, no tiling, and it works from 3D coordinates without UVs.' },
      { k: 'single', q: 'What is the quickest way to improve a flat-looking material?', opts: ['Raise the light power', 'Wire a weak Noise Texture into Roughness', 'Set Metallic to 1'], answer: 1, why: 'Real roughness is never uniform. Even a little variation removes the "CG plastic" feel.' },
    ],
    note: {
      summary: ['A texture can drive any material property, not just colour.', 'Image Texture node → Base Color / Roughness / Normal.', 'A normal map fools the lighting; the geometry stays smooth.', 'Colour space: albedo = sRGB, everything else = Non-Color.', 'Procedural textures (Noise, Voronoi) work without UVs at infinite resolution.', 'Weak Noise on Roughness instantly reads as more real.'],
      terms: [{ term: 'albedo', def: 'The surface own colour, before lighting.' }, { term: 'normal map', def: 'A texture that alters the apparent facing of a surface.' }, { term: 'Non-Color', def: 'The colour space for data textures, with no gamma correction.' }],
    },
  },
  {
    day: 17,
    title: 'Lighting: the three-point setup',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Light decides more of the final image than the model does. A mediocre model in good light sells; a perfect model in bad light looks flat.' },
      { k: 'text', md: 'Blender has four light types:\n\n- **Point** — a bulb, radiating everywhere\n- **Sun** — parallel rays; position is irrelevant, only angle matters\n- **Spot** — a cone, a stage light\n- **Area** — a rectangle or disc, the best default in most cases' },
      { k: 'callout', tone: 'key', md: '**Light size sets shadow softness.** A large area light gives soft, diffuse shadows (an overcast sky). A small light gives hard, crisp shadows (direct sun). That is the single most important rule in lighting.' },
      { k: 'text', md: 'The **three-point setup**:\n\n1. **Key** — the strongest light, 30–45 degrees off to the side and above the camera. It draws the form.\n2. **Fill** — from the other side, a quarter to a half of the key power. It opens the shadows without erasing them.\n3. **Rim / back** — from behind the object. It draws a bright edge along the silhouette and separates the subject from the background.' },
      { k: 'callout', tone: 'tip', md: 'Build them **one at a time**. Turn everything off, add the key, dial it in alone. Then the fill, then the rim. Add all three at once and you will never know which one does what.' },
      { k: 'text', md: 'The fast alternative is an **HDRI**: World Properties → Color → Environment Texture, and load a spherical panorama. It supplies light, colour and reflections from every direction at once. For product renders and glass that is often enough on its own.' },
      { k: 'callout', tone: 'warn', md: 'Light power is in **watts** and falls off with the square of distance. Move a light twice as far away and it needs four times the power. Do not cheat with exposure — fix the light.' },
    ],
    quiz: [
      { k: 'single', q: 'What sets shadow softness?', opts: ['Light power', 'Light size', 'Light colour'], answer: 1, why: 'Big source = soft shadow, small source = hard shadow. Power sets brightness, not softness.' },
      { k: 'single', q: 'What is the fill light for?', opts: ['It is the strongest light', 'It opens the shadows from the opposite side, more weakly', 'It draws a rim from behind'], answer: 1, why: 'The fill lights into the key shadow, typically at a quarter to a half the power. It makes the shadow readable rather than erasing it.' },
      { k: 'single', q: 'For which light type does position not matter, only angle?', opts: ['Point', 'Sun', 'Area'], answer: 1, why: 'Sun emits parallel rays from infinitely far away. Only direction counts.' },
      { k: 'single', q: 'What does an HDRI environment provide?', opts: ['Only a backdrop', 'Light, colour and reflections from all directions at once', 'Higher resolution'], answer: 1, why: 'The spherical panorama lights the scene and also shows up in reflective surfaces — which is what makes glass and metal believable.' },
      { k: 'order', q: 'In what order do you build a three-point setup?', items: ['Rim light from behind', 'Fill from the other side, weaker', 'Dial in the key alone'], correct: [2, 1, 0], why: 'One at a time: key, fill, rim. That way you know what each light contributes.' },
    ],
    note: {
      summary: ['Light decides more of the final image than the model.', 'Light types: Point, Sun, Spot, Area — Area is usually right.', 'Light size sets shadow softness, not light power.', 'Three-point setup: key (main), fill (shadow lift), rim (separation).', 'Build them one at a time so you can see each contribution.', 'An HDRI supplies light, colour and reflections at once.'],
      terms: [{ term: 'key light', def: 'The main light that draws the form.' }, { term: 'fill light', def: 'A weaker light that opens up the shadows.' }, { term: 'HDRI', def: 'A high dynamic range spherical panorama used to light a scene.' }],
    },
  },
];
