import type { Track } from '../../types';
import { blenderEnB } from './blender-b';
import { blenderEnC } from './blender-c';
import { blenderEnD } from './blender-d';

export const blenderEn: Track = {
  id: 'blender',
  title: 'Blender 3D',
  blurb: 'Modelling, materials, lighting and rendering in Blender.',
  plannedTitles: [
    'The Blender interface',
    'Navigating the viewport',
    'Moving objects',
    'Edit mode: vertices, edges, faces',
    'Extrude and inset',
    'Loop cuts and subdividing',
    'Modifiers: Mirror and Subdivision',
    'Bevel and shading',
    'Modelling a simple object',
    'Topology: why it matters',
    'Boolean operations',
    'Curves and profiles',
    'Materials basics',
    'Metal, plastic, glass',
    'UV unwrapping',
    'Using textures',
    'Lighting: the three-point setup',
    'HDRI and environment lighting',
    'Camera and framing',
    'Rendering: EEVEE and Cycles',
    'Render speed and noise',
    'Compositing basics',
    'Armatures and skeletons',
    'Rigging and weight painting',
    'Keyframe animation',
    'The graph editor',
    'Physics simulation',
    'Exporting for printing',
    'Modelling your robot',
    'A finished render for your portfolio',
  ],
  days: [
    {
      day: 1,
      title: 'The Blender interface',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'Blender is famously intimidating at first. Yet its interface is only a handful of areas, and once you understand those few, the rest is just buttons.' },
        { k: 'text', md: '- **3D viewport** — the middle, where you work.\n- **Outliner** — top right: the list of every object.\n- **Properties** — bottom right: settings for whatever is selected.\n- **Timeline** — along the bottom: animation time.\n- **Header** — at the top of the viewport: mode and tools.' },
        { k: 'callout', tone: 'key', md: 'Blender works in **modes**. In object mode you move whole things; in edit mode you move the points of a thing. The same key does different things in each — that is half of all beginner confusion. The switch is **Tab**.' },
        { k: 'text', md: 'The three keys you will press most:\n\n- **G** (grab) — move\n- **R** (rotate) — rotate\n- **S** (scale) — scale\n\nAfter each you can press **X**, **Y** or **Z** to lock to an axis, or type a number. `G` then `Z` then `2` then Enter: two units up.' },
        { k: 'callout', tone: 'tip', md: 'Blender is keyboard-driven. That slows you down at first and then makes you far faster than menu-hunting ever would. For the first week, those three letters and Tab are enough.' },
      ],
      quiz: [
        { k: 'single', q: 'What switches between object and edit mode?', opts: ['Space', 'Tab', 'Enter'], answer: 1, why: 'Tab is the mode switch. The same key does different things in each mode, so always know which one you are in.' },
        { k: 'single', q: 'What does the `G` key do?', opts: ['Rotates', 'Moves', 'Scales'], answer: 1, why: 'G is short for "grab": it picks up and moves the selection. Rotate is R, scale is S.' },
        { k: 'single', q: 'What does pressing `Z` after `G` mean?', opts: ['Undo', 'Locks the move to the Z axis', 'Zoom'], answer: 1, why: 'The axis letter narrows the operation to one direction. That is how you move exactly vertically.' },
        { k: 'single', q: 'What is the Outliner for?', opts: ['Rendering', 'Listing the objects in the scene', 'Editing materials'], answer: 1, why: 'The Outliner is the table of contents of the scene. If you cannot find an object in the viewport, it is certainly in there.' },
      ],
      note: {
        summary: ['The Blender interface: 3D viewport, Outliner, Properties, Timeline, header.', 'Blender works in modes; Tab switches between object and edit mode.', 'The same key does different things in each mode — always know which you are in.', 'G moves, R rotates, S scales.', 'Pressing X/Y/Z after an operation locks it to an axis, and a number can be typed.'],
        terms: [{ term: 'object mode', def: 'The mode in which you move, rotate and scale whole objects.' }, { term: 'edit mode', def: "The mode in which you edit an object's vertices, edges and faces." }, { term: 'Outliner', def: 'The panel listing every object in the scene.' }],
      },
    },
    {
      day: 2,
      title: 'Navigating the viewport',
      minutes: 18,
      lesson: [
        { k: 'text', md: 'Before you model anything you have to be able to look around. In Blender that lives on the middle mouse button.' },
        { k: 'text', md: '- **Middle button drag** — orbit around the view centre\n- **Shift + middle button** — pan\n- **Wheel** — zoom in and out\n- **Numpad .** — frame the selected object\n- **Numpad 1 / 3 / 7** — front / side / top view\n- **Numpad 5** — toggle between perspective and orthographic' },
        { k: 'callout', tone: 'key', md: 'In **orthographic** view there is no perspective: parallel edges stay parallel. Model in it almost always, because only there can you align things precisely. Perspective is for the final image.' },
        { k: 'text', md: 'These are the same three standard views you met on day 1 of the CAD track: front, side and top. Blender and a CAD package think about space identically; only the goal differs — CAD wants to manufacture, Blender wants to make a picture.' },
        { k: 'callout', tone: 'tip', md: 'With no numpad on your keyboard, turn on "Emulate Numpad" in Preferences — the top number row then takes over the job.' },
      ],
      quiz: [
        { k: 'single', q: 'What orbits the view?', opts: ['Left button drag', 'Middle button drag', 'Right button drag'], answer: 1, why: 'The middle mouse button (pressing the wheel) orbits the view. With Shift it pans.' },
        { k: 'single', q: 'What is the difference between orthographic and perspective view?', opts: ['Orthographic has no perspective, so parallel edges stay parallel', 'Orthographic is in colour', 'Nothing'], answer: 0, why: 'In perspective, distant things are smaller and edges converge. While modelling that misleads you, which is why we work orthographically.' },
        { k: 'single', q: 'What does Numpad 1 do?', opts: ['Top view', 'Front view', 'Renders'], answer: 1, why: 'Numpad 1 is front, 3 is side, 7 is top. The same three standard views as in CAD.' },
        { k: 'single', q: 'What if your keyboard has no numpad?', opts: ['Blender cannot be used', 'Turn on Emulate Numpad in Preferences', 'Buy a new machine'], answer: 1, why: 'Emulate Numpad turns the top number row into a numpad. On a laptop it is the first thing to switch on.' },
      ],
      note: {
        summary: ['Middle button orbits, Shift + middle pans, the wheel zooms.', 'Numpad 1/3/7: front, side and top; Numpad 5 toggles perspective and orthographic.', 'Model in orthographic view: perspective misleads you when aligning.', 'Numpad . frames the selected object.', 'Without a numpad, turn on Emulate Numpad.'],
        terms: [{ term: 'orthographic view', def: 'A projection without perspective, in which parallel edges stay parallel.' }, { term: 'pan', def: 'Sliding the view sideways without orbiting.' }, { term: 'Emulate Numpad', def: 'A preference that uses the top number row as a numpad.' }],
      },
    },
    {
      day: 3,
      title: 'Moving objects',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'In object mode you work with whole things. Three operations, each with a quick and a precise way to use it.' },
        { k: 'text', md: '**Quick:** press `G` and drag with the mouse.\n**Precise:** `G`, then `Z`, then `2`, then Enter — exactly two units up.\n\nThe same with `R` (degrees) and `S` (a multiplier). `S` then `0.5` halves the size.' },
        { k: 'callout', tone: 'warn', md: 'Every object has an **origin** — that little orange dot. Rotation and scaling **always** happen around it. If something jumps oddly when you rotate it, its origin is not where you think. Fix: Object → Set Origin → Origin to Geometry.' },
        { k: 'text', md: '**Transforms** live separately from the data. Scale an object to twice its size and Blender does not rewrite the points; it notes "this object is at scale two". That causes trouble later — with modifiers, physics and export.' },
        { k: 'callout', tone: 'key', md: 'That is what **Ctrl + A → Apply → All Transforms** is for. It bakes the scale and rotation into the data and resets the scale to one. Apply your transforms before exporting anything or adding physics.' },
      ],
      quiz: [
        { k: 'single', q: 'What does an object rotate around?', opts: ['The world centre', 'Its own origin', 'The camera'], answer: 1, why: 'The orange origin dot is the centre of rotation and scaling. A misplaced origin is the most common cause of odd jumping.' },
        { k: 'single', q: 'What does `S` then `0.5` then Enter do?', opts: ['Doubles the size', 'Halves the size', 'Rotates by 0.5 degrees'], answer: 1, why: 'The number after S is a multiplier. 0.5 scales to half, 2 to double.' },
        { k: 'single', q: 'Why apply transforms?', opts: ['It looks better', 'Because unapplied scale causes trouble with modifiers, physics and export', 'You do not need to'], answer: 1, why: "Blender stores an object's scale separately from its data. Many tools work on the raw data, which is why they behave unexpectedly." },
        { k: 'single', q: 'How do you move the origin to the centre of the object?', opts: ['Object → Set Origin → Origin to Geometry', 'Ctrl + Z', 'Tab'], answer: 0, why: 'That command puts the origin where the geometry actually sits. Imported or much-moved objects often need it.' },
      ],
      note: {
        summary: ['G moves, R rotates, S scales; a number after each gives an exact value.', 'The number after S is a multiplier: 0.5 halves, 2 doubles.', 'Rotation and scaling always happen around the object origin.', 'A misplaced origin is the most common cause of odd jumping.', 'Blender stores scale separately from the data — trouble for modifiers and export.', 'Ctrl + A → Apply → All Transforms bakes the transform into the data.'],
        terms: [{ term: 'origin', def: "An object's orange centre point, around which it rotates and scales." }, { term: 'transform', def: "An object's location, rotation and scale, stored apart from its data." }, { term: 'Apply Transform', def: 'Baking the transform into the data and resetting the scale.' }],
      },
    },
    ...blenderEnB,
    ...blenderEnC,
    ...blenderEnD,
  ],
};
