import type { Day } from '../../types';

/** BLENDER track, days 18-24. */
export const blenderEnD: Day[] = [
  {
    day: 18,
    title: 'HDRI and environment lighting',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'An **HDRI** is a spherical panorama stored with **high dynamic range**: the sun in it is thousands of times brighter than the shadows. That is what lets it work as a real light source.' },
      { k: 'callout', tone: 'key', md: 'An ordinary JPEG stores values from 0 to 255. An HDRI is floating point, and the sun can reach 50,000. That is why a single image can light a scene convincingly — the contrast ratio is in there.' },
      { k: 'text', md: 'Setup: **World Properties → Color → Environment Texture**, and load the `.hdr` or `.exr` file. From then on it lights the scene from every direction and shows up in reflective surfaces.' },
      { k: 'text', md: 'The three settings you will actually adjust:\n\n- **Strength** — brightness. 1.0 is the baseline; product renders often sit between 0.5 and 2.\n- **Rotation** (via a Mapping node) — turns the environment, changing where the key light comes from.\n- **Transparent film** (Render Properties → Film) — the HDRI lights but does not appear as a backdrop.' },
      { k: 'callout', tone: 'tip', md: 'The recipe for most product renders: **HDRI as the base** plus **one area light as the key**. The HDRI gives believable environment reflections, the area light gives the directional light that draws the form. Together they beat either alone.' },
      { k: 'callout', tone: 'warn', md: 'HDRI **resolution** matters for reflections. A 1K panorama is enough for lighting, but if the background is visible or a chrome surface reflects it, you need at least 4K or it will look blurred.' },
    ],
    quiz: [
      { k: 'single', q: 'What makes an HDRI special?', opts: ['Higher resolution', 'It stores high dynamic range: the sun is thousands of times brighter than the shadows', 'More colour'], answer: 1, why: 'Floating-point storage lets it behave as a real light source, not just a backdrop.' },
      { k: 'single', q: 'Where do you set up an HDRI?', opts: ['Render Properties', 'World Properties → Color → Environment Texture', 'Object Properties'], answer: 1, why: 'The World supplies environment lighting from every direction.' },
      { k: 'single', q: 'What does Transparent film do?', opts: ['Makes the object transparent', 'The HDRI lights the scene but does not appear as a backdrop', 'Disables the HDRI'], answer: 1, why: 'You get an alpha channel image you can place on any background afterwards.' },
      { k: 'single', q: 'What is the recipe for most product renders?', opts: ['HDRI only', 'HDRI as the base plus one area light as the key', 'Three lights only'], answer: 1, why: 'The HDRI supplies environment reflection, the area light the directional shaping.' },
      { k: 'single', q: 'When do you need a high-resolution HDRI?', opts: ['Always', 'When the background is visible or chrome reflects it', 'Never'], answer: 1, why: '1K is enough for lighting. Visible backdrops or sharp reflections need at least 4K.' },
    ],
    note: {
      summary: ['An HDRI is a spherical panorama with high dynamic range.', 'Floating-point storage makes it a real light source.', 'Setup: World Properties → Color → Environment Texture.', 'Strength sets brightness, Rotation turns it, Transparent film hides the backdrop.', 'Product render recipe: HDRI plus one area light.', 'Visible backdrops or sharp reflections need at least 4K.'],
      terms: [{ term: 'HDRI', def: 'A high dynamic range spherical panorama used for lighting.' }, { term: 'Environment Texture', def: 'The image node that lights the world.' }, { term: 'transparent film', def: 'A setting that keeps the render background transparent.' }],
    },
  },
  {
    day: 19,
    title: 'Camera and framing',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Setting up a camera is photography, exactly as in real life. The same decisions: where you stand, what lens you use, what goes in the frame and what stays out.' },
      { k: 'callout', tone: 'key', md: '**Focal length** does not set magnification, it sets **perspective**:\n\n- **20–35 mm** — wide, strong distortion. Near parts look huge. For interiors.\n- **50 mm** — neutral, close to human vision.\n- **85–135 mm** — compresses space, flattering proportions. The right choice for product shots.' },
      { k: 'text', md: 'So for a product render, do **not** get close with a wide lens: the front of the object swells, the back shrinks, and the image looks cheap. Step back and shoot at 85 mm — the object fills the frame the same way, but the proportions are right.' },
      { k: 'text', md: 'Three framing rules that work:\n\n- **Rule of thirds** — put key elements on the third lines or their intersections. Overlays → Composition Guides shows them.\n- **Breathing room** — do not let the subject touch the frame edge. Tight crops feel oppressive.\n- **Slightly above or below** — a shot at exact eye level is the dullest one.' },
      { k: 'callout', tone: 'tip', md: '**Depth of field** (Camera Data → Depth of Field) instantly makes it photographic. Focus on the subject and set `F-Stop` between 2.8 and 5.6. Careful: at too low an F-Stop only a thin slice of the subject stays sharp.' },
      { k: 'callout', tone: 'warn', md: '**Resolution and aspect ratio** live in Render Properties, not on the camera. Set the final size **before** you compose, or the crop will differ from what you saw in the viewport.' },
    ],
    quiz: [
      { k: 'single', q: 'What does focal length control?', opts: ['Only magnification', 'Perspective: how much proportions distort', 'Brightness'], answer: 1, why: 'A wide lens swells near parts. A longer one compresses space.' },
      { k: 'single', q: 'What focal length suits a product render?', opts: ['20 mm', '85-135 mm', 'It does not matter'], answer: 1, why: 'It compresses space and gives flattering proportions. A close wide lens looks cheap.' },
      { k: 'single', q: 'What is the rule of thirds?', opts: ['The subject in the centre', 'Key elements on the third lines or their intersections', 'Three objects in frame'], answer: 1, why: 'Overlays → Composition Guides turns on the guide lines.' },
      { k: 'single', q: 'What does depth of field add?', opts: ['Higher resolution', 'A photographic look: the background blurs', 'Faster rendering'], answer: 1, why: 'F-Stop 2.8–5.6 is a good start. Too low and only a thin slice stays sharp.' },
      { k: 'single', q: 'When should you set resolution and aspect ratio?', opts: ['After composing', 'Before composing', 'It does not matter'], answer: 1, why: 'The aspect ratio changes the crop. Setting it later gives a different frame than you saw.' },
    ],
    note: {
      summary: ['Focal length sets perspective, not magnification.', '20-35 mm is wide and distorts; 50 mm is neutral; 85-135 mm suits product shots.', 'Framing: rule of thirds, breathing room, slightly above or below eye level.', 'Depth of field: F-Stop 2.8–5.6 for a photographic look.', 'Set resolution and aspect ratio before composing.'],
      terms: [{ term: 'focal length', def: 'The value setting the camera field of view and perspective distortion.' }, { term: 'rule of thirds', def: 'A composition rule for placing key elements.' }, { term: 'depth of field', def: 'The depth of the zone rendered sharp.' }],
    },
  },
  {
    day: 20,
    title: 'Rendering: EEVEE and Cycles',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Blender has two main render engines and they work completely differently. The question is not which is better, but **what you are using it for**.' },
      { k: 'text', md: '**EEVEE** — a rasteriser, like a game engine. It approximates and renders in seconds. The viewport shows the result in real time.\n\n**Cycles** — a ray tracer. It follows the path of every light ray, so it is physically accurate. A single image takes minutes or hours.' },
      { k: 'callout', tone: 'key', md: 'What **only Cycles does well**: true refraction in glass, caustics, accurate indirect light (colour bleeding from walls), real subsurface scattering. If those matter, there is no choice.' },
      { k: 'text', md: 'What EEVEE does well: flat non-reflective surfaces, stylised looks, animation previews, and anything where speed beats perfect physics. A 250-frame animation is a night in Cycles and five minutes in EEVEE.' },
      { k: 'callout', tone: 'warn', md: 'In EEVEE you have to switch on what Cycles does by default: **Screen Space Reflections**, **Ambient Occlusion**, **Soft Shadows**, and for transparent materials the **Blend Mode** and **Refraction**. Without them an EEVEE image looks flat.' },
      { k: 'text', md: 'The practical workflow: **model and light in EEVEE**, because you see the result instantly. Render the final image in **Cycles**. Most materials look the same in both, because the Principled BSDF is shared.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the main difference between EEVEE and Cycles?', opts: ['EEVEE rasterises and approximates, Cycles traces rays and is accurate', 'EEVEE is older', 'No difference'], answer: 0, why: 'EEVEE approximates in seconds; Cycles computes a physically accurate image over minutes.' },
      { k: 'single', q: 'What does only Cycles do well?', opts: ['Fast previews', 'True refraction, caustics, accurate indirect light', 'Stylised looks'], answer: 1, why: 'All of those need real ray paths, which EEVEE only approximates.' },
      { k: 'single', q: 'When is EEVEE worth using?', opts: ['For a glassy product render', 'For animation and anywhere speed matters more', 'Never'], answer: 1, why: 'A 250-frame animation is a night in Cycles and five minutes in EEVEE.' },
      { k: 'single', q: 'What must you enable separately in EEVEE?', opts: ['Nothing', 'Screen Space Reflections, Ambient Occlusion, Soft Shadows', 'Only the resolution'], answer: 1, why: 'Without them an EEVEE image looks flat. Cycles does all of it by default.' },
      { k: 'single', q: 'What is the recommended workflow?', opts: ['Everything in Cycles', 'Model and light in EEVEE, final render in Cycles', 'Everything in EEVEE'], answer: 1, why: 'The Principled BSDF is shared, so most materials look the same in both.' },
    ],
    note: {
      summary: ['EEVEE rasterises and approximates; Cycles traces rays and is accurate.', 'Cycles only: true refraction, caustics, accurate indirect light.', 'EEVEE suits animation and fast previews.', 'EEVEE needs reflections and soft shadows switched on explicitly.', 'Workflow: model in EEVEE, final render in Cycles.'],
      terms: [{ term: 'EEVEE', def: 'A real-time rasterising render engine.' }, { term: 'Cycles', def: 'A physically accurate ray-tracing render engine.' }, { term: 'caustics', def: 'Light patterns focused by a transparent object.' }],
    },
  },
  {
    day: 21,
    title: 'Render speed and noise',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A Cycles image is **noisy**, because it samples randomly. Every extra sample reduces the noise — but the improvement slows down.' },
      { k: 'callout', tone: 'key', md: 'Noise falls with the **square root** of the sample count. Half the noise needs **four times** the samples. That is why 4096 samples rarely pays: going from 256 to 1024 costs four times the time and barely shows.' },
      { k: 'text', md: 'The most important setting is **Denoise** (Render Properties → Sampling → Denoise). The modern denoiser is machine learned and turns a 128-sample image into something like a 2000-sample one. It is the biggest free win in rendering.' },
      { k: 'text', md: 'Speed settings:\n\n- **Noise Threshold** — adaptive sampling: it stops where the image is already smooth\n- **Lower Max Bounces** — 4 instead of 12 is enough for most scenes\n- **GPU rendering** — typically 5 to 20 times faster than the CPU\n- **Persistent Data** — avoids rebuilding the scene on every animation frame' },
      { k: 'callout', tone: 'warn', md: '**Fireflies** are a separate problem: single blindingly white pixels. They come from a strong light and a small bright surface. The fix: set **Clamp Indirect** to around 10, or make the light source larger.' },
      { k: 'callout', tone: 'tip', md: 'Before waiting hours on a render, try it at **10 percent resolution**. Composition, lighting and the amount of noise are all visible in a small image, and it finishes in three seconds.' },
    ],
    quiz: [
      { k: 'single', q: 'How does noise fall with sample count?', opts: ['Linearly', 'With the square root: half the noise needs four times the samples', 'Exponentially'], answer: 1, why: 'That is why high sample counts hit diminishing returns.' },
      { k: 'single', q: 'What is the biggest free speed win?', opts: ['Lower resolution', 'Enabling Denoise', 'Fewer objects'], answer: 1, why: 'The machine-learned denoiser gets 2000-sample quality out of 128 samples.' },
      { k: 'single', q: 'What are fireflies?', opts: ['Even grain', 'Single blindingly white pixels from a strong light on a small bright surface', 'A colour error'], answer: 1, why: 'The fix is Clamp Indirect around 10, or a larger light source.' },
      { k: 'single', q: 'What does Noise Threshold do?', opts: ['Adds noise', 'Adaptive sampling: it stops sampling where the image is already smooth', 'Blurs the image'], answer: 1, why: 'It spends compute where it is needed: on the noisy regions.' },
      { k: 'single', q: 'How do you check a render in three seconds instead of hours?', opts: ['Fewer samples', 'At 10 percent resolution', 'In EEVEE'], answer: 1, why: 'Composition, lighting and noise level are all visible in a small image.' },
    ],
    note: {
      summary: ['Cycles noise falls with the square root of the sample count.', 'Half the noise needs four times the samples.', 'Denoise is the biggest free win: 2000-sample quality from 128.', 'Speed: Noise Threshold, fewer Max Bounces, GPU, Persistent Data.', 'Against fireflies: Clamp Indirect around 10, or a larger light.', 'Test renders at 10 percent resolution.'],
      terms: [{ term: 'sample', def: 'One random light path contributing to the image.' }, { term: 'denoise', def: 'Machine-learned noise removal on a rendered image.' }, { term: 'firefly', def: 'A single blindingly bright pixel in a render.' }],
    },
  },
  {
    day: 22,
    title: 'Compositing basics',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Compositing** is post-processing a render with nodes. You do not have to re-render to make the image brighter, punchier or warmer.' },
      { k: 'text', md: 'In the **Compositing** workspace, tick **Use Nodes**. Two nodes appear: `Render Layers` (the raw image) and `Composite` (the output). You chain operations between them.' },
      { k: 'callout', tone: 'key', md: 'The three nodes that give the most:\n\n- **Glare** (Fog Glow or Streaks) — a halo around bright areas. This is what makes an image feel photographic.\n- **Color Balance** or **RGB Curves** — setting the colour mood.\n- **Lens Distortion** (with a small Dispersion) — slight fringing at the edges, like a real lens.' },
      { k: 'text', md: '**AOVs**, or render passes, return the building blocks of the image as separate channels: `Diffuse`, `Glossy`, `Emission`, `Mist`, `Z` (depth). Enable them under View Layer Properties → Passes.\n\nThe `Mist` pass, for instance, lets you build fog or distance fade — with no re-render.' },
      { k: 'callout', tone: 'warn', md: '**Colour management** (Render Properties → Color Management) is not compositing, but it shapes the result just as much. The default **Filmic** or **AgX** view compresses highlights, which is what makes an image photographic. The `Standard` setting gives a blown-out, harsh image.' },
      { k: 'callout', tone: 'tip', md: 'Save as **OpenEXR** if you plan post work. PNG is 8-bit and blown highlights cannot be recovered from it. EXR keeps the full dynamic range.' },
    ],
    quiz: [
      { k: 'single', q: 'What is compositing?', opts: ['Re-rendering', 'Post-processing the render with nodes', 'Modelling'], answer: 1, why: 'Brightness, contrast and colour mood can be adjusted without re-rendering.' },
      { k: 'single', q: 'What does the Glare node do?', opts: ['Sharpens', 'Adds a halo around bright areas', 'Removes noise'], answer: 1, why: 'It is one of the fastest ways to make a render feel photographic.' },
      { k: 'single', q: 'What is the Mist pass for?', opts: ['Colour correction', 'Building fog or distance fade afterwards', 'Denoising'], answer: 1, why: 'Passes return the image components as separate channels, editable without re-rendering.' },
      { k: 'single', q: 'What does the Filmic or AgX view do?', opts: ['Sharpens', 'Compresses highlights, which makes the image photographic', 'Adds noise'], answer: 1, why: 'The `Standard` setting gives a blown-out, harsh image because it does not handle high dynamic range.' },
      { k: 'single', q: 'What format should you save for post work?', opts: ['PNG', 'OpenEXR', 'JPEG'], answer: 1, why: 'PNG is 8-bit and blown highlights cannot be recovered. EXR keeps the dynamic range.' },
    ],
    note: {
      summary: ['Compositing is node-based post-processing of a render.', 'Compositing workspace → Use Nodes.', 'Glare adds halos; Color Balance sets mood; Lens Distortion adds lens character.', 'Render passes (AOVs): Diffuse, Glossy, Mist, Z — separately editable.', 'The Filmic or AgX view is what makes the image photographic.', 'Save as OpenEXR for post work.'],
      terms: [{ term: 'compositing', def: 'Node-based post-processing of a rendered image.' }, { term: 'render pass (AOV)', def: 'One component of the image as a separate channel.' }, { term: 'colour management', def: 'How dynamic range is mapped to the display.' }],
    },
  },
  {
    day: 23,
    title: 'Armatures and skeletons',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'An **armature** is the internal skeleton of a model. Bones move the mesh, turning a rigid model into something you can animate.' },
      { k: 'text', md: 'Add → **Armature**. In edit mode a bone has a **head** and a **tail**. Bones form a **parent-child** chain: rotate the upper arm and the forearm and hand follow.' },
      { k: 'callout', tone: 'key', md: 'Bone positions define the **axes of rotation**. On a robot arm they must sit exactly at the real joints — put them beside, and the model will drift on its own as it moves.' },
      { k: 'text', md: 'Two ways to animate:\n\n- **FK (forward kinematics)** — you rotate each bone. Precise control, but hard to hit a specific endpoint.\n- **IK (inverse kinematics)** — you drag the endpoint and the bones in between arrange themselves. Needed when the hand has to be at a given point.' },
      { k: 'callout', tone: 'warn', md: 'An IK chain can be ambiguous: several elbow positions give the same endpoint. That is what the **pole target** is for — a helper object telling the elbow which way to point. Without it the animation suddenly snaps.' },
      { k: 'text', md: '**Bone constraints** encode the real range of motion: `Limit Rotation` stops a joint bending backwards. On a robot that is not just cosmetic — a real servo does not turn 360 degrees either.' },
      { k: 'callout', tone: 'tip', md: 'Name bones meaningfully and use the `.L` / `.R` suffix: `upperarm.L`, `upperarm.R`. Blender recognises the pairs and mirrored pose pasting then works.' },
    ],
    quiz: [
      { k: 'single', q: 'What is an armature?', opts: ['A material type', 'The internal skeleton that moves the mesh', 'A modifier'], answer: 1, why: 'Bones form a parent-child chain, which is what makes a rigid model animatable.' },
      { k: 'single', q: 'Where should a bone sit on a robot arm?', opts: ['In the middle of the link', 'Exactly at the real joint', 'At the edge of the model'], answer: 1, why: 'Bones define the axes of rotation. Placed wrong, the model drifts as it moves.' },
      { k: 'single', q: 'What is the difference between FK and IK?', opts: ['In FK you rotate bones, in IK you drag the endpoint', 'IK is faster', 'No difference'], answer: 0, why: 'IK is needed when the hand must reach a given point; FK gives finer joint control.' },
      { k: 'single', q: 'What is a pole target for?', opts: ['Extending the bone', 'Telling the elbow which way to point in an IK chain', 'Colouring the bone'], answer: 1, why: 'Without it IK is ambiguous and the elbow snaps mid-animation.' },
      { k: 'single', q: 'Why use `.L` and `.R` suffixes?', opts: ['Looks nicer', 'Blender recognises the pairs and mirrored pose pasting works', 'It is faster'], answer: 1, why: 'It is the prerequisite for symmetric animation.' },
    ],
    note: {
      summary: ['An armature is the internal skeleton of a model.', 'A bone has a head and a tail; bones form a parent-child chain.', 'Bone positions define rotation axes — at the real joints on a robot arm.', 'FK: rotate each bone. IK: drag the endpoint.', 'IK needs a pole target, or the elbow snaps.', 'Bone constraints encode the real range of motion.', 'Name bones with `.L` / `.R` suffixes.'],
      terms: [{ term: 'armature', def: 'The skeleton that drives a model.' }, { term: 'IK (inverse kinematics)', def: 'Joint angles computed from an endpoint position.' }, { term: 'pole target', def: 'A helper object fixing the bend direction of an IK chain.' }],
    },
  },
  {
    day: 24,
    title: 'Rigging and weight painting',
    minutes: 24,
    lesson: [
      { k: 'text', md: '**Rigging** binds the mesh to the skeleton. **Weight painting** says how strongly each vertex follows each bone.' },
      { k: 'text', md: 'The fastest start: select the mesh, shift-select the armature, and press **Ctrl+P → With Automatic Weights**. Blender estimates initial weights from bone proximity. Rarely perfect, but a good starting point.' },
      { k: 'callout', tone: 'key', md: 'The weights on each vertex should **sum to 1**. If a vertex follows the upper arm at 0.7 and the forearm at 0.3, it moves proportionally between them. If the sum is not 1, the vertex drifts or stretches.' },
      { k: 'text', md: 'In **Weight Paint** mode the colours show the weight: **red = 1** (fully follows), **blue = 0** (not at all). Paint with the brush and smooth transitions with the `Blur` tool.' },
      { k: 'callout', tone: 'warn', md: 'On **rigid robot parts there should be no transition**: every vertex belongs to exactly one bone at weight 1.0. Soft transitions are for organic bodies — a metal plate does not bend around a joint, it rotates.' },
      { k: 'text', md: 'For rigid parts there is a simpler route: do not weight at all. Make the part a **child of the bone** (Ctrl+P → Bone). It then follows rigidly with no deformation.' },
      { k: 'callout', tone: 'tip', md: 'To check: in Pose mode rotate **every joint to its limit**. Bad weighting shows where the mesh collapses or tears. At rest every rig looks fine.' },
    ],
    quiz: [
      { k: 'single', q: 'What does weight painting do?', opts: ['Colours the model', 'Says how strongly each vertex follows each bone', 'Scales the model'], answer: 1, why: 'It determines how the mesh deforms as the bones move.' },
      { k: 'single', q: 'What should the weights on a vertex sum to?', opts: ['0', '1', 'It does not matter'], answer: 1, why: 'If the sum is not 1, the vertex drifts or stretches during motion.' },
      { k: 'single', q: 'What does red mean in Weight Paint mode?', opts: ['An error', 'Full weight: the vertex follows the bone completely', 'Zero weight'], answer: 1, why: 'Red = 1, blue = 0. Intermediate colours mean partial following.' },
      { k: 'single', q: 'How should a rigid robot part be weighted?', opts: ['With a soft transition', 'Every vertex to exactly one bone at weight 1.0', 'Mixed'], answer: 1, why: 'A metal plate does not bend around a joint, it rotates. Transitions are for organic bodies.' },
      { k: 'single', q: 'How do you check a rig?', opts: ['Look at it at rest', 'In Pose mode rotate every joint to its limit', 'Render an image'], answer: 1, why: 'At rest every rig looks fine. Problems appear at the extremes.' },
    ],
    note: {
      summary: ['Rigging binds the mesh to the skeleton; weights set the degree.', 'Start with Ctrl+P → With Automatic Weights.', 'The weights on each vertex should sum to 1.', 'Weight Paint: red = 1, blue = 0.', 'Rigid parts: no transition — one bone, weight 1.0.', 'Simpler for rigid parts: parent to the bone (Ctrl+P → Bone).', 'Check by rotating every joint to its limit.'],
      terms: [{ term: 'rigging', def: 'Binding a mesh to a skeleton.' }, { term: 'weight painting', def: 'Setting per-vertex bone influence with a brush.' }, { term: 'automatic weights', def: 'Blender initial weight estimate from bone proximity.' }],
    },
  },
];
