import type { Day } from '../../types';

/** C track, days 11-17. */
export const cEnC: Day[] = [
  {
    day: 11,
    title: 'Dynamic memory: malloc and free',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'So far every variable lived on the **stack**: created when the function was entered, gone when it returned. When the size is only known at run time, or the data has to outlive the function, you use the **heap**.' },
      { k: 'code', lang: 'c', src: '#include <stdlib.h>\n\nint *arr = malloc(n * sizeof *arr);\nif (arr == NULL) {\n    return -1;              /* allocation failed */\n}\n\nfor (int i = 0; i < n; i++) {\n    arr[i] = i * i;\n}\n\nfree(arr);\narr = NULL;                 /* so no dangling pointer remains */', explain: '`sizeof *arr` beats `sizeof(int)`: if the type changes later, the line follows automatically. Setting NULL after free is not required, but it prevents a double free.' },
      { k: 'callout', tone: 'key', md: '`malloc` **does not zero** the memory: what you get back is garbage. For zeroed memory use `calloc(n, size)`.' },
      { k: 'text', md: 'The four functions you need:\n\n- `malloc(size)` — allocates, does not zero\n- `calloc(n, size)` — allocates and zeroes\n- `realloc(p, new)` — resizes; **may return a new address**\n- `free(p)` — releases' },
      { k: 'callout', tone: 'warn', md: 'Never write a `realloc` result straight back into the old pointer: `p = realloc(p, new);` — if the allocation fails you get `NULL` and have lost the original pointer too, which is a leak. Use a temporary.' },
      { k: 'callout', tone: 'tip', md: 'The rule that prevents every C memory bug: **exactly one `free` per `malloc`**, and know where the free will be at the moment you allocate.' },
    ],
    quiz: [
      { k: 'single', q: 'What does `malloc` return on failure?', opts: ['0', 'NULL', 'It throws'], answer: 1, why: 'C has no exceptions. A `NULL` return is the only signal, so always check it.' },
      { k: 'single', q: 'What is the difference between `malloc` and `calloc`?', opts: ['`calloc` zeroes the memory', '`malloc` is always faster', 'No difference'], answer: 0, why: '`malloc` leaves garbage. `calloc` zeroes the block and takes two arguments: count and size.' },
      { k: 'single', q: 'Why is `p = realloc(p, new);` dangerous?', opts: ['It is slow', 'On failure NULL lands in p and the original pointer is lost', 'It does not compile'], answer: 1, why: 'The old block still exists but you no longer have a reference. Save the result in a temporary.' },
      { k: 'single', q: 'Why set a pointer to NULL after `free`?', opts: ['It is faster', 'It prevents a double free and using a dangling pointer', 'It frees a bit more memory'], answer: 1, why: '`free(NULL)` is safe and does nothing. Dereferencing NULL crashes immediately, which beats silent corruption.' },
      { k: 'single', q: 'Why is `sizeof *arr` better than `sizeof(int)`?', opts: ['It is shorter', 'If the pointer type changes, the code follows automatically', 'It compiles faster'], answer: 1, why: 'The type is written in one place only, so a type change cannot leave the other one behind.' },
    ],
    note: {
      summary: ['The stack is tied to the function; the heap outlives it.', '`malloc` allocates without zeroing; `calloc` zeroes; `realloc` resizes; `free` releases.', 'Always check a `malloc` result against NULL.', 'Store a `realloc` result in a temporary to avoid a leak on failure.', 'Set the pointer to NULL after `free`.', 'Exactly one `free` per `malloc`.'],
      terms: [{ term: 'heap', def: 'Memory that can be allocated at run time.' }, { term: 'dangling pointer', def: 'A reference to memory that has been freed.' }, { term: 'calloc', def: 'An allocator that zeroes the block.' }],
    },
  },
  {
    day: 12,
    title: 'Memory leaks',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **leak** happens when allocated memory has no remaining reference and was never freed. The program eats more and more memory as it runs, until it runs out.' },
      { k: 'code', lang: 'c', src: '/* Leaks: an early return before the free */\nint process(const char *path) {\n    char *buffer = malloc(1024);\n    FILE *f = fopen(path, "r");\n    if (f == NULL) {\n        return -1;              /* the buffer is lost here! */\n    }\n    /* ... */\n    fclose(f);\n    free(buffer);\n    return 0;\n}', explain: 'An early `return` is the most common leak source in C: every exit path has to release everything allocated so far.' },
      { k: 'callout', tone: 'key', md: 'The proven pattern is the **cleanup label**: one exit point at the end of the function, with every error path jumping there. This is one of the few cases where `goto` is the clean answer in C.' },
      { k: 'code', lang: 'c', src: 'int process(const char *path) {\n    int code = -1;\n    char *buffer = malloc(1024);\n    if (buffer == NULL) goto done;\n\n    FILE *f = fopen(path, "r");\n    if (f == NULL) goto cleanup;\n\n    /* ... work ... */\n    code = 0;\n\n    fclose(f);\ncleanup:\n    free(buffer);\ndone:\n    return code;\n}', explain: 'Every path leaves the same way and releases exactly what was created. Adding a resource means extending one place.' },
      { k: 'text', md: 'Checking with tools:\n\n```\nvalgrind --leak-check=full ./program\ngcc -fsanitize=address,leak -g program.c\n```\n\nValgrind and AddressSanitizer report how many bytes leaked and **on which line** you allocated them.' },
      { k: 'callout', tone: 'warn', md: 'Small leaks matter too: in a server running for weeks, 100 bytes leaked per request becomes gigabytes in days. Size is not the issue — **repetition** is.' },
    ],
    quiz: [
      { k: 'single', q: 'What is a memory leak?', opts: ['A program using too much memory', 'Allocated memory with no remaining reference and no free', 'Dereferencing NULL'], answer: 1, why: 'The block stays reserved but unreachable. Neither the program nor the OS can reclaim it while it runs.' },
      { k: 'single', q: 'What is the most common leak source in C?', opts: ['Oversized arrays', 'An early `return` before the `free`', '`printf`'], answer: 1, why: 'It is easy to forget the release on an error path. That is why you want a single exit point.' },
      { k: 'single', q: 'What is the cleanup label pattern?', opts: ['One exit point at the end, with error paths jumping there via `goto`', 'A separate cleanup function', 'Automatic garbage collection'], answer: 0, why: 'One of the rare cases where `goto` is cleanest in C: every path follows the same release order.' },
      { k: 'single', q: 'Which tool finds leaks?', opts: ['gdb', 'valgrind --leak-check=full', 'make'], answer: 1, why: 'Valgrind reports leaked bytes and the allocation site. AddressSanitizer does the same, built into the compile.' },
      { k: 'single', q: 'Why does a 100-byte-per-request leak matter?', opts: ['It does not, it is small', 'Because it repeats: over a long run it becomes gigabytes', 'Because it slows the network'], answer: 1, why: 'Repetition is the issue, not the one-off size.' },
    ],
    note: {
      summary: ['A leak is allocated memory that is unreachable and never freed.', 'An early `return` is the most common source.', 'Cleanup label: one exit point, error paths jump there with `goto`.', 'Valgrind and AddressSanitizer show the allocation site.', 'Small repeating leaks are serious over a long run.'],
      terms: [{ term: 'leak', def: 'Memory that became unreachable without being freed.' }, { term: 'cleanup label', def: 'A single-exit pattern built with `goto`.' }, { term: 'Valgrind', def: 'A memory error detection tool.' }],
    },
  },
  {
    day: 13,
    title: 'Pointers to pointers',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'If a pointer holds the **address of a variable**, a pointer to a pointer holds the **address of a pointer**. There are two reasons you need it: returning a pointer through a parameter, and building a dynamic two-dimensional array.' },
      { k: 'code', lang: 'c', src: '/* The function sets the caller pointer */\nint allocate(int **out, int n) {\n    *out = malloc(n * sizeof **out);\n    return (*out != NULL) ? 0 : -1;\n}\n\nint main(void) {\n    int *data = NULL;\n    if (allocate(&data, 10) == 0) {\n        data[0] = 42;\n        free(data);\n    }\n}', explain: '`&data` is the address of the pointer. Dereferencing `*out` writes into the caller `data` variable — without that, only the copy would change.' },
      { k: 'callout', tone: 'key', md: 'Same rule as with `int`: if the function has to **change** the caller variable, you need one more level of pointer. `int` → `int *`, `int *` → `int **`.' },
      { k: 'code', lang: 'c', src: '/* A dynamic 2D array */\nint **matrix = malloc(rows * sizeof *matrix);\nfor (int i = 0; i < rows; i++) {\n    matrix[i] = malloc(cols * sizeof **matrix);\n}\n\n/* Free in reverse order! */\nfor (int i = 0; i < rows; i++) {\n    free(matrix[i]);\n}\nfree(matrix);', explain: 'Free the rows first, then the array of row pointers. The other way round you could no longer reach the rows.' },
      { k: 'callout', tone: 'warn', md: 'A row-split matrix is **not contiguous** in memory: every row is its own `malloc`. For large matrices that is slower than one `n*m` block indexed as `matrix[i*m + j]`.' },
      { k: 'text', md: 'The classic example you already know: `int main(int argc, char **argv)`. `argv` is an array of pointers, each pointing at the first character of a string.' },
    ],
    quiz: [
      { k: 'single', q: 'What does an `int **` variable hold?', opts: ['Two int values', 'The address of an `int *` variable', 'An array'], answer: 1, why: 'Each star is a level. `int **` is the address of a place holding an `int *`.' },
      { k: 'single', q: 'Why does the function need an `int **` parameter to set the caller pointer?', opts: ['It is faster', 'Because with `int *` it would only modify the copy', 'Because C requires it'], answer: 1, why: 'C passes everything by value. Changing the caller variable requires its address.' },
      { k: 'order', q: 'In what order do you free an `int **` matrix?', items: ['free(matrix)', 'free(matrix[i]) for every row'], correct: [1, 0], why: 'Rows first, then the array of row pointers. Reversed, you could no longer read the row addresses.' },
      { k: 'single', q: 'What is the drawback of a row-split matrix?', opts: ['It is not contiguous, so it is slower', 'It cannot be indexed', 'It holds fewer elements'], answer: 0, why: 'The cache likes contiguous memory. For large matrices, one block indexed `i*m + j` is faster.' },
      { k: 'single', q: 'What is the type of `argv` in `main`?', opts: ['`char *`', '`char **`', '`int *`'], answer: 1, why: 'An array of pointers: each element points at the first character of a command-line argument.' },
    ],
    note: {
      summary: ['A pointer to a pointer holds the address of a pointer.', 'To let a function set the caller pointer, take an `int **` parameter.', 'Dynamic matrix: an array of row pointers, each row allocated separately.', 'Free in reverse: rows first, then the array.', 'A row-split matrix is not contiguous, so it is slower at scale.', '`char **argv` is the classic example.'],
      terms: [{ term: 'double indirection', def: 'A pointer that points at another pointer.' }, { term: 'out parameter', def: 'A parameter through which a function returns a result.' }, { term: 'contiguous memory', def: 'Data stored in one continuous block.' }],
    },
  },
  {
    day: 14,
    title: 'Function pointers',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A function has an address in memory too, so it can be stored in a pointer. That is how C does callbacks, pluggable sorting rules and command tables.' },
      { k: 'code', lang: 'c', src: '/* Declaration: return type (*name)(parameters) */\nint add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\n\nint main(void) {\n    int (*op)(int, int) = add;\n    printf("%d\\n", op(3, 4));    /* 7 */\n\n    op = sub;\n    printf("%d\\n", op(3, 4));    /* -1 */\n}', explain: 'The parentheses around `*op` are required. Without them you get `int *op(int,int)`, a declaration of a function returning `int *` — something else entirely.' },
      { k: 'text', md: 'The commonest use is the standard `qsort`:\n\n```c\nint compare(const void *a, const void *b) {\n    int x = *(const int *)a, y = *(const int *)b;\n    return (x > y) - (x < y);\n}\nqsort(arr, n, sizeof *arr, compare);\n```\n\n`qsort` does not know what it is sorting — you supply the rule through a function pointer.' },
      { k: 'callout', tone: 'key', md: 'The expression `(x > y) - (x < y)` is the safe comparison: -1, 0 or 1. The naive `return x - y;` can **overflow** on large values, which breaks the sort.' },
      { k: 'callout', tone: 'tip', md: 'Give long function pointer types a `typedef`:\n\n`typedef int (*Op)(int, int);`\n\nThen `Op op = add;` reads cleanly. Without it, tables of function pointers are unreadable.' },
      { k: 'text', md: 'An array of function pointers makes a **command table**: a series of `struct { const char *name; void (*fn)(void); }` entries you search by name. It replaces the long `if` chain in command interpreters.' },
    ],
    quiz: [
      { k: 'single', q: 'Why are parentheses needed around `*op`?', opts: ['Readability', 'Without them it declares a function returning `int *`', 'They are optional'], answer: 1, why: 'Operator precedence. The parentheses bind the star to the name, not to the return type.' },
      { k: 'single', q: 'What is the fourth argument of `qsort` for?', opts: ['The array size', 'The comparison function pointer', 'The sort direction'], answer: 1, why: '`qsort` is generic: it does not know the element type, so you hand it the comparison rule.' },
      { k: 'single', q: 'Why is `return x - y;` wrong for comparison?', opts: ['It is slow', 'It can overflow on large values and break the sort', 'It does not compile'], answer: 1, why: '`(x > y) - (x < y)` never overflows and yields the same three values.' },
      { k: 'single', q: 'What is `typedef int (*Op)(int, int);` for?', opts: ['Faster calls', 'It gives the function pointer type a readable name', 'It creates a new function'], answer: 1, why: 'Function pointer syntax is hard to read. The typedef helps especially in tables.' },
      { k: 'single', q: 'What is a command table?', opts: ['An array of names and function pointers replacing a long `if` chain', 'A database', 'Part of the compiler'], answer: 0, why: 'You look up the name and call the matching function. A new command is a new row.' },
    ],
    note: {
      summary: ['A function has an address, so it fits in a pointer.', 'Declaration: `int (*name)(int, int)` — parentheses required.', '`qsort` receives the sorting rule as a function pointer.', 'Compare with `(x > y) - (x < y)` because it cannot overflow.', '`typedef` makes function pointer types readable.', 'A command table replaces the long `if` chain.'],
      terms: [{ term: 'function pointer', def: 'A pointer holding the address of a function.' }, { term: 'callback', def: 'A function you pass in for the called code to invoke.' }, { term: 'command table', def: 'An array of name and function pointer pairs.' }],
    },
  },
  {
    day: 15,
    title: 'Headers and translation units',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A C program consists of several `.c` files, each compiled **separately**. Those are translation units. For them to know about each other you need `.h` headers.' },
      { k: 'callout', tone: 'key', md: 'The rule in one sentence: **declarations go in the `.h`** (what exists), **definitions go in the `.c`** (how it works). Everyone includes the header; the definition lives in exactly one place.' },
      { k: 'code', lang: 'c', src: '/* rover.h */\n#ifndef ROVER_H\n#define ROVER_H\n\ntypedef struct {\n    int x, y;\n    int battery;\n} Rover;\n\nvoid rover_init(Rover *r);\nint  rover_step(Rover *r, int cm);\n\n#endif /* ROVER_H */', explain: 'The `#ifndef`/`#define`/`#endif` trio is the **include guard**: if the header is pulled in twice, the second pass is empty. Without it you get duplicate type declarations.' },
      { k: 'code', lang: 'c', src: '/* rover.c */\n#include "rover.h"\n\nstatic int valid(int cm) {      /* visible only in this file */\n    return cm > 0 && cm < 100;\n}\n\nvoid rover_init(Rover *r) {\n    r->x = r->y = 0;\n    r->battery = 100;\n}', explain: 'A file-scope `static` function or variable is **invisible** to other translation units. That is encapsulation in C: anything not in the header and marked `static` is internal.' },
      { k: 'callout', tone: 'warn', md: 'Never **define** a global variable in a header: every including file would get its own copy and the link would fail with "multiple definition". The header carries `extern int counter;` and exactly one `.c` holds the definition.' },
      { k: 'callout', tone: 'tip', md: 'A header should be **self-contained**: it includes its own dependencies so it can be pulled in from anywhere. Test it by compiling a file that includes only that one header.' },
    ],
    quiz: [
      { k: 'single', q: 'What goes in a `.h` file?', opts: ['The definition', 'The declaration: what exists', 'Everything'], answer: 1, why: 'The header advertises what is available. The implementation lives in one `.c` file.' },
      { k: 'single', q: 'What is an include guard for?', opts: ['Speeding up compilation', 'Preventing a header from being included twice', 'Hiding the code'], answer: 1, why: 'A double include would produce duplicate type declarations, which is a compile error.' },
      { k: 'single', q: 'What does file-scope `static` mean on a function?', opts: ['It does not change', 'It is visible only in that translation unit', 'There is one copy of it'], answer: 1, why: 'That is C encapsulation: internal helpers stay invisible and their names cannot clash.' },
      { k: 'single', q: 'How do you share a global variable across files?', opts: ['Define it in the header', '`extern` in the header, definition in exactly one `.c`', 'You cannot'], answer: 1, why: 'A header definition would create a copy in every including file, and the linker reports "multiple definition".' },
      { k: 'single', q: 'What does self-contained mean for a header?', opts: ['It is short', 'It includes its own dependencies, so it works from anywhere', 'It has no functions'], answer: 1, why: 'Otherwise include order would matter and the errors would be hard to follow.' },
    ],
    note: {
      summary: ['A program is several translation units (`.c` files) compiled separately.', '`.h`: declaration. `.c`: definition.', 'Include guards (`#ifndef`/`#define`/`#endif`) prevent double inclusion.', 'File-scope `static` hides a member from other translation units.', 'Globals: `extern` in the header, definition in one `.c`.', 'Headers should be self-contained.'],
      terms: [{ term: 'translation unit', def: 'One `.c` file together with everything it includes.' }, { term: 'include guard', def: 'Macro protection against double inclusion.' }, { term: 'extern', def: 'A declaration saying the variable is defined elsewhere.' }],
    },
  },
  {
    day: 16,
    title: 'The preprocessor',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'The preprocessor runs **before** compilation and substitutes text. It does not understand C grammar: it only copies, replaces and skips. That is the source of both its power and its traps.' },
      { k: 'code', lang: 'c', src: '#define MAX_ROVERS 8\n#define SQUARE(x) ((x) * (x))\n\n/* What does this give? */\nint a = SQUARE(3 + 1);\n/* ((3 + 1) * (3 + 1)) = 16  -- correct, thanks to the parentheses */\n\n/* Without them: #define SQUARE(x) x * x\n   3 + 1 * 3 + 1 = 7  -- wrong! */', explain: 'Always wrap macro parameters in parentheses, and the whole expression too. That prevents nine out of ten macro bugs.' },
      { k: 'callout', tone: 'warn', md: 'A macro may **evaluate its parameter more than once**. `SQUARE(i++)` increments `i` twice, which the C standard calls undefined behaviour. Prefer a short `static inline` function where you can: it is type safe and evaluates once.' },
      { k: 'text', md: 'Conditional compilation:\n\n```c\n#ifdef DEBUG\n    printf("battery=%d\\n", r->battery);\n#endif\n\n#if defined(__linux__)\n    /* Linux-specific code */\n#elif defined(_WIN32)\n    /* Windows */\n#endif\n```\n\nWhatever falls into a skipped branch the compiler **never sees** — so its syntax errors stay hidden too.' },
      { k: 'callout', tone: 'key', md: 'Useful built-in macros: `__FILE__`, `__LINE__`, `__func__`. They are what logging and assertion macros are built from:\n\n`#define CHECK(c) do { if (!(c)) fprintf(stderr, "%s:%d: %s\\n", __FILE__, __LINE__, #c); } while (0)`' },
      { k: 'text', md: 'The `do { ... } while (0)` wrapper is not an accident: it makes a multi-line macro behave as a single statement, so it does not break inside an `if` branch without braces. The `#c` operator turns the parameter into a string.' },
    ],
    quiz: [
      { k: 'single', q: 'When does the preprocessor run?', opts: ['After compilation', 'Before compilation, substituting text', 'At run time'], answer: 1, why: 'It only replaces text and does not understand C grammar. The compiler receives the finished text.' },
      { k: 'single', q: 'Why wrap macro parameters in parentheses?', opts: ['Readability', 'Because it is textual substitution and operator precedence would break', 'No need'], answer: 1, why: 'Without them `SQUARE(3+1)` becomes `3 + 1 * 3 + 1`, which is 7, not 16.' },
      { k: 'single', q: 'What is wrong with `SQUARE(i++)`?', opts: ['It is slow', 'The macro evaluates twice, so `i` increments twice — undefined behaviour', 'It does not compile'], answer: 1, why: 'Never pass an expression with side effects to a macro. That is what `static inline` functions are for.' },
      { k: 'single', q: 'What does `__LINE__` contain?', opts: ['The file size', 'The current line number', 'The function name'], answer: 1, why: '`__FILE__`, `__LINE__` and `__func__` are the building blocks of logging and assertion macros.' },
      { k: 'single', q: 'Why is a multi-line macro wrapped in `do { ... } while (0)`?', opts: ['So it runs once', 'So it behaves as a single statement, e.g. inside an `if` branch', 'To make it faster'], answer: 1, why: 'Without it, inside a braceless `if` the macro falls apart and only the first line belongs to the `if`.' },
    ],
    note: {
      summary: ['The preprocessor substitutes text before compilation; it does not know C grammar.', 'Always parenthesise macro parameters and the whole expression.', 'A macro may evaluate its parameter twice: never pass side effects.', 'Prefer `static inline` functions: type safe and evaluated once.', 'Conditional compilation: `#ifdef`, `#if defined(...)`.', '`__FILE__`, `__LINE__`, `__func__` for logging macros.', 'Wrap multi-line macros in `do { ... } while (0)`.'],
      terms: [{ term: 'macro', def: 'A textual substitution rule for the preprocessor.' }, { term: 'conditional compilation', def: 'Skipping code at compile time.' }, { term: 'stringification (#)', def: 'The operator turning a macro parameter into a string.' }],
    },
  },
  {
    day: 17,
    title: 'Make and the build process',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Behind `gcc program.c -o program` there are **four stages**. Knowing which stage reports which error is what makes the messages readable.' },
      { k: 'text', md: '1. **Preprocessor** — resolves `#include` and `#define`. Error: "No such file or directory".\n2. **Compiler** — C to assembly. Errors: syntax and type errors.\n3. **Assembler** — assembly to object code (`.o`).\n4. **Linker** — joins the `.o` files and libraries. Error: "undefined reference".' },
      { k: 'callout', tone: 'key', md: '**"undefined reference"** is always a linker error: the declaration was there (otherwise the compiler would have complained) but the definition is missing. Usual causes: a forgotten `.c` file in the build command, or a missing `-lm` or `-lpthread` flag.' },
      { k: 'code', lang: 'c', src: '/* Makefile -- indentation is a TAB, not spaces! */\nCC      = gcc\nCFLAGS  = -Wall -Wextra -std=c17 -g\nOBJS    = main.o rover.o\n\nrover: $(OBJS)\n\t$(CC) $(CFLAGS) -o rover $(OBJS)\n\n%.o: %.c\n\t$(CC) $(CFLAGS) -c $< -o $@\n\nclean:\n\trm -f rover $(OBJS)', explain: 'The `%.o: %.c` pattern applies to every `.c` file. `$<` is the first prerequisite, `$@` is the target. Make rebuilds only what has a newer source than object.' },
      { k: 'callout', tone: 'warn', md: 'Makefile command lines start with a **tab**. With spaces you get "missing separator", and nothing looks different in the editor. This is the number one Makefile beginner trap.' },
      { k: 'text', md: 'Flags worth always setting:\n\n- `-Wall -Wextra` — most warnings mark a real bug\n- `-std=c17` — a pinned language standard\n- `-g` — debug information for gdb\n- `-O2` — optimisation for release (use `-O0` while developing)' },
      { k: 'callout', tone: 'tip', md: 'While developing, build with `-fsanitize=address,undefined`. It catches out-of-bounds access, use-after-free and undefined behaviour at run time, with an exact line number.' },
    ],
    quiz: [
      { k: 'order', q: 'In what order do the four stages run?', items: ['Linker', 'Compiler', 'Preprocessor', 'Assembler'], correct: [2, 1, 3, 0], why: 'Preprocessor, compiler, assembler, linker. The error source tells you where it stopped.' },
      { k: 'single', q: 'Which stage reports "undefined reference"?', opts: ['Preprocessor', 'Compiler', 'Linker'], answer: 2, why: 'The declaration existed, the definition is missing. Usually a missing `.c` file or `-l` flag.' },
      { k: 'single', q: 'How must Makefile command lines start?', opts: ['With spaces', 'With a tab', 'Either'], answer: 1, why: 'With spaces you get "missing separator", and the difference is invisible in the editor.' },
      { k: 'single', q: 'What does `$<` mean in a Makefile?', opts: ['The target name', 'The first prerequisite', 'All prerequisites'], answer: 1, why: '`$@` is the target, `$<` the first prerequisite, `$^` all of them. Pattern rules need these three.' },
      { k: 'single', q: 'What does `-fsanitize=address,undefined` give you?', opts: ['Faster execution', 'Run-time checks for out-of-bounds access and undefined behaviour', 'A smaller binary'], answer: 1, why: 'It reports the error exactly where it happens, with a line number — saving hours of debugging.' },
    ],
    note: {
      summary: ['Four stages: preprocessor, compiler, assembler, linker.', '"undefined reference" is always a linker error: missing definition or library.', 'Makefile command lines start with a tab.', 'Pattern rule `%.o: %.c`, with `$<` the first prerequisite and `$@` the target.', 'Always build with `-Wall -Wextra -g`.', 'Use `-fsanitize=address,undefined` while developing.'],
      terms: [{ term: 'object code (.o)', def: 'Compiled but not yet linked machine code.' }, { term: 'linker', def: 'The stage joining object files and libraries into an executable.' }, { term: 'pattern rule', def: 'A Makefile rule driven by a filename pattern.' }],
    },
  },
];
