import type { Day } from '../../types';

/** C track, days 17-23. */
export const cEnD: Day[] = [
  {
    day: 17,
    title: 'File handling',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'File handling in C lives in `<stdio.h>`. The central type is `FILE *`: a pointer you get from the system and must give back.' },
      { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nFILE *f = fopen("data.txt", "r");\nif (f == NULL) {\n    perror("data.txt");        /* prints exactly what went wrong */\n    return -1;\n}\n\nchar line[256];\nwhile (fgets(line, sizeof line, f) != NULL) {\n    printf("%s", line);\n}\n\nfclose(f);', explain: '`perror` prints the system error message — "No such file" or "Permission denied". That says far more than your own "Error" label.' },
      { k: 'callout', tone: 'key', md: 'The open modes:\n\n- `"r"` — read, the file must exist\n- `"w"` — write, **truncates** an existing file\n- `"a"` — append to the end\n- `"r+"` — read and write\n- `"b"` suffix (`"rb"`) — binary mode, matters on Windows' },
      { k: 'callout', tone: 'warn', md: 'Mode `"w"` **truncates immediately** on open, before you write anything. Type `"w"` where you meant `"r"` and the data is gone in an instant. It is the costliest typo in C file handling.' },
      { k: 'text', md: 'Reading functions and when to use them:\n\n- `fgets(buffer, size, f)` — one line, **with a size limit**. Use this.\n- `fread(buffer, size, count, f)` — raw bytes, for binary files\n- `fscanf(f, "%d", &n)` — formatted reading; convenient, but awkward on malformed input\n- `gets()` — **never**. It has no size limit, which is why it was removed from the standard.' },
      { k: 'callout', tone: 'tip', md: 'After writing, `fclose` flushes the buffer to disk. If the program crashes without `fclose`, the last few kilobytes can be lost. For long-running logging, call `fflush(f)` periodically.' },
    ],
    quiz: [
      { k: 'single', q: 'What does `fopen` return on failure?', opts: ['0', 'NULL', 'It throws'], answer: 1, why: 'Always check it. `perror` then prints the exact system error.' },
      { k: 'single', q: 'What happens when you open with `"w"`?', opts: ['It appends', 'It truncates the existing file immediately', 'It errors if the file exists'], answer: 1, why: 'The file is emptied before you write. A typo for `"r"` destroys the data instantly.' },
      { k: 'single', q: 'Which read function should you use for lines?', opts: ['`gets`', '`fgets`', '`scanf`'], answer: 1, why: '`fgets` takes a size limit. `gets` does not, which is why it was removed from the standard.' },
      { k: 'single', q: 'What is `perror` for?', opts: ['Opening the file', 'Printing the exact system error message', 'Closing the file'], answer: 1, why: '"No such file" and "Permission denied" are different problems; your own "Error" label hides that.' },
      { k: 'single', q: 'Why call `fflush` during long logging?', opts: ['It is faster', 'Because buffered data would be lost in a crash', 'Because it is required'], answer: 1, why: '`fclose` flushes the buffer. If the program crashes first, the last kilobytes are gone.' },
    ],
    note: {
      summary: ['File handling is in `<stdio.h>`, through the `FILE *` type.', '`fopen` returns NULL on failure; `perror` prints the reason.', 'Modes: `r` read, `w` truncate, `a` append, `b` binary.', 'Mode `"w"` truncates the file the moment it opens.', 'Use `fgets` for lines, `fread` for bytes. Never `gets`.', '`fclose` flushes the buffer; use `fflush` for long runs.'],
      terms: [{ term: 'FILE *', def: 'The pointer identifying an open file.' }, { term: 'perror', def: 'A function printing the last system error message.' }, { term: 'buffering', def: 'Collecting writes in memory before committing them to disk.' }],
    },
  },
  {
    day: 18,
    title: 'Bitwise operations',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Bitwise operations manipulate the **individual bits** of a number. On microcontrollers, in compression, and with flag fields they are unavoidable.' },
      { k: 'callout', tone: 'key', md: 'The five operators:\n\n- `&` — AND: both must be 1\n- `|` — OR: either suffices\n- `^` — XOR: exactly one\n- `~` — NOT: every bit flips\n- `<<` / `>>` — shift left / right' },
      { k: 'code', lang: 'c', src: '#define LED   (1u << 2)      /* 0000 0100 */\n#define MOTOR (1u << 5)      /* 0010 0000 */\n\nunsigned port = 0;\n\nport |=  LED;                /* turn on   */\nport &= ~MOTOR;              /* turn off  */\nport ^=  LED;                /* toggle    */\n\nif (port & LED) { /* is it on? */ }', explain: 'These four patterns — `|=` sets, `&= ~` clears, `^=` toggles, `&` tests — are the whole of bit manipulation. Every microcontroller program is built from them.' },
      { k: 'text', md: 'Shifting multiplies and divides by powers of two:\n\n`x << 3` is the same as `x * 8`\n`x >> 1` is the same as `x / 2` (for non-negative values)\n\nThis used to be written for speed; today the compiler does it for you, so **write the clearer form** unless you are working with bitmasks.' },
      { k: 'callout', tone: 'warn', md: 'Do **not shift signed values**: right-shifting a negative number is implementation defined, and left-shifting is undefined behaviour on overflow. Always use `unsigned` types for bit work.' },
      { k: 'callout', tone: 'tip', md: 'In `1u << n` the `u` is not decoration: `1 << 31` on a signed `int` is already undefined behaviour, while `1u << 31` is fine.' },
    ],
    quiz: [
      { k: 'single', q: 'How do you set a bit?', opts: ['`port &= mask`', '`port |= mask`', '`port ^= mask`'], answer: 1, why: 'OR puts the 1 in and leaves the other bits untouched.' },
      { k: 'single', q: 'How do you clear a bit?', opts: ['`port |= mask`', '`port &= ~mask`', '`port = 0`'], answer: 1, why: 'AND with the inverted mask zeroes that one bit and keeps the rest.' },
      { k: 'single', q: 'What does `^=` with a mask do?', opts: ['Sets it', 'Toggles the bit', 'Tests it'], answer: 1, why: 'XOR flips every selected bit to its opposite.' },
      { k: 'single', q: 'Why use `unsigned` for bit work?', opts: ['It is faster', 'Because shifting signed values is implementation defined or undefined', 'It uses less space'], answer: 1, why: 'Right-shifting a negative is implementation defined, left-shifting on overflow is undefined.' },
      { k: 'single', q: 'Why `1u << 31` rather than `1 << 31`?', opts: ['It is shorter', 'Because on a signed `int` that is undefined behaviour', 'No difference'], answer: 1, why: 'Bit 31 is the sign bit on a 32-bit `int`. The `u` suffix makes it unsigned.' },
    ],
    note: {
      summary: ['Operators: `&` AND, `|` OR, `^` XOR, `~` NOT, `<<`/`>>` shift.', 'Set: `|=`. Clear: `&= ~`. Toggle: `^=`. Test: `&`.', 'Build a mask with `1u << n`.', 'Shifting is multiply/divide by powers of two, but the compiler does that anyway.', 'Always use `unsigned` types for bitwise work.'],
      terms: [{ term: 'bitmask', def: 'A value whose set bits select which bits to act on.' }, { term: 'shift', def: 'Moving bits left or right.' }, { term: 'XOR', def: 'An operation giving 1 when exactly one input is 1.' }],
    },
  },
  {
    day: 19,
    title: 'Enums and unions',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Two type constructs many people skip, although they make code both clearer and safer.' },
      { k: 'code', lang: 'c', src: '/* enum: named integers */\ntypedef enum {\n    STATE_IDLE,\n    STATE_DRIVING,\n    STATE_TURNING,\n    STATE_FAULT\n} State;\n\nState s = STATE_DRIVING;\n\nswitch (s) {\n    case STATE_IDLE:    break;\n    case STATE_DRIVING: break;\n    case STATE_TURNING: break;\n    case STATE_FAULT:   break;\n}', explain: 'Enum values are numbered from 0 automatically. In a `switch` the compiler **warns** when you miss a case — the biggest advantage over `#define` constants.' },
      { k: 'callout', tone: 'key', md: 'An enum is not just cosmetic: add a new state and the compiler walks you through every `switch` that does not handle it. With plain numbers or macros that safety net does not exist.' },
      { k: 'code', lang: 'c', src: '/* union: one memory area, several views */\ntypedef union {\n    float f;\n    unsigned u;\n    unsigned char b[4];\n} Num32;\n\nNum32 n;\nn.f = 1.5f;\nprintf("%08x\\n", n.u);         /* the bit pattern of the float */\nprintf("%02x\\n", n.b[0]);      /* the first byte */', explain: 'Every member of a union sits at **the same address**. Its size is that of the largest member, not their sum. Only one member is valid at a time.' },
      { k: 'callout', tone: 'warn', md: 'A union **does not track** which member is valid. Write `f` and read `u` and you get no error — just a meaningless result. That is why a union usually travels with an enum: the **tagged union**.' },
      { k: 'code', lang: 'c', src: 'typedef struct {\n    enum { VAL_INT, VAL_FLOAT, VAL_STRING } type;\n    union {\n        int   i;\n        float f;\n        char *s;\n    } value;\n} Value;', explain: 'The tagged union is the safe pattern: the `type` field says which member is valid, and the code checks it before reading.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the main advantage of an enum over `#define`?', opts: ['Less memory', 'The compiler warns when a `switch` misses a case', 'It is faster'], answer: 1, why: 'Adding a new state makes the compiler walk you through every incomplete `switch`.' },
      { k: 'single', q: 'Where do the members of a union live?', opts: ['One after another', 'At the same address, overlapping', 'In separate memory'], answer: 1, why: 'The size of a union is that of its largest member, not the sum.' },
      { k: 'single', q: 'What happens if you write one union member and read another?', opts: ['Compile error', 'No error, just a meaningless result', 'A run-time exception'], answer: 1, why: 'A union does not track which member is valid. That is why you want a tagged union.' },
      { k: 'single', q: 'What is a tagged union?', opts: ['An unnamed union', 'A struct where an enum says which union member is valid', 'Two nested unions'], answer: 1, why: 'The safe pattern: the type field lets the code validate before reading.' },
      { k: 'single', q: 'Where do enum values start by default?', opts: ['At 1', 'At 0', 'Randomly'], answer: 1, why: 'From zero, incrementing by one. You can assign values manually and numbering continues from there.' },
    ],
    note: {
      summary: ['An enum gives named integers, numbered from 0.', 'The compiler warns about a missing enum case in a `switch`.', 'Union members share an address; its size is that of the largest member.', 'A union does not track which member is valid.', 'Tagged union: an enum field plus a union — the safe pattern.'],
      terms: [{ term: 'enum', def: 'A type of named integer constants.' }, { term: 'union', def: 'A type storing several members in the same memory.' }, { term: 'tagged union', def: 'A union plus a type field marking the valid member.' }],
    },
  },
  {
    day: 20,
    title: 'const and volatile',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'Two qualifiers that are not about storage but about a **promise to the compiler**. Misusing either produces bugs that are hard to find.' },
      { k: 'callout', tone: 'key', md: '`const` means: **I will not write through this**. Not that the value cannot change — only that this reference will not change it.' },
      { k: 'code', lang: 'c', src: '/* Read right to left! */\nconst char *p;        /* pointer to const char: *p read-only, p writable */\nchar *const q;        /* const pointer to char: q read-only, *q writable */\nconst char *const r;  /* neither is writable */\n\nvoid print(const char *text);   /* a promise: I will not modify it */', explain: 'Reading right to left always works. In a function signature `const` is also documentation: the caller knows their string is safe.' },
      { k: 'text', md: '`volatile` is the opposite: it tells the compiler the variable **can change at any time** from outside the code. So it may not optimise the reads away.' },
      { k: 'code', lang: 'c', src: 'volatile int interrupt_fired = 0;\n\n/* The interrupt handler writes: */\nvoid ISR(void) { interrupt_fired = 1; }\n\n/* The main loop reads: */\nwhile (!interrupt_fired) {\n    /* without volatile the compiler would read once,\n       see 0, and make an infinite loop */\n}', explain: 'Without `volatile` the compiler would quite reasonably assume the variable does not change inside the loop and optimise the re-read away.' },
      { k: 'callout', tone: 'warn', md: '`volatile` does **not make a variable thread safe**. It provides no atomicity and no synchronisation. For data shared between threads you need `_Atomic` or a mutex — `volatile` is only right for interrupts and hardware registers.' },
      { k: 'callout', tone: 'tip', md: '`const` is more than documentation: the compiler checks it and the caller sees the intent. Mark every pointer parameter you do not modify as `const` — it is the cheapest quality improvement in C.' },
    ],
    quiz: [
      { k: 'single', q: 'What does `const` mean?', opts: ['The value can never change', 'I will not write through this reference', 'It goes into constant memory'], answer: 1, why: 'The value can still change through another reference. `const` is a promise to the compiler.' },
      { k: 'single', q: 'What is the difference between `const char *p` and `char *const q`?', opts: ['Nothing', 'In the first `*p` is read-only, in the second `q` is', 'The first is faster'], answer: 1, why: 'Read right to left: what follows `const` is the protected part.' },
      { k: 'single', q: 'What does `volatile` tell the compiler?', opts: ['That it changes fast', 'That the variable can change externally, so reads must not be optimised away', 'That it is thread safe'], answer: 1, why: 'Without it the compiler reads once and the loop never exits.' },
      { k: 'single', q: 'Does `volatile` make something thread safe?', opts: ['Yes', 'No: it provides no atomicity and no synchronisation', 'Only for reads'], answer: 1, why: 'Shared thread data needs `_Atomic` or a mutex. `volatile` is for interrupts and hardware registers.' },
      { k: 'single', q: 'When should a pointer parameter be `const`?', opts: ['Never', 'Whenever you do not modify through it', 'Only for large structs'], answer: 1, why: 'The compiler checks it and the caller sees the intent. It is the cheapest quality win in C.' },
    ],
    note: {
      summary: ['`const` is a promise: I will not write through this reference.', 'Read declarations right to left: `const char *p` differs from `char *const q`.', '`volatile` forbids optimising reads away.', '`volatile` is for interrupts and hardware registers.', '`volatile` is not thread safe; use `_Atomic` or a mutex.', 'Mark every unmodified pointer parameter `const`.'],
      terms: [{ term: 'const', def: 'A qualifier forbidding writes through that reference.' }, { term: 'volatile', def: 'A qualifier marking a variable that can change externally.' }, { term: '_Atomic', def: 'A qualifier providing thread-safe indivisible operations.' }],
    },
  },
  {
    day: 21,
    title: 'Debugging with gdb',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Debugging with `printf` works for a while. **gdb** stops the program, shows you the call chain, and lets you step through the code.' },
      { k: 'callout', tone: 'key', md: 'Compile with `-g`, or gdb cannot see source lines and variable names:\n\n`gcc -g -O0 program.c -o program`\n\n`-O0` matters too: optimised, the lines get scrambled and variables can vanish into registers.' },
      { k: 'text', md: 'The ten commands that carry you:\n\n- `run` (`r`) — start\n- `break file.c:42` (`b`) — breakpoint\n- `next` (`n`) — next line, stepping over calls\n- `step` (`s`) — step into the function\n- `continue` (`c`) — on to the next breakpoint\n- `print var` (`p`) — show a value\n- `backtrace` (`bt`) — the whole call chain\n- `frame 2` (`f`) — switch to a call level\n- `watch var` — stop when the variable changes\n- `quit` (`q`)' },
      { k: 'code', lang: 'c', src: '/* A typical session after a crash:\n\n$ gcc -g -O0 rover.c -o rover\n$ gdb ./rover\n(gdb) run\nProgram received signal SIGSEGV, Segmentation fault.\n0x... in rover_step (r=0x0, cm=10) at rover.c:42\n42          r->x += cm;\n\n(gdb) bt\n#0  rover_step (r=0x0, cm=10) at rover.c:42\n#1  main () at rover.c:88\n\n(gdb) frame 1\n(gdb) print rover\n$1 = (Rover *) 0x0\n*/', explain: '`bt` immediately shows that `main` passed a NULL pointer. The bug is not on line 42 but on line 88 — without `bt` you would not see that.' },
      { k: 'callout', tone: 'tip', md: 'A **core dump** lets you do the autopsy later. Enable it with `ulimit -c unlimited`, then after a crash: `gdb ./program core`. A test that failed overnight can still be examined in the morning.' },
      { k: 'callout', tone: 'warn', md: 'If gdb shows `<optimized out>` for a variable, you compiled with optimisation. Rebuild with `-O0` — otherwise you are looking at code that no longer matches the source.' },
    ],
    quiz: [
      { k: 'single', q: 'Which flags do you need for gdb?', opts: ['`-O2`', '`-g` and `-O0`', '`-Wall`'], answer: 1, why: '`-g` supplies debug information, `-O0` keeps lines and variables matching the source.' },
      { k: 'single', q: 'What does `backtrace` show?', opts: ['The variables', 'The whole call chain at the moment of failure', 'Memory usage'], answer: 1, why: 'It reveals that the bug is often not where the crash happened.' },
      { k: 'single', q: 'What is the difference between `next` and `step`?', opts: ['`step` enters the function, `next` steps over it', '`next` is faster', 'No difference'], answer: 0, why: 'When the bug is not inside the called function, `next` moves you along faster.' },
      { k: 'single', q: 'What is `watch` for?', opts: ['Printing a variable', 'Stopping the program when the variable changes', 'Timing'], answer: 1, why: 'Useful when you do not know where a value goes wrong.' },
      { k: 'single', q: 'What does `<optimized out>` mean?', opts: ['The variable was deleted', 'You compiled with optimisation; rebuild with `-O0`', 'gdb is broken'], answer: 1, why: 'Optimised, a variable may live in a register or vanish, and line numbers no longer match the source.' },
    ],
    note: {
      summary: ['Compile with `-g -O0` or gdb cannot see the source.', 'Core commands: run, break, next, step, continue, print, backtrace, frame, watch.', '`backtrace` shows where the trouble started, not where it crashed.', '`watch` stops when a variable changes.', 'Core dumps: `ulimit -c unlimited`, then `gdb ./program core`.', '`<optimized out>` means rebuild with `-O0`.'],
      terms: [{ term: 'breakpoint', def: 'A line where the debugger halts the program.' }, { term: 'backtrace', def: 'The chain of function calls up to the current point.' }, { term: 'core dump', def: 'A file holding the memory image at the moment of a crash.' }],
    },
  },
  {
    day: 22,
    title: 'Valgrind and memory errors',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Memory bugs in C are **silent**: the program runs, and only sometimes, somewhere else, it crashes. Valgrind and AddressSanitizer make them visible immediately.' },
      { k: 'text', md: 'The four commonest memory errors:\n\n- **Out-of-bounds access** — writing past the allocated block\n- **Use after free** — referencing memory after `free`\n- **Double free** — freeing the same block twice\n- **Uninitialised read** — reading memory you never wrote' },
      { k: 'code', lang: 'c', src: '/* $ valgrind --leak-check=full --track-origins=yes ./program\n\n==1234== Invalid write of size 4\n==1234==    at 0x1091AE: main (test.c:7)\n==1234==  Address 0x4a4b040 is 0 bytes after a block of size 40 alloc\'d\n==1234==    at 0x484...: malloc\n==1234==    by 0x109195: main (test.c:5)\n*/', explain: 'Valgrind tells you where the error is (line 7), what kind it is (invalid write), and where the block was allocated (line 5). No error message can give you more.' },
      { k: 'callout', tone: 'key', md: '**AddressSanitizer** gives the same thing, built into the compile and far faster:\n\n`gcc -fsanitize=address,undefined -g program.c`\n\nValgrind slows a program 10 to 50 times; ASan only about twice. During development ASan is therefore the better choice.' },
      { k: 'text', md: 'Valgrind leak categories:\n\n- **definitely lost** — certainly leaked, fix this\n- **indirectly lost** — part of a leaked structure\n- **possibly lost** — only an interior pointer remains; usually suspicious\n- **still reachable** — a pointer existed at exit; often harmless' },
      { k: 'callout', tone: 'warn', md: 'These tools only find bugs on **code that actually runs**. If a faulty branch triggers on one input in a hundred, Valgrind will not see it either. That is why you run them over your **tests**, not just a manual trial.' },
    ],
    quiz: [
      { k: 'single', q: 'Why are C memory bugs dangerous?', opts: ['They stop the program immediately', 'They are silent: the program runs and crashes later, elsewhere', 'They slow things down'], answer: 1, why: 'The place of the bug and the place of the symptom are often hundreds of lines apart.' },
      { k: 'single', q: 'Which is faster during development?', opts: ['Valgrind', 'AddressSanitizer', 'The same'], answer: 1, why: 'Valgrind slows execution 10 to 50 times; ASan about twice.' },
      { k: 'single', q: 'What does "definitely lost" mean?', opts: ['Certainly leaked memory, fix it', 'A pointer still exists', 'Not an error'], answer: 0, why: 'No pointer remains to it, so it can never be freed.' },
      { k: 'single', q: 'What is `--track-origins=yes` for?', opts: ['Speed', 'It shows where an uninitialised value came from', 'Finding leaks'], answer: 1, why: 'On an uninitialised read it tells you which allocation the value came from.' },
      { k: 'single', q: 'What is the limitation of these tools?', opts: ['They only run on Linux', 'They only find bugs in code that actually executes', 'They only work on small programs'], answer: 1, why: 'That is why you run them over the full test suite, not just one manual trial.' },
    ],
    note: {
      summary: ['C memory bugs are silent: they surface later and elsewhere.', 'Four kinds: out-of-bounds, use after free, double free, uninitialised read.', 'Valgrind: `--leak-check=full --track-origins=yes`.', 'AddressSanitizer: `-fsanitize=address,undefined`, far faster.', 'Leak categories: definitely, indirectly, possibly lost, still reachable.', 'They only see executed code, so run them over your tests.'],
      terms: [{ term: 'out-of-bounds access', def: 'Reading or writing outside an allocated block.' }, { term: 'AddressSanitizer', def: 'A compile-time instrumented run-time memory checker.' }, { term: 'definitely lost', def: 'Memory with no remaining pointer to it.' }],
    },
  },
  {
    day: 23,
    title: 'Static and dynamic libraries',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **library** is reusable compiled code. There are two ways to attach it to a program, and the difference is real.' },
      { k: 'callout', tone: 'key', md: '**Static** (`.a`): the code is **copied into** the executable. A bigger binary, but self-contained: no run-time dependency.\n\n**Dynamic** (`.so` on Linux, `.dll` on Windows): the code loads at run time. A smaller binary, and the library can be updated without rebuilding the program.' },
      { k: 'code', lang: 'c', src: '/* Building a static library\n$ gcc -c rover.c motor.c             # .o files\n$ ar rcs librobot.a rover.o motor.o\n$ gcc main.c -L. -lrobot -o program\n\n   Building a dynamic library\n$ gcc -fPIC -c rover.c motor.c       # position independent code\n$ gcc -shared -o librobot.so rover.o motor.o\n$ gcc main.c -L. -lrobot -o program\n$ LD_LIBRARY_PATH=. ./program        # must be findable at run time\n*/', explain: '`-lrobot` resolves to `librobot`: the linker adds the `lib` prefix and the extension. `-fPIC` is needed for a dynamic library because the code can load anywhere in memory.' },
      { k: 'text', md: 'Which to choose?\n\n- **Static**: an embedded system, a tool shipped as a single file, or an unpredictable runtime environment.\n- **Dynamic**: when several programs share the library, or when a security update must ship without rebuilding.' },
      { k: 'callout', tone: 'warn', md: 'The classic problem with dynamic libraries is **dependency hell**: the program expects a different version from the one on the machine. `ldd ./program` shows which libraries it loads and which it cannot find.' },
      { k: 'callout', tone: 'tip', md: '`.so` files are usually versioned: `librobot.so.1.2.3`, with symbolic links pointing at it. The **soname** (`librobot.so.1`) marks how far the interface stays compatible — when the major number rises, older programs can no longer use it.' },
    ],
    quiz: [
      { k: 'single', q: 'What defines a static library?', opts: ['It loads at run time', 'The code is copied into the executable', 'It is only needed to compile'], answer: 1, why: 'A larger binary, but no run-time dependency: it runs standalone.' },
      { k: 'single', q: 'What does the `-lrobot` flag mean?', opts: ['Compile `robot.c`', 'Link the library named `librobot`', 'Create a library'], answer: 1, why: 'The linker adds the `lib` prefix and the extension.' },
      { k: 'single', q: 'Why does a dynamic library need `-fPIC`?', opts: ['It is faster', 'Because the code must be loadable anywhere in memory', 'It makes it smaller'], answer: 1, why: 'Position independent code assumes no fixed load address.' },
      { k: 'single', q: 'When should you pick a static library?', opts: ['When several programs share it', 'For an embedded system or a single-file tool', 'Always'], answer: 1, why: 'No run-time dependency, so it works in an unpredictable environment.' },
      { k: 'single', q: 'What does `ldd ./program` show?', opts: ['The source files', 'Which dynamic libraries it loads and which it cannot find', 'Memory usage'], answer: 1, why: 'It is the first command to run on a dependency problem.' },
    ],
    note: {
      summary: ['Static (`.a`): copied into the binary, no run-time dependency.', 'Dynamic (`.so`): loaded at run time, updatable without rebuilding.', 'Build with `ar rcs` for static, `-fPIC -shared` for dynamic.', '`-lrobot` refers to the `librobot` library.', 'Static for embedded systems, dynamic for shared use.', '`ldd ./program` shows the run-time dependencies.'],
      terms: [{ term: 'static library', def: 'A compiled code collection copied into the binary.' }, { term: 'PIC', def: 'Position independent code, loadable at any address.' }, { term: 'soname', def: 'The compatibility version of a dynamic library interface.' }],
    },
  },
];
