import type { Track } from '../../types';
import { cEnB } from './c-b';
import { cEnC } from './c-c';

export const cEn: Track = {
  id: 'c',
  title: 'C',
  blurb: 'Memory, pointers, programming close to the hardware.',
  plannedTitles: [
    'Compiling and running',
    'Types and memory',
    'Pointers',
    'Branching and loops',
    'Functions',
    'Arrays',
    'How pointers and arrays relate',
    'Strings in C',
    'Structs',
    'Dynamic memory: malloc and free',
    'Memory leaks',
    'Pointers to pointers',
    'Function pointers',
    'Headers and translation units',
    'The preprocessor',
    'Make and the build process',
    'Working with files',
    'Bitwise operations',
    'Enums and unions',
    'const and volatile',
    'Debugging with gdb',
    'Valgrind and memory errors',
    'Static and dynamic libraries',
    'The standard library',
    'Microcontrollers and C',
    'Writing registers',
    'Interrupts',
    'The style of embedded programming',
    'A small embedded program',
    'The complete project',
  ],
  days: [
    {
      day: 1,
      title: 'Compiling and running',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'C is the language of most operating systems, of microcontroller firmware, and of the Python interpreter itself. It sits close to the machine: roughly what you write is what happens.' },
        { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nint main(void) {\n    printf("Hello, C!\\n");\n    return 0;\n}', explain: '`#include` pulls in the declaration of `printf`. `return 0` means the program finished without error — the operating system reads that.' },
        { k: 'text', md: 'Compiling and running on Linux:\n\n```\ngcc hello.c -o hello\n./hello\n```\n\n`-o hello` names the output file. Without it you get `a.out`.' },
        { k: 'callout', tone: 'key', md: 'C is a **compiled** language: the source becomes machine code and that runs. No interpreter, no virtual machine. That is why it is fast, and why it must be recompiled for each machine.' },
        { k: 'callout', tone: 'warn', md: 'Always compile with warnings on: `gcc -Wall -Wextra hello.c -o hello`. C compiles plenty of mistakes without a word, and most of those warnings become runtime crashes later.' },
      ],
      quiz: [
        { k: 'single', q: 'What does `#include <stdio.h>` do?', opts: ['Runs the program', 'Pulls in the standard input/output declarations, such as printf', 'Compiles the file'], answer: 1, why: 'The header tells the compiler that `printf` exists and what arguments it takes. Without it you get a warning or an error.' },
        { k: 'single', q: 'What does `return 0` at the end of main mean?', opts: ['It prints zero', 'The program finished without error', 'It restarts the program'], answer: 1, why: "main's return value is the exit code. Zero means success; anything else signals a problem to the operating system." },
        { k: 'single', q: 'Why compile with `-Wall -Wextra`?', opts: ['The program runs faster', 'Because C would silently compile many dangerous mistakes', 'The file is smaller'], answer: 1, why: 'C is permissive: it accepts plenty that later crashes. Warnings surface those at compile time.' },
        { k: 'single', q: 'What is the difference between running C and Python?', opts: ['None', 'C compiles to machine code; Python is run by an interpreter', 'C is slower'], answer: 1, why: 'C source becomes directly executable machine code. Python code is interpreted as it runs — slower, but more portable.' },
      ],
      note: {
        summary: ['C is compiled: the source becomes machine code, with no interpreter or VM.', '`gcc hello.c -o hello` compiles, `./hello` runs.', '`#include` pulls in a header holding function declarations.', "main's `return 0` is the exit code: zero means success.", 'Always compile with `-Wall -Wextra` — warnings are tomorrow\'s crashes.'],
        terms: [{ term: 'compiler', def: 'A program turning source code into executable machine code.' }, { term: 'header file', def: 'A file of declarations pulled in with `#include`.' }, { term: 'exit code', def: "main's return value, read by the operating system." }],
      },
    },
    {
      day: 2,
      title: 'Types and memory',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'In C a variable is not an abstraction but **a place in memory** of a certain number of bytes. Understand that and pointers stop being hard.' },
        { k: 'code', lang: 'c', src: '#include <stdio.h>\n\nint main(void) {\n    int a = 42;\n    double d = 3.14;\n    char c = \'X\';\n\n    printf("%d %f %c\\n", a, d, c);\n    printf("%zu %zu %zu\\n", sizeof(a), sizeof(d), sizeof(c));\n    return 0;\n}', explain: '`printf` works from **format specifiers**: `%d` integer, `%f` decimal, `%c` character. `sizeof` tells you how many bytes it occupies.' },
        { k: 'callout', tone: 'warn', md: 'Give the wrong specifier (`%d` for a `double`) and C **says nothing** — it just prints rubbish or crashes. This is one of the sharpest edges of the language.' },
        { k: 'text', md: 'Typical sizes on a 64-bit machine: `char` 1 byte, `int` 4, `double` 8. But that is **not guaranteed** — the standard sets only minimums. On an embedded system `int` can be 2 bytes.' },
        { k: 'callout', tone: 'key', md: 'An **uninitialised** variable in C is not zero but rubbish: whatever happened to be in that memory. Such a bug works sometimes and not others — which makes it the hardest kind to find. Always give an initial value.' },
      ],
      quiz: [
        { k: 'single', q: 'What is the value of an uninitialised local variable in C?', opts: ['Zero', 'Undefined rubbish', 'NULL'], answer: 1, why: 'C does not zero local variables. Whatever was in that memory remains — which is why such a program sometimes behaves and sometimes does not.' },
        { k: 'numeric', q: 'How many bytes is a `double` typically on a 64-bit machine?', answer: 8, tol: 0.5, why: '`double` is usually 8 bytes (64 bits). `int` is 4, and `char` is by definition always 1.' },
        { k: 'single', q: 'What happens with a wrong format specifier?', opts: ['A compile error', 'The program prints rubbish or crashes', 'It fixes itself'], answer: 1, why: '`printf` reads the specifiers at runtime and believes what you tell it. With the wrong type it misreads the bytes.' },
        { k: 'single', q: 'What does `sizeof(x)` give?', opts: ["The variable's value", 'How many bytes it occupies', "The variable's name"], answer: 1, why: '`sizeof` gives the size of a type in bytes. It is indispensable when allocating memory dynamically.' },
      ],
      note: {
        summary: ['In C a variable is a place in memory of a certain number of bytes.', '`sizeof` gives the size; `char` is 1, `int` typically 4, `double` 8 bytes.', 'Sizes are not guaranteed — they can differ on an embedded system.', '`printf` uses format specifiers: %d, %f, %c; a wrong one prints rubbish.', 'An uninitialised local variable holds rubbish, not zero.'],
        terms: [{ term: 'sizeof', def: 'An operator giving the size of a type or variable in bytes.' }, { term: 'format specifier', def: "The marker in printf giving the value's type, such as %d." }, { term: 'uninitialised variable', def: 'A variable with no initial value, whose contents are undefined.' }],
      },
    },
    {
      day: 3,
      title: 'Pointers',
      minutes: 24,
      lesson: [
        { k: 'text', md: 'Pointers are the notorious topic of C, yet they are simple: **a pointer is a variable holding a memory address**. Not the value — where the value is.' },
        { k: 'code', lang: 'c', src: 'int a = 42;\nint *p = &a;      // p holds the address of a\n\nprintf("%d\\n", a);         // 42  — the value\nprintf("%p\\n", (void*)p);  // 0x7ffd...  — the address\nprintf("%d\\n", *p);        // 42  — the value at that address\n\n*p = 99;\nprintf("%d\\n", a);         // 99  — a changed too!', explain: '`&` means "the address of", `*` means "show me what is there". They are opposites.' },
        { k: 'callout', tone: 'key', md: 'Why does this matter? Because in C a function receives a **copy** of its parameter. If it has to change the caller\'s variable, it must be given the address — there is no other way.' },
        { k: 'code', lang: 'c', src: 'void increment(int *x) {\n    *x = *x + 1;\n}\n\nint main(void) {\n    int n = 5;\n    increment(&n);\n    printf("%d\\n", n);    // 6\n    return 0;\n}', explain: '`&n` passes the address and the function writes through `*x` to the original. Without it, `increment(n)` would only raise the copy.' },
        { k: 'callout', tone: 'warn', md: 'Dereferencing a **NULL pointer** (`*p` when `p == NULL`) crashes instantly. Before dereferencing a pointer you are not sure about, check it: `if (p != NULL)`.' },
      ],
      quiz: [
        { k: 'single', q: 'What does a pointer hold?', opts: ['The value', 'A memory address', "The variable's name"], answer: 1, why: 'A pointer holds **where** the value is. You reach the value itself through the `*` operator.' },
        { k: 'single', q: 'What does `&a` do?', opts: ["Gives a's value", "Gives a's memory address", 'Doubles a'], answer: 1, why: '`&` is the address-of operator. That address is what you can store in a pointer.' },
        { k: 'output', q: 'What does this print?', code: 'int a = 5;\nint *p = &a;\n*p = 10;\nprintf("%d", a);', lang: 'c', opts: ['5', '10', '0'], answer: 1, why: '`*p = 10` writes at the address where `a` lives, so `a` itself changes.' },
        { k: 'single', q: 'Why does a function need a pointer to change the caller\'s variable?', opts: ['It is faster', 'Because otherwise it only receives a copy', 'Because C requires it'], answer: 1, why: 'Parameters pass by value: the function would change the copy. With the address it reaches the original.' },
      ],
      note: {
        summary: ['A pointer is a variable holding a memory address, not the value itself.', '`&` gives the address; `*` dereferences, showing what is at that address.', 'Functions receive parameters by value — changing the original needs its address.', '`*p = x` writes at the place the pointer points to.', 'Dereferencing NULL crashes instantly; check before you dereference.'],
        terms: [{ term: 'pointer', def: 'A variable holding a memory address.' }, { term: 'address-of operator (&)', def: "Returns a variable's memory address." }, { term: 'dereference (*)', def: 'Accessing the value at the address a pointer holds.' }],
      },
    },
    ...cEnB,
    ...cEnC,
  ],
};
