import type { Day } from '../../types';

/** CAD track, days 20-26. */
export const cadEnE: Day[] = [
  {
    day: 20,
    title: 'Designing a motor mount',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A motor mount is the first real design task: you are given a standard part and must produce something that fits it, stays stiff and can actually be assembled.' },
      { k: 'callout', tone: 'key', md: 'Design always starts with the **datasheet**. A motor mount needs four dimensions:\n\n1. The **pilot boss** diameter and depth\n2. The **bolt circle** diameter and the hole count\n3. The **shaft** diameter and protrusion\n4. The motor **length** and connector position' },
      { k: 'text', md: 'A standard NEMA 17 stepper, for instance: 42.3 mm square, a 31 mm bolt circle with four M3 holes, a 22 mm pilot boss, a 5 mm shaft. Those numbers go into the parameter list, not straight into the sketch.' },
      { k: 'callout', tone: 'warn', md: 'The **pilot boss** matters more than the screws. It holds the motor exactly in place; the screws only clamp it. If the boss is loose, the motor shifts within the hole clearance and the gear mesh goes out. Keep the boss clearance at 0.1–0.2 mm, no more.' },
      { k: 'text', md: 'Stiffness: a motor mount transmits torque, so it is loaded in bending. Three cheap answers:\n\n- **Ribs** between the wall and the base — the biggest gain for the least material\n- **A thicker wall near the root**, thinner at the edges\n- **A larger contact area** with the base plate' },
      { k: 'callout', tone: 'tip', md: 'Design in **assembly access**: the motor screws usually go in from the mount side, and the key has to reach. Model the screw and the tool cylinder too, and rotate the assembly to check.' },
      { k: 'text', md: 'Finally leave room for the **cables**: the motor connector is usually at the back and the lead needs a route. A cable cutout costs two minutes during design and half an hour with a file afterwards.' },
    ],
    quiz: [
      { k: 'single', q: 'Where does designing a motor mount start?', opts: ['With the sketch', 'With the datasheet: boss, bolt circle, shaft, length', 'With the render'], answer: 1, why: 'Those numbers go into the parameter list, and the sketch refers to them.' },
      { k: 'single', q: 'What holds the motor exactly in place?', opts: ['The screws', 'The pilot boss', 'The cable'], answer: 1, why: 'The screws only clamp. With a loose boss the motor shifts within the hole clearance.' },
      { k: 'single', q: 'What clearance should the pilot boss have?', opts: ['0.5-1 mm', '0.1-0.2 mm', 'None'], answer: 1, why: 'A larger clearance lets the motor move and the gear mesh go out.' },
      { k: 'single', q: 'What is the cheapest stiffening for a mount loaded in bending?', opts: ['A fully solid part', 'Ribs between the wall and the base', 'Bigger screws'], answer: 1, why: 'The biggest stiffness gain for the least material.' },
      { k: 'single', q: 'What else needs space?', opts: ['The cable exit', 'The paint', 'The label'], answer: 0, why: 'A cable cutout is two minutes in design and half an hour with a file later.' },
    ],
    note: {
      summary: ['Design starts with the datasheet, not the sketch.', 'Four dimensions: pilot boss, bolt circle, shaft, length.', 'The boss locates, the screws only clamp.', 'Keep the boss clearance at 0.1-0.2 mm.', 'Stiffen with ribs, a thicker root and more contact area.', 'Design in tool access and a cable route.'],
      terms: [{ term: 'pilot boss', def: 'The circular fit that locates the motor.' }, { term: 'bolt circle', def: 'The diameter through the centres of the mounting holes.' }, { term: 'rib', def: 'A stiffening web between two surfaces.' }],
    },
  },
  {
    day: 21,
    title: 'Cable routing',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Almost everyone works out cable routing at the end, as an afterthought — and that is one of the commonest reasons a handsome machine turns out unreliable.' },
      { k: 'callout', tone: 'key', md: 'A cable is **not infinitely bendable**. Every cable has a **minimum bend radius**, typically 4 to 8 times its diameter when static and 10 to 15 times when it flexes in motion. Bent tighter, the strands eventually break.' },
      { k: 'text', md: 'A moving cable is the hardest case. Three answers:\n\n- **Drag chain** — for linear motion; it guides and limits the bend\n- **Service loop** — a large, lazy loop that opens and closes\n- **Slip ring** — for a continuously rotating shaft where a cable cannot pass' },
      { k: 'callout', tone: 'warn', md: '**Strain relief** is not optional. Anchor the cable to the housing before the connector, so pulling force lands on the anchor rather than the soldered contact. Without it the connector eventually tears off — and the fault becomes intermittent, which is the hardest kind to track down.' },
      { k: 'text', md: 'Separation: **motor cables are noisy** and signal cables are sensitive. Route them along **separate paths**, and cross at right angles where they must cross. Motor and signal cables running parallel for a long stretch are the classic cause of bad sensor readings.' },
      { k: 'callout', tone: 'tip', md: 'Design **cable channels or clips** into the model. A printed clip costs a few grams and keeps the cable where you planned it. Tape peels off in two weeks and the cable ends up in the drivetrain.' },
      { k: 'text', md: 'One last consideration is **assembly order**: the cable needs a route for installation too. If the lead must be threaded before the motor goes in, document it — otherwise the next assembly means taking everything apart.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the minimum bend radius of a moving cable?', opts: ['1-2 times the diameter', '10-15 times the diameter', 'There is no limit'], answer: 1, why: 'Static, 4 to 8 times suffices, but flexing needs considerably more.' },
      { k: 'single', q: 'What is a drag chain for?', opts: ['Conducting current', 'Guiding and limiting cable bending in linear motion', 'Insulation'], answer: 1, why: 'A rotating shaft needs a slip ring; small motion needs a service loop.' },
      { k: 'single', q: 'What is strain relief for?', opts: ['Insulation', 'So pulling force lands on the anchor, not the soldered contact', 'Cooling the cable'], answer: 1, why: 'Without it the connector tears off and causes an intermittent fault — the hardest to find.' },
      { k: 'single', q: 'How should motor and signal cables be routed?', opts: ['Side by side', 'On separate paths, crossing at right angles', 'Bundled together'], answer: 1, why: 'Long parallel runs are the classic cause of bad sensor readings.' },
      { k: 'single', q: 'Why is a printed cable clip better than tape?', opts: ['It looks nicer', 'Because tape peels off in two weeks and the cable ends up in the drivetrain', 'It is cheaper'], answer: 1, why: 'A clip costs a few grams and keeps the cable where you planned it.' },
    ],
    note: {
      summary: ['Design cable routing rather than improvising it at the end.', 'Minimum bend radius: 4-8× diameter static, 10-15× moving.', 'Moving cables need a drag chain, service loop or slip ring.', 'Without strain relief the connector tears off.', 'Route motor and signal cables separately, crossing at right angles.', 'Design cable channels or clips into the model.'],
      terms: [{ term: 'bend radius', def: 'The tightest arc a cable tolerates without damage.' }, { term: 'strain relief', def: 'An anchor taking pulling force off the connector.' }, { term: 'drag chain', def: 'A linked guide carrying a moving cable.' }],
    },
  },
  {
    day: 22,
    title: 'Technical drawings',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'The 3D model is for designing; the **technical drawing** is for manufacturing. That document tells the maker what to produce, and it is the one with legal standing.' },
      { k: 'callout', tone: 'key', md: 'Europe uses **first-angle projection** (ISO), America **third-angle**. The two are mirror images. Always put the symbol on the drawing — a misread projection means a part made mirrored.' },
      { k: 'text', md: 'The usual set of views:\n\n- **Front view** — the direction carrying the most information, usually the in-use orientation\n- **Top** and **side views** — only as many as needed\n- **Section** — for internal structure; mark the cutting plane with arrows\n- **Detail view** — an enlargement where a dimension will not fit' },
      { k: 'callout', tone: 'warn', md: 'The rule: **as many views as strictly necessary and no more**. Every extra view is another place a contradiction can appear when the model changes. For a rotationally symmetric part one view and a section are often enough.' },
      { k: 'text', md: 'Mandatory elements of a drawing:\n\n- **Title block**: part name, drawing number, **scale**, material, author, date, revision\n- A stated **general tolerance** (ISO 2768-m, for instance)\n- **Surface finish** where it matters\n- A **bill of materials** on an assembly drawing' },
      { k: 'callout', tone: 'tip', md: 'Keep the drawing **associative** with the model: when the model changes, the dimensions update themselves. With hand-typed dimensions you eventually get two contradicting numbers, and the maker will follow the wrong one.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the role of a drawing beside the 3D model?', opts: ['It looks nicer', 'It tells the maker what to produce and is the document with legal standing', 'It is faster'], answer: 1, why: 'The model is for designing; the drawing is for manufacturing and handover.' },
      { k: 'single', q: 'What is the difference between first- and third-angle projection?', opts: ['They are mirror images', 'One is in colour', 'The scale'], answer: 0, why: 'Europe uses the first, America the third. It must be marked or the part comes back mirrored.' },
      { k: 'single', q: 'How many views should a drawing carry?', opts: ['As many as possible', 'As many as strictly necessary', 'Exactly six'], answer: 1, why: 'Every extra view is another place a contradiction can arise when the model changes.' },
      { k: 'single', q: 'What belongs in the title block?', opts: ['Just the name', 'Name, number, scale, material, author, date, revision', 'The render'], answer: 1, why: 'Without it the drawing cannot be identified and nobody knows which revision applies.' },
      { k: 'single', q: 'Why keep the drawing associative with the model?', opts: ['Smaller file', 'So dimensions update automatically and never contradict each other', 'Faster printing'], answer: 1, why: 'With hand-typed dimensions the maker will eventually follow the wrong one.' },
    ],
    note: {
      summary: ['The model is for designing, the drawing for manufacturing.', 'Europe uses first-angle, America third-angle projection — mark it.', 'Views: front, top, side, section, detail.', 'Use as many views as strictly necessary.', 'Mandatory: title block, general tolerance, surface finish, BOM on assemblies.', 'Keep the drawing associative with the model.'],
      terms: [{ term: 'first-angle projection', def: 'The European standard arrangement of views.' }, { term: 'title block', def: 'The field holding the identifying data of a drawing.' }, { term: 'associative drawing', def: 'A drawing linked to the model, updating automatically.' }],
    },
  },
  {
    day: 23,
    title: 'Dimensioning and symbols',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Dimensioning is not sprinkling numbers onto a drawing: the question is **what matters for function**, and that is what you state.' },
      { k: 'callout', tone: 'key', md: 'The most important rule: **every dimension appears exactly once**. A dimension given twice can contradict itself, and then the maker chooses — usually wrongly. Never restate what can be derived.' },
      { k: 'text', md: 'Where do you measure from? The **functional datum**. If four holes must fit a motor, dimension them to each other and to the pilot boss, not to the edge of the part. The edge tolerance does not matter; the hole-to-hole positions do.' },
      { k: 'text', md: 'Common symbols:\n\n- **⌀20** — diameter\n- **R5** — radius\n- **□15** — square section\n- **4× ⌀3.2** — four identical holes, stated once\n- **▽** — surface finish\n- **⌴** — counterbore' },
      { k: 'callout', tone: 'warn', md: '**Chain dimensioning** (each dimension measured from the previous) accumulates tolerance: five consecutive ±0.1 mm dimensions give ±0.5 mm of uncertainty at the end. When the endpoint position matters, dimension from **one common datum** (parallel dimensioning).' },
      { k: 'callout', tone: 'tip', md: '**GD&T** (geometric dimensioning and tolerancing) is the next level: it tolerances not only size but **form and position** — flatness, perpendicularity, true position. For precise fits it states what a plain ±0.1 cannot.' },
    ],
    quiz: [
      { k: 'single', q: 'How many times should a dimension appear?', opts: ['As often as possible', 'Exactly once', 'Twice, as a check'], answer: 1, why: 'A dimension given twice can contradict itself, and the maker chooses — usually wrongly.' },
      { k: 'single', q: 'Where do you dimension motor holes from?', opts: ['The edge of the part', 'From each other and the pilot boss: the functional datum', 'The origin'], answer: 1, why: 'The edge tolerance does not matter; the hole-to-hole positions do.' },
      { k: 'single', q: 'What is wrong with chain dimensioning?', opts: ['It is longer', 'It accumulates tolerance: five ±0.1 dimensions give ±0.5', 'It is non-standard'], answer: 1, why: 'When the endpoint matters, dimension from a common datum.' },
      { k: 'single', q: 'What does `4× ⌀3.2` mean?', opts: ['A 3.2 mm hole enlarged four times', 'Four identical holes of 3.2 mm diameter', 'Four layers'], answer: 1, why: 'Stated once; you do not dimension all four separately.' },
      { k: 'single', q: 'What does GD&T tolerance beyond size?', opts: ['Nothing', 'Form and position too: flatness, perpendicularity, true position', 'The colour'], answer: 1, why: 'For precise fits it states what a plain ±0.1 cannot.' },
    ],
    note: {
      summary: ['Every dimension appears exactly once.', 'Dimension from the functional datum, not the part edge.', 'Symbols: ⌀ diameter, R radius, 4× repetition, ▽ finish.', 'Chain dimensioning accumulates tolerance: use a common datum.', 'GD&T tolerances form and position as well as size.'],
      terms: [{ term: 'functional datum', def: 'The surface or feature function requires measuring from.' }, { term: 'chain dimensioning', def: 'A run of dimensions from each other, accumulating tolerance.' }, { term: 'GD&T', def: 'A system of geometric dimensioning and tolerancing.' }],
    },
  },
  {
    day: 24,
    title: 'Choosing materials',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Material choice is rarely about which is best. It is about **which is good enough**, fastest and cheapest.' },
      { k: 'text', md: 'The usual materials in robot building:\n\n- **PLA** — printable, stiff, cheap. Softens above 60 degrees; avoid near motors.\n- **PETG** — tougher, more heat resistant (80 degrees), slightly harder to print. A good default.\n- **ABS / ASA** — heat and UV resistant, but warps and smells.\n- **Nylon** — very tough and wear resistant; good for gears. Hygroscopic, so it needs drying.\n- **Aluminium** — stiff, thermally conductive, machinable. Heavier and dearer.\n- **Steel** — where strength and wear resistance decide: shafts, bearing seats.' },
      { k: 'callout', tone: 'key', md: 'The decision comes down to three questions:\n\n1. **How much force** does it see, and how far may it bend?\n2. **At what temperature** does it operate?\n3. **How is it made** — printing, milling, laser cutting, bending?\n\nThe manufacturing method often weighs more than the material properties.' },
      { k: 'callout', tone: 'warn', md: '**PLA next to a motor** is the commonest beginner mistake. A loaded motor case easily reaches 60 to 70 degrees, where PLA softens: the mount slowly creeps, the shaft goes out of alignment, and you cannot see why the machine broke by itself. Near a motor use PETG, ABS or metal.' },
      { k: 'text', md: '**Wear** is a separate consideration. Where two surfaces move against each other, make them **different** materials — two identical metals can gall. A plastic-metal pair usually works well, and the softer part is the replaceable one.' },
      { k: 'callout', tone: 'tip', md: 'For a prototype always pick the **fastest to produce**, even if it is not optimal. A printed PETG part is ready tonight; milled aluminium next week. Find the design mistake first, then change material.' },
    ],
    quiz: [
      { k: 'single', q: 'What is a good default for a printed robot part?', opts: ['PLA', 'PETG', 'Nylon'], answer: 1, why: 'Tougher and more heat resistant than PLA, and still easy to print.' },
      { k: 'single', q: 'Why is PLA wrong next to a motor?', opts: ['Too stiff', 'It softens above 60 degrees, and a motor case easily runs hotter', 'It cannot be printed'], answer: 1, why: 'The mount slowly creeps, the shaft misaligns, and the fault appears by itself.' },
      { k: 'single', q: 'Which material suits gears?', opts: ['PLA', 'Nylon', 'ASA'], answer: 1, why: 'Very tough and wear resistant. It is hygroscopic, so dry it before printing.' },
      { k: 'single', q: 'What material pair suits surfaces moving against each other?', opts: ['Two identical metals', 'Two different materials, such as plastic and metal', 'It does not matter'], answer: 1, why: 'Two identical metals can gall. Make the softer part the replaceable one.' },
      { k: 'single', q: 'What is the right criterion for a prototype?', opts: ['The strongest material', 'The fastest to produce', 'The cheapest'], answer: 1, why: 'Find the design mistake first; you can change material afterwards.' },
    ],
    note: {
      summary: ['Look for good enough, not best.', 'PLA is cheap but softens above 60 degrees; PETG is the good default.', 'Nylon for gears, aluminium for stiffness, steel for shafts.', 'Three questions: how much force, what temperature, what process.', 'PLA does not belong next to a motor — the commonest beginner mistake.', 'Use different materials for surfaces moving against each other.', 'For a prototype pick the fastest to produce.'],
      terms: [{ term: 'PETG', def: 'A tough, easily printed plastic stable to 80 degrees.' }, { term: 'glass transition temperature', def: 'The temperature at which a plastic starts to soften.' }, { term: 'galling', def: 'Two identical metal surfaces sticking under friction.' }],
    },
  },
  {
    day: 25,
    title: 'Print orientation',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'The same model printed in a different orientation is **a different part**: different strength, different surface, different print time and different support needs.' },
      { k: 'callout', tone: 'key', md: 'Most important: a printed part is **weakest between layers**. Layer adhesion is typically **half** the in-layer strength. Orient the part so the load acts **in the plane** of the layers rather than pulling them apart.' },
      { k: 'text', md: 'An example: an L-shaped bracket loaded downward.\n\n- **Laid flat** — the layers are horizontal and the load pulls them apart. It snaps.\n- **Stood on edge** — the layers are vertical and the load acts in their plane. Several times the capacity.' },
      { k: 'text', md: 'What else orientation affects:\n\n- **Holes** — a vertical-axis hole stays round; a sideways one comes out elliptical and undersized\n- **Surface quality** — the top face is smooth, sloped faces show stepping\n- **Print time** — a lower part has fewer layers, so it is faster\n- **Support need** — every overhang steeper than 45 degrees wants support' },
      { k: 'callout', tone: 'warn', md: '**Bed adhesion** matters too. A tall part with a small footprint can come loose mid-print. Then either lay it down, add a brim, or design a breakaway foot onto it.' },
      { k: 'callout', tone: 'tip', md: 'If a part is wrong in every orientation, **cut it in two** and glue or bolt the halves. Two simple pieces often beat one complicated one covered in support — and you choose where the joint goes.' },
    ],
    quiz: [
      { k: 'single', q: 'Where is a printed part weakest?', opts: ['In the middle', 'Between the layers', 'On the surface'], answer: 1, why: 'Layer adhesion is typically half the in-layer strength.' },
      { k: 'single', q: 'How should you orient an L bracket loaded downward?', opts: ['Laid flat', 'Stood on edge, so the load acts in the plane of the layers', 'Upside down'], answer: 1, why: 'Flat, the load pulls the layers apart and the part snaps.' },
      { k: 'single', q: 'What happens to a sideways hole?', opts: ['It stays round', 'It comes out elliptical and undersized', 'It disappears'], answer: 1, why: 'Only a vertical-axis hole stays round. Sideways, layering distorts it.' },
      { k: 'single', q: 'When is support needed?', opts: ['Always', 'For overhangs steeper than 45 degrees', 'Never'], answer: 1, why: 'That is the usual limit; below it each layer still rests on the one before.' },
      { k: 'single', q: 'What should you do when a part is wrong in every orientation?', opts: ['Cut it in two and join the halves', 'Print it anyway', 'Scale it up'], answer: 0, why: 'Two simple pieces often beat one complicated one covered in support.' },
    ],
    note: {
      summary: ['Orientation changes strength, surface, time and support needs.', 'A part is weakest between layers: load should act in their plane.', 'A bracket on edge carries several times what a flat one does.', 'Vertical holes stay round, sideways holes come out elliptical.', 'Overhangs steeper than 45 degrees need support.', 'A tall part with a small footprint needs a brim or a different lay.', 'When every orientation is wrong, split the part.'],
      terms: [{ term: 'layer adhesion', def: 'The bond strength between adjacent printed layers.' }, { term: 'overhang', def: 'An unsupported sloped or horizontal surface.' }, { term: 'brim', def: 'A flat ring printed around a part for adhesion.' }],
    },
  },
  {
    day: 26,
    title: 'Avoiding supports',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Support is extra material, extra time, and it leaves an ugly surface when removed. Much of good design for printing is about **not needing it**.' },
      { k: 'callout', tone: 'key', md: 'The **45 degree rule**: any overhang steeper than 45 degrees wants support. On a shallower slope each layer still rests substantially on the one before. That is the number to hold in your head while designing.' },
      { k: 'text', md: 'Three shapes that print without support:\n\n- **A 45 degree chamfer** — instead of a horizontal overhang\n- **A teardrop hole** — a point instead of the top of the circle; the answer for a horizontal-axis hole\n- **A bridge** — the printer can span between two supported points, up to roughly 20-30 mm' },
      { k: 'callout', tone: 'warn', md: 'The top of a **horizontal-axis round hole** is always awkward: the upper arc is an overhang. Either design it as a teardrop (with a 45 degree point on top) or accept a little droop there and drill it out afterwards.' },
      { k: 'text', md: 'When support is unavoidable, it helps to know:\n\n- Support **always spoils the surface it touches**; put it where it is hidden or does not matter\n- **Tree supports** use less material and break away more easily than the traditional kind\n- **Dissolvable support** (PVA) on a dual-head printer gives a perfect surface, but is costly and slow' },
      { k: 'callout', tone: 'tip', md: 'The best test while designing: mentally rotate the model into its print orientation and look at it from below. Whatever you see hanging in the air will want support — and it can usually be solved with a chamfer or a teardrop.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the 45 degree rule?', opts: ['Layer thickness', 'Overhangs steeper than 45 degrees want support', 'The print angle'], answer: 1, why: 'On a shallower slope each layer still rests substantially on the one before.' },
      { k: 'single', q: 'What replaces a horizontal overhang?', opts: ['A 45 degree chamfer', 'A thicker wall', 'Slower printing'], answer: 0, why: 'A chamfer prints without support and is stronger too.' },
      { k: 'single', q: 'How should you design a horizontal-axis hole?', opts: ['As a plain circle', 'As a teardrop with a 45 degree point on top', 'Square'], answer: 1, why: 'The upper arc of a circle is an overhang that droops. The teardrop avoids it.' },
      { k: 'single', q: 'How far can a printer bridge between two points?', opts: ['2-3 mm', 'Roughly 20-30 mm', 'Unlimited'], answer: 1, why: 'Bridging works well in that range with adequate cooling.' },
      { k: 'single', q: 'Where should support go when it is unavoidable?', opts: ['On the visible face', 'Where it is hidden or does not matter', 'Anywhere'], answer: 1, why: 'Support always spoils the surface it touches.' },
    ],
    note: {
      summary: ['Support costs material, time and surface quality.', '45 degree rule: steeper overhangs want support.', 'Use a 45 degree chamfer instead of a horizontal overhang.', 'Make horizontal-axis holes teardrop shaped.', 'Bridging works up to 20-30 mm.', 'When support is needed, hide it; tree supports are the gentlest.', 'Test by viewing the model from below in its print orientation.'],
      terms: [{ term: '45 degree rule', def: 'The steepest overhang printable without support.' }, { term: 'teardrop hole', def: 'A hole pointed at the top so it prints without support.' }, { term: 'bridging', def: 'Spanning between two supported points without support.' }],
    },
  },
];
