import type { Day } from '../../types';

/** CAD track, days 13-19. */
export const cadEnD: Day[] = [
  {
    day: 13,
    title: 'Parametric design',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Parametric design means the model rests on **numbers and relationships**, not on fixed geometry. Change one number and the whole model rebuilds.' },
      { k: 'callout', tone: 'key', md: 'The practical tool is the **parameter list** (Fusion: Modify → Change Parameters; FreeCAD: Spreadsheet). Named values that sketch dimensions refer to.' },
      { k: 'code', lang: 'js', src: '// A typical parameter set for a motor mount\nwall_thickness = 3        // mm\nmotor_diameter = 37\nbolt_circle    = 31\nscrew_diameter = 3.2      // M3 clearance hole\nclearance      = 0.2      // print tolerance\n\n// Derived values:\nsocket_diameter = motor_diameter + 2*clearance\nouter_diameter  = socket_diameter + 2*wall_thickness', explain: 'The derived values are the point. If the motor size changes you edit one number, and the outer diameter, the wall and the holes all follow.' },
      { k: 'text', md: 'What belongs in a parameter?\n\n- Anything that **appears more than once** (wall thickness, clearance)\n- Anything **given from outside** (motor diameter, screw size)\n- Anything you will **probably adjust** (print tolerance)\n\nSomething used once that never changes can stay a number.' },
      { k: 'callout', tone: 'tip', md: 'Give parameters **meaningful names and comments**. In six months `d12 = 3.2` tells you nothing, while `screw_diameter = 3.2  // M3 clearance` is instantly clear.' },
      { k: 'callout', tone: 'warn', md: 'Do not overdo it. If every single dimension is a parameter, the list becomes unreadable and you cannot find the one you wanted. A good ratio: **10–20 parameters** for a medium part.' },
    ],
    quiz: [
      { k: 'single', q: 'What is parametric design about?', opts: ['Drawing faster', 'The model rests on numbers and relationships and rebuilds when one changes', 'Automatic dimensioning'], answer: 1, why: 'The geometry follows from the parameters, not the other way round. That is what makes it changeable.' },
      { k: 'single', q: 'What is a derived parameter?', opts: ['A hand-typed number', 'A value computed by formula from other parameters', 'The file size'], answer: 1, why: 'For example `outer = socket + 2*wall`. One change then propagates through the model.' },
      { k: 'single', q: 'What belongs in a parameter?', opts: ['Every dimension', 'Anything repeated, given from outside, or likely to change', 'Nothing'], answer: 1, why: 'A dimension used once that never changes can stay a number. Too many parameters are unmanageable.' },
      { k: 'single', q: 'What is a good parameter count for a medium part?', opts: ['2-3', '10-20', 'Over 100'], answer: 1, why: 'That stays readable and still covers the dimensions that matter.' },
      { k: 'single', q: 'Why do parameter names matter?', opts: ['They look nicer', 'Because in six months `d12 = 3.2` tells you nothing', 'They compute faster'], answer: 1, why: 'The name and comment are the only documentation that stays inside the model.' },
    ],
    note: {
      summary: ['A parametric model rests on numbers and relationships.', 'The parameter list holds named values that sketches refer to.', 'A derived parameter is computed from others by formula.', 'Parameterise what repeats, comes from outside, or will change.', 'Meaningful names and comments are mandatory.', 'A good ratio: 10–20 parameters per part.'],
      terms: [{ term: 'parameter', def: 'A named value the model refers to.' }, { term: 'derived value', def: 'A dimension computed by formula from other parameters.' }, { term: 'parameter list', def: 'The table holding every parameter of the model.' }],
    },
  },
  {
    day: 14,
    title: 'Design intent',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Design intent** means the model describes not just the current shape but **what follows from what**. That is what keeps it usable when something has to change.' },
      { k: 'callout', tone: 'key', md: 'The question at every constraint is the same: *if this dimension changes, what should follow?* A hole dimensioned from the **edge** means something different from one dimensioned from the **centreline** — and only one stays right when the plate gets wider.' },
      { k: 'text', md: 'Three rules that help the most:\n\n1. **Express symmetry with symmetry**, not with two equal dimensions. A mirror about a centreline holds even when the size changes.\n2. **Express equality with equality**: four identical holes need one dimension and three equal constraints, not four dimensions.\n3. **Tie dimensions to function**, not convenience: a bolt hole is located relative to the flange, not to the sketch origin.' },
      { k: 'callout', tone: 'warn', md: 'An **over-constrained** sketch throws an error: contradictory dimensions. An **under-constrained** one is more dangerous: it looks right, but at the next change something shifts and you cannot see why. A fully defined sketch is usually black or green — leave nothing else behind.' },
      { k: 'text', md: 'Order matters in the feature tree too. If you place a fillet **before** a hole, and the hole later lands on the filleted edge, the model breaks. The rule: **big shape first, details last** — fillets and chamfers at the end.' },
      { k: 'callout', tone: 'tip', md: 'Try it: double one main dimension and see what happens. If the model follows cleanly, the intent is good. If it falls apart, you now know where a constraint needs fixing — not in six months, right before a deadline.' },
    ],
    quiz: [
      { k: 'single', q: 'What does design intent mean?', opts: ['The model should look nice', 'The model describes what follows from what, not just the current shape', 'Modelling quickly'], answer: 1, why: 'That is what keeps the model usable when it has to change.' },
      { k: 'single', q: 'How should you express symmetry?', opts: ['With two equal dimensions', 'With a symmetry constraint about the centreline', 'No need to express it'], answer: 1, why: 'Two equal dimensions only match today. A symmetry constraint survives change.' },
      { k: 'single', q: 'Why is an under-constrained sketch more dangerous than an over-constrained one?', opts: ['It throws an error', 'It looks right but shifts invisibly at the next change', 'It is slower'], answer: 1, why: 'Over-constraining fails immediately. Under-constraining fails quietly, later.' },
      { k: 'single', q: 'Where do fillets belong in the tree?', opts: ['At the start', 'At the end, after the main shape', 'Anywhere'], answer: 1, why: 'If a later hole lands on a filleted edge the model breaks. Shape first, details last.' },
      { k: 'single', q: 'How do you check design intent?', opts: ['Look at the render', 'Double a main dimension and see if the model follows', 'Check the file size'], answer: 1, why: 'If it falls apart you find out now, not in six months before a deadline.' },
    ],
    note: {
      summary: ['Design intent describes what follows from what.', 'At every constraint ask: if this changes, what should follow?', 'Express symmetry with symmetry, equality with equality.', 'Tie dimensions to function, not to convenience.', 'An under-constrained sketch is more dangerous than an over-constrained one.', 'Big shape first, fillets last.', 'Check by doubling a main dimension.'],
      terms: [{ term: 'design intent', def: 'The relationships built into a model that survive change.' }, { term: 'under-constrained', def: 'A sketch that still has freedom to move.' }, { term: 'fully defined', def: 'A sketch in which every element is fixed.' }],
    },
  },
  {
    day: 15,
    title: 'Assemblies',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'An **assembly** holds several parts together as one unit. You do not build one big model: you make separate parts and describe how they connect.' },
      { k: 'callout', tone: 'key', md: 'The base rule: **one part = one file** (or one component). If a screw is used ten times there is one definition and ten instances. Fix the definition and all ten follow.' },
      { k: 'text', md: 'The assembly tree should mirror the **real build order**:\n\n```\nRobot\n├── Chassis\n│   ├── Base plate\n│   └── Side wall ×2\n├── Drivetrain\n│   ├── Motor ×4\n│   └── Motor mount ×4\n└── Superstructure\n```\n\nThis is not decoration: whoever assembles it later works from that tree.' },
      { k: 'text', md: 'A **sub-assembly** groups several parts and moves as one. A four-motor drivetrain is positioned once as a sub-assembly and can then be relocated in a single move.' },
      { k: 'callout', tone: 'warn', md: 'A **circular reference** is the curse of assemblies: part A refers to a dimension of B, and B refers to one of A. At the first change the software either loops forever or refuses to rebuild. Refer instead to a shared **skeleton** geometry that both use.' },
      { k: 'callout', tone: 'tip', md: 'In a large assembly, hide what you do not need or use a simplified representation. Spinning a five-hundred-part model at full detail is slow even on a strong machine.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the rule for repeated parts?', opts: ['Every instance is its own file', 'One definition, many instances — a fix propagates to all', 'Copy it again'], answer: 1, why: 'One screw definition and ten instances. A fix does not have to be made ten times.' },
      { k: 'single', q: 'What should the assembly tree mirror?', opts: ['Part sizes', 'The real build order', 'Alphabetical order'], answer: 1, why: 'Whoever assembles the machine later works from that tree.' },
      { k: 'single', q: 'What is a sub-assembly good for?', opts: ['A smaller file', 'Several parts move as one and can be reused', 'Faster rendering'], answer: 1, why: 'A four-motor drivetrain is positioned once and then handled as a unit.' },
      { k: 'single', q: 'What is a circular reference?', opts: ['Two parts referring to each other dimensions', 'A circular part', 'A repeating pattern'], answer: 0, why: 'At the first change the software loops forever or refuses to rebuild.' },
      { k: 'single', q: 'What is the fix for a circular reference?', opts: ['Delete one part', 'A shared skeleton geometry both parts refer to', 'Refer to nothing'], answer: 1, why: 'The skeleton gives a one-way dependency: both parts follow from it, not from each other.' },
    ],
    note: {
      summary: ['An assembly connects separate parts.', 'One part = one definition, many instances.', 'The tree should mirror the real build order.', 'A sub-assembly groups parts so they move as one.', 'Use a shared skeleton instead of circular references.', 'Use simplified representation in large assemblies.'],
      terms: [{ term: 'assembly', def: 'A connected set of parts.' }, { term: 'sub-assembly', def: 'A group of parts handled as a single unit.' }, { term: 'skeleton geometry', def: 'Shared reference geometry that parts refer to.' }],
    },
  },
  {
    day: 16,
    title: 'Joints and assembly constraints',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Inside an assembly, parts are tied together with **joints** (or mates). A joint says where something sits relative to something else, and **what can still move**.' },
      { k: 'callout', tone: 'key', md: 'A free body has six degrees of freedom: three translations and three rotations. Every constraint removes some. A joint should leave exactly as many as **reality allows**.' },
      { k: 'text', md: 'The common joint types:\n\n- **Rigid** — zero degrees of freedom. A bolted plate.\n- **Revolute** — one rotation. A bearing, a hinge.\n- **Slider** — one translation. A linear rail.\n- **Cylindrical** — rotation and translation on the same axis. A pin in a hole.\n- **Ball** — three rotations.' },
      { k: 'callout', tone: 'warn', md: '**Over-constraining** is a bug here too: if two joints restrict the same motion, one is redundant and they will fight at the first dimension change. The rule: remove every degree of freedom **exactly once**.' },
      { k: 'text', md: 'Verify joints by **moving them**, not by eye. Grab a part and drag: if it moves somewhere reality would not allow, a constraint is missing. If it will not move where it should, a constraint is too tight.' },
      { k: 'callout', tone: 'tip', md: 'An **interference check** shows where parts overlap. Run it on every assembly before release — a 0.2 mm overlap is invisible on screen, but in reality the machine will not go together.' },
    ],
    quiz: [
      { k: 'single', q: 'How many degrees of freedom does a free body have?', opts: ['3', '6', '12'], answer: 1, why: 'Three translations and three rotations. Every constraint removes some.' },
      { k: 'single', q: 'Which joint allows one rotation?', opts: ['Rigid', 'Revolute', 'Slider'], answer: 1, why: 'Bearings, hinges and wheel axles all allow exactly one rotation.' },
      { k: 'single', q: 'What does a cylindrical joint allow?', opts: ['Rotation only', 'Rotation and translation on the same axis', 'Translation only'], answer: 1, why: 'A pin in a hole: it both turns and slides along its axis.' },
      { k: 'single', q: 'What is wrong with over-constraining an assembly?', opts: ['It is slow', 'Two joints restrict the same motion and fight at the first change', 'The model disappears'], answer: 1, why: 'Remove every degree of freedom exactly once.' },
      { k: 'single', q: 'How should you verify joints?', opts: ['By eye', 'Grab and drag: does it move where reality allows?', 'By file size'], answer: 1, why: 'Moving the part immediately exposes a missing or redundant constraint.' },
    ],
    note: {
      summary: ['A joint says where a part sits and what can move.', 'A free body has six degrees of freedom.', 'Types: rigid, revolute, slider, cylindrical, ball.', 'Remove every degree of freedom exactly once.', 'Verify joints by dragging, not by eye.', 'Always run an interference check before release.'],
      terms: [{ term: 'joint', def: 'A connection between parts that removes degrees of freedom.' }, { term: 'cylindrical joint', def: 'A joint allowing rotation and translation on one axis.' }, { term: 'interference check', def: 'Checking for overlapping parts in an assembly.' }],
    },
  },
  {
    day: 17,
    title: 'Tolerances and fits',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Nothing can be made exactly. A **tolerance** states how much deviation is allowed — and that is what turns a drawing into a manufacturable part.' },
      { k: 'callout', tone: 'key', md: 'Three kinds of fit:\n\n- **Clearance** — the pin is always smaller than the hole. It moves freely.\n- **Transition** — depending on the actual sizes it may be tight or loose. Accurate location, assembled by hand.\n- **Interference** — the pin is always larger. It has to be pressed or heated in.' },
      { k: 'code', lang: 'js', src: '// Typical gaps for 3D printing (FDM, 0.4 mm nozzle)\nmoving_fit    = 0.40   // a hinge or rotating part\nassembly_fit  = 0.25   // pushes together by hand\ntransition    = 0.15   // tight, but still assembles\npress_fit     = 0.00   // pressed in with a mallet\n\n// Always draw the hole at nominal + gap:\nhole = shaft_diameter + assembly_fit', explain: 'These are for FDM printing. Milling and turning need a tenth of these; SLA printing about half.' },
      { k: 'callout', tone: 'warn', md: 'An FDM printer is **inaccurate inwards**: holes come out smaller than designed and pins larger. So splitting the gap between the two is not enough — draw the hole oversize and leave the pin nominal.' },
      { k: 'text', md: 'Tolerance notation on a drawing:\n\n- **Bilateral**: `20 ±0.1` — between 19.9 and 20.1\n- **Unilateral**: `20 +0.2 / −0` — may only deviate upward\n- **ISO fit**: `H7/g6` — a standard code the manufacturer reads limits from' },
      { k: 'callout', tone: 'tip', md: 'A tight tolerance **costs money**: every tenth of a millimetre tightened raises the price. Specify tight tolerances only where they are needed — typically bearing seats and mating faces. General tolerance covers the rest.' },
    ],
    quiz: [
      { k: 'single', q: 'What is a clearance fit?', opts: ['The pin is always larger than the hole', 'The pin is always smaller, so it moves freely', 'They are exactly equal'], answer: 1, why: 'Needed for rotating and sliding connections where motion must be unimpeded.' },
      { k: 'single', q: 'What gap does an FDM hand-assembly fit need?', opts: ['0.05 mm', '0.25 mm', '1.0 mm'], answer: 1, why: 'Moving parts need 0.4 mm, assembly 0.25 mm, press fit 0. Milled parts need a tenth of that.' },
      { k: 'single', q: 'Why draw FDM holes oversize?', opts: ['It looks better', 'Because the printer is inaccurate inwards: holes come out smaller', 'To use less material'], answer: 1, why: 'Holes shrink and pins grow, so splitting the gap evenly does not work.' },
      { k: 'single', q: 'What does `20 +0.2 / −0` mean?', opts: ['Between 19.8 and 20.2', 'Between 20 and 20.2: deviation only upward', 'Exactly 20'], answer: 1, why: 'A unilateral tolerance. Common for holes: better oversize than undersize.' },
      { k: 'single', q: 'Where should you specify tight tolerances?', opts: ['Everywhere', 'Only where needed: bearing seats, mating faces', 'Nowhere'], answer: 1, why: 'Every tightening raises the manufacturing cost. General tolerance covers the rest.' },
    ],
    note: {
      summary: ['A tolerance is the allowed manufacturing deviation.', 'Fits: clearance, transition, interference.', 'FDM gaps: moving 0.4; assembly 0.25; transition 0.15; press 0.', 'FDM holes come out smaller and pins larger than designed.', 'Notation: bilateral `±`, unilateral, or ISO fit (H7/g6).', 'Tight tolerances only where needed — they cost money.'],
      terms: [{ term: 'tolerance', def: 'The allowed deviation from the nominal size.' }, { term: 'clearance fit', def: 'The pin is always smaller than the hole, allowing motion.' }, { term: 'ISO fit', def: 'A standard code (e.g. H7/g6) for tolerance limits.' }],
    },
  },
  {
    day: 18,
    title: 'Screws and fasteners',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Most machines are held together by screws. A few rules save a pile of redesign.' },
      { k: 'callout', tone: 'key', md: 'A metric screw needs **two kinds of hole**:\n\n- **Clearance hole** — the screw passes freely. For M3: 3.2–3.4 mm.\n- **Tapped hole** — the thread cuts into it. For M3 the pilot is 2.5 mm.\n\nMixing them up is the commonest beginner mistake: tap both plates and the screw cannot pull them together.' },
      { k: 'text', md: 'Common metric sizes for robot building:\n\n| Size | Clearance | Pilot | Key |\n|---|---|---|---|\n| M2 | 2.2 | 1.6 | 1.5 mm hex |\n| M3 | 3.2 | 2.5 | 2.5 mm hex |\n| M4 | 4.3 | 3.3 | 3 mm hex |\n| M5 | 5.3 | 4.2 | 4 mm hex |' },
      { k: 'callout', tone: 'warn', md: 'Thread engagement should be at least **1.5×** the screw diameter in steel, and **2–2.5×** in aluminium or plastic. A shorter thread strips. So an M3 in plastic needs at least 6–8 mm of tapped depth.' },
      { k: 'text', md: 'Do not tap plastic directly if it has to come apart repeatedly — use a **heat-set insert**. You melt it in with a soldering iron and it survives a hundred assemblies. On 3D-printed robots this is the standard answer.' },
      { k: 'callout', tone: 'tip', md: 'Leave **tool access**. A perfectly designed bolted joint is useless if the hex key does not reach. Model the tool cylinder too and check whether it collides with anything.' },
    ],
    quiz: [
      { k: 'single', q: 'What clearance hole does an M3 screw need?', opts: ['2.5 mm', '3.2 mm', '4 mm'], answer: 1, why: 'The pilot hole is 2.5 mm, but the clearance hole is 3.2 mm so the screw passes freely.' },
      { k: 'single', q: 'What happens if you tap both plates?', opts: ['It is stronger', 'The screw cannot pull them together', 'Nothing'], answer: 1, why: 'For clamping, one side must let the screw pass freely. This is the commonest beginner mistake.' },
      { k: 'single', q: 'How deep should an M3 thread be in plastic?', opts: ['3 mm', 'At least 6-8 mm', '1 mm'], answer: 1, why: 'Plastic needs 2–2.5× the diameter. A shorter thread strips.' },
      { k: 'single', q: 'What is a heat-set insert for?', opts: ['Looks', 'It survives many assembly cycles in plastic', 'It is cheaper'], answer: 1, why: 'A printed thread wears out after a few cycles. A melted-in metal insert survives a hundred.' },
      { k: 'single', q: 'What must you check when placing a screw in the model?', opts: ['Its colour', 'Tool access: can the hex key reach it?', 'Its mass'], answer: 1, why: 'Model the tool cylinder too and check whether it collides with anything.' },
    ],
    note: {
      summary: ['Clearance hole: the screw passes freely (M3 → 3.2 mm).', 'Tapped hole: a pilot the thread cuts into (M3 → 2.5 mm).', 'Tapping both sides stops the screw clamping.', 'Thread engagement: 1.5× diameter in steel, 2–2.5× in plastic.', 'Use heat-set inserts in plastic for repeated assembly.', 'Always leave tool access; model the tool.'],
      terms: [{ term: 'clearance hole', def: 'A hole the screw passes through freely.' }, { term: 'pilot hole', def: 'The smaller hole a thread is cut into.' }, { term: 'heat-set insert', def: 'A threaded metal sleeve melted into plastic.' }],
    },
  },
  {
    day: 19,
    title: 'Mounting bearings',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **bearing** carries a rotating shaft with minimal friction. Mounted wrong it binds, rattles or fails — so the few rules are worth keeping.' },
      { k: 'text', md: 'The commonest type is the **deep-groove ball bearing**. Its code is four digits, for instance **608**: the leading 6 is the series and 08 is the bore diameter times five, so 8 mm. The 608 is the skateboard wheel bearing — cheap and available everywhere.' },
      { k: 'callout', tone: 'key', md: 'The shaft holds the bearing by its **inner ring**, the housing by its **outer ring**. Load must always pass through the rings — **never through the balls**, which destroys it immediately.' },
      { k: 'text', md: 'The standard mounting:\n\n1. The housing bore is an **interference** fit to the outer ring\n2. The shaft is an **interference** fit to the inner ring\n3. A **shoulder** locates the bearing axially\n4. The shoulder height must be **less** than the ring thickness, so it does not touch the seal' },
      { k: 'callout', tone: 'warn', md: 'A shaft needs **two bearings**, but only **one** should locate it axially. Clamp both and thermal expansion or manufacturing error puts the shaft in tension, and the bearings fail fast. That is the "fixed and floating" principle.' },
      { k: 'text', md: 'An interference fit is hard in a printed housing: too tight and it will not go in, too loose and it falls out. Two good answers: **printed ribs** inside the bore that deform slightly, or a **clamping** housing pulled tight with a screw.' },
      { k: 'callout', tone: 'tip', md: 'Model the bearing as a simplified shape (two rings) and place it in the assembly. You then see immediately whether it fits, whether there is an assembly path, and whether the shoulder fouls the seal.' },
    ],
    quiz: [
      { k: 'single', q: 'What does the bearing code 608 mean?', opts: ['608 mm diameter', '8 mm bore, series 6', '608 grams'], answer: 1, why: 'The last two digits times five give the bore. The 608 is the skateboard wheel bearing.' },
      { k: 'single', q: 'How should load pass through a bearing?', opts: ['Through the balls', 'Through the rings', 'Through the seal'], answer: 1, why: 'The shaft holds the inner ring and the housing the outer. Load directly on the balls destroys it.' },
      { k: 'single', q: 'Why should only one bearing locate the shaft axially?', opts: ['It is cheaper', 'Because thermal expansion or manufacturing error would tension the shaft', 'It is easier to assemble'], answer: 1, why: 'That is the fixed and floating principle: one locates, the other can slide.' },
      { k: 'single', q: 'How high should the locating shoulder be?', opts: ['Higher than the ring', 'Less than the ring thickness, so it does not touch the seal', 'It does not matter'], answer: 1, why: 'A shoulder bearing on the seal makes the bearing bind and ruins the seal.' },
      { k: 'single', q: 'How do you get an interference fit in a printed housing?', opts: ['Glue', 'Printed ribs in the bore, or a clamping housing', 'You cannot'], answer: 1, why: 'The ribs deform slightly and absorb the printing inaccuracy.' },
    ],
    note: {
      summary: ['Deep-groove ball bearing code: 608 → 8 mm bore.', 'Load must pass through the rings, never the balls.', 'Both the housing bore and the shaft are interference fits to the rings.', 'A shoulder locates it axially, lower than the ring thickness.', 'Of two bearings, only one should locate axially.', 'Printed housings: ribs or a clamping design.'],
      terms: [{ term: 'deep-groove ball bearing', def: 'The most common bearing type for radial load.' }, { term: 'fixed and floating', def: 'One bearing locates axially, the other can slide.' }, { term: 'shoulder', def: 'A step that locates a bearing axially.' }],
    },
  },
];
