import type { Day } from '../../types';

/** CODE track, days 16–23. */
export const codeEnC: Day[] = [
  {
    day: 16,
    title: 'Classes and objects',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Until now data and the operations on it lived apart: a dictionary here, functions poking at it there. A **class** binds the two together.' },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self, name):\n        self.name = name\n        self.x = 0\n        self.battery = 100\n\n    def drive(self, cm):\n        self.x = self.x + cm\n        self.battery = self.battery - cm * 0.1\n\nr = Rover("Mk-I")\nr.drive(30)\nprint(r.name, r.x, r.battery)', explain: '`__init__` runs at birth. `self` is the object itself — the way it reaches its own data.' },
      { k: 'callout', tone: 'warn', md: '`self` is the first parameter of every method, but you do **not** pass it when calling: `r.drive(30)`, not `r.drive(r, 30)`. Python puts it there for you.' },
      { k: 'text', md: 'The **class** is the blueprint, the **object** is an instance made from it. From one `Rover` class you can build any number of rovers, each with its own `x` and battery.' },
      { k: 'callout', tone: 'key', md: 'A class earns its place when a set of data and the operations on it always travel together. If you are only storing data, a dictionary is enough.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `Counter` class with a `value` starting at 0 and an `increment()` method. Call it three times and print the value.',
      starter: 'class Counter:\n    pass\n\n',
      checks: [{ k: 'output', contains: '3', label: 'After three increments the value is 3' }],
      hints: ['`def __init__(self): self.value = 0`', '`def increment(self): self.value += 1`', '`c = Counter()`, three `c.increment()`, then `print(c.value)`.'],
    },
    quiz: [
      { k: 'single', q: 'When does `__init__` run?', opts: ['On every method call', 'When the object is created', 'At the end of the program'], answer: 1, why: '`__init__` is the constructor: it runs exactly once, when `Rover("Mk-I")` creates the instance.' },
      { k: 'single', q: 'What does `self` mean?', opts: ['The class', 'The object the method was called on', 'A global variable'], answer: 1, why: '`self` is the specific instance the method is running on. Through it the method reaches that instance\'s data.' },
      { k: 'output', q: 'What does this print?', code: 'class A:\n    def __init__(self):\n        self.n = 1\n\na = A()\nb = A()\nb.n = 9\nprint(a.n, b.n)', lang: 'py', opts: ['1 9', '9 9', '1 1'], answer: 0, why: 'Two separate instances, two separate `n`s. Changing one does not touch the other — that is the point of objects.' },
      { k: 'single', q: 'When is a class NOT worth it?', opts: ['When you only store data with no operations', 'When you have a lot of data', 'Never, always use a class'], answer: 0, why: 'With no behaviour attached, a dictionary is simpler and clearer. A class is about data and behaviour belonging together.' },
    ],
    note: {
      summary: ['A class binds data and the operations on it together.', '`__init__` runs once, at creation.', '`self` is the instance; you do not pass it, Python does.', 'The class is the blueprint, the object an instance — each with its own data.', 'With no behaviour, a dictionary is enough.'],
      terms: [{ term: 'class', def: "A blueprint describing an object's data and operations." }, { term: 'object', def: 'A concrete instance made from a class.' }, { term: 'self', def: 'Inside a method, the instance the call was made on.' }],
    },
  },
  {
    day: 17,
    title: 'State and methods',
    minutes: 22,
    lesson: [
      { k: 'text', md: "An object's **state** is what it carries inside. Methods read and change that state — which is exactly why it is worth guarding." },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self):\n        self.battery = 100\n\n    def drive(self, cm):\n        if self.battery <= 0:\n            return False          # going nowhere\n        self.battery -= cm * 0.1\n        return True\n\n    def charge(self):\n        self.battery = 100', explain: '`drive` protects the object from an invalid state: a flat battery means it does not move, and it says so.' },
      { k: 'callout', tone: 'key', md: 'The real value of a class is not the syntax but that you guard the data in one place. If only the class methods may touch the battery, nothing can accidentally set it to -40 %.' },
      { k: 'code', lang: 'py', src: 'class Rover:\n    def __init__(self, name):\n        self.name = name\n\n    def __repr__(self):\n        return f"Rover({self.name})"\n\nprint(Rover("Mk-II"))     # Rover(Mk-II)', explain: '`__repr__` decides how the object looks when printed. When debugging, that helps a lot.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `Battery` class with a `level` starting at 100 and a `drain(amount)` method. The level must never go below zero. Drain 120 and print the level.',
      starter: 'class Battery:\n    pass\n\n',
      checks: [{ k: 'output', contains: '0', label: 'The level does not go below zero' }],
      hints: ['`self.level = 100` in `__init__`.', '`self.level = max(0, self.level - amount)`', 'Finally: `print(b.level)`.'],
    },
    quiz: [
      { k: 'single', q: "What is an object's state?", opts: ['Its list of methods', 'The data it carries inside', 'The class name'], answer: 1, why: "State is the instance's data — what makes one object different from another." },
      { k: 'single', q: 'Why is it good that only methods change the data?', opts: ['It is faster', 'You can guard validity in one place', 'Less typing'], answer: 1, why: 'If anything can write it, anything can break it. If only methods can, you only have to get those right.' },
      { k: 'single', q: 'What is `__repr__` for?', opts: ['It speeds the object up', 'It decides how the object appears when printed', 'It deletes the object'], answer: 1, why: 'Without it `print(obj)` shows something like `<__main__.Rover object at 0x7f...>`, which tells you nothing. `__repr__` makes it readable.' },
      { k: 'output', q: 'What does this print?', code: 'class C:\n    def __init__(self):\n        self.n = 5\n    def down(self):\n        self.n = max(0, self.n - 10)\n\nc = C()\nc.down()\nprint(c.n)', lang: 'py', opts: ['-5', '0', '5'], answer: 1, why: '`max(0, ...)` holds the floor, so instead of 5-10 = -5 you get 0.' },
    ],
    note: {
      summary: ["State is the sum of an object's own data.", 'Methods read and change that state.', 'When only methods can change it, validity is guarded in one place.', '`__repr__` decides how the object prints — worth a lot when debugging.', 'Enforcing bounds is the method\'s job, not the caller\'s.'],
      terms: [{ term: 'state', def: "The sum of an object's own data." }, { term: 'method', def: "A function inside a class that works on the object's state." }, { term: 'invariant', def: "A rule that must hold throughout an object's life." }],
    },
  },
  {
    day: 18,
    title: 'Inheritance, when it earns its place',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Inheritance** means one class takes everything from another and adds to it or overrides part of it.' },
      { k: 'code', lang: 'py', src: 'class Robot:\n    def __init__(self, name):\n        self.name = name\n\n    def move(self):\n        print(f"{self.name} moves")\n\nclass Rover(Robot):\n    def move(self):\n        print(f"{self.name} rolls")\n\nclass Drone(Robot):\n    def move(self):\n        print(f"{self.name} flies")\n\nfor r in [Rover("R1"), Drone("D1")]:\n    r.move()', explain: 'Both are a `Robot`, but they move differently. The loop does not know which is which — yet each does its own thing. That is polymorphism.' },
      { k: 'callout', tone: 'warn', md: 'Inheritance is easy to overuse. It is worth it only when the derived class really is a kind of the parent. "A dog is an animal" works. "An engine is a car" does not — an engine is *part* of a car, not a kind of one.' },
      { k: 'callout', tone: 'tip', md: 'When in doubt, do not inherit: make one object a field of the other. That is composition, and most of the time it is simpler.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `Shape` class with an `area()` method returning 0. Derive a `Square` that returns the side squared. Print the area of a square with side 4.',
      starter: 'class Shape:\n    def area(self):\n        return 0\n\n',
      checks: [{ k: 'output', contains: '16', label: 'A square of side 4 has area 16' }],
      hints: ['`class Square(Shape):`', '`def __init__(self, side): self.side = side`', '`def area(self): return self.side ** 2`'],
    },
    quiz: [
      { k: 'single', q: 'What does `class Rover(Robot):` mean?', opts: ['Rover contains a Robot', 'Rover inherits from Robot', 'Rover deletes Robot'], answer: 1, why: 'The parent class goes in the parentheses. Rover gets all of Robot\'s methods and may override them.' },
      { k: 'output', q: 'What does this print?', code: 'class A:\n    def f(self):\n        return "A"\nclass B(A):\n    def f(self):\n        return "B"\n\nprint(B().f())', lang: 'py', opts: ['A', 'B', 'AB'], answer: 1, why: 'B overrode `f`, and its own version wins. That is overriding.' },
      { k: 'single', q: 'When is inheritance the wrong tool?', opts: ['When the derived class is not really a kind of the parent', 'When there are many methods', 'When the parent is short'], answer: 0, why: 'Inheritance means "is a kind of". When the relationship is really "has one of those", you want composition.' },
      { k: 'single', q: 'What is polymorphism?', opts: ['A class having several names', 'Different types answering the same call in their own way', 'A method running more than once'], answer: 1, why: 'The caller writes the same thing (`r.move()`) and each type answers its own way. That is what makes code extensible.' },
    ],
    note: {
      summary: ['Inheritance takes all of the parent\'s methods, and you may override them.', '`class Child(Parent):` — the parent goes in the parentheses.', 'Polymorphism: each type answers the same call in its own way.', 'Only inherit when the child really is a kind of the parent.', 'When in doubt, use composition: make one object a field of the other.'],
      terms: [{ term: 'inheritance', def: 'Deriving a class from another with all its capabilities.' }, { term: 'overriding', def: "Replacing a parent's method in the child class." }, { term: 'composition', def: 'Holding one object as a field of another instead of inheriting.' }],
    },
  },
  {
    day: 19,
    title: 'Errors and exceptions',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'An error is not a failure, it is information. An **exception** is how Python says: I cannot do this the way you asked.' },
      { k: 'code', lang: 'py', src: 'try:\n    number = int("apple")\nexcept ValueError:\n    print("That is not a number.")\n    number = 0\n\nprint(number)', explain: 'You attempt in the `try` block and handle it in the `except` branch. The program keeps going.' },
      { k: 'callout', tone: 'warn', md: 'Never write a bare `except:`. It catches everything, including your own typos, and the program then quietly does the wrong thing. Always name what you expect: `except ValueError:`.' },
      { k: 'code', lang: 'py', src: 'def divide(a, b):\n    if b == 0:\n        raise ValueError("We do not divide by zero")\n    return a / b\n\ntry:\n    divide(1, 0)\nexcept ValueError as e:\n    print("Error:", e)', explain: '`raise` is you raising an error yourself. It beats quietly returning a wrong value: at least the caller knows something is off.' },
      { k: 'text', md: 'The common kinds:\n\n- `ValueError` — right type, wrong value (`int("apple")`)\n- `TypeError` — wrong type (`1 + "a"`)\n- `IndexError` — an index that does not exist\n- `KeyError` — a key that does not exist\n- `ZeroDivisionError` — division by zero' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `safe_int(text)` function that converts to a number but returns 0 on bad input instead of raising. Try it with "42" and "apple".',
      starter: 'def safe_int(text):\n    pass\n\nprint(safe_int("42"))\nprint(safe_int("apple"))\n',
      checks: [{ k: 'output', contains: '42', label: '"42" converts' }, { k: 'output', contains: '0', label: '"apple" gives 0' }],
      hints: ['`try:` then `return int(text)`.', '`except ValueError:` then `return 0`.'],
    },
    quiz: [
      { k: 'single', q: 'What does `try` / `except` do?', opts: ['Prevents the error', 'Catches the error and gives you a chance to handle it', 'Prints the error and stops'], answer: 1, why: 'The error still happens, but it does not stop the program: the `except` branch runs instead.' },
      { k: 'single', q: 'Why is a bare `except:` bad?', opts: ['It is slow', 'It catches everything, including your own typos', 'It does not work in Python'], answer: 1, why: 'It hides errors you never expected — and from then on the program is quietly wrong. That is the hardest kind of bug to find.' },
      { k: 'single', q: 'Which error does `int("apple")` raise?', opts: ['TypeError', 'ValueError', 'KeyError'], answer: 1, why: 'The type is fine (it is text), only the value cannot become a number — that is `ValueError`.' },
      { k: 'single', q: 'When should you `raise` yourself?', opts: ['Never', 'When your function cannot sensibly do its job', 'At the start of every function'], answer: 1, why: 'When there is no sensible result for the input, raising loudly beats returning a wrong value quietly.' },
    ],
    note: {
      summary: ["An exception is Python's signal that an operation cannot be done.", '`try` / `except` catches it and makes it handleable.', 'Always name what you expect — a bare `except:` hides your own bugs.', '`raise` is your own error signal: better than a quietly wrong value.', 'Common kinds: ValueError, TypeError, IndexError, KeyError, ZeroDivisionError.'],
      terms: [{ term: 'exception', def: 'A runtime error signal that interrupts normal execution.' }, { term: 'try/except', def: 'The structure for catching and handling an error.' }, { term: 'raise', def: 'Raising an error yourself.' }],
    },
  },
  {
    day: 20,
    title: 'Debugging methodically',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Debugging is not talent, it is method. Four steps, in this order.' },
      { k: 'text', md: '**1. Reproduce it.** If you cannot summon the bug on demand, you cannot fix it either — you can only hope. Write down the smallest input that breaks it.\n\n**2. Narrow it.** Halve: is the bug in the first or the second half of the code? One `print` in the middle tells you.\n\n**3. Form a hypothesis.** Say it out loud: "I think the list is empty by the time it gets here." That is a checkable claim.\n\n**4. Check it.** Print it and look. If that was not it, form a new hypothesis — do not patch blindly.' },
      { k: 'code', lang: 'py', src: 'def average(numbers):\n    print("GOT:", repr(numbers))         # 1. what came in?\n    total = sum(numbers)\n    print("TOTAL:", total)               # 2. is the partial right?\n    return total / len(numbers)', explain: 'Printing is the simplest and most reliable tool there is. It needs nothing, and it shows exactly what happens.' },
      { k: 'callout', tone: 'key', md: 'The most common debugging mistake: believing you know what is happening and not looking. The code you read shows what you **meant**. The printed value shows what **is**.' },
      { k: 'callout', tone: 'warn', md: 'Once you have fixed it, understand why it works. "It is fine now, no idea why" means the bug will come back somewhere else.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'This function is always one short. Find the bug and fix it.',
      starter: 'def total(numbers):\n    s = 0\n    for i in range(len(numbers) - 1):\n        s = s + numbers[i]\n    return s\n\nprint(total([1, 2, 3, 4]))\n',
      checks: [{ k: 'output', contains: '10', label: 'The sum of [1,2,3,4] is 10' }],
      hints: ['Print how many items the loop walks.', '`range(len(numbers) - 1)` gives one fewer than it should.', 'The fix: `range(len(numbers))`, or simpler still `for x in numbers:`.'],
    },
    quiz: [
      { k: 'order', q: 'What is the order of methodical debugging?', items: ['Form a hypothesis', 'Reproduce', 'Check'], correct: [1, 0, 2], why: 'You have to be able to summon the bug first, then you can theorise about it, and finally check the theory.' },
      { k: 'single', q: 'Why reproduce the bug first?', opts: ['Because it is tidy', 'Because otherwise you cannot tell whether you fixed it', 'Because it is faster'], answer: 1, why: 'If you cannot summon it, you cannot prove it is gone. You will only believe it is.' },
      { k: 'single', q: 'What does halving mean in debugging?', opts: ['You halve the code and see which half holds the bug', 'You run it twice', 'You halve the input'], answer: 0, why: 'One check in the middle halves the search space. Ten halvings narrow it a thousandfold.' },
      { k: 'single', q: 'What if "something fixed it" but you do not know what?', opts: ['Be glad and move on', 'Understand it, or it will come back elsewhere', 'Rewrite everything'], answer: 1, why: 'A fix you do not understand means you found the symptom, not the cause.' },
    ],
    note: {
      summary: ['Four steps: reproduce → narrow → hypothesise → check.', 'If you cannot summon the bug, you cannot prove the fix either.', 'Narrow by halving: a `print` in the middle halves the search space.', 'A hypothesis is a checkable claim, not a hunch.', 'The code shows what you meant; the printed value shows what is.', 'A fix you do not understand will come back.'],
      terms: [{ term: 'reproduction', def: 'Summoning the bug on demand with a minimal input.' }, { term: 'halving', def: 'Cutting the search space in two with an intermediate check.' }, { term: 'hypothesis', def: 'A checkable claim about what causes the bug.' }],
    },
  },
  {
    day: 21,
    title: 'Fixing a broken program',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'No new material today, only practice. Here is a program that is almost right. It holds three bugs — find all three with yesterday\'s method.' },
      { k: 'code', lang: 'py', src: 'def largest(numbers):\n    largest = 0                        # (1)\n    for i in range(1, len(numbers)):   # (2)\n        if numbers[i] > largest:\n            largest = numbers[i]\n    return largest\n\nprint(largest([-5, -2, -9]))           # expected: -2\nprint(largest([3]))                    # expected: 3', explain: 'Run both calls in your head before reading on. Which line causes which wrong answer?' },
      { k: 'text', md: '**Bug (1):** starting from zero assumes there is a positive number in the list. With all-negative input it answers wrongly. It should start from the **first item**.\n\n**Bug (2):** the loop starting at 1 skips item zero. With a one-item list it never runs at all.\n\n**Bug (3):** on an empty list `numbers[0]` blows up. That case needs handling of its own.' },
      { k: 'code', lang: 'py', src: 'def largest(numbers):\n    if not numbers:\n        return None\n    best = numbers[0]\n    for x in numbers:\n        if x > best:\n            best = x\n    return best', explain: 'The fixed version. Note also that the variable no longer shares its name with the function — that was confusing too.' },
      { k: 'callout', tone: 'key', md: 'All three were **edge cases**: all negative, one item, no items. Most bugs live here, not in the typical input. When you think you are done, always ask: what if it is empty? what if there is one? what if they are all negative?' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'This `count` function miscounts the even numbers. Find the bug and fix it.',
      starter: 'def count(numbers):\n    n = 0\n    for x in numbers:\n        if x % 2 == 1:\n            n = n + 1\n    return n\n\nprint(count([1, 2, 3, 4, 6]))\n',
      checks: [{ k: 'output', contains: '3', label: 'There are three even numbers: 2, 4, 6' }],
      hints: ['Print which number triggers the increment.', '`% 2 == 1` finds the odd ones, not the even.', 'The fix: `if x % 2 == 0:`.'],
    },
    quiz: [
      { k: 'single', q: 'Why is starting a maximum search from zero wrong?', opts: ['It is slow', 'With all-negative numbers it answers wrongly', 'It will not compile'], answer: 1, why: 'Zero is not in the list, yet it takes part in the comparison. With all-negative input it "wins" despite not being in the data.' },
      { k: 'single', q: 'What does `for i in range(1, len(list))` skip?', opts: ['The last item', 'Item zero', 'Nothing'], answer: 1, why: 'It starts at index 1, so it jumps over the very first item. With a one-item list it never runs.' },
      { k: 'multi', q: 'Which two edge cases are always worth thinking through?', opts: ['Empty input', 'Very large input', 'One-item input', 'Exactly ten items'], answers: [0, 2], why: 'Empty and single-item inputs break more loops and index expressions than anything else. Most bugs live there.' },
      { k: 'single', q: 'Why is naming a variable the same as the function confusing?', opts: ['It raises', 'It hides the original name and confuses the reader', 'It runs slower'], answer: 1, why: 'Python allows it, but the function name becomes unreachable inside the function, and the reader gets lost too.' },
    ],
    note: {
      summary: ['Most bugs live in edge cases: empty, one item, all negative.', 'Start a maximum search from the first item, not from zero.', '`range(1, n)` skips item zero — with one item it never runs.', 'Handle empty input before indexing into it.', 'Do not give a variable the same name as its function.', 'Being done means having thought through the edges too.'],
      terms: [{ term: 'edge case', def: 'An extreme input: empty, single, all-equal or all-negative.' }, { term: 'off-by-one', def: 'A bug caused by a loop bound that is one out.' }, { term: 'shadowing', def: 'When a variable name hides another thing of the same name.' }],
    },
  },
  {
    day: 22,
    title: 'Modules and imports',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'A serious program does not fit in one file. A **module** is a single `.py` file you can use from another.' },
      { k: 'code', lang: 'py', src: '# maths.py\ndef area(a, b):\n    return a * b\n\nPI = 3.14159', explain: 'That is a module. Nothing special about it — one file, with functions and values.' },
      { k: 'code', lang: 'py', src: '# main.py\nimport maths\nprint(maths.area(3, 4))\n\nfrom maths import area, PI\nprint(area(3, 4), PI)', explain: '`import maths` brings the whole module, reached with the `maths.` prefix. `from ... import ...` pulls specific names in directly.' },
      { k: 'callout', tone: 'tip', md: 'Avoid `from maths import *`. It brings everything in anonymously, and in six months nobody will know where a function came from.' },
      { k: 'text', md: 'The most useful **built-in modules**: `math` (roots, trigonometry), `random`, `json`, `os`, `datetime`, `time`.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Import the `math` module and print the square root of 2 to three decimals, plus the value of `math.pi`.',
      starter: 'import math\n',
      checks: [{ k: 'output', contains: '1.414', label: 'The square root of 2 appears' }, { k: 'output', contains: '3.14', label: 'Pi appears' }],
      hints: ['`math.sqrt(2)` is the square root.', 'Formatting: `f"{math.sqrt(2):.3f}"`.', '`print(math.pi)`'],
    },
    quiz: [
      { k: 'single', q: 'What is a module?', opts: ['A function', 'A .py file you can use from another file', 'A class'], answer: 1, why: 'Every `.py` file is a module. `import` makes its contents available from another file.' },
      { k: 'single', q: 'What is the difference between `import math` and `from math import sqrt`?', opts: ['Nothing', 'The first needs math.sqrt(), the second just sqrt()', 'The second is faster'], answer: 1, why: '`import` brings in the module, reached by qualified name. `from ... import` pulls specific names in directly.' },
      { k: 'single', q: 'Why avoid `from module import *`?', opts: ['It is slow', 'You cannot tell which name came from where', 'It does not work'], answer: 1, why: 'After a couple of star imports it is impossible to say which function came from which module — and names can collide.' },
      { k: 'multi', q: 'Which two are built-in Python modules?', opts: ['math', 'rover', 'json', 'kinematics'], answers: [0, 2], why: '`math` and `json` ship with Python and need no install. The other two are made up.' },
    ],
    note: {
      summary: ['A module is a `.py` file you can use from another file.', '`import module` — reach everything by qualified name (`module.func()`).', '`from module import name` — pulls the name in directly.', 'Avoid star imports: they hide where a name came from.', 'Useful built-ins: `math`, `random`, `json`, `os`, `datetime`, `time`.'],
      terms: [{ term: 'module', def: 'A single Python file importable from another.' }, { term: 'import', def: "Making another module's contents available." }, { term: 'standard library', def: 'The collection of modules that ship with Python.' }],
    },
  },
  {
    day: 23,
    title: 'Using libraries',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **library** is code somebody else wrote that you can use. In robotics and physics, almost everything you will need already exists.' },
      { k: 'code', lang: 'py', src: 'import math\n\nprint(math.sqrt(16))               # 4.0\nprint(math.degrees(math.pi))       # 180.0\nprint(math.sin(math.radians(30)))  # 0.5\nprint(math.hypot(3, 4))            # 5.0 — distance from the origin', explain: '`hypot` is Pythagoras in one call. It is exactly how you compute the distance to your robot\'s position.' },
      { k: 'code', lang: 'py', src: 'import random\n\nprint(random.randint(1, 6))      # a die roll\nprint(random.choice(["left", "right"]))\nrandom.seed(42)                  # repeatable randomness', explain: '`seed` pins the randomness: the same seed gives the same sequence. When testing a simulation that is essential.' },
      { k: 'callout', tone: 'key', md: 'In robotics you will meet these: `numpy` (matrices), `matplotlib` (plots), `pyserial` (talking to a microcontroller), `opencv` (camera images). You do not need to learn any of them now — just know they exist.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'The robot is at (3, 4). Use `math` to compute its distance from the origin and the heading in degrees.',
      starter: 'import math\n\nx, y = 3, 4\n',
      checks: [{ k: 'output', contains: '5', label: 'The distance is 5' }],
      hints: ['Distance: `math.hypot(x, y)`.', 'Angle in radians: `math.atan2(y, x)`.', 'To degrees: `math.degrees(...)`.'],
    },
    quiz: [
      { k: 'numeric', q: 'What is `math.hypot(3, 4)`?', answer: 5, tol: 0.01, why: 'Pythagoras: sqrt(3² + 4²) = sqrt(25) = 5. This is the most common distance calculation in robotics.' },
      { k: 'single', q: 'What does `random.seed(42)` do?', opts: ['Generates forty-two random numbers', 'Pins the random sequence so it repeats', 'Clears all randomness'], answer: 1, why: 'The same seed gives the same sequence. Without it you could not run a simulation twice the same way.' },
      { k: 'single', q: 'What unit does `math.sin` expect?', opts: ['Degrees', 'Radians', 'Either'], answer: 1, why: 'Radians. `math.radians()` converts from degrees — forgetting that is a classic source of bugs.' },
      { k: 'single', q: 'Why use an existing library?', opts: ['Less typing', 'It is tried and tested, unlike yours', 'It runs faster'], answer: 1, why: 'A widely used library has been used and fixed by thousands. Your implementation has been used by nobody.' },
    ],
    note: {
      summary: ['A library is finished, tested code written by others.', '`math`: `sqrt`, `hypot`, `sin`/`cos`, `radians`/`degrees`.', 'Trigonometric functions expect radians — convert with `math.radians()`.', '`random.seed(n)` makes randomness repeatable; essential for testing a simulation.', 'In robotics: numpy, matplotlib, pyserial, opencv — worth knowing they exist.'],
      terms: [{ term: 'library', def: 'A reusable package of code written by others.' }, { term: 'radian', def: 'The angle unit the mathematical functions expect.' }, { term: 'seed', def: 'The starting point of the random generator, making the sequence repeatable.' }],
    },
  },
];
