import type { Track } from '../../types';
import { codeEnB } from './code-b';
import { codeEnC } from './code-c';
import { codeEnD } from './code-d';

export const codeEn: Track = {
  id: 'code',
  title: 'Coding',
  blurb: 'From zero to driving a robot with your own code.',
  plannedTitles: [
    'Variables and types',
    'Branching: if, elif, else',
    'Loops: while and for',
    'Lists',
    'Dictionaries',
    'Loop patterns over lists',
    'Functions',
    'Parameters and return values',
    'Scope and side effects',
    'Working with text',
    'Formatting and input',
    'Text processing in practice',
    'Reading and writing files',
    'JSON and structured data',
    'Saving and reloading data',
    'Classes and objects',
    'State and methods',
    'Inheritance, when it earns its place',
    'Errors and exceptions',
    'Debugging methodically',
    'Fixing a broken program',
    'Modules and imports',
    'Using libraries',
    'Reading documentation',
    'Search: linear and binary',
    'Sorting and why it matters',
    'Complexity in plain words',
    'Robot controller: the sensor loop',
    'Robot controller: decision logic',
    'Robot controller: a full mission',
  ],
  days: [
    // ── Day 1 ───────────────────────────────────────────────────────
    {
      day: 1,
      title: 'Variables and types',
      minutes: 20,
      lesson: [
        {
          k: 'text',
          md: 'A program works with data. A **variable** is a name you use to refer to a piece of data. That is all it is — not a box, not magic. A label you hang on a value so you can address it later.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'distance = 15\nname = "Rover"\nrunning = True\n\nprint(name, distance)',
          explain: 'Three variables, three different kinds of data. The `=` here does not mean equality. It means: "from now on I call this value by this name."',
        },
        {
          k: 'text',
          md: 'Every value has a **type**, and the type decides what you can do with it. You can add two numbers. You can join two pieces of text. You cannot add a number to a piece of text — Python raises an error, and that is good news: better it complains than quietly does something silly.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'print(2 + 3)        # 5        — number + number\nprint("2" + "3")    # 23       — text + text\nprint(type(2))      # <class \'int\'>\nprint(type("2"))    # <class \'str\'>',
          explain: '`type()` tells you what you are holding. When you cannot work out what is happening, this is the first question to ask.',
        },
        {
          k: 'text',
          md: 'The four types you will use for the next few weeks:\n\n- `int` — whole number: `15`, `-3`, `0`\n- `float` — decimal number: `3.14`, `0.5`\n- `str` — text: `"Rover"`, `"hello"`\n- `bool` — true or false: `True`, `False`',
        },
        {
          k: 'callout',
          tone: 'key',
          md: 'On your robot this is not theory. The distance sensor gives you a `float` (12.7 cm). Whether a motor is on is a `bool`. The robot name is a `str`. Compute with the wrong type and the robot drives into the wall.',
        },
        {
          k: 'callout',
          tone: 'tip',
          md: 'Give your variables names that say what is in them. `distance_cm` beats `d`. In six months you are the one who will not understand your own code.',
        },
      ],
      lab: {
        lab: 'code',
        lang: 'py',
        brief: 'Create a variable called `distance` holding 42, and a variable called `name` holding "Rover". Print them on one line, separated by a space.',
        starter: '# Write your solution here\n',
        checks: [
          { k: 'output', contains: 'Rover', label: 'The output contains the name' },
          { k: 'output', contains: '42', label: 'The output contains the distance' },
        ],
        hints: [
          'Creating a variable looks like `name = "Rover"`.',
          'You can print several things at once: `print(a, b)`.',
          'Full solution: `distance = 42`, then `name = "Rover"`, then `print(name, distance)`.',
        ],
      },
      quiz: [
        {
          k: 'single',
          q: 'What does the `=` do in the line `distance = 15`?',
          opts: [
            'It checks whether distance equals 15',
            'It binds the value 15 to the name distance',
            'It prints 15 to the screen',
          ],
          answer: 1,
          why: 'A single `=` is assignment: it binds the right-hand value to the left-hand name. Testing equality is `==`, which we meet tomorrow.',
        },
        {
          k: 'output',
          q: 'What does this print?',
          code: 'print("2" + "3")',
          lang: 'py',
          opts: ['5', '23', 'It raises an error'],
          answer: 1,
          why: 'Both values are text, and `+` joins text rather than adding it. Converted to numbers (`int("2") + int("3")`) you would get 5.',
        },
        {
          k: 'single',
          q: 'What type is the value `True`?',
          opts: ['str', 'int', 'bool'],
          answer: 2,
          why: '`bool` is the logical type with exactly two values, `True` and `False`. Every decision your program makes is built out of these.',
        },
        {
          k: 'multi',
          q: 'Which two variable names tell you what they hold?',
          opts: ['x', 'battery_percent', 'a1', 'motor_rpm'],
          answers: [1, 3],
          why: 'A descriptive name is one you still understand six months later. `x` and `a1` say nothing, and that is exactly what you will be missing when you hunt a bug.',
        },
        {
          k: 'numeric',
          q: 'What is the result of `3 + 4 * 2`?',
          answer: 11,
          tol: 0.01,
          why: 'Multiplication happens before addition, the same as in maths class: 4*2 = 8, then 3+8 = 11. If you expected 14 you were thinking of `(3+4)*2`.',
        },
      ],
      note: {
        summary: [
          'A variable is a name that refers to a value. `=` is assignment, not equality.',
          'Every value has a type, and the type decides which operations make sense on it.',
          'Four core types: `int` (whole), `float` (decimal), `str` (text), `bool` (true/false).',
          '`+` adds numbers and joins text. Mixing a number and text raises an error.',
          '`type(value)` tells you what you are holding — the first question when something looks wrong.',
          'A descriptive variable name is not style. It is what saves you time when debugging.',
        ],
        terms: [
          { term: 'variable', def: 'A name that refers to a stored value.' },
          { term: 'assignment', def: 'The `=` operation, binding the right-hand value to the left-hand name.' },
          { term: 'type', def: 'The kind of a value, which decides what operations are valid on it.' },
          { term: 'bool', def: 'The logical type with two values: `True` and `False`.' },
        ],
      },
    },

    // ── Day 2 ───────────────────────────────────────────────────────
    {
      day: 2,
      title: 'Branching: if, elif, else',
      minutes: 22,
      lesson: [
        {
          k: 'text',
          md: 'Until now your program ran straight down every line. **Branching** is the first tool that lets it decide: if this is true do that, otherwise do something else.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'distance = 8\n\nif distance < 10:\n    print("Obstacle! Brake.")\nelse:\n    print("Road is clear.")',
          explain: 'The **indented** lines after the `:` belong to the `if`. In Python indentation is not decoration — it is what says which lines belong where.',
        },
        {
          k: 'text',
          md: 'After `if` comes a **condition** that is either true or false. The comparison operators:\n\n- `==` equal (two equals signs!)\n- `!=` not equal\n- `<` `>` less than, greater than\n- `<=` `>=` at most, at least',
        },
        {
          k: 'callout',
          tone: 'warn',
          md: '`=` assigns, `==` compares. This is the most common beginner mistake, and thankfully Python raises an error rather than quietly giving a wrong answer.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'battery = 35\n\nif battery > 70:\n    print("Full speed")\nelif battery > 20:\n    print("Economy mode")\nelse:\n    print("Needs charging")',
          explain: '`elif` means "otherwise if". It checks top to bottom and stops at the **first** true branch. 35 is not above 70, but it is above 20, so: "Economy mode".',
        },
        {
          k: 'text',
          md: 'You can combine conditions: `and` (both true), `or` (at least one true), `not` (flips it).',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'if distance > 20 and battery > 30:\n    print("We can go fast")',
        },
        {
          k: 'callout',
          tone: 'key',
          md: "Your robot's whole behaviour is made of decisions like these: if the wall is close, turn; if the battery is low, slow down; if you see the goal, stop. From day 28 that is exactly what you will be writing.",
        },
      ],
      lab: {
        lab: 'code',
        lang: 'py',
        brief: 'You are given a `distance` variable. Write a branch: below 10 print "STOP"; between 10 and 30 print "SLOW"; otherwise print "GO". Try it with several values.',
        starter: 'distance = 15\n\n# Your branch goes here\n',
        checks: [{ k: 'output', contains: 'SLOW', label: 'At 15 the answer is SLOW' }],
        hints: [
          'Start with `if distance < 10:`',
          'For the middle case `elif distance < 30:` is enough — only values that were not below 10 reach it.',
          'Finish with an `else:` branch for everything else.',
        ],
      },
      quiz: [
        {
          k: 'single',
          q: 'What is the difference between `=` and `==`?',
          opts: [
            'Nothing, both compare',
            '`=` assigns, `==` compares',
            '`=` compares, `==` assigns',
          ],
          answer: 1,
          why: '`=` binds a value to a name. `==` asks whether two values are equal and answers `True` or `False`.',
        },
        {
          k: 'output',
          q: 'What does this print?',
          code: 'battery = 35\nif battery > 70:\n    print("A")\nelif battery > 20:\n    print("B")\nelse:\n    print("C")',
          lang: 'py',
          opts: ['A', 'B', 'C', 'Both B and C'],
          answer: 1,
          why: 'In an `elif` chain the first true branch runs and the program then leaves the chain. 35 is not above 70 but is above 20, so "B" — and only that.',
        },
        {
          k: 'single',
          q: 'When is `a > 5 and b < 3` true?',
          opts: ['When at least one is true', 'When both are true', 'When neither is true'],
          answer: 1,
          why: '`and` needs both sides to be true. If either is false the whole thing is false. "At least one" is `or`.',
        },
        {
          k: 'single',
          q: 'Why does indentation matter in Python?',
          opts: [
            'It is purely cosmetic',
            'Indentation is what says which lines belong to the if',
            'Python ignores it',
          ],
          answer: 1,
          why: 'Other languages mark a block with braces; Python uses indentation. A stray space is therefore not a style slip — it changes what your program does.',
        },
      ],
      note: {
        summary: [
          '`if` decides on a condition: the true branch runs, the others do not.',
          'In an `elif` chain the **first** true branch runs, then the program leaves the chain.',
          'Comparisons: `==`, `!=`, `<`, `>`, `<=`, `>=`. `=` by contrast is assignment.',
          'Combining conditions: `and` (both), `or` (at least one), `not` (flip).',
          'Indentation decides which lines belong to a block — it is structure, not decoration.',
        ],
        terms: [
          { term: 'condition', def: 'An expression whose value is true or false.' },
          { term: 'elif', def: '"Otherwise if" — a further branch, checked only when the earlier ones were false.' },
          { term: 'block', def: 'A group of lines that belong together, marked in Python by indentation.' },
          { term: 'logical operator', def: '`and`, `or` and `not`, which combine conditions.' },
        ],
      },
    },

    // ── Day 3 ───────────────────────────────────────────────────────
    {
      day: 3,
      title: 'Loops: while and for',
      minutes: 24,
      lesson: [
        {
          k: 'text',
          md: 'A **loop** repeats something. This is what makes a computer useful: it never gets bored, and it does not slip on the ten-thousandth round.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'for i in range(5):\n    print("step", i)',
          explain: '`for` walks every item of a sequence. `range(5)` gives 0, 1, 2, 3, 4 — **five** of them, but starting from zero.',
        },
        {
          k: 'callout',
          tone: 'warn',
          md: '`range(5)` does not include 5. That looks odd until you get used to it, and then it is obvious: `range(n)` always gives exactly `n` numbers.',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'distance = 100\n\nwhile distance > 0:\n    print(distance, "cm to go")\n    distance = distance - 20',
          explain: '`while` repeats as long as the condition holds. Look at that last line: leave it out and the condition would stay true forever.',
        },
        {
          k: 'callout',
          tone: 'key',
          md: 'For every `while` loop, ask: **what is it that eventually ends this?** If you cannot answer, you have written an infinite loop. The FORGE Code Lab stops your code after three seconds, but on a real robot this is a flat battery.',
        },
        {
          k: 'text',
          md: 'Two extra keywords:\n\n- `break` — leave the loop immediately\n- `continue` — skip the rest of this round and start the next one',
        },
        {
          k: 'code',
          lang: 'py',
          src: 'for i in range(10):\n    if i == 3:\n        continue     # skip the 3\n    if i == 6:\n        break        # stop at 6\n    print(i)',
          explain: 'The output is 0 1 2 4 5. The 3 is skipped and at 6 the loop ends.',
        },
      ],
      lab: {
        lab: 'code',
        lang: 'py',
        brief: 'Use a loop to print every even number between 2 and 20, one per line. (Hint: a number is even when `n % 2 == 0`.)',
        starter: '# % gives the remainder: 7 % 2 == 1, 8 % 2 == 0\n',
        checks: [
          { k: 'output', contains: '2', label: '2 is included' },
          { k: 'output', contains: '20', label: '20 is included' },
        ],
        hints: [
          'Walk the numbers: `for n in range(2, 21):`',
          '`range(2, 21)` runs from 2 to 20 — the upper bound is not included.',
          'Inside the loop: `if n % 2 == 0: print(n)`. Or more neatly, `range(2, 21, 2)` steps by two.',
        ],
      },
      quiz: [
        {
          k: 'numeric',
          q: 'How many numbers does `range(5)` produce?',
          answer: 5,
          tol: 0.01,
          why: '`range(n)` always produces exactly n numbers, from 0 to n-1. So 0, 1, 2, 3, 4 — five of them, and 5 is not among them.',
        },
        {
          k: 'output',
          q: 'What does this print?',
          code: 'for i in range(4):\n    if i == 2:\n        break\n    print(i)',
          lang: 'py',
          opts: ['0 1 2 3', '0 1', '0 1 2', 'nothing'],
          answer: 1,
          why: '`break` leaves immediately, before the `print` runs. 0 and 1 are printed, then at i=2 the loop ends.',
        },
        {
          k: 'single',
          q: 'What makes a `while` loop infinite?',
          opts: [
            'Using `while` instead of `for`',
            'Nothing in it ever makes the condition false',
            'Running more than 1000 times',
          ],
          answer: 1,
          why: '`while` repeats as long as the condition is true. If nothing inside moves the condition towards false, it never ends. Always find the line that moves you towards the exit.',
        },
        {
          k: 'single',
          q: 'What is the difference between `break` and `continue`?',
          opts: [
            'break skips a round, continue exits',
            'break exits the loop, continue jumps to the next round',
            'They are the same',
          ],
          answer: 1,
          why: '`break` ends the whole loop. `continue` only skips the rest of this round and moves on to the next iteration.',
        },
        {
          k: 'order',
          q: 'In what order do things happen in a `while` loop?',
          items: ['The body runs', 'The condition is evaluated', 'Control returns to the condition'],
          correct: [1, 0, 2],
          why: '`while` always checks the condition first — which is why the body may never run at all. Then the body, then back to the condition.',
        },
      ],
      note: {
        summary: [
          '`for` walks the items of a sequence; `range(n)` gives n numbers from 0 to n-1.',
          '`range(a, b)` runs from a to b-1, and `range(a, b, step)` steps by step.',
          '`while` repeats while its condition holds — always include something that moves towards the exit.',
          'An infinite loop is one whose condition never becomes false. The Code Lab stops it after 3 seconds.',
          '`break` leaves the loop, `continue` jumps to the next round.',
          '`%` gives the remainder; `n % 2 == 0` is the standard even-number test.',
        ],
        terms: [
          { term: 'loop', def: 'A structure that runs a piece of code more than once.' },
          { term: 'range', def: 'A function producing a sequence of numbers; the upper bound is excluded.' },
          { term: 'infinite loop', def: 'A loop whose condition never becomes false.' },
          { term: 'break', def: 'Leaves the loop immediately.' },
          { term: 'continue', def: 'Skips the rest of the current round.' },
        ],
      },
    },

    {
      day: 4,
      title: 'Lists',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'So far one variable held one value. A **list** holds many values under one name, in order. It is your first data structure.' },
        { k: 'code', lang: 'py', src: 'distances = [12, 8, 30, 5]\n\nprint(distances[0])      # 12  — the first item\nprint(distances[-1])     # 5   — the last one\nprint(len(distances))    # 4   — how many there are', explain: 'Numbering starts at **zero**. A negative index counts from the end.' },
        { k: 'callout', tone: 'warn', md: 'In a four-item list the last index is **3**, not 4. `distances[4]` raises `IndexError`.' },
        { k: 'code', lang: 'py', src: 'distances.append(21)     # add to the end\ndistances[0] = 99        # overwrite\ndistances.remove(8)      # drop the first 8\n\nprint(distances)         # [99, 30, 5, 21]\nprint(min(distances), max(distances), sum(distances))' },
        { k: 'text', md: 'Walking a list with `for` is the natural way:\n\n- `for d in distances:` — gives you the **values**\n- `for i, d in enumerate(distances):` — the index **and** the value' },
        { k: 'callout', tone: 'key', md: "Your robot's sensors hand you lists: the last ten readings, the waypoints of a route, the queue of commands. Handle lists and you can program a robot." },
      ],
      lab: {
        lab: 'code', lang: 'py',
        brief: 'Given `readings = [12, 8, 30, 5, 21]`, print the smallest and largest value, then the average to one decimal place.',
        starter: 'readings = [12, 8, 30, 5, 21]\n',
        checks: [{ k: 'output', contains: '30', label: 'The largest value appears' }, { k: 'output', contains: '5', label: 'The smallest value appears' }],
        hints: ['`min(list)` and `max(list)` are built in.', 'Average: `sum(readings) / len(readings)`.', 'Rounding: `round(avg, 1)`.'],
      },
      quiz: [
        { k: 'numeric', q: 'What is the value of `[10, 20, 30][1]`?', answer: 20, tol: 0.01, why: 'Numbering starts at zero, so index 1 is the **second** item: 20.' },
        { k: 'single', q: 'What does `lst.append(5)` do?', opts: ['Puts 5 at the front', 'Puts 5 at the end', 'Replaces every item with 5'], answer: 1, why: '`append` always adds at the end. To put something at the front, use `insert(0, 5)`.' },
        { k: 'output', q: 'What does this print?', code: 'x = [1, 2, 3]\nprint(len(x), x[-1])', lang: 'py', opts: ['3 3', '3 1', '2 3'], answer: 0, why: '`len` is the count (3) and index `-1` is the last item (also 3). The two happen to match here.' },
        { k: 'single', q: 'What happens when you evaluate `[1,2,3][3]`?', opts: ['It gives 3', 'It raises IndexError', 'It gives None'], answer: 1, why: 'With three items the valid indexes are 0, 1 and 2. Index 3 is past the end, so `IndexError`.' },
      ],
      note: {
        summary: ['A list holds many values under one name, in order.', 'Numbering starts at zero; `-1` is the last item.', '`append` adds, `remove` deletes, `len` counts.', '`min`, `max` and `sum` process the whole list in one step.', '`for x in list` walks the values; `enumerate` also gives the index.'],
        terms: [{ term: 'list', def: 'An ordered collection whose items you reach by index.' }, { term: 'index', def: "An item's position in a list, counting from zero." }, { term: 'IndexError', def: 'The error raised when you reference an index that does not exist.' }],
      },
    },
    {
      day: 5,
      title: 'Dictionaries',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'In a list you look things up by number. In a **dictionary** you look them up by name. When you ask "what is the battery level?", you do not care which position it is in — you care what it is called.' },
        { k: 'code', lang: 'py', src: "robot = {\n    'name': 'Rover',\n    'battery': 78,\n    'speed': 12.5,\n}\n\nprint(robot['name'])        # Rover\nrobot['battery'] = 61       # overwrite\nrobot['fault'] = None       # new key", explain: 'The **key** is usually text; the **value** can be anything — a number, text, a list, even another dictionary.' },
        { k: 'callout', tone: 'warn', md: "A missing key makes `robot['nope']` raise. `robot.get('nope')` gives `None` instead, and `robot.get('nope', 0)` gives zero. With sensor data that is what saves you." },
        { k: 'code', lang: 'py', src: "for key, value in robot.items():\n    print(key, '=', value)\n\nprint('battery' in robot)     # True" },
        { k: 'callout', tone: 'key', md: "A robot's state is naturally a dictionary: position, heading, battery, sensor readings. When you later save it as JSON, this is exactly the shape that goes to the file." },
      ],
      lab: {
        lab: 'code', lang: 'py',
        brief: 'Build a dictionary describing your robot: `name`, `battery` (a number) and `active` (True/False). Print all three keys with their values, one per line.',
        starter: '',
        checks: [{ k: 'output', contains: 'battery', label: 'The battery key appears' }],
        hints: ["A dictionary: `robot = {'name': 'Rover', 'battery': 80, 'active': True}`.", 'Walk it with `for k, v in robot.items():`', 'Print with `print(k, v)`.'],
      },
      quiz: [
        { k: 'single', q: 'How does a dictionary differ from a list?', opts: ['You reach items by key, not by position', 'It can only hold numbers', 'It cannot be changed'], answer: 0, why: 'A list identifies by position, a dictionary by name. That is what makes it readable when the data means something.' },
        { k: 'single', q: "What does `d.get('nope', 0)` give when the key is missing?", opts: ['It raises an error', 'It gives 0', 'It gives None'], answer: 1, why: "`get`'s second argument is the fallback returned for a missing key. That is exactly why it does not raise." },
        { k: 'output', q: 'What does this print?', code: "d = {'a': 1}\nd['a'] = 2\nprint(len(d))", lang: 'py', opts: ['1', '2', 'It raises'], answer: 0, why: 'We wrote to the same key again rather than adding a new one. A key can appear only once in a dictionary.' },
        { k: 'multi', q: 'Which two statements about dictionaries are true?', opts: ['Keys are unique', 'Every key must be a number', 'A value can be a list', 'You cannot loop over it'], answers: [0, 2], why: 'Keys are unique and values can be any type. Keys need not be numbers, and a dictionary can be walked with `for`.' },
      ],
      note: {
        summary: ['A dictionary stores key-value pairs; you look items up by key.', 'Build it with braces, reach into it with square brackets.', '`get(key, fallback)` does not raise on a missing key.', '`.items()` gives you key and value together in one loop.', 'A key appears only once: writing to it again replaces rather than adds.'],
        terms: [{ term: 'dictionary', def: 'A data structure of key-value pairs.' }, { term: 'key', def: 'The name you use to reach a value in a dictionary.' }, { term: 'get', def: 'A safe lookup that returns a fallback for a missing key.' }],
      },
    },
    {
      day: 6,
      title: 'Loop patterns over lists',
      minutes: 24,
      lesson: [
        { k: 'text', md: 'Four patterns that will solve ninety per cent of your list problems. Learn to recognise them, because they come back again and again.' },
        { k: 'code', lang: 'py', src: '# 1. Summing\ntotal = 0\nfor d in distances:\n    total = total + d\n\n# 2. Filtering\nnear = []\nfor d in distances:\n    if d < 15:\n        near.append(d)', explain: 'Summing starts with an accumulator. Filtering starts with an empty list you only add the matches to.' },
        { k: 'code', lang: 'py', src: '# 3. Searching (is there one?)\ndanger = False\nfor d in distances:\n    if d < 5:\n        danger = True\n        break\n\n# 4. Extreme value\nsmallest = distances[0]\nfor d in distances:\n    if d < smallest:\n        smallest = d', explain: 'The `break` matters when searching: once you have found it, there is no point looking further.' },
        { k: 'callout', tone: 'tip', md: 'Python has shorter forms for all of these (`sum`, `min`, `[d for d in distances if d < 15]`), but write the loop first. Once you understand what it does, use the short form.' },
      ],
      lab: {
        lab: 'code', lang: 'py',
        brief: 'Given `readings = [22, 4, 17, 3, 30, 9]`, collect the values below 10 into their own list and print how many there are.',
        starter: 'readings = [22, 4, 17, 3, 30, 9]\nsmall = []\n',
        checks: [{ k: 'output', contains: '3', label: 'There are three small values' }],
        hints: ['Walk the list with `for r in readings:`.', 'Inside the loop: `if r < 10: small.append(r)`.', 'At the end: `print(len(small))`.'],
      },
      quiz: [
        { k: 'single', q: 'Why does filtering start with an empty list?', opts: ['Because otherwise it is slow', 'Because that is where you collect the matches', 'It does not, that is unnecessary'], answer: 1, why: 'The empty list is the collecting place. Without creating it first, `append` has nothing to add to.' },
        { k: 'single', q: 'What does `break` buy you in a search?', opts: ['A more accurate answer', 'It stops looking once there is nothing left to learn', 'More memory'], answer: 1, why: 'The answer would be the same without it; it would just walk the rest for nothing. On a large list that is real time.' },
        { k: 'output', q: 'What does this print?', code: 's = 0\nfor x in [1, 2, 3]:\n    s = s + x\nprint(s)', lang: 'py', opts: ['3', '6', '123'], answer: 1, why: 'This is the summing pattern: 0+1=1, 1+2=3, 3+3=6.' },
        { k: 'order', q: 'In what order does a filter loop come together?', items: ['Test the condition', 'Create the empty list', 'Append the match'], correct: [1, 0, 2], why: 'The collecting place has to exist first, then the test runs, and the append happens inside the true branch of that test.' },
      ],
      note: {
        summary: ['Summing: an accumulator from zero, adding every item.', 'Filtering: an empty list, appending only what matches.', 'Searching: a flag plus `break` once found.', 'Extreme value: start from the first item and only swap when you find better.', 'These patterns look the same in every language — they are not Python-specific.'],
        terms: [{ term: 'accumulator', def: 'A variable created before the loop that collects the running result.' }, { term: 'filtering', def: 'Selecting the items of a list that meet a condition.' }, { term: 'extreme-value search', def: 'Finding the smallest or largest item by walking the whole list.' }],
      },
    },
    ...codeEnB,
    ...codeEnC,
    ...codeEnD,
  ],
};
