import type { Day } from '../../types';

/** CODE track, days 7–15. */
export const codeEnB: Day[] = [
  {
    day: 7,
    title: 'Functions',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **function** is a named piece of code you can call from anywhere. It buys you two things: you stop writing the same thing twice, and you get to give a name to an idea.' },
      { k: 'code', lang: 'py', src: 'def greet():\n    print("Hello, Rover!")\n\ngreet()\ngreet()', explain: '`def` defines; `greet()` **calls**. The definition on its own runs nothing — it only teaches the program what the name means.' },
      { k: 'code', lang: 'py', src: 'def area(a, b):\n    return a * b\n\nt = area(3, 4)\nprint(t)     # 12', explain: '`a` and `b` are **parameters**. `return` hands the result back to the caller.' },
      { k: 'callout', tone: 'warn', md: '`print` and `return` are not the same thing. `print` shows it on screen and forgets it. `return` hands the value back so you can keep computing with it. A function that only prints gives you nothing to use.' },
      { k: 'callout', tone: 'key', md: 'A good rule: a function does one thing, and its name says which. If the name needs an "and", it probably wants to be two functions.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a function called `double(n)` that returns twice the number it is given. Call it with 21 and print the result.',
      starter: 'def double(n):\n    pass\n\n',
      checks: [{ k: 'output', contains: '42', label: 'double(21) gives 42' }],
      hints: ['Replace `pass` with `return n * 2`.', 'Call it: `print(double(21))`.'],
    },
    quiz: [
      { k: 'single', q: 'What is the difference between `print` and `return`?', opts: ['Nothing, they are the same', 'print displays, return hands the value back to the caller', 'return displays, print hands back'], answer: 1, why: '`print` only shows. `return` gives a value you can store or compute with. This is the most common beginner mix-up.' },
      { k: 'output', q: 'What does this print?', code: 'def f(x):\n    return x + 1\n\nprint(f(f(1)))', lang: 'py', opts: ['2', '3', '1'], answer: 1, why: 'Inside out: f(1) = 2, then f(2) = 3.' },
      { k: 'single', q: 'What does the line `def add(a, b):` do on its own?', opts: ['Computes a+b', 'Only defines the function; it does not run it', 'Raises an error'], answer: 1, why: 'A definition just teaches the name. Nothing happens until you call it: `add(2, 3)`.' },
      { k: 'single', q: 'What does a function with no `return` give back?', opts: ['0', 'None', 'It raises'], answer: 1, why: 'Without a `return`, Python hands back `None`. That is why you get `None` when you print instead of returning.' },
    ],
    note: {
      summary: ['A function is a named, reusable piece of code.', '`def` defines it; the call with parentheses runs it.', 'Parameters are the inputs; `return` hands back the result.', '`print` displays, `return` gives a value — they are not interchangeable.', 'A function with no `return` gives back `None`.', 'One function, one job, and the name says which.'],
      terms: [{ term: 'function', def: 'A named, reusable piece of code.' }, { term: 'parameter', def: 'An input value a function receives when called.' }, { term: 'return', def: 'Hands the result back to the caller and ends the function.' }],
    },
  },
  {
    day: 8,
    title: 'Parameters and return values',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Today we sharpen how values go into a function and come back out. This is the layer where code starts to feel comfortable.' },
      { k: 'code', lang: 'py', src: 'def drive(cm, speed=10):\n    print(f"{cm} cm at {speed} cm/s")\n\ndrive(30)              # 30 cm at 10 cm/s\ndrive(30, 25)          # 30 cm at 25 cm/s\ndrive(cm=30, speed=5)', explain: '`speed=10` is a **default**: it applies when you do not pass one. The `cm=30` form names the parameter, so order stops mattering.' },
      { k: 'callout', tone: 'warn', md: 'Parameters with defaults always come last. `def f(a=1, b)` is a syntax error.' },
      { k: 'code', lang: 'py', src: 'def bounds(values):\n    return min(values), max(values)\n\nlow, high = bounds([4, 9, 2])\nprint(low, high)     # 2 9', explain: 'You can return several values separated by commas, and unpack them the same way at the call site.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write an `average(numbers)` function returning the average of a list. For an empty list it should give 0 rather than raising. Try it with `[2, 4, 6]` and with `[]`.',
      starter: 'def average(numbers):\n    pass\n\nprint(average([2, 4, 6]))\nprint(average([]))\n',
      checks: [{ k: 'output', contains: '4', label: 'The average of [2,4,6] is 4' }, { k: 'output', contains: '0', label: 'An empty list averages to 0' }],
      hints: ['Handle the special case first: `if len(numbers) == 0: return 0`.', 'Then: `return sum(numbers) / len(numbers)`.'],
    },
    quiz: [
      { k: 'single', q: 'What does `b=5` mean in the header `def f(a, b=5):`?', opts: ['b is always 5', 'b defaults to 5 when you do not pass it', 'b can be at most 5'], answer: 1, why: 'It is a default. If the caller supplies a value it wins; otherwise 5 applies.' },
      { k: 'output', q: 'What does this print?', code: 'def f(a, b=2):\n    return a * b\n\nprint(f(3), f(3, 4))', lang: 'py', opts: ['6 12', '6 6', '3 12'], answer: 0, why: 'The first call takes the default (2), so 3*2=6. The second gets 4, so 3*4=12.' },
      { k: 'single', q: 'Why is a named call like `drive(speed=5, cm=30)` useful?', opts: ['It is faster', 'Order stops mattering and the call explains itself', 'It uses less memory'], answer: 1, why: 'Named arguments document themselves and free you from remembering the order. With many parameters that is a real gain.' },
      { k: 'single', q: 'What does `return a, b` give back?', opts: ['Only a', 'Two values you can unpack', 'An error'], answer: 1, why: 'You can return several values. At the call site, `x, y = f()` splits them apart.' },
    ],
    note: {
      summary: ['A default (`b=5`) applies when the caller passes nothing.', 'Parameters with defaults go at the end of the list.', 'Named arguments (`f(b=2, a=1)`) ignore order and read better.', 'A function can return several values separated by commas.', 'Catch the special cases (empty list, zero) at the top of the function.'],
      terms: [{ term: 'default value', def: 'A value a parameter takes when no argument is supplied.' }, { term: 'named argument', def: 'An argument passed by name, independent of order.' }, { term: 'unpacking', def: 'Splitting several returned values into separate variables.' }],
    },
  },
  {
    day: 9,
    title: 'Scope and side effects',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Scope** says where a variable is visible. A variable created inside a function does not exist outside it.' },
      { k: 'code', lang: 'py', src: 'def f():\n    inner = 10\n    print(inner)     # 10\n\nf()\nprint(inner)         # NameError!', explain: '`inner` is the function\'s **local** variable. Once the function returns, it is gone.' },
      { k: 'callout', tone: 'key', md: 'This is protection, not restriction. If every variable were visible everywhere, in a long program you would never know who overwrote what.' },
      { k: 'code', lang: 'py', src: 'def add_one(items):\n    items.append(99)     # CHANGES the caller\'s list\n\ndata = [1, 2]\nadd_one(data)\nprint(data)              # [1, 2, 99]', explain: 'Lists and dictionaries arrive **by reference**: what you change inside is visible outside. That is a side effect.' },
      { k: 'callout', tone: 'tip', md: 'If a function modifies what it was given, say so in its name or its documentation. A surprise side effect is the hardest kind of bug to find.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `doubled(items)` function that returns a **new** list with every value doubled, leaving the original untouched. Check that the original really is unchanged.',
      starter: 'def doubled(items):\n    pass\n\noriginal = [1, 2, 3]\nprint(doubled(original))\nprint(original)\n',
      checks: [{ k: 'output', contains: '[2, 4, 6]', label: 'The new list is doubled' }, { k: 'output', contains: '[1, 2, 3]', label: 'The original is unchanged' }],
      hints: ['Create an empty list inside the function and collect into it.', '`out = []`, then `for x in items: out.append(x * 2)`, then `return out`.'],
    },
    quiz: [
      { k: 'single', q: 'What happens if you reference a variable created inside a function from outside?', opts: ['You get its value', 'You get a NameError', 'You get None'], answer: 1, why: 'A local variable disappears when the function returns. From outside it does not exist, hence `NameError`.' },
      { k: 'output', q: 'What does this print?', code: 'def f(lst):\n    lst.append(9)\n\na = [1]\nf(a)\nprint(a)', lang: 'py', opts: ['[1]', '[1, 9]', 'It raises'], answer: 1, why: 'The list arrives by reference, so `append` modifies the caller\'s list. That is a side effect.' },
      { k: 'single', q: 'Why is it useful that local variables do not leak?', opts: ['The program runs faster', 'They cannot accidentally overwrite other variables', 'Less typing'], answer: 1, why: 'Isolation is what lets you understand one function without holding the whole program in your head.' },
      { k: 'single', q: 'What is a side effect?', opts: ['When a function raises', 'When a function changes something outside itself', 'When a function is slow'], answer: 1, why: 'A side effect is any change beyond the returned value: modifying an input, writing a file, changing a global.' },
    ],
    note: {
      summary: ['A variable created inside a function is local: it does not exist outside.', 'Locality is protection, not restriction — without it, large programs would be impossible.', 'Lists and dictionaries arrive by reference, so a function can change the caller\'s copy.', 'A side effect is any change beyond the returned value.', 'If a function modifies, make that clear in its name or description.'],
      terms: [{ term: 'scope', def: 'The region in which a variable name exists.' }, { term: 'local variable', def: 'A variable created inside a function, gone once it returns.' }, { term: 'side effect', def: 'A change a function causes beyond its returned value.' }],
    },
  },
  {
    day: 10,
    title: 'Working with text',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'Text (`str`) is a sequence of characters, and it behaves much like a list: it has a length, it can be indexed, and it can be sliced.' },
      { k: 'code', lang: 'py', src: 's = "Rover Mk-II"\n\nprint(len(s))        # 11\nprint(s[0])          # R\nprint(s[0:5])        # Rover     — slicing\nprint(s.upper())     # ROVER MK-II\nprint(s.lower())' },
      { k: 'code', lang: 'py', src: 'line = "  12, 8, 30  "\n\nprint(line.strip())              # trims the spaces\nprint(line.strip().split(","))   # [\'12\', \' 8\', \' 30\']\nprint("-".join(["a", "b"]))      # a-b\nprint("30" in line)              # True', explain: '`split` breaks apart, `join` puts together. Those two are the backbone of text processing.' },
      { k: 'callout', tone: 'warn', md: 'Text is **immutable**. `s.upper()` does not change `s`; it returns a new string. If you want the result, you have to keep it: `s = s.upper()`.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Given `line = "12,8,30,5"`, turn it into a list of numbers and print their sum.',
      starter: 'line = "12,8,30,5"\n',
      checks: [{ k: 'output', contains: '55', label: 'The sum is 55' }],
      hints: ['Split it: `parts = line.split(",")` — these are still text.', 'Convert with `int(p)`.', 'Collect in a loop, or: `sum(int(p) for p in line.split(","))`.'],
    },
    quiz: [
      { k: 'output', q: 'What does this print?', code: 's = "robot"\nprint(s[1:4])', lang: 'py', opts: ['rob', 'obo', 'obot'], answer: 1, why: 'The slice runs from index 1 up to but not including 4: o, b, o.' },
      { k: 'single', q: 'What does `"a,b,c".split(",")` do?', opts: ['Joins a list', 'Gives a three-item list: [a, b, c]', 'Replaces the commas'], answer: 1, why: '`split` breaks the text at the separator and returns a list.' },
      { k: 'output', q: 'What does this print?', code: 's = "abc"\ns.upper()\nprint(s)', lang: 'py', opts: ['ABC', 'abc', 'It raises'], answer: 1, why: 'Text is immutable: `upper()` returns a new string, which nobody kept here. `s` is unchanged.' },
      { k: 'single', q: 'What is `strip()` for?', opts: ['Trimming whitespace from both ends', 'Lowercasing', 'Splitting'], answer: 0, why: '`strip` clears spaces and newlines from both ends. With lines read from a file you almost always need it.' },
    ],
    note: {
      summary: ['Text is a sequence of characters: it has a length, an index and slices (`s[1:4]`).', 'A slice excludes its upper bound.', 'Text is immutable: its methods return new strings.', '`split` breaks apart, `join` puts together, `strip` trims the ends.', 'The `in` operator tells you whether a fragment appears in the text.'],
      terms: [{ term: 'slicing', def: 'Taking a substring by index bounds, e.g. `s[1:4]`.' }, { term: 'split', def: 'Breaking text into a list at a separator.' }, { term: 'immutable', def: 'A value that cannot be changed in place, only used to build a new one.' }],
    },
  },
  {
    day: 11,
    title: 'Formatting and input',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'The **f-string** is the most comfortable way to put values into text. An `f` before the quote, and any expression inside the braces.' },
      { k: 'code', lang: 'py', src: 'name = "Rover"\nbattery = 78.456\n\nprint(f"{name}: {battery} %")\nprint(f"{name}: {battery:.1f} %")     # one decimal\nprint(f"{battery:6.2f}")              # 6 wide, 2 decimals', explain: 'The part after the colon is the format. `.1f` rounds to one decimal — standard for measured values.' },
      { k: 'code', lang: 'py', src: 'number = int("42")\nreal = float("3.14")\ntext = str(42)\n\nprint(number + 1, real * 2, text + "!")', explain: 'Conversion is explicit. Anything a user types arrives as text — you can only compute with it after converting.' },
      { k: 'callout', tone: 'warn', md: '`int("apple")` raises `ValueError`. Real input needs guarding against this — on day 19 we learn how.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Given `dist = 12.3456` and `name = "Rover"`, print exactly this shape: `Rover: 12.35 cm` — two decimal places.',
      starter: 'dist = 12.3456\nname = "Rover"\n',
      checks: [{ k: 'output', contains: '12.35', label: 'Rounded to two decimals' }, { k: 'output', contains: 'Rover', label: 'The name appears' }],
      hints: ['f-string: `print(f"...")`.', 'Two decimals: `{dist:.2f}`.', 'Full answer: `print(f"{name}: {dist:.2f} cm")`.'],
    },
    quiz: [
      { k: 'output', q: 'What does this print?', code: 'x = 3.14159\nprint(f"{x:.2f}")', lang: 'py', opts: ['3.14159', '3.14', '3'], answer: 1, why: '`.2f` formats to two decimals. The value itself is unchanged; only the display is.' },
      { k: 'single', q: 'What does `int("7")` give?', opts: ['The text "7"', 'The whole number 7', 'An error'], answer: 1, why: '`int` turns text into a whole number when the text really holds one.' },
      { k: 'single', q: 'What happens on `int("apple")`?', opts: ['It gives 0', 'It raises ValueError', 'It gives None'], answer: 1, why: 'It cannot be converted, so `ValueError`. That needs handling when the input comes from a person.' },
      { k: 'single', q: 'What goes before an f-string?', opts: ['An f before the quote', 'A % sign', 'Nothing'], answer: 0, why: 'The `f` prefix is what makes the braces evaluate. Without it, `{x}` appears literally.' },
    ],
    note: {
      summary: ['An f-string, `f"{value}"`, drops values into text.', 'Format after the colon: `{x:.2f}` two decimals, `{x:6.2f}` six wide.', 'Conversion: `int()`, `float()`, `str()`.', 'Anything typed by a person arrives as text — convert before computing.', 'Bad input raises `ValueError`, which has to be handled.'],
      terms: [{ term: 'f-string', def: 'A string form that evaluates expressions written in braces.' }, { term: 'format spec', def: 'The part after the colon that controls the display.' }, { term: 'ValueError', def: 'The error raised when a value cannot be converted to the requested type.' }],
    },
  },
  {
    day: 12,
    title: 'Text processing in practice',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A real task: the robot writes a log and you want the useful part out of it. This is every programmer\'s daily work.' },
      { k: 'code', lang: 'py', src: 'log = """12:00 dist 30\n12:01 dist 18\n12:02 fault motor\n12:03 dist 7"""\n\nfor line in log.split("\\n"):\n    parts = line.split()\n    if parts[1] == "dist":\n        print(parts[0], int(parts[2]))', explain: '`split()` with no argument breaks at any run of whitespace. `split("\\n")` breaks into lines.' },
      { k: 'callout', tone: 'tip', md: 'Before processing, look at one raw line: `print(repr(line))`. `repr` shows the hidden spaces and newlines that will trip your parsing up.' },
      { k: 'code', lang: 'py', src: 'line = "temperature: 23.5 C"\n\nif line.startswith("temperature"):\n    value = float(line.split(":")[1].strip().split()[0])\n    print(value + 1)', explain: 'Several steps in a row: cut at the colon, trim, take the first piece, convert. Split it across lines if it gets hard to read.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Given the `log` text, count how many "dist" entries it holds and print the number.',
      starter: 'log = "12:00 dist 30\\n12:01 dist 18\\n12:02 fault motor\\n12:03 dist 7"\n',
      checks: [{ k: 'output', contains: '3', label: 'There are three dist entries' }],
      hints: ['Split into lines: `log.split("\\n")`.', 'Counter: `count = 0`, then `count = count + 1` on a match.', 'Test with `if " dist " in line:` or `line.split()[1] == "dist"`.'],
    },
    quiz: [
      { k: 'single', q: 'What does `split()` with no argument do?', opts: ['Splits every character', 'Splits at whitespace, treating a run as one', 'Raises'], answer: 1, why: 'With no argument, `split` breaks at whitespace and collapses consecutive spaces into one separator.' },
      { k: 'single', q: 'What is `repr(line)` for when debugging?', opts: ['It runs faster', 'It shows hidden spaces and newlines', 'It converts to a number'], answer: 1, why: 'Plain `print` hides invisible characters. `repr` shows them, and that is usually where the bug is.' },
      { k: 'output', q: 'What does this print?', code: 's = "a b  c"\nprint(len(s.split()))', lang: 'py', opts: ['3', '4', '6'], answer: 0, why: '`split()` treats the run of spaces as one separator, so it gives three pieces: a, b, c.' },
      { k: 'single', q: 'Why break complicated parsing across several lines?', opts: ['It runs faster', 'It shows you which step went wrong', 'It uses less memory'], answer: 1, why: 'In one long line you cannot tell which step failed. Split up, you can print every intermediate result.' },
    ],
    note: {
      summary: ['Split into lines with `text.split("\\n")`, into words with `line.split()`.', '`split()` with no argument collapses runs of whitespace.', '`repr()` reveals hidden characters — the first move when parsing misbehaves.', '`startswith` and `in` are quick filters.', 'Break multi-step parsing across lines so you can see where it goes wrong.'],
      terms: [{ term: 'parsing', def: 'Extracting structured data from raw text.' }, { term: 'repr', def: 'The faithful, quoted rendering of a value, hidden characters included.' }, { term: 'startswith', def: 'Tells you whether text begins with a given fragment.' }],
    },
  },
  {
    day: 13,
    title: 'Reading and writing files',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'So far everything vanished when the program ended. A **file** is the first place data outlives the run.' },
      { k: 'code', lang: 'py', src: 'with open("log.txt", "w") as f:\n    f.write("12:00 dist 30\\n")\n    f.write("12:01 dist 18\\n")\n\nwith open("log.txt", "r") as f:\n    content = f.read()\n\nprint(content)', explain: '`with` makes sure the file is closed, even if something fails partway. Always open files this way.' },
      { k: 'callout', tone: 'warn', md: 'Mode `"w"` **erases** an existing file. To add to it you need `"a"` (append). Everyone learns this difference — usually once, unpleasantly.' },
      { k: 'code', lang: 'py', src: 'with open("log.txt") as f:\n    for line in f:\n        print(line.strip())', explain: 'You can also walk a file line by line. On a big file that beats loading the whole thing into memory.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write three lines of numbers into a `readings.txt` file, then read it back and print how many lines it holds.',
      starter: '',
      checks: [{ k: 'output', contains: '3', label: 'The file has three lines' }],
      hints: ['Writing: `with open("readings.txt", "w") as f:` then `f.write("12\\n")`.', 'Reading: `with open("readings.txt") as f: lines = f.readlines()`.', 'Print: `print(len(lines))`.'],
    },
    quiz: [
      { k: 'single', q: 'What does mode `"w"` do to an existing file?', opts: ['Appends to the end', 'Erases its contents', 'Raises'], answer: 1, why: '`"w"` starts the file from scratch. To add, use `"a"`.' },
      { k: 'single', q: 'Why use the `with open(...)` form?', opts: ['It is faster', 'It closes the file reliably, even on an error', 'Less typing'], answer: 1, why: 'At the end of the `with` block the file is closed whatever happens. Without it, an exception can leave it open and data stuck in the buffer.' },
      { k: 'single', q: 'What does `f.read()` give?', opts: ['The whole file as one string', 'A list of lines', 'The first line'], answer: 0, why: '`read()` loads everything into one string. For the list of lines, use `readlines()`.' },
      { k: 'single', q: 'Why walk a big file line by line?', opts: ['You never hold the whole file in memory', 'It is more accurate', 'No difference'], answer: 0, why: '`for line in f:` keeps one line in memory at a time. On a multi-gigabyte log that is the difference between working and crashing.' },
    ],
    note: {
      summary: ['A file is the first place data outlives the program run.', 'Always `with open(...) as f:` — it closes reliably at the end of the block.', 'Modes: `"r"` read, `"w"` write (erases!), `"a"` append.', '`read()` gives the whole file, `readlines()` the list of lines.', 'Walk a large file with `for line in f:` rather than loading it all.'],
      terms: [{ term: 'with block', def: 'A structure that releases a resource automatically at the end.' }, { term: 'file mode', def: "`open`'s second argument: read, write or append." }, { term: 'readlines', def: "Returns the file's lines as a list." }],
    },
  },
  {
    day: 14,
    title: 'JSON and structured data',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A plain text file is fine for a log and poor for structure. **JSON** is a text format that keeps lists and dictionaries intact.' },
      { k: 'code', lang: 'py', src: 'import json\n\nstate = {"name": "Rover", "battery": 78, "position": [12, 4]}\n\ntext = json.dumps(state)     # dict → text\nback = json.loads(text)      # text → dict\n\nprint(text)\nprint(back["position"][0])   # 12', explain: '`dumps` is "dump string" — turns it into text. `loads` goes back. The structure survives.' },
      { k: 'code', lang: 'py', src: 'with open("state.json", "w") as f:\n    json.dump(state, f, indent=2)\n\nwith open("state.json") as f:\n    loaded = json.load(f)', explain: 'The versions without the `s` work straight with a file. `indent=2` makes the file readable.' },
      { k: 'callout', tone: 'key', md: 'FORGE saves your progress exactly this way: one JSON file on your machine. When you export your data in Settings, this is the file that comes out.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Build a dictionary about your robot, turn it into JSON text, read it back, and print one value from what came back.',
      starter: 'import json\n\nrobot = {"name": "Rover", "battery": 80}\n',
      checks: [{ k: 'output', contains: '80', label: 'The reloaded battery value appears' }],
      hints: ['`text = json.dumps(robot)`', '`back = json.loads(text)`', '`print(back["battery"])`'],
    },
    quiz: [
      { k: 'single', q: 'What does `json.dumps(d)` do?', opts: ['Writes the dictionary to a file', 'Turns the dictionary into JSON text', 'Reads a file'], answer: 1, why: '`dumps` produces text. Writing to a file is `dump`, without the `s`.' },
      { k: 'single', q: 'What does JSON give you over a plain text file?', opts: ['Smaller files', 'It keeps the structure: lists, dictionaries, types', 'Faster reading'], answer: 1, why: 'From plain text you have to reconstruct the structure yourself. JSON does that for you.' },
      { k: 'output', q: 'What does this print?', code: 'import json\nd = json.loads(\'{"a": [1, 2]}\')\nprint(d["a"][1])', lang: 'py', opts: ['1', '2', '[1, 2]'], answer: 1, why: '`loads` restores the dictionary with the nested list, so `["a"][1]` is the second item: 2.' },
      { k: 'single', q: 'What is the difference between `dump` and `dumps`?', opts: ['dump writes to a file, dumps returns text', 'Nothing', 'dumps is faster'], answer: 0, why: 'The `s` stands for "string". `dumps`/`loads` work with text, `dump`/`load` with files.' },
    ],
    note: {
      summary: ['JSON is a text format that preserves lists, dictionaries and types.', '`json.dumps` dict to text, `json.loads` text to dict.', 'Without the `s`, `json.dump`/`json.load` work straight with files.', '`indent=2` makes the saved file readable.', 'It is the most widely used format for programs to exchange data.'],
      terms: [{ term: 'JSON', def: 'A text data format able to describe structure.' }, { term: 'serialisation', def: 'Turning in-memory data into something storable or sendable.' }, { term: 'dumps/loads', def: 'Converting between a dictionary and JSON text, both ways.' }],
    },
  },
  {
    day: 15,
    title: 'Saving and reloading data',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Now we put it together: a program that remembers what happened, even after you close it.' },
      { k: 'code', lang: 'py', src: 'import json, os\n\nFILE = "state.json"\n\ndef load():\n    if not os.path.exists(FILE):\n        return {"runs": 0}\n    with open(FILE) as f:\n        return json.load(f)\n\ndef save(data):\n    with open(FILE, "w") as f:\n        json.dump(data, f, indent=2)', explain: '`load` treats a missing file not as an error but as "no save yet". That is the first run.' },
      { k: 'code', lang: 'py', src: 'state = load()\nstate["runs"] = state["runs"] + 1\nsave(state)\n\nprint("This is run number", state["runs"])' },
      { k: 'callout', tone: 'key', md: 'Three rules for saving: (1) a missing file is not an error, (2) a corrupt file must not take the whole program down, (3) do not overwrite the old data until the new is complete. FORGE does exactly this: it writes a temporary file and then renames it.' },
    ],
    lab: {
      lab: 'code', lang: 'py',
      brief: 'Write a `load()` function that returns `{"runs": 0}` when the file does not exist. Call it, increment the counter and print it.',
      starter: 'import json, os\n\ndef load():\n    pass\n\n',
      checks: [{ k: 'output', contains: '1', label: 'After the first run the counter is 1' }],
      hints: ['`if not os.path.exists("a.json"): return {"runs": 0}`', 'Increment: `s["runs"] += 1`.', 'Print: `print(s["runs"])`.'],
    },
    quiz: [
      { k: 'single', q: 'Why should a missing save file not be an error?', opts: ['Because error handling is slow', 'Because on the first run there naturally is none', 'Because Python does not support it'], answer: 1, why: 'On first launch there is no save. If that stops the program, it can never start at all.' },
      { k: 'single', q: 'Why write to a temporary file and then rename?', opts: ['It is faster', 'An interrupted write cannot truncate the old save', 'The file is smaller'], answer: 1, why: 'If the power goes during the write, the old file is untouched. Renaming is an atomic operation in the filesystem.' },
      { k: 'single', q: 'What does `os.path.exists("a.json")` do?', opts: ['Creates the file', 'Tells you whether it exists', 'Opens it'], answer: 1, why: 'It only checks whether the path is there. It creates nothing and opens nothing.' },
      { k: 'order', q: 'In what order does a safe save happen?', items: ['Rename to the final name', 'Write the temporary file', 'Prepare the data'], correct: [2, 1, 0], why: 'Data first, then the temp file, and the rename last — so the old save stays intact throughout.' },
    ],
    note: {
      summary: ['Saving is the pair of loading and writing.', 'A missing file is not an error but "first run" — return a default.', 'A corrupt file must not take the whole program down.', 'Safe writing: temporary file, then rename.', '`os.path.exists` only checks; it creates nothing.'],
      terms: [{ term: 'persistence', def: 'Keeping data beyond the run of the program.' }, { term: 'atomic write', def: 'A write pattern where the old data stays intact until the new is complete.' }, { term: 'default state', def: 'The value a program starts from when there is no save yet.' }],
    },
  },
];
