import type { Day } from '../../types';

/** C++ track, days 17-23. */
export const cppEnD: Day[] = [
  {
    day: 17,
    title: 'const correctness',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**const correctness** means marking everything that does not change as `const`. The compiler checks it, and the intent of the code becomes readable.' },
      { k: 'code', lang: 'cpp', src: 'class Rover {\n    int battery_ = 100;\n    std::string name_;\npublic:\n    int battery() const { return battery_; }     // does not modify\n    const std::string& name() const { return name_; }\n\n    void drain(int amount) { battery_ -= amount; }   // modifies\n};\n\nvoid print(const Rover& r) {\n    std::cout << r.battery();     // only const methods are callable\n    // r.drain(5);                // does not compile -- and that is good\n}', explain: 'The `const` after a method promises the object will not change. Through a `const Rover&` only such methods can be called.' },
      { k: 'callout', tone: 'key', md: 'The rule: **mark every non-modifying method `const`**, and pass every unmodified parameter as a `const` reference. Retrofitting it is painful, because `const` propagates along the whole call chain.' },
      { k: 'text', md: 'A `const` reference is also how you avoid copying:\n\n```\nvoid f(std::string s);          // copies\nvoid f(const std::string& s);   // no copy, no modification\n```\n\nFor large objects that is a real difference. For small types (`int`, `double`) passing by value is faster.' },
      { k: 'callout', tone: 'warn', md: 'The `mutable` keyword grants an exception: such a field can be written from a `const` method. It is legitimate for caches and mutexes, but anywhere else it usually means the `const` promise is not true.' },
      { k: 'callout', tone: 'tip', md: '`const` is not only documentation: it is information for the compiler. It knows a `const` object will not change between calls, and allows itself more optimisation.' },
    ],
    quiz: [
      { k: 'single', q: 'What does `const` after a method mean?', opts: ['It returns nothing', 'It does not modify the object', 'It cannot be called'], answer: 1, why: 'Through a `const` reference only such methods can be called.' },
      { k: 'single', q: 'Why pass a large object by `const` reference?', opts: ['It is shorter', 'It neither copies nor modifies', 'It compiles faster'], answer: 1, why: 'For small types (`int`, `double`) passing by value is faster though.' },
      { k: 'single', q: 'What does `mutable` allow?', opts: ['The field can be written from a `const` method', 'The field cannot change', 'The method becomes virtual'], answer: 0, why: 'Legitimate for caches and mutexes. Elsewhere it usually signals a false `const` promise.' },
      { k: 'single', q: 'Why is const correctness hard to retrofit?', opts: ['A lot of typing', 'Because `const` propagates along the whole call chain', 'Because it slows the code'], answer: 1, why: 'A `const` method can only call `const` methods, so the change cascades.' },
      { k: 'single', q: 'What does the compiler gain from `const`?', opts: ['Nothing', 'It knows the object will not change, so it can optimise more', 'A smaller binary'], answer: 1, why: '`const` is not only documentation: it is real information for the optimiser.' },
    ],
    note: {
      summary: ['const correctness: mark everything that does not change as `const`.', '`const` after a method promises not to modify the object.', 'Through a `const` reference only `const` methods are callable.', 'Pass large objects as `const&`, small ones by value.', '`mutable` grants an exception — legitimate for caches and mutexes.', 'Retrofitting is hard because `const` propagates.'],
      terms: [{ term: 'const method', def: 'A method that does not modify the object.' }, { term: 'const correctness', def: 'Consistent use of `const` across an interface.' }, { term: 'mutable', def: 'A field writable even from a `const` method.' }],
    },
  },
  {
    day: 18,
    title: 'Exception handling',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'C++ exception handling rests on RAII: as an exception travels upward, **stack unwinding** runs the destructor of every local object. That is what makes it safe.' },
      { k: 'code', lang: 'cpp', src: '#include <stdexcept>\n\nint battery_level(const Rover& r) {\n    if (!r.powered())\n        throw std::runtime_error("The rover is switched off");\n    return r.battery();\n}\n\ntry {\n    int level = battery_level(r);\n} catch (const std::runtime_error& e) {\n    std::cerr << e.what() << "\\n";\n} catch (const std::exception& e) {\n    std::cerr << "Other error: " << e.what() << "\\n";\n}', explain: 'Always catch by **const reference** (`const std::exception&`), never by value: by value you would slice off the derived type and lose the information.' },
      { k: 'callout', tone: 'key', md: '`catch` clauses are tried **in order**, so the **narrower type goes first**. If the `std::exception` clause comes first it swallows everything and the specific clauses never run.' },
      { k: 'text', md: 'The standard exception hierarchy:\n\n```\nstd::exception\n├── std::logic_error\n│   ├── std::invalid_argument\n│   └── std::out_of_range\n└── std::runtime_error\n    ├── std::overflow_error\n    └── std::system_error\n```\n\nDerive your own from `std::runtime_error` when nothing fits better.' },
      { k: 'callout', tone: 'warn', md: 'A **destructor must never throw**. If a destructor throws while another exception is being handled, the program stops immediately with `std::terminate`. Since C++11 destructors are `noexcept` by default — throw anyway and the program dies.' },
      { k: 'text', md: 'The `noexcept` keyword is a promise: this function does not throw. The compiler exploits it (for instance when moving a `std::vector`), but if you do throw, `std::terminate` follows. Write it only when you are sure.' },
    ],
    quiz: [
      { k: 'single', q: 'What happens to local objects as an exception travels upward?', opts: ['They leak', 'Stack unwinding runs their destructors', 'They stay alive'], answer: 1, why: 'That is the basis of RAII and exception safety: resources are released anyway.' },
      { k: 'single', q: 'How should you catch an exception?', opts: ['By value', 'By `const` reference', 'By pointer'], answer: 1, why: 'By value you would slice off the derived type and lose information.' },
      { k: 'single', q: 'In what order should `catch` clauses appear?', opts: ['Narrower type first', 'Wider type first', 'It does not matter'], answer: 0, why: 'A `std::exception` clause placed first would swallow all the others.' },
      { k: 'single', q: 'What happens if a destructor throws?', opts: ['Nothing', 'The program stops with `std::terminate`', 'It can be caught'], answer: 1, why: 'Since C++11 destructors are `noexcept` by default. Throwing during exception handling kills the program.' },
      { k: 'single', q: 'What does `noexcept` mean?', opts: ['It catches no exceptions', 'A promise that this function does not throw', 'It swallows exceptions'], answer: 1, why: 'The compiler relies on it, but throwing anyway leads to `std::terminate`.' },
    ],
    note: {
      summary: ['Stack unwinding runs local destructors — that is the payoff of RAII.', 'Always catch by `const` reference.', 'Put the narrower `catch` type first.', 'Hierarchy: `std::exception` → `logic_error` / `runtime_error`.', 'A destructor must never throw: it means `std::terminate`.', '`noexcept` is a promise, not a protection.'],
      terms: [{ term: 'stack unwinding', def: 'Running local destructors as an exception propagates.' }, { term: 'slicing', def: 'Losing the derived part when copying by value.' }, { term: 'noexcept', def: 'A promise that a function will not throw.' }],
    },
  },
  {
    day: 19,
    title: 'Namespaces',
    minutes: 20,
    lesson: [
      { k: 'text', md: 'A **namespace** is the C++ answer to name clashes. Two libraries may each contain a `Logger` class as long as they live in different namespaces.' },
      { k: 'code', lang: 'cpp', src: 'namespace forge {\nnamespace robot {\n\nclass Rover { /* ... */ };\n\n}  // namespace robot\n}  // namespace forge\n\n// Shorter since C++17:\nnamespace forge::robot {\nclass Rover { /* ... */ };\n}\n\nforge::robot::Rover r;\nnamespace fr = forge::robot;    // alias\nfr::Rover r2;', explain: 'A namespace alias (`namespace fr = ...`) is local and lives only in the scope where you wrote it. It is the good middle ground between the full name and a `using`.' },
      { k: 'callout', tone: 'warn', md: '`using namespace std;` **never in a header**. It spills into every file that includes the header and causes clashes the author of that file cannot even see. Inside a source file, within a function, it is acceptable.' },
      { k: 'text', md: 'An **anonymous namespace** is the C++ equivalent of C file-scope `static`:\n\n```cpp\nnamespace {\n    int internal_counter = 0;      // visible only in this file\n    void helper() { }\n}\n```\n\nThis is the modern C++ way to keep something inside one translation unit.' },
      { k: 'callout', tone: 'key', md: 'Because of **ADL** (argument-dependent lookup) the compiler also searches the namespace of the arguments. That is why `std::cout << v` works without qualifying the operator — it is found in the `std` namespace.' },
      { k: 'text', md: 'The usual convention: give a library one short, unique root namespace (`forge`) and sub-namespaces by feature inside it. A sub-namespace named `detail` traditionally marks the internal, non-public part.' },
    ],
    quiz: [
      { k: 'single', q: 'What is a namespace for?', opts: ['Speed', 'Preventing name clashes', 'Saving memory'], answer: 1, why: 'Two libraries can each have a class of the same name in different namespaces.' },
      { k: 'single', q: 'Where is `using namespace std;` forbidden?', opts: ['In a source file', 'In a header file', 'Inside a function'], answer: 1, why: 'It spills into every including file and causes invisible clashes.' },
      { k: 'single', q: 'What is the C equivalent of an anonymous namespace?', opts: ['`extern`', 'File-scope `static`', '`const`'], answer: 1, why: 'Both limit visibility to a single translation unit.' },
      { k: 'single', q: 'What does ADL mean?', opts: ['Automatic deletion', 'The compiler also searches the namespace of the arguments', 'A library'], answer: 1, why: 'That is why `std::cout << v` works without qualification.' },
      { k: 'single', q: 'What does a `detail` sub-namespace traditionally mark?', opts: ['Documentation', 'The internal, non-public part', 'Tests'], answer: 1, why: 'A signal to the reader: do not depend on this, it can change at any time.' },
    ],
    note: {
      summary: ['A namespace prevents name clashes.', 'Since C++17 you can write `namespace a::b { }`.', 'Namespace alias: `namespace fr = forge::robot;`.', 'Never put `using namespace std;` in a header.', 'An anonymous namespace is the equivalent of C file-scope `static`.', 'ADL: the compiler also searches the argument namespaces.', 'A `detail` sub-namespace marks internal code.'],
      terms: [{ term: 'namespace', def: 'A grouping of names to avoid clashes.' }, { term: 'anonymous namespace', def: 'Visibility limited to one translation unit.' }, { term: 'ADL', def: 'Argument-dependent lookup in the argument namespaces.' }],
    },
  },
  {
    day: 20,
    title: 'Splitting headers and sources',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'C++ uses the same header and source split as C, but templates and inline functions add more exceptions.' },
      { k: 'callout', tone: 'key', md: 'The base rule: **the `.hpp` is the interface**, the **`.cpp` is the implementation**. What does not need to be visible from outside should not be in the header — every line there adds to the compile time of every including file.' },
      { k: 'code', lang: 'cpp', src: '// rover.hpp\n#pragma once                     // simpler than an include guard\n#include <string>\n\nclass Map;                       // forward declaration: enough for a pointer\n\nclass Rover {\n    std::string name_;\n    Map* map_ = nullptr;\npublic:\n    explicit Rover(std::string name);\n    void step(int cm);\n};', explain: 'A **forward declaration** (`class Map;`) is enough when you only store a pointer or a reference. You then need not include `map.hpp`, and the compile dependency does not spread.' },
      { k: 'callout', tone: 'warn', md: '**Templates cannot be split**: the compiler needs the whole body to instantiate them. That is why template code stays in the header — and why template-heavy projects compile slowly.' },
      { k: 'text', md: 'What does belong in a header?\n\n- **inline functions** — short getters, one-line operations\n- **templates** — necessarily\n- **constexpr** functions and constants\n- `class` and `struct` definitions' },
      { k: 'callout', tone: 'tip', md: '`#pragma once` works on every mainstream compiler today and is shorter than a three-line include guard. Choose the `#ifndef` form only when you must support a very old or exotic compiler.' },
      { k: 'text', md: 'The **PIMPL** idiom is the strongest tool for cutting compile dependencies: move the private fields into a forward-declared `Impl` class and leave only a `std::unique_ptr<Impl>` in the header. A change in the implementation then does not rebuild half the project.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the base rule for headers and sources?', opts: ['Everything in the header', 'The `.hpp` is the interface, the `.cpp` the implementation', 'Everything in the source'], answer: 1, why: 'Every line in a header adds to the compile time of every including file.' },
      { k: 'single', q: 'When is a forward declaration enough?', opts: ['Always', 'When you only store a pointer or a reference', 'Never'], answer: 1, why: 'For a value member the compiler must know the size, so it needs the full definition.' },
      { k: 'single', q: 'Why does template code stay in the header?', opts: ['Tradition', 'Because the compiler needs the whole body to instantiate it', 'Because it is faster'], answer: 1, why: 'That is why template-heavy projects compile slowly.' },
      { k: 'single', q: 'What is the advantage of `#pragma once`?', opts: ['Faster execution', 'Shorter than a three-line include guard and works on every mainstream compiler', 'A smaller binary'], answer: 1, why: 'Only a very old or exotic compiler needs the `#ifndef` form.' },
      { k: 'single', q: 'What does the PIMPL idiom solve?', opts: ['It speeds up execution', 'It cuts compile dependencies so an implementation change does not rebuild everything', 'It reduces memory'], answer: 1, why: 'Private fields move into a forward-declared `Impl` class, leaving only a pointer in the header.' },
    ],
    note: {
      summary: ['`.hpp` is the interface, `.cpp` the implementation.', 'A forward declaration suffices for pointers and references.', 'Templates necessarily stay in the header.', 'Headers also hold inline, constexpr and class definitions.', '`#pragma once` replaces the include guard.', 'PIMPL hides the private implementation to stop dependency spread.'],
      terms: [{ term: 'forward declaration', def: 'Announcing a type without its full definition.' }, { term: '#pragma once', def: 'A compiler directive to include a header only once.' }, { term: 'PIMPL', def: 'An idiom hiding the private implementation in a separate class.' }],
    },
  },
  {
    day: 21,
    title: 'CMake basics',
    minutes: 24,
    lesson: [
      { k: 'text', md: '**CMake** does not compile: it *generates*. From one description it produces a Makefile, a Ninja file or a Visual Studio project — which is how the same project builds on every platform.' },
      { k: 'code', lang: 'cpp', src: '/* CMakeLists.txt\ncmake_minimum_required(VERSION 3.20)\nproject(robot VERSION 1.0 LANGUAGES CXX)\n\nset(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\nadd_library(robotlib\n    src/rover.cpp\n    src/motor.cpp\n)\ntarget_include_directories(robotlib PUBLIC include)\n\nadd_executable(robot src/main.cpp)\ntarget_link_libraries(robot PRIVATE robotlib)\n*/', explain: 'Modern CMake is **target centric**: every setting belongs to a target (`target_...`), not to global variables. That is what makes dependencies propagate correctly.' },
      { k: 'callout', tone: 'key', md: 'The `PUBLIC`, `PRIVATE` and `INTERFACE` keywords control how a dependency **propagates**:\n\n- **PRIVATE** — needed only by this target\n- **PUBLIC** — needed by this target and by everyone who uses it\n- **INTERFACE** — needed only by the users, not by this target' },
      { k: 'text', md: 'The usual workflow:\n\n```\ncmake -S . -B build -DCMAKE_BUILD_TYPE=Debug\ncmake --build build -j\nctest --test-dir build\n```\n\n`-S` is the source and `-B` the separate build directory. **Always build out of tree**, so generated files never mix with the source.' },
      { k: 'callout', tone: 'warn', md: 'Do not use `file(GLOB ...)` to collect source files. CMake only runs it at generation time, so it will not notice a newly added file until you regenerate. List the files explicitly — unambiguous and reliable.' },
      { k: 'callout', tone: 'tip', md: 'The `FetchContent` module pulls an external library straight from `CMakeLists.txt` with no installation. For test libraries (GoogleTest, Catch2) it is the simplest route.' },
    ],
    quiz: [
      { k: 'single', q: 'What does CMake do?', opts: ['Compiles', 'Generates: a Makefile, a Ninja file or an IDE project', 'Runs the program'], answer: 1, why: 'That is how the same project can build on every platform.' },
      { k: 'single', q: 'What does target-centric modern CMake mean?', opts: ['You set global variables', 'Every setting belongs to a target, via `target_...` commands', 'No difference'], answer: 1, why: 'That is what makes dependencies propagate correctly to the users of a target.' },
      { k: 'single', q: 'What does `PUBLIC` mean in `target_link_libraries`?', opts: ['Only this target needs it', 'This target and everyone who uses it needs it', 'Only the users need it'], answer: 1, why: '`PRIVATE` does not propagate; `INTERFACE` applies only to the users.' },
      { k: 'single', q: 'Why build out of tree?', opts: ['It is faster', 'So generated files do not mix with the source', 'It is required'], answer: 1, why: '`cmake -S . -B build` does exactly that, and the `build` directory can be deleted any time.' },
      { k: 'single', q: 'Why avoid `file(GLOB ...)`?', opts: ['It is slow', 'It only runs at generation time, so new files go unnoticed', 'It is unsupported'], answer: 1, why: 'Listing files explicitly is unambiguous and reliable.' },
    ],
    note: {
      summary: ['CMake generates a Makefile, a Ninja file or an IDE project.', 'Modern CMake is target centric: `target_...` commands, not globals.', 'PRIVATE stays, PUBLIC propagates, INTERFACE applies to users only.', 'Workflow: `cmake -S . -B build`, `cmake --build build`, `ctest`.', 'Always build into a separate directory.', 'Do not use `file(GLOB ...)` for sources.', '`FetchContent` pulls external libraries with no installation.'],
      terms: [{ term: 'target', def: 'A library or executable that settings attach to.' }, { term: 'out-of-tree build', def: 'A directory keeping generated files apart from the source.' }, { term: 'FetchContent', def: 'A CMake module that downloads dependencies during the build.' }],
    },
  },
  {
    day: 22,
    title: 'Reading compiler errors',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'C++ error messages are famously long. With a few rules the real cause is usually findable in thirty seconds.' },
      { k: 'callout', tone: 'key', md: 'Three rules:\n\n1. **Always fix the first error.** The rest are usually its consequence. One missing semicolon spawns twenty errors.\n2. **Read template errors from the bottom.** The upper lines list the instantiation trail; the real cause is at the end of the chain.\n3. **Look at the previous line too.** For a missing semicolon or bracket the compiler points at the following line.' },
      { k: 'text', md: 'The commonest messages and what they mean:\n\n- **"undefined reference to ..."** — a linker error: the declaration existed, the definition is missing\n- **"no matching function for call to ..."** — the argument types do not fit; read the listed candidates\n- **"incomplete type"** — only a forward declaration exists where the full definition is needed\n- **"invalid use of ... in read-only object"** — you called a non-`const` method on a `const` object\n- **"expected ; before ..."** — usually the semicolon is missing at the end of the **previous** line' },
      { k: 'callout', tone: 'tip', md: '**Clang** error messages are usually more readable than GCC ones. If a message is impenetrable, compile the same file with Clang — it often states the problem in a single sentence.' },
      { k: 'text', md: 'Useful flags for template errors:\n\n- `-fmax-errors=1` (GCC) or `-ferror-limit=1` (Clang) — only the first error, without the avalanche\n- `-fno-diagnostics-show-template-tree` — shorter template output\n- `-fdiagnostics-color=always` — colouring, which helps a lot with long type names' },
      { k: 'callout', tone: 'warn', md: 'Since C++20, **concepts** give far clearer template errors: instead of three hundred lines of instantiation trail you get "type T does not satisfy Sortable". Use them where you can.' },
    ],
    quiz: [
      { k: 'single', q: 'Which error should you fix first?', opts: ['The last', 'The first', 'The shortest'], answer: 1, why: 'The rest are usually its consequence. One missing semicolon spawns twenty errors.' },
      { k: 'single', q: 'How should you read a template error?', opts: ['Top down', 'Bottom up: the real cause is at the end of the chain', 'From the middle'], answer: 1, why: 'The upper lines list the instantiation trail.' },
      { k: 'single', q: 'What does "undefined reference" mean?', opts: ['A syntax error', 'A linker error: the definition is missing', 'A missing header'], answer: 1, why: 'The declaration existed, or the compiler would have complained earlier.' },
      { k: 'single', q: 'Where do you look for an "expected ; before ..." error?', opts: ['The reported line', 'Usually the end of the previous line', 'The top of the file'], answer: 1, why: 'The compiler notices the omission where the next statement would begin.' },
      { k: 'single', q: 'What do concepts give you?', opts: ['Faster compilation', 'Far clearer template error messages', 'A smaller binary'], answer: 1, why: 'Instead of three hundred lines of trail, one sentence naming the violated requirement.' },
    ],
    note: {
      summary: ['Always fix the first error: the rest follow from it.', 'Read template errors bottom up.', 'For a missing semicolon, check the previous line.', '"undefined reference" is a linker error: a missing definition.', '"incomplete type" means only a forward declaration exists.', 'Clang messages are often clearer; `-fmax-errors=1` cuts the avalanche.', 'C++20 concepts give far clearer template errors.'],
      terms: [{ term: 'error avalanche', def: 'Many follow-on errors caused by a single mistake.' }, { term: 'incomplete type', def: 'A forward-declared type without a full definition.' }, { term: 'concept', def: 'A C++20 feature naming template requirements.' }],
    },
  },
  {
    day: 23,
    title: 'Unit testing',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A **unit test** is a small, fast, automatic check of one behaviour. It is primarily not about finding bugs but about **daring to change things**.' },
      { k: 'code', lang: 'cpp', src: '#include <catch2/catch_test_macros.hpp>\n#include "rover.hpp"\n\nTEST_CASE("the rover does not pass through a wall") {\n    Rover r{"Alpha"};\n    r.place(0, 0);\n\n    SECTION("moves on a clear path") {\n        REQUIRE(r.step(10) == 10);\n        REQUIRE(r.x() == 10);\n    }\n\n    SECTION("stops at a wall") {\n        r.put_wall(5);\n        REQUIRE(r.step(10) == 5);\n    }\n}', explain: 'Each `SECTION` **re-runs** the start of the `TEST_CASE`, so it begins with a fresh `Rover`. That stops state leaking between tests.' },
      { k: 'callout', tone: 'key', md: 'A good test has three parts (**arrange, act, assert**): set up the state, perform the operation, check the result. If a test has several "act" steps, it usually should be two tests.' },
      { k: 'text', md: 'What to test:\n\n- **Edge cases**: empty input, zero, maximum, a single element\n- **Error paths**: what happens on invalid input\n- **Every bug you fix**: first write a test that fails, then fix it\n\nWhat not to test: trivial getters and things the compiler already guarantees.' },
      { k: 'callout', tone: 'warn', md: 'A **slow test is a dead test**. If the suite runs for minutes, nobody runs it. A unit test is measured in milliseconds: it must not touch the network, the file system or a database. If it has to, that is an integration test.' },
      { k: 'text', md: 'Wiring it up from CMake:\n\n```\nenable_testing()\nadd_executable(tests test/rover_test.cpp)\ntarget_link_libraries(tests PRIVATE robotlib Catch2::Catch2WithMain)\nadd_test(NAME rover COMMAND tests)\n```\n\nThen `ctest --test-dir build` runs them all.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the main benefit of unit tests?', opts: ['Finding bugs', 'The confidence to change things', 'Documentation'], answer: 1, why: 'They tell you a change broke nothing else. Bug finding is a side benefit.' },
      { k: 'single', q: 'What are the three parts of a good test?', opts: ['Setup, run, print', 'Arrange, act, assert', 'Open, read, close'], answer: 1, why: 'Set up the state, perform the operation, check the result.' },
      { k: 'single', q: 'What happens on each `SECTION` run in Catch2?', opts: ['It continues the previous state', 'The start of the `TEST_CASE` re-runs, so it begins fresh', 'It skips the others'], answer: 1, why: 'That stops state leaking between tests.' },
      { k: 'single', q: 'What should you not test?', opts: ['Edge cases', 'Trivial getters and things the compiler guarantees', 'Error paths'], answer: 1, why: 'They carry no risk, only maintenance cost.' },
      { k: 'single', q: 'Why is a slow test suite a problem?', opts: ['It uses memory', 'Because nobody runs it, which defeats the point', 'Because it is wrong'], answer: 1, why: 'A unit test is measured in milliseconds: no network, no file system.' },
    ],
    note: {
      summary: ['A unit test is a small, fast check of one behaviour.', 'Its main benefit is the confidence to change things.', 'Structure: arrange, act, assert.', 'In Catch2 every `SECTION` starts from a fresh state.', 'Test edge cases, error paths, and every bug you fix.', 'A slow test is a dead test: no network, no disk.', 'In CMake use `enable_testing()` and `add_test`, run with `ctest`.'],
      terms: [{ term: 'unit test', def: 'A fast automatic test of a single behaviour.' }, { term: 'arrange-act-assert', def: 'The three phases of a test: setup, action, check.' }, { term: 'integration test', def: 'A slower test exercising several components together.' }],
    },
  },
];
