import type { Track } from '../../types';
import { cppEnB } from './cpp-b';
import { cppEnC } from './cpp-c';
import { cppEnD } from './cpp-d';
import { cppEnE } from './cpp-e';

export const cppEn: Track = {
  id: 'cpp',
  title: 'C++',
  blurb: 'The power of C with classes, templates and the STL.',
  plannedTitles: [
    'C++ and C: what is the difference?',
    'Strings and vectors',
    'Classes and RAII',
    'Passing by reference and by value',
    'Constructors and destructors',
    'Copy and move semantics',
    'Operator overloading',
    'Inheritance and virtual methods',
    'Abstract classes',
    'Smart pointers',
    'Templates',
    'STL containers',
    'Iterators',
    'Algorithms: sort, find, transform',
    'Lambda expressions',
    'auto and type deduction',
    'const correctness',
    'Exception handling',
    'Namespaces',
    'Splitting headers and sources',
    'CMake basics',
    'Reading compiler errors',
    'Unit testing',
    'Performance and optimisation',
    'The cost of moving and copying',
    'Concurrency basics',
    'Modern C++ style',
    'Embedded C++',
    'A small program',
    'The complete project',
  ],
  days: [
    {
      day: 1,
      title: 'C++ and C: what is the difference?',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'C++ grew out of C, and almost every C program compiles as C++ too. But its **style** is radically different: in C you manage the memory, in C++ objects manage themselves.' },
        { k: 'code', lang: 'cpp', src: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, C++!" << std::endl;\n    return 0;\n}', explain: '`std::cout` is the output stream and `<<` is the insertion operator. There is no format specifier as in `printf` — the compiler knows the type.' },
        { k: 'callout', tone: 'key', md: 'That solves the worst problem with `printf`: with `cout` you **cannot** give a wrong format specifier, because there are none. The compiler knows whether you passed a number or text.' },
        { k: 'text', md: 'Compiling:\n\n```\ng++ -std=c++17 -Wall hello.cpp -o hello\n./hello\n```\n\n`-std=c++17` picks the language standard. Without it you get an older, poorer version.' },
        { k: 'code', lang: 'cpp', src: '#include <iostream>\nusing namespace std;   // avoid in a large project\n\nint main() {\n    cout << "shorter, but risky" << endl;\n}', explain: '`using namespace std;` saves the `std::` prefix but invites name clashes. Fine while learning, best avoided in a serious project.' },
      ],
      quiz: [
        { k: 'single', q: 'Why is `cout` safer than `printf`?', opts: ['It is faster', 'There is no format specifier to get wrong', 'Less typing'], answer: 1, why: '`printf` believes whatever the specifier claims. With `cout` the compiler knows the type, so it cannot be got wrong.' },
        { k: 'single', q: 'What does `std::` mean?', opts: ['Static', 'The namespace of the standard library', 'Standard data'], answer: 1, why: '`std` is the standard library namespace. `std::cout` means: the thing called `cout` from the `std` namespace.' },
        { k: 'single', q: 'Why avoid `using namespace std;` in a large project?', opts: ['It is slower', 'It can clash with your own names', 'It will not compile'], answer: 1, why: 'It brings the whole standard library in unqualified. Your own `count` or `distance` can collide with it.' },
        { k: 'output', q: 'What does this print?', code: '#include <iostream>\nint main() {\n    std::cout << 2 + 3 << "x" << std::endl;\n}', lang: 'cpp', opts: ['23x', '5x', '2+3x'], answer: 1, why: '`2 + 3` is evaluated to 5 first, that goes into the stream, then "x". The result is 5x.' },
      ],
      note: {
        summary: ['C++ grew out of C; most C code compiles, but the style differs.', '`std::cout << ... << std::endl` is output; there are no format specifiers.', 'That is safer than printf: the compiler knows the type.', 'Compile with `g++ -std=c++17 -Wall file.cpp -o file`.', '`using namespace std;` is convenient but invites clashes in a large project.'],
        terms: [{ term: 'stream', def: 'An input or output channel you write to with the `<<` operator.' }, { term: 'namespace', def: 'A group of names preventing clashes; the standard one is `std`.' }, { term: 'language standard', def: 'The version of C++, selected with the `-std=` flag.' }],
      },
    },
    {
      day: 2,
      title: 'Strings and vectors',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'In C, text is an array of characters and a list is memory you allocate by hand. C++ has a ready, safe type for both — one of the biggest wins of the language.' },
        { k: 'code', lang: 'cpp', src: '#include <string>\n#include <vector>\n#include <iostream>\n\nint main() {\n    std::string name = "Rover";\n    name += " Mk-II";\n    std::cout << name << " " << name.size() << "\\n";\n\n    std::vector<int> distances = {12, 8, 30};\n    distances.push_back(5);\n    std::cout << distances.size() << " " << distances[0] << "\\n";\n}', explain: 'A `string` grows by itself and a `vector` allocates by itself. No `malloc`, no `free`, no counting bytes.' },
        { k: 'callout', tone: 'key', md: 'A `vector` **manages its own memory**: when it goes out of scope, that memory is released. This is RAII, and it is why modern C++ rarely needs manual memory management.' },
        { k: 'code', lang: 'cpp', src: 'for (int d : distances) {\n    std::cout << d << " ";\n}\n\nfor (size_t i = 0; i < distances.size(); i++) {\n    std::cout << distances[i] << " ";\n}', explain: 'The range-based `for` reads better and cannot get the index wrong. Use it whenever you do not need the index itself.' },
        { k: 'callout', tone: 'warn', md: '`distances[10]` on a three-item vector does **not** raise — it just reads something from memory. For a check, `distances.at(10)` throws. `[]` is fast, `at()` is safe.' },
      ],
      quiz: [
        { k: 'single', q: 'What is the biggest advantage of `std::vector` over a C array?', opts: ['It is faster', 'It manages its own memory and size', 'It takes less space'], answer: 1, why: 'A vector grows when needed and frees itself when it goes out of scope. With a C array you would have to do both yourself.' },
        { k: 'single', q: 'What is the difference between `v[10]` and `v.at(10)`?', opts: ['None', 'at() checks and throws; [] does not check', 'at() is faster'], answer: 1, why: '`[]` does no bounds check — an invalid index is undefined behaviour. `at()` throws, at the cost of a hair of speed.' },
        { k: 'output', q: 'What does this print?', code: 'std::vector<int> v = {1, 2};\nv.push_back(3);\nstd::cout << v.size();', lang: 'cpp', opts: ['2', '3', '6'], answer: 1, why: 'It started with two items and `push_back` added one, so the size is 3.' },
        { k: 'single', q: 'When should you use the range-based `for`?', opts: ['Never', 'When you do not need the index itself', 'Only with strings'], answer: 1, why: 'It reads better and cannot get the bounds wrong. When you do need the index, the classic loop is the right choice.' },
      ],
      note: {
        summary: ['`std::string` grows by itself; no character-array handling.', '`std::vector` is a dynamic array that manages its own memory.', 'The memory is released when the vector goes out of scope — that is RAII.', 'The range-based `for (int x : v)` reads better when the index is not needed.', '`[]` does no bounds check; `at()` throws.'],
        terms: [{ term: 'std::vector', def: 'A dynamic array managing its own size and memory.' }, { term: 'RAII', def: "A principle tying a resource to an object's lifetime." }, { term: 'range-based for', def: 'A loop that walks a container without an index.' }],
      },
    },
    {
      day: 3,
      title: 'Classes and RAII',
      minutes: 24,
      lesson: [
        { k: 'text', md: 'A C++ class resembles a Java one, but it has something Java does not: the **destructor** — and the most important idea in the language grows out of it.' },
        { k: 'code', lang: 'cpp', src: 'class Rover {\npublic:\n    Rover(std::string name) : name_(name) {\n        std::cout << "created\\n";\n    }\n\n    ~Rover() {\n        std::cout << "destroyed\\n";\n    }\n\n    void drive(int cm) { battery_ -= cm / 10; }\n    int battery() const { return battery_; }\n\nprivate:\n    std::string name_;\n    int battery_ = 100;\n};', explain: '`~Rover()` is the destructor: it runs automatically when the object ceases to exist. The part after the colon is the initialiser list.' },
        { k: 'callout', tone: 'key', md: '**RAII** means this: the constructor acquires the resource and the destructor returns it. A file, memory, a network connection, a lock — all of them. Because the destructor **is guaranteed** to run when the object goes out of scope, releasing cannot be forgotten.' },
        { k: 'code', lang: 'cpp', src: '{\n    Rover r("Mk-I");    // "created"\n    r.drive(50);\n}                       // "destroyed" — automatically' },
        { k: 'callout', tone: 'tip', md: '`const` after a method (`int battery() const`) promises that the method does not modify the object. The compiler enforces it. Put it on every query method — that is "const correctness", and it prevents a lot of bugs.' },
      ],
      quiz: [
        { k: 'single', q: 'When does a destructor run?', opts: ['When you call it', 'When the object is destroyed or goes out of scope', 'At the end of the program'], answer: 1, why: 'A destructor is automatic: it runs at the end of the scope, or on `delete`. You neither need nor normally call it by hand.' },
        { k: 'single', q: 'What does RAII mean?', opts: ['Fast compilation', 'The constructor acquires a resource, the destructor returns it', 'The name of a library'], answer: 1, why: 'Resource Acquisition Is Initialization. Because the destructor is guaranteed to run, the resource cannot be left unreleased.' },
        { k: 'single', q: 'What does `const` after a method promise?', opts: ['The method is fast', 'The method does not modify the object', 'The method is private'], answer: 1, why: 'The compiler checks it: if the method did write a field, you get a compile error. It makes clear at a glance what mutates and what does not.' },
        { k: 'output', q: 'How many lines does this block print?', code: '{\n    Rover r("A");\n}', lang: 'cpp', opts: ['1', '2', '0'], answer: 1, why: 'The constructor prints "created" and at the end of the block the destructor prints "destroyed" — two lines.' },
      ],
      note: {
        summary: ['A C++ class has a destructor (`~Class()`) that runs automatically.', 'The destructor is guaranteed to run at the end of the scope — it cannot be forgotten.', 'RAII: the constructor acquires the resource, the destructor returns it.', 'The initialiser list (`: member_(value)`) sets fields in the constructor header.', '`const` after a method promises it does not modify the object.'],
        terms: [{ term: 'destructor', def: 'A method that runs automatically when an object is destroyed.' }, { term: 'RAII', def: "Managing a resource by tying it to an object's lifetime." }, { term: 'const method', def: 'A method the compiler guarantees does not modify the object.' }],
      },
    },
    ...cppEnB,
    ...cppEnC,
    ...cppEnD,
    ...cppEnE,
  ],
};
