import type { Track } from '../../types';

export const javaEn: Track = {
  id: 'java',
  title: 'Java',
  blurb: 'Classes, types, the JVM — the language of large systems.',
  plannedTitles: [
    'Your first Java program',
    'Types and variables',
    'Classes and objects',
    'Methods and parameters',
    'Branching and loops',
    'Arrays',
    'Working with strings',
    'Constructors',
    'Visibility: public and private',
    'Getters, setters, encapsulation',
    'Static members',
    'Inheritance',
    'Abstract classes and interfaces',
    'Polymorphism in practice',
    'Exception handling',
    'Your own exception',
    'Collections: List and Map',
    'Iterators and for-each',
    'Generics',
    'Lambdas and functional interfaces',
    'The Stream API',
    'Working with files',
    'Packages and imports',
    'Builds: Maven basics',
    'Unit testing with JUnit',
    'Threads basics',
    'Memory and garbage collection',
    'Debugging in an IDE',
    'A small application',
    'The complete project',
  ],
  days: [
    {
      day: 1,
      title: 'Your first Java program',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'Java code does not run on the machine directly. It compiles to **bytecode**, and the **JVM** (Java Virtual Machine) executes that. This is why the same program runs unchanged on Windows, Linux and Mac.' },
        { k: 'code', lang: 'java', src: 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Hello, Java!");\n    }\n}', explain: 'The file must be called `Hello.java` — it has to match the public class name. That is one of the strictest rules in Java.' },
        { k: 'text', md: 'Compile and run:\n\n```\njavac Hello.java    → produces Hello.class\njava Hello          → runs it\n```\n\nOn recent Java versions one step is enough: `java Hello.java`.' },
        { k: 'callout', tone: 'key', md: '`main` is the entry point and its signature is fixed: `public static void main(String[] args)`. Get any of it wrong and the program compiles but will not start — you get "main method not found".' },
        { k: 'callout', tone: 'tip', md: 'Compared with Python, Java is **verbose**: all code lives in a class, every statement ends with a semicolon, every variable has a type. That is a burden at first, and in a large system it is exactly what keeps the chaos in check.' },
      ],
      quiz: [
        { k: 'single', q: 'What is the JVM?', opts: ['A text editor', 'The virtual machine that runs the bytecode', 'The Java compiler'], answer: 1, why: 'The compiler (`javac`) produces bytecode and the JVM executes it. That is what makes a Java program platform-independent.' },
        { k: 'single', q: 'What must the file be called if the public class is `Robot`?', opts: ['robot.java', 'Robot.java', 'It does not matter'], answer: 1, why: 'The file name must match the public class name exactly, including case. Otherwise the compiler refuses it.' },
        { k: 'output', q: 'What does this print?', code: 'public class A {\n    public static void main(String[] args) {\n        System.out.println(2 + 3 + "x");\n    }\n}', lang: 'java', opts: ['23x', '5x', '2 + 3 + x'], answer: 1, why: 'It evaluates left to right: 2+3 = 5 (still a number), then 5 + "x" joins as text: "5x".' },
        { k: 'single', q: 'What happens if you mistype the `main` signature?', opts: ['It compiles but will not start', 'It will not compile', 'It runs, only slower'], answer: 0, why: 'The compiler does not require a main, but the JVM looks for exactly that signature at launch. Missing it gives "main method not found".' },
      ],
      note: {
        summary: ['Java compiles to bytecode, which the JVM runs — hence platform independence.', '`javac Hello.java` compiles, `java Hello` runs.', 'The file name must match the public class name.', 'The entry point signature is fixed: `public static void main(String[] args)`.', 'All code lives in a class and every statement ends with a semicolon.'],
        terms: [{ term: 'JVM', def: 'The virtual machine that executes Java bytecode.' }, { term: 'bytecode', def: 'The intermediate form compiled from source, run by the JVM.' }, { term: 'main method', def: "The program's entry point, with a fixed signature." }],
      },
    },
    {
      day: 2,
      title: 'Types and variables',
      minutes: 20,
      lesson: [
        { k: 'text', md: 'Java is **statically typed**: you declare the type of every variable and it never changes. In Python `x = 5` followed by `x = "hi"` is fine; in Java it is a compile error.' },
        { k: 'code', lang: 'java', src: 'int distance = 15;\ndouble weight = 2.45;\nboolean running = true;\nchar mark = \'A\';\nString name = "Rover";\n\nfinal int MAX = 100;      // cannot be reassigned', explain: '`String` is capitalised because it is a class, not a primitive. `final` means: assigned once, constant thereafter.' },
        { k: 'text', md: 'The **primitives** hold a value directly: `int`, `long`, `double`, `float`, `boolean`, `char`, `byte`, `short`. Everything else is an **object**: `String`, `Integer`, your own classes.' },
        { k: 'callout', tone: 'warn', md: 'Integer division truncates in Java too: `7 / 2` is **3**, not 3.5. For a decimal, make at least one side a `double`: `7.0 / 2`.' },
        { k: 'callout', tone: 'key', md: 'The cost of static typing is more typing. The benefit is that most mistakes surface **at compile time** rather than six months later at a user. On a large system that trade is worth it.' },
      ],
      quiz: [
        { k: 'output', q: 'What does this print?', code: 'int a = 7;\nint b = 2;\nSystem.out.println(a / b);', lang: 'java', opts: ['3.5', '3', '4'], answer: 1, why: 'Dividing two integers gives an integer: the fractional part is lost. You get 3 instead of 3.5.' },
        { k: 'single', q: 'What does `final` mean on a variable?', opts: ['It is the last variable', 'Assigned once, then unchangeable', 'It is deleted automatically'], answer: 1, why: '`final` makes it a constant: reassignment is a compile error. It signals that this value will not change.' },
        { k: 'single', q: 'Why is `String` capitalised?', opts: ['It looks nicer', 'Because it is a class, not a primitive', 'By accident'], answer: 1, why: 'Primitives are lowercase (`int`, `double`); classes start with a capital. `String` is an object, hence the capital S.' },
        { k: 'single', q: 'What is the main benefit of static typing?', opts: ['Faster execution', 'Most mistakes surface at compile time', 'Less typing'], answer: 1, why: 'The compiler checks types before the program ever runs. Many bugs therefore never reach a user.' },
      ],
      note: {
        summary: ['Java is statically typed: a variable\'s type is fixed and cannot change.', 'Primitives: int, long, double, float, boolean, char, byte, short.', 'Everything else is an object, including `String` — hence the capital letter.', 'Integer division gives an integer: `7 / 2` is 3. For a decimal use `7.0 / 2`.', '`final` turns a variable into a constant.', 'Static typing costs typing and buys compile-time errors.'],
        terms: [{ term: 'static typing', def: "A variable's type is fixed at compile time and cannot change." }, { term: 'primitive type', def: 'A basic type holding a value directly, such as int or double.' }, { term: 'final', def: 'A keyword making a variable a write-once constant.' }],
      },
    },
    {
      day: 3,
      title: 'Classes and objects',
      minutes: 22,
      lesson: [
        { k: 'text', md: 'In Java **everything** lives in a class. There is no free-standing function as in Python — which is why classes are not an advanced topic here but arrive on day three.' },
        { k: 'code', lang: 'java', src: 'public class Rover {\n    private String name;\n    private int battery = 100;\n\n    public Rover(String name) {      // constructor\n        this.name = name;\n    }\n\n    public void drive(int cm) {\n        battery -= cm / 10;\n    }\n\n    public int getBattery() {\n        return battery;\n    }\n}', explain: 'The constructor is named after the class and has no return type. `this.name` is the field; `name` is the parameter.' },
        { k: 'code', lang: 'java', src: 'Rover r = new Rover("Mk-I");\nr.drive(50);\nSystem.out.println(r.getBattery());    // 95', explain: '`new` creates the instance and calls the constructor. `Rover r` is the type, `r` is the variable.' },
        { k: 'callout', tone: 'key', md: 'A `private` field cannot be touched from outside — only through methods. This is **encapsulation**, and it is not a formality: it is how you guarantee the battery never goes negative, whoever uses your class.' },
        { k: 'callout', tone: 'warn', md: '`new Rover("A")` and `new Rover("A")` are **two different objects**, even holding the same thing. That is why `r1 == r2` is `false`. Comparing content needs `equals()` — one of the classic Java traps.' },
      ],
      quiz: [
        { k: 'single', q: 'What characterises a constructor?', opts: ['It is called main', 'Named after the class, with no return type', 'It is always private'], answer: 1, why: 'A constructor must carry the class name and declares no return type — not even `void`.' },
        { k: 'single', q: 'What does `r1 == r2` give for two separate `new Rover("A")` calls?', opts: ['true', 'false', 'A compile error'], answer: 1, why: 'For objects, `==` asks whether it is the same instance, not whether the contents match. Content needs `equals()`.' },
        { k: 'single', q: 'Why make fields `private`?', opts: ['It is faster', 'So only methods can change them and the state stays valid', 'Because it is required'], answer: 1, why: 'That is encapsulation. If anyone could write the battery directly, you could not guarantee it never goes negative.' },
        { k: 'output', q: 'What does this print?', code: 'Rover r = new Rover("X");\nr.drive(50);\nSystem.out.println(r.getBattery());', lang: 'java', opts: ['100', '95', '50'], answer: 1, why: 'From the initial 100, `drive(50)` subtracts 50/10 = 5, leaving 95.' },
      ],
      note: {
        summary: ['In Java all code lives in a class; there are no free-standing functions.', 'A constructor carries the class name and has no return type.', '`new` creates the instance and calls the constructor.', 'A `private` field is reachable only through methods — that is encapsulation.', 'For objects `==` tests identity, not content; content needs `equals()`.'],
        terms: [{ term: 'constructor', def: 'A method named after the class, run when an instance is created.' }, { term: 'encapsulation', def: "Hiding data so it can only be changed through the class's methods." }, { term: 'this', def: 'A reference to the instance itself, distinguishing field from parameter.' }],
      },
    },
  ],
};
