import type { Day } from '../../types';

/** PHYSICS track, days 13-19. */
export const physicsEnD: Day[] = [
  {
    day: 13,
    title: 'Drag',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Air and water resist motion. At low speed that is negligible; at high speed **it sets the top speed** — not the power of the motor.' },
      { k: 'callout', tone: 'key', md: 'At higher speeds drag grows with the **square of speed**:\n\n`F = ½ · ρ · v² · C · A`\n\nwhere `ρ` is the fluid density, `v` the speed, `C` the drag coefficient and `A` the frontal area.' },
      { k: 'text', md: 'The square is the point. **Twice the speed is four times the drag** — and since power is force times speed, that needs **eight times the power**. A car does not go twice as fast with twice the engine.' },
      { k: 'code', lang: 'py', src: 'rho, C, A = 1.225, 0.9, 0.05     # air, boxy robot, 500 cm2\n\ndef drag(v):\n    return 0.5 * rho * v*v * C * A\n\nfor v in (1, 2, 4, 8):\n    print(v, "m/s ->", round(drag(v), 3), "N")\n# 1 -> 0.028   2 -> 0.110   4 -> 0.441   8 -> 1.764', explain: 'Eight times the speed, sixty-four times the force. On a slow robot drag is negligible; on a drone it is everything.' },
      { k: 'callout', tone: 'tip', md: 'The `C` coefficient varies enormously: a flat plate is about 1.2; a sphere 0.47; a teardrop 0.04. The shape of the **rear** matters more than the front: that is where the flow separates and the suction forms.' },
      { k: 'text', md: '**Terminal velocity** arrives when the driving force equals the drag. From then on there is no acceleration. The same holds for a falling object: weight and drag balance, and the speed stays constant.' },
      { k: 'callout', tone: 'warn', md: 'At very low speed, or for very small objects, drag is **linear** rather than quadratic (Stokes law). A dust mote or a microrobot lives in a completely different world from a car.' },
    ],
    quiz: [
      { k: 'single', q: 'How does drag depend on speed at high speed?', opts: ['Linearly', 'With the square of speed', 'Not at all'], answer: 1, why: 'Twice the speed means four times the drag. That is the key practical consequence.' },
      { k: 'single', q: 'How much power does twice the speed need?', opts: ['Twice', 'Four times', 'Eight times'], answer: 2, why: 'Four times the force at twice the speed, and power is force times speed, so eight times.' },
      { k: 'single', q: 'Which part of a shape matters more for streamlining?', opts: ['The front', 'The rear, where the flow separates', 'Neither'], answer: 1, why: 'Most of the drag comes from the wake and suction formed at separation.' },
      { k: 'single', q: 'When is terminal velocity reached?', opts: ['When the fuel runs out', 'When the driving force equals the drag', 'Never'], answer: 1, why: 'The net force is then zero, so the acceleration is zero and the speed stays constant.' },
      { k: 'single', q: 'What is true for very small objects at very low speed?', opts: ['Drag is linear, not quadratic', 'There is no drag', 'Drag is cubic'], answer: 0, why: 'That is the Stokes regime. A dust mote or microrobot follows completely different rules.' },
    ],
    note: {
      summary: ['`F = ½ · ρ · v² · C · A` is the drag formula.', 'At high speed drag grows with the square of speed.', 'Twice the speed needs eight times the power.', 'Drag coefficient: flat plate 1.2, sphere 0.47, teardrop 0.04.', 'The rear shape matters more than the front: flow separates there.', 'Terminal velocity: driving force equals drag.', 'For very small objects drag is linear (Stokes).'],
      terms: [{ term: 'drag coefficient (C)', def: 'A dimensionless number measuring aerodynamic quality of a shape.' }, { term: 'frontal area', def: 'The projected area perpendicular to the motion.' }, { term: 'terminal velocity', def: 'The speed where driving force and drag balance.' }],
    },
  },
  {
    day: 14,
    title: 'Charge and voltage',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Electricity starts with **charge**. There are two kinds; opposites attract and likes repel. The unit is the **coulomb (C)**; an electron carries 1.6 × 10⁻¹⁹ C.' },
      { k: 'callout', tone: 'key', md: '**Voltage** (volts) is not "an amount of electricity" but **energy difference per unit charge**:\n\n`1 V = 1 J / 1 C`\n\nThat is: one coulomb passing through one volt of difference does one joule of work.' },
      { k: 'text', md: 'Height is the best picture. Voltage is like a **difference in level**: what matters is not where you are but how big the difference is. That is why "ground" is meaningful — zero has to be defined somewhere.' },
      { k: 'callout', tone: 'warn', md: 'This is why voltage is always **between two points**. Talking about the voltage of a single point is meaningless, just as the height of a point only exists relative to something.' },
      { k: 'text', md: 'Common voltages in robotics:\n\n- Logic circuits: **3.3 V** or **5 V**\n- A Li-ion cell: **3.7 V** nominal (4.2 V full, 3.0 V empty)\n- Servos and small motors: **6–12 V**\n- Larger drives: **24 V** or **48 V**' },
      { k: 'callout', tone: 'tip', md: 'For the human body it is **current that is dangerous, not voltage by itself**. A 9 V battery is harmless, because against skin resistance almost no current flows. Above 50 V be careful, and never experiment with mains voltage.' },
    ],
    quiz: [
      { k: 'single', q: 'What does 1 volt mean?', opts: ['1 amp of current', '1 joule of energy per coulomb', '1 ohm of resistance'], answer: 1, why: 'Voltage is energy difference per unit charge. Everything else follows from that.' },
      { k: 'single', q: 'Why do we always speak of a voltage difference?', opts: ['Tradition', 'Because voltage is a relation between two points, like a height difference', 'Because it is hard to measure'], answer: 1, why: 'The voltage of a single point alone is meaningless, just like the height of a point.' },
      { k: 'single', q: 'What is the nominal voltage of a Li-ion cell?', opts: ['1.5 V', '3.7 V', '12 V'], answer: 1, why: '4.2 V full, around 3.0 V empty. The nominal figure is the average in between.' },
      { k: 'single', q: 'What is primarily dangerous to the human body?', opts: ['Voltage by itself', 'Current', 'The amount of charge'], answer: 1, why: 'A 9 V battery is harmless because almost no current flows through skin resistance.' },
      { k: 'single', q: 'What is the unit of charge?', opts: ['Volt', 'Coulomb', 'Watt'], answer: 1, why: 'An electron carries 1.6 × 10⁻¹⁹ coulombs.' },
    ],
    note: {
      summary: ['Charge is measured in coulombs; an electron carries 1.6 × 10⁻¹⁹ C.', '1 V = 1 J / 1 C: energy difference per unit charge.', 'Voltage always exists between two points, like a height difference.', 'Typical values: logic 3.3/5 V, Li-ion 3.7 V, motors 6–48 V.', 'Current is what harms the body, not voltage alone.'],
      terms: [{ term: 'charge', def: 'The base quantity of electrical interaction, in coulombs.' }, { term: 'voltage', def: 'Energy difference per unit charge, between two points.' }, { term: 'ground (reference)', def: 'The point chosen as zero for measuring voltage.' }],
    },
  },
  {
    day: 15,
    title: 'Current and Ohm law',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Current** is the flow of charge: how many coulombs pass a cross-section per second. The unit is the **ampere**: 1 A = 1 C/s.' },
      { k: 'callout', tone: 'key', md: '**Ohm law** ties the three together:\n\n`U = I · R`\n\nVoltage = current × resistance. Any two give the third, and that is the basis of all DC circuit analysis.' },
      { k: 'text', md: 'The plumbing picture works very well:\n\n- **voltage** → pressure\n- **current** → the volume of water flowing\n- **resistance** → the narrowing of the pipe\n\nMore pressure pushes more water; a narrower pipe passes less.' },
      { k: 'code', lang: 'py', src: '# Series resistor for an LED\nU_supply = 5.0     # V\nU_led    = 2.0     # V, forward voltage of a red LED\nI_target = 0.015   # A, 15 mA\n\nR = (U_supply - U_led) / I_target\nprint(round(R), "ohms")       # 200 ohms -> nearest standard: 220\n\nP = (U_supply - U_led) * I_target\nprint(round(P, 3), "W")       # 0.045 W -> a 0.25 W resistor is plenty', explain: 'The LED voltage is fixed; the resistor must absorb the rest. Always pick the larger standard value — a smaller current is safer.' },
      { k: 'callout', tone: 'warn', md: 'An LED is **not ohmic**: it has no constant resistance, it conducts at an almost fixed voltage. Without a series resistor the current grows without limit and the LED burns out instantly. This is the most common beginner mistake in electronics.' },
      { k: 'text', md: 'Not every component follows Ohm law. **Ohmic**: resistors, wire, heating elements. **Non-ohmic**: diodes, LEDs, transistors, filament bulbs (whose resistance changes with temperature).' },
    ],
    quiz: [
      { k: 'single', q: 'What does 1 ampere mean?', opts: ['1 volt / 1 ohm', '1 coulomb per second', '1 joule'], answer: 1, why: 'Current is the rate of charge flow: coulombs per second.' },
      { k: 'single', q: 'What is Ohm law?', opts: ['`U = I · R`', '`P = U · I`', '`F = m · a`'], answer: 0, why: 'Voltage = current × resistance. All DC analysis follows from it.' },
      { k: 'single', q: 'Why does an LED need a series resistor?', opts: ['To make it brighter', 'Because an LED is non-ohmic: unchecked, the current runs away and burns it out', 'To stop it flickering'], answer: 1, why: 'An LED conducts at an almost fixed voltage. The current has to be limited separately.' },
      { k: 'single', q: 'From 5 V, driving a 2 V LED at 15 mA, what resistor do you need?', opts: ['100 ohms', '200 ohms', '470 ohms'], answer: 1, why: '(5 − 2) / 0.015 = 200 ohms. In practice the next standard value, 220 ohms.' },
      { k: 'single', q: 'Which component is NOT ohmic?', opts: ['A resistor', 'A diode', 'Copper wire'], answer: 1, why: 'Diodes and LEDs are non-linear: current rises exponentially with voltage.' },
    ],
    note: {
      summary: ['Current is charge flow: 1 A = 1 C/s.', 'Ohm law: `U = I · R`.', 'Plumbing picture: voltage is pressure, current is flow, resistance is narrowing.', 'An LED always needs a series resistor because it is non-ohmic.', 'Series resistor: `R = (U_supply − U_LED) / I_target`.', 'Non-ohmic: diodes, LEDs, transistors, filament bulbs.'],
      terms: [{ term: 'ampere', def: 'The unit of current: coulombs per second.' }, { term: 'Ohm law', def: '`U = I · R`, the basis of DC analysis.' }, { term: 'series resistor', def: 'A current-limiting resistor beside a non-ohmic part.' }],
    },
  },
  {
    day: 16,
    title: 'Series and parallel',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'There are two basic connections, and every complex circuit is built from them. The difference is one question: **what is shared** — the current or the voltage?' },
      { k: 'callout', tone: 'key', md: '**Series**: one path, so **the current is shared**. The voltage divides.\n\n`R_total = R₁ + R₂ + ...`\n\n**Parallel**: several paths, so **the voltage is shared**. The current divides.\n\n`1/R_total = 1/R₁ + 1/R₂ + ...`' },
      { k: 'text', md: 'Two useful consequences:\n\n- In series the total is **always larger** than the largest part.\n- In parallel the total is **always smaller** than the smallest part.\n\nIf your answer breaks that, you made an arithmetic mistake.' },
      { k: 'code', lang: 'py', src: 'def series(*r):\n    return sum(r)\n\ndef parallel(*r):\n    return 1 / sum(1/x for x in r)\n\nprint(series(100, 220))         # 320 ohms\nprint(parallel(100, 100))       # 50.0 ohms  -- two equal: half\nprint(parallel(100, 1000))      # 90.9 ohms  -- close to the smaller', explain: 'Two equal resistors in parallel give half. If one is much larger, the total is almost exactly the smaller one.' },
      { k: 'callout', tone: 'warn', md: 'The **voltage divider** is the commonest use of a series pair:\n\n`U_out = U_in · R₂ / (R₁ + R₂)`\n\nBut it is only accurate **unloaded**. The moment you attach a load it sits in parallel with `R₂` and the voltage sags. That is why you cannot build a power supply from a divider.' },
      { k: 'text', md: 'In practice: **LEDs in series** get identical current (so they look equally bright), while **in parallel** small manufacturing differences make them unequal. That is why every branch gets its own series resistor.' },
    ],
    quiz: [
      { k: 'single', q: 'What is shared in a series connection?', opts: ['The voltage', 'The current', 'The resistance'], answer: 1, why: 'There is one path, so the same current flows through everything. The voltage divides.' },
      { k: 'single', q: 'What is the total of two 100-ohm resistors in parallel?', opts: ['200 ohms', '50 ohms', '100 ohms'], answer: 1, why: 'Two equal resistors in parallel give half.' },
      { k: 'single', q: 'What is true of a parallel total?', opts: ['Always larger than the largest part', 'Always smaller than the smallest part', 'The average of the parts'], answer: 1, why: 'A good sanity check: if it came out otherwise, the arithmetic is wrong.' },
      { k: 'single', q: 'Why can you not build a power supply from a voltage divider?', opts: ['Too expensive', 'Because the output voltage sags under load', 'Because it gets hot'], answer: 1, why: 'The load sits in parallel with the lower resistor and changes the division ratio.' },
      { k: 'single', q: 'Why does every parallel LED need its own resistor?', opts: ['It looks nicer', 'Because manufacturing differences would make them share current unevenly', 'It is cheaper'], answer: 1, why: 'The LED with the lower forward voltage would take more current, run brighter and fail sooner.' },
    ],
    note: {
      summary: ['Series: shared current, total `R₁ + R₂`.', 'Parallel: shared voltage, `1/R = 1/R₁ + 1/R₂`.', 'A series total exceeds the largest part; a parallel total is below the smallest.', 'Two equal resistors in parallel give half.', 'Voltage divider: `U_out = U_in · R₂/(R₁+R₂)`, accurate only unloaded.', 'Parallel LEDs need a resistor per branch.'],
      terms: [{ term: 'series', def: 'One path; current is shared, voltage divides.' }, { term: 'parallel', def: 'Several paths; voltage is shared, current divides.' }, { term: 'voltage divider', def: 'A series resistor pair whose midpoint gives a proportional voltage.' }],
    },
  },
  {
    day: 17,
    title: 'Power and heat',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Electrical **power** says how fast energy is converted. In a resistor it all turns into heat — which is why every circuit warms up.' },
      { k: 'callout', tone: 'key', md: 'Three forms of the same thing:\n\n`P = U · I`\n`P = I² · R`\n`P = U² / R`\n\nUse whichever matches the two quantities you know.' },
      { k: 'text', md: 'The `I² · R` form is the most instructive: heat grows with the **square of current**. Twice the current means four times the heating. That is why a wire that is warm at 5 A melts at 10 A.' },
      { k: 'code', lang: 'py', src: '# How much does the wire lose?\nR_wire = 0.05        # ohms, 2 m of thin cable\n\nfor I in (1, 5, 10, 20):\n    P = I*I * R_wire\n    print(I, "A ->", round(P, 2), "W lost")\n# 1 -> 0.05   5 -> 1.25   10 -> 5.0   20 -> 20.0', explain: 'At twenty amps two metres of cable dissipate 20 watts. That is a soldering iron — which is why high current needs thicker wire.' },
      { k: 'callout', tone: 'warn', md: 'Every resistor has a **power rating**: a common small one is 0.25 W. Dissipate more and it browns, then burns out. Always compute the dissipation and pick at least double the margin.' },
      { k: 'text', md: 'At high current there are two answers: **thicker wire** (lower R) or **higher voltage** (the same power at less current). That is why transmission lines run at high voltage, and why robots move to 24 V or 48 V for larger drives.' },
      { k: 'callout', tone: 'tip', md: 'Battery capacity is quoted in **amp-hours (Ah)** but its energy is in **watt-hours (Wh)**: `Wh = Ah · V`. Only compare batteries in watt-hours — a 5 Ah 3.7 V cell (18.5 Wh) holds far less than a 3 Ah 12 V pack (36 Wh).' },
    ],
    quiz: [
      { k: 'single', q: 'How does dissipated power depend on current?', opts: ['Linearly', 'With the square', 'Not at all'], answer: 1, why: '`P = I² · R`. Twice the current means four times the heating.' },
      { k: 'single', q: 'Which formula do you use knowing current and resistance?', opts: ['`P = U · I`', '`P = I² · R`', '`P = U² / R`'], answer: 1, why: 'Always pick the form that matches the two quantities you have.' },
      { k: 'single', q: 'What happens to a 0.25 W resistor dissipating 1 W?', opts: ['Nothing', 'It browns and then burns out', 'It becomes more efficient'], answer: 1, why: 'The power rating is the allowed heat dissipation. Always pick at least double the margin.' },
      { k: 'single', q: 'Why is electrical energy transmitted at high voltage?', opts: ['Cheaper cable', 'Because the same power flows at lower current, and loss grows with the square of current', 'Because it is faster'], answer: 1, why: 'Ten times the voltage is a tenth of the current, and a hundredth of the line loss.' },
      { k: 'single', q: 'Which battery stores more energy: 5 Ah at 3.7 V or 3 Ah at 12 V?', opts: ['The first', 'The second', 'The same'], answer: 1, why: '18.5 Wh versus 36 Wh. Amp-hours alone are not comparable across different voltages.' },
    ],
    note: {
      summary: ['`P = U · I = I² · R = U² / R`.', 'Heat grows with the square of current: twice the current, four times the heat.', 'Every resistor has a power rating; a small one is 0.25 W.', 'At high current: thicker wire or higher voltage.', 'Compare batteries in watt-hours: `Wh = Ah · V`.'],
      terms: [{ term: 'dissipation', def: 'Electrical power converted into heat.' }, { term: 'power rating', def: 'The heat dissipation a component can withstand.' }, { term: 'watt-hour', def: 'An energy unit: capacity times voltage.' }],
    },
  },
  {
    day: 18,
    title: 'Capacitors',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A **capacitor** is two conducting plates separated by an insulator. It stores charge and thereby **holds a voltage** — but only briefly. It is not a battery: it stores less energy, but gives and takes it very quickly.' },
      { k: 'callout', tone: 'key', md: 'The basic relation:\n\n`Q = C · U`\n\nwhere `Q` is stored charge (coulombs), `C` the capacitance (farads) and `U` the voltage. The stored energy is `E = ½ · C · U²`.' },
      { k: 'text', md: 'The `U²` matters: **twice the voltage holds four times the energy**. That is why it pays to run a capacitor at the highest safe voltage.' },
      { k: 'code', lang: 'py', src: 'C = 1000e-6        # 1000 uF\nU = 12.0\n\nQ = C * U\nE = 0.5 * C * U*U\nprint(round(Q, 4), "C")      # 0.012 coulombs\nprint(round(E, 4), "J")      # 0.072 joules\n\n# Charging time constant through a resistor\nR = 1000           # ohms\nprint(R * C, "s")            # 1.0 s -> after 5 tau, essentially full', explain: 'The time constant `tau = R · C` is how long it takes to reach 63 percent of the final value. After five time constants it is essentially fully charged.' },
      { k: 'callout', tone: 'warn', md: 'An **electrolytic capacitor is polarised**: the longer leg is positive. Wired backwards it heats up and bursts. That is not an exaggeration — the plastic sleeve splits and the electrolyte escapes.' },
      { k: 'text', md: 'What do you use them for?\n\n- **Filtering** — smoothing supply noise. 100 nF beside every IC.\n- **Buffering** — absorbing a current surge, for instance at motor start.\n- **Timing** — an RC pair for a delay or a filter.\n- **Coupling** — blocking DC while passing an AC signal.' },
      { k: 'callout', tone: 'tip', md: 'Put a **100 nF ceramic capacitor** beside every microcontroller supply pin, as close as possible. That decoupling capacitor is the simplest and most effective thing you can do for circuit stability.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the basic capacitor relation?', opts: ['`U = I · R`', '`Q = C · U`', '`P = U · I`'], answer: 1, why: 'Stored charge is capacitance times voltage.' },
      { k: 'single', q: 'How much more energy fits at twice the voltage?', opts: ['Twice', 'Four times', 'The same'], answer: 1, why: '`E = ½ · C · U²`, so voltage counts quadratically.' },
      { k: 'single', q: 'What does the RC time constant mean?', opts: ['The full charging time', 'The time to reach 63 percent of the final value', 'The discharge rate'], answer: 1, why: 'After five time constants it is essentially fully charged.' },
      { k: 'single', q: 'What happens to a reverse-wired electrolytic capacitor?', opts: ['It does not work', 'It heats up and bursts', 'It charges slower'], answer: 1, why: 'The longer leg is positive. With reversed polarity the sleeve splits open.' },
      { k: 'single', q: 'What is a decoupling capacitor?', opts: ['It cools the chip', 'A 100 nF ceramic at the IC supply pin against supply noise', 'A large electrolytic in the power supply'], answer: 1, why: 'The simplest and most effective stability measure. Place it as close to the pin as possible.' },
    ],
    note: {
      summary: ['A capacitor stores charge: `Q = C · U`, energy `E = ½ · C · U²`.', 'Twice the voltage holds four times the energy.', 'RC time constant `tau = R · C` gives 63 percent charge; five tau is full.', 'Electrolytic capacitors are polarised and burst if reversed.', 'Uses: filtering, buffering, timing, coupling.', '100 nF ceramic beside every IC supply pin, as close as possible.'],
      terms: [{ term: 'capacitance', def: 'Charge stored per unit voltage, in farads.' }, { term: 'time constant', def: '`R · C`: the characteristic charging time.' }, { term: 'decoupling capacitor', def: 'A small ceramic beside an IC supply pin against noise.' }],
    },
  },
  {
    day: 19,
    title: 'Magnetic fields',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A magnetic field forms around every moving charge. That is why **every current-carrying wire is a magnet**, and why every electric motor turns.' },
      { k: 'callout', tone: 'key', md: 'The **right-hand rule**: point your right thumb along the current, and the curl of your fingers gives the circular direction of the field around the wire.' },
      { k: 'text', md: 'The field of a straight wire is weak. Wind it into a **coil** and the turns add up, giving a strong, even field inside. That is a **solenoid** — the basis of every electromagnet.' },
      { k: 'text', md: 'Three things strengthen the field:\n\n1. **More turns** — proportionally\n2. **More current** — proportionally\n3. **An iron core** — up to a thousandfold, because iron gathers and channels the field' },
      { k: 'callout', tone: 'warn', md: 'An iron core **saturates**. Beyond a point, more current barely raises the field — every domain in the iron is already aligned. That is why an electromagnet cannot be strengthened indefinitely, and why every motor has a maximum torque.' },
      { k: 'text', md: 'A current-carrying wire in a magnetic field feels a **force** (the Lorentz force), perpendicular to both the current and the field. That is what turns a motor: the force between the coil current and the permanent magnet field becomes torque.' },
      { k: 'callout', tone: 'tip', md: 'When you cut the current to a coil abruptly, the collapsing field induces a **large voltage spike** — hundreds of volts. That is why every relay and motor needs a **flyback diode**, or the switching transistor dies.' },
    ],
    quiz: [
      { k: 'single', q: 'What creates a magnetic field?', opts: ['Any charge', 'Any moving charge, so any current', 'Only a permanent magnet'], answer: 1, why: 'That is why every current-carrying wire is a magnet, and why electromagnets work.' },
      { k: 'single', q: 'What does the right-hand rule say?', opts: ['Thumb along the current, finger curl gives the field direction', 'The palm gives the field direction', 'It gives the force direction'], answer: 0, why: 'It lets you work out which way the field runs around a wire, from memory.' },
      { k: 'single', q: 'What strengthens an electromagnet the most?', opts: ['Thicker wire', 'An iron core', 'Longer wire'], answer: 1, why: 'Iron can raise the field a thousandfold, because it gathers and channels it.' },
      { k: 'single', q: 'What does core saturation mean?', opts: ['It heats up', 'Beyond a point, more current barely raises the field', 'It loses its magnetism'], answer: 1, why: 'Every domain in the iron is already aligned. That is why every motor has a maximum torque.' },
      { k: 'single', q: 'Why does a relay need a flyback diode?', opts: ['To switch faster', 'Because the collapsing field induces a large spike that would destroy the transistor', 'To draw less current'], answer: 1, why: 'Abruptly interrupting a coil current can induce hundreds of volts.' },
    ],
    note: {
      summary: ['A magnetic field forms around every moving charge.', 'Right-hand rule: thumb along the current, finger curl gives the field.', 'A solenoid has a strong, even field inside.', 'Strengthen it with more turns, more current, or an iron core (up to 1000x).', 'An iron core saturates: beyond a point current no longer helps.', 'The Lorentz force is perpendicular to current and field — that turns the motor.', 'Always fit a flyback diode beside a coil.'],
      terms: [{ term: 'solenoid', def: 'A coil with an even magnetic field inside.' }, { term: 'saturation', def: 'The core state where the field no longer grows.' }, { term: 'flyback diode', def: 'A diode across a coil that absorbs the switch-off spike.' }],
    },
  },
];
