import type { Day } from '../../types';

/** PHYSICS track, days 20-26. */
export const physicsEnE: Day[] = [
  {
    day: 20,
    title: 'Electromagnetism',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Electricity and magnetism are **two sides of the same phenomenon**. Maxwell described it, and every motor, generator and transformer follows from it.' },
      { k: 'callout', tone: 'key', md: 'The two basic relations:\n\n1. **A moving charge creates a magnetic field.** That is why every current-carrying wire is a magnet.\n2. **A changing magnetic field induces a current.** That is why generators and transformers work.\n\nThe key word is **change**: a steady field induces nothing.' },
      { k: 'text', md: '**Faraday law** says the induced voltage is proportional to the rate of change of magnetic flux:\n\n`U = -N · ΔΦ / Δt`\n\nwhere `N` is the turn count and `Φ` the flux. The minus sign is **Lenz law**: the induced current always opposes the change that created it.' },
      { k: 'callout', tone: 'tip', md: 'Lenz law made visible: drop a strong magnet through a copper tube. It falls slowly, as if through honey. The motion induces a current in the tube, and the field of that current brakes the magnet. Conservation of energy: if it accelerated it, you would have a perpetual motion machine.' },
      { k: 'text', md: 'Three practical consequences:\n\n- **Transformer** — two coils on a shared iron core. Voltage changes in the ratio of the turns; power (minus losses) stays.\n- **Eddy current** — induced current circulating in solid metal. Useful for braking, a loss in a transformer; that is why cores are laminated.\n- **Induction heating** — eddy currents heat; that is how an induction hob works.' },
      { k: 'callout', tone: 'warn', md: 'A transformer **only works on alternating current**, because a steady field induces nothing. Direct current cannot be transformed — which is why alternating current won the grid distribution argument.' },
    ],
    quiz: [
      { k: 'single', q: 'What induces a voltage?', opts: ['A steady magnetic field', 'A changing magnetic field', 'Any magnet'], answer: 1, why: 'The key word is change. A steady field drives no induced current.' },
      { k: 'single', q: 'What does Lenz law say?', opts: ['The induced current reinforces the change', 'The induced current opposes the change that created it', 'There is no relation'], answer: 1, why: 'It follows from conservation of energy: reinforcement would be perpetual motion.' },
      { k: 'single', q: 'Why does a magnet fall slowly through a copper tube?', opts: ['Friction', 'The field of the induced current brakes it', 'Air resistance'], answer: 1, why: 'The motion induces a current, and by Lenz law that current opposes the motion.' },
      { k: 'single', q: 'Why is a transformer core laminated?', opts: ['It is cheaper', 'To reduce eddy current losses', 'It is lighter'], answer: 1, why: 'In solid iron the circulating induced current turns into heat. Laminations break those loops.' },
      { k: 'single', q: 'Why can direct current not be transformed?', opts: ['Too strong', 'Because a steady field induces no voltage', 'The coil would melt'], answer: 1, why: 'That is why alternating current won for grid distribution.' },
    ],
    note: {
      summary: ['Electricity and magnetism are two sides of one phenomenon.', 'Moving charge creates a field; a changing field induces current.', 'Faraday: `U = -N · ΔΦ / Δt`.', 'Lenz: the induced current opposes the change (conservation of energy).', 'Transformer: voltage changes in the ratio of the turns.', 'Eddy currents: useful for braking, a loss in transformers — hence laminated cores.', 'Direct current cannot be transformed.'],
      terms: [{ term: 'induction', def: 'Voltage arising from a changing magnetic field.' }, { term: 'Lenz law', def: 'The induced current always opposes the change creating it.' }, { term: 'eddy current', def: 'An induced current circulating in a solid conductor.' }],
    },
  },
  {
    day: 21,
    title: 'How a DC motor works',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'The DC motor is the simplest electromechanical converter and the basic building block of every robot. Its operation combines two things you already know.' },
      { k: 'callout', tone: 'key', md: 'A current-carrying wire in a magnetic field feels a force (the **Lorentz force**) perpendicular to both the current and the field. If the wire is a loop that can turn about an axis, that force becomes **torque**.' },
      { k: 'text', md: 'The **commutator** solves the central problem: after half a turn the force would reverse and the motor would stall. The commutator swaps the current direction every half turn, so the torque always acts the same way.' },
      { k: 'code', lang: 'py', src: '# The two basic motor equations\n# Torque:    M = Kt * I\n# Back EMF:  Ue = Ke * omega\n\nKt, Ke, R = 0.05, 0.05, 1.2       # Nm/A, Vs/rad, ohms\nU = 12.0\n\nfor omega in (0, 50, 100, 200):\n    I = (U - Ke*omega) / R\n    M = Kt * I\n    print(f"{omega:3} rad/s -> {I:5.2f} A, {M:5.3f} Nm")\n# 0 -> 10.00 A, 0.500 Nm   (stall torque, maximum current)\n# 200 -> 1.67 A, 0.083 Nm  (high speed, low torque)', explain: 'The key is the **back EMF**: a turning motor is also a generator, and its own voltage reduces the current drawn. That is why a stalled motor draws many times the running current.' },
      { k: 'callout', tone: 'warn', md: 'A **stalled motor** is the commonest failure cause. With the shaft unable to turn there is no back EMF, and the motor draws the full `U/R` current — ten times the running value in the example. The winding can burn out in seconds. Current limiting or a thermal cutout is mandatory.' },
      { k: 'text', md: 'Speed is controlled with **PWM**: you switch the supply on and off rapidly, and the duty cycle sets the average voltage. It beats resistive control because the switch is either fully on or fully off — so it wastes almost no power.' },
      { k: 'callout', tone: 'tip', md: 'A motor **always** needs a flyback diode and usually a capacitor too. The diode absorbs the switch-off voltage spike; the capacitor filters the high-frequency noise from brush sparking.' },
    ],
    quiz: [
      { k: 'single', q: 'What drives a motor?', opts: ['Heat', 'The Lorentz force on a current-carrying wire in a magnetic field', 'Friction'], answer: 1, why: 'The force is perpendicular to current and field; on a turning loop it becomes torque.' },
      { k: 'single', q: 'What is the commutator for?', opts: ['Cooling', 'Swapping the current direction every half turn to keep the torque one-way', 'Measuring speed'], answer: 1, why: 'Without it the motor would stall after half a turn as the force reversed.' },
      { k: 'single', q: 'Why does a stalled motor draw much more current?', opts: ['It is cold', 'Because there is no back EMF to reduce it', 'Its resistance is higher'], answer: 1, why: 'A turning motor is also a generator; stalled, the full `U/R` current flows.' },
      { k: 'single', q: 'What happens to a stalled motor?', opts: ['It stops and draws no current', 'It draws the full `U/R` current and can burn out in seconds', 'It keeps turning slowly'], answer: 1, why: 'Without current limiting or a thermal cutout this is the commonest failure cause.' },
      { k: 'single', q: 'Why is PWM better than resistive control?', opts: ['It is simpler', 'The switch is fully on or fully off, so it wastes almost no power', 'It is quieter'], answer: 1, why: 'A resistor turns the excess into heat; a PWM switch dissipates almost nothing.' },
    ],
    note: {
      summary: ['A motor runs on the Lorentz force: current plus field gives torque.', 'The commutator swaps current direction every half turn.', 'Torque `M = Kt · I`, back EMF `Ue = Ke · omega`.', 'A turning motor acts as a generator and reduces the current drawn.', 'A stalled motor draws the full `U/R` current: current limiting is needed.', 'Control speed with PWM, which wastes almost no power.', 'Always fit a flyback diode and a noise capacitor.'],
      terms: [{ term: 'commutator', def: 'The mechanism reversing current every half turn.' }, { term: 'back EMF', def: 'The turning motor own voltage, which reduces current draw.' }, { term: 'stall', def: 'A non-turning shaft, so maximum current flows.' }],
    },
  },
  {
    day: 22,
    title: 'Generators and induction',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'A generator is **the same machine** as a motor, used in reverse. Turn it and it produces voltage; apply voltage and it turns. That is called reversibility.' },
      { k: 'callout', tone: 'key', md: 'From that follows a very useful trick: **any DC motor can serve as a speed sensor**. Turned, the voltage at its terminals is proportional to the speed (`Ue = Ke · omega`).' },
      { k: 'text', md: '**Regenerative braking** comes from the same place: as the robot slows, the motor becomes a generator and returns energy to the battery. In an electric car this recovers twenty to thirty percent of urban driving energy.' },
      { k: 'code', lang: 'py', src: '# How much voltage does the motor give as a generator?\nKe = 0.05            # Vs/rad\n\nfor rpm in (100, 500, 1000, 3000):\n    omega = rpm * 2*3.14159 / 60\n    print(f"{rpm:4} rpm -> {Ke*omega:5.2f} V")\n# 100 -> 0.52 V   500 -> 2.62 V   1000 -> 5.24 V   3000 -> 15.71 V', explain: 'Note that at 3000 rpm the 12 volt motor produces 15.7 volts. That is how a robot rolling downhill can **overvolt** its own controller.' },
      { k: 'callout', tone: 'warn', md: '**Generator overvoltage** is a real hazard. If the robot rolls down a slope or decelerates hard, the motors feed back and the supply can rise above the controller tolerance. The remedy: a **brake resistor** (brake chopper) or a charging circuit that absorbs it.' },
      { k: 'text', md: 'An AC generator works on the same principle without a commutator: a sinusoidally alternating voltage arises in the rotating coil. Mains at 50 Hz means exactly that — the turbine sweeps through the corresponding angle fifty times a second.' },
    ],
    quiz: [
      { k: 'single', q: 'How do a motor and a generator relate?', opts: ['Two different machines', 'The same machine used in reverse', 'A generator is more complex'], answer: 1, why: 'That is reversibility: turned it gives voltage, powered it turns.' },
      { k: 'single', q: 'How can a motor act as a speed sensor?', opts: ['Measure its current', 'The voltage at its terminals is proportional to speed', 'Measure its temperature'], answer: 1, why: '`Ue = Ke · omega`. Every motor contains a free sensor.' },
      { k: 'single', q: 'What is regenerative braking?', opts: ['Friction braking', 'The motor acts as a generator and returns energy to the battery', 'Engine braking'], answer: 1, why: 'In an electric car it recovers twenty to thirty percent of urban driving energy.' },
      { k: 'single', q: 'Why is a robot rolling downhill a hazard for the controller?', opts: ['It overheats', 'The motors feed back and the supply can exceed the tolerance', 'It drains the battery'], answer: 1, why: 'The remedy is a brake resistor or an absorbing charge circuit.' },
      { k: 'single', q: 'What does mains 50 Hz mean?', opts: ['50 volts', 'The generator produces fifty full sine cycles per second', '50 amps'], answer: 1, why: 'A sinusoidally alternating voltage arises in the rotating coil.' },
    ],
    note: {
      summary: ['A generator and a motor are the same machine used in reverse.', 'Any DC motor can act as a speed sensor.', 'Regenerative braking returns energy to the battery.', 'At high speed a motor produces more than its rated voltage.', 'Against generator overvoltage: a brake resistor or absorbing charger.', 'An AC generator is the same without a commutator.'],
      terms: [{ term: 'reversibility', def: 'The same machine working as motor and generator.' }, { term: 'regenerative braking', def: 'Braking that returns the energy.' }, { term: 'brake resistor', def: 'A resistor converting fed-back energy into heat.' }],
    },
  },
  {
    day: 23,
    title: 'Efficiency',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Efficiency** is the ratio of useful output to input power. It is never 100 percent, and the difference always becomes **heat**.' },
      { k: 'callout', tone: 'key', md: '`eta = P_useful / P_input`\n\nThe efficiency of a chain is the **product** of its stages, not their average. That is the key practical consequence: four stages at 90 percent come to only 66 percent.' },
      { k: 'code', lang: 'py', src: 'chain = {\n    "battery discharge": 0.95,\n    "motor driver":      0.90,\n    "motor":             0.80,\n    "gearbox":           0.85,\n    "wheel to ground":   0.90,\n}\n\neta = 1.0\nfor name, e in chain.items():\n    eta *= e\n    print(f"{name:20} {e:.2f} -> cumulative {eta:.3f}")\nprint(f"\\nOverall efficiency: {eta*100:.1f}%")\n# Overall efficiency: 52.3%', explain: 'Five reasonable-looking stages come to 52 percent. Half the input energy becomes heat — that is what you must size the cooling for.' },
      { k: 'text', md: 'Typical efficiencies:\n\n- **DC motor** — 70 to 90 percent, depending on load\n- **Gear train** — 95 to 98 percent per stage\n- **Worm gear** — 40 to 70 percent, but self-locking\n- **Li-ion battery** — above 95 percent\n- **Linear voltage regulator** — the voltage ratio; 12 V to 5 V is only 42 percent!\n- **Switching power supply** — 85 to 95 percent' },
      { k: 'callout', tone: 'warn', md: 'Motor efficiency depends **strongly on load**. It peaks near the rated load and is zero both at no load and at stall. An oversized motor running lightly loaded wastes energy — bigger is not better.' },
      { k: 'callout', tone: 'tip', md: 'Swapping a linear regulator for a switching one is often the single biggest easy win in a robot. Converting 12 V to 5 V, the linear one turns 58 percent of the input into heat — the switching one only 10 percent.' },
    ],
    quiz: [
      { k: 'single', q: 'How does the efficiency of a chain combine?', opts: ['The average of the stages', 'The product of the stage efficiencies', 'The smallest stage'], answer: 1, why: 'Four stages at 90 percent come to only 66 percent.' },
      { k: 'single', q: 'Where does the missing energy go?', opts: ['It vanishes', 'It becomes heat', 'Back into the battery'], answer: 1, why: 'That is why cooling requirements are computed from efficiency.' },
      { k: 'single', q: 'What is the efficiency of a linear regulator from 12 V to 5 V?', opts: ['90 percent', 'About 42 percent', '100 percent'], answer: 1, why: 'The voltage ratio, 5/12. The difference becomes heat entirely.' },
      { k: 'single', q: 'When is motor efficiency best?', opts: ['At no load', 'Near the rated load', 'At stall'], answer: 1, why: 'It is zero both at no load and at stall.' },
      { k: 'single', q: 'Why is an oversized motor a bad idea?', opts: ['It costs more', 'Lightly loaded it runs at poor efficiency and wastes energy', 'It is heavier'], answer: 1, why: 'Efficiency peaks near the rated load — bigger is not better.' },
    ],
    note: {
      summary: ['`eta = P_useful / P_input`; the difference always becomes heat.', 'A chain efficiency is the product of its stages, not the average.', 'Five stages at 80-95 percent come to only 52 percent.', 'A linear regulator from 12 V to 5 V is only 42 percent.', 'Motor efficiency is best near the rated load.', 'A switching supply is the biggest easy win.'],
      terms: [{ term: 'efficiency', def: 'The ratio of useful output to input power.' }, { term: 'linear regulator', def: 'A regulator converting the excess into heat.' }, { term: 'switching supply', def: 'A high-efficiency converter working by switching.' }],
    },
  },
  {
    day: 24,
    title: 'Thermodynamics basics',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Temperature** is not the same as **heat**. Temperature is the average kinetic energy of the particles; heat is the quantity of energy transferred.' },
      { k: 'callout', tone: 'key', md: 'The energy needed to warm something:\n\n`Q = m · c · ΔT`\n\nwhere `m` is mass, `c` the specific heat and `ΔT` the temperature change. Water has a specific heat of 4186 J/(kg·K) — remarkably high, which is why it is such a good coolant.' },
      { k: 'code', lang: 'py', src: '# How much does an aluminium heatsink warm up?\nc_alu = 900          # J/(kg*K)\nm = 0.05             # kg, 50 grams\nP = 5.0              # W dissipated\nt = 60               # s\n\ndT = (P * t) / (m * c_alu)\nprint(f"{dT:.1f} K rise in one minute")   # 6.7 K', explain: 'Without cooling the sink warms nearly 7 degrees a minute. That is 67 degrees in ten minutes — mass alone is not enough, you need airflow.' },
      { k: 'text', md: 'Three modes of heat transfer:\n\n- **Conduction** — within material, by contact. Metal conducts well, plastic badly.\n- **Convection** — by moving liquid or gas. A fan accelerates this.\n- **Radiation** — by electromagnetic waves, even through vacuum. Significant only at high temperature.' },
      { k: 'callout', tone: 'warn', md: 'Inside a sealed box a heatsink **achieves nothing on its own**. It carries heat away from the chip, but the heat stays inside the box. The heat must **get out**: a vent, a fan, or a thermal path to the enclosure wall that cools from outside.' },
      { k: 'callout', tone: 'tip', md: 'Most electronic components are safe to **85 degrees**, but batteries age rapidly above **45 degrees**. In thermal design the battery is the bottleneck, not the processor — keep it away from the motors and the driver.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the difference between heat and temperature?', opts: ['None', 'Temperature is the average kinetic energy, heat is the energy transferred', 'Heat is colder'], answer: 1, why: 'A mug of hot water and a bath of warm water: the bath holds more heat, the mug has the higher temperature.' },
      { k: 'single', q: 'What does `Q = m · c · ΔT` give?', opts: ['The temperature', 'The energy needed to warm something', 'The efficiency'], answer: 1, why: 'Water has a remarkably high specific heat (4186 J/kg·K), hence its use as a coolant.' },
      { k: 'single', q: 'What are the three modes of heat transfer?', opts: ['Conduction, convection, radiation', 'Conduction, pressure, scattering', 'Convection, light, sound'], answer: 0, why: 'Radiation matters only at high temperature; in a robot conduction and convection dominate.' },
      { k: 'single', q: 'Why is a heatsink not enough in a sealed box?', opts: ['It is too small', 'Because the heat stays in the box: it has to get out', 'It is the wrong material'], answer: 1, why: 'You need a vent, a fan, or a thermal path to an externally cooled wall.' },
      { k: 'single', q: 'What is the bottleneck in thermal design?', opts: ['The processor', 'The battery, which ages fast above 45 degrees', 'The motor'], answer: 1, why: 'Electronics are typically safe to 85 degrees. Keep the battery away from the motors.' },
    ],
    note: {
      summary: ['Temperature is average kinetic energy; heat is energy transferred.', '`Q = m · c · ΔT`; water has a remarkably high specific heat.', 'Heat transfer: conduction, convection, radiation.', 'In a sealed box a heatsink alone is useless: the heat must get out.', 'Electronics last to 85 degrees, batteries age above 45.'],
      terms: [{ term: 'specific heat', def: 'Energy needed to warm one kilogram by one degree.' }, { term: 'convection', def: 'Heat transfer by moving gas or liquid.' }, { term: 'heatsink', def: 'A large-area metal part passing heat to the surroundings.' }],
    },
  },
  {
    day: 25,
    title: 'Thermal conduction and cooling',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Designing cooling is the same calculation as a circuit — only here **heat** is the current, **temperature difference** is the voltage, and **thermal resistance** is the resistance.' },
      { k: 'callout', tone: 'key', md: 'The thermal Ohm law:\n\n`ΔT = P · R_th`\n\nwhere `P` is the dissipated power in watts and `R_th` the thermal resistance in K/W. Thermal resistances **add in series** exactly like electrical ones.' },
      { k: 'code', lang: 'py', src: '# Can a 3 watt chip survive on this cooling?\nR_die_case  = 1.5       # K/W\nR_case_sink = 0.5       # K/W, with thermal paste\nR_sink_air  = 8.0       # K/W, a small passive sink\n\nR_total = R_die_case + R_case_sink + R_sink_air\nP = 3.0\nT_ambient = 25\n\nprint(f"R_total = {R_total} K/W")\nprint(f"Die temperature: {T_ambient + P*R_total:.0f} C")\n# R_total = 10.0 K/W -> 55 C. Fine, but 5 W would give 75 C.', explain: 'The largest term decides: the 8 K/W sink-to-air step dominates the chain. A fan can cut it to 2 K/W.' },
      { k: 'text', md: 'Where can you gain the most?\n\n- **Thermal paste or pad** — an air gap insulates; without paste the case-to-sink step can be ten times worse\n- **More sink area** — a finned design, not a solid block\n- **A fan** — cuts the sink-to-air resistance to a quarter or a fifth\n- **A thermal bridge to the enclosure** — the metal case becomes the heatsink' },
      { k: 'callout', tone: 'warn', md: '**Thermal paste is not glue and does not cool**: it only fills the microscopic air gaps. Apply it thinly and evenly. A thick layer makes conduction **worse**, because paste is a far poorer conductor than metal-to-metal contact.' },
      { k: 'callout', tone: 'tip', md: 'Measuring is easier than calculating. Stick a cheap thermometer or an NTC resistor on the hottest component and run the robot at full load for ten minutes. Reality always tells you more than a table.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the thermal Ohm law?', opts: ['`ΔT = P · R_th`', '`P = U · I`', '`Q = m · c · ΔT`'], answer: 0, why: 'Heat is the current, temperature difference the voltage, thermal resistance the resistance.' },
      { k: 'single', q: 'How do thermal resistances combine in a chain?', opts: ['They multiply', 'They add in series, like electrical ones', 'Only the largest counts'], answer: 1, why: 'That is why the largest term dominates: usually the sink-to-air step.' },
      { k: 'single', q: 'What is thermal paste for?', opts: ['Gluing', 'Filling the microscopic air gaps', 'Cooling'], answer: 1, why: 'Air insulates. The paste does not cool, it only fills the gaps.' },
      { k: 'single', q: 'What happens with too thick a paste layer?', opts: ['Better cooling', 'Worse conduction, because paste conducts worse than metal', 'Nothing'], answer: 1, why: 'Apply it thinly and evenly.' },
      { k: 'single', q: 'By how much does a fan cut sink-to-air resistance?', opts: ['Barely', 'To a quarter or a fifth', 'It doubles it'], answer: 1, why: 'It is the largest term in the chain, so that is where most can be gained.' },
    ],
    note: {
      summary: ['Thermal Ohm law: `ΔT = P · R_th`.', 'Thermal resistances add in series; the largest term decides.', 'Thermal paste fills air gaps; apply it thinly.', 'A fan cuts sink-to-air resistance to a quarter or a fifth.', 'A metal enclosure can itself be the heatsink.', 'Measure rather than only calculate: a thermometer on the hottest part.'],
      terms: [{ term: 'thermal resistance', def: 'A K/W figure: how much it warms per watt.' }, { term: 'thermal paste', def: 'A conductive compound filling air gaps.' }, { term: 'thermal bridge', def: 'A deliberate conduction path from source to cooling surface.' }],
    },
  },
  {
    day: 26,
    title: 'Strength of materials',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A part is good when it **does not break** and **does not bend too much**. Those are two separate requirements, and the second is often the stricter one.' },
      { k: 'callout', tone: 'key', md: 'Two basic quantities:\n\n- **Stress** (`sigma = F / A`) — force divided by cross-section, in pascals. This decides whether it breaks.\n- **Strain** (`epsilon = ΔL / L`) — the relative change in length, dimensionless.\n\nThe **elastic modulus** connects them: `sigma = E · epsilon` (Hooke law).' },
      { k: 'text', md: 'Typical values:\n\n| Material | E (GPa) | Yield (MPa) |\n|---|---|---|\n| Steel | 200 | 250–900 |\n| Aluminium | 70 | 100–500 |\n| PLA (printed) | 3.5 | 50 |\n| PETG | 2.0 | 50 |\n| Carbon fibre composite | 70–200 | 600+ |' },
      { k: 'callout', tone: 'warn', md: 'The elastic modulus of aluminium is **a third** of steel. An identically shaped aluminium part bends three times as much, even if it does not break. That is why you cannot swap a steel part for aluminium one-for-one — the geometry has to change too.' },
      { k: 'text', md: 'Bending stiffness is not proportional to **cross-section** but to the **second moment of area**. For a rectangle that is `b·h³/12` — height counts **cubically**. That is why a plank on edge is far stiffer than one laid flat.' },
      { k: 'callout', tone: 'tip', md: 'From that comes the main trick of lightweight design: **move the material away from the centreline**. A tube is nearly as stiff as a solid rod of the same diameter at a fraction of the mass. That is why bicycle frames are tubes and beams are I-shaped.' },
      { k: 'callout', tone: 'warn', md: 'A **3D-printed part is weakest between layers**: layer adhesion is often half the in-layer strength. Always orient the part so the load acts **in the plane** of the layers rather than pulling them apart.' },
    ],
    quiz: [
      { k: 'single', q: 'What is stress (sigma)?', opts: ['Force divided by cross-section', 'The change in length', 'The energy'], answer: 0, why: 'Measured in pascals. It decides whether the material breaks.' },
      { k: 'single', q: 'What does Hooke law say?', opts: ['`sigma = E · epsilon`', '`F = m · a`', '`Q = m · c · ΔT`'], answer: 0, why: 'Stress is proportional to strain, with the elastic modulus as the constant.' },
      { k: 'single', q: 'How much more does an identical aluminium part bend than steel?', opts: ['The same', 'About three times as much', 'Half as much'], answer: 1, why: 'Aluminium has E = 70 GPa, steel 200 GPa.' },
      { k: 'single', q: 'How does bending stiffness depend on height?', opts: ['Linearly', 'With the cube', 'With the square root'], answer: 1, why: 'The second moment of area is `b·h³/12`. That is why a plank on edge is stiffer.' },
      { k: 'single', q: 'How should you orient a 3D-printed part?', opts: ['It does not matter', 'So the load acts in the plane of the layers', 'Always vertically'], answer: 1, why: 'Layer adhesion is often half the in-layer strength.' },
    ],
    note: {
      summary: ['Two requirements: do not break, do not bend too much.', 'Stress `sigma = F/A`, strain `epsilon = ΔL/L`.', 'Hooke: `sigma = E · epsilon`.', 'Aluminium E is a third of steel: it bends three times as much.', 'Bending stiffness grows with the cube of the height.', 'Move material away from the centreline: tubes, I-beams.', 'Orient printed parts so load acts in the plane of the layers.'],
      terms: [{ term: 'elastic modulus (E)', def: 'A number characterising material stiffness, in GPa.' }, { term: 'yield strength', def: 'The stress above which deformation becomes permanent.' }, { term: 'second moment of area', def: 'Bending stiffness arising from the cross-section shape.' }],
    },
  },
];
