import type { Day } from '../../types';

/** ROBOTICS track, days 20-26. */
export const roboticsEnE: Day[] = [
  {
    day: 20,
    title: 'Mapping basics',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A reactive robot gets stuck in a corner because it has no memory. A **map** gives it one: it stores what it has seen, and from that it can plan.' },
      { k: 'callout', tone: 'key', md: 'The commonest representation is the **occupancy grid**: divide the space into cells, each holding the probability that an obstacle is there. 0 = certainly free, 1 = certainly occupied, 0.5 = unknown.' },
      { k: 'code', lang: 'py', src: 'CELL = 5.0           # cm, the size of one cell\nWIDE, HIGH = 100, 100\ngrid = [[0.5]*WIDE for _ in range(HIGH)]      # everything unknown at first\n\ndef update(cx, cy, occupied):\n    p = grid[cy][cx]\n    grid[cy][cx] = min(0.95, p + 0.2) if occupied else max(0.05, p - 0.1)', explain: 'Gradual updating handles sensor noise: one false reading does not flip a cell. The 0.05 and 0.95 clamps leave room for later correction.' },
      { k: 'text', md: 'Cell size is the key decision. **Small cells**: accurate, but memory hungry and slow to plan on. **Large cells**: fast, but the robot cannot pass a narrow gap because the grid calls it occupied. A practical rule: make a cell about half the robot width.' },
      { k: 'callout', tone: 'warn', md: '**Odometry drifts**: a wheel spins, the carpet is soft, and after a hundred steps the robot no longer believes it is where it is. A map built from a wrong pose is useless: the same wall goes in twice, offset.' },
      { k: 'text', md: 'That is why mapping and localization go together. **SLAM** (Simultaneous Localization and Mapping) solves both at once: it refines the pose from the map and the map from the pose. It is one of the central problems in robotics.' },
    ],
    quiz: [
      { k: 'single', q: 'What is an occupancy grid?', opts: ['The robot path', 'Space divided into cells, each with an obstacle probability', 'A photograph'], answer: 1, why: '0 = free, 1 = occupied, 0.5 = unknown. It is the standard map representation.' },
      { k: 'single', q: 'Why update cells gradually?', opts: ['It is faster', 'So one false reading does not flip a cell', 'Less memory'], answer: 1, why: 'Sensor noise averages out over several readings.' },
      { k: 'single', q: 'What is wrong with too large a cell size?', opts: ['Memory use', 'The robot cannot pass a narrow gap the grid calls occupied', 'Slowness'], answer: 1, why: 'Make a cell about half the robot width.' },
      { k: 'single', q: 'Why is a map built from a wrong pose useless?', opts: ['Too large', 'The same wall goes in twice, offset', 'Too few cells'], answer: 1, why: 'Odometry drift means the robot does not believe it is where it is.' },
      { k: 'single', q: 'What does SLAM solve?', opts: ['Only mapping', 'Mapping and localization at the same time', 'Only path planning'], answer: 1, why: 'It refines the pose from the map and the map from the pose.' },
    ],
    note: {
      summary: ['A map gives the robot the memory that reactive control lacks.', 'Occupancy grid: an obstacle probability per cell.', 'Update gradually so sensor noise averages out.', 'Make a cell about half the robot width.', 'Odometry drifts; a map built from a wrong pose is useless.', 'SLAM solves mapping and localization together.'],
      terms: [{ term: 'occupancy grid', def: 'A cell-based map holding obstacle probabilities.' }, { term: 'odometry', def: 'Estimating distance travelled from wheel rotations.' }, { term: 'SLAM', def: 'Simultaneous localization and mapping.' }],
    },
  },
  {
    day: 21,
    title: 'Localization',
    minutes: 24,
    lesson: [
      { k: 'text', md: '**Localization** asks: where am I on the map? It is not trivial, because every sensor is imprecise and the errors accumulate.' },
      { k: 'text', md: 'Three sources of information, each with a different error:\n\n- **Odometry** — wheel rotations. Accurate in the short term, but its error **accumulates**.\n- **IMU** (accelerometer and gyroscope) — fast, but **drifts** within minutes.\n- **Range sensor or camera** — absolute, but noisy and slow.' },
      { k: 'callout', tone: 'key', md: 'The answer is **sensor fusion**: odometry supplies the continuous estimate, and range measurements **correct** it periodically. Neither suffices alone; together they are accurate.' },
      { k: 'text', md: 'The **particle filter** is the intuitive method:\n\n1. Scatter several hundred "guesses" (particles) over the map, each a possible pose.\n2. On movement, shift them all by the odometry, with a little random noise.\n3. On a measurement, give each a **weight**: how well the reading matches what should be visible from there.\n4. **Resample**: high-weight particles multiply, low-weight ones disappear.' },
      { k: 'callout', tone: 'tip', md: 'The beauty of a particle filter is that it **keeps several hypotheses alive**. In a symmetric corridor two clouds survive at first, and it only resolves once the robot reaches a distinguishing feature.' },
      { k: 'callout', tone: 'warn', md: 'The **kidnapped robot** problem: if someone picks the robot up and moves it, every particle is in the wrong place and the filter never recovers. The remedy: keep a few percent of particles **randomly scattered** so they can pick the trail back up.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the main error of odometry?', opts: ['Noise', 'Its error accumulates', 'Slowness'], answer: 1, why: 'Accurate short term, but slip and wheel spin add up.' },
      { k: 'single', q: 'What is sensor fusion in localization?', opts: ['Several identical sensors', 'Odometry gives the continuous estimate, range measurements correct it', 'Averaging'], answer: 1, why: 'No single source suffices, but their errors are different in kind.' },
      { k: 'single', q: 'What does a particle filter do when resampling?', opts: ['Deletes everything', 'High-weight particles multiply, low-weight ones disappear', 'Redraws the map'], answer: 1, why: 'The cloud condenses around the likely poses.' },
      { k: 'single', q: 'What is the advantage of a particle filter over plain averaging?', opts: ['Speed', 'It keeps several hypotheses alive at once', 'Less memory'], answer: 1, why: 'In a symmetric corridor two clouds survive until a distinguishing feature resolves them.' },
      { k: 'single', q: 'What is the remedy for the kidnapped robot problem?', opts: ['More sensors', 'A few percent of randomly scattered particles', 'Moving slower'], answer: 1, why: 'They can pick the trail back up when every existing particle is wrong.' },
    ],
    note: {
      summary: ['Localization: where am I on the map?', 'Odometry accumulates error, the IMU drifts, range sensing is noisy.', 'Sensor fusion: continuous estimate plus periodic correction.', 'Particle filter: many guesses, weighting by measurement, resampling.', 'Its main advantage is keeping several hypotheses alive.', 'Keep random particles against the kidnapped robot problem.'],
      terms: [{ term: 'localization', def: 'Determining the robot pose on a known map.' }, { term: 'particle filter', def: 'An estimator weighting many possible poses.' }, { term: 'drift', def: 'The slow degradation of an IMU estimate over time.' }],
    },
  },
  {
    day: 22,
    title: 'Grid path planning',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'With a map and a known pose comes the question: **how do I get from A to B**? On a grid map that is a graph search problem.' },
      { k: 'callout', tone: 'key', md: 'A grid is a **graph**: every free cell is a node, with edges to its neighbours. Four neighbours (up, down, left, right) or eight (including diagonals). With eight, a diagonal costs 1.41, not 1.' },
      { k: 'text', md: '**Breadth-first search** (BFS) is the simplest: it expands outward in rings from the start, and the first path found is the shortest — as long as every step costs the same.' },
      { k: 'code', lang: 'py', src: 'from collections import deque\n\ndef bfs(grid, start, goal):\n    queue = deque([start])\n    came_from = {start: None}\n    while queue:\n        p = queue.popleft()\n        if p == goal:\n            break\n        for n in neighbours(grid, p):\n            if n not in came_from:\n                came_from[n] = p\n                queue.append(n)\n    return path(came_from, goal)', explain: 'The `came_from` dictionary does double duty: it records the path **and** marks a cell as visited. Without that the search would go round in circles.' },
      { k: 'callout', tone: 'warn', md: 'When cells have **different costs** (grass is slower than asphalt) BFS no longer gives the shortest path. Then you need **Dijkstra**: a priority queue, always expanding the cheapest-reached node.' },
      { k: 'text', md: 'One practical step many people skip: **inflate the obstacles** by the robot radius (this is called configuration space). You can then plan for a point robot, and the path found is guaranteed to fit.' },
      { k: 'callout', tone: 'tip', md: 'A raw grid path is staircase-shaped. **Smooth it**: if a straight line between two distant points is clear, drop the intermediate ones. The robot then moves continuously instead of zigzagging.' },
    ],
    quiz: [
      { k: 'single', q: 'How does a grid become a graph?', opts: ['Every free cell is a node with edges to neighbours', 'Every wall is a node', 'The corners are the nodes'], answer: 0, why: 'Four or eight neighbours; with eight a diagonal costs 1.41.' },
      { k: 'single', q: 'When does BFS give the shortest path?', opts: ['Always', 'When every step costs the same', 'Never'], answer: 1, why: 'With different costs you need Dijkstra and a priority queue.' },
      { k: 'single', q: 'What is the double duty of the `came_from` dictionary?', opts: ['It records the path and marks cells as visited', 'It counts steps', 'It stores the cost'], answer: 0, why: 'Without it the search would revisit the same cells in a loop.' },
      { k: 'single', q: 'Why inflate the obstacles?', opts: ['It looks better', 'So you can plan for a point robot and the path is guaranteed to fit', 'For speed'], answer: 1, why: 'That is configuration space: obstacles grown by the robot radius.' },
      { k: 'single', q: 'Why smooth a grid path?', opts: ['Shorter code', 'Because the raw path is staircase-shaped and the robot would zigzag', 'Less memory'], answer: 1, why: 'If a straight line between two distant points is clear, the intermediate points can go.' },
    ],
    note: {
      summary: ['A grid is a graph: free cells are nodes, adjacency gives edges.', 'With eight neighbours a diagonal costs 1.41.', 'BFS gives the shortest path when every step costs the same.', 'Different costs need Dijkstra with a priority queue.', 'Inflate obstacles by the robot radius (configuration space).', 'Smooth the path or the robot will zigzag.'],
      terms: [{ term: 'BFS', def: 'Breadth-first search: ring-by-ring graph traversal.' }, { term: 'Dijkstra', def: 'A cheapest-path algorithm for varying edge costs.' }, { term: 'configuration space', def: 'An obstacle map inflated by the robot radius.' }],
    },
  },
  {
    day: 23,
    title: 'The A* algorithm',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'Dijkstra expands equally in every direction — even when the goal is clearly to the right. **A*** improves on that: it guesses where it is worth looking.' },
      { k: 'callout', tone: 'key', md: 'A* ranks every node by:\n\n`f(n) = g(n) + h(n)`\n\n- **g(n)** — the **actual** cost from the start\n- **h(n)** — the **estimated** remaining cost to the goal (the heuristic)\n\nIt always expands the node with the smallest `f`.' },
      { k: 'code', lang: 'py', src: 'import heapq\n\ndef heur(a, b):            # Manhattan distance for four neighbours\n    return abs(a[0]-b[0]) + abs(a[1]-b[1])\n\ndef astar(grid, start, goal):\n    open_set = [(heur(start, goal), 0, start)]\n    g = {start: 0}\n    came_from = {start: None}\n    while open_set:\n        _, gp, p = heapq.heappop(open_set)\n        if p == goal:\n            return path(came_from, goal)\n        for n in neighbours(grid, p):\n            new = gp + 1\n            if new < g.get(n, float("inf")):\n                g[n] = new\n                came_from[n] = p\n                heapq.heappush(open_set, (new + heur(n, goal), new, n))\n    return None', explain: 'The heap (`heapq`) always returns the smallest `f`. The `new < g.get(...)` condition allows a node to be rediscovered along a cheaper route.' },
      { k: 'callout', tone: 'warn', md: 'The heuristic must be **admissible**: it must never **overestimate** the remaining cost. If it overestimates, A* gets faster but no longer guarantees the shortest path. Use Manhattan distance for four neighbours and Chebyshev distance for eight.' },
      { k: 'text', md: 'Two extreme cases illuminate how it works:\n\n- With `h(n) = 0`, A* **is exactly Dijkstra**.\n- With a perfect `h(n)`, A* walks straight to the goal with no detour.\n\nIn practice it sits in between: it examines far fewer cells than Dijkstra and returns the same optimal path.' },
      { k: 'callout', tone: 'tip', md: 'When the map changes mid-run (a new obstacle appears), do not replan from scratch. The **D* Lite** algorithm recomputes only the affected part — on a moving robot that is an order-of-magnitude difference.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the A* ranking formula?', opts: ['`f = g`', '`f = g + h`', '`f = h`'], answer: 1, why: 'The actual cost travelled plus the estimated cost remaining.' },
      { k: 'single', q: 'What does an admissible heuristic mean?', opts: ['It is fast', 'It never overestimates the remaining cost', 'It is always exact'], answer: 1, why: 'Overestimating makes A* faster but loses the shortest-path guarantee.' },
      { k: 'single', q: 'What happens when `h(n) = 0`?', opts: ['It finds no path', 'A* becomes exactly Dijkstra', 'It loops forever'], answer: 1, why: 'With no heuristic it expands equally in every direction.' },
      { k: 'single', q: 'Which heuristic suits four neighbours?', opts: ['Euclidean distance', 'Manhattan distance', 'Zero'], answer: 1, why: 'Without diagonals, Manhattan distance is exact and never overestimates.' },
      { k: 'single', q: 'What does D* Lite add over A*?', opts: ['A shorter path', 'On a changing map it recomputes only the affected part', 'Less memory'], answer: 1, why: 'On a moving robot where new obstacles appear, that is an order-of-magnitude speedup.' },
    ],
    note: {
      summary: ['A* ranking: `f(n) = g(n) + h(n)`.', 'g is the actual cost travelled, h the estimated cost remaining.', 'The heuristic must be admissible: never overestimate.', 'Manhattan distance for four neighbours, Chebyshev for eight.', 'With `h = 0` A* degenerates into Dijkstra.', 'For a changing map use D* Lite, which recomputes only the affected part.'],
      terms: [{ term: 'heuristic', def: 'An estimate of the remaining cost.' }, { term: 'admissible heuristic', def: 'An estimate never greater than the true cost.' }, { term: 'D* Lite', def: 'A replanning path algorithm for changing maps.' }],
    },
  },
  {
    day: 24,
    title: 'State machines',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'Robot behaviour quickly becomes a thicket of branches. A **state machine** tidies that up: the robot is always in exactly **one** state and switches by clear rules.' },
      { k: 'code', lang: 'py', src: 'SEARCH, APPROACH, GRASP, CARRY, CHARGE = range(5)\nstate = SEARCH\n\nwhile True:\n    if state == SEARCH:\n        rotate()\n        if object_visible(): state = APPROACH\n    elif state == APPROACH:\n        drive_to_target()\n        if arrived():        state = GRASP\n        if not object_visible(): state = SEARCH\n    elif state == GRASP:\n        if gripper_closed():  state = CARRY\n\n    if battery() < 15:        state = CHARGE      # from anywhere', explain: 'The battery check sits **outside** the state machine, so it applies from every state. That is the usual pattern for safety and emergency transitions.' },
      { k: 'callout', tone: 'key', md: 'Three questions to answer for every state:\n\n1. **What does** the robot do in this state?\n2. **When does it leave**, and for where?\n3. **What happens on entry and exit** (opening the gripper, say)?' },
      { k: 'callout', tone: 'warn', md: 'The commonest bug is the **stuck state**: a situation with no transition out. Draw the machine and ask at every state: *what if the expected event never arrives?* The answer is usually a timeout.' },
      { k: 'text', md: 'A **hierarchical state machine** scales further: states contain states. Inside a `CARRY` super-state there can be `DRIVE`, `AVOID` and `DROP` sub-states — and interrupting the super-state closes all of them.' },
      { k: 'callout', tone: 'tip', md: 'Log **every transition** with its reason: "APPROACH → SEARCH (object lost)". When the robot behaves oddly, that log tells you what it believed about itself.' },
    ],
    quiz: [
      { k: 'single', q: 'What defines a state machine?', opts: ['It does several things at once', 'The robot is always in exactly one state and switches by rules', 'Random behaviour'], answer: 1, why: 'It tidies behaviour that would otherwise be a thicket of branches.' },
      { k: 'single', q: 'Why does the battery check sit outside the state machine?', opts: ['Speed', 'So it applies from every state', 'So it runs less often'], answer: 1, why: 'That is the standard pattern for safety and emergency transitions.' },
      { k: 'single', q: 'What is a stuck state?', opts: ['A slow state', 'A state with no transition out of it', 'The initial state'], answer: 1, why: 'Ask at every state what happens if the expected event never arrives. Usually the answer is a timeout.' },
      { k: 'single', q: 'What is a hierarchical state machine?', opts: ['Two parallel machines', 'States that contain states', 'A faster state machine'], answer: 1, why: 'Interrupting the super-state closes every sub-state with it.' },
      { k: 'single', q: 'Why log transitions with their reason?', opts: ['It is required', 'Because on odd behaviour it tells you what the robot believed', 'It speeds things up'], answer: 1, why: 'A line like "APPROACH → SEARCH (object lost)" shows the reason for the decision at once.' },
    ],
    note: {
      summary: ['A state machine tidies behaviour: one state at a time.', 'Per state: what it does, when it exits, what happens on entry and exit.', 'Safety transitions (battery) sit outside, applying from every state.', 'Against stuck states: a timeout for every expected event.', 'Hierarchical state machine: states within states.', 'Log every transition with its reason.'],
      terms: [{ term: 'state machine', def: 'A system of finite states and their transitions.' }, { term: 'stuck state', def: 'A state with no transition leading out.' }, { term: 'hierarchical state machine', def: 'A machine whose states contain sub-states.' }],
    },
  },
  {
    day: 25,
    title: 'Behaviour trees',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A state machine works nicely up to about ten states. After that the number of transitions grows quadratically and it becomes unreadable. A **behaviour tree** is the answer.' },
      { k: 'callout', tone: 'key', md: 'Each tick, the nodes of the tree **run once** and return one of three values: **SUCCESS**, **FAILURE** or **RUNNING** (still working). The parent decides what comes next from that.' },
      { k: 'text', md: 'The four node types:\n\n- **Sequence (→)** — left to right. Stops at the first FAILURE. "This **and** this **and** this."\n- **Selector (?)** — left to right. Stops at the first SUCCESS. "This **or** this **or** this."\n- **Decorator** — modifies one child: repeat, invert, time limit.\n- **Leaf** — the actual action or condition.' },
      { k: 'code', lang: 'py', src: '# The tree of a delivery robot (the left branch has priority):\n#\n# ? Selector\n# ├── → Sequence: emergency\n# │    ├── battery < 15?\n# │    └── go and charge\n# ├── → Sequence: delivery\n# │    ├── am I carrying something?\n# │    ├── go to the drop point\n# │    └── put it down\n# └── → Sequence: search\n#      ├── find an object\n#      └── go there and grasp it', explain: 'The top selector gives the **priority**: the emergency branch always runs first. When the battery is fine, that branch returns FAILURE and the selector moves on to delivery.' },
      { k: 'callout', tone: 'tip', md: 'The main advantage of a behaviour tree is **modular extensibility**: a new behaviour is one new branch at the right priority. In a state machine the same change means rewriting the transitions of every existing state.' },
      { k: 'callout', tone: 'warn', md: 'The tree **restarts from the root** on every tick. That is what gives priority (the emergency always gets a say), but it also means a long action must return RUNNING rather than blocking the loop. A blocking leaf kills responsiveness.' },
    ],
    quiz: [
      { k: 'single', q: 'What three values can a node return?', opts: ['True, false, null', 'SUCCESS, FAILURE, RUNNING', 'Start, stop, pause'], answer: 1, why: 'RUNNING means the action is still working and continues on the next tick.' },
      { k: 'single', q: 'What does a sequence (→) node do?', opts: ['Stops at the first SUCCESS', 'Stops at the first FAILURE: "this and this and this"', 'Picks at random'], answer: 1, why: 'Every child must succeed for the sequence to succeed.' },
      { k: 'single', q: 'What does a selector (?) node do?', opts: ['Stops at the first SUCCESS: "this or this or this"', 'Runs them all', 'Stops at the first FAILURE'], answer: 0, why: 'That is how you express priority: the leftmost branch matters most.' },
      { k: 'single', q: 'What is the main advantage over a state machine?', opts: ['Speed', 'A new behaviour is one branch, not a rewrite of every transition', 'Less memory'], answer: 1, why: 'In a state machine the transition count grows quadratically with states.' },
      { k: 'single', q: 'Why must a leaf not block?', opts: ['It is slow', 'Because the tree restarts from the root every tick and blocking kills responsiveness', 'It errors'], answer: 1, why: 'A long action must return RUNNING so the emergency branch can get a say.' },
    ],
    note: {
      summary: ['A behaviour tree answers the scaling problem of state machines.', 'Node results: SUCCESS, FAILURE or RUNNING.', 'Sequence (→) is "and". Selector (?) is "or". Decorators modify, leaves act.', 'The top selector sets the priority order.', 'A new behaviour is a single inserted branch.', 'The tree restarts from the root each tick: a leaf must not block.'],
      terms: [{ term: 'behaviour tree', def: 'A tree-shaped, priority-ordered behaviour controller.' }, { term: 'sequence node', def: 'A node requiring every child to succeed.' }, { term: 'selector node', def: 'A node stopping at the first successful child.' }],
    },
  },
  {
    day: 26,
    title: 'Safety and emergency stop',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A robot that moves can be dangerous. Safety is not a feature added at the end: it is **part of the build**, and usually independent of the software.' },
      { k: 'callout', tone: 'key', md: 'The **emergency stop** (E-stop) is the most important rule: it must work **independently of the software**. A relay or contactor that physically cuts motor power. Rely on software and the one thing that will not work is exactly the thing that crashed.' },
      { k: 'text', md: 'Requirements for an E-stop:\n\n- A **normally closed** contact: if the cable breaks, the circuit opens and the robot stops\n- A **latching** button: it stays pressed until twisted free\n- **Reachable** and clearly visible (red button, yellow background)\n- After reset, motion **must not resume on its own**' },
      { k: 'callout', tone: 'warn', md: 'The **normally closed** logic is not a detail. With a normally open contact a broken cable means the E-stop will never work again — and nobody notices until it is needed. Faults must fail **towards safety**.' },
      { k: 'text', md: 'Software layers sit **on top of** the hardware E-stop, not instead of it:\n\n- **Watchdog timer** — if the main loop does not check in on time, the motors stop\n- **Speed limit** — slower near people\n- **Torque limit** — do not keep pushing on a collision\n- **Workspace limit** — do not leave the designated area' },
      { k: 'callout', tone: 'tip', md: 'A **watchdog** is the cheapest software safety net. The main loop pets it regularly; if it hangs or enters an infinite loop, the watchdog times out, stops the motors and resets the controller.' },
      { k: 'text', md: 'Testing: try the E-stop **before every use**, and test extreme cases regularly — what happens on a power cut, a broken cable, a flat battery. A safety system you do not test is not a safety system.' },
    ],
    quiz: [
      { k: 'single', q: 'Why must an E-stop work independently of software?', opts: ['It is faster', 'Because if the software has crashed, that is exactly what will not work', 'It is cheaper'], answer: 1, why: 'A relay or contactor physically cuts power to the motors.' },
      { k: 'single', q: 'Why is an E-stop contact normally closed?', opts: ['Less current', 'So the robot also stops on a broken cable: the fault fails towards safety', 'Faster switching'], answer: 1, why: 'With a normally open contact a broken cable would silently disable the button.' },
      { k: 'single', q: 'What does a watchdog timer do?', opts: ['Logs', 'Stops the motors if the main loop does not check in on time', 'Measures speed'], answer: 1, why: 'It is the software safety net for a hang or an infinite loop.' },
      { k: 'single', q: 'What should happen after an E-stop is released?', opts: ['Resume immediately', 'Motion must not resume on its own', 'The program restarts'], answer: 1, why: 'An unexpected restart is itself a source of accidents.' },
      { k: 'single', q: 'When must the E-stop be tested?', opts: ['Annually', 'Before every use, and regularly with extreme cases', 'Never'], answer: 1, why: 'A safety system you do not test is not a safety system.' },
    ],
    note: {
      summary: ['Safety is part of the build, not a feature added later.', 'The E-stop must cut power in hardware, independently of software.', 'A normally closed contact also stops on a broken cable.', 'Latching, clearly visible button; no automatic restart after reset.', 'Software layers on top: watchdog, speed, torque and workspace limits.', 'Test the E-stop before every use.'],
      terms: [{ term: 'emergency stop (E-stop)', def: 'A hardware switch cutting power to the drives.' }, { term: 'normally closed', def: 'A contact closed at rest, so a break stops the machine.' }, { term: 'watchdog', def: 'A timer that shuts the system down if it hangs.' }],
    },
  },
];
