import type { Day } from '../../types';

/** ROBOTICS track, days 13-19. */
export const roboticsEnD: Day[] = [
  {
    day: 13,
    title: 'Anatomy of a robot arm',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'A robot arm is made of **joints** and the **links** between them. The number of joints gives its degrees of freedom: how many independent ways it can move.' },
      { k: 'callout', tone: 'key', md: 'Placing an object fully in space takes **six** degrees of freedom: three for position (x, y, z) and three for orientation (roll, pitch, yaw). That is why most industrial arms have six joints.' },
      { k: 'text', md: 'Two kinds of joint:\n\n- **Revolute** — changes an angle. The common one; cheap, rugged, wide range of motion.\n- **Prismatic** — changes a length, like a telescope. More accurate, but costlier and sensitive to dirt.' },
      { k: 'text', md: 'Three typical layouts:\n\n- **Cartesian** — three linear axes, like a 3D printer. Simple maths, but it takes a lot of room.\n- **SCARA** — two vertical-axis revolute joints plus a lift. Fast in the horizontal plane; the favourite of assembly lines.\n- **Articulated** — all joints revolute, like a human arm. The most flexible, the hardest to compute.' },
      { k: 'callout', tone: 'warn', md: 'Every joint **multiplies the error of the one before it**. If the first joint is half a degree off, at the end of a one-metre arm that is nearly a centimetre. That is why the joints nearest the base need the most accurate encoders.' },
      { k: 'text', md: 'The **workspace** is the volume the arm can reach. It is not a sphere: there is an unreachable bubble around the base, and at the outer edge the fully extended arm can barely carry a load. The practical workspace is much smaller than the one on the datasheet.' },
    ],
    quiz: [
      { k: 'single', q: 'How many degrees of freedom place an object fully in space?', opts: ['3', '6', '12'], answer: 1, why: 'Three for position, three for orientation. That is why most industrial arms have six joints.' },
      { k: 'single', q: 'What is the difference between revolute and prismatic joints?', opts: ['Revolute changes an angle, prismatic changes a length', 'Revolute is faster', 'No difference'], answer: 0, why: 'A revolute joint is cheaper with a wider range; a prismatic one is more accurate but costlier.' },
      { k: 'single', q: 'Which layout is fastest for assembly in a horizontal plane?', opts: ['Cartesian', 'SCARA', 'Articulated'], answer: 1, why: 'SCARA is stiff vertically and fast in the plane, which is why assembly lines use it.' },
      { k: 'single', q: 'Why do joints near the base need the most accurate encoders?', opts: ['Because the load is higher there', 'Because their error is amplified along the whole arm', 'Because it is hotter there'], answer: 1, why: 'Half a degree over a one-metre arm is nearly a centimetre at the tip.' },
      { k: 'single', q: 'Why is the practical workspace smaller than the datasheet figure?', opts: ['There is an unreachable bubble near the base, and the edges barely carry load', 'Because it is measured badly', 'It is not smaller'], answer: 0, why: 'Both the inner bubble and the weak fully-extended edge remove usable volume.' },
    ],
    note: {
      summary: ['An arm is joints and links; the joint count gives the degrees of freedom.', 'Full placement in space takes six degrees of freedom.', 'Revolute: cheap, wide range. Prismatic: accurate, costly.', 'Layouts: Cartesian, SCARA, articulated.', 'Every joint multiplies the error of the one before it.', 'The practical workspace is smaller than the nominal one.'],
      terms: [{ term: 'degree of freedom', def: 'The number of independent directions of motion.' }, { term: 'SCARA', def: 'A layout with two vertical revolute axes, fast in-plane.' }, { term: 'workspace', def: 'The volume an arm can reach.' }],
    },
  },
  {
    day: 14,
    title: 'Grippers and end effectors',
    minutes: 22,
    lesson: [
      { k: 'text', md: 'The tool at the end of the arm is the **end effector**. It decides what the robot is for: a gripper, a suction cup, a welding torch, a camera or a screwdriver.' },
      { k: 'text', md: 'The three common gripper types:\n\n- **Parallel jaw** — two fingers closing on each other. Simple, strong, positions well. For rigid objects.\n- **Vacuum** — a suction cup. Perfect for smooth flat surfaces: glass, sheet metal, boxes. Useless on dust or rough texture.\n- **Soft gripper** — flexible, air-inflated fingers. For fragile and irregular objects: fruit, eggs.' },
      { k: 'callout', tone: 'key', md: '**Force control** matters more than position control in a gripper. Grip an egg by position and you either crush it or drop it. Grip it by force and every egg size holds equally well.' },
      { k: 'text', md: 'To grasp something you need three things:\n\n1. **Where** the object is (camera or fixed position)\n2. **From where** to approach (grasp point and direction)\n3. **How hard** to squeeze' },
      { k: 'callout', tone: 'warn', md: 'The gripper weight **counts against the arm payload**. On a 3 kg arm, a 1.5 kg gripper leaves 1.5 kg of useful payload. Beginners forget this routinely, and then the arm shakes or faults out.' },
      { k: 'callout', tone: 'tip', md: 'In most industrial tasks the gripper is not the hard part — **finding the object and presenting it repeatably** is. A well-designed feed tray that always holds the part the same way beats an expensive camera system.' },
    ],
    quiz: [
      { k: 'single', q: 'What is an end effector?', opts: ['The base of the arm', 'The tool at the end of the arm that does the work', 'The controller'], answer: 1, why: 'Gripper, suction cup, welding torch, camera — it decides what the robot is for.' },
      { k: 'single', q: 'When does a vacuum gripper fail?', opts: ['On smooth glass', 'On dusty or rough surfaces', 'On a flat box'], answer: 1, why: 'A suction cup needs an airtight seal. Dust and texture let it leak.' },
      { k: 'single', q: 'Why grip an egg by force rather than position?', opts: ['It is faster', 'Because by position you either crush it or drop it', 'It uses less energy'], answer: 1, why: 'Force control gives the same squeeze for every egg size. Position control is sensitive to the object size.' },
      { k: 'single', q: 'How does gripper weight affect payload?', opts: ['It does not', 'It subtracts from the useful payload', 'It increases it'], answer: 1, why: 'On a 3 kg arm, a 1.5 kg gripper leaves 1.5 kg of useful payload.' },
      { k: 'single', q: 'What is the hard part of most industrial grasping tasks?', opts: ['Building the gripper', 'Finding the object and presenting it repeatably', 'Programming the arm'], answer: 1, why: 'A good feed tray that always holds the part the same way often replaces an expensive camera system.' },
    ],
    note: {
      summary: ['The end effector decides what the robot is for.', 'Parallel jaw: rigid objects. Vacuum: smooth surfaces. Soft: fragile items.', 'Force control matters more than position control in a gripper.', 'Grasping needs: where it is, how to approach, how hard to squeeze.', 'Gripper weight subtracts from the useful payload.', 'The hard part is repeatable presentation, not the gripper.'],
      terms: [{ term: 'end effector', def: 'The working tool mounted at the end of the arm.' }, { term: 'force control', def: 'Regulating grip force instead of position.' }, { term: 'payload', def: 'The mass liftable on top of the gripper weight.' }],
    },
  },
  {
    day: 15,
    title: 'Control: open and closed loop',
    minutes: 22,
    lesson: [
      { k: 'text', md: '**Open-loop** control issues a command and hopes. **Closed-loop** control measures the result and corrects from the difference. That distinction is the whole of control engineering in robotics.' },
      { k: 'text', md: '**Open loop**: "drive forward for 2 seconds". On a softer carpet, or with a draining battery, you travel a different distance. No feedback, no correction.\n\n**Closed loop**: "travel 50 cm". The encoder measures the distance covered and the controller drives until the difference is zero.' },
      { k: 'callout', tone: 'key', md: 'A closed loop has four parts: **setpoint** (what you want), **measurement** (what you have), **error** (the difference) and **actuation** (what you do about it). Every controller is a relationship between those four.' },
      { k: 'code', lang: 'py', src: 'setpoint = 50.0       # cm\nmeasured = 0.0\n\nwhile True:\n    measured = encoder_distance()\n    error = setpoint - measured\n    if abs(error) < 0.5:\n        motor(0)\n        break\n    motor(0.4 if error > 0 else -0.4)', explain: 'This is the simplest closed loop: a bang-bang controller. It works, but it oscillates around the target because it never slows down on approach.' },
      { k: 'callout', tone: 'warn', md: 'The **deadband** (0.5 cm here) is not a luxury, it is a necessity. Without it the robot switches back and forth around the target forever, and the motor wears out fast.' },
      { k: 'text', md: 'When is open loop enough? When the disturbance is small and accuracy is not critical: switching a lamp, opening a valve. Motion almost always needs a closed loop, because traction, load and battery voltage keep changing.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the difference between open and closed loop?', opts: ['Closed loop measures the result and corrects', 'Open loop is always faster', 'No difference'], answer: 0, why: 'Open loop issues a command and never checks. Closed loop acts on the measured error.' },
      { k: 'single', q: 'What is the error signal?', opts: ['Sensor noise', 'The difference between setpoint and measurement', 'The motor current'], answer: 1, why: 'It is the input to control: the controller computes actuation from it.' },
      { k: 'single', q: 'What is wrong with a bang-bang controller?', opts: ['Too slow', 'It oscillates around the target because it never slows on approach', 'It never reaches the target'], answer: 1, why: 'It drives at full power until it overshoots, then reverses. That makes it oscillate.' },
      { k: 'single', q: 'What is the deadband for?', opts: ['Speed', 'Preventing endless switching around the target', 'Measuring distance'], answer: 1, why: 'Without it the motor switches constantly and wears out quickly.' },
      { k: 'order', q: 'In what order does one control cycle run?', items: ['Actuate the motor', 'Compute the error', 'Measure'], correct: [2, 1, 0], why: 'Measure, compute error, actuate — then start again.' },
    ],
    note: {
      summary: ['Open loop: a command with no feedback. Closed loop: measure and correct.', 'Four parts: setpoint, measurement, error, actuation.', 'A bang-bang controller works but oscillates around the target.', 'A deadband prevents endless switching.', 'Motion almost always needs a closed loop.'],
      terms: [{ term: 'setpoint', def: 'The value you want to reach.' }, { term: 'error signal', def: 'The difference between setpoint and measurement.' }, { term: 'deadband', def: 'A tolerance band inside which no action is taken.' }],
    },
  },
  {
    day: 16,
    title: 'The P controller',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'The **P (proportional) controller** is the simplest sensible answer: actuation is **proportional to the error**. Big error, big power; small error, a careful approach.' },
      { k: 'code', lang: 'py', src: 'Kp = 0.02             # proportional gain\n\nwhile True:\n    error = setpoint - encoder_distance()\n    u = Kp * error\n    u = max(-1.0, min(1.0, u))     # clamp to the motor range\n    motor(u)\n    if abs(error) < 0.5:\n        motor(0); break', explain: '`Kp` is the single number to tune. Clamping is mandatory: the motor cannot give more than 1.0, and without the clamp the maths produces meaningless values.' },
      { k: 'callout', tone: 'key', md: 'Tuning `Kp`:\n\n- **too small** — slow to arrive, and may stall short of the target\n- **right** — fast approach, barely any overshoot\n- **too large** — overshoots, oscillates, eventually goes unstable' },
      { k: 'text', md: 'The practical method: start small and **double** it until the system just begins to overshoot. Then halve it. That is step one of tuning any controller.' },
      { k: 'callout', tone: 'warn', md: 'A pure P controller leaves a **steady-state error**. When the error is small the actuation is small too — and at some point it is no longer enough to overcome friction or gravity. The robot stops 2 cm short of the target and stays there forever.' },
      { k: 'text', md: 'Steady-state error is a fundamental limit of P control, not a tuning mistake. A larger `Kp` reduces it but brings instability. The answer is the **I term**, which is the next day.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the P controller proportional to?', opts: ['Time', 'The actuation is proportional to the error', 'Speed'], answer: 1, why: 'A big error gives a big actuation and a small error a small one, which is what slows it near the target.' },
      { k: 'single', q: 'What happens with too large a `Kp`?', opts: ['Slow arrival', 'It overshoots, oscillates, and eventually goes unstable', 'Nothing'], answer: 1, why: 'High gain overreacts to the error and swings the system to the other side.' },
      { k: 'single', q: 'What is steady-state error?', opts: ['Sensor noise', 'The small error a P controller cannot beat because the actuation is too small', 'A software bug'], answer: 1, why: 'At a small error the actuation is not enough to overcome friction. The robot stops short.' },
      { k: 'single', q: 'What is the practical way to tune `Kp`?', opts: ['Random trial', 'Start small, double until overshoot, then halve', 'Always 1.0'], answer: 1, why: 'That is the standard first step in controller tuning, and it works on every system.' },
      { k: 'single', q: 'Why must the actuation be clamped?', opts: ['For looks', 'Because the motor cannot exceed its range', 'It need not be'], answer: 1, why: 'Without a clamp the maths produces meaningless values, and later the integral term winds up as well.' },
    ],
    note: {
      summary: ['A P controller actuates in proportion to the error.', 'One tunable number: `Kp`.', 'Too small: slow. Too large: oscillation and instability.', 'Tuning: double until overshoot, then halve.', 'Clamp the actuation to the motor range.', 'Pure P leaves a steady-state error — a fundamental limit.'],
      terms: [{ term: 'proportional gain (Kp)', def: 'The multiplier between error and actuation.' }, { term: 'steady-state error', def: 'The residual error the P term cannot overcome.' }, { term: 'overshoot', def: 'Passing the target before settling back.' }],
    },
  },
  {
    day: 17,
    title: 'Tuning a PID',
    minutes: 26,
    lesson: [
      { k: 'text', md: 'A PID has three terms, each looking at a different aspect of the error: the **present**, the **past** and the **future**.' },
      { k: 'text', md: '- **P (proportional)** — reacts to the current error. It does most of the work.\n- **I (integral)** — looks at accumulated past error. It removes the steady-state error.\n- **D (derivative)** — looks at how fast the error is changing. It brakes before the target and reduces overshoot.' },
      { k: 'code', lang: 'py', src: 'Kp, Ki, Kd = 0.02, 0.001, 0.005\nintegral = 0.0\nprev_error = 0.0\ndt = 0.02             # 50 Hz\n\nwhile True:\n    error = setpoint - encoder_distance()\n    integral += error * dt\n    integral = max(-500, min(500, integral))     # anti-windup\n    derivative = (error - prev_error) / dt\n    u = Kp*error + Ki*integral + Kd*derivative\n    motor(max(-1.0, min(1.0, u)))\n    prev_error = error', explain: '`dt` is fixed and known — which matters, because with a varying cycle time the I and D terms behave unpredictably.' },
      { k: 'callout', tone: 'warn', md: '**Integral windup** is the most common PID bug. When the motor is saturated and the error persists, the integral grows without bound. By the time you reach the target the accumulated integral keeps driving, causing a large overshoot. Clamping is mandatory.' },
      { k: 'callout', tone: 'key', md: 'The tuning order:\n\n1. `Ki = 0`, `Kd = 0`. Tune `Kp` to the edge of overshoot, then back off.\n2. Raise `Kd` until the overshoot disappears. Carefully: the D term amplifies sensor noise.\n3. Raise `Ki` until the steady-state error disappears. `Ki` is always the smallest of the three.' },
      { k: 'text', md: 'The D term is noise sensitive because it takes a difference. With a noisy sensor the derivative jumps and the motor starts to judder. The remedies: filter the measurement, or drop the D term — plenty of systems work perfectly as a **PI** controller.' },
    ],
    quiz: [
      { k: 'single', q: 'Which term removes the steady-state error?', opts: ['P', 'I', 'D'], answer: 1, why: 'The integral term accumulates the error and keeps raising the actuation until it is gone.' },
      { k: 'single', q: 'What does the D term do?', opts: ['Accumulates', 'Looks at the rate of change and brakes before the target', 'Multiplies the error'], answer: 1, why: 'When the error falls quickly the D term pushes back, reducing overshoot.' },
      { k: 'single', q: 'What is integral windup?', opts: ['A sensor fault', 'The integral grows without bound under saturation and causes a big overshoot later', 'Motor overheating'], answer: 1, why: 'That is why the integral must be clamped. It is the most common PID bug in practice.' },
      { k: 'order', q: 'In what order do you tune a PID?', items: ['Kd against overshoot', 'Ki against steady-state error', 'Kp to the edge of overshoot'], correct: [2, 0, 1], why: 'Kp first, then Kd, then Ki. Ki is always the smallest of the three.' },
      { k: 'single', q: 'Why is the D term noise sensitive?', opts: ['Because it sums errors', 'Because it takes a difference, which amplifies noise jitter', 'Because it is slow'], answer: 1, why: 'Small fast noise gives a large derivative. The remedy is filtering, or a plain PI controller.' },
    ],
    note: {
      summary: ['P looks at the present, I at the past, D at the future.', 'P does most of the work; I removes steady-state error; D brakes before the target.', 'Keep `dt` fixed and known.', 'Clamp the integral against windup.', 'Tuning order: Kp, Kd, Ki. Ki is the smallest.', 'The D term is noise sensitive; many systems work fine as PI.'],
      terms: [{ term: 'PID', def: 'A controller with proportional, integral and derivative terms.' }, { term: 'windup', def: 'An integral term growing without bound under saturation.' }, { term: 'PI controller', def: 'A PID without the D term; common on noisy systems.' }],
    },
  },
  {
    day: 18,
    title: 'Line following',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Line following is the textbook control problem: a simple sensor, a simple goal, and every tuning mistake shows up immediately in how the robot behaves.' },
      { k: 'text', md: 'The sensor is usually an **infrared array**: five to eight LED and photodiode pairs under the robot. A black line absorbs the light, a white floor reflects it. Each sensor gives a number between 0 and 1.' },
      { k: 'code', lang: 'py', src: '# Weighted average: where is the line relative to the array?\nweights = [-3, -2, -1, 0, 1, 2, 3]\n\ndef line_position(values):\n    total = sum(values)\n    if total < 0.1:\n        return None                  # line lost\n    return sum(w*v for w, v in zip(weights, values)) / total', explain: 'A weighted average gives a **continuous** position, not just which sensor sees the line. That is what makes the control smooth instead of stepped.' },
      { k: 'callout', tone: 'key', md: 'The position is the error, and the setpoint is zero (line in the middle). From there it is the usual PID:\n\n`u = Kp*error + Kd*(error - previous)`\n\n`left = base - u`, `right = base + u`' },
      { k: 'callout', tone: 'warn', md: '**Calibration** is not optional. Sensors differ, light changes, and floor brightness varies by room. At startup, drag the robot across the line, record the minimum and maximum per sensor, and normalise against that.' },
      { k: 'text', md: 'What should you do when the line is lost? The proven answer: **remember the last known direction** and turn that way until you find it again. Carrying straight on loses it for good.' },
      { k: 'callout', tone: 'tip', md: 'Speed and `Kp` are linked: what works well slowly will oscillate at speed. Competition robots therefore **slow down in corners** — they compute speed from the magnitude of the error.' },
    ],
    quiz: [
      { k: 'single', q: 'Why is a weighted average better than "which sensor sees it"?', opts: ['Faster', 'It gives a continuous position, which makes the control smooth', 'It needs fewer sensors'], answer: 1, why: 'A stepped signal gives stepped steering. A continuous value gives smooth line following.' },
      { k: 'single', q: 'What is the setpoint in line following?', opts: ['The robot speed', 'Zero: the line in the middle of the array', 'The line width'], answer: 1, why: 'The error is the deviation of the line from centre, and the controller drives it to zero.' },
      { k: 'single', q: 'Why calibrate?', opts: ['Because sensors differ and light varies by room', 'Because it is faster', 'No need'], answer: 0, why: 'Without calibration the raw values are not comparable and the weighted average misleads.' },
      { k: 'single', q: 'What should you do when the line is lost?', opts: ['Carry straight on', 'Turn towards the last known direction until you find it', 'Stop'], answer: 1, why: 'Going straight only takes you further away. The last direction is the best guess.' },
      { k: 'single', q: 'Why do competition robots slow down in corners?', opts: ['To spare the motor', 'Because a Kp that works slowly oscillates at speed', 'The rules require it'], answer: 1, why: 'They compute speed from the error magnitude: big error, slower travel.' },
    ],
    note: {
      summary: ['An infrared array: the black line absorbs, the white floor reflects.', 'A weighted average gives a continuous position and smooth control.', 'Setpoint zero; error is the line deviation from centre.', 'Without calibration the raw values mislead.', 'When the line is lost, turn towards the last known direction.', 'Slow down in corners: compute speed from the error.'],
      terms: [{ term: 'weighted average', def: 'A continuous position estimate from several sensor values.' }, { term: 'calibration', def: 'Recording the min and max range of each sensor.' }, { term: 'line loss', def: 'The state where no sensor sees the line.' }],
    },
  },
  {
    day: 19,
    title: 'Obstacle avoidance',
    minutes: 24,
    lesson: [
      { k: 'text', md: 'Obstacle avoidance has two parts: **detecting** that something is there, and **deciding** which way to go round it. The second is the hard one.' },
      { k: 'text', md: 'Sensors and their limits:\n\n- **Ultrasonic** — cheap, 2 cm to 4 m. On soft or angled surfaces the sound escapes and no echo returns.\n- **Infrared distance** — fast, but surface colour matters: it spots a black object later.\n- **LiDAR** — accurate, 360 degrees, expensive. It cannot see clear glass.\n- **Bump switch** — the last safety net. Always have one on the robot.' },
      { k: 'callout', tone: 'key', md: 'Trust no single sensor. A reliable robot uses **several sensors of different kinds**: what the ultrasonic misses, the LiDAR sees, and the other way round. That is sensor fusion.' },
      { k: 'code', lang: 'py', src: '# Simple reactive avoidance\nSAFE = 30.0           # cm\n\nwhile True:\n    l, c, r = dist_left(), dist_centre(), dist_right()\n    if c > SAFE:\n        drive(0.5, 0.5)                 # road clear\n    elif l > r:\n        drive(-0.3, 0.3)                # turn left\n    else:\n        drive(0.3, -0.3)                # turn right', explain: 'This is **reactive** control: no map, no plan, only a response to the current reading. Simple, fast, and it gets stuck in corners.' },
      { k: 'callout', tone: 'warn', md: 'The classic failure of reactive avoidance is the **trap**: in a U-shaped obstacle the robot paces back and forth forever. It has no memory, so after every turn it makes the same decision again. Only mapping gets you out — which is the next day.' },
      { k: 'text', md: 'The **potential field** method is subtler: the goal attracts, obstacles repel, and the robot moves along the sum of those forces. It gives smooth paths, but it too has local minima where the robot gets stuck.' },
    ],
    quiz: [
      { k: 'single', q: 'What is the main weakness of an ultrasonic sensor?', opts: ['It is slow', 'No echo returns from soft or angled surfaces', 'It is expensive'], answer: 1, why: 'The sound escapes off an angled surface and soft material absorbs it. The robot then "sees" a clear path.' },
      { k: 'single', q: 'Why use several kinds of sensor?', opts: ['For speed', 'Because each principle fails in different situations', 'To make it more expensive'], answer: 1, why: 'What the ultrasonic misses, the LiDAR sees. Different principles do not share the same blind spots.' },
      { k: 'single', q: 'What is reactive control?', opts: ['Planning from a map', 'Responding only to the current reading, with no plan or memory', 'Replaying a recorded path'], answer: 1, why: 'Simple and fast, but with no memory it can fall into traps.' },
      { k: 'single', q: 'Why does a reactive robot get stuck in a U-shaped obstacle?', opts: ['A sensor breaks', 'It has no memory, so it makes the same decision after every turn', 'The battery runs out'], answer: 1, why: 'Only mapping, which remembers where it has already been, gets it out.' },
      { k: 'single', q: 'What is the potential field method?', opts: ['The goal attracts, obstacles repel, and the robot follows the resultant', 'Random wandering', 'A pre-planned route'], answer: 0, why: 'It gives smooth paths but has local minima where the robot can also get stuck.' },
    ],
    note: {
      summary: ['Two parts: detecting the obstacle and deciding which way round.', 'Ultrasonic: cheap, but fails on angled and soft surfaces.', 'LiDAR: accurate and 360 degrees, but blind to glass.', 'Always fit a bump switch as the last safety net.', 'Use several sensors of different kinds: sensor fusion.', 'Reactive avoidance is simple but gets stuck in U-shaped traps.', 'Potential field: the goal attracts, obstacles repel.'],
      terms: [{ term: 'reactive control', def: 'Control responding to the current reading with no plan.' }, { term: 'sensor fusion', def: 'Combining data from several different kinds of sensor.' }, { term: 'potential field', def: 'Navigation from an attracting goal and repelling obstacles.' }],
    },
  },
];
