import type { Track } from '../../types';
import { roboticsEnB } from './robotics-b';

export const roboticsEn: Track = {
  id: 'robotics',
  title: 'Robotics',
  blurb: 'Sensors, motors, kinematics, PID, path planning.',
  plannedTitles: [
    'What is a robot?',
    'Sensors: how a machine sees',
    'Motors and servos',
    'H-bridges and PWM',
    'Drivetrain and odometry',
    'Power and batteries',
    'Microcontroller basics',
    'Digital and analogue signals',
    'I2C, SPI, UART',
    'Noise and filtering',
    'Forward kinematics',
    'Inverse kinematics',
    'Anatomy of a robot arm',
    'Grippers and end effectors',
    'Control: open and closed loop',
    'The P controller',
    'Tuning a PID',
    'Line following',
    'Obstacle avoidance',
    'Mapping basics',
    'Localisation',
    'Path planning on a grid',
    'The A* algorithm',
    'State machines',
    'Behaviour trees',
    'Safety and the emergency stop',
    'Testing in simulation',
    'Choosing components',
    'Assembly and wiring',
    'Your first robot',
  ],
  days: [
    {
      day: 1,
      title: 'What is a robot?',
      minutes: 18,
      lesson: [
        {
          k: 'text',
          md: 'A robot is not a robot because it has an arm or is made of metal. It is a robot because it does three things one after another, over and over: **sense — decide — act**. We call that the control loop.',
        },
        {
          k: 'callout',
          tone: 'key',
          md: 'Sense → decide → act → sense → … This loop can run a hundred times a second. Every robot, from a vacuum cleaner to a Mars rover, does exactly this.',
        },
        {
          k: 'text',
          md: 'Three groups of parts serve those three steps:\n\n- **Sensors** — the robot senses: rangefinder, camera, gyroscope, bump switch.\n- **Controller** — the brain: usually a microcontroller running your code.\n- **Actuators** — the muscles: motors, servos, solenoids.',
        },
        {
          k: 'text',
          md: 'And there is a fourth that beginners always underestimate: **power**. The finest code is useless if the motor drags the voltage down and the controller reboots.',
        },
        { k: 'robot', scene: 'flat' },
        {
          k: 'text',
          md: 'The simulator above holds a differential-drive rover: two driven wheels, independent of each other. Both forward and it goes straight. One only and it turns. This is the simplest drivetrain there is, which is exactly why everyone starts here.',
        },
        {
          k: 'callout',
          tone: 'tip',
          md: 'Before you build anything, draw the loop: what you sense, what decision comes out of it, what you move. Without those three you do not have a robot yet — you have a radio-controlled car.',
        },
      ],
      quiz: [
        {
          k: 'order',
          q: 'In what order does the control loop run?',
          items: ['Act', 'Sense', 'Decide'],
          correct: [1, 2, 0],
          why: 'Data has to be gathered first, the decision comes out of it, and only then does the machine move. Then it all starts again.',
        },
        {
          k: 'single',
          q: 'Which part belongs to the sensing step?',
          opts: ['A servo', 'An ultrasonic rangefinder', 'An H-bridge'],
          answer: 1,
          why: 'A rangefinder is a sensor: it gathers data about the surroundings. A servo is an actuator, and an H-bridge drives a motor.',
        },
        {
          k: 'single',
          q: 'What defines differential drive?',
          opts: [
            'One motor drives, another steers',
            'Two independently driven wheels',
            'Four wheels, all steerable',
          ],
          answer: 1,
          why: 'In differential drive the difference in speed between the two driven wheels is what turns the robot — there is no separate steering mechanism. That is why it is so simple to build.',
        },
        {
          k: 'multi',
          q: 'Without which two is there no working robot?',
          opts: ['Sensor', 'Bluetooth', 'Actuator', 'Display'],
          answers: [0, 2],
          why: 'Without a sensor it is blind, without an actuator it is helpless. Bluetooth and a display are conveniences — useful, but not what makes a robot a robot.',
        },
      ],
      note: {
        summary: [
          'A robot is defined by its control loop: sense → decide → act, repeated continuously.',
          'Sensor = sense, controller = brain, actuator = muscle. You need all three.',
          'Power is the fourth, often underestimated element: a voltage sag on motor start reboots the controller.',
          'Differential drive steers with two independent wheels — no separate steering mechanism.',
          'Without all three steps it is not a robot but a remote-controlled vehicle.',
        ],
        terms: [
          { term: 'control loop', def: 'The sense-decide-act cycle a robot repeats continuously.' },
          { term: 'sensor', def: 'A part that reports data about the surroundings or the robot itself.' },
          { term: 'actuator', def: 'A part that produces movement or a physical effect.' },
          { term: 'differential drive', def: 'Steering achieved with two independently driven wheels.' },
        ],
      },
    },
    ...roboticsEnB,
  ],
};
